/**
 * Question bank chunk — part of questions.generated.ts. DO NOT EDIT BY HAND.
 */
import type { Question } from "../content";
import { src } from "./shared";

export const citizenshipA: Question[] = [
  {
    id: "ctz-e-001",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: {
      en: "When you apply for Canadian citizenship, what will officials do with your application?",
    },
    options: [
      {
        en: "Check your status, verify that you are not prohibited from applying, and ensure that you meet the requirements",
      },
      { en: "Approve it automatically without any checks" },
      { en: "Ask your employer to decide the outcome" },
      { en: "Send it to another country for review" },
    ],
    answerIndex: 0,
    explanation: {
      en: "When you apply, officials check your status, verify you are not prohibited from applying, and ensure you meet the requirements.",
    },
    source: src("Applying for Citizenship"),
  },
  {
    id: "ctz-e-002",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "About how long may your citizenship application take?" },
    options: [
      { en: "A few days" },
      { en: "Several months" },
      { en: "About one week" },
      { en: "Less than an hour" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The guide notes that your application may take several months to process.",
    },
    source: src("Applying for Citizenship"),
  },
  {
    id: "ctz-e-003",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "While your application is being processed, what should you make sure of?" },
    options: [
      { en: "That you visit the Call Centre every week" },
      { en: "That you change your phone number every month" },
      { en: "That the Call Centre always has your correct address" },
      { en: "That you write to the Call Centre every day" },
    ],
    answerIndex: 2,
    explanation: {
      en: "You should ensure the Call Centre always has your correct address while your application is being processed.",
    },
    source: src("Applying for Citizenship"),
  },
  {
    id: "ctz-e-004",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: {
      en: "What is one thing the guide recommends you do to prepare for the citizenship test?",
    },
    options: [
      { en: "Memorize a dictionary word by word" },
      { en: "Travel outside Canada for a month" },
      { en: "Stop practising entirely" },
      { en: "Study this guide" },
    ],
    answerIndex: 3,
    explanation: { en: "The guide's preparation list begins with studying this guide." },
    source: src("Applying for Citizenship"),
  },
  {
    id: "ctz-e-005",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: {
      en: "Whom does the guide suggest asking to help you practise answering questions about Canada?",
    },
    options: [
      { en: "A friend or family member" },
      { en: "A travel agent" },
      { en: "A sports coach" },
      { en: "A taxi driver" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The guide suggests asking a friend or family member to help you practise answering questions about Canada.",
    },
    source: src("Applying for Citizenship"),
  },
  {
    id: "ctz-e-006",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: {
      en: "According to the guide, where can you call to get information on citizenship classes?",
    },
    options: [
      { en: "A movie theatre or a shopping mall" },
      {
        en: "A local school or school board, a college, a community centre, or an organization that provides services to immigrants",
      },
      { en: "A car dealership" },
      { en: "A fast-food restaurant" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The guide says to call a local school or school board, a college, a community centre or an organization serving immigrants for citizenship class information.",
    },
    source: src("Applying for Citizenship"),
  },
  {
    id: "ctz-e-007",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "Who offers free English or French language classes?" },
    options: [
      { en: "Local restaurants" },
      { en: "Private airlines" },
      { en: "The Government of Canada" },
      { en: "Sports clubs" },
    ],
    answerIndex: 2,
    explanation: {
      en: "English or French language classes are offered free of charge by the Government of Canada.",
    },
    source: src("Applying for Citizenship"),
  },
  {
    id: "ctz-e-008",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "Is the citizenship test always a written test?" },
    options: [
      { en: "Yes — it is always a written test" },
      { en: "No — it is always an interview" },
      { en: "Yes — and it is always taken online" },
      { en: "No — it is usually a written test, but it could be an interview" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The citizenship test is usually a written test, but it could be an interview.",
    },
    source: src("Applying for Citizenship"),
  },
  {
    id: "ctz-e-009",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "What are the two basic requirements you are tested on for citizenship?" },
    options: [
      {
        en: "Knowledge of Canada and of the rights and responsibilities of citizenship, and adequate knowledge of English or French",
      },
      { en: "Knowledge of world geography and advanced mathematics" },
      { en: "Knowledge of car repair and cooking skills" },
      { en: "Knowledge of sports history and music theory" },
    ],
    answerIndex: 0,
    explanation: {
      en: "You are tested on knowledge of Canada and of the rights and responsibilities of citizenship, and on adequate knowledge of English or French.",
    },
    source: src("Applying for Citizenship"),
  },
  {
    id: "ctz-e-010",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "Adult applicants who are 55 years of age and over…" },
    options: [
      { en: "Must write the test twice" },
      { en: "Do not need to write the citizenship test" },
      { en: "Must take the test in another country" },
      { en: "Must score higher than younger applicants" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Adult applicants 55 years of age and over do not need to write the citizenship test.",
    },
    source: src("Applying for Citizenship"),
  },
  {
    id: "ctz-e-011",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: {
      en: "If you pass the test and meet all the other requirements, what will you receive?",
    },
    options: [
      { en: "A driver's licence" },
      { en: "A passport on the spot" },
      { en: "A Notice to Appear to Take the Oath of Citizenship" },
      { en: "A tax refund" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Passing applicants receive a Notice to Appear to Take the Oath of Citizenship.",
    },
    source: src("Applying for Citizenship"),
  },
  {
    id: "ctz-e-012",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "What does the Notice to Appear to Take the Oath of Citizenship tell you?" },
    options: [
      { en: "Your test score and ranking" },
      { en: "The names of the other applicants" },
      { en: "Your new health card number" },
      { en: "The date, time and place of your citizenship ceremony" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The Notice tells you the date, time and place of your citizenship ceremony.",
    },
    source: src("Applying for Citizenship"),
  },
  {
    id: "ctz-e-013",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "What do you receive at the citizenship ceremony?" },
    options: [
      { en: "Your Canadian Citizenship Certificate" },
      { en: "A provincial health card" },
      { en: "A library card" },
      { en: "A fishing licence" },
    ],
    answerIndex: 0,
    explanation: { en: "At the ceremony you receive your Canadian Citizenship Certificate." },
    source: src("Applying for Citizenship"),
  },
  {
    id: "ctz-e-014",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "Whom are you encouraged to bring to your citizenship ceremony?" },
    options: [
      { en: "Only your lawyer" },
      { en: "Your family and friends" },
      { en: "Only government officials" },
      { en: "No guests at all" },
    ],
    answerIndex: 1,
    explanation: {
      en: "You are encouraged to bring your family and friends to celebrate the occasion.",
    },
    source: src("Applying for Citizenship"),
  },
  {
    id: "ctz-e-015",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "What do new citizens take at the citizenship ceremony?" },
    options: [
      { en: "A driving test" },
      { en: "A first-aid course" },
      { en: "The Oath of Citizenship" },
      { en: "A swimming test" },
    ],
    answerIndex: 2,
    explanation: { en: "At the ceremony, new citizens take the Oath of Citizenship." },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "ctz-e-016",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "To whom do you swear allegiance in the Oath of Citizenship?" },
    options: [
      { en: "The Prime Minister of Canada" },
      { en: "The Premier of Ontario" },
      { en: "The Mayor of Ottawa" },
      { en: "His Majesty King Charles the Third" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The Oath pledges to be faithful and bear true allegiance to His Majesty King Charles the Third.",
    },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "ctz-e-017",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "In the Oath, what do you promise to “faithfully observe”?" },
    options: [
      { en: "The laws of Canada" },
      { en: "The laws of the United States" },
      { en: "Only the traffic laws of your province" },
      { en: "The rules of your workplace" },
    ],
    answerIndex: 0,
    explanation: { en: "The Oath promises that you will faithfully observe the laws of Canada." },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "ctz-e-018",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "Complete the line from the Oath: “I will be faithful and ___.”" },
    options: [
      { en: "pay higher taxes" },
      { en: "bear true allegiance" },
      { en: "serve in the army" },
      { en: "leave the country" },
    ],
    answerIndex: 1,
    explanation: { en: "The Oath's words are “That I will be faithful and bear true allegiance.”" },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "ctz-e-019",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "In Canada, loyalty is professed to…" },
    options: [
      { en: "A written constitution" },
      { en: "A national flag" },
      { en: "A person who represents all Canadians" },
      { en: "A piece of land" },
    ],
    answerIndex: 2,
    explanation: { en: "In Canada we profess loyalty to a person who represents all Canadians." },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "ctz-e-020",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "In Canada, we do NOT profess loyalty to a document such as…" },
    options: [
      { en: "The Sovereign" },
      { en: "His Majesty the King" },
      { en: "A person who represents all Canadians" },
      { en: "A constitution" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Loyalty is professed to a person, not to a document such as a constitution.",
    },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "ctz-e-021",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "According to the Oath, what does the Constitution recognize and affirm?" },
    options: [
      { en: "The Aboriginal and treaty rights of First Nations, Inuit and Métis peoples" },
      { en: "The rights of all foreign visitors" },
      { en: "The rights of corporations only" },
      { en: "The rights of political parties" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The Oath refers to the Constitution “which recognizes and affirms the Aboriginal and treaty rights of First Nations, Inuit and Métis peoples.”",
    },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "ctz-e-022",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "Which three peoples are named in the Oath of Citizenship?" },
    options: [
      { en: "English, Scottish and Irish" },
      { en: "First Nations, Inuit and Métis" },
      { en: "French, German and Italian" },
      { en: "Chinese, Ukrainian and Dutch" },
    ],
    answerIndex: 1,
    explanation: { en: "The Oath names the First Nations, Inuit and Métis peoples." },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "ctz-e-023",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "How does the Oath of Citizenship end?" },
    options: [
      { en: "“And never leave Canada.”" },
      { en: "“And serve in the military.”" },
      { en: "“And fulfil my duties as a Canadian citizen.”" },
      { en: "“And pay taxes forever.”" },
    ],
    answerIndex: 2,
    explanation: { en: "The Oath ends with “And fulfil my duties as a Canadian citizen.”" },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "ctz-e-024",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "The Oath begins “I swear (or affirm)”. What does this mean?" },
    options: [
      { en: "You must swear on a holy book" },
      { en: "Only affirming is allowed" },
      { en: "Swearing is not permitted" },
      { en: "You may either swear the Oath or affirm it" },
    ],
    answerIndex: 3,
    explanation: { en: "The opening words give you the choice to swear or to affirm." },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "ctz-e-025",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "What title is given to King Charles the Third in the Oath?" },
    options: [
      { en: "King of Canada" },
      { en: "King of England" },
      { en: "King of the Commonwealth" },
      { en: "King of Ontario" },
    ],
    answerIndex: 0,
    explanation: { en: "The Oath addresses him as “King Charles the Third, King of Canada.”" },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "ctz-e-026",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: {
      en: "The updated Oath of Citizenship refers to the Aboriginal and treaty rights of…",
    },
    options: [
      { en: "People in other countries" },
      { en: "Indigenous peoples in Canada" },
      { en: "Only new immigrants" },
      { en: "Only elected officials" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The Oath now refers to the Aboriginal and treaty rights of Indigenous peoples in Canada.",
    },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "ctz-e-027",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "Canada is known around the world as…" },
    options: [
      { en: "A weak and divided country" },
      { en: "A new and unknown country" },
      { en: "A strong and free country" },
      { en: "A closed and isolated country" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The guide opens by describing Canada as known around the world as a strong and free country.",
    },
    source: src("Who We Are"),
  },
  {
    id: "ctz-e-028",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "Canadians are proud of…" },
    options: [
      { en: "Having no traditions" },
      { en: "Copying other countries" },
      { en: "Avoiding all change" },
      { en: "Their unique identity" },
    ],
    answerIndex: 3,
    explanation: { en: "Canadians are proud of their unique identity." },
    source: src("Who We Are"),
  },
  {
    id: "ctz-e-029",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "Canada has…" },
    options: [
      { en: "The oldest continuous constitutional tradition in the world" },
      { en: "The newest constitution in the world" },
      { en: "No constitutional tradition at all" },
      { en: "The shortest constitution ever written" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Canada has inherited the oldest continuous constitutional tradition in the world.",
    },
    source: src("Who We Are"),
  },
  {
    id: "ctz-e-030",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "Canada is…" },
    options: [
      { en: "The only republic in North America" },
      { en: "The only constitutional monarchy in North America" },
      { en: "A dictatorship" },
      { en: "A colony of France" },
    ],
    answerIndex: 1,
    explanation: { en: "Canada is the only constitutional monarchy in North America." },
    source: src("Who We Are"),
  },
  {
    id: "ctz-e-031",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "Complete the key phrase: “Peace, Order, and ___.”" },
    options: [
      { en: "Total Freedom" },
      { en: "Strict Control" },
      { en: "Good Government" },
      { en: "Endless Debate" },
    ],
    answerIndex: 2,
    explanation: {
      en: "“Peace, Order, and Good Government” is a key phrase in Canada's original constitutional document.",
    },
    source: src("Who We Are"),
  },
  {
    id: "ctz-e-032",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "Who are Canada's three founding peoples?" },
    options: [
      { en: "American, Mexican and Brazilian" },
      { en: "Chinese, Indian and Filipino" },
      { en: "German, Italian and Dutch" },
      { en: "Aboriginal, French and British" },
    ],
    answerIndex: 3,
    explanation: { en: "The three founding peoples are Aboriginal, French and British." },
    source: src("Who We Are"),
  },
  {
    id: "ctz-e-033",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "Which of the following is NOT one of Canada's three founding peoples?" },
    options: [{ en: "German" }, { en: "Aboriginal" }, { en: "French" }, { en: "British" }],
    answerIndex: 0,
    explanation: {
      en: "The founding peoples are Aboriginal, French and British — German is not among them.",
    },
    source: src("Who We Are"),
  },
  {
    id: "ctz-e-034",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: {
      en: "About how many Francophones — people who speak French as a first language — live in Canada?",
    },
    options: [{ en: "1 million" }, { en: "7 million" }, { en: "13 million" }, { en: "18 million" }],
    answerIndex: 1,
    explanation: { en: "There are 18 million Anglophones and 7 million Francophones in Canada." },
    source: src("Who We Are"),
  },
  {
    id: "ctz-e-035",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: {
      en: "About how many Anglophones — people who speak English as a first language — are there in Canada?",
    },
    options: [
      { en: "1 million" },
      { en: "180 million" },
      { en: "18 million" },
      { en: "800 thousand" },
    ],
    answerIndex: 2,
    explanation: { en: "Today there are 18 million Anglophones in Canada." },
    source: src("Who We Are"),
  },
  {
    id: "ctz-e-036",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: {
      en: "About how many Francophones — people who speak French as a first language — are there in Canada?",
    },
    options: [
      { en: "70 million" },
      { en: "700 thousand" },
      { en: "17 million" },
      { en: "7 million" },
    ],
    answerIndex: 3,
    explanation: { en: "Today there are 7 million Francophones in Canada." },
    source: src("Who We Are"),
  },
  {
    id: "ctz-e-037",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "Which is the only officially bilingual province?" },
    options: [{ en: "New Brunswick" }, { en: "Ontario" }, { en: "Quebec" }, { en: "Alberta" }],
    answerIndex: 0,
    explanation: { en: "New Brunswick is the only officially bilingual province." },
    source: src("Who We Are"),
  },
  {
    id: "ctz-e-038",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "Where do the majority of Francophones live?" },
    options: [
      { en: "In Alberta" },
      { en: "In the province of Quebec" },
      { en: "In British Columbia" },
      { en: "In Saskatchewan" },
    ],
    answerIndex: 1,
    explanation: { en: "The majority of Francophones live in the province of Quebec." },
    source: src("Who We Are"),
  },
  {
    id: "ctz-e-039",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "The ancestors of Aboriginal peoples are believed to have migrated from…" },
    options: [
      { en: "Europe, a few hundred years ago" },
      { en: "Africa, about a hundred years ago" },
      { en: "Asia, many thousands of years ago" },
      { en: "South America, about fifty years ago" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The ancestors of Aboriginal peoples are believed to have migrated from Asia many thousands of years ago.",
    },
    source: src("Who We Are"),
  },
  {
    id: "ctz-e-040",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "What are the three distinct groups of Aboriginal peoples?" },
    options: [
      { en: "Cree, Ojibway and Mohawk" },
      { en: "Acadians, Quebecers and Anglo-Quebecers" },
      { en: "Anglophones, Francophones and Allophones" },
      { en: "First Nations, Inuit and Métis" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The term Aboriginal peoples refers to three distinct groups: First Nations, Inuit and Métis.",
    },
    source: src("Who We Are"),
  },
  {
    id: "ctz-e-041",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "What does “Inuit” mean in the Inuktitut language?" },
    options: [
      { en: "“The people”" },
      { en: "“The hunters”" },
      { en: "“The north”" },
      { en: "“The ice”" },
    ],
    answerIndex: 0,
    explanation: { en: "“Inuit” means “the people” in the Inuktitut language." },
    source: src("Who We Are"),
  },
  {
    id: "ctz-e-042",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "The Métis speak their own dialect called…" },
    options: [{ en: "Inuktitut" }, { en: "Michif" }, { en: "Acadian French" }, { en: "Cree" }],
    answerIndex: 1,
    explanation: { en: "The Métis speak their own dialect, Michif." },
    source: src("Who We Are"),
  },
  {
    id: "ctz-e-043",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "Which group makes up the largest share of Aboriginal peoples, at about 65%?" },
    options: [{ en: "Inuit" }, { en: "Métis" }, { en: "First Nations" }, { en: "Acadians" }],
    answerIndex: 2,
    explanation: { en: "About 65% of Aboriginal people are First Nations, the largest share." },
    source: src("Who We Are"),
  },
  {
    id: "ctz-e-044",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: {
      en: "From the 1800s until the 1980s, the federal government placed many Aboriginal children in…",
    },
    options: [
      { en: "Private schools abroad" },
      { en: "Military academies" },
      { en: "Summer camps" },
      { en: "Residential schools" },
    ],
    answerIndex: 3,
    explanation: {
      en: "From the 1800s until the 1980s the federal government placed many Aboriginal children in residential schools.",
    },
    source: src("Who We Are"),
  },
  {
    id: "ctz-e-045",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "In 2008, Ottawa formally apologized to…" },
    options: [
      { en: "Former residential school students" },
      { en: "War veterans" },
      { en: "New immigrants" },
      { en: "Olympic athletes" },
    ],
    answerIndex: 0,
    explanation: {
      en: "In 2008, Ottawa formally apologized to the former students of residential schools.",
    },
    source: src("Who We Are"),
  },
  {
    id: "ctz-e-046",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "The majority of Canadians were born…" },
    options: [
      { en: "In the United States" },
      { en: "In Canada — and this has been true since the 1800s" },
      { en: "In Europe" },
      { en: "In Asia" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The majority of Canadians were born in this country, true since the 1800s.",
    },
    source: src("Who We Are"),
  },
  {
    id: "ctz-e-047",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "Why is Canada often called a “land of immigrants”?" },
    options: [
      { en: "Everyone in Canada arrived last year" },
      { en: "Nobody was born in Canada" },
      {
        en: "Over the past 200 years, millions of newcomers have helped to build and defend our way of life",
      },
      { en: "Immigration to Canada began in 2020" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Over the past 200 years, millions of newcomers have helped to build and defend Canada's way of life.",
    },
    source: src("Who We Are"),
  },
  {
    id: "ctz-e-048",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "Since the 1970s, most immigrants to Canada have come from…" },
    options: [
      { en: "European countries" },
      { en: "South American countries" },
      { en: "African countries" },
      { en: "Asian countries" },
    ],
    answerIndex: 3,
    explanation: { en: "Since the 1970s, most immigrants have come from Asian countries." },
    source: src("Who We Are"),
  },
  {
    id: "ctz-e-049",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "Poets and songwriters have hailed Canada as the…" },
    options: [
      { en: "“Great Dominion”" },
      { en: "“Great Republic”" },
      { en: "“Great Empire”" },
      { en: "“Great Colony”" },
    ],
    answerIndex: 0,
    explanation: { en: "Poets and songwriters have hailed Canada as the “Great Dominion.”" },
    source: src("Who We Are"),
  },
  {
    id: "ctz-e-050",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "The great majority of Canadians identify as…" },
    options: [{ en: "Buddhists" }, { en: "Christians" }, { en: "Muslims" }, { en: "Hindus" }],
    answerIndex: 1,
    explanation: { en: "The great majority of Canadians identify as Christians." },
    source: src("Who We Are"),
  },
  {
    id: "ctz-e-051",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "The largest religious affiliation in Canada is…" },
    options: [{ en: "Anglican" }, { en: "Baptist" }, { en: "Catholic" }, { en: "Lutheran" }],
    answerIndex: 2,
    explanation: {
      en: "The largest religious affiliation is Catholic, followed by various Protestant churches.",
    },
    source: src("Who We Are"),
  },
  {
    id: "ctz-e-052",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "In Canada, gay and lesbian Canadians enjoy…" },
    options: [
      { en: "Fewer rights than other Canadians" },
      { en: "No legal protections at all" },
      { en: "Rights only in some provinces" },
      { en: "The full protection of and equal treatment under the law" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Gay and lesbian Canadians enjoy the full protection of and equal treatment under the law.",
    },
    source: src("Who We Are"),
  },
  {
    id: "ctz-e-053",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: {
      en: "Equal treatment under the law for gay and lesbian Canadians includes access to…",
    },
    options: [
      { en: "Civil marriage" },
      { en: "Diplomatic immunity" },
      { en: "Exemption from all taxes" },
      { en: "Free university tuition" },
    ],
    answerIndex: 0,
    explanation: { en: "Equal treatment includes access to civil marriage." },
    source: src("Who We Are"),
  },
  {
    id: "ctz-e-054",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "In becoming Canadian, newcomers are expected to embrace…" },
    options: [
      { en: "Violent prejudices from their past" },
      { en: "Democratic principles such as the rule of law" },
      { en: "Extreme ideologies" },
      { en: "Hateful traditions" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Newcomers are expected to embrace democratic principles such as the rule of law.",
    },
    source: src("Who We Are"),
  },
  {
    id: "ctz-e-055",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "The Acadians are the descendants of…" },
    options: [
      { en: "British soldiers who arrived in 1900" },
      { en: "Spanish explorers from 1492" },
      { en: "French colonists who began settling in what are now the Maritime provinces in 1604" },
      { en: "Dutch traders from 1800" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The Acadians descend from French colonists who began settling in the Maritime provinces in 1604.",
    },
    source: src("Who We Are"),
  },
  {
    id: "ctz-e-056",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "What was the “Great Upheaval”?" },
    options: [
      { en: "A major earthquake in Quebec" },
      { en: "A stock market crash" },
      { en: "A famous hockey victory" },
      {
        en: "The deportation of more than two-thirds of the Acadians from their homeland between 1755 and 1763",
      },
    ],
    answerIndex: 3,
    explanation: {
      en: "The Great Upheaval was the deportation of more than two-thirds of the Acadians between 1755 and 1763.",
    },
    source: src("Who We Are"),
  },
  {
    id: "ctz-e-057",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "Anglophones (English speakers) are generally referred to as…" },
    options: [
      { en: "English Canadians" },
      { en: "French Canadians" },
      { en: "New Canadians" },
      { en: "Old Canadians" },
    ],
    answerIndex: 0,
    explanation: { en: "Anglophones are generally referred to as English Canadians." },
    source: src("Who We Are"),
  },
  {
    id: "ctz-e-058",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "In 2006, the House of Commons recognized that the Québécois form…" },
    options: [
      { en: "An independent country" },
      { en: "A nation within a united Canada" },
      { en: "A province of France" },
      { en: "A territory of the United States" },
    ],
    answerIndex: 1,
    explanation: {
      en: "In 2006 the House of Commons recognized that the Québécois form a nation within a united Canada.",
    },
    source: src("Who We Are"),
  },
  {
    id: "ctz-e-059",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: {
      en: "Which languages are the second most-spoken at home, after English, in two of Canada's biggest cities?",
    },
    options: [{ en: "Italian" }, { en: "German" }, { en: "Chinese languages" }, { en: "Spanish" }],
    answerIndex: 2,
    explanation: {
      en: "Chinese languages are the second most-spoken at home, after English, in two of Canada's biggest cities.",
    },
    source: src("Who We Are"),
  },
  {
    id: "ctz-e-060",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "About half of First Nations people live…" },
    options: [
      { en: "In the Arctic" },
      { en: "In other countries" },
      { en: "On cruise ships" },
      { en: "On reserve land in about 600 communities" },
    ],
    answerIndex: 3,
    explanation: {
      en: "About half of First Nations people live on reserve land in about 600 communities.",
    },
    source: src("Who We Are"),
  },
  {
    id: "ctz-e-061",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "Mobility rights allow Canadians to…" },
    options: [
      { en: "Live and work anywhere they choose in Canada" },
      { en: "Live only in their birth province" },
      { en: "Work only for the government" },
      { en: "Live only in large cities" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Mobility rights mean Canadians can live and work anywhere they choose in Canada.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "ctz-e-062",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "As a Canadian citizen, you can…" },
    options: [
      { en: "Drive without a licence" },
      { en: "Apply for a passport" },
      { en: "Enter any country without documents" },
      { en: "Ignore jury duty legally" },
    ],
    answerIndex: 1,
    explanation: { en: "Mobility rights include the right to apply for a passport." },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "ctz-e-063",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "Canadian citizens can vote in…" },
    options: [
      { en: "Only federal elections" },
      { en: "Only local elections" },
      { en: "Federal, provincial or territorial and local elections" },
      { en: "Only when asked by the government" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The responsibility to vote covers federal, provincial or territorial and local elections.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "ctz-e-064",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "Is there compulsory military service in Canada?" },
    options: [
      { en: "Yes — for two years" },
      { en: "Yes — for all men" },
      { en: "Yes — for one year" },
      { en: "No — there is no compulsory military service in Canada" },
    ],
    answerIndex: 3,
    explanation: { en: "There is no compulsory military service in Canada." },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "ctz-e-065",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "When called to do so, you are legally required to…" },
    options: [
      { en: "Serve on a jury" },
      { en: "Join the army" },
      { en: "Donate blood" },
      { en: "Run for office" },
    ],
    answerIndex: 0,
    explanation: { en: "When called to do so, you are legally required to serve on a jury." },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "ctz-e-066",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "Canada is the only ____ in North America." },
    options: [
      { en: "republic" },
      { en: "constitutional monarchy" },
      { en: "one-party state" },
      { en: "direct democracy" },
    ],
    answerIndex: 1,
    explanation: { en: "Canada is the only constitutional monarchy in North America." },
    source: src("Who We Are"),
  },
  {
    id: "ctz-e-067",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "Which of the following is a citizenship responsibility in Canada?" },
    options: [
      { en: "Breaking minor laws" },
      { en: "Ignoring court orders" },
      { en: "Obeying the law" },
      { en: "Avoiding the police" },
    ],
    answerIndex: 2,
    explanation: { en: "Obeying the law is listed among citizenship responsibilities." },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "ctz-e-068",
    topicId: "citizenship",
    difficulty: "easy",
    prompt: { en: "According to the guide, volunteering is…" },
    options: [
      { en: "A waste of time" },
      { en: "Required only of newcomers" },
      { en: "Paid work" },
      { en: "An excellent way to gain useful skills and develop friends and contacts" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Volunteering is an excellent way to gain useful skills and develop friends and contacts.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "ctz-m-001",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: { en: "Applicants who are 18 to 54 years of age when they apply must…" },
    options: [
      { en: "Only pay a higher application fee" },
      {
        en: "Demonstrate adequate knowledge of Canada and of the responsibilities and privileges of citizenship through a citizenship knowledge test in English or French",
      },
      { en: "Skip the citizenship ceremony" },
      { en: "Write the test in any non-official language" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Applicants 18–54 when they apply must demonstrate adequate knowledge of Canada and of the responsibilities and privileges of citizenship through a test in English or French.",
    },
    source: src("Applying for Citizenship"),
  },
  {
    id: "ctz-m-002",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: {
      en: "In addition to the knowledge test, applicants aged 18 to 54 must also demonstrate…",
    },
    options: [
      { en: "Adequate knowledge of a third language" },
      { en: "A university degree" },
      { en: "Adequate knowledge of either English or French" },
      { en: "Five years of Canadian work experience" },
    ],
    answerIndex: 2,
    explanation: {
      en: "They must also demonstrate adequate knowledge of either English or French.",
    },
    source: src("Applying for Citizenship"),
  },
  {
    id: "ctz-m-003",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: { en: "Is the citizenship test used to assess your knowledge of English or French?" },
    options: [
      { en: "Yes — it is the main language test" },
      { en: "Yes — it replaces all other language tests" },
      { en: "Yes — but only for French" },
      { en: "No — the citizenship test is not used to assess knowledge of English or French" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The citizenship test is not used to assess an applicant's knowledge of English or French.",
    },
    source: src("Applying for Citizenship"),
  },
  {
    id: "ctz-m-004",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: { en: "Citizenship test questions are based on…" },
    options: [
      { en: "The subject areas noted in the Citizenship Regulations" },
      { en: "The personal opinions of the examiner" },
      { en: "Questions from other countries' tests" },
      { en: "Topics chosen at random each year" },
    ],
    answerIndex: 0,
    explanation: {
      en: "All test questions are based on the subject areas noted in the Citizenship Regulations.",
    },
    source: src("Applying for Citizenship"),
  },
  {
    id: "ctz-m-005",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: { en: "Where is all the information required for the citizenship test provided?" },
    options: [
      { en: "In a daily newspaper" },
      { en: "In this study guide" },
      { en: "In a phone book" },
      { en: "On a cooking show" },
    ],
    answerIndex: 1,
    explanation: { en: "All required information for the test is provided in this study guide." },
    source: src("Applying for Citizenship"),
  },
  {
    id: "ctz-m-006",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: { en: "At the citizenship ceremony, you will sign…" },
    options: [
      { en: "A mortgage agreement" },
      { en: "A job contract" },
      { en: "The oath form" },
      { en: "A tax return" },
    ],
    answerIndex: 2,
    explanation: { en: "At the ceremony you sign the oath form." },
    source: src("Applying for Citizenship"),
  },
  {
    id: "ctz-m-007",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: {
      en: "Why does the guide stress keeping your correct address with the Call Centre while your application is processed?",
    },
    options: [
      { en: "Because applications are decided within a day" },
      { en: "Because the Call Centre visits every applicant" },
      { en: "Because addresses are published publicly" },
      { en: "Because your application may take several months to process" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Applications may take several months, so the Call Centre must always have your correct address during processing.",
    },
    source: src("Applying for Citizenship"),
  },
  {
    id: "ctz-m-008",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: { en: "If you do not pass the citizenship test…" },
    options: [
      { en: "You will receive a notification indicating the next steps" },
      { en: "You can never apply again" },
      { en: "You must leave Canada" },
      { en: "You are fined immediately" },
    ],
    answerIndex: 0,
    explanation: {
      en: "If you do not pass, you receive a notification indicating the next steps.",
    },
    source: src("Applying for Citizenship"),
  },
  {
    id: "ctz-m-009",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: {
      en: "How much do the English or French language classes offered by the Government of Canada cost?",
    },
    options: [
      { en: "$500 per course" },
      { en: "They are free of charge" },
      { en: "$100 per month" },
      { en: "Full price" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The Government of Canada offers English or French language classes free of charge.",
    },
    source: src("Applying for Citizenship"),
  },
  {
    id: "ctz-m-010",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: {
      en: "When you call a school, college or community centre about citizenship classes, what should you ask for?",
    },
    options: [
      { en: "Job listings" },
      { en: "Housing applications" },
      { en: "Information on citizenship classes" },
      { en: "Travel visas" },
    ],
    answerIndex: 2,
    explanation: { en: "You should ask for information on citizenship classes." },
    source: src("Applying for Citizenship"),
  },
  {
    id: "ctz-m-011",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: { en: "Of the two basic requirements for citizenship, which one relates to language?" },
    options: [
      { en: "Knowledge of Canadian history only" },
      { en: "Knowledge of world geography" },
      { en: "Knowledge of advanced mathematics" },
      { en: "Adequate knowledge of English or French" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The two requirements are knowledge of Canada and of the rights and responsibilities of citizenship, and adequate knowledge of English or French.",
    },
    source: src("Applying for Citizenship"),
  },
  {
    id: "ctz-m-012",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: {
      en: "Where can you find information on how the knowledge-of-Canada requirement is determined?",
    },
    options: [
      { en: "The Citizenship Regulations" },
      { en: "The phone book" },
      { en: "A travel guide" },
      { en: "The weather channel" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The Citizenship Regulations provide information on how the knowledge-of-Canada requirement is determined.",
    },
    source: src("Applying for Citizenship"),
  },
  {
    id: "ctz-m-013",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: { en: "In the Oath, “His Heirs and Successors” refers to…" },
    options: [
      { en: "The heirs of the Prime Minister" },
      { en: "The heirs and successors of King Charles the Third" },
      { en: "The successors of Parliament" },
      { en: "The heirs of the Governor General" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The Oath pledges allegiance to King Charles the Third, “His Heirs and Successors.”",
    },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "ctz-m-014",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: { en: "The Oath says you will observe the laws of Canada, “including…”" },
    options: [
      { en: "The traffic code" },
      { en: "The tax guide" },
      { en: "The Constitution" },
      { en: "The phone book" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The Oath says “I will faithfully observe the laws of Canada, including the Constitution.”",
    },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "ctz-m-015",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: { en: "How does the French version of the Oath begin?" },
    options: [
      { en: "“Je promets toujours”" },
      { en: "“Vive le Canada”" },
      { en: "“Je suis citoyen”" },
      { en: "“Je jure (ou j'affirme solennellement)”" },
    ],
    answerIndex: 3,
    explanation: { en: "The French Oath begins “Je jure (ou j'affirme solennellement).”" },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "ctz-m-016",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: { en: "In the French Oath, the King is called…" },
    options: [
      { en: "“Le roi Charles Trois”" },
      { en: "“Le président Charles”" },
      { en: "“Le roi Louis”" },
      { en: "“L'empereur Charles”" },
    ],
    answerIndex: 0,
    explanation: { en: "The French text addresses “Sa Majesté, Le roi Charles Trois.”" },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "ctz-m-017",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: { en: "In the French Oath, “King of Canada” is…" },
    options: [
      { en: "“Roi d'Angleterre”" },
      { en: "“Roi du Canada”" },
      { en: "“Roi de France”" },
      { en: "“Roi d'Ottawa”" },
    ],
    answerIndex: 1,
    explanation: { en: "The French Oath calls him “Le roi Charles Trois, Roi du Canada.”" },
    source: src("The Oath of Citizenship"),
  },
];
