/**
 * Question bank chunk — part of questions.generated.ts. DO NOT EDIT BY HAND.
 */
import type { Question } from "../content";
import { src } from "./shared";

export const citizenshipB: Question[] = [
  {
    id: "ctz-m-018",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: {
      en: "In our constitutional monarchy, loyalty to a document, a banner or a country is…",
    },
    options: [
      { en: "Decided by popular vote" },
      { en: "Written in a separate charter" },
      { en: "Encompassed by the Sovereign (Queen or King)" },
      { en: "Left to each province" },
    ],
    answerIndex: 2,
    explanation: {
      en: "In our constitutional monarchy these elements are encompassed by the Sovereign.",
    },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "ctz-m-019",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: { en: "In Canada, we do NOT profess loyalty to a banner such as…" },
    options: [
      { en: "The Sovereign" },
      { en: "A person" },
      { en: "His Majesty the King" },
      { en: "A flag" },
    ],
    answerIndex: 3,
    explanation: { en: "Loyalty is professed to a person, not to a banner such as a flag." },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "ctz-m-020",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: { en: "In Canada, we do NOT profess loyalty to a geopolitical entity such as…" },
    options: [
      { en: "A country" },
      { en: "The King" },
      { en: "The Sovereign" },
      { en: "A person representing Canadians" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Loyalty is professed to a person, not to a geopolitical entity such as a country.",
    },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "ctz-m-021",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: { en: "The person to whom Canadians profess loyalty represents…" },
    options: [
      { en: "Only new citizens" },
      { en: "All Canadians" },
      { en: "Only the government" },
      { en: "Only one province" },
    ],
    answerIndex: 1,
    explanation: { en: "We profess loyalty to a person who represents all Canadians." },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "ctz-m-022",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: { en: "What does “À ses héritiers et successeurs” mean in the French Oath?" },
    options: [
      { en: "“His laws and courts”" },
      { en: "“His lands and seas”" },
      { en: "“His heirs and successors”" },
      { en: "“His friends and family”" },
    ],
    answerIndex: 2,
    explanation: {
      en: "“À ses héritiers et successeurs” is the French for “His Heirs and Successors.”",
    },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "ctz-m-023",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: { en: "In the French Oath, the Constitution “reconnaît et confirme”…" },
    options: [
      { en: "“Les droits de vote”" },
      { en: "“Les droits de propriété”" },
      { en: "“Les droits d'auteur”" },
      { en: "“Les droits ancestraux ou issus de traités”" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The French Oath says the Constitution “reconnaît et confirme les droits ancestraux ou issus de traités.”",
    },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "ctz-m-024",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: { en: "What is the French title of the Oath of Citizenship?" },
    options: [
      { en: "Le serment de citoyenneté" },
      { en: "Le drapeau canadien" },
      { en: "L'hymne national" },
      { en: "La fête du Canada" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The chapter presents the Oath as “The Oath of Citizenship / Le serment de citoyenneté.”",
    },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "ctz-m-025",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: { en: "In the French Oath, “À Sa Majesté” means…" },
    options: [
      { en: "“To the President”" },
      { en: "“To His Majesty”" },
      { en: "“To the Minister”" },
      { en: "“To the Judge”" },
    ],
    answerIndex: 1,
    explanation: { en: "“À Sa Majesté” is the French for “To His Majesty.”" },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "ctz-m-026",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: { en: "Aboriginal peoples were well established in North America…" },
    options: [
      { en: "Only after Europeans arrived" },
      { en: "At exactly the same time as Europeans" },
      { en: "Long before explorers from Europe first came to North America" },
      { en: "After Confederation in 1867" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Aboriginal peoples were well established here long before explorers from Europe first came to North America.",
    },
    source: src("Who We Are"),
  },
  {
    id: "ctz-m-027",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: {
      en: "Early First Nations cultures were rooted in religious beliefs about their relationship to…",
    },
    options: [
      { en: "European kings and queens" },
      { en: "Distant empires" },
      { en: "Written scriptures only" },
      { en: "The Creator, the natural environment and each other" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Diverse, vibrant First Nations cultures were rooted in religious beliefs about their relationship to the Creator, the natural environment and each other.",
    },
    source: src("Who We Are"),
  },
  {
    id: "ctz-m-028",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: { en: "Who issued the Royal Proclamation of 1763?" },
    options: [
      { en: "King George III" },
      { en: "King Charles the Third" },
      { en: "Queen Victoria" },
      { en: "King Henry VIII" },
    ],
    answerIndex: 0,
    explanation: { en: "The Royal Proclamation of 1763 was issued by King George III." },
    source: src("Who We Are"),
  },
  {
    id: "ctz-m-029",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: { en: "What did the Royal Proclamation of 1763 establish the basis for?" },
    options: [
      { en: "Building railways" },
      { en: "Negotiating treaties with the newcomers" },
      { en: "Founding universities" },
      { en: "Creating provinces" },
    ],
    answerIndex: 1,
    explanation: { en: "It established the basis for negotiating treaties with the newcomers." },
    source: src("Who We Are"),
  },
  {
    id: "ctz-m-030",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: { en: "What was the purpose of placing Aboriginal children in residential schools?" },
    options: [
      { en: "To train them as sailors" },
      { en: "To teach them foreign languages only" },
      { en: "To educate and assimilate them into mainstream Canadian culture" },
      { en: "To prepare them for careers abroad" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The federal government placed children in residential schools to educate and assimilate them into mainstream Canadian culture.",
    },
    source: src("Who We Are"),
  },
  {
    id: "ctz-m-031",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: { en: "What were conditions like in the residential schools?" },
    options: [
      { en: "Well funded and comfortable" },
      { en: "Brief optional summer programs" },
      { en: "Popular and highly praised" },
      { en: "Poorly funded, with hardship inflicted on students — some were physically abused" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The schools were poorly funded and inflicted hardship on the students; some were physically abused.",
    },
    source: src("Who We Are"),
  },
  {
    id: "ctz-m-032",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: { en: "In residential schools, Aboriginal languages and cultural practices were…" },
    options: [
      { en: "Mostly prohibited" },
      { en: "Encouraged and celebrated" },
      { en: "Taught to all Canadians" },
      { en: "Left completely unchanged" },
    ],
    answerIndex: 0,
    explanation: { en: "Aboriginal languages and cultural practices were mostly prohibited." },
    source: src("Who We Are"),
  },
  {
    id: "ctz-m-033",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: { en: "Where do the Inuit live?" },
    options: [
      { en: "In large southern cities" },
      { en: "In small, scattered communities across the Arctic" },
      { en: "In the Prairie provinces" },
      { en: "In the Maritime provinces" },
    ],
    answerIndex: 1,
    explanation: { en: "The Inuit live in small, scattered communities across the Arctic." },
    source: src("Who We Are"),
  },
  {
    id: "ctz-m-034",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: { en: "What enabled the Inuit to adapt to one of the harshest environments on earth?" },
    options: [
      { en: "Government funding" },
      { en: "Modern technology" },
      { en: "Their knowledge of the land, sea and wildlife" },
      { en: "Help from explorers" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Their knowledge of the land, sea and wildlife enabled them to adapt to one of the harshest environments on earth.",
    },
    source: src("Who We Are"),
  },
  {
    id: "ctz-m-035",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: { en: "The Métis are a distinct people of…" },
    options: [
      { en: "Purely French ancestry" },
      { en: "Purely British ancestry" },
      { en: "Asian and African ancestry" },
      { en: "Mixed Aboriginal and European ancestry" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The Métis are a distinct people of mixed Aboriginal and European ancestry.",
    },
    source: src("Who We Are"),
  },
  {
    id: "ctz-m-036",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: { en: "Where do the majority of Métis live?" },
    options: [
      { en: "In the Prairie provinces" },
      { en: "In the Arctic" },
      { en: "In the Maritimes" },
      { en: "In downtown Toronto" },
    ],
    answerIndex: 0,
    explanation: { en: "The majority of Métis live in the Prairie provinces." },
    source: src("Who We Are"),
  },
  {
    id: "ctz-m-037",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: { en: "The Métis come from…" },
    options: [
      { en: "Only French-speaking backgrounds" },
      { en: "Both French- and English-speaking backgrounds" },
      { en: "Only English-speaking backgrounds" },
      { en: "Only Spanish-speaking backgrounds" },
    ],
    answerIndex: 1,
    explanation: { en: "The Métis come from both French- and English-speaking backgrounds." },
    source: src("Who We Are"),
  },
  {
    id: "ctz-m-038",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: { en: "The term “Indian” refers to…" },
    options: [
      { en: "All people born in India" },
      { en: "Only the Inuit" },
      { en: "All Aboriginal people who are not Inuit or Métis" },
      { en: "Only the Métis" },
    ],
    answerIndex: 2,
    explanation: { en: "“Indian” refers to all Aboriginal people who are not Inuit or Métis." },
    source: src("Who We Are"),
  },
  {
    id: "ctz-m-039",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: { en: "Where does the half of First Nations people who do NOT live on reserves live?" },
    options: [
      { en: "In the Arctic" },
      { en: "In the United States" },
      { en: "In rural France" },
      { en: "Off-reserve, mainly in urban centres" },
    ],
    answerIndex: 3,
    explanation: {
      en: "About half live on reserve land while the other half live off-reserve, mainly in urban centres.",
    },
    source: src("Who We Are"),
  },
  {
    id: "ctz-m-040",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: { en: "When did the term “First Nations” begin to be used?" },
    options: [
      { en: "In the 1970s" },
      { en: "In the 1870s" },
      { en: "In the 1970s BC era" },
      { en: "In the 1990s" },
    ],
    answerIndex: 0,
    explanation: { en: "The term First Nations began to be used in the 1970s." },
    source: src("Who We Are"),
  },
  {
    id: "ctz-m-041",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: { en: "About what share of Aboriginal peoples are Métis?" },
    options: [{ en: "About 65%" }, { en: "About 30%" }, { en: "About 4%" }, { en: "About 50%" }],
    answerIndex: 1,
    explanation: { en: "About 30% of Aboriginal people are Métis." },
    source: src("Who We Are"),
  },
  {
    id: "ctz-m-042",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: { en: "About what share of Aboriginal peoples are Inuit?" },
    options: [{ en: "About 40%" }, { en: "About 14%" }, { en: "About 4%" }, { en: "About 24%" }],
    answerIndex: 2,
    explanation: { en: "About 4% of Aboriginal people are Inuit." },
    source: src("Who We Are"),
  },
  {
    id: "ctz-m-043",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: { en: "The federal government is required by law to…" },
    options: [
      { en: "Provide services only in English" },
      { en: "Provide services only in French" },
      { en: "Provide services in any language requested" },
      { en: "Provide services throughout Canada in English and French" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The federal government is required by law to provide services throughout Canada in English and French.",
    },
    source: src("Who We Are"),
  },
  {
    id: "ctz-m-044",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: { en: "Outside Quebec, one million Francophones live in…" },
    options: [
      { en: "Ontario, New Brunswick and Manitoba" },
      { en: "Alberta, British Columbia and Saskatchewan" },
      { en: "Quebec only" },
      { en: "The territories" },
    ],
    answerIndex: 0,
    explanation: { en: "One million Francophones live in Ontario, New Brunswick and Manitoba." },
    source: src("Who We Are"),
  },
  {
    id: "ctz-m-045",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: { en: "After the Great Upheaval, what happened to Acadian identity?" },
    options: [
      { en: "It disappeared completely" },
      { en: "The Acadians survived and maintained their unique identity" },
      { en: "They moved to France permanently" },
      { en: "They stopped speaking French" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Despite the ordeal, the Acadians survived and maintained their unique identity.",
    },
    source: src("Who We Are"),
  },
  {
    id: "ctz-m-046",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: { en: "Who are the Quebecers?" },
    options: [
      { en: "The people of Ontario" },
      { en: "Only English-speaking newcomers" },
      { en: "The people of Quebec, the vast majority French-speaking" },
      { en: "Only recent immigrants" },
    ],
    answerIndex: 2,
    explanation: { en: "Quebecers are the people of Quebec, the vast majority French-speaking." },
    source: src("Who We Are"),
  },
  {
    id: "ctz-m-047",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: { en: "Quebecers are mostly descendants of…" },
    options: [
      { en: "85,000 British soldiers" },
      { en: "800 Dutch traders" },
      { en: "8,000 Spanish explorers" },
      { en: "8,500 French settlers from the 1600s and 1700s" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Most Quebecers are descendants of 8,500 French settlers from the 1600s and 1700s.",
    },
    source: src("Who We Are"),
  },
  {
    id: "ctz-m-048",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: { en: "What does the guide say about Anglo-Quebecers?" },
    options: [
      {
        en: "One million have a heritage of 250 years and form a vibrant part of the Quebec fabric",
      },
      { en: "They all left Quebec in 1900" },
      { en: "They number only one thousand" },
      { en: "They speak no English" },
    ],
    answerIndex: 0,
    explanation: {
      en: "One million Anglo-Quebecers have a heritage of 250 years and form a vibrant part of the Quebec fabric.",
    },
    source: src("Who We Are"),
  },
  {
    id: "ctz-m-049",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: { en: "Who established the basic way of life in English-speaking areas of Canada?" },
    options: [
      { en: "French fur traders alone" },
      { en: "English, Welsh, Scottish and Irish settlers, soldiers and migrants" },
      { en: "American pioneers alone" },
      { en: "Spanish missionaries" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Hundreds of thousands of English, Welsh, Scottish and Irish settlers, soldiers and migrants established it from the 1600s to the 20th century.",
    },
    source: src("Who We Are"),
  },
  {
    id: "ctz-m-050",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: { en: "In Vancouver, what share of the population speaks Chinese languages at home?" },
    options: [{ en: "3%" }, { en: "31%" }, { en: "13%" }, { en: "73%" }],
    answerIndex: 2,
    explanation: { en: "In Vancouver, 13% of the population speak Chinese languages at home." },
    source: src("Who We Are"),
  },
  {
    id: "ctz-m-051",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: { en: "In Toronto, what share of the population speaks Chinese languages at home?" },
    options: [{ en: "17%" }, { en: "27%" }, { en: "70%" }, { en: "7%" }],
    answerIndex: 3,
    explanation: { en: "In Toronto, the number is 7%." },
    source: src("Who We Are"),
  },
  {
    id: "ctz-m-052",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: { en: "Which of the following is listed among Canada's largest ethnic groups?" },
    options: [{ en: "Ukrainian" }, { en: "Brazilian" }, { en: "Japanese" }, { en: "Egyptian" }],
    answerIndex: 0,
    explanation: {
      en: "Ukrainian is listed among the largest groups: English, French, Scottish, Irish, German, Italian, Chinese, Aboriginal, Ukrainian, Dutch, South Asian and Scandinavian.",
    },
    source: src("Who We Are"),
  },
  {
    id: "ctz-m-053",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: {
      en: "How do many ethnic and religious groups live in Canada, according to the guide?",
    },
    options: [
      { en: "They live in conflict with each other" },
      { en: "They live and work in peace as proud Canadians" },
      { en: "They live separately with no contact" },
      { en: "They live under different laws" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Many ethnic and religious groups live and work in peace as proud Canadians.",
    },
    source: src("Who We Are"),
  },
  {
    id: "ctz-m-054",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: { en: "Mobility rights mean Canadians can…" },
    options: [
      { en: "Enter Canada but never leave" },
      { en: "Leave Canada but never return" },
      { en: "Enter and leave the country freely" },
      { en: "Travel only within their province" },
    ],
    answerIndex: 2,
    explanation: { en: "Mobility rights include entering and leaving the country freely." },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "ctz-m-055",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: { en: "What does the guide say about the right to vote?" },
    options: [
      { en: "It is optional and unimportant" },
      { en: "It applies only to citizens over 60" },
      { en: "It can be sold to others" },
      { en: "The right to vote comes with a responsibility to vote" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The right to vote comes with a responsibility to vote in federal, provincial or territorial and local elections.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "ctz-m-056",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: { en: "Why is serving on a jury described as a privilege?" },
    options: [
      { en: "Because the justice system depends on impartial juries made up of citizens" },
      { en: "Because jurors are paid large salaries" },
      { en: "Because it exempts you from taxes" },
      { en: "Because it is a rare honour for politicians" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Serving on a jury is a privilege that makes the justice system work as it depends on impartial juries made up of citizens.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "ctz-m-057",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: { en: "Which of the following are described as important Canadian values?" },
    options: [
      { en: "Avoiding work and depending on others" },
      {
        en: "Getting a job, taking care of one's family and working hard in keeping with one's abilities",
      },
      { en: "Leaving family care to strangers" },
      { en: "Working only when forced" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Getting a job, taking care of one's family and working hard in keeping with one's abilities are important Canadian values.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "ctz-m-058",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: { en: "About how many First Nations communities are on reserve land?" },
    options: [{ en: "About 60" }, { en: "About 160" }, { en: "About 600" }, { en: "About 6,000" }],
    answerIndex: 2,
    explanation: {
      en: "About half of First Nations people live on reserve land in about 600 communities.",
    },
    source: src("Who We Are"),
  },
  {
    id: "ctz-m-059",
    topicId: "citizenship",
    difficulty: "medium",
    prompt: { en: "What role does every citizen have regarding heritage and the environment?" },
    options: [
      { en: "Using as many resources as possible" },
      { en: "Leaving protection to the government only" },
      { en: "Ignoring pollution issues" },
      {
        en: "Avoiding waste and pollution while protecting Canada's natural, cultural and architectural heritage",
      },
    ],
    answerIndex: 3,
    explanation: {
      en: "Every citizen has a role in avoiding waste and pollution while protecting Canada's natural, cultural and architectural heritage for future generations.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "ctz-h-001",
    topicId: "citizenship",
    difficulty: "hard",
    prompt: {
      en: "When did the amended age range (18–54) for the knowledge and language requirements take effect?",
    },
    options: [
      { en: "January 1, 2000" },
      { en: "July 1, 1867" },
      { en: "October 11, 2017" },
      { en: "October 11, 1997" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Effective October 11, 2017, applicants 18–54 when they apply must meet the knowledge and language requirements.",
    },
    source: src("Applying for Citizenship"),
  },
  {
    id: "ctz-h-002",
    topicId: "citizenship",
    difficulty: "hard",
    prompt: { en: "The 18–54 knowledge and language rule also applies to…" },
    options: [
      { en: "Only future applicants" },
      { en: "Only applicants under 18" },
      { en: "Only applicants over 54" },
      { en: "Applicants who already have an application in process" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The rule covers applicants 18–54 when they apply, including those who already have an application in process.",
    },
    source: src("Applying for Citizenship"),
  },
  {
    id: "ctz-h-003",
    topicId: "citizenship",
    difficulty: "hard",
    prompt: { en: "The 18–54 age range is determined by…" },
    options: [
      { en: "The applicant's age when they apply" },
      { en: "The applicant's age at the ceremony" },
      { en: "The applicant's age when the test is written" },
      { en: "The applicant's age at birth" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The requirement applies to applicants who are 18–54 years of age when they apply.",
    },
    source: src("Applying for Citizenship"),
  },
  {
    id: "ctz-h-004",
    topicId: "citizenship",
    difficulty: "hard",
    prompt: {
      en: "If the citizenship test is not used to assess English or French, how are language abilities assessed?",
    },
    options: [
      { en: "They are not assessed at all" },
      { en: "Through a separate assessment — the test is not used for language ability" },
      { en: "Through the citizenship test itself" },
      { en: "Through a driving test" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The citizenship test is not used to assess English or French; the guide points to a separate language assessment.",
    },
    source: src("Applying for Citizenship"),
  },
  {
    id: "ctz-h-005",
    topicId: "citizenship",
    difficulty: "hard",
    prompt: { en: "Complete the principle: “Canada is personified by the Sovereign just as…”" },
    options: [
      { en: "“the flag is personified by the people”" },
      { en: "“the constitution is personified by Parliament”" },
      { en: "“the Sovereign is personified by Canada”" },
      { en: "“the land is personified by its resources”" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The guide states: “Canada is personified by the Sovereign just as the Sovereign is personified by Canada.”",
    },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "ctz-h-006",
    topicId: "citizenship",
    difficulty: "hard",
    prompt: {
      en: "In contrast to the Sovereign, which three things does Canada NOT ask for loyalty to?",
    },
    options: [
      { en: "A King, a Queen, and a Parliament" },
      { en: "A province, a city, and a town" },
      { en: "An army, a navy, and an air force" },
      { en: "A constitution, a flag, and a country" },
    ],
    answerIndex: 3,
    explanation: {
      en: "We profess loyalty to a person, not to a document such as a constitution, a banner such as a flag, or a geopolitical entity such as a country.",
    },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "ctz-h-007",
    topicId: "citizenship",
    difficulty: "hard",
    prompt: {
      en: "Which two verbs does the Oath use to describe what the Constitution does regarding Aboriginal and treaty rights?",
    },
    options: [
      { en: "Recognizes and affirms" },
      { en: "Creates and grants" },
      { en: "Ignores and denies" },
      { en: "Limits and removes" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The Oath refers to the Constitution “which recognizes and affirms the Aboriginal and treaty rights.”",
    },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "ctz-h-008",
    topicId: "citizenship",
    difficulty: "hard",
    prompt: {
      en: "In the French Oath, “fidèle” and “sincère allégeance” correspond to the English…",
    },
    options: [
      { en: "“Rich” and “powerful”" },
      { en: "“Faithful” and “true allegiance”" },
      { en: "“Free” and “equal”" },
      { en: "“Brave” and “strong”" },
    ],
    answerIndex: 1,
    explanation: {
      en: "“Que je serai fidèle et porterai sincère allégeance” matches “That I will be faithful and bear true allegiance.”",
    },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "ctz-h-009",
    topicId: "citizenship",
    difficulty: "hard",
    prompt: {
      en: "According to the guide's update note, the Oath now refers to which two things?",
    },
    options: [
      { en: "The flag and the national anthem" },
      { en: "The Charter and the Senate" },
      {
        en: "The Aboriginal and treaty rights of Indigenous peoples in Canada, and King Charles the Third",
      },
      { en: "The provinces and the territories" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The Oath now refers to the Aboriginal and treaty rights of Indigenous peoples in Canada, and to King Charles the Third.",
    },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "ctz-h-010",
    topicId: "citizenship",
    difficulty: "hard",
    prompt: { en: "The guide calls the principle that Canada is personified by the Sovereign…" },
    options: [
      { en: "A complicated legal doctrine" },
      { en: "An outdated tradition" },
      { en: "A controversial new idea" },
      { en: "A remarkably simple yet powerful principle" },
    ],
    answerIndex: 3,
    explanation: { en: "It is described as “a remarkably simple yet powerful principle.”" },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "ctz-h-011",
    topicId: "citizenship",
    difficulty: "hard",
    prompt: { en: "In the French Oath, the final line speaks of fulfilling…" },
    options: [
      { en: "“Mes obligations de citoyen canadien”" },
      { en: "“Mes impôts chaque année”" },
      { en: "“Mon service militaire”" },
      { en: "“Mes voyages à l'étranger”" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The French Oath ends: “Et que je remplirai loyalement mes obligations de citoyen canadien.”",
    },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "ctz-h-012",
    topicId: "citizenship",
    difficulty: "hard",
    prompt: { en: "In the Oath, what immediately follows “King of Canada”?" },
    options: [
      { en: "“And my family”" },
      { en: "“His Heirs and Successors”" },
      { en: "“For ever and ever”" },
      { en: "“The end”" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The Oath's order is “King Charles the Third, King of Canada, His Heirs and Successors.”",
    },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "ctz-h-013",
    topicId: "citizenship",
    difficulty: "hard",
    prompt: {
      en: "The French phrase “droits ancestraux ou issus de traités” corresponds to the English…",
    },
    options: [
      { en: "“Civil and political rights”" },
      { en: "“Mobility and language rights”" },
      { en: "“Aboriginal and treaty rights”" },
      { en: "“Property and voting rights”" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The French “les droits ancestraux ou issus de traités” matches the English “Aboriginal and treaty rights.”",
    },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "ctz-h-014",
    topicId: "citizenship",
    difficulty: "hard",
    prompt: { en: "What does the guide suggest using to help you prepare to repeat the Oath?" },
    options: [
      { en: "A daily newspaper" },
      { en: "A novel" },
      { en: "A cooking show" },
      { en: "The Oath of Citizenship video" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The guide offers a video of the Oath of Citizenship to help you prepare to repeat it at the ceremony.",
    },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "ctz-h-015",
    topicId: "citizenship",
    difficulty: "hard",
    prompt: { en: "The British North America Act is described as…" },
    options: [
      { en: "Canada's original constitutional document" },
      { en: "A provincial law from 1900" },
      { en: "A trade agreement" },
      { en: "A military treaty" },
    ],
    answerIndex: 0,
    explanation: {
      en: "“Peace, Order, and Good Government” is a key phrase in Canada's original constitutional document, the British North America Act of 1867.",
    },
    source: src("Who We Are"),
  },
  {
    id: "ctz-h-016",
    topicId: "citizenship",
    difficulty: "hard",
    prompt: {
      en: "According to the guide, a belief in ordered liberty, enterprise, hard work and fair play enabled Canadians to…",
    },
    options: [
      { en: "Conquer neighbouring countries" },
      { en: "Build a prosperous society in a rugged environment" },
      { en: "Avoid all hard work" },
      { en: "Isolate themselves from the world" },
    ],
    answerIndex: 1,
    explanation: {
      en: "That belief enabled Canadians to build a prosperous society in a rugged environment.",
    },
    source: src("Who We Are"),
  },
  {
    id: "ctz-h-017",
    topicId: "citizenship",
    difficulty: "hard",
    prompt: { en: "The guide describes Canada as stretching…" },
    options: [
      { en: "From the Atlantic shores to the Mediterranean Sea" },
      { en: "From the Pacific Ocean to the Arctic Circle only" },
      { en: "From our Atlantic shores to the Pacific Ocean and to the Arctic Circle" },
      { en: "From the Great Lakes to the Gulf of Mexico" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Canadians built a prosperous society “from our Atlantic shores to the Pacific Ocean and to the Arctic Circle.”",
    },
    source: src("Who We Are"),
  },
  {
    id: "ctz-h-018",
    topicId: "citizenship",
    difficulty: "hard",
    prompt: { en: "John Buchan said immigrant groups “should retain their individuality and…”" },
    options: [
      { en: "“forget their past completely”" },
      { en: "“avoid all traditions”" },
      { en: "“live separately from others”" },
      { en: "“each make its contribution to the national character”" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Buchan said immigrant groups “should retain their individuality and each make its contribution to the national character.”",
    },
    source: src("Who We Are"),
  },
  {
    id: "ctz-h-019",
    topicId: "citizenship",
    difficulty: "hard",
    prompt: { en: "When was John Buchan (the 1st Baron Tweedsmuir) Governor General of Canada?" },
    options: [{ en: "1935–40" }, { en: "1910–15" }, { en: "1950–55" }, { en: "1970–75" }],
    answerIndex: 0,
    explanation: {
      en: "John Buchan, the 1st Baron Tweedsmuir, was Governor General from 1935 to 1940.",
    },
    source: src("Who We Are"),
  },
  {
    id: "ctz-h-020",
    topicId: "citizenship",
    difficulty: "hard",
    prompt: { en: "Where and when did John Buchan give the speech quoted in the guide?" },
    options: [
      { en: "Toronto, 1900" },
      { en: "Canadian Club of Halifax, 1937" },
      { en: "Ottawa, 1967" },
      { en: "Vancouver, 1980" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The quotation is from his address to the Canadian Club of Halifax in 1937.",
    },
    source: src("Who We Are"),
  },
  {
    id: "ctz-h-021",
    topicId: "citizenship",
    difficulty: "hard",
    prompt: { en: "What did the Royal Proclamation of 1763 first guarantee?" },
    options: [
      { en: "Voting rights" },
      { en: "Language rights" },
      { en: "Territorial rights" },
      { en: "Fishing licences" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Territorial rights were first guaranteed through the Royal Proclamation of 1763.",
    },
    source: src("Who We Are"),
  },
  {
    id: "ctz-h-022",
    topicId: "citizenship",
    difficulty: "hard",
    prompt: {
      en: "What does the guide say about the treaties negotiated after the Royal Proclamation?",
    },
    options: [
      { en: "They were all perfectly honoured" },
      { en: "They were never written down" },
      { en: "They applied only to Europe" },
      { en: "They were not always fully respected" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The Proclamation established the basis for negotiating treaties — treaties that were not always fully respected.",
    },
    source: src("Who We Are"),
  },
  {
    id: "ctz-h-023",
    topicId: "citizenship",
    difficulty: "hard",
    prompt: {
      en: "Over what period did the federal government place Aboriginal children in residential schools?",
    },
    options: [
      { en: "From the 1800s until the 1980s" },
      { en: "From the 1500s to the 1600s" },
      { en: "From 1900 to 1910" },
      { en: "From 2010 to 2020" },
    ],
    answerIndex: 0,
    explanation: { en: "This happened from the 1800s until the 1980s." },
    source: src("Who We Are"),
  },
  {
    id: "ctz-h-024",
    topicId: "citizenship",
    difficulty: "hard",
    prompt: { en: "Which statement about the population shares of Aboriginal peoples is correct?" },
    options: [
      { en: "About 65% are Inuit, 30% First Nations and 4% Métis" },
      { en: "About 65% are First Nations, 30% Métis and 4% Inuit" },
      { en: "About 65% are Métis, 30% Inuit and 4% First Nations" },
      { en: "About 50% are First Nations, 50% Métis and 50% Inuit" },
    ],
    answerIndex: 1,
    explanation: {
      en: "About 65% of Aboriginal people are First Nations, while 30% are Métis and 4% Inuit.",
    },
    source: src("Who We Are"),
  },
  {
    id: "ctz-h-025",
    topicId: "citizenship",
    difficulty: "hard",
    prompt: {
      en: "In what year did French colonists begin settling in what are now the Maritime provinces?",
    },
    options: [{ en: "1492" }, { en: "1755" }, { en: "1604" }, { en: "1867" }],
    answerIndex: 2,
    explanation: {
      en: "The Acadians descend from French colonists who began settling there in 1604.",
    },
    source: src("Who We Are"),
  },
  {
    id: "ctz-h-026",
    topicId: "citizenship",
    difficulty: "hard",
    prompt: { en: "During which war were the Acadians deported from their homeland?" },
    options: [
      { en: "The Napoleonic Wars" },
      { en: "The American Civil War" },
      { en: "The Crimean War" },
      { en: "The war between Britain and France" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The deportation happened between 1755 and 1763, during the war between Britain and France.",
    },
    source: src("Who We Are"),
  },
  {
    id: "ctz-h-027",
    topicId: "citizenship",
    difficulty: "hard",
    prompt: { en: "How is Acadian culture described today?" },
    options: [
      { en: "Flourishing and a lively part of French-speaking Canada" },
      { en: "Disappeared entirely" },
      { en: "Struggling to survive" },
      { en: "Unknown to most Canadians" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Today, Acadian culture is flourishing and is a lively part of French-speaking Canada.",
    },
    source: src("Who We Are"),
  },
  {
    id: "ctz-h-028",
    topicId: "citizenship",
    difficulty: "hard",
    prompt: { en: "Besides Quebec, Ontario, New Brunswick and Manitoba, Francophones have…" },
    options: [
      { en: "No presence elsewhere" },
      { en: "A smaller presence in other provinces" },
      { en: "A majority in Alberta" },
      { en: "Official status everywhere" },
    ],
    answerIndex: 1,
    explanation: {
      en: "One million Francophones live in Ontario, New Brunswick and Manitoba, with a smaller presence in other provinces.",
    },
    source: src("Who We Are"),
  },
  {
    id: "ctz-h-029",
    topicId: "citizenship",
    difficulty: "hard",
    prompt: { en: "Quebecers maintain…" },
    options: [
      { en: "No distinct identity" },
      { en: "Only a unique cuisine" },
      { en: "A unique identity, culture and language" },
      { en: "An identity identical to France's" },
    ],
    answerIndex: 2,
    explanation: { en: "Quebecers maintain a unique identity, culture and language." },
    source: src("Who We Are"),
  },
  {
    id: "ctz-h-030",
    topicId: "citizenship",
    difficulty: "hard",
    prompt: { en: "What did generations of pioneers and builders of British origins do?" },
    options: [
      { en: "Avoided all hardship" },
      { en: "Left the country" },
      { en: "Refused to invest" },
      { en: "Invested and endured hardship in laying the foundations of the country" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Generations of pioneers and builders invested and endured hardship in laying the foundations of the country.",
    },
    source: src("Who We Are"),
  },
  {
    id: "ctz-h-031",
    topicId: "citizenship",
    difficulty: "hard",
    prompt: { en: "According to the guide, experiences of warfare or conflict…" },
    options: [
      { en: "Do not justify bringing violent, extreme or hateful prejudices to Canada" },
      { en: "Justify any behaviour" },
      { en: "Are celebrated" },
      { en: "Must be forgotten entirely" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Such experiences do not justify bringing to Canada violent, extreme or hateful prejudices.",
    },
    source: src("Who We Are"),
  },
  {
    id: "ctz-h-032",
    topicId: "citizenship",
    difficulty: "hard",
    prompt: { en: "What does the guide say about non-official languages in Canada?" },
    options: [
      { en: "They are banned in homes" },
      { en: "They are widely spoken in Canadian homes" },
      { en: "They are rarely spoken" },
      { en: "They are only spoken in schools" },
    ],
    answerIndex: 1,
    explanation: { en: "Non-official languages are widely spoken in Canadian homes." },
    source: src("Who We Are"),
  },
  {
    id: "ctz-h-033",
    topicId: "citizenship",
    difficulty: "hard",
    prompt: { en: "The state's traditional partnership with faith communities upholds…" },
    options: [
      { en: "Military expansion and conquest" },
      { en: "A single official religion" },
      { en: "Religious freedom, religious expression and freedom of conscience" },
      { en: "Bans on all worship" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The partnership upholds religious freedom, religious expression and freedom of conscience.",
    },
    source: src("Who We Are"),
  },
  {
    id: "ctz-h-034",
    topicId: "citizenship",
    difficulty: "hard",
    prompt: {
      en: "From where did Marjorie Turner-Bailey's ancestors flee to Canada in the 1780s?",
    },
    options: [{ en: "The Caribbean" }, { en: "West Africa" }, { en: "England" }, { en: "America" }],
    answerIndex: 3,
    explanation: {
      en: "Her ancestors were Black Loyalists who in the 1780s fled to Canada from America.",
    },
    source: src("Who We Are"),
  },
  {
    id: "ctz-h-035",
    topicId: "citizenship",
    difficulty: "hard",
    prompt: { en: "According to the guide, slavery remained legal in America until…" },
    options: [{ en: "1863" }, { en: "1783" }, { en: "1900" }, { en: "1865" }],
    answerIndex: 0,
    explanation: { en: "They fled from America, where slavery remained legal until 1863." },
    source: src("Who We Are"),
  },
  {
    id: "ctz-h-036",
    topicId: "citizenship",
    difficulty: "hard",
    prompt: { en: "The Black Loyalists included…" },
    options: [
      { en: "Only British soldiers" },
      { en: "Escaped slaves and freed men and women of African origin" },
      { en: "Only French traders" },
      { en: "Only recent immigrants" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Marjorie Turner-Bailey is a descendant of Black Loyalists, escaped slaves and freed men and women of African origin.",
    },
    source: src("Who We Are"),
  },
  {
    id: "ctz-h-037",
    topicId: "citizenship",
    difficulty: "hard",
    prompt: { en: "Who is Marjorie Turner-Bailey?" },
    options: [
      { en: "A Governor General" },
      { en: "A Prime Minister" },
      { en: "An Olympian from Nova Scotia descended from Black Loyalists" },
      { en: "An inventor from Ontario" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Olympian Marjorie Turner-Bailey of Nova Scotia is a descendant of Black Loyalists.",
    },
    source: src("Who We Are"),
  },
  {
    id: "ctz-h-038",
    topicId: "citizenship",
    difficulty: "hard",
    prompt: {
      en: "According to the guide, what distinction does Canada’s constitutional tradition hold?",
    },
    options: [
      { en: "The newest written constitution in the world" },
      { en: "The only unwritten constitution in the Americas" },
      { en: "The first constitution to mention multiculturalism" },
      { en: "The oldest continuous constitutional tradition in the world" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Canadians have inherited the oldest continuous constitutional tradition in the world.",
    },
    source: src("Who We Are"),
  },
  {
    id: "ctz-h-039",
    topicId: "citizenship",
    difficulty: "hard",
    prompt: { en: "What does the rule of law mean in Canada?" },
    options: [
      { en: "No person or group is above the law" },
      { en: "The government is above the law" },
      { en: "Only citizens must obey laws" },
      { en: "Laws apply only in cities" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Individuals and governments are regulated by laws, and no person or group is above the law.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "ctz-h-040",
    topicId: "citizenship",
    difficulty: "hard",
    prompt: { en: "According to the guide, work contributes to…" },
    options: [
      { en: "Only personal wealth" },
      { en: "Personal dignity and self-respect, and to Canada's prosperity" },
      { en: "Nothing of value" },
      { en: "Only government revenue" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Work contributes to personal dignity and self-respect, and to Canada's prosperity.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "ctz-h-041",
    topicId: "citizenship",
    difficulty: "hard",
    prompt: { en: "By helping to protect your community, you…" },
    options: [
      { en: "Break with all traditions" },
      { en: "Avoid all responsibility" },
      {
        en: "Follow in the footsteps of Canadians before you who made sacrifices in the service of the country",
      },
      { en: "Reject Canadian values" },
    ],
    answerIndex: 2,
    explanation: {
      en: "By helping protect your community, you follow in the footsteps of Canadians before you who made sacrifices in the service of the country.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "ctz-h-042",
    topicId: "citizenship",
    difficulty: "hard",
    prompt: { en: "What is the relationship between rights and responsibilities in Canada?" },
    options: [
      { en: "Rights have no responsibilities" },
      { en: "Responsibilities cancel rights" },
      { en: "Only newcomers have responsibilities" },
      { en: "Rights come with responsibilities" },
    ],
    answerIndex: 3,
    explanation: { en: "In Canada, rights come with responsibilities." },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "ctz-h-043",
    topicId: "citizenship",
    difficulty: "hard",
    prompt: { en: "In Canada, individuals and governments are regulated by…" },
    options: [
      { en: "Laws, and not by arbitrary actions" },
      { en: "Arbitrary actions" },
      { en: "Personal opinions" },
      { en: "Foreign decrees" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Individuals and governments are regulated by laws and not by arbitrary actions.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
];
