/**
 * Question bank chunk — part of questions.generated.ts. DO NOT EDIT BY HAND.
 */
import type { Question } from "../content";
import { src } from "./shared";

export const economyB: Question[] = [
  {
    id: "eco-m-019",
    topicId: "economy",
    difficulty: "medium",
    prompt: {
      en: "The guide says Canada exports billions of dollars worth of ___ goods every year.",
    },
    options: [{ en: "Banned" }, { en: "Stolen" }, { en: "Consumer" }, { en: "Imaginary" }],
    answerIndex: 2,
    explanation: { en: "Consumer goods are listed among Canada's annual exports." },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-m-020",
    topicId: "economy",
    difficulty: "medium",
    prompt: { en: "Which pair is listed among Canada's exports?" },
    options: [
      { en: "Banking and tourism" },
      { en: "Education and health care" },
      { en: "Software and films" },
      { en: "Fishing and forestry products" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Fishing and forestry products are listed among Canada's exports to the United States.",
    },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-m-021",
    topicId: "economy",
    difficulty: "medium",
    prompt: { en: "Canada's exports to the U.S. include ___." },
    options: [
      { en: "Machinery and equipment" },
      { en: "Perfumes and cosmetics" },
      { en: "Spices and teas" },
      { en: "Silk and carpets" },
    ],
    answerIndex: 0,
    explanation: { en: "Machinery and equipment are listed among Canada's annual exports." },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-m-022",
    topicId: "economy",
    difficulty: "medium",
    prompt: { en: "Which export category relates to farming?" },
    options: [
      { en: "Automotive" },
      { en: "Agricultural" },
      { en: "Industrial" },
      { en: "Forestry" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Agricultural products are listed among Canada's exports to the United States.",
    },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-m-023",
    topicId: "economy",
    difficulty: "medium",
    prompt: { en: "The guide illustrates Alberta's oil industry with ___." },
    options: [
      { en: "Offshore rigs in the north" },
      { en: "Coal mines in the east" },
      { en: "Oil pumpjacks in the south" },
      { en: "Refineries in the west" },
    ],
    answerIndex: 2,
    explanation: { en: "The photo caption shows oil pumpjacks in southern Alberta." },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-m-024",
    topicId: "economy",
    difficulty: "medium",
    prompt: { en: "The pictured hydro-electric dam stands on which river?" },
    options: [
      { en: "The Fraser River" },
      { en: "The St. Lawrence River" },
      { en: "The Mackenzie River" },
      { en: "The Saguenay River" },
    ],
    answerIndex: 3,
    explanation: { en: "The pictured hydro-electric dam is on the Saguenay River, Quebec." },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-m-025",
    topicId: "economy",
    difficulty: "medium",
    prompt: { en: "The car assembly plant pictured is in which Ontario city?" },
    options: [{ en: "Oakville" }, { en: "Hamilton" }, { en: "London" }, { en: "Windsor" }],
    answerIndex: 0,
    explanation: { en: "The pictured car assembly plant is in Oakville, Ontario." },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-m-026",
    topicId: "economy",
    difficulty: "medium",
    prompt: {
      en: "Along with the Oakville car plant, which other trade-related photo appears in the chapter?",
    },
    options: [
      { en: "The CN Tower" },
      { en: "The Port of Vancouver" },
      { en: "Niagara Falls" },
      { en: "Parliament Hill" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The Port of Vancouver is pictured alongside the Oakville car assembly plant.",
    },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-m-027",
    topicId: "economy",
    difficulty: "medium",
    prompt: { en: "Ice wine grapes are associated with which region?" },
    options: [
      { en: "The Okanagan Valley" },
      { en: "The Annapolis Valley" },
      { en: "The Niagara Region" },
      { en: "The Fraser Valley" },
    ],
    answerIndex: 2,
    explanation: { en: "Ice wine grapes are pictured from the Niagara Region, Ontario." },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-m-028",
    topicId: "economy",
    difficulty: "medium",
    prompt: { en: "The guide's lobster photo illustrates which natural resources industry?" },
    options: [{ en: "Forestry" }, { en: "Mining" }, { en: "Energy" }, { en: "Fishing" }],
    answerIndex: 3,
    explanation: { en: "The Atlantic lobster photo illustrates the fishing industry." },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-m-029",
    topicId: "economy",
    difficulty: "medium",
    prompt: {
      en: "The RIM BlackBerry laboratory photo illustrates which type of manufactured product?",
    },
    options: [
      { en: "High technology equipment" },
      { en: "Paper" },
      { en: "Food" },
      { en: "Clothing" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The RIM BlackBerry research laboratory illustrates high technology equipment manufacturing.",
    },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-m-030",
    topicId: "economy",
    difficulty: "medium",
    prompt: { en: "The restrictive trading policies opened up by the GATT dated from which era?" },
    options: [
      { en: "The Victorian era" },
      { en: "The Depression era" },
      { en: "The Space Age" },
      { en: "The Renaissance" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The world's restrictive trading policies in the Depression era were opened up by treaties such as the GATT.",
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-m-031",
    topicId: "economy",
    difficulty: "medium",
    prompt: { en: "In 1951, a ___ of Canadians could afford adequate food, shelter and clothing." },
    options: [{ en: "Small minority" }, { en: "Handful" }, { en: "Majority" }, { en: "None" }],
    answerIndex: 2,
    explanation: {
      en: "In 1951, for the first time, a majority of Canadians could afford adequate food, shelter and clothing.",
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-m-032",
    topicId: "economy",
    difficulty: "medium",
    prompt: { en: "The guide's strong-economy period runs from ___." },
    options: [
      { en: "1935 to 1960" },
      { en: "1955 to 1980" },
      { en: "1925 to 1950" },
      { en: "1945 to 1970" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Between 1945 and 1970, Canada enjoyed one of the strongest economies among industrialized nations.",
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-m-033",
    topicId: "economy",
    difficulty: "medium",
    prompt: { en: "Between 1945 and 1970, Canada drew closer to ___." },
    options: [
      { en: "The United States and other trading partners" },
      { en: "The Soviet Union" },
      { en: "South America only" },
      { en: "Antarctica" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Between 1945 and 1970, Canada drew closer to the United States and other trading partners.",
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-m-034",
    topicId: "economy",
    difficulty: "medium",
    prompt: {
      en: "During 1945–1970, Canada's economy was one of the strongest among industrialized nations as it ___.",
    },
    options: [
      { en: "Closed its borders" },
      { en: "Drew closer to the U.S. and other trading partners" },
      { en: "Abandoned trade" },
      { en: "Stopped manufacturing" },
    ],
    answerIndex: 1,
    explanation: {
      en: "As Canada drew closer to the United States and other trading partners, it enjoyed one of the strongest economies among industrialized nations.",
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-m-035",
    topicId: "economy",
    difficulty: "medium",
    prompt: {
      en: 'Canada\'s high standard of living is maintained by trade with other nations, "in particular" ___.',
    },
    options: [{ en: "France" }, { en: "Japan" }, { en: "The United States" }, { en: "Brazil" }],
    answerIndex: 2,
    explanation: {
      en: "The standard of living is maintained by trade with other nations, in particular the United States.",
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-m-036",
    topicId: "economy",
    difficulty: "medium",
    prompt: { en: '"As prosperity grew, so did the ability to support ___."' },
    options: [
      { en: "Military parades" },
      { en: "Royal visits" },
      { en: "Space missions" },
      { en: "Social assistance programs" },
    ],
    answerIndex: 3,
    explanation: {
      en: "As prosperity grew, so did the ability to support social assistance programs.",
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-m-037",
    topicId: "economy",
    difficulty: "medium",
    prompt: { en: "The Canada Health Act ensures ___ across the country." },
    options: [
      { en: "Common elements" },
      { en: "Different rules per clinic" },
      { en: "No standards at all" },
      { en: "Fees for everyone" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The Canada Health Act ensures common elements and a basic standard of coverage.",
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-m-038",
    topicId: "economy",
    difficulty: "medium",
    prompt: { en: "Employment insurance was originally called ___." },
    options: [
      { en: "Old age security" },
      { en: "Unemployment insurance" },
      { en: "Workers' compensation" },
      { en: "Baby bonus" },
    ],
    answerIndex: 1,
    explanation: { en: "Unemployment insurance is now called employment insurance." },
    source: src("Modern Canada"),
  },
  {
    id: "eco-m-039",
    topicId: "economy",
    difficulty: "medium",
    prompt: { en: "Which of these social programs came first?" },
    options: [
      { en: "Employment insurance (1940)" },
      { en: "The Canada and Quebec Pension Plans (1965)" },
      { en: "Old Age Security (1927)" },
      { en: "The Canada Health Act" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Old Age Security was devised as early as 1927, before employment insurance (1940) and the 1965 pension plans.",
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-m-040",
    topicId: "economy",
    difficulty: "medium",
    prompt: { en: "The year 1965 saw the creation of ___." },
    options: [
      { en: "The GATT and the WTO" },
      { en: "NAFTA and the G8" },
      { en: "The Health Act and EI" },
      { en: "The Canada and Quebec Pension Plans" },
    ],
    answerIndex: 3,
    explanation: { en: "The Canada and Quebec Pension Plans were established in 1965." },
    source: src("Modern Canada"),
  },
  {
    id: "eco-m-041",
    topicId: "economy",
    difficulty: "medium",
    prompt: { en: "Education in Canada is described as ___." },
    options: [
      { en: "Publicly funded" },
      { en: "Privately funded" },
      { en: "Foreign funded" },
      { en: "Unfunded" },
    ],
    answerIndex: 0,
    explanation: { en: "Publicly funded education is provided by the provinces and territories." },
    source: src("Modern Canada"),
  },
  {
    id: "eco-m-042",
    topicId: "economy",
    difficulty: "medium",
    prompt: { en: "In 1948, which group gained the right to vote?" },
    options: [
      { en: "Chinese-Canadians" },
      { en: "Japanese-Canadians" },
      { en: "Aboriginal people" },
      { en: "Women" },
    ],
    answerIndex: 1,
    explanation: {
      en: "In 1948 the last of these, the Japanese-Canadians, gained the right to vote.",
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-m-043",
    topicId: "economy",
    difficulty: "medium",
    prompt: {
      en: "The Japanese-Canadians were the ___ Canadians of Asian descent to gain the vote.",
    },
    options: [{ en: "First" }, { en: "Second" }, { en: "Last" }, { en: "Only" }],
    answerIndex: 2,
    explanation: {
      en: "In 1948 the last of these, the Japanese-Canadians, gained the right to vote.",
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-m-044",
    topicId: "economy",
    difficulty: "medium",
    prompt: { en: "Aboriginal people were granted the vote in ___." },
    options: [{ en: "1948" }, { en: "1970" }, { en: "1980" }, { en: "1960" }],
    answerIndex: 3,
    explanation: { en: "Aboriginal people were granted the vote in 1960." },
    source: src("Modern Canada"),
  },
  {
    id: "eco-m-045",
    topicId: "economy",
    difficulty: "medium",
    prompt: { en: "About 37,000 refugees who escaped Soviet tyranny came from ___ in 1956." },
    options: [{ en: "Hungary" }, { en: "Poland" }, { en: "Vietnam" }, { en: "Cuba" }],
    answerIndex: 0,
    explanation: {
      en: "About 37,000 refugees escaped Soviet tyranny in Hungary in 1956 and came to Canada.",
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-m-046",
    topicId: "economy",
    difficulty: "medium",
    prompt: { en: "Over 50,000 Vietnamese sought refuge in Canada after ___." },
    options: [
      { en: "The 1956 Olympics" },
      { en: "The Communist victory in the Vietnam War in 1975" },
      { en: "The 1967 Centennial" },
      { en: "The 1988 Winter Games" },
    ],
    answerIndex: 1,
    explanation: {
      en: "With the Communist victory in the Vietnam War in 1975, over 50,000 Vietnamese sought refuge in Canada.",
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-m-047",
    topicId: "economy",
    difficulty: "medium",
    prompt: { en: "By the 1960s, about ___ of Canadians had origins neither British nor French." },
    options: [{ en: "One-half" }, { en: "One-tenth" }, { en: "One-third" }, { en: "Nine-tenths" }],
    answerIndex: 2,
    explanation: {
      en: "By the 1960s, one-third of Canadians had origins that were neither British nor French.",
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-m-048",
    topicId: "economy",
    difficulty: "medium",
    prompt: {
      en: "Canadians of diverse origins took pride in preserving their distinct culture in ___.",
    },
    options: [
      { en: "Their home countries" },
      { en: "Secret societies" },
      { en: "Foreign clubs" },
      { en: "The Canadian fabric" },
    ],
    answerIndex: 3,
    explanation: {
      en: "They took pride in preserving their distinct culture in the Canadian fabric.",
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-m-049",
    topicId: "economy",
    difficulty: "medium",
    prompt: { en: "Many Canadians took advantage of expanding ___ educational opportunities." },
    options: [
      { en: "Secondary and postsecondary" },
      { en: "Primary only" },
      { en: "Military" },
      { en: "Overseas" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Many took advantage of expanding secondary and postsecondary educational opportunities.",
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-m-050",
    topicId: "economy",
    difficulty: "medium",
    prompt: { en: "Quebec's era of rapid change in the 1960s is known as ___." },
    options: [
      { en: "The Loud Rebellion" },
      { en: "The Quiet Revolution" },
      { en: "The Silent Winter" },
      { en: "The Great Uprising" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Quebec experienced an era of rapid change in the 1960s known as the Quiet Revolution.",
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-m-051",
    topicId: "economy",
    difficulty: "medium",
    prompt: { en: "The Official Languages Act was passed in ___." },
    options: [{ en: "1959" }, { en: "1979" }, { en: "1969" }, { en: "1989" }],
    answerIndex: 2,
    explanation: {
      en: "The Official Languages Act (1969) guarantees French and English services in the federal government.",
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-m-052",
    topicId: "economy",
    difficulty: "medium",
    prompt: { en: "The Official Languages Act guarantees French and English services in ___." },
    options: [
      { en: "Quebec only" },
      { en: "Private businesses" },
      { en: "Foreign embassies" },
      { en: "The federal government across Canada" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The Official Languages Act guarantees French and English services in the federal government across Canada.",
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-m-053",
    topicId: "economy",
    difficulty: "medium",
    prompt: { en: "The Canadarm was invented by ___." },
    options: [
      { en: "SPAR Aerospace / National Research Council" },
      { en: "RIM" },
      { en: "Bell Canada" },
      { en: "NASA alone" },
    ],
    answerIndex: 0,
    explanation: {
      en: "SPAR Aerospace and the National Research Council invented the Canadarm, a robotic arm used in outer space.",
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-m-054",
    topicId: "economy",
    difficulty: "medium",
    prompt: { en: "Since ___, the Canadian Space Agency has participated in space exploration." },
    options: [{ en: "1969" }, { en: "1989" }, { en: "1979" }, { en: "1999" }],
    answerIndex: 1,
    explanation: {
      en: "Since 1989, the Canadian Space Agency and Canadian astronauts have participated in space exploration.",
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-m-055",
    topicId: "economy",
    difficulty: "medium",
    prompt: { en: "Insulin was discovered by ___." },
    options: [
      { en: "Bell and Edison" },
      { en: "Fleming and Lister" },
      { en: "Sir Frederick Banting and Charles Best" },
      { en: "Curie and Curie" },
    ],
    answerIndex: 2,
    explanation: { en: "Sir Frederick Banting of Toronto and Charles Best discovered insulin." },
    source: src("Modern Canada"),
  },
  {
    id: "eco-m-056",
    topicId: "economy",
    difficulty: "medium",
    prompt: { en: "Insulin has saved ___ lives worldwide." },
    options: [
      { en: "16 thousand" },
      { en: "16 hundred" },
      { en: "16 billion" },
      { en: "16 million" },
    ],
    answerIndex: 3,
    explanation: { en: "Insulin has saved 16 million lives worldwide." },
    source: src("Modern Canada"),
  },
  {
    id: "eco-m-057",
    topicId: "economy",
    difficulty: "medium",
    prompt: { en: "James Naismith, who invented basketball, was ___." },
    options: [{ en: "Canadian" }, { en: "American" }, { en: "British" }, { en: "French" }],
    answerIndex: 0,
    explanation: { en: "Basketball was invented by Canadian James Naismith in 1891." },
    source: src("Modern Canada"),
  },
  {
    id: "eco-m-058",
    topicId: "economy",
    difficulty: "medium",
    prompt: { en: "In 1963, Parliament established the Royal Commission on ___." },
    options: [
      { en: "Trade and Tariffs" },
      { en: "Bilingualism and Biculturalism" },
      { en: "Health and Welfare" },
      { en: "Space and Science" },
    ],
    answerIndex: 1,
    explanation: {
      en: "In 1963 Parliament established the Royal Commission on Bilingualism and Biculturalism.",
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-m-059",
    topicId: "economy",
    difficulty: "medium",
    prompt: {
      en: "In 1970, Canada helped found La Francophonie, an international association of ___.",
    },
    options: [
      { en: "English-speaking countries" },
      { en: "Trading nations" },
      { en: "French-speaking countries" },
      { en: "Arctic nations" },
    ],
    answerIndex: 2,
    explanation: {
      en: "La Francophonie is an international association of French-speaking countries.",
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-m-060",
    topicId: "economy",
    difficulty: "medium",
    prompt: { en: "Quebec's first sovereignty referendum was defeated in ___." },
    options: [{ en: "1970" }, { en: "1990" }, { en: "2000" }, { en: "1980" }],
    answerIndex: 3,
    explanation: {
      en: "The movement for Quebec sovereignty was defeated in a referendum in the province in 1980.",
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-m-061",
    topicId: "economy",
    difficulty: "medium",
    prompt: { en: "Toronto's ___ is Canada's financial capital." },
    options: [
      { en: "Business district" },
      { en: "Harbourfront" },
      { en: "Subway system" },
      { en: "City zoo" },
    ],
    answerIndex: 0,
    explanation: { en: "Toronto's business district is described as Canada's financial capital." },
    source: src("Modern Canada"),
  },
  {
    id: "eco-m-062",
    topicId: "economy",
    difficulty: "medium",
    prompt: {
      en: 'The guide\'s list of manufactured products ends with "many other goods," showing the list is ___.',
    },
    options: [
      { en: "A complete ranking" },
      { en: "Not exhaustive" },
      { en: "An alphabetical index" },
      { en: "A legal definition" },
    ],
    answerIndex: 1,
    explanation: {
      en: 'The manufactured products list ends with "and many other goods," so it gives examples rather than every product.',
    },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-m-063",
    topicId: "economy",
    difficulty: "medium",
    prompt: {
      en: 'Service industries provide jobs in "areas like" transportation and tourism — the words "areas like" show these are ___.',
    },
    options: [
      { en: "The only areas" },
      { en: "Legal requirements" },
      { en: "Examples" },
      { en: "Foreign jobs" },
    ],
    answerIndex: 2,
    explanation: {
      en: 'The guide says "areas like," indicating transportation, education and the others are examples.',
    },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-h-001",
    topicId: "economy",
    difficulty: "hard",
    prompt: { en: "In 2008, merchandise trade within NAFTA was over ___." },
    options: [
      { en: "$1 trillion" },
      { en: "$1 billion" },
      { en: "$1 million" },
      { en: "$100 trillion" },
    ],
    answerIndex: 0,
    explanation: { en: "NAFTA had over $1 trillion in merchandise trade in 2008." },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-h-002",
    topicId: "economy",
    difficulty: "hard",
    prompt: { en: "NAFTA (1994) built upon an earlier deal. Which one?" },
    options: [
      { en: "The 1988 Canada–Mexico deal" },
      { en: "The 1988 Canada–U.S. free trade agreement" },
      { en: "The 1988 Canada–Japan deal" },
      { en: "The 1988 Canada–U.K. deal" },
    ],
    answerIndex: 1,
    explanation: {
      en: "In 1988, Canada enacted free trade with the United States; Mexico became a partner in the broader NAFTA in 1994.",
    },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-h-003",
    topicId: "economy",
    difficulty: "hard",
    prompt: {
      en: 'The guide gives two "more than three-quarters" figures. Which pair is correct?',
    },
    options: [
      { en: "75% in manufacturing and 75% in farming" },
      { en: "75% French-speaking and 75% urban" },
      { en: "More than 75% of workers in services and over three-quarters of exports to the U.S." },
      { en: "75% under 18 and 75% in Toronto" },
    ],
    answerIndex: 2,
    explanation: {
      en: "More than 75% of working Canadians have service jobs, and over three-quarters of Canadian exports go to the U.S.A.",
    },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-h-004",
    topicId: "economy",
    difficulty: "hard",
    prompt: { en: "The guide lists the Peace Arch inscriptions in this order:" },
    options: [
      { en: '"Brethren dwelling together in unity," then "children of a common mother"' },
      { en: "Only one inscription is quoted" },
      { en: "Two unrelated phrases about trade" },
      { en: '"Children of a common mother," then "brethren dwelling together in unity"' },
    ],
    answerIndex: 3,
    explanation: {
      en: 'The guide quotes the Peace Arch as inscribed with the words "children of a common mother" and "brethren dwelling together in unity," in that order.',
    },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-h-005",
    topicId: "economy",
    difficulty: "hard",
    prompt: {
      en: 'The phrase "the world\'s longest undefended border" is introduced with which qualifier?',
    },
    options: [
      { en: "Traditionally known as" },
      { en: "Officially designated as" },
      { en: "Legally defined as" },
      { en: "Recently renamed as" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The border is described as what is traditionally known as the world's longest undefended border.",
    },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-h-006",
    topicId: "economy",
    difficulty: "hard",
    prompt: { en: "Who crosses the Canada–U.S. border in the millions each year?" },
    options: [
      { en: "Tourists from Asia" },
      { en: "Canadians and Americans" },
      { en: "European diplomats" },
      { en: "Mexican truckers only" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Millions of Canadians and Americans cross the border every year in safety.",
    },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-h-007",
    topicId: "economy",
    difficulty: "hard",
    prompt: { en: "The guide describes Canada–U.S. supply chains as ___." },
    options: [{ en: "Separated" }, { en: "Forbidden" }, { en: "Integrated" }, { en: "Temporary" }],
    answerIndex: 2,
    explanation: {
      en: "The guide refers to integrated Canada–U.S. supply chains that compete with the rest of the world.",
    },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-h-008",
    topicId: "economy",
    difficulty: "hard",
    prompt: { en: "Which Asian country is a G8 member according to the guide?" },
    options: [{ en: "China" }, { en: "India" }, { en: "South Korea" }, { en: "Japan" }],
    answerIndex: 3,
    explanation: {
      en: "Japan is listed among the G8 members: the United States, Germany, the United Kingdom, Italy, France, Japan and Russia.",
    },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-h-009",
    topicId: "economy",
    difficulty: "hard",
    prompt: { en: "Which of these is NOT listed as a G8 member?" },
    options: [{ en: "China" }, { en: "Japan" }, { en: "Russia" }, { en: "Italy" }],
    answerIndex: 0,
    explanation: {
      en: "The G8 members listed are the United States, Germany, the United Kingdom, Italy, France, Japan and Russia — China is not among them.",
    },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-h-010",
    topicId: "economy",
    difficulty: "hard",
    prompt: { en: "Which of these countries is listed as a G8 member?" },
    options: [{ en: "China" }, { en: "Russia" }, { en: "Mexico" }, { en: "Brazil" }],
    answerIndex: 1,
    explanation: { en: "Russia is listed as a G8 member." },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-h-011",
    topicId: "economy",
    difficulty: "hard",
    prompt: {
      en: "The guide names seven G8 countries besides Canada itself. This makes the G8 an ___-member group.",
    },
    options: [{ en: "Six" }, { en: "Seven" }, { en: "Eight" }, { en: "Ten" }],
    answerIndex: 2,
    explanation: {
      en: "Canada is part of the G8, and the guide names seven other members: the United States, Germany, the United Kingdom, Italy, France, Japan and Russia.",
    },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-h-012",
    topicId: "economy",
    difficulty: "hard",
    prompt: { en: "The guide presents the GATT as ___." },
    options: [
      { en: "The single treaty that created Canada" },
      { en: "A Canadian invention" },
      { en: "A military alliance" },
      { en: "One of the treaties that opened up restrictive trading policies" },
    ],
    answerIndex: 3,
    explanation: {
      en: 'The guide says the restrictive trading policies were opened up by "such treaties as" the GATT — the GATT being one example.',
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-h-013",
    topicId: "economy",
    difficulty: "hard",
    prompt: { en: "Which social program is the oldest?" },
    options: [
      { en: "Old Age Security (1927)" },
      { en: "Employment insurance (1940)" },
      { en: "The Canada and Quebec Pension Plans (1965)" },
      { en: "The Canada Health Act" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Old Age Security was devised as early as 1927, predating employment insurance (1940) and the 1965 pension plans.",
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-h-014",
    topicId: "economy",
    difficulty: "hard",
    prompt: { en: "Unemployment insurance was introduced by ___ in 1940." },
    options: [
      { en: "The provinces" },
      { en: "The federal government" },
      { en: "Private insurers" },
      { en: "The United Nations" },
    ],
    answerIndex: 1,
    explanation: { en: "Unemployment insurance was introduced by the federal government in 1940." },
    source: src("Modern Canada"),
  },
  {
    id: "eco-h-015",
    topicId: "economy",
    difficulty: "hard",
    prompt: { en: "In 1970, Canada ___ La Francophonie." },
    options: [{ en: "Founded alone" }, { en: "Left" }, { en: "Helped found" }, { en: "Boycotted" }],
    answerIndex: 2,
    explanation: {
      en: "In 1970, Canada helped found La Francophonie, an international association of French-speaking countries.",
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-h-016",
    topicId: "economy",
    difficulty: "hard",
    prompt: { en: "In 1982, the Constitution was amended ___." },
    options: [
      { en: "With Quebec's full support" },
      { en: "By the United States" },
      { en: "Without any debate" },
      { en: "Without the agreement of Quebec" },
    ],
    answerIndex: 3,
    explanation: { en: "In 1982 the Constitution was amended without the agreement of Quebec." },
    source: src("Modern Canada"),
  },
  {
    id: "eco-h-017",
    topicId: "economy",
    difficulty: "hard",
    prompt: { en: "Quebec sovereignty was defeated in a second referendum in ___." },
    options: [{ en: "1995" }, { en: "1985" }, { en: "2005" }, { en: "1975" }],
    answerIndex: 0,
    explanation: { en: "Sovereignty was again defeated in a second referendum in 1995." },
    source: src("Modern Canada"),
  },
  {
    id: "eco-h-018",
    topicId: "economy",
    difficulty: "hard",
    prompt: { en: "The first electric light bulb was invented by ___." },
    options: [
      { en: "Thomas Edison alone" },
      { en: "Mathew Evans and Henry Woodward" },
      { en: "Alexander Graham Bell" },
      { en: "Joseph Bombardier" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Mathew Evans and Henry Woodward together invented the first electric light bulb.",
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-h-019",
    topicId: "economy",
    difficulty: "hard",
    prompt: { en: "Evans and Woodward later sold their light bulb patent to ___." },
    options: [
      { en: "Alexander Graham Bell" },
      { en: "Henry Ford" },
      { en: "Thomas Edison" },
      { en: "George Westinghouse" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Evans and Woodward sold the patent to Thomas Edison, who commercialized the light bulb.",
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-h-020",
    topicId: "economy",
    difficulty: "hard",
    prompt: { en: "Reginald Fessenden sent the ___." },
    options: [
      { en: "First telegram" },
      { en: "First TV broadcast" },
      { en: "First email" },
      { en: "First wireless voice message in the world" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Reginald Fessenden contributed to the invention of radio, sending the first wireless voice message in the world.",
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-h-021",
    topicId: "economy",
    difficulty: "hard",
    prompt: { en: "Dr. Wilder Penfield was a pioneering brain surgeon at ___." },
    options: [
      { en: "McGill University in Montreal" },
      { en: "The University of Toronto" },
      { en: "UBC" },
      { en: "Oxford" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Dr. Wilder Penfield was a pioneering brain surgeon at McGill University in Montreal.",
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-h-022",
    topicId: "economy",
    difficulty: "hard",
    prompt: { en: "Dr. John A. Hopps invented the ___." },
    options: [
      { en: "First stethoscope" },
      { en: "First cardiac pacemaker" },
      { en: "First MRI scanner" },
      { en: "First hearing aid" },
    ],
    answerIndex: 1,
    explanation: { en: "Dr. John A. Hopps invented the first cardiac pacemaker." },
    source: src("Modern Canada"),
  },
  {
    id: "eco-h-023",
    topicId: "economy",
    difficulty: "hard",
    prompt: { en: "Gerhard Herzberg, a Nobel Prize-winning scientist, was a refugee from ___." },
    options: [
      { en: "Soviet Russia" },
      { en: "Fascist Italy" },
      { en: "Nazi Germany" },
      { en: "Communist China" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Gerhard Herzberg, a refugee from Nazi Germany, was a Nobel Prize-winning scientist.",
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-h-024",
    topicId: "economy",
    difficulty: "hard",
    prompt: { en: "Which of these is named as a Nobel Prize-winning scientist?" },
    options: [
      { en: "Alexander Graham Bell" },
      { en: "Joseph Bombardier" },
      { en: "James Naismith" },
      { en: "John Polanyi" },
    ],
    answerIndex: 3,
    explanation: { en: "John Polanyi is named among the Nobel Prize-winning scientists." },
    source: src("Modern Canada"),
  },
  {
    id: "eco-h-025",
    topicId: "economy",
    difficulty: "hard",
    prompt: { en: 'Sir Frederick Banting is identified as being "of" ___.' },
    options: [{ en: "Toronto" }, { en: "Montreal" }, { en: "Vancouver" }, { en: "Ottawa" }],
    answerIndex: 0,
    explanation: {
      en: "The guide identifies Sir Frederick Banting of Toronto, who discovered insulin with Charles Best.",
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-h-026",
    topicId: "economy",
    difficulty: "hard",
    prompt: { en: "Insulin is described as a hormone to treat ___." },
    options: [{ en: "Cancer" }, { en: "Diabetes" }, { en: "Asthma" }, { en: "Flu" }],
    answerIndex: 1,
    explanation: {
      en: "Insulin is described as a hormone to treat diabetes that has saved 16 million lives.",
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-h-027",
    topicId: "economy",
    difficulty: "hard",
    prompt: { en: "The 37,000 refugees of 1956 had escaped ___." },
    options: [
      { en: "Nazi occupation of France" },
      { en: "Famine in Ireland" },
      { en: "Soviet tyranny in Hungary" },
      { en: "War in Korea" },
    ],
    answerIndex: 2,
    explanation: { en: "About 37,000 refugees escaped Soviet tyranny in Hungary in 1956." },
    source: src("Modern Canada"),
  },
  {
    id: "eco-h-028",
    topicId: "economy",
    difficulty: "hard",
    prompt: { en: "The Vietnamese refugees fled after ___." },
    options: [
      { en: "The 1976 Olympics" },
      { en: "A 1975 earthquake" },
      { en: "The 1974 recession" },
      { en: "The Communist victory in the Vietnam War in 1975" },
    ],
    answerIndex: 3,
    explanation: {
      en: "With the Communist victory in the Vietnam War in 1975, many Vietnamese fled, including over 50,000 who sought refuge in Canada.",
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-h-029",
    topicId: "economy",
    difficulty: "hard",
    prompt: { en: "By the 1960s, one-third of Canadians had origins that were ___." },
    options: [
      { en: "Neither British nor French" },
      { en: "Only British" },
      { en: "Only French" },
      { en: "Neither European nor Asian" },
    ],
    answerIndex: 0,
    explanation: {
      en: "By the 1960s, one-third of Canadians had origins that were neither British nor French.",
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-h-030",
    topicId: "economy",
    difficulty: "hard",
    prompt: {
      en: '"As social values changed over ___, Canada became a more flexible and open society."',
    },
    options: [
      { en: "Five years" },
      { en: "More than 50 years" },
      { en: "Ten years" },
      { en: "Twenty years" },
    ],
    answerIndex: 1,
    explanation: {
      en: "As social values changed over more than 50 years, Canada became a more flexible and open society.",
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-h-031",
    topicId: "economy",
    difficulty: "hard",
    prompt: { en: 'Canada became a "more ___" society.' },
    options: [
      { en: "Closed and rigid" },
      { en: "Secretive and strict" },
      { en: "Flexible and open" },
      { en: "Divided and hostile" },
    ],
    answerIndex: 2,
    explanation: { en: "Canada became a more flexible and open society." },
    source: src("Modern Canada"),
  },
  {
    id: "eco-h-032",
    topicId: "economy",
    difficulty: "hard",
    prompt: {
      en: "In the past, most Canadians of Asian descent had been denied the vote in ___ elections.",
    },
    options: [
      { en: "Municipal only" },
      { en: "Foreign" },
      { en: "School board" },
      { en: "Federal and provincial" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Most Canadians of Asian descent had in the past been denied the vote in federal and provincial elections.",
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-h-033",
    topicId: "economy",
    difficulty: "hard",
    prompt: { en: "In the postwar years, French-Canadian society and culture ___." },
    options: [
      { en: "Flourished" },
      { en: "Disappeared" },
      { en: "Moved abroad" },
      { en: "Stood still" },
    ],
    answerIndex: 0,
    explanation: { en: "French-Canadian society and culture flourished in the postwar years." },
    source: src("Modern Canada"),
  },
  {
    id: "eco-h-034",
    topicId: "economy",
    difficulty: "hard",
    prompt: { en: "In the postwar era, many Quebecers sought to ___ from Canada." },
    options: [
      { en: "Move the capital to" },
      { en: "Separate" },
      { en: "Merge with the U.S." },
      { en: "Ban French in" },
    ],
    answerIndex: 1,
    explanation: { en: "Many Quebecers sought to separate from Canada." },
    source: src("Modern Canada"),
  },
  {
    id: "eco-h-035",
    topicId: "economy",
    difficulty: "hard",
    prompt: { en: "The autonomy of Quebec within Canada remains a ___ topic." },
    options: [{ en: "Forgotten" }, { en: "Banned" }, { en: "Lively" }, { en: "Settled" }],
    answerIndex: 2,
    explanation: { en: "The autonomy of Quebec within Canada remains a lively topic." },
    source: src("Modern Canada"),
  },
  {
    id: "eco-h-036",
    topicId: "economy",
    difficulty: "hard",
    prompt: { en: "Canada welcomed thousands of refugees from ___." },
    options: [
      { en: "Natural disasters" },
      { en: "Economic recessions" },
      { en: "Overpopulation" },
      { en: "Communist oppression" },
    ],
    answerIndex: 3,
    explanation: { en: "Canada welcomed thousands of refugees from Communist oppression." },
    source: src("Modern Canada"),
  },
  {
    id: "eco-h-037",
    topicId: "economy",
    difficulty: "hard",
    prompt: { en: "Today, ___ over the age of 18 may vote." },
    options: [
      { en: "Every citizen" },
      { en: "Every resident" },
      { en: "Every taxpayer" },
      { en: "Every homeowner" },
    ],
    answerIndex: 0,
    explanation: { en: "Today every citizen over the age of 18 may vote." },
    source: src("Modern Canada"),
  },
  {
    id: "eco-h-038",
    topicId: "economy",
    difficulty: "hard",
    prompt: { en: 'The "$1 trillion" NAFTA figure refers to ___.' },
    options: [
      { en: "Services trade in 1994" },
      { en: "Merchandise trade in 2008" },
      { en: "Tourism in 2008" },
      { en: "Foreign aid in 2008" },
    ],
    answerIndex: 1,
    explanation: { en: "NAFTA had over $1 trillion in merchandise trade in 2008." },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-h-039",
    topicId: "economy",
    difficulty: "hard",
    prompt: { en: "Which statement about the guide's manufactured-products list is accurate?" },
    options: [
      { en: "It lists exactly three products" },
      { en: "It lists no products at all" },
      { en: 'It names seven examples plus "many other goods"' },
      { en: "It lists only automobiles" },
    ],
    answerIndex: 2,
    explanation: {
      en: 'The guide names paper, high technology equipment, aerospace technology, automobiles, machinery, food and clothing — seven examples — plus "many other goods."',
    },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-h-040",
    topicId: "economy",
    difficulty: "hard",
    prompt: {
      en: 'The guide uses "more than 75%" for service jobs and "over three-quarters" for exports to the U.S. These phrases both mean ___.',
    },
    options: [
      { en: "Exactly 75 percent" },
      { en: "Below 75 percent" },
      { en: "About 50 percent" },
      { en: "Above 75 percent" },
    ],
    answerIndex: 3,
    explanation: { en: 'Both "more than 75%" and "over three-quarters" mean above 75 percent.' },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-h-041",
    topicId: "economy",
    difficulty: "hard",
    prompt: { en: "The economy chapter's first section is titled ___." },
    options: [
      { en: "A Trading Nation" },
      { en: "A Farming Nation" },
      { en: "A Quiet Revolution" },
      { en: "A New Currency" },
    ],
    answerIndex: 0,
    explanation: { en: 'The economy chapter opens with the section "A Trading Nation."' },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-h-042",
    topicId: "economy",
    difficulty: "hard",
    prompt: { en: "The Modern Canada chapter section on the economy is titled ___." },
    options: [
      { en: "War and Peace" },
      { en: "Trade and Economic Growth" },
      { en: "Arts and Culture" },
      { en: "Sports and Games" },
    ],
    answerIndex: 1,
    explanation: {
      en: 'The Modern Canada chapter includes the section "Trade and Economic Growth."',
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-h-043",
    topicId: "economy",
    difficulty: "hard",
    prompt: { en: "The 1951 list of newly affordable basics ends with ___." },
    options: [{ en: "Cars" }, { en: "Phones" }, { en: "Clothing" }, { en: "Televisions" }],
    answerIndex: 2,
    explanation: {
      en: "In 1951, a majority of Canadians could afford adequate food, shelter and clothing.",
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-h-044",
    topicId: "economy",
    difficulty: "hard",
    prompt: { en: "Between 1945 and 1970, Canada drew closer to the U.S. and ___." },
    options: [
      { en: "No one else" },
      { en: "Only Mexico" },
      { en: "Only Britain" },
      { en: "Other trading partners" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Between 1945 and 1970, Canada drew closer to the United States and other trading partners.",
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-h-045",
    topicId: "economy",
    difficulty: "hard",
    prompt: { en: 'Canada\'s high standard of living is maintained "by the hard work of ___."' },
    options: [
      { en: "Canadians" },
      { en: "Americans" },
      { en: "Immigrants only" },
      { en: "Robots" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The standard of living is maintained by the hard work of Canadians and by trade with other nations.",
    },
    source: src("Modern Canada"),
  },
];
