/**
 * Question bank chunk — part of questions.generated.ts. DO NOT EDIT BY HAND.
 */
import type { Question } from "../content";
import { src } from "./shared";

export const economyA: Question[] = [
  {
    id: "eco-e-001",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: 'According to Discover Canada, Canada has "always been" what?' },
    options: [
      { en: "A trading nation" },
      { en: "A farming nation" },
      { en: "An isolated nation" },
      { en: "A manufacturing-only nation" },
    ],
    answerIndex: 0,
    explanation: { en: "Discover Canada states that Canada has always been a trading nation." },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-e-002",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: 'Discover Canada calls commerce the "engine of" what?' },
    options: [
      { en: "Population growth" },
      { en: "Economic growth" },
      { en: "Political change" },
      { en: "Cultural decline" },
    ],
    answerIndex: 1,
    explanation: { en: "The guide says commerce remains the engine of economic growth." },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-e-003",
    topicId: "economy",
    difficulty: "easy",
    prompt: {
      en: '"As Canadians, we could not maintain our ___ without engaging in trade with other nations."',
    },
    options: [
      { en: "Hockey teams" },
      { en: "National anthem" },
      { en: "Standard of living" },
      { en: "Official languages" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The guide says Canadians could not maintain their standard of living without engaging in trade.",
    },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-e-004",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "In which year did Canada enact free trade with the United States?" },
    options: [{ en: "1978" }, { en: "1994" }, { en: "2001" }, { en: "1988" }],
    answerIndex: 3,
    explanation: { en: "Canada enacted free trade with the United States in 1988." },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-e-005",
    topicId: "economy",
    difficulty: "easy",
    prompt: {
      en: "Which country became a NAFTA partner alongside Canada and the United States in 1994?",
    },
    options: [{ en: "Mexico" }, { en: "Brazil" }, { en: "Japan" }, { en: "Germany" }],
    answerIndex: 0,
    explanation: {
      en: "Mexico became a partner in 1994 in the broader North American Free Trade Agreement (NAFTA).",
    },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-e-006",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "What does NAFTA stand for?" },
    options: [
      { en: "National Association of Free Traders of America" },
      { en: "North American Free Trade Agreement" },
      { en: "North Atlantic Fisheries Trade Accord" },
      { en: "Northern American Financial Trust Association" },
    ],
    answerIndex: 1,
    explanation: { en: "NAFTA stands for the North American Free Trade Agreement." },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-e-007",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "Canada has one of the ___ largest economies in the world." },
    options: [{ en: "Five" }, { en: "Fifteen" }, { en: "Ten" }, { en: "Twenty" }],
    answerIndex: 2,
    explanation: {
      en: "The guide states Canada has one of the ten largest economies in the world.",
    },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-e-008",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "Canada is part of the G8, a group of leading ___ countries." },
    options: [
      { en: "Developing" },
      { en: "Agricultural" },
      { en: "Island" },
      { en: "Industrialized" },
    ],
    answerIndex: 3,
    explanation: { en: "The G8 is described as a group of leading industrialized countries." },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-e-009",
    topicId: "economy",
    difficulty: "easy",
    prompt: {
      en: "According to Discover Canada, Canada's largest international trading partner is ___.",
    },
    options: [
      { en: "The United States" },
      { en: "China" },
      { en: "Japan" },
      { en: "The United Kingdom" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The guide states that Canada's largest international trading partner is the United States.",
    },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-e-010",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "Canada and the United States are each ___ largest trading partner." },
    options: [{ en: "Asia's" }, { en: "The other's" }, { en: "Europe's" }, { en: "Nobody's" }],
    answerIndex: 1,
    explanation: {
      en: "The guide says Canada and the United States are each the other's largest trading partner.",
    },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-e-011",
    topicId: "economy",
    difficulty: "easy",
    prompt: {
      en: "The Canada–U.S. border is traditionally known as the world's longest ___ border.",
    },
    options: [{ en: "Guarded" }, { en: "Fenced" }, { en: "Undefended" }, { en: "Closed" }],
    answerIndex: 2,
    explanation: {
      en: "The border is traditionally known as the world's longest undefended border.",
    },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-e-012",
    topicId: "economy",
    difficulty: "easy",
    prompt: {
      en: "Which list correctly names the three main types of industries in Canada's economy?",
    },
    options: [
      { en: "Farming, mining and banking" },
      { en: "Tourism, sports and film" },
      { en: "Fishing, oil and technology" },
      { en: "Service, manufacturing and natural resources" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Canada's economy includes three main types of industries: service, manufacturing and natural resources.",
    },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-e-013",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "More than ___ of working Canadians have jobs in service industries." },
    options: [{ en: "75%" }, { en: "25%" }, { en: "50%" }, { en: "90%" }],
    answerIndex: 0,
    explanation: { en: "More than 75% of working Canadians now have jobs in service industries." },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-e-014",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "Service industries provide thousands of different ___." },
    options: [{ en: "Tariffs" }, { en: "Jobs" }, { en: "Products" }, { en: "Exports" }],
    answerIndex: 1,
    explanation: {
      en: "Service industries provide thousands of different jobs in areas like transportation, education and health care.",
    },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-e-015",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "Manufacturing industries make products to sell ___." },
    options: [
      { en: "Only in Ontario" },
      { en: "Only to the United States" },
      { en: "In Canada and around the world" },
      { en: "Only online" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Manufacturing industries make products to sell in Canada and around the world.",
    },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-e-016",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "Which of the following is listed as a manufactured product?" },
    options: [{ en: "Crude oil" }, { en: "Raw timber" }, { en: "Iron ore" }, { en: "Automobiles" }],
    answerIndex: 3,
    explanation: {
      en: "Automobiles are listed among manufactured products, along with paper, machinery, food and clothing.",
    },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-e-017",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "The guide lists ___ among manufactured products." },
    options: [{ en: "Paper" }, { en: "Raw logs" }, { en: "Uncut fish" }, { en: "Crude oil" }],
    answerIndex: 0,
    explanation: { en: "Paper is listed among Canada's manufactured products." },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-e-018",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "Which of these is a natural resources industry?" },
    options: [{ en: "Banking" }, { en: "Forestry" }, { en: "Tourism" }, { en: "Retail services" }],
    answerIndex: 1,
    explanation: {
      en: "Forestry is one of the natural resources industries, along with fishing, agriculture, mining and energy.",
    },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-e-019",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "Fishing is an example of which type of industry?" },
    options: [
      { en: "Service" },
      { en: "Manufacturing" },
      { en: "Natural resources" },
      { en: "Financial" },
    ],
    answerIndex: 2,
    explanation: { en: "Fishing is listed as a natural resources industry." },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-e-020",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "Which pair are both natural resources industries?" },
    options: [
      { en: "Banking and tourism" },
      { en: "Paper and clothing" },
      { en: "Education and health care" },
      { en: "Mining and energy" },
    ],
    answerIndex: 3,
    explanation: { en: "Mining and energy are both natural resources industries." },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-e-021",
    topicId: "economy",
    difficulty: "easy",
    prompt: {
      en: "Natural resources industries include forestry, fishing, agriculture, mining and ___.",
    },
    options: [{ en: "Energy" }, { en: "Banking" }, { en: "Tourism" }, { en: "Software" }],
    answerIndex: 0,
    explanation: {
      en: "The five natural resources industries are forestry, fishing, agriculture, mining and energy.",
    },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-e-022",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "Agriculture belongs to which industry type?" },
    options: [
      { en: "Technology industries" },
      { en: "Natural resources industries" },
      { en: "Service industries" },
      { en: "Manufacturing industries" },
    ],
    answerIndex: 1,
    explanation: { en: "Agriculture is listed as a natural resources industry." },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-e-023",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "Over ___ of Canadian exports are destined for the U.S.A." },
    options: [
      { en: "One-quarter" },
      { en: "One-half" },
      { en: "Three-quarters" },
      { en: "One-tenth" },
    ],
    answerIndex: 2,
    explanation: { en: "Over three-quarters of Canadian exports are destined for the U.S.A." },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-e-024",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "Canada and the U.S. have the biggest ___ in the world." },
    options: [
      { en: "Military alliance" },
      { en: "Shared currency" },
      { en: "Common parliament" },
      { en: "Bilateral trading relationship" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The guide states that Canada and the U.S. have the biggest bilateral trading relationship in the world.",
    },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-e-025",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "Canada exports ___ worth of goods to the United States every year." },
    options: [
      { en: "Billions of dollars" },
      { en: "Millions of dollars" },
      { en: "Thousands of dollars" },
      { en: "Trillions of dollars" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Canada exports billions of dollars worth of goods to the United States every year.",
    },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-e-026",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "Which of these is listed among Canada's exports to the U.S.?" },
    options: [
      { en: "Tropical fruit" },
      { en: "Energy products" },
      { en: "Coffee beans" },
      { en: "Rice" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Energy products are listed among the goods Canada exports to the United States every year.",
    },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-e-027",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "Canada exports billions of dollars worth of ___ products every year." },
    options: [{ en: "Textile" }, { en: "Ceramic" }, { en: "Automotive" }, { en: "Toy" }],
    answerIndex: 2,
    explanation: {
      en: "Automotive products are listed among Canada's annual exports to the United States.",
    },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-e-028",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "The Peace Arch stands at Blaine in which U.S. state?" },
    options: [{ en: "Oregon" }, { en: "California" }, { en: "Montana" }, { en: "Washington" }],
    answerIndex: 3,
    explanation: { en: "The Peace Arch is at Blaine in the State of Washington." },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-e-029",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "The Peace Arch symbolizes Canada's ___ with the United States." },
    options: [
      { en: "Close ties and common interests" },
      { en: "Trade disputes" },
      { en: "Border conflicts" },
      { en: "Political union" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The Peace Arch symbolizes Canada's close ties and common interests with the United States.",
    },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-e-030",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "Discover Canada says Canada enjoys ___ relations with the United States." },
    options: [{ en: "Distant" }, { en: "Close" }, { en: "Tense" }, { en: "Formal" }],
    answerIndex: 1,
    explanation: {
      en: "The guide states that Canada enjoys close relations with the United States.",
    },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-e-031",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "The guide's photo of oil pumpjacks was taken in which part of Alberta?" },
    options: [{ en: "Northern" }, { en: "Eastern" }, { en: "Southern" }, { en: "Central" }],
    answerIndex: 2,
    explanation: { en: "The photo caption shows oil pumpjacks in southern Alberta." },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-e-032",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "Which seafood product represents Atlantic Canada in the guide's photos?" },
    options: [{ en: "Salmon" }, { en: "Tuna" }, { en: "Shrimp" }, { en: "Lobster" }],
    answerIndex: 3,
    explanation: { en: "Atlantic lobster is pictured in the economy chapter." },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-e-033",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "A lumber truck pictured in the guide illustrates which industry?" },
    options: [{ en: "Forestry" }, { en: "Fishing" }, { en: "Mining" }, { en: "Banking" }],
    answerIndex: 0,
    explanation: { en: "The lumber truck illustrates the forestry industry." },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-e-034",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "The car assembly plant pictured in the guide is in which province?" },
    options: [{ en: "Quebec" }, { en: "Ontario" }, { en: "Alberta" }, { en: "Manitoba" }],
    answerIndex: 1,
    explanation: { en: "The pictured car assembly plant is in Oakville, Ontario." },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-e-035",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "The research laboratory photo features products from which company?" },
    options: [{ en: "Nokia" }, { en: "Apple" }, { en: "RIM" }, { en: "Samsung" }],
    answerIndex: 2,
    explanation: { en: "The photo shows a research laboratory for RIM's BlackBerry." },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-e-036",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "Ice wine grapes are pictured from which Ontario region?" },
    options: [{ en: "Muskoka" }, { en: "Kawartha" }, { en: "Essex" }, { en: "Niagara" }],
    answerIndex: 3,
    explanation: { en: "Ice wine grapes are pictured from the Niagara Region, Ontario." },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-e-037",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "The hydro-electric dam pictured in the guide is in which province?" },
    options: [{ en: "Quebec" }, { en: "Ontario" }, { en: "British Columbia" }, { en: "Manitoba" }],
    answerIndex: 0,
    explanation: { en: "The pictured hydro-electric dam is on the Saguenay River, Quebec." },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-e-038",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "Which Canadian port city is pictured in the economy chapter?" },
    options: [{ en: "Halifax" }, { en: "Vancouver" }, { en: "Montreal" }, { en: "Toronto" }],
    answerIndex: 1,
    explanation: { en: "The Port of Vancouver is pictured in the economy chapter." },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-e-039",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "Postwar Canada enjoyed record ___." },
    options: [
      { en: "Inflation" },
      { en: "Unemployment" },
      { en: "Prosperity" },
      { en: "Deficits" },
    ],
    answerIndex: 2,
    explanation: { en: "Postwar Canada enjoyed record prosperity and material progress." },
    source: src("Modern Canada"),
  },
  {
    id: "eco-e-040",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "In which year was oil discovered in Alberta?" },
    options: [{ en: "1937" }, { en: "1957" }, { en: "1967" }, { en: "1947" }],
    answerIndex: 3,
    explanation: { en: "Oil was discovered in Alberta in 1947." },
    source: src("Modern Canada"),
  },
  {
    id: "eco-e-041",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "The 1947 oil discovery began Canada's modern ___ industry." },
    options: [{ en: "Energy" }, { en: "Steel" }, { en: "Textile" }, { en: "Film" }],
    answerIndex: 0,
    explanation: {
      en: "The discovery of oil in Alberta in 1947 began Canada's modern energy industry.",
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-e-042",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "The General Agreement on Tariffs and Trade (GATT) is now the ___." },
    options: [
      { en: "World Bank" },
      { en: "World Trade Organization" },
      { en: "International Monetary Fund" },
      { en: "United Nations" },
    ],
    answerIndex: 1,
    explanation: { en: "The GATT is now the World Trade Organization (WTO)." },
    source: src("Modern Canada"),
  },
  {
    id: "eco-e-043",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "What does GATT stand for?" },
    options: [
      { en: "Global Alliance for Trade and Travel" },
      { en: "General Assembly on Taxes and Tariffs" },
      { en: "General Agreement on Tariffs and Trade" },
      { en: "Greater American Trade Treaty" },
    ],
    answerIndex: 2,
    explanation: { en: "GATT stands for the General Agreement on Tariffs and Trade." },
    source: src("Modern Canada"),
  },
  {
    id: "eco-e-044",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "What does WTO stand for?" },
    options: [
      { en: "World Trade Office" },
      { en: "Western Trade Organization" },
      { en: "World Tariff Office" },
      { en: "World Trade Organization" },
    ],
    answerIndex: 3,
    explanation: { en: "WTO stands for the World Trade Organization." },
    source: src("Modern Canada"),
  },
  {
    id: "eco-e-045",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "Which law ensures common elements and a basic standard of health coverage?" },
    options: [
      { en: "The Canada Health Act" },
      { en: "The Health Tax Act" },
      { en: "The Medical Fees Act" },
      { en: "The Hospital Closure Act" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The Canada Health Act ensures common elements and a basic standard of coverage.",
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-e-046",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "Unemployment insurance was introduced in ___." },
    options: [{ en: "1930" }, { en: "1940" }, { en: "1950" }, { en: "1960" }],
    answerIndex: 1,
    explanation: {
      en: "Unemployment insurance, now called employment insurance, was introduced in 1940.",
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-e-047",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "Old Age Security was devised as early as ___." },
    options: [{ en: "1937" }, { en: "1947" }, { en: "1927" }, { en: "1957" }],
    answerIndex: 2,
    explanation: { en: "Old Age Security was devised as early as 1927." },
    source: src("Modern Canada"),
  },
  {
    id: "eco-e-048",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "The Canada Pension Plan dates to ___." },
    options: [{ en: "1955" }, { en: "1975" }, { en: "1985" }, { en: "1965" }],
    answerIndex: 3,
    explanation: { en: "The Canada and Quebec Pension Plans date to 1965." },
    source: src("Modern Canada"),
  },
  {
    id: "eco-e-049",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "Which pension plan was created alongside the Canada Pension Plan in 1965?" },
    options: [
      { en: "The Quebec Pension Plan" },
      { en: "The Ontario Pension Plan" },
      { en: "The Western Pension Plan" },
      { en: "The Atlantic Pension Plan" },
    ],
    answerIndex: 0,
    explanation: { en: "The Canada and Quebec Pension Plans were both established in 1965." },
    source: src("Modern Canada"),
  },
  {
    id: "eco-e-050",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "Today, every citizen over the age of ___ may vote." },
    options: [{ en: "16" }, { en: "18" }, { en: "19" }, { en: "21" }],
    answerIndex: 1,
    explanation: { en: "Today every citizen over the age of 18 may vote." },
    source: src("Modern Canada"),
  },
  {
    id: "eco-e-051",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "Which city's business district is described as Canada's financial capital?" },
    options: [{ en: "Montreal" }, { en: "Vancouver" }, { en: "Toronto" }, { en: "Calgary" }],
    answerIndex: 2,
    explanation: { en: "Toronto's business district is described as Canada's financial capital." },
    source: src("Modern Canada"),
  },
  {
    id: "eco-e-052",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "Banting and Best discovered ___, a hormone to treat diabetes." },
    options: [{ en: "Penicillin" }, { en: "Adrenaline" }, { en: "Morphine" }, { en: "Insulin" }],
    answerIndex: 3,
    explanation: {
      en: "Sir Frederick Banting and Charles Best discovered insulin, a hormone to treat diabetes.",
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-e-053",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "Diversity enriches Canadians' lives, particularly in ___." },
    options: [{ en: "Cities" }, { en: "Villages" }, { en: "Farms" }, { en: "Mines" }],
    answerIndex: 0,
    explanation: {
      en: "The guide says diversity enriches Canadians' lives, particularly in cities.",
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-e-054",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "A growing number of women entered the ___ work force." },
    options: [{ en: "Volunteer" }, { en: "Professional" }, { en: "Military" }, { en: "Seasonal" }],
    answerIndex: 1,
    explanation: { en: "A growing number of women entered the professional work force." },
    source: src("Modern Canada"),
  },
  {
    id: "eco-e-055",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "Who invented the snowmobile?" },
    options: [
      { en: "Alexander Graham Bell" },
      { en: "Sandford Fleming" },
      { en: "Joseph-Armand Bombardier" },
      { en: "John Hopps" },
    ],
    answerIndex: 2,
    explanation: { en: "Joseph-Armand Bombardier invented the snowmobile." },
    source: src("Modern Canada"),
  },
  {
    id: "eco-e-056",
    topicId: "economy",
    difficulty: "easy",
    prompt: {
      en: "Alexander Graham Bell hit on the idea of the telephone at his summer house in ___.",
    },
    options: [{ en: "Scotland" }, { en: "England" }, { en: "The United States" }, { en: "Canada" }],
    answerIndex: 3,
    explanation: {
      en: "Alexander Graham Bell hit on the idea of the telephone at his summer house in Canada.",
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-e-057",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "Who invented the world system of standard time zones?" },
    options: [
      { en: "Sir Sandford Fleming" },
      { en: "Reginald Fessenden" },
      { en: "Wilder Penfield" },
      { en: "John Hopps" },
    ],
    answerIndex: 0,
    explanation: { en: "Sir Sandford Fleming invented the world system of standard time zones." },
    source: src("Modern Canada"),
  },
  {
    id: "eco-e-058",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "Canadians enjoy one of the world's highest ___." },
    options: [
      { en: "Tax rates" },
      { en: "Standards of living" },
      { en: "Speed limits" },
      { en: "Mountain ranges" },
    ],
    answerIndex: 1,
    explanation: { en: "Canadians enjoy one of the world's highest standards of living." },
    source: src("Modern Canada"),
  },
  {
    id: "eco-e-059",
    topicId: "economy",
    difficulty: "easy",
    prompt: {
      en: "In 1951, for the first time, a majority of Canadians could afford adequate ___.",
    },
    options: [
      { en: "Cars, boats and planes" },
      { en: "Phones, TVs and radios" },
      { en: "Food, shelter and clothing" },
      { en: "Stocks, bonds and funds" },
    ],
    answerIndex: 2,
    explanation: {
      en: "In 1951, for the first time, a majority of Canadians could afford adequate food, shelter and clothing.",
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-e-060",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "Canada's high standard of living is maintained by hard work and ___." },
    options: [
      { en: "Foreign aid" },
      { en: "Lottery winnings" },
      { en: "Inheritance" },
      { en: "Trade with other nations" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The standard of living is maintained by the hard work of Canadians and by trade with other nations.",
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-e-061",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "Publicly funded education is provided by ___." },
    options: [
      { en: "The provinces and territories" },
      { en: "The federal government alone" },
      { en: "Private companies" },
      { en: "The United Nations" },
    ],
    answerIndex: 0,
    explanation: { en: "Publicly funded education is provided by the provinces and territories." },
    source: src("Modern Canada"),
  },
  {
    id: "eco-e-062",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "Natural resources industries have played an important part in Canada's ___." },
    options: [
      { en: "Sports and music" },
      { en: "History and development" },
      { en: "Fashion and film" },
      { en: "Myths and legends" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Natural resources industries have played an important part in the country's history and development.",
    },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-e-063",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "Today, the economy of many areas of the country still depends on ___." },
    options: [
      { en: "Importing luxury goods" },
      { en: "Printing money" },
      { en: "Developing natural resources" },
      { en: "Hosting festivals" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Today, the economy of many areas of the country still depends on developing natural resources.",
    },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-e-064",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "A large percentage of Canada's exports are ___ commodities." },
    options: [
      { en: "Banking" },
      { en: "Tourism" },
      { en: "Software" },
      { en: "Natural resources" },
    ],
    answerIndex: 3,
    explanation: {
      en: "A large percentage of Canada's exports are natural resources commodities.",
    },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-e-065",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "Who invented basketball?" },
    options: [
      { en: "James Naismith" },
      { en: "Wayne Gretzky" },
      { en: "Terry Fox" },
      { en: "Donovan Bailey" },
    ],
    answerIndex: 0,
    explanation: { en: "Basketball was invented by Canadian James Naismith." },
    source: src("Modern Canada"),
  },
  {
    id: "eco-e-066",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "The Canadarm is a ___ used in outer space." },
    options: [
      { en: "Telescope" },
      { en: "Robotic arm" },
      { en: "Satellite" },
      { en: "Space suit" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The Canadarm is a robotic arm used in outer space, invented by SPAR Aerospace and the National Research Council.",
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-e-067",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "The BlackBerry was the most famous invention of ___." },
    options: [
      { en: "SPAR Aerospace" },
      { en: "Bell Canada" },
      { en: "Research in Motion (RIM)" },
      { en: "Nortel" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Research in Motion (RIM), a wireless communications company, is known for its most famous invention, the BlackBerry.",
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-e-068",
    topicId: "economy",
    difficulty: "easy",
    prompt: {
      en: "Between 1945 and 1970, Canada enjoyed one of the strongest economies among ___.",
    },
    options: [
      { en: "Tropical nations" },
      { en: "Island nations" },
      { en: "Desert nations" },
      { en: "Industrialized nations" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Between 1945 and 1970, Canada enjoyed one of the strongest economies among industrialized nations.",
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-e-069",
    topicId: "economy",
    difficulty: "easy",
    prompt: {
      en: "Treaties such as the GATT opened up the world's ___ trading policies of the Depression era.",
    },
    options: [{ en: "Restrictive" }, { en: "Generous" }, { en: "Secret" }, { en: "Modern" }],
    answerIndex: 0,
    explanation: {
      en: "The world's restrictive trading policies in the Depression era were opened up by treaties such as the GATT.",
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-e-070",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "The Canada Health Act ensures common elements and a basic standard of ___." },
    options: [{ en: "Taxation" }, { en: "Coverage" }, { en: "Censorship" }, { en: "Conscription" }],
    answerIndex: 1,
    explanation: {
      en: "The Canada Health Act ensures common elements and a basic standard of coverage.",
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-e-071",
    topicId: "economy",
    difficulty: "easy",
    prompt: { en: "Unemployment insurance is now called ___." },
    options: [
      { en: "Retirement insurance" },
      { en: "Disability insurance" },
      { en: "Employment insurance" },
      { en: "Travel insurance" },
    ],
    answerIndex: 2,
    explanation: { en: "Unemployment insurance is now called employment insurance." },
    source: src("Modern Canada"),
  },
  {
    id: "eco-e-072",
    topicId: "economy",
    difficulty: "easy",
    prompt: {
      en: "The idea of multiculturalism gained a new impetus as a result of ___ immigration.",
    },
    options: [
      { en: "16th-century" },
      { en: "18th-century" },
      { en: "21st-century" },
      { en: "19th- and 20th-century" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The idea of multiculturalism, as a result of 19th- and 20th-century immigration, gained a new impetus.",
    },
    source: src("Modern Canada"),
  },
  {
    id: "eco-m-001",
    topicId: "economy",
    difficulty: "medium",
    prompt: { en: "NAFTA covers over ___ people." },
    options: [
      { en: "444 million" },
      { en: "244 million" },
      { en: "144 million" },
      { en: "544 million" },
    ],
    answerIndex: 0,
    explanation: { en: "NAFTA covers over 444 million people." },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-m-002",
    topicId: "economy",
    difficulty: "medium",
    prompt: { en: 'Mexico joined the "broader" NAFTA in 1994 — broader than what?' },
    options: [
      { en: "The GATT" },
      { en: "The 1988 Canada–U.S. free trade deal" },
      { en: "The WTO" },
      { en: "The G8" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Mexico became a partner in 1994 in the broader NAFTA, following the 1988 Canada–U.S. free trade deal.",
    },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-m-003",
    topicId: "economy",
    difficulty: "medium",
    prompt: { en: "The guide lists ___ as an area where service industries provide jobs." },
    options: [{ en: "Mining" }, { en: "Forestry" }, { en: "Tourism" }, { en: "Fishing" }],
    answerIndex: 2,
    explanation: { en: "Tourism is listed among the areas where service industries provide jobs." },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-m-004",
    topicId: "economy",
    difficulty: "medium",
    prompt: { en: "Banking is mentioned as part of which industry type?" },
    options: [
      { en: "Manufacturing" },
      { en: "Natural resources" },
      { en: "Energy" },
      { en: "Service industries" },
    ],
    answerIndex: 3,
    explanation: { en: "Banking is listed as an area of service industries." },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-m-005",
    topicId: "economy",
    difficulty: "medium",
    prompt: { en: "Which of these service-industry areas relates to schools?" },
    options: [
      { en: "Education" },
      { en: "Oil drilling" },
      { en: "Logging" },
      { en: "Auto assembly" },
    ],
    answerIndex: 0,
    explanation: { en: "Education is listed as an area where service industries provide jobs." },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-m-006",
    topicId: "economy",
    difficulty: "medium",
    prompt: { en: "Health care is listed as an area of ___." },
    options: [
      { en: "Manufacturing industries" },
      { en: "Service industries" },
      { en: "Natural resources industries" },
      { en: "Mining industries" },
    ],
    answerIndex: 1,
    explanation: { en: "Health care is listed as an area of service industries." },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-m-007",
    topicId: "economy",
    difficulty: "medium",
    prompt: { en: "Which of these is NOT listed as a service-industry area?" },
    options: [{ en: "Tourism" }, { en: "Banking" }, { en: "Mining" }, { en: "Communications" }],
    answerIndex: 2,
    explanation: {
      en: "Mining is a natural resources industry, not one of the listed service-industry areas.",
    },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-m-008",
    topicId: "economy",
    difficulty: "medium",
    prompt: { en: "Which of these is listed as a manufactured product?" },
    options: [
      { en: "Raw lumber" },
      { en: "Crude oil" },
      { en: "Wheat grain" },
      { en: "High technology equipment" },
    ],
    answerIndex: 3,
    explanation: { en: "High technology equipment is listed among manufactured products." },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-m-009",
    topicId: "economy",
    difficulty: "medium",
    prompt: { en: "Aerospace technology is given as an example of ___." },
    options: [
      { en: "Manufactured products" },
      { en: "Natural resources" },
      { en: "Service jobs" },
      { en: "Farm goods" },
    ],
    answerIndex: 0,
    explanation: { en: "Aerospace technology is listed among manufactured products." },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-m-010",
    topicId: "economy",
    difficulty: "medium",
    prompt: { en: "The guide names machinery as a ___." },
    options: [
      { en: "Natural resource" },
      { en: "Manufactured product" },
      { en: "Service industry" },
      { en: "Raw export" },
    ],
    answerIndex: 1,
    explanation: { en: "Machinery is listed among manufactured products." },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-m-011",
    topicId: "economy",
    difficulty: "medium",
    prompt: { en: "Which manufactured product is also something you eat?" },
    options: [{ en: "Timber" }, { en: "Crude oil" }, { en: "Food" }, { en: "Iron ore" }],
    answerIndex: 2,
    explanation: { en: "Food is listed among manufactured products." },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-m-012",
    topicId: "economy",
    difficulty: "medium",
    prompt: { en: "Clothing appears in the guide's list of ___." },
    options: [
      { en: "Natural resources" },
      { en: "Service industries" },
      { en: "Exports only" },
      { en: "Manufactured products" },
    ],
    answerIndex: 3,
    explanation: { en: "Clothing is listed among manufactured products." },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-m-013",
    topicId: "economy",
    difficulty: "medium",
    prompt: { en: "Which list correctly names the natural resources industries?" },
    options: [
      { en: "Forestry, fishing, agriculture, mining and energy" },
      { en: "Banking, tourism, forestry and mining" },
      { en: "Fishing, education, energy and health care" },
      { en: "Agriculture, retail, mining and banking" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The natural resources industries are forestry, fishing, agriculture, mining and energy.",
    },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-m-014",
    topicId: "economy",
    difficulty: "medium",
    prompt: { en: "Which statement about the Peace Arch's location is correct?" },
    options: [
      { en: "It is in British Columbia" },
      { en: "It is in the U.S. state of Washington" },
      { en: "It is in Ottawa" },
      { en: "It is in Alaska" },
    ],
    answerIndex: 1,
    explanation: { en: "The Peace Arch stands at Blaine in the State of Washington." },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-m-015",
    topicId: "economy",
    difficulty: "medium",
    prompt: { en: "Which words are inscribed on the Peace Arch?" },
    options: [
      { en: "Peace through strength" },
      { en: "One nation under God" },
      { en: "Brethren dwelling together in unity" },
      { en: "Liberty and justice for all" },
    ],
    answerIndex: 2,
    explanation: {
      en: 'The Peace Arch is inscribed with the words "brethren dwelling together in unity" (and "children of a common mother").',
    },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-m-016",
    topicId: "economy",
    difficulty: "medium",
    prompt: { en: "Integrated Canada–U.S. supply chains compete with ___." },
    options: [
      { en: "Each other" },
      { en: "Small businesses" },
      { en: "Local farmers" },
      { en: "The rest of the world" },
    ],
    answerIndex: 3,
    explanation: { en: "Integrated Canada–U.S. supply chains compete with the rest of the world." },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-m-017",
    topicId: "economy",
    difficulty: "medium",
    prompt: { en: "Millions of Canadians and Americans cross the border every year in ___." },
    options: [{ en: "Safety" }, { en: "Secrecy" }, { en: "Protest" }, { en: "Disguise" }],
    answerIndex: 0,
    explanation: {
      en: "Millions of Canadians and Americans cross the border every year in safety.",
    },
    source: src("Canada's Economy"),
  },
  {
    id: "eco-m-018",
    topicId: "economy",
    difficulty: "medium",
    prompt: { en: "Which of these does Canada export to the U.S. every year?" },
    options: [
      { en: "Tropical fruit" },
      { en: "Industrial goods" },
      { en: "Coffee" },
      { en: "Rice" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Industrial goods are listed among Canada's annual exports to the United States.",
    },
    source: src("Canada's Economy"),
  },
];
