/**
 * Question bank chunk — part of questions.generated.ts. DO NOT EDIT BY HAND.
 */
import type { Question } from "../content";
import { src } from "./shared";

export const geographyB: Question[] = [
  {
    id: "geo-m-019",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "Nova Scotia's vibrant culture is sustained by its ___ traditions." },
    options: [
      { en: "Loyalist and Acadian" },
      { en: "Ukrainian and Métis" },
      { en: "Inuit and Dene" },
      { en: "Celtic and Gaelic" },
    ],
    answerIndex: 3,
    explanation: { en: "The province's Celtic and Gaelic traditions sustain a vibrant culture." },
    source: src("Canada's Regions: Nova Scotia"),
  },
  {
    id: "geo-m-020",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "Nova Scotia is home to over ___ annual festivals." },
    options: [{ en: "70" }, { en: "7,000" }, { en: "700" }, { en: "70,000" }],
    answerIndex: 2,
    explanation: { en: "Nova Scotia is home to over 700 annual festivals." },
    source: src("Canada's Regions: Nova Scotia"),
  },
  {
    id: "geo-m-021",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "The spectacular military tattoo is held in which city?" },
    options: [{ en: "Ottawa" }, { en: "Victoria" }, { en: "Halifax" }, { en: "Fredericton" }],
    answerIndex: 2,
    explanation: {
      en: "Nova Scotia's festivals include the spectacular military tattoo in Halifax.",
    },
    source: src("Canada's Regions: Nova Scotia"),
  },
  {
    id: "geo-m-022",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "New Brunswick is situated in which mountain range?" },
    options: [
      { en: "The Rocky Mountains" },
      { en: "The Badlands" },
      { en: "Mount Logan" },
      { en: "The Appalachian Range" },
    ],
    answerIndex: 3,
    explanation: { en: "New Brunswick is situated in the Appalachian Range." },
    source: src("Canada's Regions: New Brunswick"),
  },
  {
    id: "geo-m-023",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "New Brunswick was founded by ___." },
    options: [
      { en: "the Vikings" },
      { en: "French explorers" },
      { en: "Scottish immigrants" },
      { en: "the United Empire Loyalists" },
    ],
    answerIndex: 3,
    explanation: { en: "New Brunswick was founded by the United Empire Loyalists." },
    source: src("Canada's Regions: New Brunswick"),
  },
  {
    id: "geo-m-024",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "The St. John River system is ___." },
    options: [
      { en: "the longest river in Canada" },
      { en: "a tributary of the St. Lawrence River" },
      { en: "the second largest river system on North America's Atlantic coastline" },
      { en: "located in Nova Scotia" },
    ],
    answerIndex: 2,
    explanation: {
      en: "New Brunswick has the second largest river system on North America's Atlantic coastline, the St. John River system.",
    },
    source: src("Canada's Regions: New Brunswick"),
  },
  {
    id: "geo-m-025",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "Which are principal industries of New Brunswick?" },
    options: [
      { en: "Oil sands, diamonds and gold" },
      { en: "Banking, insurance and film" },
      { en: "Forestry, agriculture, fisheries, mining, food processing and tourism" },
      { en: "Wheat, potash and uranium" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Forestry, agriculture, fisheries, mining, food processing and tourism are the principal industries of New Brunswick.",
    },
    source: src("Canada's Regions: New Brunswick"),
  },
  {
    id: "geo-m-026",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "Fredericton is described as the ___ capital of New Brunswick." },
    options: [{ en: "former" }, { en: "summer" }, { en: "historic" }, { en: "new" }],
    answerIndex: 2,
    explanation: { en: "Fredericton is the historic capital of New Brunswick." },
    source: src("Canada's Regions: New Brunswick"),
  },
  {
    id: "geo-m-027",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "New Brunswick is the only ___ province in Canada." },
    options: [
      { en: "landlocked" },
      { en: "officially bilingual" },
      { en: "island" },
      { en: "Arctic" },
    ],
    answerIndex: 1,
    explanation: { en: "New Brunswick is the only officially bilingual province." },
    source: src("Canada's Regions: New Brunswick"),
  },
  {
    id: "geo-m-028",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "About how much of New Brunswick's population lives and works in French?" },
    options: [
      { en: "About one-third" },
      { en: "About one-half" },
      { en: "About three-quarters" },
      { en: "About one-tenth" },
    ],
    answerIndex: 0,
    explanation: { en: "About one-third of New Brunswick's population lives and works in French." },
    source: src("Canada's Regions: New Brunswick"),
  },
  {
    id: "geo-m-029",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "Together, Ontario and Quebec produce ___ of all Canadian manufactured goods." },
    options: [
      { en: "about one-half" },
      { en: "less than one-quarter" },
      { en: "about one-tenth" },
      { en: "more than three-quarters" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Together, Ontario and Quebec produce more than three-quarters of all Canadian manufactured goods.",
    },
    source: src("Canada's Regions: Central Canada"),
  },
  {
    id: "geo-m-030",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "Southern Ontario and Quebec have ___." },
    options: [
      { en: "cool winters and cool humid summers" },
      { en: "cold winters and warm humid summers" },
      { en: "long cold winters and short cool summers" },
      { en: "mild winters and dry summers" },
    ],
    answerIndex: 1,
    explanation: { en: "Southern Ontario and Quebec have cold winters and warm humid summers." },
    source: src("Canada's Regions: Central Canada"),
  },
  {
    id: "geo-m-031",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "About how many people live in Quebec?" },
    options: [
      { en: "Nearly eight million" },
      { en: "About four million" },
      { en: "More than 12 million" },
      { en: "About 100,000" },
    ],
    answerIndex: 0,
    explanation: { en: "Nearly eight million people live in Quebec." },
    source: src("Canada's Regions: Quebec"),
  },
  {
    id: "geo-m-032",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "More than three-quarters of Quebecers speak ___ as their first language." },
    options: [{ en: "English" }, { en: "French" }, { en: "Inuktitut" }, { en: "Punjabi" }],
    answerIndex: 1,
    explanation: {
      en: "More than three-quarters of Quebecers speak French as their first language.",
    },
    source: src("Canada's Regions: Quebec"),
  },
  {
    id: "geo-m-033",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "Quebec is Canada's main producer of ___." },
    options: [{ en: "wheat" }, { en: "diamonds" }, { en: "beef" }, { en: "pulp and paper" }],
    answerIndex: 3,
    explanation: { en: "Quebec is Canada's main producer of pulp and paper." },
    source: src("Canada's Regions: Quebec"),
  },
  {
    id: "geo-m-034",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "Which province is Canada's largest producer of hydro-electricity?" },
    options: [{ en: "Ontario" }, { en: "Quebec" }, { en: "Manitoba" }, { en: "Alberta" }],
    answerIndex: 1,
    explanation: {
      en: "Quebec's huge supply of fresh water has made it Canada's largest producer of hydro-electricity.",
    },
    source: src("Canada's Regions: Quebec"),
  },
  {
    id: "geo-m-035",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "Quebecers are leaders in cutting-edge industries such as ___." },
    options: [
      { en: "pharmaceuticals and aeronautics" },
      { en: "oil sands and mining" },
      { en: "shipbuilding and fishing" },
      { en: "forestry and farming" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Quebecers are leaders in cutting-edge industries such as pharmaceuticals and aeronautics.",
    },
    source: src("Canada's Regions: Quebec"),
  },
  {
    id: "geo-m-036",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "La Francophonie is ___." },
    options: [
      { en: "a Quebec film festival" },
      { en: "an association of French-speaking nations" },
      { en: "a Montreal university" },
      { en: "a French-Canadian holiday" },
    ],
    answerIndex: 1,
    explanation: { en: "La Francophonie is an association of French-speaking nations." },
    source: src("Canada's Regions: Quebec"),
  },
  {
    id: "geo-m-037",
    topicId: "geography",
    difficulty: "medium",
    prompt: {
      en: "Montreal is the second largest mainly French-speaking city in the world after ___.",
    },
    options: [{ en: "Brussels" }, { en: "Quebec City" }, { en: "Ottawa" }, { en: "Paris" }],
    answerIndex: 3,
    explanation: {
      en: "Montreal is the second largest mainly French-speaking city in the world after Paris.",
    },
    source: src("Canada's Regions: Quebec"),
  },
  {
    id: "geo-m-038",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "Montreal is famous for its ___." },
    options: [
      { en: "gold rush history" },
      { en: "cultural diversity" },
      { en: "oil refineries" },
      { en: "tall mountains" },
    ],
    answerIndex: 1,
    explanation: { en: "Montreal is famous for its cultural diversity." },
    source: src("Canada's Regions: Quebec"),
  },
  {
    id: "geo-m-039",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "The people of Ontario, at more than 12 million, make up ___ of Canadians." },
    options: [
      { en: "about one-half" },
      { en: "more than one-third" },
      { en: "less than one-quarter" },
      { en: "nearly three-quarters" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The people of Ontario, at more than 12 million, make up more than one-third of Canadians.",
    },
    source: src("Canada's Regions: Ontario"),
  },
  {
    id: "geo-m-040",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "The Niagara region is known for its ___." },
    options: [
      { en: "dairy farms" },
      { en: "steel mills" },
      { en: "vineyards, wines and fruit crops" },
      { en: "fishing villages" },
    ],
    answerIndex: 2,
    explanation: { en: "The Niagara region is known for its vineyards, wines and fruit crops." },
    source: src("Canada's Regions: Ontario"),
  },
  {
    id: "geo-m-041",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "Ontario farmers raise ___." },
    options: [
      { en: "wheat and potash" },
      { en: "dairy and beef cattle, poultry, and vegetable and grain crops" },
      { en: "oranges and lemons" },
      { en: "sheep and goats" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Ontario farmers raise dairy and beef cattle, poultry, and vegetable and grain crops.",
    },
    source: src("Canada's Regions: Ontario"),
  },
  {
    id: "geo-m-042",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "Ontario was founded by ___." },
    options: [
      { en: "French fur traders" },
      { en: "American settlers" },
      { en: "the United Empire Loyalists" },
      { en: "Viking explorers" },
    ],
    answerIndex: 2,
    explanation: { en: "Ontario was founded by United Empire Loyalists." },
    source: src("Canada's Regions: Ontario"),
  },
  {
    id: "geo-m-043",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "Ontario has the largest French-speaking population ___." },
    options: [
      { en: "in the world" },
      { en: "outside of Quebec" },
      { en: "in Western Canada" },
      { en: "in the Atlantic region" },
    ],
    answerIndex: 1,
    explanation: { en: "Ontario has the largest French-speaking population outside of Quebec." },
    source: src("Canada's Regions: Ontario"),
  },
  {
    id: "geo-m-044",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "Which Great Lake is located in the U.S.A.?" },
    options: [
      { en: "Lake Ontario" },
      { en: "Lake Michigan" },
      { en: "Lake Erie" },
      { en: "Lake Huron" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Lake Michigan is in the U.S.A.; the other four Great Lakes are shared with Canada.",
    },
    source: src("Canada's Regions: Ontario"),
  },
  {
    id: "geo-m-045",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "The Prairie Provinces are rich in ___." },
    options: [
      { en: "fishing grounds" },
      { en: "tropical fruit" },
      { en: "ocean ports" },
      { en: "energy resources" },
    ],
    answerIndex: 3,
    explanation: { en: "Manitoba, Saskatchewan and Alberta are rich in energy resources." },
    source: src("Canada's Regions: The Prairie Provinces"),
  },
  {
    id: "geo-m-046",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "The Prairies have some of the most fertile ___ in the world." },
    options: [{ en: "fishing waters" }, { en: "farmland" }, { en: "forests" }, { en: "oil sands" }],
    answerIndex: 1,
    explanation: {
      en: "The Prairie Provinces have some of the most fertile farmland in the world.",
    },
    source: src("Canada's Regions: The Prairie Provinces"),
  },
  {
    id: "geo-m-047",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "The Prairie region is mostly ___, with cold winters and hot summers." },
    options: [{ en: "dry" }, { en: "humid" }, { en: "tropical" }, { en: "coastal" }],
    answerIndex: 0,
    explanation: { en: "The Prairie region is mostly dry, with cold winters and hot summers." },
    source: src("Canada's Regions: The Prairie Provinces"),
  },
  {
    id: "geo-m-048",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "Manitoba's economy is based on ___." },
    options: [
      { en: "fishing and shipbuilding" },
      { en: "banking and insurance" },
      { en: "agriculture, mining and hydro-electric power generation" },
      { en: "tourism and film" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Manitoba's economy is based on agriculture, mining and hydro-electric power generation.",
    },
    source: src("Canada's Regions: Manitoba"),
  },
  {
    id: "geo-m-049",
    topicId: "geography",
    difficulty: "medium",
    prompt: {
      en: "St. Boniface in Winnipeg has Western Canada's largest Francophone community, at ___ people.",
    },
    options: [{ en: "4,500" }, { en: "450,000" }, { en: "45,000" }, { en: "15,000" }],
    answerIndex: 2,
    explanation: {
      en: "Winnipeg's French Quarter, St. Boniface, has Western Canada's largest Francophone community at 45,000.",
    },
    source: src("Canada's Regions: Manitoba"),
  },
  {
    id: "geo-m-050",
    topicId: "geography",
    difficulty: "medium",
    prompt: {
      en: "Manitoba is an important centre of Ukrainian culture, with ___ reporting Ukrainian origins.",
    },
    options: [{ en: "45%" }, { en: "4%" }, { en: "14%" }, { en: "34%" }],
    answerIndex: 2,
    explanation: {
      en: "Manitoba is an important centre of Ukrainian culture, with 14% reporting Ukrainian origins.",
    },
    source: src("Canada's Regions: Manitoba"),
  },
  {
    id: "geo-m-051",
    topicId: "geography",
    difficulty: "medium",
    prompt: {
      en: "Which province has the largest Aboriginal population of any province, at over 15%?",
    },
    options: [{ en: "Manitoba" }, { en: "Saskatchewan" }, { en: "Ontario" }, { en: "Quebec" }],
    answerIndex: 0,
    explanation: {
      en: "Manitoba has the largest Aboriginal population of any province, at over 15%.",
    },
    source: src("Canada's Regions: Manitoba"),
  },
  {
    id: "geo-m-052",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "Saskatchewan has ___ of the arable land in Canada." },
    options: [{ en: "40%" }, { en: "14%" }, { en: "4%" }, { en: "90%" }],
    answerIndex: 0,
    explanation: { en: "Saskatchewan has 40% of the arable land in Canada." },
    source: src("Canada's Regions: Saskatchewan"),
  },
  {
    id: "geo-m-053",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "Saskatchewan is the country's largest producer of ___." },
    options: [
      { en: "pulp and paper" },
      { en: "dairy products" },
      { en: "grains and oilseeds" },
      { en: "seafood" },
    ],
    answerIndex: 2,
    explanation: { en: "Saskatchewan is the country's largest producer of grains and oilseeds." },
    source: src("Canada's Regions: Saskatchewan"),
  },
  {
    id: "geo-m-054",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "Saskatchewan boasts the world's richest deposits of ___." },
    options: [
      { en: "uranium and potash" },
      { en: "gold and diamonds" },
      { en: "coal and iron" },
      { en: "oil and gas" },
    ],
    answerIndex: 0,
    explanation: { en: "Saskatchewan boasts the world's richest deposits of uranium and potash." },
    source: src("Canada's Regions: Saskatchewan"),
  },
  {
    id: "geo-m-055",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "Potash, mined in Saskatchewan, is used in ___." },
    options: [{ en: "computer chips" }, { en: "fertilizer" }, { en: "jet fuel" }, { en: "paint" }],
    answerIndex: 1,
    explanation: { en: "Potash from Saskatchewan is used in fertilizer." },
    source: src("Canada's Regions: Saskatchewan"),
  },
  {
    id: "geo-m-056",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "Saskatoon is the headquarters of which industry?" },
    options: [
      { en: "The fishing industry" },
      { en: "The film industry" },
      { en: "The banking industry" },
      { en: "The mining industry" },
    ],
    answerIndex: 3,
    explanation: { en: "Saskatoon is the headquarters of the mining industry." },
    source: src("Canada's Regions: Saskatchewan"),
  },
  {
    id: "geo-m-057",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "Alberta was named after ___." },
    options: [
      { en: "Princess Louise Caroline Alberta, fourth daughter of Queen Victoria" },
      { en: "Queen Victoria herself" },
      { en: "the wife of Sir William Logan" },
      { en: "an early French explorer" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Alberta was named after Princess Louise Caroline Alberta, fourth daughter of Queen Victoria.",
    },
    source: src("Canada's Regions: Alberta"),
  },
  {
    id: "geo-m-058",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "Lake Louise in the Rocky Mountains was named after ___." },
    options: [
      { en: "Sir William Logan" },
      { en: "Princess Louise Caroline Alberta" },
      { en: "Queen Elizabeth II" },
      { en: "Martin Frobisher" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Lake Louise in the Rocky Mountains was also named after Princess Louise Caroline Alberta.",
    },
    source: src("Canada's Regions: Alberta"),
  },
  {
    id: "geo-m-059",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "How many national parks does Alberta have?" },
    options: [{ en: "One" }, { en: "Ten" }, { en: "Five" }, { en: "Fifty" }],
    answerIndex: 2,
    explanation: { en: "Alberta has five national parks." },
    source: src("Canada's Regions: Alberta"),
  },
  {
    id: "geo-m-060",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "Banff National Park was established in ___." },
    options: [{ en: "1857" }, { en: "1885" }, { en: "1867" }, { en: "1999" }],
    answerIndex: 1,
    explanation: { en: "Banff National Park was established in 1885." },
    source: src("Canada's Regions: Alberta"),
  },
  {
    id: "geo-m-061",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "Which province is the largest producer of oil and gas?" },
    options: [{ en: "Alberta" }, { en: "Saskatchewan" }, { en: "Ontario" }, { en: "Quebec" }],
    answerIndex: 0,
    explanation: { en: "Alberta is the largest producer of oil and gas." },
    source: src("Canada's Regions: Alberta"),
  },
  {
    id: "geo-m-062",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "Alberta's oil sands in the north are ___." },
    options: [
      { en: "closed to development" },
      { en: "used for farming" },
      { en: "being developed as a major energy source" },
      { en: "a tourist attraction" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The oil sands in the north of Alberta are being developed as a major energy source.",
    },
    source: src("Canada's Regions: Alberta"),
  },
  {
    id: "geo-m-063",
    topicId: "geography",
    difficulty: "medium",
    prompt: {
      en: "Alberta's vast cattle ranches make Canada one of the world's major ___ producers.",
    },
    options: [{ en: "beef" }, { en: "pork" }, { en: "lamb" }, { en: "dairy" }],
    answerIndex: 0,
    explanation: {
      en: "Alberta's vast cattle ranches make Canada one of the world's major beef producers.",
    },
    source: src("Canada's Regions: Alberta"),
  },
  {
    id: "geo-h-001",
    topicId: "geography",
    difficulty: "hard",
    prompt: { en: "The B.C. coast has a temperate climate because of ___." },
    options: [
      { en: "cold Arctic winds" },
      { en: "the Rocky Mountains blocking rain" },
      { en: "warm airstreams from the Pacific Ocean" },
      { en: "its northern latitude" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Warm airstreams from the Pacific Ocean give the B.C. coast a temperate climate.",
    },
    source: src("Canada's Regions: British Columbia"),
  },
  {
    id: "geo-h-002",
    topicId: "geography",
    difficulty: "hard",
    prompt: { en: "British Columbia has a population of ___." },
    options: [
      { en: "four million" },
      { en: "eight million" },
      { en: "12 million" },
      { en: "100,000" },
    ],
    answerIndex: 0,
    explanation: { en: "British Columbia has a population of four million." },
    source: src("Canada's Regions: British Columbia"),
  },
  {
    id: "geo-h-003",
    topicId: "geography",
    difficulty: "hard",
    prompt: { en: "About how much of all the goods produced in B.C. are forestry products?" },
    options: [
      { en: "About one-quarter" },
      { en: "About one-half" },
      { en: "About three-quarters" },
      { en: "About one-tenth" },
    ],
    answerIndex: 1,
    explanation: { en: "About one-half of all the goods produced in B.C. are forestry products." },
    source: src("Canada's Regions: British Columbia"),
  },
  {
    id: "geo-h-004",
    topicId: "geography",
    difficulty: "hard",
    prompt: { en: "British Columbia has the ___ forestry industry in Canada." },
    options: [{ en: "smallest" }, { en: "most valuable" }, { en: "oldest" }, { en: "newest" }],
    answerIndex: 1,
    explanation: { en: "B.C. has the most valuable forestry industry in Canada." },
    source: src("Canada's Regions: British Columbia"),
  },
  {
    id: "geo-h-005",
    topicId: "geography",
    difficulty: "hard",
    prompt: { en: "B.C. forestry products include ___." },
    options: [
      { en: "steel and automobiles" },
      { en: "wheat and canola" },
      { en: "lumber, newsprint, and pulp and paper products" },
      { en: "diamonds and gold" },
    ],
    answerIndex: 2,
    explanation: {
      en: "B.C. forestry products include lumber, newsprint, and pulp and paper products.",
    },
    source: src("Canada's Regions: British Columbia"),
  },
  {
    id: "geo-h-006",
    topicId: "geography",
    difficulty: "hard",
    prompt: { en: "Besides forestry, British Columbia is also known for ___." },
    options: [
      { en: "mining and fishing" },
      { en: "oil sands and wheat" },
      { en: "banking and insurance" },
      { en: "cotton and tobacco" },
    ],
    answerIndex: 0,
    explanation: { en: "B.C. is also known for mining and fishing." },
    source: src("Canada's Regions: British Columbia"),
  },
  {
    id: "geo-h-007",
    topicId: "geography",
    difficulty: "hard",
    prompt: {
      en: "British Columbia has the most extensive park system in Canada, with approximately ___ provincial parks.",
    },
    options: [{ en: "60" }, { en: "6,000" }, { en: "600" }, { en: "60,000" }],
    answerIndex: 2,
    explanation: {
      en: "B.C. has the most extensive park system in Canada, with approximately 600 provincial parks.",
    },
    source: src("Canada's Regions: British Columbia"),
  },
  {
    id: "geo-h-008",
    topicId: "geography",
    difficulty: "hard",
    prompt: { en: "After English, the most spoken languages in B.C. cities are ___." },
    options: [
      { en: "French and German" },
      { en: "Ukrainian and Italian" },
      { en: "Spanish and Portuguese" },
      { en: "Chinese and Punjabi" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Large Asian communities have made Chinese and Punjabi the most spoken languages in B.C. cities after English.",
    },
    source: src("Canada's Regions: British Columbia"),
  },
  {
    id: "geo-h-009",
    topicId: "geography",
    difficulty: "hard",
    prompt: { en: "The Port of Vancouver is Canada's gateway to ___." },
    options: [
      { en: "Europe" },
      { en: "South America" },
      { en: "Africa" },
      { en: "the Asia-Pacific" },
    ],
    answerIndex: 3,
    explanation: { en: "The Port of Vancouver is Canada's gateway to the Asia-Pacific." },
    source: src("Canada's Regions: British Columbia"),
  },
  {
    id: "geo-h-010",
    topicId: "geography",
    difficulty: "hard",
    prompt: {
      en: "The Northern Territories contain one-third of Canada's land mass but have a population of only ___.",
    },
    options: [{ en: "1 million" }, { en: "100,000" }, { en: "34 million" }, { en: "10 million" }],
    answerIndex: 1,
    explanation: {
      en: "The Northwest Territories, Nunavut and Yukon contain one-third of Canada's land mass but have a population of only 100,000.",
    },
    source: src("Canada's Regions: The Northern Territories"),
  },
  {
    id: "geo-h-011",
    topicId: "geography",
    difficulty: "hard",
    prompt: { en: "Mines in the North produce ___." },
    options: [
      { en: "iron and steel" },
      { en: "coal and oil" },
      { en: "wheat and potash" },
      { en: "gold, lead, copper, diamond and zinc" },
    ],
    answerIndex: 3,
    explanation: { en: "There are gold, lead, copper, diamond and zinc mines in the North." },
    source: src("Canada's Regions: The Northern Territories"),
  },
  {
    id: "geo-h-012",
    topicId: "geography",
    difficulty: "hard",
    prompt: { en: "In the North, deposits of ___ are being developed." },
    options: [{ en: "oil and gas" }, { en: "diamonds" }, { en: "coal" }, { en: "uranium" }],
    answerIndex: 0,
    explanation: { en: "Oil and gas deposits in the North are being developed." },
    source: src("Canada's Regions: The Northern Territories"),
  },
  {
    id: "geo-h-013",
    topicId: "geography",
    difficulty: "hard",
    prompt: { en: "At the height of summer in the North, daylight can last up to ___." },
    options: [{ en: "12 hours" }, { en: "18 hours" }, { en: "6 hours" }, { en: "24 hours" }],
    answerIndex: 3,
    explanation: { en: "At the height of summer, daylight in the North can last up to 24 hours." },
    source: src("Canada's Regions: The Northern Territories"),
  },
  {
    id: "geo-h-014",
    topicId: "geography",
    difficulty: "hard",
    prompt: { en: "In winter in the North, the sun disappears and darkness sets in for ___." },
    options: [
      { en: "three weeks" },
      { en: "three months" },
      { en: "three days" },
      { en: "six months" },
    ],
    answerIndex: 1,
    explanation: { en: "In winter, the sun disappears and darkness sets in for three months." },
    source: src("Canada's Regions: The Northern Territories"),
  },
  {
    id: "geo-h-015",
    topicId: "geography",
    difficulty: "hard",
    prompt: { en: "The Northern territories have ___." },
    options: [
      { en: "cool winters and cool humid summers" },
      { en: "cold winters and warm humid summers" },
      { en: "mild winters and hot summers" },
      { en: "long cold winters and short cool summers" },
    ],
    answerIndex: 3,
    explanation: { en: "The Northern territories have long cold winters and short cool summers." },
    source: src("Canada's Regions: The Northern Territories"),
  },
  {
    id: "geo-h-016",
    topicId: "geography",
    difficulty: "hard",
    prompt: { en: "On the tundra, the soil is ___." },
    options: [
      { en: "permanently frozen" },
      { en: "rich and fertile" },
      { en: "sandy and dry" },
      { en: "covered in grass" },
    ],
    answerIndex: 0,
    explanation: { en: "On the tundra the soil is permanently frozen." },
    source: src("Canada's Regions: The Northern Territories"),
  },
  {
    id: "geo-h-017",
    topicId: "geography",
    difficulty: "hard",
    prompt: { en: "Some people in the North continue to earn a living by ___." },
    options: [
      { en: "hunting, fishing and trapping" },
      { en: "farming wheat" },
      { en: "mining coal" },
      { en: "logging forests" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Some in the North continue to earn a living by hunting, fishing and trapping.",
    },
    source: src("Canada's Regions: The Northern Territories"),
  },
  {
    id: "geo-h-018",
    topicId: "geography",
    difficulty: "hard",
    prompt: { en: "Inuit art is sold ___." },
    options: [
      { en: "only in Nunavut" },
      { en: "throughout Canada and around the world" },
      { en: "only in museums" },
      { en: "only online" },
    ],
    answerIndex: 1,
    explanation: { en: "Inuit art is sold throughout Canada and around the world." },
    source: src("Canada's Regions: The Northern Territories"),
  },
  {
    id: "geo-h-019",
    topicId: "geography",
    difficulty: "hard",
    prompt: { en: "The Yukon Gold Rush of the 1890s was celebrated in the poetry of ___." },
    options: [
      { en: "Lucy Maud Montgomery" },
      { en: "Sir William Logan" },
      { en: "Martin Frobisher" },
      { en: "Robert W. Service" },
    ],
    answerIndex: 3,
    explanation: { en: "The Gold Rush was celebrated in the poetry of Robert W. Service." },
    source: src("Canada's Regions: Yukon"),
  },
  {
    id: "geo-h-020",
    topicId: "geography",
    difficulty: "hard",
    prompt: {
      en: "The White Pass and Yukon Railway opened in 1900 from Skagway in neighbouring Alaska to ___.",
    },
    options: [{ en: "Yellowknife" }, { en: "Iqaluit" }, { en: "Whitehorse" }, { en: "Vancouver" }],
    answerIndex: 2,
    explanation: {
      en: "The railway opened from Skagway in neighbouring Alaska to the territorial capital, Whitehorse, in 1900.",
    },
    source: src("Canada's Regions: Yukon"),
  },
  {
    id: "geo-h-021",
    topicId: "geography",
    difficulty: "hard",
    prompt: {
      en: "The White Pass and Yukon Railway provides a spectacular tourist excursion across ___.",
    },
    options: [
      { en: "the Rocky Mountains" },
      { en: "precipitous passes and bridges" },
      { en: "frozen tundra" },
      { en: "the Badlands" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The railway provides a spectacular tourist excursion across precipitous passes and bridges.",
    },
    source: src("Canada's Regions: Yukon"),
  },
  {
    id: "geo-h-022",
    topicId: "geography",
    difficulty: "hard",
    prompt: { en: "Mount Logan was named in honour of ___." },
    options: [
      { en: "Princess Louise Caroline Alberta" },
      { en: "Martin Frobisher" },
      { en: "Sir William Logan, a world-famous geologist" },
      { en: "Robert W. Service" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Mount Logan is named in honour of Sir William Logan, a world-famous geologist.",
    },
    source: src("Canada's Regions: Yukon"),
  },
  {
    id: "geo-h-023",
    topicId: "geography",
    difficulty: "hard",
    prompt: {
      en: "Sir William Logan founded and directed the Geological Survey of Canada from ___.",
    },
    options: [
      { en: "1857 to 1885" },
      { en: "1890 to 1900" },
      { en: "1870 to 1999" },
      { en: "1842 to 1869" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Logan founded and directed the Geological Survey of Canada from 1842 to 1869.",
    },
    source: src("Canada's Regions: Yukon"),
  },
  {
    id: "geo-h-024",
    topicId: "geography",
    difficulty: "hard",
    prompt: { en: "Sir William Logan was born in Montreal in 1798 to ___ parents." },
    options: [
      { en: "French settler" },
      { en: "Scottish immigrant" },
      { en: "English explorer" },
      { en: "Irish pioneer" },
    ],
    answerIndex: 1,
    explanation: { en: "Logan was born in Montreal in 1798 to Scottish immigrant parents." },
    source: src("Canada's Regions: Yukon"),
  },
  {
    id: "geo-h-025",
    topicId: "geography",
    difficulty: "hard",
    prompt: { en: "The Northwest Territories were originally made up in 1870 from ___." },
    options: [
      { en: "the District of Keewatin" },
      { en: "British Columbia and Alberta" },
      { en: "Alaska and Yukon" },
      { en: "Rupert's Land and the North-Western Territory" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The Northwest Territories were originally made up in 1870 from Rupert's Land and the North-Western Territory.",
    },
    source: src("Canada's Regions: Northwest Territories"),
  },
  {
    id: "geo-h-026",
    topicId: "geography",
    difficulty: "hard",
    prompt: { en: "Yellowknife has a population of ___." },
    options: [{ en: "100,000" }, { en: "45,000" }, { en: "4,700" }, { en: "20,000" }],
    answerIndex: 3,
    explanation: { en: "The capital, Yellowknife, has a population of 20,000." },
    source: src("Canada's Regions: Northwest Territories"),
  },
  {
    id: "geo-h-027",
    topicId: "geography",
    difficulty: "hard",
    prompt: {
      en: "More than half the population of the Northwest Territories is Aboriginal, including ___.",
    },
    options: [
      { en: "Cree, Ojibway and Mohawk" },
      { en: "Inuit only" },
      { en: "Métis only" },
      { en: "Dene, Inuit and Métis" },
    ],
    answerIndex: 3,
    explanation: { en: "More than half the population is Aboriginal (Dene, Inuit and Métis)." },
    source: src("Canada's Regions: Northwest Territories"),
  },
  {
    id: "geo-h-028",
    topicId: "geography",
    difficulty: "hard",
    prompt: { en: "The Mackenzie River is ___ long." },
    options: [
      { en: "1,800 kilometres" },
      { en: "4,700 kilometres" },
      { en: "4,200 kilometres" },
      { en: "24,000 kilometres" },
    ],
    answerIndex: 2,
    explanation: { en: "The Mackenzie River is 4,200 kilometres long." },
    source: src("Canada's Regions: Northwest Territories"),
  },
  {
    id: "geo-h-029",
    topicId: "geography",
    difficulty: "hard",
    prompt: { en: "The Mackenzie River drains an area of ___." },
    options: [
      { en: "4,200 square kilometres" },
      { en: "1.8 million square kilometres" },
      { en: "10 million square kilometres" },
      { en: "100,000 square kilometres" },
    ],
    answerIndex: 1,
    explanation: { en: "The Mackenzie River drains an area of 1.8 million square kilometres." },
    source: src("Canada's Regions: Northwest Territories"),
  },
  {
    id: "geo-h-030",
    topicId: "geography",
    difficulty: "hard",
    prompt: { en: "Nunavut was established in 1999 from ___." },
    options: [
      { en: "the western part of Yukon" },
      {
        en: "the eastern part of the Northwest Territories, including the former District of Keewatin",
      },
      { en: "Rupert's Land" },
      { en: "the Labrador coast" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Nunavut was established in 1999 from the eastern part of the Northwest Territories, including all of the former District of Keewatin.",
    },
    source: src("Canada's Regions: Nunavut"),
  },
  {
    id: "geo-h-031",
    topicId: "geography",
    difficulty: "hard",
    prompt: {
      en: "Martin Frobisher, after whom Iqaluit was named, penetrated the uncharted Arctic for Queen Elizabeth I in ___.",
    },
    options: [{ en: "1576" }, { en: "1857" }, { en: "1867" }, { en: "1999" }],
    answerIndex: 0,
    explanation: {
      en: "Martin Frobisher penetrated the uncharted Arctic for Queen Elizabeth I in 1576.",
    },
    source: src("Canada's Regions: Nunavut"),
  },
  {
    id: "geo-h-032",
    topicId: "geography",
    difficulty: "hard",
    prompt: { en: "Nunavut's 19-member Legislative Assembly ___." },
    options: [
      { en: "chooses a premier and ministers by consensus" },
      { en: "is appointed by the Queen" },
      { en: "elects members every ten years" },
      { en: "has no premier" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The 19-member Legislative Assembly chooses a premier and ministers by consensus.",
    },
    source: src("Canada's Regions: Nunavut"),
  },
  {
    id: "geo-h-033",
    topicId: "geography",
    difficulty: "hard",
    prompt: { en: "About ___ of Nunavut's population is Inuit." },
    options: [{ en: "85%" }, { en: "15%" }, { en: "50%" }, { en: "35%" }],
    answerIndex: 0,
    explanation: { en: "The population of Nunavut is about 85% Inuit." },
    source: src("Canada's Regions: Nunavut"),
  },
  {
    id: "geo-h-034",
    topicId: "geography",
    difficulty: "hard",
    prompt: { en: "In Nunavut, Inuktitut is ___." },
    options: [
      { en: "spoken only by elders" },
      { en: "a second language only" },
      { en: "an official language and the first language in schools" },
      { en: "not an official language" },
    ],
    answerIndex: 2,
    explanation: { en: "Inuktitut is an official language and the first language in schools." },
    source: src("Canada's Regions: Nunavut"),
  },
  {
    id: "geo-h-035",
    topicId: "geography",
    difficulty: "hard",
    prompt: { en: "The Canadian Rangers are part of ___." },
    options: [
      { en: "the Royal Canadian Mounted Police" },
      { en: "the Coast Guard" },
      { en: "the regular army infantry" },
      { en: "the Canadian Forces Reserves (militia)" },
    ],
    answerIndex: 3,
    explanation: { en: "The Canadian Rangers are part of the Canadian Forces Reserves (militia)." },
    source: src("Canada's Regions: The Canadian Rangers"),
  },
  {
    id: "geo-h-036",
    topicId: "geography",
    difficulty: "hard",
    prompt: {
      en: "The Canadian Rangers travel by snowmobile in winter and ___ in summer, from Resolute to the Magnetic North Pole.",
    },
    options: [
      { en: "all-terrain vehicles" },
      { en: "dogsleds" },
      { en: "helicopters" },
      { en: "canoes" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The Rangers travel by snowmobile in the winter and all-terrain vehicles in the summer, from Resolute to the Magnetic North Pole.",
    },
    source: src("Canada's Regions: The Canadian Rangers"),
  },
  {
    id: "geo-h-037",
    topicId: "geography",
    difficulty: "hard",
    prompt: {
      en: "Before becoming a tourist attraction and winter skateway, Ottawa's Rideau Canal was ___.",
    },
    options: [
      { en: "a logging route" },
      { en: "a gold rush trail" },
      { en: "a railway line" },
      { en: "a military waterway" },
    ],
    answerIndex: 3,
    explanation: { en: "Ottawa's Rideau Canal was once a military waterway." },
    source: src("Canada's Regions: The National Capital"),
  },
  {
    id: "geo-h-038",
    topicId: "geography",
    difficulty: "hard",
    prompt: { en: "The National Capital Region preserves and enhances the area's ___." },
    options: [
      { en: "built heritage and natural environment" },
      { en: "military bases" },
      { en: "farmland" },
      { en: "fisheries" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The National Capital Region preserves and enhances the area's built heritage and natural environment.",
    },
    source: src("Canada's Regions: The National Capital"),
  },
  {
    id: "geo-h-039",
    topicId: "geography",
    difficulty: "hard",
    prompt: {
      en: "Queen Victoria, who chose Ottawa as the capital, was the ___ of Queen Elizabeth II.",
    },
    options: [
      { en: "great-great-grandmother" },
      { en: "grandmother" },
      { en: "mother" },
      { en: "great-grandmother" },
    ],
    answerIndex: 0,
    explanation: { en: "Queen Victoria was the great-great-grandmother of Queen Elizabeth II." },
    source: src("Canada's Regions: The National Capital"),
  },
  {
    id: "geo-h-040",
    topicId: "geography",
    difficulty: "hard",
    prompt: { en: "Besides grains and oilseeds, Saskatchewan also produces ___." },
    options: [
      { en: "diamonds and gold" },
      { en: "oil and natural gas" },
      { en: "seafood" },
      { en: "wine" },
    ],
    answerIndex: 1,
    explanation: { en: "Saskatchewan produces oil and natural gas." },
    source: src("Canada's Regions: Saskatchewan"),
  },
  {
    id: "geo-h-041",
    topicId: "geography",
    difficulty: "hard",
    prompt: { en: "Saskatoon is an important ___ centre." },
    options: [
      { en: "fishing and shipping" },
      { en: "educational, research and technology" },
      { en: "banking and finance" },
      { en: "military and defence" },
    ],
    answerIndex: 1,
    explanation: { en: "Saskatoon is an important educational, research and technology centre." },
    source: src("Canada's Regions: Saskatchewan"),
  },
  {
    id: "geo-h-042",
    topicId: "geography",
    difficulty: "hard",
    prompt: {
      en: "New Brunswick's pioneer Loyalist and French cultural heritage comes alive in ___.",
    },
    options: [
      { en: "winter carnivals" },
      { en: "street festivals and traditional music" },
      { en: "rodeos" },
      { en: "film festivals" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The province's pioneer Loyalist and French cultural heritage and history come alive in street festivals and traditional music.",
    },
    source: src("Canada's Regions: New Brunswick"),
  },
  {
    id: "geo-h-043",
    topicId: "geography",
    difficulty: "hard",
    prompt: {
      en: "The resources of the Canadian Shield have helped Quebec develop important industries, including ___.",
    },
    options: [
      { en: "forestry, energy and mining" },
      { en: "fishing and shipbuilding" },
      { en: "banking and insurance" },
      { en: "tourism and film" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The resources of the Canadian Shield have helped Quebec to develop important industries, including forestry, energy and mining.",
    },
    source: src("Canada's Regions: Quebec"),
  },
  {
    id: "geo-h-044",
    topicId: "geography",
    difficulty: "hard",
    prompt: {
      en: "In Ontario, many people work in the service or manufacturing industries, which produce ___.",
    },
    options: [
      { en: "a large percentage of Canada's exports" },
      { en: "most of the world's wheat" },
      { en: "all of Canada's oil" },
      { en: "little of value" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Many people in Ontario work in the service or manufacturing industries, which produce a large percentage of Canada's exports.",
    },
    source: src("Canada's Regions: Ontario"),
  },
  {
    id: "geo-h-045",
    topicId: "geography",
    difficulty: "hard",
    prompt: {
      en: "Ontario's vital economy comes from its large and culturally diverse population, natural resources and ___.",
    },
    options: [
      { en: "gold mines" },
      { en: "ocean ports" },
      { en: "tropical climate" },
      { en: "strategic location" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The large and culturally diverse population, natural resources and strategic location contribute to Ontario's vital economy.",
    },
    source: src("Canada's Regions: Ontario"),
  },
];
