/**
 * Question bank chunk — part of questions.generated.ts. DO NOT EDIT BY HAND.
 */
import type { Question } from "../content";
import { src } from "./shared";

export const geographyA: Question[] = [
  {
    id: "geo-e-001",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "What is the capital city of Canada?" },
    options: [{ en: "Toronto" }, { en: "Montreal" }, { en: "Vancouver" }, { en: "Ottawa" }],
    answerIndex: 3,
    explanation: { en: "Ottawa, located on the Ottawa River, is the capital of Canada." },
    source: src("Canada's Regions: The National Capital"),
  },
  {
    id: "geo-e-002",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "Canada is the ___ largest country on earth." },
    options: [{ en: "third" }, { en: "second" }, { en: "largest" }, { en: "fourth" }],
    answerIndex: 1,
    explanation: {
      en: "Canada is the second largest country on earth, covering 10 million square kilometres.",
    },
    source: src("Canada's Regions"),
  },
  {
    id: "geo-e-003",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "Approximately how large is Canada?" },
    options: [
      { en: "10 million square kilometres" },
      { en: "5 million square kilometres" },
      { en: "1 million square kilometres" },
      { en: "20 million square kilometres" },
    ],
    answerIndex: 0,
    explanation: { en: "Canada covers about 10 million square kilometres." },
    source: src("Canada's Regions"),
  },
  {
    id: "geo-e-004",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "How many oceans line Canada's frontiers?" },
    options: [{ en: "Three" }, { en: "Two" }, { en: "Four" }, { en: "Five" }],
    answerIndex: 0,
    explanation: {
      en: "Three oceans line Canada's frontiers: the Pacific, the Atlantic and the Arctic.",
    },
    source: src("Canada's Regions"),
  },
  {
    id: "geo-e-005",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "Which ocean lies to the west of Canada?" },
    options: [
      { en: "The Pacific Ocean" },
      { en: "The Atlantic Ocean" },
      { en: "The Arctic Ocean" },
      { en: "The Indian Ocean" },
    ],
    answerIndex: 0,
    explanation: { en: "The Pacific Ocean lies to the west of Canada." },
    source: src("Canada's Regions"),
  },
  {
    id: "geo-e-006",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "Which ocean lies to the east of Canada?" },
    options: [
      { en: "The Atlantic Ocean" },
      { en: "The Pacific Ocean" },
      { en: "The Arctic Ocean" },
      { en: "The Southern Ocean" },
    ],
    answerIndex: 0,
    explanation: { en: "The Atlantic Ocean lies to the east of Canada." },
    source: src("Canada's Regions"),
  },
  {
    id: "geo-e-007",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "Which ocean lies to the north of Canada?" },
    options: [
      { en: "The Pacific Ocean" },
      { en: "The Arctic Ocean" },
      { en: "The Atlantic Ocean" },
      { en: "The Indian Ocean" },
    ],
    answerIndex: 1,
    explanation: { en: "The Arctic Ocean lies to the north of Canada." },
    source: src("Canada's Regions"),
  },
  {
    id: "geo-e-008",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "How many provinces does Canada have?" },
    options: [{ en: "Thirteen" }, { en: "Three" }, { en: "Ten" }, { en: "Five" }],
    answerIndex: 2,
    explanation: { en: "Canada has ten provinces and three territories." },
    source: src("Canada's Regions: Provinces and Territories"),
  },
  {
    id: "geo-e-009",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "How many territories does Canada have?" },
    options: [{ en: "Ten" }, { en: "Three" }, { en: "Five" }, { en: "Thirteen" }],
    answerIndex: 1,
    explanation: { en: "Canada has ten provinces and three territories." },
    source: src("Canada's Regions: Provinces and Territories"),
  },
  {
    id: "geo-e-010",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "How many distinct regions does Canada have?" },
    options: [{ en: "Five" }, { en: "Three" }, { en: "Ten" }, { en: "Thirteen" }],
    answerIndex: 0,
    explanation: {
      en: "Canada includes many different geographical areas and five distinct regions.",
    },
    source: src("Canada's Regions"),
  },
  {
    id: "geo-e-011",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "Which of the following is NOT one of Canada's five regions?" },
    options: [
      { en: "The Atlantic Provinces" },
      { en: "The Maritimes" },
      { en: "Central Canada" },
      { en: "The Prairie Provinces" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The five regions are the Atlantic Provinces, Central Canada, the Prairie Provinces, the West Coast and the Northern Territories.",
    },
    source: src("Canada's Regions"),
  },
  {
    id: "geo-e-012",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "Which province is part of the Atlantic region?" },
    options: [{ en: "Nova Scotia" }, { en: "Ontario" }, { en: "Manitoba" }, { en: "Alberta" }],
    answerIndex: 0,
    explanation: {
      en: "The Atlantic region includes Newfoundland and Labrador, Prince Edward Island, Nova Scotia and New Brunswick.",
    },
    source: src("Canada's Regions: The Atlantic Provinces"),
  },
  {
    id: "geo-e-013",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "Which two provinces make up Central Canada?" },
    options: [
      { en: "Manitoba and Saskatchewan" },
      { en: "Alberta and British Columbia" },
      { en: "New Brunswick and Nova Scotia" },
      { en: "Quebec and Ontario" },
    ],
    answerIndex: 3,
    explanation: { en: "Central Canada consists of Quebec and Ontario." },
    source: src("Canada's Regions: Central Canada"),
  },
  {
    id: "geo-e-014",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "Which provinces are the Prairie Provinces?" },
    options: [
      { en: "Manitoba, Saskatchewan and Alberta" },
      { en: "Ontario, Quebec and Manitoba" },
      { en: "British Columbia and Alberta" },
      { en: "Nova Scotia, New Brunswick and Prince Edward Island" },
    ],
    answerIndex: 0,
    explanation: { en: "The Prairie Provinces are Manitoba, Saskatchewan and Alberta." },
    source: src("Canada's Regions: The Prairie Provinces"),
  },
  {
    id: "geo-e-015",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "Which province is in the West Coast region?" },
    options: [{ en: "Alberta" }, { en: "Manitoba" }, { en: "British Columbia" }, { en: "Ontario" }],
    answerIndex: 2,
    explanation: { en: "The West Coast region is British Columbia." },
    source: src("Canada's Regions: The West Coast"),
  },
  {
    id: "geo-e-016",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "Which of the following are the Northern Territories?" },
    options: [
      { en: "Alaska, Yukon and Nunavut" },
      { en: "Nunavut, Manitoba and Saskatchewan" },
      { en: "Yukon, the Northwest Territories and Nunavut" },
      { en: "The Northwest Territories, Alberta and British Columbia" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The Northern Territories are Nunavut, the Northwest Territories and Yukon.",
    },
    source: src("Canada's Regions: The Northern Territories"),
  },
  {
    id: "geo-e-017",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "What is the capital of Newfoundland and Labrador?" },
    options: [
      { en: "Halifax" },
      { en: "Charlottetown" },
      { en: "St. John's" },
      { en: "Fredericton" },
    ],
    answerIndex: 2,
    explanation: { en: "St. John's is the capital of Newfoundland and Labrador." },
    source: src("Canada's Regions: Newfoundland and Labrador"),
  },
  {
    id: "geo-e-018",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "What is the capital of Prince Edward Island?" },
    options: [
      { en: "Halifax" },
      { en: "St. John's" },
      { en: "Fredericton" },
      { en: "Charlottetown" },
    ],
    answerIndex: 3,
    explanation: { en: "Charlottetown is the capital of Prince Edward Island." },
    source: src("Canada's Regions: Prince Edward Island"),
  },
  {
    id: "geo-e-019",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "What is the capital of Nova Scotia?" },
    options: [
      { en: "Charlottetown" },
      { en: "St. John's" },
      { en: "Fredericton" },
      { en: "Halifax" },
    ],
    answerIndex: 3,
    explanation: { en: "Halifax is the capital of Nova Scotia." },
    source: src("Canada's Regions: Nova Scotia"),
  },
  {
    id: "geo-e-020",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "What is the capital of New Brunswick?" },
    options: [{ en: "Saint John" }, { en: "Fredericton" }, { en: "Moncton" }, { en: "Halifax" }],
    answerIndex: 1,
    explanation: { en: "Fredericton is the capital of New Brunswick." },
    source: src("Canada's Regions: New Brunswick"),
  },
  {
    id: "geo-e-021",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "What is the capital of Quebec?" },
    options: [{ en: "Montreal" }, { en: "Ottawa" }, { en: "Québec City" }, { en: "Toronto" }],
    answerIndex: 2,
    explanation: { en: "Québec City is the capital of Quebec." },
    source: src("Canada's Regions: Quebec"),
  },
  {
    id: "geo-e-022",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "What is the capital of Ontario?" },
    options: [{ en: "Ottawa" }, { en: "Montreal" }, { en: "Winnipeg" }, { en: "Toronto" }],
    answerIndex: 3,
    explanation: { en: "Toronto is the capital of Ontario." },
    source: src("Canada's Regions: Ontario"),
  },
  {
    id: "geo-e-023",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "What is the capital of Manitoba?" },
    options: [{ en: "Winnipeg" }, { en: "Regina" }, { en: "Edmonton" }, { en: "Saskatoon" }],
    answerIndex: 0,
    explanation: { en: "Winnipeg is the capital of Manitoba." },
    source: src("Canada's Regions: Manitoba"),
  },
  {
    id: "geo-e-024",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "What is the capital of Saskatchewan?" },
    options: [{ en: "Saskatoon" }, { en: "Winnipeg" }, { en: "Regina" }, { en: "Edmonton" }],
    answerIndex: 2,
    explanation: { en: "Regina is the capital of Saskatchewan." },
    source: src("Canada's Regions: Saskatchewan"),
  },
  {
    id: "geo-e-025",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "What is the capital of Alberta?" },
    options: [{ en: "Winnipeg" }, { en: "Regina" }, { en: "Edmonton" }, { en: "Victoria" }],
    answerIndex: 2,
    explanation: { en: "Edmonton is the capital of Alberta." },
    source: src("Canada's Regions: Alberta"),
  },
  {
    id: "geo-e-026",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "What is the capital of British Columbia?" },
    options: [{ en: "Vancouver" }, { en: "Edmonton" }, { en: "Whitehorse" }, { en: "Victoria" }],
    answerIndex: 3,
    explanation: { en: "Victoria is the capital of British Columbia." },
    source: src("Canada's Regions: British Columbia"),
  },
  {
    id: "geo-e-027",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "What is the capital of Nunavut?" },
    options: [{ en: "Yellowknife" }, { en: "Whitehorse" }, { en: "Ottawa" }, { en: "Iqaluit" }],
    answerIndex: 3,
    explanation: { en: "Iqaluit is the capital of Nunavut." },
    source: src("Canada's Regions: Nunavut"),
  },
  {
    id: "geo-e-028",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "What is the capital of the Northwest Territories?" },
    options: [{ en: "Whitehorse" }, { en: "Yellowknife" }, { en: "Iqaluit" }, { en: "Edmonton" }],
    answerIndex: 1,
    explanation: { en: "Yellowknife is the capital of the Northwest Territories." },
    source: src("Canada's Regions: Northwest Territories"),
  },
  {
    id: "geo-e-029",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "What is the capital of Yukon?" },
    options: [{ en: "Yellowknife" }, { en: "Iqaluit" }, { en: "Victoria" }, { en: "Whitehorse" }],
    answerIndex: 3,
    explanation: { en: "Whitehorse is the territorial capital of Yukon." },
    source: src("Canada's Regions: Yukon"),
  },
  {
    id: "geo-e-030",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "About how many people live in Canada?" },
    options: [
      { en: "About 10 million" },
      { en: "About 100 million" },
      { en: "About 340 million" },
      { en: "About 34 million" },
    ],
    answerIndex: 3,
    explanation: { en: "Canada has a population of about 34 million people." },
    source: src("Canada's Regions"),
  },
  {
    id: "geo-e-031",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "Where does the majority of Canada's population live?" },
    options: [
      { en: "In cities" },
      { en: "In rural areas" },
      { en: "In the North" },
      { en: "On farms" },
    ],
    answerIndex: 0,
    explanation: {
      en: "While the majority of Canadians live in cities, Canadians also live in small towns and rural areas.",
    },
    source: src("Canada's Regions"),
  },
  {
    id: "geo-e-032",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "What is the largest city in Canada?" },
    options: [{ en: "Montreal" }, { en: "Toronto" }, { en: "Vancouver" }, { en: "Ottawa" }],
    answerIndex: 1,
    explanation: { en: "Toronto is the largest city in Canada." },
    source: src("Canada's Regions: Ontario"),
  },
  {
    id: "geo-e-033",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "Which city is Canada's main financial centre?" },
    options: [{ en: "Montreal" }, { en: "Vancouver" }, { en: "Ottawa" }, { en: "Toronto" }],
    answerIndex: 3,
    explanation: {
      en: "Toronto is the largest city in Canada and the country's main financial centre.",
    },
    source: src("Canada's Regions: Ontario"),
  },
  {
    id: "geo-e-034",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "Which is Canada's second largest city?" },
    options: [{ en: "Toronto" }, { en: "Vancouver" }, { en: "Montreal" }, { en: "Ottawa" }],
    answerIndex: 2,
    explanation: { en: "Montreal is Canada's second largest city." },
    source: src("Canada's Regions: Quebec"),
  },
  {
    id: "geo-e-035",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "Which is the smallest province in Canada?" },
    options: [
      { en: "Prince Edward Island" },
      { en: "Nova Scotia" },
      { en: "New Brunswick" },
      { en: "Newfoundland and Labrador" },
    ],
    answerIndex: 0,
    explanation: { en: "Prince Edward Island (P.E.I.) is the smallest province." },
    source: src("Canada's Regions: Prince Edward Island"),
  },
  {
    id: "geo-e-036",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "Which is the most populous Atlantic province?" },
    options: [
      { en: "New Brunswick" },
      { en: "Newfoundland and Labrador" },
      { en: "Nova Scotia" },
      { en: "Prince Edward Island" },
    ],
    answerIndex: 2,
    explanation: { en: "Nova Scotia is the most populous Atlantic province." },
    source: src("Canada's Regions: Nova Scotia"),
  },
  {
    id: "geo-e-037",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "Which is the most populous Prairie province?" },
    options: [{ en: "Manitoba" }, { en: "Alberta" }, { en: "Saskatchewan" }, { en: "Ontario" }],
    answerIndex: 1,
    explanation: { en: "Alberta is the most populous Prairie province." },
    source: src("Canada's Regions: Alberta"),
  },
  {
    id: "geo-e-038",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "Which is Canada's westernmost province?" },
    options: [{ en: "Alberta" }, { en: "British Columbia" }, { en: "Yukon" }, { en: "Manitoba" }],
    answerIndex: 1,
    explanation: {
      en: "British Columbia, on the Pacific coast, is Canada's westernmost province.",
    },
    source: src("Canada's Regions: British Columbia"),
  },
  {
    id: "geo-e-039",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "Which province is the most easterly point in North America?" },
    options: [
      { en: "Nova Scotia" },
      { en: "Prince Edward Island" },
      { en: "New Brunswick" },
      { en: "Newfoundland and Labrador" },
    ],
    answerIndex: 3,
    explanation: { en: "Newfoundland and Labrador is the most easterly point in North America." },
    source: src("Canada's Regions: Newfoundland and Labrador"),
  },
  {
    id: "geo-e-040",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "Which province is known as the birthplace of Confederation?" },
    options: [
      { en: "Prince Edward Island" },
      { en: "Ontario" },
      { en: "Quebec" },
      { en: "Nova Scotia" },
    ],
    answerIndex: 0,
    explanation: { en: "Prince Edward Island is the birthplace of Confederation." },
    source: src("Canada's Regions: Prince Edward Island"),
  },
  {
    id: "geo-e-041",
    topicId: "geography",
    difficulty: "easy",
    prompt: {
      en: "Which province was once known as the 'breadbasket of the world' and the 'wheat province'?",
    },
    options: [{ en: "Manitoba" }, { en: "Alberta" }, { en: "Saskatchewan" }, { en: "Ontario" }],
    answerIndex: 2,
    explanation: {
      en: "Saskatchewan was once known as the 'breadbasket of the world' and the 'wheat province'.",
    },
    source: src("Canada's Regions: Saskatchewan"),
  },
  {
    id: "geo-e-042",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "Which region is often called the 'Land of the Midnight Sun'?" },
    options: [
      { en: "The North" },
      { en: "The Prairies" },
      { en: "The West Coast" },
      { en: "Central Canada" },
    ],
    answerIndex: 0,
    explanation: { en: "The North is often referred to as the 'Land of the Midnight Sun'." },
    source: src("Canada's Regions: The Northern Territories"),
  },
  {
    id: "geo-e-043",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "Which city is called the 'diamond capital of North America'?" },
    options: [{ en: "Whitehorse" }, { en: "Iqaluit" }, { en: "Regina" }, { en: "Yellowknife" }],
    answerIndex: 3,
    explanation: { en: "Yellowknife is called the 'diamond capital of North America'." },
    source: src("Canada's Regions: Northwest Territories"),
  },
  {
    id: "geo-e-044",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "What does 'Nunavut' mean in Inuktitut?" },
    options: [
      { en: "Land of the midnight sun" },
      { en: "Diamond capital" },
      { en: "Our land" },
      { en: "Big water" },
    ],
    answerIndex: 2,
    explanation: { en: "Nunavut means 'our land' in Inuktitut." },
    source: src("Canada's Regions: Nunavut"),
  },
  {
    id: "geo-e-045",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "How many Great Lakes are located between Ontario and the United States?" },
    options: [{ en: "Three" }, { en: "Four" }, { en: "Five" }, { en: "Seven" }],
    answerIndex: 2,
    explanation: {
      en: "There are five Great Lakes located between Ontario and the United States.",
    },
    source: src("Canada's Regions: Ontario"),
  },
  {
    id: "geo-e-046",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "Which is the largest freshwater lake in the world?" },
    options: [
      { en: "Lake Ontario" },
      { en: "Lake Superior" },
      { en: "Lake Erie" },
      { en: "Lake Huron" },
    ],
    answerIndex: 1,
    explanation: { en: "Lake Superior is the largest freshwater lake in the world." },
    source: src("Canada's Regions: Ontario"),
  },
  {
    id: "geo-e-047",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "The world's highest tides are found in which bay?" },
    options: [
      { en: "Frobisher Bay" },
      { en: "The St. Lawrence River" },
      { en: "Lake Superior" },
      { en: "The Bay of Fundy" },
    ],
    answerIndex: 3,
    explanation: { en: "Nova Scotia is known for the world's highest tides in the Bay of Fundy." },
    source: src("Canada's Regions: Nova Scotia"),
  },
  {
    id: "geo-e-048",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "What is the highest mountain in Canada?" },
    options: [
      { en: "The Rocky Mountains" },
      { en: "Mount Logan" },
      { en: "The Appalachian Range" },
      { en: "The Badlands" },
    ],
    answerIndex: 1,
    explanation: { en: "Mount Logan, located in the Yukon, is the highest mountain in Canada." },
    source: src("Canada's Regions: Yukon"),
  },
  {
    id: "geo-e-049",
    topicId: "geography",
    difficulty: "easy",
    prompt: {
      en: "In which territory was the coldest temperature ever recorded in Canada (-63°C)?",
    },
    options: [
      { en: "Yukon" },
      { en: "Nunavut" },
      { en: "The Northwest Territories" },
      { en: "Alberta" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Yukon holds the record for the coldest temperature ever recorded in Canada (-63°C).",
    },
    source: src("Canada's Regions: Yukon"),
  },
  {
    id: "geo-e-050",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "The Mackenzie River is the ___ longest river system in North America." },
    options: [{ en: "longest" }, { en: "third" }, { en: "second" }, { en: "fourth" }],
    answerIndex: 2,
    explanation: {
      en: "The Mackenzie River is the second-longest river system in North America after the Mississippi.",
    },
    source: src("Canada's Regions: Northwest Territories"),
  },
  {
    id: "geo-e-051",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "Which is Canada's largest and busiest port?" },
    options: [
      { en: "The Port of Vancouver" },
      { en: "The Port of Halifax" },
      { en: "The Port of Saint John" },
      { en: "The Port of Charlottetown" },
    ],
    answerIndex: 0,
    explanation: { en: "The Port of Vancouver is Canada's largest and busiest port." },
    source: src("Canada's Regions: British Columbia"),
  },
  {
    id: "geo-e-052",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "Which city is home to Canada's largest naval base?" },
    options: [{ en: "Victoria" }, { en: "Halifax" }, { en: "Vancouver" }, { en: "Ottawa" }],
    answerIndex: 1,
    explanation: { en: "Halifax is home to Canada's largest naval base." },
    source: src("Canada's Regions: Nova Scotia"),
  },
  {
    id: "geo-e-053",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "Much of the North is tundra, a vast rocky Arctic plain with ___." },
    options: [
      { en: "many oak trees" },
      { en: "thick pine forests" },
      { en: "no trees" },
      { en: "tropical plants" },
    ],
    answerIndex: 2,
    explanation: { en: "Because of the cold Arctic climate, there are no trees on the tundra." },
    source: src("Canada's Regions: The Northern Territories"),
  },
  {
    id: "geo-e-054",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "Ottawa is located on which river?" },
    options: [
      { en: "The St. Lawrence River" },
      { en: "The Ottawa River" },
      { en: "The Mackenzie River" },
      { en: "The St. John River" },
    ],
    answerIndex: 1,
    explanation: { en: "Ottawa is located on the Ottawa River." },
    source: src("Canada's Regions: The National Capital"),
  },
  {
    id: "geo-e-055",
    topicId: "geography",
    difficulty: "easy",
    prompt: {
      en: "Ottawa's Rideau Canal, once a military waterway, is now a tourist attraction and ___.",
    },
    options: [
      { en: "summer beach" },
      { en: "ski resort" },
      { en: "winter skateway" },
      { en: "cargo port" },
    ],
    answerIndex: 2,
    explanation: { en: "The Rideau Canal is now a tourist attraction and winter skateway." },
    source: src("Canada's Regions: The National Capital"),
  },
  {
    id: "geo-e-056",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "Anne of Green Gables is set in which province?" },
    options: [
      { en: "Nova Scotia" },
      { en: "New Brunswick" },
      { en: "Ontario" },
      { en: "Prince Edward Island" },
    ],
    answerIndex: 3,
    explanation: { en: "Anne of Green Gables is set in P.E.I." },
    source: src("Canada's Regions: Prince Edward Island"),
  },
  {
    id: "geo-e-057",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "The Confederation Bridge connects Prince Edward Island to ___." },
    options: [
      { en: "Nova Scotia" },
      { en: "Newfoundland" },
      { en: "Quebec" },
      { en: "mainland Canada" },
    ],
    answerIndex: 3,
    explanation: { en: "P.E.I. is connected to mainland Canada by the Confederation Bridge." },
    source: src("Canada's Regions: Prince Edward Island"),
  },
  {
    id: "geo-e-058",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "Victoria is the headquarters of which fleet?" },
    options: [
      { en: "The navy's Pacific fleet" },
      { en: "The navy's Atlantic fleet" },
      { en: "The Arctic patrol fleet" },
      { en: "The Great Lakes fleet" },
    ],
    answerIndex: 0,
    explanation: { en: "Victoria is the headquarters of the navy's Pacific fleet." },
    source: src("Canada's Regions: British Columbia"),
  },
  {
    id: "geo-e-059",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "Iqaluit, the capital of Nunavut, was formerly known as ___." },
    options: [
      { en: "Whitehorse" },
      { en: "Yellowknife" },
      { en: "Resolute" },
      { en: "Frobisher Bay" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Iqaluit was formerly Frobisher Bay, named after the explorer Martin Frobisher.",
    },
    source: src("Canada's Regions: Nunavut"),
  },
  {
    id: "geo-e-060",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "The training academy of the Royal Canadian Mounted Police is in which city?" },
    options: [{ en: "Regina" }, { en: "Ottawa" }, { en: "Winnipeg" }, { en: "Edmonton" }],
    answerIndex: 0,
    explanation: {
      en: "Regina, the capital of Saskatchewan, is home to the training academy of the Royal Canadian Mounted Police.",
    },
    source: src("Canada's Regions: Saskatchewan"),
  },
  {
    id: "geo-e-061",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "What is the largest city in Saskatchewan?" },
    options: [{ en: "Regina" }, { en: "Winnipeg" }, { en: "Saskatoon" }, { en: "Edmonton" }],
    answerIndex: 2,
    explanation: { en: "Saskatoon is the largest city in Saskatchewan." },
    source: src("Canada's Regions: Saskatchewan"),
  },
  {
    id: "geo-e-062",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "What is the largest city in New Brunswick?" },
    options: [{ en: "Saint John" }, { en: "Fredericton" }, { en: "Moncton" }, { en: "Halifax" }],
    answerIndex: 0,
    explanation: { en: "Saint John is the largest city in New Brunswick." },
    source: src("Canada's Regions: New Brunswick"),
  },
  {
    id: "geo-e-063",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "Which city is the principal Francophone Acadian centre?" },
    options: [{ en: "Fredericton" }, { en: "Moncton" }, { en: "Saint John" }, { en: "Halifax" }],
    answerIndex: 1,
    explanation: { en: "Moncton is the principal Francophone Acadian centre." },
    source: src("Canada's Regions: New Brunswick"),
  },
  {
    id: "geo-e-064",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "The vast majority of Quebec's nearly eight million people live ___." },
    options: [
      { en: "in the Rocky Mountains" },
      { en: "along the Arctic coast" },
      { en: "along or near the St. Lawrence River" },
      { en: "near the Great Lakes" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Nearly eight million people live in Quebec, the vast majority along or near the St. Lawrence River.",
    },
    source: src("Canada's Regions: Quebec"),
  },
  {
    id: "geo-e-065",
    topicId: "geography",
    difficulty: "easy",
    prompt: {
      en: "Which region is known as the industrial and manufacturing heartland of Canada?",
    },
    options: [
      { en: "The Prairies" },
      { en: "The West Coast" },
      { en: "Central Canada" },
      { en: "Atlantic Canada" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Central Canada — southern Quebec and Ontario — is the industrial and manufacturing heartland.",
    },
    source: src("Canada's Regions: Central Canada"),
  },
  {
    id: "geo-e-066",
    topicId: "geography",
    difficulty: "easy",
    prompt: {
      en: "More than half of Canadians live in cities and towns near the Great Lakes and the St. Lawrence River in ___.",
    },
    options: [
      { en: "the Prairies" },
      { en: "the North" },
      { en: "Atlantic Canada" },
      { en: "southern Quebec and Ontario" },
    ],
    answerIndex: 3,
    explanation: {
      en: "More than half the people in Canada live in cities and towns near the Great Lakes and the St. Lawrence River in southern Quebec and Ontario.",
    },
    source: src("Canada's Regions: Central Canada"),
  },
  {
    id: "geo-e-067",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "Banff National Park is located in which province?" },
    options: [{ en: "British Columbia" }, { en: "Alberta" }, { en: "Manitoba" }, { en: "Ontario" }],
    answerIndex: 1,
    explanation: { en: "Banff National Park is one of Alberta's five national parks." },
    source: src("Canada's Regions: Alberta"),
  },
  {
    id: "geo-e-068",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "The rugged Badlands are famous for ___." },
    options: [
      { en: "gold mines" },
      { en: "the world's highest tides" },
      { en: "ice-free ports" },
      { en: "prehistoric fossils and dinosaur finds" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The rugged Badlands house some of the world's richest deposits of prehistoric fossils and dinosaur finds.",
    },
    source: src("Canada's Regions: Alberta"),
  },
  {
    id: "geo-e-069",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "The Okanagan Valley in British Columbia is known for ___." },
    options: [
      { en: "wheat farms" },
      { en: "diamond mines" },
      { en: "fruit orchards and the wine industry" },
      { en: "oil sands" },
    ],
    answerIndex: 2,
    explanation: {
      en: "B.C. is known for the fruit orchards and wine industry of the Okanagan Valley.",
    },
    source: src("Canada's Regions: British Columbia"),
  },
  {
    id: "geo-e-070",
    topicId: "geography",
    difficulty: "easy",
    prompt: {
      en: "Thousands of miners came to which territory during the Gold Rush of the 1890s?",
    },
    options: [
      { en: "Nunavut" },
      { en: "The Northwest Territories" },
      { en: "Yukon" },
      { en: "Alaska" },
    ],
    answerIndex: 2,
    explanation: { en: "Thousands of miners came to the Yukon during the Gold Rush of the 1890s." },
    source: src("Canada's Regions: Yukon"),
  },
  {
    id: "geo-e-071",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "Portage and Main, Canada's most famous street intersection, is in which city?" },
    options: [{ en: "Winnipeg" }, { en: "Toronto" }, { en: "Montreal" }, { en: "Regina" }],
    answerIndex: 0,
    explanation: {
      en: "Winnipeg's Exchange District includes the most famous street intersection in Canada, Portage and Main.",
    },
    source: src("Canada's Regions: Manitoba"),
  },
  {
    id: "geo-e-072",
    topicId: "geography",
    difficulty: "easy",
    prompt: { en: "Canada's southern edge is the boundary with which country?" },
    options: [{ en: "The United States" }, { en: "Mexico" }, { en: "Greenland" }, { en: "Russia" }],
    answerIndex: 0,
    explanation: {
      en: "Along the southern edge of Canada lies the Canada-United States boundary.",
    },
    source: src("Canada's Regions"),
  },
  {
    id: "geo-m-001",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "Who chose Ottawa as the capital of Canada in 1857?" },
    options: [
      { en: "Queen Elizabeth II" },
      { en: "Sir William Logan" },
      { en: "Queen Victoria" },
      { en: "Martin Frobisher" },
    ],
    answerIndex: 2,
    explanation: { en: "Ottawa was chosen as the capital in 1857 by Queen Victoria." },
    source: src("Canada's Regions: The National Capital"),
  },
  {
    id: "geo-m-002",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "Ottawa is Canada's ___ largest metropolitan area." },
    options: [{ en: "largest" }, { en: "second" }, { en: "third" }, { en: "fourth" }],
    answerIndex: 3,
    explanation: { en: "Today Ottawa is Canada's fourth largest metropolitan area." },
    source: src("Canada's Regions: The National Capital"),
  },
  {
    id: "geo-m-003",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "How large is the National Capital Region surrounding Ottawa?" },
    options: [
      { en: "10 million square kilometres" },
      { en: "4,700 square kilometres" },
      { en: "1,857 square kilometres" },
      { en: "34,000 square kilometres" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The National Capital Region covers 4,700 square kilometres surrounding Ottawa.",
    },
    source: src("Canada's Regions: The National Capital"),
  },
  {
    id: "geo-m-004",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "The Atlantic provinces' coasts and natural resources include ___." },
    options: [
      { en: "oil sands and diamonds" },
      { en: "fishing, farming, forestry and mining" },
      { en: "wheat and potash" },
      { en: "gold and copper" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Atlantic Canada's natural resources include fishing, farming, forestry and mining.",
    },
    source: src("Canada's Regions: The Atlantic Provinces"),
  },
  {
    id: "geo-m-005",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "The Atlantic Ocean brings the Atlantic provinces ___." },
    options: [
      { en: "long cold winters and short cool summers" },
      { en: "hot dry summers" },
      { en: "cool winters and cool humid summers" },
      { en: "a temperate climate all year" },
    ],
    answerIndex: 2,
    explanation: { en: "The Atlantic Ocean brings cool winters and cool humid summers." },
    source: src("Canada's Regions: The Atlantic Provinces"),
  },
  {
    id: "geo-m-006",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "Which province has its own time zone?" },
    options: [
      { en: "Prince Edward Island" },
      { en: "Newfoundland and Labrador" },
      { en: "Nova Scotia" },
      { en: "New Brunswick" },
    ],
    answerIndex: 1,
    explanation: { en: "Newfoundland and Labrador has its own time zone." },
    source: src("Canada's Regions: Newfoundland and Labrador"),
  },
  {
    id: "geo-m-007",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "Which province was the oldest colony of the British Empire?" },
    options: [
      { en: "Newfoundland and Labrador" },
      { en: "Nova Scotia" },
      { en: "Ontario" },
      { en: "Quebec" },
    ],
    answerIndex: 0,
    explanation: { en: "Newfoundland and Labrador was the oldest colony of the British Empire." },
    source: src("Canada's Regions: Newfoundland and Labrador"),
  },
  {
    id: "geo-m-008",
    topicId: "geography",
    difficulty: "medium",
    prompt: {
      en: "In Newfoundland and Labrador, offshore oil and gas extraction contributes ___.",
    },
    options: [
      { en: "nothing to the economy" },
      { en: "only a tiny part of tourism" },
      { en: "most of the fishing jobs" },
      { en: "a substantial part of the economy" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Today offshore oil and gas extraction contributes a substantial part of the province's economy.",
    },
    source: src("Canada's Regions: Newfoundland and Labrador"),
  },
  {
    id: "geo-m-009",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "Labrador is known for its immense ___ resources." },
    options: [{ en: "coal" }, { en: "diamond" }, { en: "hydro-electric" }, { en: "uranium" }],
    answerIndex: 2,
    explanation: { en: "Labrador also has immense hydro-electric resources." },
    source: src("Canada's Regions: Newfoundland and Labrador"),
  },
  {
    id: "geo-m-010",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "Prince Edward Island is known for its beaches and ___ soil." },
    options: [{ en: "black" }, { en: "red" }, { en: "white" }, { en: "golden" }],
    answerIndex: 1,
    explanation: { en: "P.E.I. is known for its beaches, red soil and agriculture." },
    source: src("Canada's Regions: Prince Edward Island"),
  },
  {
    id: "geo-m-011",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "Agriculture on Prince Edward Island is known especially for ___." },
    options: [{ en: "wheat" }, { en: "corn" }, { en: "rice" }, { en: "potatoes" }],
    answerIndex: 3,
    explanation: { en: "P.E.I. is known for its agriculture, especially potatoes." },
    source: src("Canada's Regions: Prince Edward Island"),
  },
  {
    id: "geo-m-012",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "The Confederation Bridge is ___." },
    options: [
      { en: "one of the longest continuous multispan bridges in the world" },
      { en: "the shortest bridge in Canada" },
      { en: "a railway bridge to Newfoundland" },
      { en: "a bridge over the St. Lawrence River" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The Confederation Bridge is one of the longest continuous multispan bridges in the world.",
    },
    source: src("Canada's Regions: Prince Edward Island"),
  },
  {
    id: "geo-m-013",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "Who wrote Anne of Green Gables?" },
    options: [
      { en: "Robert W. Service" },
      { en: "Martin Frobisher" },
      { en: "Lucy Maud Montgomery" },
      { en: "Sir William Logan" },
    ],
    answerIndex: 2,
    explanation: { en: "Anne of Green Gables was written by Lucy Maud Montgomery." },
    source: src("Canada's Regions: Prince Edward Island"),
  },
  {
    id: "geo-m-014",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "Anne of Green Gables is a story about ___." },
    options: [
      { en: "a gold miner in the Yukon" },
      { en: "a voyageur on the St. Lawrence" },
      { en: "a Mountie in Saskatchewan" },
      { en: "a little red-headed orphan girl" },
    ],
    answerIndex: 3,
    explanation: {
      en: "It is a much-loved story about the adventures of a little red-headed orphan girl.",
    },
    source: src("Canada's Regions: Prince Edward Island"),
  },
  {
    id: "geo-m-015",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "Nova Scotia is known for its rich history as ___." },
    options: [
      { en: "the gateway to Canada" },
      { en: "the birthplace of Confederation" },
      { en: "the diamond capital of North America" },
      { en: "the wheat province" },
    ],
    answerIndex: 0,
    explanation: { en: "Nova Scotia has a rich history as the gateway to Canada." },
    source: src("Canada's Regions: Nova Scotia"),
  },
  {
    id: "geo-m-016",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "Nova Scotia's identity is linked to ___." },
    options: [
      { en: "oil sands and cattle ranching" },
      { en: "potash and uranium mining" },
      { en: "shipbuilding, fisheries and shipping" },
      { en: "hydro-electric dams" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The province's identity is linked to shipbuilding, fisheries and shipping.",
    },
    source: src("Canada's Regions: Nova Scotia"),
  },
  {
    id: "geo-m-017",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "Halifax is Canada's largest east coast port because it is ___." },
    options: [
      { en: "the oldest port in Canada" },
      { en: "the warmest port in Canada" },
      { en: "the smallest port in Canada" },
      { en: "deep-water and ice-free" },
    ],
    answerIndex: 3,
    explanation: { en: "Halifax is Canada's largest east coast port, deep-water and ice-free." },
    source: src("Canada's Regions: Nova Scotia"),
  },
  {
    id: "geo-m-018",
    topicId: "geography",
    difficulty: "medium",
    prompt: { en: "Nova Scotia has a long history of ___." },
    options: [
      { en: "gold mining and diamond cutting" },
      { en: "oil sands development" },
      { en: "wheat farming" },
      { en: "coal mining, forestry and agriculture" },
    ],
    answerIndex: 3,
    explanation: { en: "Nova Scotia has a long history of coal mining, forestry and agriculture." },
    source: src("Canada's Regions: Nova Scotia"),
  },
];
