/**
 * Question bank chunk — part of questions.generated.ts. DO NOT EDIT BY HAND.
 */
import type { Question } from "../content";
import { src } from "./shared";

export const governmentA: Question[] = [
  {
    id: "gov-e-001",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "Which three facts describe Canada's system of government?" },
    options: [
      { en: "A federal state, a parliamentary democracy and a constitutional monarchy" },
      { en: "A republic, a presidential democracy and a theocracy" },
      { en: "A unitary state, a direct democracy and an absolute monarchy" },
      { en: "A confederation, a parliamentary republic and a military state" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The study guide states three key facts: Canada is a federal state, a parliamentary democracy and a constitutional monarchy.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-e-002",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "Who is Canada's Head of State?" },
    options: [
      { en: "The Prime Minister" },
      { en: "A hereditary Sovereign (Queen or King)" },
      { en: "The Governor General" },
      { en: "The Speaker of the House of Commons" },
    ],
    answerIndex: 1,
    explanation: {
      en: "As a constitutional monarchy, Canada's Head of State is a hereditary Sovereign (Queen or King).",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-e-003",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "Who is Canada's Head of Government?" },
    options: [
      { en: "The Sovereign" },
      { en: "The Governor General" },
      { en: "The Prime Minister" },
      { en: "The Chief Justice" },
    ],
    answerIndex: 2,
    explanation: {
      en: "There is a clear distinction between the head of state (the Sovereign) and the head of government — the Prime Minister, who actually directs the governing of the country.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-e-004",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "Who actually directs the governing of Canada?" },
    options: [
      { en: "The Lieutenant Governor" },
      { en: "The monarch's household" },
      { en: "The Senate" },
      { en: "The Prime Minister" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The Prime Minister is the head of government and actually directs the governing of the country.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-e-005",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "How old must Canadian citizens be to vote in elections?" },
    options: [
      { en: "18 years or older" },
      { en: "16 years or older" },
      { en: "21 years or older" },
      { en: "25 years or older" },
    ],
    answerIndex: 0,
    explanation: {
      en: "It is important for Canadians aged 18 or more to participate in their democracy by voting.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-e-006",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "Who is eligible to vote in a federal election?" },
    options: [
      { en: "Any resident of Canada" },
      { en: "A Canadian citizen, at least 18 years old on voting day, and on the voters' list" },
      { en: "A permanent resident who pays taxes" },
      { en: "Any person over 18 who owns property in Canada" },
    ],
    answerIndex: 1,
    explanation: {
      en: "To vote federally you must be a Canadian citizen, at least 18 years old on voting day, and on the voters' list.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-e-007",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "What does a secret ballot mean in Canada?" },
    options: [
      { en: "Only government officials may vote" },
      { en: "Votes are cast in secret so no one can watch you vote or see how you voted" },
      { en: "Ballots are counted in secret by the Prime Minister" },
      { en: "Only citizens with secret clearance may vote" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Canadian law secures the right to a secret ballot: no one can watch you vote and no one should look at how you voted.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-e-008",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "How do you mark your ballot in a federal election?" },
    options: [
      { en: "By signing your name on it" },
      { en: "By circling your province" },
      { en: "By writing the Prime Minister's name" },
      { en: "By marking an 'X' in the circle next to the name of the candidate of your choice" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Mark an 'X' in the circle next to the name of the candidate of your choice.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-e-009",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "How many electoral districts is Canada divided into for federal elections?" },
    options: [{ en: "308" }, { en: "338" }, { en: "250" }, { en: "415" }],
    answerIndex: 0,
    explanation: {
      en: "Canada is divided into 308 electoral districts, also known as ridings or constituencies. (Note: the study guide gives 308; after the 2021 redistribution, Canada now has 343 federal electoral districts.)",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-e-010",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "What are electoral districts also called?" },
    options: [
      { en: "Wards or boroughs" },
      { en: "Ridings or constituencies" },
      { en: "Precincts or parishes" },
      { en: "Divisions or counties" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Canada is divided into 308 electoral districts, also known as ridings or constituencies. (Note: the study guide gives 308; after the 2021 redistribution, Canada now has 343 federal electoral districts.)",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-e-011",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "Where do elected Members of Parliament (MPs) sit?" },
    options: [
      { en: "The Senate" },
      { en: "The Supreme Court" },
      { en: "The House of Commons" },
      { en: "The National Assembly" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The citizens in each electoral district elect one MP who sits in the House of Commons to represent them.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-e-012",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "How does a candidate become the MP for an electoral district?" },
    options: [
      { en: "By appointment of the Governor General" },
      { en: "By approval of the Senate" },
      { en: "By election of the Cabinet" },
      { en: "By receiving the most votes in that electoral district" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The candidate who receives the most votes becomes the MP for that electoral district.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-e-013",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "Under legislation, when must federal elections be held?" },
    options: [
      {
        en: "On the third Monday in October every four years following the most recent general election",
      },
      { en: "On the first Monday in May every three years" },
      { en: "Whenever the opposition demands one" },
      { en: "On Canada Day every year" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Federal elections must be held on the third Monday in October every four years following the most recent general election.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-e-014",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "Who can ask the Governor General to call an earlier federal election?" },
    options: [
      { en: "The Leader of the Opposition" },
      { en: "The Prime Minister" },
      { en: "The Chief Electoral Officer" },
      { en: "Any Member of Parliament" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The Prime Minister may ask the Governor General to call an earlier election.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-e-015",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "What does the voter information card tell you?" },
    options: [
      { en: "Your political party membership number" },
      { en: "The names of all candidates in Canada" },
      { en: "When and where you vote" },
      { en: "The result of the last election" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Elections Canada mails a voter information card listing when and where you vote and the number to call for special services.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-e-016",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "What is Elections Canada?" },
    options: [
      { en: "A political party" },
      { en: "A neutral agency of Parliament that produces the voters' lists" },
      { en: "A government department run by the Prime Minister" },
      { en: "A private company that counts votes" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The voters' lists are produced from the National Register of Electors by a neutral agency of Parliament called Elections Canada.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-e-017",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "What is the National Register of Electors?" },
    options: [
      {
        en: "A permanent database of Canadian citizens 18 years or older who are qualified to vote",
      },
      { en: "A list of all taxpayers in Canada" },
      { en: "A registry of political party donors" },
      { en: "A database of elected officials" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The National Register of Electors is a permanent database of Canadian citizens 18 years of age or older who are qualified to vote in federal elections and referendums.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-e-018",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "What are the three parts of Canada's Parliament?" },
    options: [
      { en: "The Cabinet, the judiciary and the police" },
      { en: "The Sovereign, the Senate and the House of Commons" },
      { en: "The Prime Minister, the Premiers and the mayors" },
      { en: "The Governor General, the Lieutenant Governors and the Commissioners" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Parliament has three parts: the Sovereign (Queen or King), the Senate and the House of Commons.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-e-019",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "How do Senators get their positions, and how long do they serve?" },
    options: [
      { en: "Elected every four years" },
      { en: "Elected for life by the provinces" },
      {
        en: "Appointed by the Governor General on the advice of the Prime Minister, serving until age 75",
      },
      { en: "Chosen by the Supreme Court for ten-year terms" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Senators are appointed by the Governor General on the advice of the Prime Minister and serve until age 75.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-e-020",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "What must happen before a bill can become law in Canada?" },
    options: [
      { en: "Approval by the Prime Minister alone" },
      { en: "A referendum in every province" },
      {
        en: "It must be passed by both the House of Commons and the Senate, and receive royal assent",
      },
      { en: "A two-thirds vote of the Cabinet" },
    ],
    answerIndex: 2,
    explanation: {
      en: "No bill can become law in Canada until it has been passed by both chambers and has received royal assent.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-e-021",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "Who selects the Cabinet ministers?" },
    options: [
      { en: "The Prime Minister" },
      { en: "The Governor General acting alone" },
      { en: "The Senate" },
      { en: "The voters in a general election" },
    ],
    answerIndex: 0,
    explanation: {
      en: "In the federal government, the Prime Minister selects the Cabinet ministers.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-e-022",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "What is a majority government?" },
    options: [
      { en: "A government led by the Governor General" },
      {
        en: "A government where the party in power holds at least half of the seats in the House of Commons",
      },
      { en: "A government formed only by Senators" },
      { en: "A government with no opposition parties" },
    ],
    answerIndex: 1,
    explanation: {
      en: "If the party in power holds at least half of the seats in the House of Commons, this is called a majority government.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-e-023",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "What is a minority government?" },
    options: [
      { en: "A government led by a minor political party" },
      { en: "A government formed by the provinces" },
      {
        en: "A government where the party in power holds less than half of the seats in the House of Commons",
      },
      { en: "A government with no Cabinet" },
    ],
    answerIndex: 2,
    explanation: {
      en: "If the party in power holds less than half of the seats in the House of Commons, this is called a minority government.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-e-024",
    topicId: "government",
    difficulty: "easy",
    prompt: {
      en: "After an election, who is normally invited by the Governor General to form the government?",
    },
    options: [
      { en: "The oldest Member of Parliament" },
      { en: "The Chief Justice" },
      { en: "The Lieutenant Governor" },
      { en: "The leader of the political party with the most seats in the House of Commons" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Ordinarily, after an election, the leader of the political party with the most seats in the House of Commons is invited by the Governor General to form the government.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-e-025",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "Which of these is a federal government responsibility?" },
    options: [
      { en: "National defence" },
      { en: "Education" },
      { en: "Health care" },
      { en: "Municipal government" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The federal government takes responsibility for matters of national and international concern, including defence.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-e-026",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "Which level of government is responsible for foreign policy?" },
    options: [
      { en: "Municipal" },
      { en: "The federal government" },
      { en: "Provincial" },
      { en: "Territorial" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Foreign policy is one of the matters of national and international concern handled by the federal government.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-e-027",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "Which level of government is responsible for criminal law?" },
    options: [
      { en: "Municipal" },
      { en: "Provincial" },
      { en: "The federal government" },
      { en: "The courts alone" },
    ],
    answerIndex: 2,
    explanation: { en: "Criminal law is listed among the federal government's responsibilities." },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-e-028",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "Which level of government is responsible for education?" },
    options: [
      { en: "Federal" },
      { en: "Municipal" },
      { en: "First Nations band councils" },
      { en: "Provincial" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The provinces are responsible for municipal government, education, health, natural resources, property and civil rights, and highways.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-e-029",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "Which of these is a provincial government responsibility?" },
    options: [
      { en: "Health care" },
      { en: "Currency" },
      { en: "Foreign policy" },
      { en: "Citizenship" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The provinces are responsible for health, along with education, natural resources, highways, municipal government and property and civil rights.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-e-030",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "Which level of government is responsible for natural resources?" },
    options: [
      { en: "Federal" },
      { en: "Provincial" },
      { en: "Municipal" },
      { en: "The Governor General" },
    ],
    answerIndex: 1,
    explanation: { en: "Natural resources are a provincial responsibility." },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-e-031",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "Which two areas are shared between the federal government and the provinces?" },
    options: [
      { en: "Defence and currency" },
      { en: "Agriculture and immigration" },
      { en: "Criminal law and citizenship" },
      { en: "Navigation and currency" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The federal government and the provinces share jurisdiction over agriculture and immigration.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-e-032",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "Who heads a municipal government?" },
    options: [
      { en: "The Premier" },
      { en: "The Governor General" },
      { en: "A Member of Parliament" },
      { en: "A mayor or a reeve" },
    ],
    answerIndex: 3,
    explanation: {
      en: "A municipal council usually includes a mayor (or a reeve) and councillors or aldermen.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-e-033",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "What are laws passed by a municipal council called?" },
    options: [
      { en: "By-laws" },
      { en: "Statutes of Parliament" },
      { en: "Royal decrees" },
      { en: "Provincial codes" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Municipal governments usually have a council that passes laws called 'by-laws' that affect only the local community.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-e-034",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "Which of these is a municipal government responsibility?" },
    options: [
      { en: "Foreign policy" },
      { en: "Snow removal" },
      { en: "Criminal justice" },
      { en: "Currency" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Municipalities are normally responsible for snow removal, along with streets and roads, sanitation, firefighting, ambulance and other services.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-e-035",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "Who represents the Sovereign in each of the ten provinces?" },
    options: [
      { en: "The Prime Minister" },
      { en: "The Lieutenant Governor" },
      { en: "The Premier" },
      { en: "The Commissioner" },
    ],
    answerIndex: 1,
    explanation: {
      en: "In each of the ten provinces, the Sovereign is represented by the Lieutenant Governor.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-e-036",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "Who is the head of government in a province?" },
    options: [
      { en: "The Governor General" },
      { en: "The Lieutenant Governor" },
      { en: "The Mayor" },
      { en: "The Premier" },
    ],
    answerIndex: 3,
    explanation: {
      en: "In each province, the Premier has a role similar to that of the Prime Minister in the federal government.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-e-037",
    topicId: "government",
    difficulty: "easy",
    prompt: {
      en: "In the three territories, who represents the federal government in a ceremonial role?",
    },
    options: [
      { en: "The Commissioner" },
      { en: "The Governor General" },
      { en: "The Speaker" },
      { en: "The Chief Justice" },
    ],
    answerIndex: 0,
    explanation: {
      en: "In the three territories, the Commissioner represents the federal government and plays a ceremonial role.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-e-038",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "How is the Governor General chosen and for how long does he or she serve?" },
    options: [
      { en: "Elected by Canadians for four years" },
      {
        en: "Appointed by the Sovereign on the advice of the Prime Minister, usually for five years",
      },
      { en: "Chosen by the Senate for life" },
      { en: "Hired by Elections Canada for ten years" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The Governor General is appointed by the Sovereign on the advice of the Prime Minister, usually for five years.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-e-039",
    topicId: "government",
    difficulty: "easy",
    prompt: {
      en: "In what year and in which Act were the responsibilities of the federal and provincial governments defined?",
    },
    options: [
      { en: "1776, the Declaration of Independence" },
      { en: "1982, the Charter of Rights" },
      { en: "1867, the British North America Act, now known as the Constitution Act, 1867" },
      { en: "1812, the War of 1812 treaty" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The responsibilities of the federal and provincial governments were defined in 1867 in the British North America Act, now known as the Constitution Act, 1867.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-e-040",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "What is Canada's highest court?" },
    options: [
      { en: "The Court of Queen's Bench" },
      { en: "The Federal Court of Canada" },
      { en: "The provincial appeal court" },
      { en: "The Supreme Court of Canada" },
    ],
    answerIndex: 3,
    explanation: { en: "The Supreme Court of Canada is our country's highest court." },
    source: src("The Justice System"),
  },
  {
    id: "gov-e-041",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "In Canadian criminal matters, what does the presumption of innocence mean?" },
    options: [
      { en: "Everyone is innocent until proven guilty" },
      { en: "Only citizens are presumed innocent" },
      { en: "Guilt is decided by the police" },
      { en: "The accused must prove their innocence" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Our judicial system is founded on the presumption of innocence in criminal matters, meaning everyone is innocent until proven guilty.",
    },
    source: src("The Justice System"),
  },
  {
    id: "gov-e-042",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "Which police force enforces federal laws throughout Canada?" },
    options: [
      { en: "The Ontario Provincial Police" },
      { en: "The Royal Canadian Mounted Police (RCMP)" },
      { en: "The municipal police" },
      { en: "The border patrol of the United States" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The Royal Canadian Mounted Police (RCMP) enforce federal laws throughout Canada.",
    },
    source: src("The Justice System"),
  },
  {
    id: "gov-e-043",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "In which provinces does the RCMP NOT serve as the provincial police?" },
    options: [
      { en: "Alberta and British Columbia" },
      { en: "Manitoba and Saskatchewan" },
      { en: "Ontario and Quebec" },
      { en: "Nova Scotia and New Brunswick" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The RCMP serves as the provincial police in all provinces and territories except Ontario and Quebec, which have their own provincial police forces.",
    },
    source: src("The Justice System"),
  },
  {
    id: "gov-e-044",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "If you cannot pay for a lawyer in Canada, what help is available?" },
    options: [
      { en: "You must represent yourself" },
      { en: "Legal aid services are available free of charge or at a low cost" },
      { en: "The judge acts as your lawyer" },
      { en: "The police assign you a lawyer for free in every case" },
    ],
    answerIndex: 3,
    explanation: {
      en: "If you cannot pay for a lawyer, in most communities there are legal aid services available free of charge or at a low cost.",
    },
    source: src("The Justice System"),
  },
  {
    id: "gov-e-045",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "According to the guide, which Parliament did Queen Elizabeth II open in 1957?" },
    options: [
      { en: "The 23rd Parliament" },
      { en: "The 20th Parliament" },
      { en: "The 25th Parliament" },
      { en: "The 30th Parliament" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The guide's caption notes that Queen Elizabeth II opened the 23rd Parliament in 1957.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-e-046",
    topicId: "government",
    difficulty: "easy",
    prompt: {
      en: "According to the guide, who was the 28th Governor General since Confederation?",
    },
    options: [
      { en: "Adrienne Clarkson" },
      { en: "David Johnston" },
      { en: "Michaëlle Jean" },
      { en: "Julie Payette" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The guide's photo caption identifies David Johnston as the 28th Governor General since Confederation.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-e-047",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "What does every province have, like the House of Commons in Ottawa?" },
    options: [
      { en: "A provincial court of appeal" },
      { en: "A ceremonial Commissioner" },
      { en: "Its own elected Legislative Assembly" },
      { en: "A federally appointed Senate" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Every province has its own elected Legislative Assembly, like the House of Commons in Ottawa.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-e-048",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "Why do the three northern territories not have the status of provinces?" },
    options: [
      { en: "They have no elected officials" },
      { en: "They are not part of Canada" },
      { en: "They were created after 1999" },
      { en: "They have small populations" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The three northern territories, which have small populations, do not have the status of provinces.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-e-049",
    topicId: "government",
    difficulty: "easy",
    prompt: {
      en: "What happens to Cabinet ministers if they are defeated in a non-confidence vote?",
    },
    options: [
      {
        en: "They must retain the confidence of the House and resign if defeated in a non-confidence vote",
      },
      { en: "They serve for life" },
      { en: "They can never be removed by Parliament" },
      { en: "They answer only to the Sovereign" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Cabinet ministers must retain the 'confidence of the House' and have to resign if they are defeated in a non-confidence vote.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-e-050",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "Who makes up the House of Commons?" },
    options: [
      { en: "The Governor General" },
      { en: "The members of Parliament elected by the people, traditionally every four years" },
      { en: "The Senators" },
      { en: "The Supreme Court judges" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The House of Commons is made up of members of Parliament elected by the people, traditionally every four years.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-e-051",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "What are provincial legislatures made up of?" },
    options: [
      { en: "The Governor General and the Senate" },
      { en: "The Premier and the Cabinet" },
      { en: "The Lieutenant Governor and the elected Assembly" },
      { en: "The Commissioner and the House of Commons" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Provincial legislatures comprise the Lieutenant Governor and the elected Assembly.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-e-052",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "In which elections should Canadians aged 18 or more vote?" },
    options: [
      { en: "Only federal elections" },
      { en: "Only provincial elections" },
      { en: "Only municipal elections" },
      { en: "Federal, provincial or territorial, and municipal elections" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Canadians aged 18 or more should participate by voting in federal, provincial or territorial and municipal elections.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-e-053",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "What role does the Sovereign play as part of Parliament?" },
    options: [
      { en: "An important, non-partisan role as the focus of citizenship and allegiance" },
      { en: "A partisan role campaigning for the governing party" },
      { en: "No role in Parliament at all" },
      { en: "The role of choosing the Prime Minister alone" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The Sovereign is a part of Parliament, playing an important, non-partisan role as the focus of citizenship and allegiance, most visibly during royal visits to Canada.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-e-054",
    topicId: "government",
    difficulty: "easy",
    prompt: {
      en: "As Head of the Commonwealth, the Sovereign links Canada to how many other nations?",
    },
    options: [{ en: "50" }, { en: "53" }, { en: "28" }, { en: "100" }],
    answerIndex: 1,
    explanation: {
      en: "As Head of the Commonwealth, the Sovereign links Canada to 53 other nations that cooperate to advance social, economic and cultural progress.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-e-055",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "Which of these countries is also a constitutional monarchy, like Canada?" },
    options: [{ en: "France" }, { en: "The United States" }, { en: "Australia" }, { en: "Brazil" }],
    answerIndex: 2,
    explanation: {
      en: "The guide lists Australia, New Zealand, Denmark, Norway, Sweden, the Netherlands, Spain, Thailand, Japan, Jordan and Morocco as other constitutional monarchies.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-e-056",
    topicId: "government",
    difficulty: "easy",
    prompt: {
      en: "What are the elected members of provincial and territorial legislatures called?",
    },
    options: [
      { en: "Senators" },
      { en: "Aldermen" },
      { en: "Reeves" },
      {
        en: "Members of the Legislative Assembly (MLAs), members of the National Assembly (MNAs), members of the Provincial Parliament (MPPs) or members of the House of Assembly (MHAs)",
      },
    ],
    answerIndex: 3,
    explanation: {
      en: "Members of the legislature are called members of the Legislative Assembly (MLAs), members of the National Assembly (MNAs), members of the Provincial Parliament (MPPs) or members of the House of Assembly (MHAs), depending on the province or territory.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-e-057",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "What are the three branches of government in Canada?" },
    options: [
      { en: "The Executive, the Legislative and the Judicial" },
      { en: "The Federal, the Provincial and the Municipal" },
      { en: "The Crown, the Cabinet and the Courts" },
      { en: "The House, the Senate and the Sovereign" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The interplay between the three branches of government — the Executive, Legislative and Judicial — helps secure the rights and freedoms of Canadians.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-e-058",
    topicId: "government",
    difficulty: "easy",
    prompt: {
      en: "When the party in power is defeated, on whose behalf does the Prime Minister ask the Governor General to call an election?",
    },
    options: [
      { en: "On behalf of the Cabinet" },
      { en: "On behalf of the Sovereign" },
      { en: "On behalf of the Senate" },
      { en: "On behalf of the opposition" },
    ],
    answerIndex: 1,
    explanation: {
      en: "If defeated on a major vote, this usually results in the Prime Minister asking the Governor General, on behalf of the Sovereign, to call an election.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-e-059",
    topicId: "government",
    difficulty: "easy",
    prompt: {
      en: "Which three major political parties are currently represented in the House of Commons?",
    },
    options: [
      { en: "The Conservative Party, the Liberal Party and the Reform Party" },
      { en: "The Liberal Party, the Green Party and the Bloc Québécois" },
      { en: "The Conservative Party, the Liberal Party and the New Democratic Party" },
      { en: "The New Democratic Party, the Green Party and the Progressive Party" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The guide names three major political parties currently represented in the House of Commons: the Conservative Party, the Liberal Party, and the New Democratic Party.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-e-060",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "Which party is the Official Opposition (Her Majesty's Loyal Opposition)?" },
    options: [
      { en: "The largest provincial party" },
      { en: "The party with the most Senators" },
      { en: "The oldest political party" },
      { en: "The opposition party with the most members of the House of Commons" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The opposition party with the most members of the House of Commons is the Official Opposition or Her Majesty's Loyal Opposition.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-e-061",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "What is the role of opposition parties?" },
    options: [
      { en: "To peacefully oppose or try to improve government proposals" },
      { en: "To block all laws from passing" },
      { en: "To replace the Governor General" },
      { en: "To run the federal departments" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The role of opposition parties is to peacefully oppose or try to improve government proposals.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-e-062",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "What are the people who run for office in an election called?" },
    options: [
      { en: "Elected MPs" },
      { en: "Candidates" },
      { en: "Cabinet ministers" },
      { en: "Senators" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Canadian citizens who are 18 years old or older may run in a federal election; the people who run for office are called candidates.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-e-063",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "How many MPs does each electoral district elect?" },
    options: [{ en: "Three" }, { en: "Two" }, { en: "One" }, { en: "Five" }],
    answerIndex: 2,
    explanation: {
      en: "The citizens in each electoral district elect one MP who sits in the House of Commons to represent them.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-e-064",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "Who does a Member of Parliament represent?" },
    options: [
      { en: "Only the Prime Minister" },
      { en: "Only people who voted for them" },
      { en: "Only their own political party" },
      { en: "The citizens in their electoral district, as well as all Canadians" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Each MP sits in the House of Commons to represent the citizens of their electoral district, as well as all Canadians.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-e-065",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "In each election, what choice do voters have about their MPs?" },
    options: [
      { en: "They may re-elect the same members or choose new ones" },
      { en: "They must re-elect the same members" },
      { en: "They must choose all new members" },
      { en: "They can only vote for the Prime Minister's party" },
    ],
    answerIndex: 0,
    explanation: {
      en: "In each election, voters may re-elect the same members of the House of Commons or choose new ones.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-e-066",
    topicId: "government",
    difficulty: "easy",
    prompt: {
      en: "According to the guide, what number do you call Elections Canada in Ottawa if you did not get a voter information card?",
    },
    options: [{ en: "1-800-555-1212" }, { en: "1-800-463-6868" }, { en: "911" }, { en: "411" }],
    answerIndex: 1,
    explanation: {
      en: "If you do not receive a voter information card, call your local elections office; if you do not have the number, call Elections Canada, in Ottawa, at 1-800-463-6868.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-e-067",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "What if you did not receive a voter information card — can you still vote?" },
    options: [
      { en: "You can never vote in that election" },
      { en: "You must wait until the next election" },
      { en: "You can still be added to the voters' list at any time, including on election day" },
      { en: "Only your provincial representative can add you" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Even if you choose not to be listed in the National Register of Electors or do not receive a voter information card, you can still be added to the voters' list at any time, including on election day.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-e-068",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "If you cannot vote on election day, what are your options?" },
    options: [
      { en: "You cannot vote at all" },
      { en: "You must vote by mail from another country" },
      { en: "Only the Governor General can excuse you" },
      { en: "You can vote at the advance polls or by special ballot" },
    ],
    answerIndex: 3,
    explanation: {
      en: "If you cannot or do not wish to vote on election day, you can vote at the advance polls or by special ballot; the dates and location are on your voter information card.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-e-069",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "What should you bring to the polling station on election day?" },
    options: [
      { en: "Your voter information card and proof of your identity and address" },
      { en: "Only your political party membership" },
      { en: "A letter from your employer" },
      { en: "Your birth certificate and passport only" },
    ],
    answerIndex: 0,
    explanation: {
      en: "On election day, go to your polling station and bring your voter information card and proof of your identity and address.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-e-070",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "Where do you mark your ballot?" },
    options: [
      { en: "At the registration desk in public" },
      { en: "Behind the screen" },
      { en: "At home before arriving" },
      { en: "At the ballot box" },
    ],
    answerIndex: 1,
    explanation: {
      en: "You will be invited to go behind the screen to mark your ballot; once marked, fold it and present it to the poll officials.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-e-071",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "What happens after the poll official tears off the ballot number?" },
    options: [
      { en: "Keep the ballot as a souvenir" },
      { en: "Show it to the other voters" },
      { en: "Deposit it in the ballot box" },
      { en: "Mail it to Elections Canada" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The poll official will tear off the ballot number and give your ballot back to you to deposit in the ballot box.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-e-072",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "Who gets to see the election results?" },
    options: [
      { en: "Only the winning party" },
      { en: "Only the Prime Minister" },
      { en: "No one — results are kept secret" },
      { en: "The public, on television and on the Elections Canada website" },
    ],
    answerIndex: 3,
    explanation: {
      en: "When the polls close, every ballot is counted and the results are made public; you can see the results on television or on the Elections Canada website (www.elections.ca).",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-e-073",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "What are First Nations band chiefs and councillors responsible for?" },
    options: [
      { en: "Housing, schools and other services on First Nations reserves" },
      { en: "Federal elections" },
      { en: "National defence" },
      { en: "Foreign policy" },
    ],
    answerIndex: 0,
    explanation: {
      en: "First Nations band chiefs and councillors have major responsibilities on First Nations reserves, including housing, schools and other services.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-e-074",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "Who enforces the laws in Canada?" },
    options: [
      { en: "The courts" },
      { en: "The police" },
      { en: "The lawyers" },
      { en: "The journalists" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Canada's laws are made by elected representatives; the courts settle disputes and the police enforce the laws.",
    },
    source: src("The Justice System"),
  },
  {
    id: "gov-e-075",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "To whom does the law in Canada apply?" },
    options: [
      { en: "Only to ordinary citizens" },
      { en: "Only to visitors" },
      { en: "To everyone, including judges, politicians and the police" },
      { en: "Only to people under 65" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The law in Canada applies to everyone, including judges, politicians and the police.",
    },
    source: src("The Justice System"),
  },
  {
    id: "gov-e-076",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "What does the Federal Court of Canada deal with?" },
    options: [
      { en: "Divorce cases" },
      { en: "Traffic tickets" },
      { en: "Small claims disputes" },
      { en: "Matters concerning the federal government" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The Federal Court of Canada deals with matters concerning the federal government.",
    },
    source: src("The Justice System"),
  },
  {
    id: "gov-e-077",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "What is a provincial trial court sometimes called?" },
    options: [
      { en: "The Court of Queen's Bench or the Supreme Court" },
      { en: "The Senate Court" },
      { en: "The Election Court" },
      { en: "The Tax Court" },
    ],
    answerIndex: 0,
    explanation: {
      en: "In most provinces there is an appeal court and a trial court, sometimes called the Court of Queen's Bench or the Supreme Court.",
    },
    source: src("The Justice System"),
  },
  {
    id: "gov-e-078",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "What is due process?" },
    options: [
      { en: "The police decide who is guilty" },
      {
        en: "The government must respect all of the legal rights a person is entitled to under the law",
      },
      { en: "Trials are always held in secret" },
      { en: "Only judges have rights in court" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Due process is the principle that the government must respect all of the legal rights a person is entitled to under the law.",
    },
    source: src("The Justice System"),
  },
  {
    id: "gov-e-079",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "Can you question the police about their service or conduct?" },
    options: [
      { en: "You can never question the police" },
      { en: "You must go through the courts first" },
      { en: "You can question the police about their service or conduct and seek action" },
      { en: "Only the media can question the police" },
    ],
    answerIndex: 2,
    explanation: {
      en: "You can question the police about their service or conduct if you feel you need to; almost all police forces in Canada have a process by which you can bring your concerns to the police and seek action.",
    },
    source: src("The Justice System"),
  },
  {
    id: "gov-e-080",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "Who grants royal assent to a bill?" },
    options: [
      { en: "The Prime Minister" },
      { en: "The Leader of the Opposition" },
      { en: "The Chief Justice" },
      { en: "The Governor General, on behalf of the Sovereign" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Royal assent is granted by the Governor General on behalf of the Sovereign.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-e-081",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "Which courts handle civil cases involving small sums of money?" },
    options: [
      { en: "Small claims courts" },
      { en: "The Supreme Court of Canada" },
      { en: "The Senate" },
      { en: "The Federal Court of Canada" },
    ],
    answerIndex: 0,
    explanation: {
      en: "There are small claims courts for civil cases involving small sums of money.",
    },
    source: src("The Justice System"),
  },
  {
    id: "gov-e-082",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "How is a Lieutenant Governor chosen and for how long does he or she serve?" },
    options: [
      { en: "Elected by the province" },
      {
        en: "Appointed by the Governor General on the advice of the Prime Minister, normally for five years",
      },
      { en: "Chosen by the Senate" },
      { en: "Appointed by the Premier" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The Lieutenant Governor is appointed by the Governor General on the advice of the Prime Minister, also normally for five years.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-e-083",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "What happens at the Second Reading of a bill?" },
    options: [
      { en: "The bill is printed" },
      { en: "The committee studies it clause by clause" },
      { en: "Members debate the bill's principle" },
      { en: "Royal assent is granted" },
    ],
    answerIndex: 2,
    explanation: { en: "Step 2, Second Reading: Members debate the bill's principle." },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-e-084",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "What happens at the Committee Stage of a bill?" },
    options: [
      { en: "The bill is printed" },
      { en: "The members vote on it" },
      { en: "The Governor General signs it" },
      { en: "Committee members study the bill clause by clause" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Step 3, Committee Stage: Committee members study the bill clause by clause.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-e-085",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "What happens at the First Reading of a bill?" },
    options: [
      { en: "The bill is considered read for the first time and is printed" },
      { en: "The Senate rejects it" },
      { en: "The public votes on it" },
      { en: "It becomes law" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Step 1, First Reading: The bill is considered read for the first time and is printed.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-e-086",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "What happens at the Third Reading of a bill?" },
    options: [
      { en: "Members debate and vote on the bill" },
      { en: "The bill is printed" },
      { en: "The committee studies it clause by clause" },
      { en: "The Prime Minister signs it" },
    ],
    answerIndex: 0,
    explanation: { en: "Step 5, Third Reading: Members debate and vote on the bill." },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-e-087",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "What happens at the Report Stage of a bill?" },
    options: [
      { en: "The bill becomes law" },
      { en: "Royal assent is granted" },
      { en: "Members can make other amendments" },
      { en: "The Senate dissolves" },
    ],
    answerIndex: 2,
    explanation: { en: "Step 4, Report Stage: Members can make other amendments." },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-e-088",
    topicId: "government",
    difficulty: "easy",
    prompt: { en: "Who provides policing in most major urban centres?" },
    options: [
      { en: "The RCMP always" },
      { en: "The provincial police always" },
      { en: "The Canadian Armed Forces" },
      { en: "Municipal police forces" },
    ],
    answerIndex: 3,
    explanation: { en: "Most major urban centres have municipal police forces." },
    source: src("Federal Elections"),
  },
  {
    id: "gov-m-001",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "When the House of Commons votes on the budget, how is that vote considered?" },
    options: [
      { en: "A matter of confidence" },
      { en: "A ceremonial vote" },
      { en: "A Senate referral" },
      { en: "A by-election trigger" },
    ],
    answerIndex: 0,
    explanation: {
      en: "When the House of Commons votes on a major issue such as the budget, this is considered a matter of confidence.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-m-002",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "How long do the Prime Minister and the party in power run the government?" },
    options: [
      { en: "As long as the Governor General approves" },
      { en: "As long as they have the support or confidence of the majority of the MPs" },
      { en: "Until the next census" },
      { en: "For exactly four years no matter what" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The Prime Minister and the party in power run the government as long as they have the support or confidence of the majority of the MPs.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-m-003",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "From where does the Prime Minister choose most Cabinet ministers?" },
    options: [
      { en: "All of them from the Senate" },
      { en: "From the provincial Premiers" },
      { en: "Most of them from among members of the House of Commons" },
      { en: "All of them from outside Parliament" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The Prime Minister chooses the ministers of the Crown, most of them from among members of the House of Commons.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-m-004",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "Who prepares the budget and proposes most new laws?" },
    options: [
      { en: "The Supreme Court" },
      { en: "The opposition parties" },
      { en: "The Lieutenant Governors" },
      { en: "The Prime Minister and the Cabinet" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The Prime Minister and the Cabinet ministers prepare the budget and propose most new laws.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-m-005",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "Whose decisions can be questioned by all members of the House of Commons?" },
    options: [
      { en: "All members of the House of Commons" },
      { en: "Only Senators" },
      { en: "Only the Official Opposition" },
      { en: "Only the Governor General" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Their decisions can be questioned by all members of the House of Commons.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-m-006",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "Who appoints the leader of the winning party as Prime Minister?" },
    options: [
      { en: "The Speaker of the House" },
      { en: "The Governor General" },
      { en: "The Chief Justice" },
      { en: "The Lieutenant Governor" },
    ],
    answerIndex: 1,
    explanation: {
      en: "After being appointed by the Governor General, the leader of the party with the most seats becomes the Prime Minister.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-m-007",
    topicId: "government",
    difficulty: "medium",
    prompt: {
      en: "How do voting rules for provincial, territorial and municipal elections compare to federal rules?",
    },
    options: [
      { en: "Federal election rules apply everywhere" },
      { en: "Rules are identical at all levels" },
      {
        en: "Provincial, territorial and municipal elections are also by secret ballot, but their rules differ from federal rules",
      },
      { en: "Only federal elections use a secret ballot" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Provincial, territorial and municipal elections are held by secret ballot, but the rules are not the same as those for federal elections.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-m-008",
    topicId: "government",
    difficulty: "medium",
    prompt: {
      en: "Which of these is a shared responsibility of the federal and provincial governments?",
    },
    options: [{ en: "Defence" }, { en: "Criminal law" }, { en: "Currency" }, { en: "Environment" }],
    answerIndex: 3,
    explanation: {
      en: "The federal government and the provinces share jurisdiction over agriculture and immigration, and environment is listed as shared in the responsibility table.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-m-009",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "Which level of government is responsible for Aboriginal Affairs?" },
    options: [
      { en: "The federal government" },
      { en: "Provincial governments" },
      { en: "Municipal governments" },
      { en: "First Nations band councils alone" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Aboriginal Affairs appears under the federal government's responsibilities in the guide's table.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-m-010",
    topicId: "government",
    difficulty: "medium",
    prompt: {
      en: "Which responsibility appears at all three levels of government in the guide's table?",
    },
    options: [
      { en: "Education" },
      { en: "Policing" },
      { en: "Currency" },
      { en: "Natural resources" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Policing appears in the responsibility table under federal, provincial (Ontario, Quebec) and municipal governments.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-m-011",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "Which level of government is responsible for currency?" },
    options: [
      { en: "The provinces" },
      { en: "The municipalities" },
      { en: "The federal government" },
      { en: "The Bank of Canada alone" },
    ],
    answerIndex: 2,
    explanation: { en: "Currency is listed among the federal government's responsibilities." },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-m-012",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "Which level of government is responsible for navigation?" },
    options: [
      { en: "Provincial" },
      { en: "Municipal" },
      { en: "Territorial" },
      { en: "The federal government" },
    ],
    answerIndex: 3,
    explanation: { en: "Navigation is listed among the federal government's responsibilities." },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-m-013",
    topicId: "government",
    difficulty: "medium",
    prompt: {
      en: "Which level of government is responsible for interprovincial trade and communications?",
    },
    options: [
      { en: "The federal government" },
      { en: "Provincial governments" },
      { en: "Municipal governments" },
      { en: "The territories" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Interprovincial trade and communications is listed among the federal government's responsibilities.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-m-014",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "Which level of government is responsible for property and civil rights?" },
    options: [{ en: "Federal" }, { en: "Provincial" }, { en: "Municipal" }, { en: "The courts" }],
    answerIndex: 1,
    explanation: {
      en: "Property and civil rights is listed among the provinces' responsibilities.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-m-015",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "Which level of government is responsible for highways?" },
    options: [
      { en: "The federal government" },
      { en: "The municipalities" },
      { en: "Provincial governments" },
      { en: "The RCMP" },
    ],
    answerIndex: 2,
    explanation: { en: "Highways are listed among the provinces' responsibilities." },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-m-016",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "Which level of government is responsible for recycling programs?" },
    options: [{ en: "Federal" }, { en: "Provincial" }, { en: "Territorial" }, { en: "Municipal" }],
    answerIndex: 3,
    explanation: { en: "Recycling programs are listed among municipal responsibilities." },
    source: src("Federal Elections"),
  },
  {
    id: "gov-m-017",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "Which level of government is responsible for transportation and utilities?" },
    options: [
      { en: "Municipal governments" },
      { en: "The federal government" },
      { en: "Provincial governments" },
      { en: "Elections Canada" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Transportation and utilities are listed among municipal responsibilities.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-m-018",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "Which level of government is responsible for emergency services?" },
    options: [{ en: "Federal" }, { en: "Municipal" }, { en: "Provincial" }, { en: "Territorial" }],
    answerIndex: 1,
    explanation: { en: "Emergency services are listed among municipal responsibilities." },
    source: src("Federal Elections"),
  },
  {
    id: "gov-m-019",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "Which level of government is responsible for firefighting?" },
    options: [{ en: "Provincial" }, { en: "Federal" }, { en: "Municipal" }, { en: "The RCMP" }],
    answerIndex: 2,
    explanation: { en: "Firefighting is listed among municipal responsibilities." },
    source: src("Federal Elections"),
  },
  {
    id: "gov-m-020",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "Which level of government is responsible for social and community health?" },
    options: [{ en: "Federal" }, { en: "Provincial" }, { en: "Territorial" }, { en: "Municipal" }],
    answerIndex: 3,
    explanation: { en: "Social and community health is listed among municipal responsibilities." },
    source: src("Federal Elections"),
  },
  {
    id: "gov-m-021",
    topicId: "government",
    difficulty: "medium",
    prompt: {
      en: "According to the responsibility table, which provinces have their own policing listed at the provincial level?",
    },
    options: [
      { en: "Ontario and Quebec" },
      { en: "Alberta and British Columbia" },
      { en: "Manitoba and Saskatchewan" },
      { en: "Nova Scotia and New Brunswick" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The guide's table lists policing under provincial and territorial responsibilities specifically for Ontario and Quebec.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-m-022",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "Which level of government is responsible for citizenship?" },
    options: [{ en: "Provincial" }, { en: "Federal" }, { en: "Municipal" }, { en: "Territorial" }],
    answerIndex: 1,
    explanation: { en: "Citizenship is listed among the federal government's responsibilities." },
    source: src("How Canadians Govern Themselves"),
  },
];
