/**
 * Question bank chunk — part of questions.generated.ts. DO NOT EDIT BY HAND.
 */
import type { Question } from "../content";
import { src } from "./shared";

export const governmentB: Question[] = [
  {
    id: "gov-m-023",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "Who counts the ballots after the polling stations close?" },
    options: [
      { en: "The Prime Minister" },
      { en: "The candidates themselves" },
      { en: "Election officers" },
      { en: "The voters" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Immediately after the polling stations close, election officers count the ballots.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-m-024",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "What does federalism allow the provinces to do?" },
    options: [
      { en: "It requires all provinces to have identical laws" },
      {
        en: "It gives provinces flexibility to tailor policies to their populations and experiment",
      },
      { en: "It removes all provincial powers" },
      { en: "It merges the provinces into one government" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Federalism allows different provinces to adopt policies tailored to their own populations, and gives provinces the flexibility to experiment with new ideas and policies.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-m-025",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "In which city is Parliament Hill, the seat of Canada's Parliament?" },
    options: [{ en: "Ottawa" }, { en: "Toronto" }, { en: "Montreal" }, { en: "Vancouver" }],
    answerIndex: 0,
    explanation: { en: "The guide shows Parliament Hill, Ottawa, as the seat of Parliament." },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-m-026",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "According to the guide, what essential role do prisons have?" },
    options: [
      { en: "Rehabilitation only" },
      { en: "Punishing criminals and deterring crime" },
      { en: "Housing the homeless" },
      { en: "Training police officers" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The guide's caption states that prisons have an essential role in punishing criminals and deterring crime.",
    },
    source: src("The Justice System"),
  },
  {
    id: "gov-m-027",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "What does the blindfolded Lady Justice symbolize?" },
    options: [
      { en: "Speed of trials" },
      { en: "Impartial administration of laws, blind to all considerations but the facts" },
      { en: "Severity of punishment" },
      { en: "Wealth of the accused" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The blindfolded Lady Justice at the Vancouver Law Courts symbolizes the impartial manner in which laws are administered: blind to all considerations but the facts.",
    },
    source: src("The Justice System"),
  },
  {
    id: "gov-m-028",
    topicId: "government",
    difficulty: "medium",
    prompt: {
      en: "The study guide encourages every citizen to know what about their federal representation?",
    },
    options: [
      { en: "The Governor General's birthday" },
      { en: "The date of the next census" },
      { en: "The price of a postage stamp" },
      { en: "The name of your Member of Parliament (MP) in Ottawa" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The guide's 'How Much Do You Know About Your Government?' self-test asks you to fill in the name of your Member of Parliament in Ottawa.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-m-029",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "The study guide encourages you to know the name of what federal item?" },
    options: [
      { en: "Your federal electoral district" },
      { en: "Your passport number" },
      { en: "Your tax bracket" },
      { en: "Your health card number" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The guide's self-test asks you to fill in the name of your federal electoral district.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-m-030",
    topicId: "government",
    difficulty: "medium",
    prompt: {
      en: "For your provincial government, what does the study guide encourage you to know?",
    },
    options: [
      { en: "The name of the provincial party in power and the Premier" },
      { en: "The name of the federal Cabinet" },
      { en: "The names of all Senators" },
      { en: "The name of the Chief Justice" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The guide's self-test asks for the name of the provincial party in power and the name of the Premier, the head of the provincial government.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-m-031",
    topicId: "government",
    difficulty: "medium",
    prompt: {
      en: "For your territorial government, what does the study guide encourage you to know?",
    },
    options: [
      { en: "The Governor General" },
      { en: "The Chief Justice" },
      { en: "The Commissioner, who represents the federal government in the territory" },
      { en: "The mayor of Ottawa" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The guide's self-test for territorial government asks for the name of the Commissioner, who represents the federal government in the territory.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-m-032",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "Which courts handle lesser offences?" },
    options: [
      { en: "The Supreme Court of Canada" },
      { en: "The Federal Court of Canada" },
      { en: "The Senate" },
      { en: "Provincial courts" },
    ],
    answerIndex: 3,
    explanation: { en: "There are provincial courts for lesser offences." },
    source: src("The Justice System"),
  },
  {
    id: "gov-m-033",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "In most provinces, what two levels of courts exist?" },
    options: [
      { en: "An appeal court and a trial court" },
      { en: "Two supreme courts" },
      { en: "A Senate and a House" },
      { en: "A family court and a traffic court only" },
    ],
    answerIndex: 0,
    explanation: { en: "In most provinces there is an appeal court and a trial court." },
    source: src("The Justice System"),
  },
  {
    id: "gov-m-034",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "What can lawyers do for you?" },
    options: [
      { en: "Only with paying taxes" },
      { en: "Lawyers can help with legal problems and act for you in court" },
      { en: "Only with voting" },
      { en: "Only with immigration paperwork" },
    ],
    answerIndex: 1,
    explanation: { en: "Lawyers can help you with legal problems and act for you in court." },
    source: src("The Justice System"),
  },
  {
    id: "gov-m-035",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "What do the governments and assemblies of the three northern territories do?" },
    options: [
      { en: "They have no government at all" },
      { en: "They are governed directly by the Senate" },
      { en: "Their governments and assemblies carry out many of the same functions as provinces" },
      { en: "They follow American state law" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The three northern territories do not have the status of provinces, but their governments and assemblies carry out many of the same functions.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-m-036",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "Which level of government is responsible for international trade?" },
    options: [{ en: "Provincial" }, { en: "Municipal" }, { en: "Territorial" }, { en: "Federal" }],
    answerIndex: 3,
    explanation: {
      en: "International trade is listed among the federal government's responsibilities.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-m-037",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "Who is responsible for running the federal government departments?" },
    options: [
      { en: "Cabinet ministers" },
      { en: "The opposition parties" },
      { en: "The Senators" },
      { en: "The Lieutenant Governors" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Cabinet ministers are responsible for running the federal government departments.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-m-038",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "Participating in democracy is described as what for Canadian citizens?" },
    options: [
      { en: "Only a right" },
      { en: "Only a responsibility" },
      { en: "Both a right and a responsibility" },
      { en: "Neither a right nor a responsibility" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Living in a democracy, Canadian citizens have the right and the responsibility to participate in making decisions that affect them.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-m-039",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "What are elected representatives responsible for?" },
    options: [
      { en: "Enforcing laws on the street" },
      {
        en: "Passing laws, approving and monitoring expenditures, and keeping the government accountable",
      },
      { en: "Counting election ballots" },
      { en: "Granting royal assent" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Representatives in the House of Commons and provincial and territorial legislatures are responsible for passing laws, approving and monitoring expenditures, and keeping the government accountable.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-m-040",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "Which chamber of Parliament is the representative chamber?" },
    options: [
      { en: "The House of Commons" },
      { en: "The Senate" },
      { en: "The Supreme Court" },
      { en: "The Cabinet" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The House of Commons is described as the representative chamber, made up of members of Parliament elected by the people.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-m-041",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "After the Third Reading in the House of Commons, what happens next to a bill?" },
    options: [
      { en: "It becomes law immediately" },
      { en: "It follows a similar process in the Senate" },
      { en: "It goes back to the voters" },
      { en: "It is signed by the Prime Minister" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Step 6 of the legislative process: after the Third Reading in the House of Commons, the bill follows a similar process in the Senate.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-m-042",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "In accordance with what does the Sovereign reign?" },
    options: [
      { en: "By personal decree" },
      { en: "In accordance with the Constitution: the rule of law" },
      { en: "Through the Cabinet" },
      { en: "By military authority" },
    ],
    answerIndex: 1,
    explanation: {
      en: "As a constitutional monarchy, Canada's Head of State is a hereditary Sovereign who reigns in accordance with the Constitution: the rule of law.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-m-043",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "How is the Sovereign described in the study guide?" },
    options: [
      { en: "The commander of the armed forces" },
      { en: "The head of the judiciary" },
      { en: "The leader of the Senate" },
      {
        en: "A symbol of Canadian sovereignty, a guardian of constitutional freedoms, and a reflection of our history",
      },
    ],
    answerIndex: 3,
    explanation: {
      en: "Her Majesty is described as a symbol of Canadian sovereignty, a guardian of constitutional freedoms, and a reflection of our history.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-m-044",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "What is the significance of the Royal Family's example of lifelong service?" },
    options: [
      { en: "It is an encouragement for citizens to give their best to their country" },
      { en: "It is required viewing for new citizens" },
      { en: "It replaces the national anthem" },
      { en: "It decides election dates" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The Royal Family's example of lifelong service to the community is an encouragement for citizens to give their best to their country.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-m-045",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "Where are provincial and territorial laws passed?" },
    options: [
      { en: "In the House of Commons in Ottawa" },
      { en: "In each province and territory's elected legislature" },
      { en: "In the Senate" },
      { en: "In municipal councils" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Each provincial and territorial government has an elected legislature where provincial and territorial laws are passed.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-m-046",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "Which level of government is responsible for urban or regional planning?" },
    options: [{ en: "Federal" }, { en: "Provincial" }, { en: "Municipal" }, { en: "Territorial" }],
    answerIndex: 2,
    explanation: { en: "Municipalities are normally responsible for urban or regional planning." },
    source: src("Federal Elections"),
  },
  {
    id: "gov-m-047",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "Which level of government is responsible for streets and roads?" },
    options: [{ en: "Federal" }, { en: "Provincial" }, { en: "Territorial" }, { en: "Municipal" }],
    answerIndex: 3,
    explanation: { en: "Municipalities are normally responsible for streets and roads." },
    source: src("Federal Elections"),
  },
  {
    id: "gov-m-048",
    topicId: "government",
    difficulty: "medium",
    prompt: {
      en: "Which level of government is responsible for sanitation, such as garbage removal?",
    },
    options: [
      { en: "Municipal governments" },
      { en: "The federal government" },
      { en: "Provincial governments" },
      { en: "The RCMP" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Municipalities are normally responsible for sanitation, such as garbage removal.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-m-049",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "Which level of government is responsible for public transit?" },
    options: [{ en: "Federal" }, { en: "Municipal" }, { en: "Provincial" }, { en: "Territorial" }],
    answerIndex: 1,
    explanation: { en: "Municipalities are normally responsible for public transit." },
    source: src("Federal Elections"),
  },
  {
    id: "gov-m-050",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "Which level of government is responsible for recreation facilities?" },
    options: [
      { en: "Provincial" },
      { en: "Federal" },
      { en: "Municipal" },
      { en: "The Governor General" },
    ],
    answerIndex: 2,
    explanation: { en: "Municipalities are normally responsible for recreation facilities." },
    source: src("Federal Elections"),
  },
  {
    id: "gov-m-051",
    topicId: "government",
    difficulty: "medium",
    prompt: {
      en: "Besides when and where you vote, what else does the voter information card list?",
    },
    options: [
      { en: "The names of the candidates" },
      { en: "The election results" },
      { en: "The date of the next census" },
      { en: "The number to call if you require an interpreter or other special services" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The voter information card lists the number to call if you require an interpreter or other special services.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-m-052",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "Where do you find the location of your polling station?" },
    options: [
      { en: "Your voter information card" },
      { en: "The local newspaper" },
      { en: "Your tax return" },
      { en: "The phone book" },
    ],
    answerIndex: 0,
    explanation: {
      en: "To vote either on election day or at advance polls, go to the polling station listed on your voter information card.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-m-053",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "Who has the right to insist that you tell them how you voted?" },
    options: [
      { en: "Your employer" },
      { en: "Your union representative" },
      { en: "Your family members" },
      { en: "No one — not family, employer or union representative" },
    ],
    answerIndex: 1,
    explanation: {
      en: "No one, including family members, your employer or union representative, has the right to insist that you tell them how you voted.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-m-054",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "Where does the RCMP serve as the provincial police?" },
    options: [
      { en: "Only in Ontario and Quebec" },
      { en: "Only in the territories" },
      {
        en: "In all provinces and territories except Ontario and Quebec, and in some municipalities",
      },
      { en: "Only in municipalities" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The RCMP serves as the provincial police in all provinces and territories except Ontario and Quebec, as well as in some municipalities.",
    },
    source: src("The Justice System"),
  },
  {
    id: "gov-m-055",
    topicId: "government",
    difficulty: "medium",
    prompt: {
      en: "Who is a voice for First Nations, Métis and Inuit people in their relationships with governments?",
    },
    options: [
      { en: "Federal Cabinet ministers" },
      { en: "Provincial Premiers" },
      { en: "Municipal mayors" },
      { en: "Provincial, regional and national Aboriginal organizations" },
    ],
    answerIndex: 3,
    explanation: {
      en: "There are a number of provincial, regional and national Aboriginal organizations that are a voice for First Nations, Métis and Inuit people in their relationships with the federal, provincial and territorial governments.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-m-056",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "What is true of municipal by-laws?" },
    options: [
      { en: "They affect only the local community" },
      { en: "They apply across the whole province" },
      { en: "They override federal law" },
      { en: "They apply across Canada" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Municipal governments usually have a council that passes laws called 'by-laws' that affect only the local community.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-m-057",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "In each electoral district, what do the people vote for?" },
    options: [
      { en: "Only for a political party, not a person" },
      { en: "For the candidate and political party of their choice" },
      { en: "Only for the sitting MP" },
      { en: "Only for independent candidates" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The people in each electoral district vote for the candidate and political party of their choice.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-m-058",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "How many candidates can there be in an electoral district?" },
    options: [{ en: "Only one" }, { en: "Only two" }, { en: "Many" }, { en: "Exactly three" }],
    answerIndex: 2,
    explanation: {
      en: "The guide states that there can be many candidates in an electoral district.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-m-059",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "What does receiving a voter information card confirm?" },
    options: [
      { en: "Your citizenship certificate" },
      { en: "Your party membership" },
      { en: "Your tax assessment" },
      { en: "That your name is on the voters' list" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The voter information card confirms that your name is on the voters' list and states when and where you vote.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-m-060",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "What is the effect of the interplay between the three branches of government?" },
    options: [
      { en: "It helps to secure the rights and freedoms of Canadians" },
      { en: "It lets the Prime Minister rule alone" },
      { en: "It removes the courts from government" },
      { en: "It merges the provinces into the federal government" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The interplay between the three branches of government — the Executive, Legislative and Judicial — which work together but also sometimes in creative tension, helps to secure the rights and freedoms of Canadians.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-m-061",
    topicId: "government",
    difficulty: "medium",
    prompt: {
      en: "Why does the guide say it is important to find out the voting rules for provincial, territorial and local elections?",
    },
    options: [
      { en: "Because federal election rules apply automatically at all levels" },
      {
        en: "Because their rules differ from federal rules and you need to know them to exercise your right to vote",
      },
      { en: "Because Elections Canada mails you the provincial rules" },
      { en: "Because voting is mandatory in provincial elections" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The guide says provincial, territorial and municipal elections use a secret ballot but their rules differ from federal rules, so it is important to find out the rules to exercise your right to vote.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-m-062",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "Which of these is part of the Canadian court system?" },
    options: [
      { en: "The House of Commons" },
      { en: "The Governor General's office" },
      { en: "Traffic courts" },
      { en: "The RCMP headquarters" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The guide lists traffic courts among the courts in the Canadian justice system.",
    },
    source: src("The Justice System"),
  },
  {
    id: "gov-m-063",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "In which situations can you ask the police for help?" },
    options: [
      { en: "Only if you are a victim of assault" },
      { en: "Only after a trial" },
      { en: "Only for traffic tickets" },
      {
        en: "If there's been an accident, a theft, an assault, a crime taking place, or someone has gone missing",
      },
    ],
    answerIndex: 3,
    explanation: {
      en: "You can ask the police for help if there's been an accident, if someone has stolen something from you, if you are a victim of assault, if you see a crime taking place or if someone you know has gone missing.",
    },
    source: src("The Justice System"),
  },
  {
    id: "gov-m-064",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "What does it mean that Canada is a federal state?" },
    options: [
      {
        en: "The federal government takes responsibility for matters of national and international concern",
      },
      { en: "Each province handles foreign policy" },
      { en: "Municipalities handle national defence" },
      { en: "The territories handle currency" },
    ],
    answerIndex: 0,
    explanation: {
      en: "In our federal state, the federal government takes responsibility for matters of national and international concern.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-m-065",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "Which chambers consider and review bills?" },
    options: [
      { en: "Only the House of Commons" },
      { en: "Both the House of Commons and the Senate" },
      { en: "Only the Senate" },
      { en: "Only the Cabinet" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Both the House of Commons and the Senate consider and review bills (proposals for new laws).",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-m-066",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "Who is responsible for the operations and policy of the federal government?" },
    options: [
      { en: "The Governor General" },
      { en: "The Speaker" },
      { en: "The Prime Minister" },
      { en: "The Chief Justice" },
    ],
    answerIndex: 2,
    explanation: {
      en: "In the federal government, the Prime Minister selects the Cabinet ministers and is responsible for the operations and policy of the government.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-m-067",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "What is the minimum age to run as a candidate in a federal election?" },
    options: [{ en: "21" }, { en: "25" }, { en: "30" }, { en: "18" }],
    answerIndex: 3,
    explanation: {
      en: "Canadian citizens who are 18 years old or older may run in a federal election.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-m-068",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "How are police forces organized across the provinces?" },
    options: [
      {
        en: "There are provincial police forces in Ontario and Quebec, and municipal police departments in all provinces",
      },
      { en: "The RCMP is the only police in Canada" },
      { en: "There are no municipal police forces" },
      { en: "Only the federal government has police" },
    ],
    answerIndex: 0,
    explanation: {
      en: "There are provincial police forces in Ontario and Quebec and municipal police departments in all provinces.",
    },
    source: src("The Justice System"),
  },
  {
    id: "gov-m-069",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "What are Canada's laws intended to do?" },
    options: [
      { en: "To punish citizens" },
      {
        en: "To provide order, a peaceful way to settle disputes, and to express Canadians' values and beliefs",
      },
      { en: "To raise taxes" },
      { en: "To control the media" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Our laws are intended to provide order in society and a peaceful way to settle disputes, and to express the values and beliefs of Canadians.",
    },
    source: src("The Justice System"),
  },
  {
    id: "gov-m-070",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "Who settles disputes under Canada's system of laws?" },
    options: [
      { en: "The police" },
      { en: "The lawyers" },
      { en: "The courts" },
      { en: "The journalists" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Canada's laws are made by elected representatives; the courts settle disputes and the police enforce the laws.",
    },
    source: src("The Justice System"),
  },
  {
    id: "gov-m-071",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "When does Elections Canada mail the voter information card?" },
    options: [
      { en: "One year before the election" },
      { en: "Once an election has been called" },
      { en: "Only on election day" },
      { en: "After the results are announced" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Once an election has been called, Elections Canada mails a voter information card to each elector whose name is in the National Register of Electors.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-m-072",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "Canada's legal system is based on a heritage that includes what?" },
    options: [
      { en: "The rule of law, freedom under the law, democratic principles and due process" },
      { en: "The divine right of kings" },
      { en: "Military tribunals" },
      { en: "Rule by the majority party alone" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Canada's legal system is based on a heritage that includes the rule of law, freedom under the law, democratic principles and due process.",
    },
    source: src("The Justice System"),
  },
  {
    id: "gov-m-073",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "What are Canada's laws?" },
    options: [
      { en: "Unwritten traditions" },
      { en: "The written rules intended to guide people in our society" },
      { en: "Orders from the Governor General" },
      { en: "Decisions of the police" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Canada is governed by an organized system of laws, which are the written rules intended to guide people in our society.",
    },
    source: src("The Justice System"),
  },
  {
    id: "gov-m-074",
    topicId: "government",
    difficulty: "medium",
    prompt: {
      en: "The Lieutenant Governor's role in a province is similar to whose role federally?",
    },
    options: [
      { en: "The Prime Minister" },
      { en: "The Governor General" },
      { en: "The Speaker" },
      { en: "The Chief Justice" },
    ],
    answerIndex: 1,
    explanation: {
      en: "In each province, the Premier has a role similar to that of the Prime Minister in the federal government, just as the Lieutenant Governor has a role similar to that of the Governor General.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-m-075",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "What are the parties that are not in power called?" },
    options: [
      { en: "Backbenchers" },
      { en: "Independents" },
      { en: "Senators" },
      { en: "Opposition parties" },
    ],
    answerIndex: 3,
    explanation: { en: "The other parties that are not in power are known as opposition parties." },
    source: src("Federal Elections"),
  },
  {
    id: "gov-m-076",
    topicId: "government",
    difficulty: "medium",
    prompt: {
      en: "When is the Sovereign's role as the focus of citizenship and allegiance most visible?",
    },
    options: [
      { en: "During royal visits to Canada" },
      { en: "During elections" },
      { en: "During Cabinet meetings" },
      { en: "During court trials" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The Sovereign plays a non-partisan role as the focus of citizenship and allegiance, most visibly during royal visits to Canada.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-m-077",
    topicId: "government",
    difficulty: "medium",
    prompt: { en: "What happens if a majority of MPs vote against a major government decision?" },
    options: [
      { en: "The Senate takes over" },
      { en: "The Governor General resigns" },
      { en: "A new election is held the next day automatically" },
      { en: "The party in power is defeated" },
    ],
    answerIndex: 3,
    explanation: {
      en: "If a majority of the members of the House of Commons vote against a major government decision, the party in power is defeated.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-h-001",
    topicId: "government",
    difficulty: "hard",
    prompt: { en: "The Governor General grants royal assent on behalf of whom?" },
    options: [
      { en: "The Sovereign (Queen or King)" },
      { en: "The Prime Minister" },
      { en: "The Senate" },
      { en: "The Chief Justice" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Royal assent is granted by the Governor General on behalf of the Sovereign.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-h-002",
    topicId: "government",
    difficulty: "hard",
    prompt: {
      en: "Which statement best describes the difference between the Sovereign and the Governor General?",
    },
    options: [
      { en: "The Governor General outranks the Sovereign" },
      {
        en: "The Sovereign is the Head of State and the Governor General represents the Sovereign in Canada",
      },
      { en: "Both are elected by Parliament" },
      {
        en: "The Governor General directs the government while the Sovereign is ceremonial only in Britain",
      },
    ],
    answerIndex: 1,
    explanation: {
      en: "The Sovereign is Canada's Head of State; the Governor General represents the Sovereign in Canada.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-h-003",
    topicId: "government",
    difficulty: "hard",
    prompt: { en: "How does the way Senators get their seats differ from the way MPs get theirs?" },
    options: [
      { en: "Both are elected every four years" },
      { en: "Both are appointed by the Governor General" },
      {
        en: "Senators are appointed by the Governor General on the Prime Minister's advice while MPs are elected by voters in electoral districts",
      },
      { en: "Senators are elected by provinces while MPs are appointed" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Senators are appointed by the Governor General on the advice of the Prime Minister and serve until age 75, while MPs are elected by voters in each electoral district.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-h-004",
    topicId: "government",
    difficulty: "hard",
    prompt: { en: "How do the terms of Senators and the Governor General compare?" },
    options: [
      { en: "Both serve for life" },
      { en: "Both serve five-year terms" },
      { en: "The Governor General serves until 75 and Senators serve five years" },
      {
        en: "Senators serve until age 75 while the Governor General usually serves for five years",
      },
    ],
    answerIndex: 3,
    explanation: {
      en: "Senators serve until age 75, while the Governor General is usually appointed for five years.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-h-005",
    topicId: "government",
    difficulty: "hard",
    prompt: {
      en: "How do the roles of a Lieutenant Governor and a territorial Commissioner differ?",
    },
    options: [
      {
        en: "The Lieutenant Governor represents the Sovereign in a province; the Commissioner represents the federal government in a territory",
      },
      { en: "Both represent the Sovereign" },
      { en: "The Commissioner outranks the Lieutenant Governor" },
      { en: "Both are elected officials" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The Lieutenant Governor represents the Sovereign in each province, while in the territories the Commissioner represents the federal government in a ceremonial role.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-h-006",
    topicId: "government",
    difficulty: "hard",
    prompt: {
      en: "What usually happens after the governing party loses a vote on a major issue such as the budget?",
    },
    options: [
      { en: "The Senate immediately forms a new government" },
      { en: "The defeated party stays in power regardless" },
      {
        en: "The party in power is defeated and the Prime Minister usually asks the Governor General, on behalf of the Sovereign, to call an election",
      },
      { en: "The Governor General becomes Prime Minister" },
    ],
    answerIndex: 1,
    explanation: {
      en: "If defeated on a major vote, the party in power is defeated, which usually results in the Prime Minister asking the Governor General, on behalf of the Sovereign, to call an election.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-h-007",
    topicId: "government",
    difficulty: "hard",
    prompt: { en: "Why is a vote on the budget considered a matter of confidence?" },
    options: [
      { en: "Because the Senate demands it" },
      { en: "Because the budget is prepared by the Governor General" },
      {
        en: "Because the government can continue only with the support or confidence of the majority of MPs",
      },
      { en: "Because elections are held every year" },
    ],
    answerIndex: 2,
    explanation: {
      en: "A vote on the budget is a matter of confidence because the Prime Minister and the party in power run the government only as long as they have the support or confidence of the majority of the MPs.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-h-008",
    topicId: "government",
    difficulty: "hard",
    prompt: { en: "Which of the following is NOT required for a bill to become law in Canada?" },
    options: [
      { en: "Passage by the House of Commons" },
      { en: "Passage by the Senate" },
      { en: "Royal assent" },
      { en: "Approval by all provincial legislatures" },
    ],
    answerIndex: 3,
    explanation: {
      en: "No bill can become law until it has been passed by both chambers and received royal assent; approval by provincial legislatures is not required.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-h-009",
    topicId: "government",
    difficulty: "hard",
    prompt: { en: "A bill has passed the House of Commons. Why must it still go to the Senate?" },
    options: [
      {
        en: "No bill can become law until it has been passed by both the House of Commons and the Senate",
      },
      { en: "The Senate only handles provincial matters" },
      { en: "Senate approval is optional" },
      { en: "The House of Commons can override the Senate at will" },
    ],
    answerIndex: 0,
    explanation: {
      en: "No bill can become law in Canada until it has been passed by both chambers and has received royal assent.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-h-010",
    topicId: "government",
    difficulty: "hard",
    prompt: { en: "Which pairing of responsibilities is correct?" },
    options: [
      { en: "Criminal law is shared; immigration is exclusively federal" },
      {
        en: "Immigration is shared between federal and provincial governments; criminal law is exclusively federal",
      },
      { en: "Both are exclusively provincial" },
      { en: "Both are exclusively municipal" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Immigration is a shared federal-provincial responsibility, while criminal law is an exclusively federal responsibility.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-h-011",
    topicId: "government",
    difficulty: "hard",
    prompt: { en: "The environment is a shared responsibility of which two levels of government?" },
    options: [
      { en: "Federal and municipal" },
      { en: "Provincial and territorial" },
      { en: "Federal and provincial" },
      { en: "Municipal and territorial" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The guide's responsibility table lists environment as shared between the federal and provincial governments.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-h-012",
    topicId: "government",
    difficulty: "hard",
    prompt: { en: "Which statement about policing in Canada is correct?" },
    options: [
      { en: "The RCMP only polices the territories" },
      { en: "Ontario and Quebec are policed by the RCMP" },
      { en: "Municipal police enforce federal law" },
      {
        en: "The RCMP enforces federal laws throughout Canada and serves as provincial police everywhere except Ontario and Quebec, which have their own provincial forces",
      },
    ],
    answerIndex: 3,
    explanation: {
      en: "The RCMP enforces federal laws throughout Canada and serves as the provincial police in all provinces and territories except Ontario and Quebec, which have their own provincial police forces.",
    },
    source: src("The Justice System"),
  },
  {
    id: "gov-h-013",
    topicId: "government",
    difficulty: "hard",
    prompt: {
      en: "A city wants a new rule about garbage collection. Which level of government handles this, and how?",
    },
    options: [
      { en: "The municipal government, through a by-law" },
      { en: "The federal government, through criminal law" },
      { en: "The provincial government, through education policy" },
      { en: "The Senate, through a resolution" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Municipalities are normally responsible for sanitation, such as garbage removal, and pass by-laws affecting only the local community.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-h-014",
    topicId: "government",
    difficulty: "hard",
    prompt: { en: "Which pairing is correct for highways and currency?" },
    options: [
      { en: "Both are federal" },
      { en: "Both are provincial" },
      { en: "Highways are provincial and currency is federal" },
      { en: "Highways are federal and currency is provincial" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Highways are a provincial responsibility, while currency is a federal responsibility.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-h-015",
    topicId: "government",
    difficulty: "hard",
    prompt: { en: "The 1867 Act defined the responsibilities of which two levels of government?" },
    options: [
      { en: "Federal and municipal" },
      { en: "Provincial and municipal" },
      { en: "Federal and provincial" },
      { en: "Territorial and municipal" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The responsibilities of the federal and provincial governments were defined in 1867 in the British North America Act, now known as the Constitution Act, 1867.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-h-016",
    topicId: "government",
    difficulty: "hard",
    prompt: { en: "Why can different provinces adopt different policies?" },
    options: [
      { en: "Because the federal government orders it" },
      { en: "Because Senators require it" },
      { en: "Because all provinces must copy Ontario" },
      {
        en: "Because federalism gives provinces the flexibility to tailor policies to their populations and experiment with new ideas",
      },
    ],
    answerIndex: 3,
    explanation: {
      en: "Federalism allows different provinces to adopt policies tailored to their own populations, and gives provinces the flexibility to experiment with new ideas and policies.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-h-017",
    topicId: "government",
    difficulty: "hard",
    prompt: { en: "Who makes the laws, who settles disputes, and who enforces the laws?" },
    options: [
      {
        en: "Elected representatives make the laws, the courts settle disputes, and the police enforce the laws",
      },
      { en: "The police make the laws and the courts enforce them" },
      { en: "The Governor General makes the laws and the RCMP settles disputes" },
      { en: "Judges make the laws and politicians enforce them" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Canada's laws are made by elected representatives; the courts settle disputes and the police enforce the laws.",
    },
    source: src("The Justice System"),
  },
  {
    id: "gov-h-018",
    topicId: "government",
    difficulty: "hard",
    prompt: {
      en: "A dispute involving the federal government versus a lesser offence: which courts handle each?",
    },
    options: [
      { en: "Both go to the Supreme Court of Canada" },
      {
        en: "A federal-government matter goes to the Federal Court; a lesser offence goes to a provincial court",
      },
      { en: "Both go to small claims court" },
      { en: "A federal-government matter goes to a provincial court" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The Federal Court of Canada deals with matters concerning the federal government, while there are provincial courts for lesser offences.",
    },
    source: src("The Justice System"),
  },
  {
    id: "gov-h-019",
    topicId: "government",
    difficulty: "hard",
    prompt: { en: "Which legal principle means 'innocent until proven guilty'?" },
    options: [
      { en: "Due process" },
      { en: "The rule of law" },
      { en: "The presumption of innocence" },
      { en: "Parliamentary privilege" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The presumption of innocence means everyone is innocent until proven guilty; due process is the principle that the government must respect all of a person's legal rights under the law.",
    },
    source: src("The Justice System"),
  },
  {
    id: "gov-h-020",
    topicId: "government",
    difficulty: "hard",
    prompt: {
      en: "Who selects the Cabinet, and who invites the winning party's leader to form the government?",
    },
    options: [
      {
        en: "The Governor General selects the Cabinet and the Prime Minister invites the party leader",
      },
      { en: "The Senate does both" },
      { en: "The voters do both directly" },
      {
        en: "The Prime Minister selects the Cabinet ministers and the Governor General invites the party leader to form the government",
      },
    ],
    answerIndex: 3,
    explanation: {
      en: "The Prime Minister selects the Cabinet ministers, while the Governor General invites the leader of the party with the most seats to form the government.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-h-021",
    topicId: "government",
    difficulty: "hard",
    prompt: { en: "Which two facts about the Sovereign are both true?" },
    options: [
      {
        en: "The Sovereign is both Head of State and a part of Parliament with a non-partisan role",
      },
      { en: "The Sovereign is elected every four years" },
      { en: "The Sovereign runs the federal departments" },
      { en: "The Sovereign leads the Official Opposition" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The Sovereign is Canada's Head of State and is also a part of Parliament, playing an important, non-partisan role as the focus of citizenship and allegiance.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-h-022",
    topicId: "government",
    difficulty: "hard",
    prompt: {
      en: "Which of these countries is NOT listed in the guide as a constitutional monarchy?",
    },
    options: [{ en: "Australia" }, { en: "Japan" }, { en: "France" }, { en: "Norway" }],
    answerIndex: 1,
    explanation: {
      en: "The guide lists Australia, Japan and Norway among the constitutional monarchies; France is a republic and is not on the list.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-h-023",
    topicId: "government",
    difficulty: "hard",
    prompt: { en: "Which statement about the three northern territories is correct?" },
    options: [
      { en: "They have no government at all" },
      { en: "They are provinces in all but name" },
      {
        en: "Their governments carry out many of the same functions as provinces, and the Commissioner ceremonially represents the federal government",
      },
      { en: "They are governed by the Senate" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The three northern territories have small populations and no province status, but their governments carry out many of the same functions; the Commissioner represents the federal government in a ceremonial role.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-h-024",
    topicId: "government",
    difficulty: "hard",
    prompt: { en: "What is the correct order of the steps for a bill to become law?" },
    options: [
      { en: "First Reading, Committee Stage, Second Reading, Royal Assent, Senate" },
      { en: "Second Reading, First Reading, Third Reading, Senate, Royal Assent" },
      { en: "First Reading, Second Reading, Royal Assent, Committee Stage, Senate" },
      {
        en: "First Reading, Second Reading, Committee Stage, Report Stage, Third Reading, Senate, Royal Assent",
      },
    ],
    answerIndex: 3,
    explanation: {
      en: "The legislative process runs: First Reading, Second Reading, Committee Stage, Report Stage, Third Reading, then a similar process in the Senate, then Royal Assent.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-h-025",
    topicId: "government",
    difficulty: "hard",
    prompt: { en: "What is the difference between the Committee Stage and the Report Stage?" },
    options: [
      {
        en: "At the Committee Stage members study the bill clause by clause, while at the Report Stage members can make other amendments",
      },
      { en: "Both stages are votes on the whole bill" },
      { en: "The Committee Stage comes after Royal Assent" },
      { en: "The Report Stage is conducted by the Senate only" },
    ],
    answerIndex: 0,
    explanation: {
      en: "At the Committee Stage, committee members study the bill clause by clause; at the Report Stage, members can make other amendments.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-h-026",
    topicId: "government",
    difficulty: "hard",
    prompt: { en: "How can voting be secret while election results are public?" },
    options: [
      { en: "Individual votes are published with names" },
      { en: "How you voted is secret, but the counted results are announced publicly" },
      { en: "Only the winning party sees the results" },
      { en: "Ballots are never counted" },
    ],
    answerIndex: 1,
    explanation: {
      en: "No one can watch you vote and no one should look at how you voted, yet immediately after the polling stations close, election officers count the ballots and the results are announced on radio, television and in the newspapers.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-h-027",
    topicId: "government",
    difficulty: "hard",
    prompt: { en: "Which statement about opposition parties is true?" },
    options: [
      { en: "All opposition parties are called the Official Opposition" },
      { en: "The Official Opposition is chosen by the Senate" },
      {
        en: "The parties not in power are opposition parties, and the one with the most MPs is the Official Opposition",
      },
      { en: "Opposition parties run the federal departments" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The parties not in power are known as opposition parties, and the opposition party with the most members of the House of Commons is the Official Opposition.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-h-028",
    topicId: "government",
    difficulty: "hard",
    prompt: { en: "Which statement correctly contrasts the Sovereign and the Prime Minister?" },
    options: [
      { en: "The Sovereign directs the government and the Prime Minister reigns" },
      { en: "Both are elected officials" },
      { en: "The Sovereign appoints the Cabinet" },
      {
        en: "The Sovereign reigns in accordance with the Constitution while the Prime Minister actually directs the governing of the country",
      },
    ],
    answerIndex: 3,
    explanation: {
      en: "The Sovereign reigns in accordance with the Constitution (the rule of law), while the Prime Minister, as head of government, actually directs the governing of the country.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-h-029",
    topicId: "government",
    difficulty: "hard",
    prompt: { en: "Which description matches 'parliamentary democracy' in Canada?" },
    options: [
      {
        en: "The people elect members to the House of Commons and to the provincial and territorial legislatures",
      },
      { en: "The Sovereign appoints all representatives" },
      { en: "The Governor General elects the Cabinet" },
      { en: "The Senate elects the Prime Minister" },
    ],
    answerIndex: 0,
    explanation: {
      en: "In Canada's parliamentary democracy, the people elect members to the House of Commons in Ottawa and to the provincial and territorial legislatures.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-h-030",
    topicId: "government",
    difficulty: "hard",
    prompt: { en: "How do elected representatives keep the government accountable?" },
    options: [
      { en: "By appointing the judges" },
      { en: "By approving royal visits" },
      { en: "By requiring Cabinet ministers to retain the confidence of the House" },
      { en: "By counting the ballots" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Representatives keep the government accountable partly because Cabinet ministers are responsible to the elected representatives: they must retain the confidence of the House and resign if defeated in a non-confidence vote.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-h-031",
    topicId: "government",
    difficulty: "hard",
    prompt: {
      en: "A party wins 160 of the 308 seats in the House of Commons. What kind of government is this?",
    },
    options: [
      { en: "A minority government" },
      { en: "A coalition government" },
      { en: "A majority government" },
      { en: "A hung parliament with no government" },
    ],
    answerIndex: 2,
    explanation: {
      en: "A majority government holds at least half of the seats; half of 308 is 154, so 160 seats is a majority.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-h-032",
    topicId: "government",
    difficulty: "hard",
    prompt: {
      en: "A party wins 120 of the 308 seats in the House of Commons. What kind of government is this?",
    },
    options: [
      { en: "A majority government" },
      { en: "A unanimous government" },
      { en: "A Senate government" },
      { en: "A minority government" },
    ],
    answerIndex: 3,
    explanation: {
      en: "A minority government holds less than half of the seats; 120 of 308 is less than half.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-h-033",
    topicId: "government",
    difficulty: "hard",
    prompt: { en: "Why must a minority government maintain support beyond its own MPs?" },
    options: [
      {
        en: "It must keep the support or confidence of the majority of MPs even though it holds less than half the seats",
      },
      { en: "It can ignore the other parties completely" },
      { en: "It must call an election every year" },
      { en: "It is led by the Governor General" },
    ],
    answerIndex: 0,
    explanation: {
      en: "In a minority government the party in power holds less than half the seats, yet it runs the government as long as it has the support or confidence of the majority of the MPs.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-h-034",
    topicId: "government",
    difficulty: "hard",
    prompt: { en: "Which person is eligible to vote in a federal election?" },
    options: [
      { en: "A 17-year-old Canadian citizen on the voters' list" },
      { en: "A 19-year-old Canadian citizen on the voters' list" },
      { en: "A 30-year-old permanent resident on the voters' list" },
      { en: "A 25-year-old citizen not on any voters' list" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Eligibility requires all three: a Canadian citizen, at least 18 years old on voting day, and on the voters' list.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-h-035",
    topicId: "government",
    difficulty: "hard",
    prompt: {
      en: "In a riding, three candidates receive 35%, 33% and 32% of the votes. Who becomes the MP?",
    },
    options: [
      { en: "The candidate with 33%" },
      { en: "The candidate with 32%" },
      { en: "The candidate with 35%" },
      { en: "None — a runoff is required" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The candidate who receives the most votes becomes the MP for that electoral district — even without a majority of all votes cast.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-h-036",
    topicId: "government",
    difficulty: "hard",
    prompt: { en: "How many MPs sit in the House of Commons?" },
    options: [{ en: "150" }, { en: "200" }, { en: "250" }, { en: "308" }],
    answerIndex: 3,
    explanation: {
      en: "Canada is divided into 308 electoral districts and the citizens in each district elect one MP, so 308 MPs sit in the House of Commons. (Note: the study guide gives 308; after the 2021 redistribution, Canada now has 343 federal electoral districts.)",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-h-037",
    topicId: "government",
    difficulty: "hard",
    prompt: { en: "A Senator is 74 years old. About how much longer can they serve?" },
    options: [
      { en: "About one more year, until age 75" },
      { en: "Four more years, like an MP's term" },
      { en: "Ten more years" },
      { en: "For life" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Senators are appointed and serve until age 75, so a 74-year-old Senator may serve about one more year.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-h-038",
    topicId: "government",
    difficulty: "hard",
    prompt: { en: "How does a provincial legislature's composition differ from Parliament's?" },
    options: [
      { en: "They are identical in structure" },
      { en: "Provincial legislatures have a Senate too" },
      {
        en: "Parliament has the Sovereign, Senate and House of Commons, while a provincial legislature has the Lieutenant Governor and the elected Assembly",
      },
      { en: "Provinces have no legislatures" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Parliament has three parts — the Sovereign, the Senate and the House of Commons — while provincial legislatures comprise the Lieutenant Governor and the elected Assembly, with no Senate equivalent.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-h-039",
    topicId: "government",
    difficulty: "hard",
    prompt: { en: "How are Indigenous-related responsibilities divided?" },
    options: [
      { en: "Band chiefs handle foreign policy" },
      { en: "Aboriginal organizations run the reserves" },
      {
        en: "Band chiefs and councillors handle housing, schools and services on reserves, while Aboriginal organizations speak for Indigenous peoples with governments",
      },
      { en: "The federal government handles all reserve services directly" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Band chiefs and councillors have major responsibilities on reserves including housing, schools and other services, while Aboriginal organizations are a voice for First Nations, Métis and Inuit people with governments.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-h-040",
    topicId: "government",
    difficulty: "hard",
    prompt: { en: "Who makes Canada's laws?" },
    options: [
      { en: "The police" },
      { en: "The courts" },
      { en: "The Governor General" },
      { en: "Elected representatives" },
    ],
    answerIndex: 3,
    explanation: { en: "Canada's laws are made by elected representatives." },
    source: src("The Justice System"),
  },
  {
    id: "gov-h-041",
    topicId: "government",
    difficulty: "hard",
    prompt: { en: "What happens if a police officer breaks the law?" },
    options: [
      { en: "The law applies to them too, since it applies to everyone including the police" },
      { en: "Police are exempt from the law" },
      { en: "Only judges can charge them" },
      { en: "The law does not apply on duty" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The law in Canada applies to everyone, including judges, politicians and the police.",
    },
    source: src("The Justice System"),
  },
  {
    id: "gov-h-042",
    topicId: "government",
    difficulty: "hard",
    prompt: { en: "In most provinces, in which courts is a case heard first and second?" },
    options: [
      { en: "The Supreme Court of Canada first" },
      { en: "The trial court first, then the appeal court" },
      { en: "The appeal court first, then the trial court" },
      { en: "The Senate first" },
    ],
    answerIndex: 1,
    explanation: {
      en: "In most provinces there is an appeal court and a trial court; a case is first heard in the trial court and can then go to the appeal court.",
    },
    source: src("The Justice System"),
  },
  {
    id: "gov-h-043",
    topicId: "government",
    difficulty: "hard",
    prompt: { en: "A minor offence versus a small civil claim: which courts handle each?" },
    options: [
      { en: "Both go to the Supreme Court of Canada" },
      { en: "A lesser offence goes to small claims court" },
      {
        en: "A lesser offence goes to a provincial court and a small civil claim goes to a small claims court",
      },
      { en: "Both go to the Federal Court" },
    ],
    answerIndex: 2,
    explanation: {
      en: "There are provincial courts for lesser offences, and small claims courts for civil cases involving small sums of money.",
    },
    source: src("The Justice System"),
  },
  {
    id: "gov-h-044",
    topicId: "government",
    difficulty: "hard",
    prompt: {
      en: "How do health responsibilities differ between the provincial and municipal levels?",
    },
    options: [
      { en: "Both are federal" },
      { en: "Both are municipal" },
      { en: "Health care is municipal and social health is provincial" },
      { en: "Health care is provincial and social and community health is municipal" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The provinces are responsible for health care, while municipalities are responsible for social and community health.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-h-045",
    topicId: "government",
    difficulty: "hard",
    prompt: { en: "Which statement correctly divides these responsibilities?" },
    options: [
      {
        en: "Aboriginal Affairs is federal, while band chiefs and councillors handle housing, schools and services on reserves",
      },
      { en: "Both are municipal responsibilities" },
      { en: "Band chiefs handle foreign policy" },
      { en: "Aboriginal Affairs is provincial" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Aboriginal Affairs is a federal responsibility, while First Nations band chiefs and councillors handle housing, schools and other services on reserves.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-h-046",
    topicId: "government",
    difficulty: "hard",
    prompt: { en: "Which three areas are shared between the federal and provincial governments?" },
    options: [
      { en: "Defence, currency and navigation" },
      { en: "Agriculture, immigration and environment" },
      { en: "Criminal law, citizenship and foreign policy" },
      { en: "Education, health and highways" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The federal government and the provinces share jurisdiction over agriculture and immigration, and the responsibility table also lists environment as shared.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-h-047",
    topicId: "government",
    difficulty: "hard",
    prompt: { en: "Criminal law is federal — but where are lesser offences heard?" },
    options: [
      { en: "Criminal law is provincial" },
      { en: "Lesser offences are heard in the Supreme Court of Canada" },
      { en: "Criminal law is federal, but lesser offences are heard in provincial courts" },
      { en: "All criminal cases go to the Federal Court" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Criminal law is a federal responsibility, but lesser offences are heard in provincial courts.",
    },
    source: src("The Justice System"),
  },
  {
    id: "gov-h-048",
    topicId: "government",
    difficulty: "hard",
    prompt: {
      en: "Who represents the Sovereign in Canada as a whole, and who represents the Sovereign in each province?",
    },
    options: [
      { en: "The Prime Minister in both cases" },
      {
        en: "The Governor General in Canada as a whole, and the Lieutenant Governor in each province",
      },
      { en: "The Lieutenant Governor in both cases" },
      { en: "The Commissioner in both cases" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The Sovereign is represented in Canada by the Governor General, and in each of the ten provinces by the Lieutenant Governor.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-h-049",
    topicId: "government",
    difficulty: "hard",
    prompt: {
      en: "A bill has passed both the House of Commons and the Senate but has not received royal assent. Is it law?",
    },
    options: [
      { en: "No — it is not law without royal assent" },
      { en: "Yes — passage by both chambers is enough" },
      { en: "Yes — if the Prime Minister approves" },
      { en: "Yes — after 30 days automatically" },
    ],
    answerIndex: 0,
    explanation: {
      en: "No bill can become law until it has been passed by both chambers and has received royal assent.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-h-050",
    topicId: "government",
    difficulty: "hard",
    prompt: { en: "Can voters remove a Senator in a general election?" },
    options: [
      { en: "Yes, every four years" },
      { en: "Yes, through a referendum" },
      { en: "No — Senators are appointed, not elected" },
      { en: "Yes, the Prime Minister can be voted out instead" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Senators are appointed by the Governor General on the advice of the Prime Minister — they are not elected, so voters cannot remove them in an election.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-h-051",
    topicId: "government",
    difficulty: "hard",
    prompt: { en: "Why do provincial representatives have different titles (MLA, MNA, MPP, MHA)?" },
    options: [
      { en: "Because the federal government assigns them randomly" },
      { en: "Because they change every election" },
      { en: "Depending on the province or territory" },
      { en: "Because Senators choose them" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Members of the legislature are called MLAs, MNAs, MPPs or MHAs, depending on the province or territory.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-h-052",
    topicId: "government",
    difficulty: "hard",
    prompt: { en: "Does the territorial Commissioner make the territory's laws?" },
    options: [
      { en: "The Commissioner makes all territorial laws alone" },
      { en: "The Governor General passes territorial laws" },
      { en: "There are no laws in the territories" },
      {
        en: "No — the Commissioner plays a ceremonial role and the elected legislature passes territorial laws",
      },
    ],
    answerIndex: 3,
    explanation: {
      en: "In the territories, the Commissioner represents the federal government and plays a ceremonial role, while each territory has an elected legislature where territorial laws are passed.",
    },
    source: src("How Canadians Govern Themselves"),
  },
  {
    id: "gov-h-053",
    topicId: "government",
    difficulty: "hard",
    prompt: {
      en: "Two opposition parties hold 100 and 40 seats respectively. Which is the Official Opposition?",
    },
    options: [
      { en: "The party with 100 seats" },
      { en: "The party with 40 seats" },
      { en: "Neither — the Senate decides" },
      { en: "Both share the title" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The opposition party with the most members of the House of Commons is the Official Opposition.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-h-054",
    topicId: "government",
    difficulty: "hard",
    prompt: { en: "A party holds exactly 154 of the 308 seats. What kind of government is this?" },
    options: [
      { en: "A minority government" },
      { en: "No government can form" },
      { en: "A coalition is required" },
      { en: "A majority government" },
    ],
    answerIndex: 3,
    explanation: {
      en: "A majority government holds at least half of the seats; 154 is exactly half of 308, so it qualifies as a majority.",
    },
    source: src("Federal Elections"),
  },
  {
    id: "gov-h-055",
    topicId: "government",
    difficulty: "hard",
    prompt: {
      en: "A criminal-law bill has just passed Third Reading in the House of Commons. What happens next?",
    },
    options: [
      { en: "It becomes law immediately" },
      { en: "The Prime Minister signs it into law" },
      {
        en: "The Senate reviews it and then the Governor General grants royal assent on behalf of the Sovereign",
      },
      { en: "It goes to a public referendum" },
    ],
    answerIndex: 2,
    explanation: {
      en: "After the Third Reading in the House of Commons, the bill follows a similar process in the Senate, and royal assent is then granted by the Governor General on behalf of the Sovereign.",
    },
    source: src("How Canadians Govern Themselves"),
  },
];
