/**
 * Question bank chunk — part of questions.generated.ts. DO NOT EDIT BY HAND.
 */
import type { Question } from "../content";
import { src } from "./shared";

export const historyB: Question[] = [
  {
    id: "hist-m-023",
    topicId: "history",
    difficulty: "medium",
    prompt: {
      en: "John Graves Simcoe was Upper Canada’s first Lieutenant Governor and founder of…",
    },
    options: [
      { en: "Kingston" },
      { en: "Ottawa" },
      { en: "the City of York (now Toronto)" },
      { en: "Hamilton" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Simcoe was Upper Canada’s first Lieutenant Governor and founder of the City of York (now Toronto).",
    },
    source: src("Canada’s History: Abolition of Slavery"),
  },
  {
    id: "hist-m-024",
    topicId: "history",
    difficulty: "medium",
    prompt: {
      en: "The Hudson’s Bay Company came to dominate the northwest trade from Fort Garry (Winnipeg) and Fort Edmonton to…",
    },
    options: [
      { en: "Fort Calgary and Fort MacLeod" },
      { en: "Fort William and Fort York" },
      { en: "Fort Frontenac and Fort Niagara" },
      { en: "Fort Langley (near Vancouver) and Fort Victoria" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The Hudson’s Bay Company came to dominate the trade in the northwest from Fort Garry (Winnipeg) and Fort Edmonton to Fort Langley (near Vancouver) and Fort Victoria.",
    },
    source: src("Canada’s History: A Growing Economy"),
  },
  {
    id: "hist-m-025",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "The Hudson’s Bay Company operated with…" },
    options: [
      { en: "French, British and Aboriginal employees" },
      { en: "only British employees" },
      { en: "only French employees" },
      { en: "American contractors only" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The Hudson’s Bay Company, with French, British and Aboriginal employees, came to dominate the trade in the northwest.",
    },
    source: src("Canada’s History: A Growing Economy"),
  },
  {
    id: "hist-m-026",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "The first financial institutions in Canada opened in…" },
    options: [
      { en: "the 1860s" },
      { en: "the late 18th and early 19th centuries" },
      { en: "the 1920s" },
      { en: "after the Second World War" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The first financial institutions opened in the late 18th and early 19th centuries.",
    },
    source: src("Canada’s History: A Growing Economy"),
  },
  {
    id: "hist-m-027",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "For centuries, Canada’s economy was based mainly on…" },
    options: [
      { en: "manufacturing and steel" },
      { en: "banking and insurance" },
      { en: "farming and exporting natural resources such as fur, fish and timber" },
      { en: "oil and gas" },
    ],
    answerIndex: 2,
    explanation: {
      en: "For centuries Canada’s economy was based mainly on farming and on exporting natural resources such as fur, fish and timber.",
    },
    source: src("Canada’s History: A Growing Economy"),
  },
  {
    id: "hist-m-028",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "In early Canada, goods were transported by…" },
    options: [
      { en: "railways and highways" },
      { en: "airplanes and trucks" },
      { en: "pipelines" },
      { en: "roads, lakes, rivers and canals" },
    ],
    answerIndex: 3,
    explanation: { en: "Goods were transported by roads, lakes, rivers and canals." },
    source: src("Canada’s History: A Growing Economy"),
  },
  {
    id: "hist-m-029",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "After the defeat of Napoleon’s fleet at the Battle of Trafalgar in 1805…" },
    options: [
      { en: "the Royal Navy ruled the waves" },
      { en: "France ruled the waves" },
      { en: "America ruled the waves" },
      { en: "Spain ruled the waves" },
    ],
    answerIndex: 0,
    explanation: {
      en: "After the defeat of Napoleon Bonaparte’s fleet in the Battle of Trafalgar (1805), the Royal Navy ruled the waves.",
    },
    source: src("Canada’s History: The War of 1812: The Fight for Canada"),
  },
  {
    id: "hist-m-030",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "Major-General Sir Isaac Brock captured Detroit in…" },
    options: [{ en: "June 1812" }, { en: "July 1812" }, { en: "August 1813" }, { en: "June 1814" }],
    answerIndex: 1,
    explanation: { en: "In July, Major-General Sir Isaac Brock captured Detroit." },
    source: src("Canada’s History: The War of 1812: The Fight for Canada"),
  },
  {
    id: "hist-m-031",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "In 1813, HMS Shannon led the captured USS Chesapeake into…" },
    options: [
      { en: "Québec City" },
      { en: "Kingston harbour" },
      { en: "Halifax harbour" },
      { en: "Saint John harbour" },
    ],
    answerIndex: 2,
    explanation: {
      en: "HMS Shannon, a Royal Navy frigate, led the captured USS Chesapeake into Halifax harbour in 1813.",
    },
    source: src("Canada’s History: The War of 1812: The Fight for Canada"),
  },
  {
    id: "hist-m-032",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "The Duke of Wellington chose Bytown (Ottawa) as the endpoint of…" },
    options: [
      { en: "the St. Lawrence Seaway" },
      { en: "the Erie Canal" },
      { en: "the Welland Canal" },
      { en: "the Rideau Canal" },
    ],
    answerIndex: 3,
    explanation: { en: "Wellington chose Bytown (Ottawa) as the endpoint of the Rideau Canal." },
    source: src("Canada’s History: The War of 1812: The Fight for Canada"),
  },
  {
    id: "hist-m-033",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "The Rideau Canal was part of a network of forts built to…" },
    options: [
      { en: "prevent the U.S.A. from invading Canada again" },
      { en: "connect the Great Lakes" },
      { en: "transport furs to Montreal" },
      { en: "defend against French attacks" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The Rideau Canal was part of a network of forts to prevent the U.S.A. from invading Canada again.",
    },
    source: src("Canada’s History: The War of 1812: The Fight for Canada"),
  },
  {
    id: "hist-m-034",
    topicId: "history",
    difficulty: "medium",
    prompt: {
      en: "Britain paid for a costly Canadian defence system that included the Citadels at…",
    },
    options: [
      { en: "Kingston and Toronto" },
      { en: "Halifax and Québec City" },
      { en: "Montreal and Ottawa" },
      { en: "York and Niagara" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The British paid for a costly Canadian defence system, including the Citadels at Halifax and Québec City, the naval drydock at Halifax and Fort Henry at Kingston.",
    },
    source: src("Canada’s History: The War of 1812: The Fight for Canada"),
  },
  {
    id: "hist-m-035",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "The present-day Canada–U.S.A. border is partly an outcome of…" },
    options: [
      { en: "the Quebec Act" },
      { en: "Confederation" },
      { en: "the War of 1812" },
      { en: "the Treaty of Paris" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The present-day Canada-U.S.A. border is partly an outcome of the War of 1812, which ensured that Canada would remain independent of the United States.",
    },
    source: src("Canada’s History: The War of 1812: The Fight for Canada"),
  },
  {
    id: "hist-m-036",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "The rebellions of 1837–38 failed because the rebels…" },
    options: [
      { en: "lacked weapons" },
      { en: "were betrayed by the French" },
      { en: "arrived too late" },
      { en: "did not have enough public support" },
    ],
    answerIndex: 3,
    explanation: { en: "The rebels did not have enough public support to succeed." },
    source: src("Canada’s History: Rebellions of 1837–38"),
  },
  {
    id: "hist-m-037",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "After the rebellions, a number of rebels were…" },
    options: [
      { en: "hanged or exiled" },
      { en: "rewarded with land" },
      { en: "elected to Parliament" },
      { en: "sent to Britain as heroes" },
    ],
    answerIndex: 0,
    explanation: {
      en: "A number of rebels were hanged or exiled; some exiles later returned to Canada.",
    },
    source: src("Canada’s History: Rebellions of 1837–38"),
  },
  {
    id: "hist-m-038",
    topicId: "history",
    difficulty: "medium",
    prompt: {
      en: "Reformers Sir Étienne-Paschal Taché and Sir George-Étienne Cartier later became…",
    },
    options: [
      { en: "governors of New France" },
      { en: "Fathers of Confederation" },
      { en: "leaders of the rebellions" },
      { en: "American congressmen" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Reformers including Sir Étienne-Paschal Taché and Sir George-Étienne Cartier later became Fathers of Confederation.",
    },
    source: src("Canada’s History: Rebellions of 1837–38"),
  },
  {
    id: "hist-m-039",
    topicId: "history",
    difficulty: "medium",
    prompt: {
      en: "Lord Durham controversially said the quickest way for the Canadiens to achieve progress was to…",
    },
    options: [
      { en: "learn Indigenous languages" },
      { en: "move to the United States" },
      { en: "assimilate into English-speaking Protestant culture" },
      { en: "return to France" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Lord Durham said that the quickest way for the Canadiens to achieve progress was to assimilate into English-speaking Protestant culture.",
    },
    source: src("Canada’s History: Rebellions of 1837–38"),
  },
  {
    id: "hist-m-040",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "In 1848–49, the governor of United Canada, Lord Elgin…" },
    options: [
      { en: "abolished the assembly" },
      { en: "declared independence" },
      { en: "joined the United States" },
      { en: "introduced responsible government" },
    ],
    answerIndex: 3,
    explanation: {
      en: "In 1848–49 the governor of United Canada, Lord Elgin, with encouragement from London, introduced responsible government.",
    },
    source: src("Canada’s History: Responsible Government"),
  },
  {
    id: "hist-m-041",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "Sir Louis-Hippolyte La Fontaine was a champion of…" },
    options: [
      { en: "democracy and French language rights" },
      { en: "British imperial expansion" },
      { en: "American republican values" },
      { en: "the fur trade monopoly" },
    ],
    answerIndex: 0,
    explanation: {
      en: "La Fontaine, a champion of democracy and French language rights, became the first leader of a responsible government in the Canadas.",
    },
    source: src("Canada’s History: Responsible Government"),
  },
  {
    id: "hist-m-042",
    topicId: "history",
    difficulty: "medium",
    prompt: {
      en: "Under responsible government today, if the government loses a confidence vote in the assembly…",
    },
    options: [
      { en: "it calls a referendum" },
      { en: "it must resign" },
      { en: "it dissolves the courts" },
      { en: "it appeals to the King" },
    ],
    answerIndex: 1,
    explanation: {
      en: "This is the system that we have today: if the government loses a confidence vote in the assembly it must resign.",
    },
    source: src("Canada’s History: Responsible Government"),
  },
  {
    id: "hist-m-043",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "From 1864 to 1867, the Confederation representatives came from…" },
    options: [
      { en: "Ontario, Manitoba and British Columbia" },
      { en: "Quebec, Ontario and Alberta" },
      { en: "Nova Scotia, New Brunswick and the Province of Canada" },
      { en: "all thirteen colonies" },
    ],
    answerIndex: 2,
    explanation: {
      en: "From 1864 to 1867, representatives of Nova Scotia, New Brunswick and the Province of Canada, with British support, worked together to establish a new country.",
    },
    source: src("Canada’s History: Confederation"),
  },
  {
    id: "hist-m-044",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "Sir Leonard Tilley suggested the term “Dominion of Canada” in…" },
    options: [{ en: "1837" }, { en: "1867" }, { en: "1982" }, { en: "1864" }],
    answerIndex: 3,
    explanation: { en: "Sir Leonard Tilley suggested the term Dominion of Canada in 1864." },
    source: src("Canada’s History: Dominion from Sea to Sea"),
  },
  {
    id: "hist-m-045",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "Tilley was inspired by Psalm 72 in the Bible, which refers to…" },
    options: [
      { en: "dominion from sea to sea and from the river to the ends of the earth" },
      { en: "a city on a hill" },
      { en: "a new Jerusalem" },
      { en: "the promised land" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Tilley was inspired by Psalm 72, which refers to dominion from sea to sea and from the river to the ends of the earth.",
    },
    source: src("Canada’s History: Dominion from Sea to Sea"),
  },
  {
    id: "hist-m-046",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "The title “Dominion of Canada” was used officially for…" },
    options: [
      { en: "about 10 years" },
      { en: "about 100 years" },
      { en: "about 50 years" },
      { en: "about 200 years" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The title was written into the Constitution, was used officially for about 100 years, and remains part of our heritage today.",
    },
    source: src("Canada’s History: Dominion from Sea to Sea"),
  },
  {
    id: "hist-m-047",
    topicId: "history",
    difficulty: "medium",
    prompt: {
      en: "In the 1920s, some believed the British West Indies should become part of Canada. What happened?",
    },
    options: [
      { en: "They joined in 1925" },
      { en: "They became Nunavut" },
      { en: "This did not occur" },
      { en: "They joined in 1949" },
    ],
    answerIndex: 2,
    explanation: {
      en: "In the 1920s, some believed that the British West Indies should become part of Canada. This did not occur.",
    },
    source: src("Canada’s History: Dominion from Sea to Sea"),
  },
  {
    id: "hist-m-048",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "The transfer of the Arctic Islands (to the N.W.T.) occurred in…" },
    options: [{ en: "1870" }, { en: "1871" }, { en: "1873" }, { en: "1880" }],
    answerIndex: 3,
    explanation: { en: "1880 — Transfer of the Arctic Islands (to N.W.T.)." },
    source: src("Canada’s History: Expansion of the Dominion"),
  },
  {
    id: "hist-m-049",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "The Yukon Territory was created in…" },
    options: [{ en: "1898" }, { en: "1905" }, { en: "1949" }, { en: "1999" }],
    answerIndex: 0,
    explanation: { en: "1898 — Yukon Territory." },
    source: src("Canada’s History: Expansion of the Dominion"),
  },
  {
    id: "hist-m-050",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "Parliament has recognized January 11 as…" },
    options: [
      { en: "Vimy Day" },
      { en: "Sir John A. Macdonald Day" },
      { en: "Remembrance Day" },
      { en: "Canada Day" },
    ],
    answerIndex: 1,
    explanation: { en: "Parliament has recognized January 11 as Sir John A. Macdonald Day." },
    source: src("Canada’s History: Canada’s First Prime Minister"),
  },
  {
    id: "hist-m-051",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "Macdonald came to Upper Canada as a child and worked as a lawyer in…" },
    options: [{ en: "Toronto" }, { en: "Ottawa" }, { en: "Kingston, Ontario" }, { en: "Montreal" }],
    answerIndex: 2,
    explanation: { en: "He was a lawyer in Kingston, Ontario." },
    source: src("Canada’s History: Canada’s First Prime Minister"),
  },
  {
    id: "hist-m-052",
    topicId: "history",
    difficulty: "medium",
    prompt: {
      en: "Sir George-Étienne Cartier helped negotiate the entry into Canada of the Northwest Territories, Manitoba and…",
    },
    options: [{ en: "Ontario" }, { en: "Quebec" }, { en: "Alberta" }, { en: "British Columbia" }],
    answerIndex: 3,
    explanation: {
      en: "Cartier helped negotiate the entry of the Northwest Territories, Manitoba and British Columbia into Canada.",
    },
    source: src("Canada’s History: Canada’s First Prime Minister"),
  },
  {
    id: "hist-m-053",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "Ottawa sent soldiers to retake Fort Garry in…" },
    options: [{ en: "1870" }, { en: "1869" }, { en: "1873" }, { en: "1885" }],
    answerIndex: 0,
    explanation: { en: "Ottawa sent soldiers to retake Fort Garry in 1870." },
    source: src("Canada’s History: Challenge in the West"),
  },
  {
    id: "hist-m-054",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "After the first uprising, Riel fled to…" },
    options: [
      { en: "France" },
      { en: "the United States" },
      { en: "England" },
      { en: "the Northwest Territories" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Riel fled to the United States and Canada established a new province: Manitoba.",
    },
    source: src("Canada’s History: Challenge in the West"),
  },
  {
    id: "hist-m-055",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "Riel was elected to Parliament but…" },
    options: [
      { en: "became Speaker" },
      { en: "became prime minister" },
      { en: "never took his seat" },
      { en: "moved to Ottawa" },
    ],
    answerIndex: 2,
    explanation: { en: "Riel was elected to Parliament but never took his seat." },
    source: src("Canada’s History: Challenge in the West"),
  },
  {
    id: "hist-m-056",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "Riel’s trial and execution for high treason was…" },
    options: [
      { en: "celebrated across Canada" },
      { en: "ignored by Parliament" },
      { en: "ordered by the Queen" },
      { en: "strongly opposed in Quebec" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Riel’s trial and execution for high treason was strongly opposed in Quebec.",
    },
    source: src("Canada’s History: Challenge in the West"),
  },
  {
    id: "hist-m-057",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "The North West Mounted Police was established in 1873 to…" },
    options: [
      { en: "pacify the West and assist in negotiations with the Indians" },
      { en: "build the railway" },
      { en: "collect taxes in Ontario" },
      { en: "guard the US border" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Macdonald established the North West Mounted Police (NWMP) in 1873 to pacify the West and assist in negotiations with the Indians.",
    },
    source: src("Canada’s History: Challenge in the West"),
  },
  {
    id: "hist-m-058",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "The NWMP founded…" },
    options: [
      { en: "Fort Garry and Fort Edmonton" },
      { en: "Fort Calgary, Fort MacLeod and other centres that today are cities and towns" },
      { en: "York and Kingston" },
      { en: "Halifax and Québec City" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The NWMP founded Fort Calgary, Fort MacLeod and other centres that today are cities and towns.",
    },
    source: src("Canada’s History: Challenge in the West"),
  },
  {
    id: "hist-m-059",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "Regina became the NWMP’s…" },
    options: [
      { en: "first fort" },
      { en: "training school" },
      { en: "headquarters" },
      { en: "museum" },
    ],
    answerIndex: 2,
    explanation: { en: "Regina became its headquarters." },
    source: src("Canada’s History: Challenge in the West"),
  },
  {
    id: "hist-m-060",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "Gabriel Dumont was…" },
    options: [
      { en: "the first NWMP commissioner" },
      { en: "a Father of Confederation" },
      { en: "a railway engineer" },
      { en: "the Métis’ greatest military leader" },
    ],
    answerIndex: 3,
    explanation: { en: "Gabriel Dumont was the Métis’ greatest military leader." },
    source: src("Canada’s History: Challenge in the West"),
  },
  {
    id: "hist-m-061",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "The Canadian Pacific Railway was financed by…" },
    options: [
      { en: "British and American investors" },
      { en: "the Canadian government alone" },
      { en: "French banks" },
      { en: "Chinese merchants" },
    ],
    answerIndex: 0,
    explanation: { en: "The project was financed by British and American investors." },
    source: src("Canada’s History: A Railway from Sea to Sea"),
  },
  {
    id: "hist-m-062",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "After the railway was built, Chinese workers faced discrimination including…" },
    options: [
      { en: "a ban on owning land" },
      { en: "the Head Tax, a race-based entry fee" },
      { en: "forced military service" },
      { en: "deportation to Britain" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Afterwards the Chinese were subject to discrimination, including the Head Tax, a race-based entry fee.",
    },
    source: src("Canada’s History: A Railway from Sea to Sea"),
  },
  {
    id: "hist-m-063",
    topicId: "history",
    difficulty: "medium",
    prompt: {
      en: "During the economic boom of the 1890s and early 1900s, one million British and one million … immigrated to Canada.",
    },
    options: [{ en: "French" }, { en: "Germans" }, { en: "Americans" }, { en: "Russians" }],
    answerIndex: 2,
    explanation: {
      en: "One million British and one million Americans immigrated to Canada at this time.",
    },
    source: src("Canada’s History: Moving Westward"),
  },
  {
    id: "hist-m-064",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "Before 1914, about how many Ukrainians settled in the West?" },
    options: [{ en: "17,000" }, { en: "70,000" }, { en: "115,000" }, { en: "170,000" }],
    answerIndex: 3,
    explanation: {
      en: "The railway made it possible for immigrants, including 170,000 Ukrainians, to settle in the West before 1914.",
    },
    source: src("Canada’s History: Moving Westward"),
  },
  {
    id: "hist-m-065",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "Before 1914, about how many Poles settled in the West?" },
    options: [{ en: "115,000" }, { en: "11,500" }, { en: "1,150,000" }, { en: "15,000" }],
    answerIndex: 0,
    explanation: {
      en: "The railway made it possible for immigrants, including 115,000 Poles, to settle in the West before 1914.",
    },
    source: src("Canada’s History: Moving Westward"),
  },
  {
    id: "hist-m-066",
    topicId: "history",
    difficulty: "medium",
    prompt: {
      en: "Over 7,000 Canadians volunteered for the South African (Boer) War of 1899–1902, and over … died.",
    },
    options: [{ en: "26" }, { en: "260" }, { en: "2,600" }, { en: "26,000" }],
    answerIndex: 1,
    explanation: {
      en: "Over 7,000 volunteered to fight in the South African War (1899–1902), popularly known as the Boer War, and over 260 died.",
    },
    source: src("Canada’s History: The First World War"),
  },
  {
    id: "hist-m-067",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "In 1900, Canadians fought in the battles of…" },
    options: [
      { en: "Vimy and Amiens" },
      { en: "Detroit and Queenston" },
      { en: "Paardeberg and Lillefontein" },
      { en: "Dieppe and Hong Kong" },
    ],
    answerIndex: 2,
    explanation: {
      en: "In 1900, Canadians took part in the battles of Paardeberg and Lillefontein, victories that strengthened national pride.",
    },
    source: src("Canada’s History: The First World War"),
  },
  {
    id: "hist-m-068",
    topicId: "history",
    difficulty: "medium",
    prompt: {
      en: "More than 600,000 Canadians served in the First World War, out of a total population of…",
    },
    options: [
      { en: "four million" },
      { en: "six million" },
      { en: "eleven million" },
      { en: "eight million" },
    ],
    answerIndex: 3,
    explanation: {
      en: "More than 600,000 Canadians served in the war, most of them volunteers, out of a total population of eight million.",
    },
    source: src("Canada’s History: The First World War"),
  },
  {
    id: "hist-m-069",
    topicId: "history",
    difficulty: "medium",
    prompt: {
      en: "From 1914 to 1920, Ottawa interned over 8,000 former Austro-Hungarian subjects — mainly … — as “enemy aliens” in 24 labour camps.",
    },
    options: [
      { en: "Ukrainian men" },
      { en: "German women" },
      { en: "Italian children" },
      { en: "Turkish merchants" },
    ],
    answerIndex: 0,
    explanation: {
      en: "From 1914 to 1920, Ottawa interned over 8,000 former Austro-Hungarian subjects, mainly Ukrainian men, as enemy aliens in 24 labour camps.",
    },
    source: src("Canada’s History: The First World War"),
  },
  {
    id: "hist-m-070",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "The Canadian Corps captured Vimy Ridge in April 1917, with…" },
    options: [
      { en: "1,000 killed or wounded" },
      { en: "10,000 killed or wounded" },
      { en: "100,000 killed or wounded" },
      { en: "no casualties" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The Canadian Corps captured Vimy Ridge in April 1917, with 10,000 killed or wounded.",
    },
    source: src("Canada’s History: The First World War"),
  },
  {
    id: "hist-m-071",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "In 1918, under General Sir Arthur Currie, the Canadian Corps advanced in…" },
    options: [
      { en: "the first hundred days" },
      { en: "the Hundred Years’ War" },
      { en: "the last hundred days" },
      { en: "the Seven Years’ War" },
    ],
    answerIndex: 2,
    explanation: {
      en: "In 1918, under the command of General Sir Arthur Currie, the Canadian Corps advanced in the last hundred days.",
    },
    source: src("Canada’s History: The First World War"),
  },
  {
    id: "hist-m-072",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "The Germans called the Battle of Amiens of August 8, 1918…" },
    options: [
      { en: "the miracle of the Marne" },
      { en: "the turning point" },
      { en: "the great retreat" },
      { en: "the black day of the German Army" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The Battle of Amiens on August 8, 1918 — which the Germans called the black day of the German Army.",
    },
    source: src("Canada’s History: The First World War"),
  },
  {
    id: "hist-m-073",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "The First World War ended in the Armistice on…" },
    options: [
      { en: "November 11, 1918" },
      { en: "April 9, 1917" },
      { en: "August 8, 1918" },
      { en: "May 8, 1945" },
    ],
    answerIndex: 0,
    explanation: {
      en: "With Germany and Austria’s surrender, the war ended in the Armistice on November 11, 1918.",
    },
    source: src("Canada’s History: The First World War"),
  },
  {
    id: "hist-m-074",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "In the First World War, 60,000 Canadians were killed and … wounded." },
    options: [{ en: "17,000" }, { en: "170,000" }, { en: "1,700,000" }, { en: "70,000" }],
    answerIndex: 1,
    explanation: { en: "In total 60,000 Canadians were killed and 170,000 wounded." },
    source: src("Canada’s History: The First World War"),
  },
  {
    id: "hist-m-075",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "More than 3,000 nurses nicknamed “Bluebirds” served in the…" },
    options: [
      { en: "Royal Canadian Navy" },
      { en: "Canadian Red Cross" },
      { en: "Royal Canadian Army Medical Corps" },
      { en: "Victorian Order of Nurses" },
    ],
    answerIndex: 2,
    explanation: {
      en: "More than 3,000 nurses, nicknamed Bluebirds, served in the Royal Canadian Army Medical Corps, 2,500 of them overseas.",
    },
    source: src("Canada’s History: Women Get the Vote"),
  },
  {
    id: "hist-m-076",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "In 1917, Borden’s government gave women the federal vote — first to…" },
    options: [
      { en: "all women over 21" },
      { en: "women in Quebec only" },
      { en: "married women only" },
      { en: "nurses at the battle front, then women related to men in active wartime service" },
    ],
    answerIndex: 3,
    explanation: {
      en: "In 1917 the federal government gave women the right to vote in federal elections — first to nurses at the battle front, then to women who were related to men in active wartime service.",
    },
    source: src("Canada’s History: Women Get the Vote"),
  },
  {
    id: "hist-m-077",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "In 1921, Agnes Macphail — a farmer and teacher — became…" },
    options: [
      { en: "the first woman senator" },
      { en: "the first woman judge" },
      { en: "the first woman MP" },
      { en: "the first woman premier" },
    ],
    answerIndex: 2,
    explanation: { en: "In 1921 Agnes Macphail, a farmer and teacher, became the first woman MP." },
    source: src("Canada’s History: Women Get the Vote"),
  },
  {
    id: "hist-h-001",
    topicId: "history",
    difficulty: "hard",
    prompt: { en: "Which act restored French civil law while maintaining British criminal law?" },
    options: [
      { en: "The Quebec Act of 1774" },
      { en: "The Constitutional Act of 1791" },
      { en: "The British North America Act of 1867" },
      { en: "The Durham Report" },
    ],
    answerIndex: 0,
    explanation: {
      en: "It was the Quebec Act of 1774 — not the Constitutional Act — that restored French civil law while maintaining British criminal law.",
    },
    source: src("Canada’s History: A Tradition of Accommodation"),
  },
  {
    id: "hist-h-002",
    topicId: "history",
    difficulty: "hard",
    prompt: { en: "Under which act did the name “Canada” become official?" },
    options: [
      { en: "The Quebec Act of 1774" },
      { en: "The Constitutional Act of 1791" },
      { en: "The British North America Act of 1867" },
      { en: "The Manitoba Act of 1870" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The Constitutional Act of 1791 made the name Canada official, and it has been used ever since.",
    },
    source: src("Canada’s History: The Beginnings of Democracy"),
  },
  {
    id: "hist-h-003",
    topicId: "history",
    difficulty: "hard",
    prompt: {
      en: "Unlike the 1869–70 uprising — sparked when Canada took over the northwest without consulting the 12,000 Métis — the 1885 rebellion began when…",
    },
    options: [
      { en: "British Columbia joined Confederation" },
      { en: "the CPR was completed" },
      { en: "Métis and Indian rights were again threatened by westward settlement" },
      { en: "Riel was elected to Parliament" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The second rebellion in 1885 began as Métis and Indian rights were again threatened by westward settlement.",
    },
    source: src("Canada’s History: Challenge in the West"),
  },
  {
    id: "hist-h-004",
    topicId: "history",
    difficulty: "hard",
    prompt: {
      en: "Which of these happened between Riel’s flight to the United States (1870) and his execution (1885)?",
    },
    options: [
      { en: "Riel seized Fort Garry" },
      { en: "Manitoba was established" },
      { en: "Riel fled to the United States" },
      { en: "Riel was elected to Parliament but never took his seat" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Between his 1870 flight and his 1885 execution, Riel was elected to Parliament but never took his seat.",
    },
    source: src("Canada’s History: Challenge in the West"),
  },
  {
    id: "hist-h-005",
    topicId: "history",
    difficulty: "hard",
    prompt: {
      en: "Which governor both defended the rights of the Canadiens and supervised the Loyalist migration of 1782–83?",
    },
    options: [
      { en: "Sir Guy Carleton (Lord Dorchester)" },
      { en: "Lord Durham" },
      { en: "Lord Elgin" },
      { en: "John Graves Simcoe" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Sir Guy Carleton defended the rights of the Canadiens, defeated the 1775 American invasion of Quebec, and supervised the Loyalist migration of 1782–83.",
    },
    source: src("Canada’s History: Royal New France"),
  },
  {
    id: "hist-h-006",
    topicId: "history",
    difficulty: "hard",
    prompt: {
      en: "Which came first: the establishment of the NWMP or the execution of Louis Riel?",
    },
    options: [
      { en: "Riel’s execution came first" },
      { en: "The NWMP was established first, in 1873" },
      { en: "Both happened in 1885" },
      { en: "Neither event happened" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The NWMP was established in 1873, twelve years before Riel’s 1885 execution.",
    },
    source: src("Canada’s History: Challenge in the West"),
  },
  {
    id: "hist-h-007",
    topicId: "history",
    difficulty: "hard",
    prompt: {
      en: "After its 1670 charter, the Hudson’s Bay Company competed with Montreal-based traders for…",
    },
    options: [
      { en: "10 years" },
      { en: "50 years" },
      { en: "the next 100 years" },
      { en: "the next 200 years" },
    ],
    answerIndex: 2,
    explanation: { en: "For the next 100 years the Company competed with Montreal-based traders." },
    source: src("Canada’s History: Struggle for a Continent"),
  },
  {
    id: "hist-h-008",
    topicId: "history",
    difficulty: "hard",
    prompt: {
      en: "According to the guide, the Hudson’s Bay Company flag flew over Western Canada for … before Confederation.",
    },
    options: [{ en: "50 years" }, { en: "100 years" }, { en: "150 years" }, { en: "200 years" }],
    answerIndex: 3,
    explanation: {
      en: "The flag of the Hudson’s Bay Company flew over Western Canada for 200 years before Confederation.",
    },
    source: src("Canada’s History: Challenge in the West"),
  },
  {
    id: "hist-h-009",
    topicId: "history",
    difficulty: "hard",
    prompt: {
      en: "Which came first: the first representative assembly in Halifax or the Battle of the Plains of Abraham?",
    },
    options: [
      { en: "The Halifax assembly, elected in 1758" },
      { en: "The Plains of Abraham, in 1759" },
      { en: "Both in the same year" },
      { en: "Both are 19th-century events" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The first representative assembly was elected in Halifax in 1758, a year before the 1759 Battle of the Plains of Abraham.",
    },
    source: src("Canada’s History: The Beginnings of Democracy"),
  },
  {
    id: "hist-h-010",
    topicId: "history",
    difficulty: "hard",
    prompt: { en: "Which came first: the Quebec Act or the American Declaration of Independence?" },
    options: [
      { en: "They were passed in the same year" },
      { en: "The Quebec Act of 1774" },
      { en: "The Declaration of 1776" },
      { en: "The Constitutional Act of 1791" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The Quebec Act (1774) came two years before the 1776 Declaration of Independence.",
    },
    source: src("Canada’s History: A Tradition of Accommodation"),
  },
  {
    id: "hist-h-011",
    topicId: "history",
    difficulty: "hard",
    prompt: { en: "What distinguished Britain’s 1807 anti-slavery action from its 1833 action?" },
    options: [
      { en: "1807 freed all slaves; 1833 only banned the trade" },
      { en: "1807 applied only to Canada" },
      {
        en: "1807 prohibited the buying and selling of slaves; 1833 abolished slavery throughout the Empire",
      },
      { en: "There was no difference" },
    ],
    answerIndex: 2,
    explanation: {
      en: "In 1807 Parliament prohibited the buying and selling of slaves; in 1833 it abolished slavery throughout the Empire.",
    },
    source: src("Canada’s History: Abolition of Slavery"),
  },
  {
    id: "hist-h-012",
    topicId: "history",
    difficulty: "hard",
    prompt: {
      en: "Before becoming Upper Canada’s first Lieutenant Governor, John Graves Simcoe was a…",
    },
    options: [
      { en: "French fur trader" },
      { en: "American congressman" },
      { en: "British admiral" },
      { en: "Loyalist military officer" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Simcoe, who led Upper Canada toward abolition, was a Loyalist military officer.",
    },
    source: src("Canada’s History: Abolition of Slavery"),
  },
  {
    id: "hist-h-013",
    topicId: "history",
    difficulty: "hard",
    prompt: { en: "After burning Washington in 1814, Robert Ross died in battle and was buried…" },
    options: [
      { en: "in Halifax with full military honours" },
      { en: "in Washington with honours" },
      { en: "at Queenston Heights" },
      { en: "in London" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Ross died in battle soon afterwards and was buried in Halifax with full military honours.",
    },
    source: src("Canada’s History: The War of 1812: The Fight for Canada"),
  },
  {
    id: "hist-h-014",
    topicId: "history",
    difficulty: "hard",
    prompt: { en: "Laura Secord’s warning contributed to victory at the Battle of…" },
    options: [
      { en: "Châteauguay" },
      { en: "Beaver Dams" },
      { en: "Queenston Heights" },
      { en: "Detroit" },
    ],
    answerIndex: 1,
    explanation: { en: "Her bravery contributed to victory at the Battle of Beaver Dams." },
    source: src("Canada’s History: The War of 1812: The Fight for Canada"),
  },
  {
    id: "hist-h-015",
    topicId: "history",
    difficulty: "hard",
    prompt: {
      en: "How did the Duke of Wellington play a direct role in founding the national capital?",
    },
    options: [
      { en: "He named it Ottawa" },
      { en: "He built the Parliament Buildings" },
      { en: "He chose Bytown (Ottawa) as the endpoint of the Rideau Canal" },
      { en: "He defeated Napoleon at Ottawa" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Wellington chose Bytown (Ottawa) as the endpoint of the Rideau Canal, and therefore played a direct role in founding the national capital.",
    },
    source: src("Canada’s History: The War of 1812: The Fight for Canada"),
  },
  {
    id: "hist-h-016",
    topicId: "history",
    difficulty: "hard",
    prompt: { en: "At Châteauguay, Charles de Salaberry’s 460 soldiers were mostly…" },
    options: [
      { en: "British regulars" },
      { en: "American defectors" },
      { en: "Iroquois warriors" },
      { en: "French Canadiens" },
    ],
    answerIndex: 3,
    explanation: {
      en: "De Salaberry’s 460 soldiers were mostly French Canadiens who turned back 4,000 American invaders.",
    },
    source: src("Canada’s History: The War of 1812: The Fight for Canada"),
  },
  {
    id: "hist-h-017",
    topicId: "history",
    difficulty: "hard",
    prompt: {
      en: "Lord Durham’s recommendation that Canadiens assimilate into English-speaking Protestant culture demonstrated…",
    },
    options: [
      { en: "a complete lack of understanding of French Canadians" },
      { en: "his support for French rights" },
      { en: "his plan for independence" },
      { en: "British military strategy" },
    ],
    answerIndex: 0,
    explanation: {
      en: "This recommendation demonstrated a complete lack of understanding of French Canadians, who sought to uphold the distinct identity of French Canada.",
    },
    source: src("Canada’s History: Rebellions of 1837–38"),
  },
  {
    id: "hist-h-018",
    topicId: "history",
    difficulty: "hard",
    prompt: { en: "Lord Elgin introduced responsible government in United Canada in 1848–49…" },
    options: [
      { en: "against London’s wishes" },
      { en: "with encouragement from London" },
      { en: "after a military coup" },
      { en: "by order of the Pope" },
    ],
    answerIndex: 1,
    explanation: {
      en: "In 1848–49 the governor of United Canada, Lord Elgin, with encouragement from London, introduced responsible government.",
    },
    source: src("Canada’s History: Responsible Government"),
  },
  {
    id: "hist-h-019",
    topicId: "history",
    difficulty: "hard",
    prompt: {
      en: "La Fontaine’s 1849 role as first head of a responsible government was described as similar to…",
    },
    options: [
      { en: "a king" },
      { en: "a governor general" },
      { en: "a prime minister" },
      { en: "a chief justice" },
    ],
    answerIndex: 2,
    explanation: {
      en: "La Fontaine became the first head of a responsible government (similar to a prime minister) in Canada in 1849.",
    },
    source: src("Canada’s History: Responsible Government"),
  },
  {
    id: "hist-h-020",
    topicId: "history",
    difficulty: "hard",
    prompt: { en: "The Fathers of Confederation worked with the support of…" },
    options: [
      { en: "France" },
      { en: "the United States" },
      { en: "the Hudson’s Bay Company" },
      { en: "Britain" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The Fathers of Confederation worked with British support from 1864 to 1867.",
    },
    source: src("Canada’s History: Confederation"),
  },
  {
    id: "hist-h-021",
    topicId: "history",
    difficulty: "hard",
    prompt: { en: "The British North America Act of 1867 was passed by…" },
    options: [
      { en: "the British Parliament" },
      { en: "the Canadian Parliament" },
      { en: "the Quebec Assembly" },
      { en: "the US Congress" },
    ],
    answerIndex: 0,
    explanation: { en: "The British Parliament passed the British North America Act in 1867." },
    source: src("Canada’s History: Confederation"),
  },
  {
    id: "hist-h-022",
    topicId: "history",
    difficulty: "hard",
    prompt: { en: "Which of these came first: the Yukon Territory, Alberta, or Nunavut?" },
    options: [
      { en: "Alberta" },
      { en: "The Yukon Territory (1898)" },
      { en: "Nunavut" },
      { en: "All in the same year" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The Yukon Territory (1898) came before Alberta (1905) and Nunavut (1999).",
    },
    source: src("Canada’s History: Expansion of the Dominion"),
  },
  {
    id: "hist-h-023",
    topicId: "history",
    difficulty: "hard",
    prompt: { en: "Sir Leonard Tilley, who suggested the term “Dominion of Canada,” was from…" },
    options: [
      { en: "Nova Scotia" },
      { en: "Ontario" },
      { en: "New Brunswick" },
      { en: "Prince Edward Island" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Sir Leonard Tilley was an elected official and Father of Confederation from New Brunswick.",
    },
    source: src("Canada’s History: Dominion from Sea to Sea"),
  },
  {
    id: "hist-h-024",
    topicId: "history",
    difficulty: "hard",
    prompt: { en: "Before becoming a Father of Confederation, John A. Macdonald had served in…" },
    options: [
      { en: "the Royal Navy" },
      { en: "the French army" },
      { en: "the Hudson’s Bay Company" },
      { en: "the voluntary government militia in Upper Canada" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Macdonald had been a member of the voluntary government militia in Upper Canada during the rebellions era.",
    },
    source: src("Canada’s History: Rebellions of 1837–38"),
  },
  {
    id: "hist-h-025",
    topicId: "history",
    difficulty: "hard",
    prompt: {
      en: "The French Empire in North America built by Jean Talon, Bishop Laval and Count Frontenac reached from…",
    },
    options: [
      { en: "Hudson Bay to the Gulf of Mexico" },
      { en: "Labrador to California" },
      { en: "Newfoundland to the Arctic" },
      { en: "Acadia to Louisiana" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Leaders like Jean Talon, Bishop Laval, and Count Frontenac built a French Empire in North America that reached from Hudson Bay to the Gulf of Mexico.",
    },
    source: src("Canada’s History: Royal New France"),
  },
  {
    id: "hist-h-026",
    topicId: "history",
    difficulty: "hard",
    prompt: { en: "How did Jacques Cartier learn the Iroquoian word “kanata”?" },
    options: [
      { en: "From a French dictionary" },
      { en: "From two captured guides" },
      { en: "From a map" },
      { en: "From the King of France" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Cartier heard two captured guides speak the Iroquoian word kanata, meaning village.",
    },
    source: src("Canada’s History: Exploring a River, Naming Canada"),
  },
  {
    id: "hist-h-027",
    topicId: "history",
    difficulty: "hard",
    prompt: { en: "The first 1604 settlement site, St. Croix Island, is in present-day…" },
    options: [{ en: "Nova Scotia" }, { en: "Quebec" }, { en: "Maine" }, { en: "New Brunswick" }],
    answerIndex: 2,
    explanation: {
      en: "The 1604 settlement was first on St. Croix Island (in present-day Maine), then at Port-Royal in Acadia.",
    },
    source: src("Canada’s History: Royal New France"),
  },
  {
    id: "hist-h-028",
    topicId: "history",
    difficulty: "hard",
    prompt: {
      en: "The Iroquois confederation that battled French settlements originally comprised…",
    },
    options: [
      { en: "three First Nations" },
      { en: "four First Nations" },
      { en: "twelve First Nations" },
      { en: "five (later six) First Nations" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The Iroquois were a confederation of five (later six) First Nations who battled with the French settlements for a century.",
    },
    source: src("Canada’s History: Royal New France"),
  },
  {
    id: "hist-h-029",
    topicId: "history",
    difficulty: "hard",
    prompt: { en: "The voyageurs and coureurs des bois formed strong alliances with…" },
    options: [
      { en: "First Nations" },
      { en: "the British army" },
      { en: "American settlers" },
      { en: "Spanish merchants" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The voyageurs and coureurs des bois formed strong alliances with First Nations.",
    },
    source: src("Canada’s History: Struggle for a Continent"),
  },
  {
    id: "hist-h-030",
    topicId: "history",
    difficulty: "hard",
    prompt: {
      en: "Which of the following groups were among the Loyalists’ religious backgrounds?",
    },
    options: [
      { en: "Only Anglican" },
      { en: "Presbyterian, Anglican, Baptist, Methodist, Jewish, Quaker and Catholic" },
      { en: "Only Catholic and Jewish" },
      { en: "Only Methodist and Baptist" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The Loyalists came from Presbyterian, Anglican, Baptist, Methodist, Jewish, Quaker, and Catholic religious backgrounds.",
    },
    source: src("Canada’s History: United Empire Loyalists"),
  },
  {
    id: "hist-h-031",
    topicId: "history",
    difficulty: "hard",
    prompt: { en: "Why did some black Nova Scotians leave for Sierra Leone in 1792?" },
    options: [
      { en: "They were ordered by the King" },
      { en: "They sought gold" },
      { en: "They were given poor land" },
      { en: "They fled the War of 1812" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Some black Nova Scotians, who were given poor land, moved on in 1792 to establish Freetown, Sierra Leone.",
    },
    source: src("Canada’s History: United Empire Loyalists"),
  },
  {
    id: "hist-h-032",
    topicId: "history",
    difficulty: "hard",
    prompt: {
      en: "Which colony received its first representative assembly earlier: Prince Edward Island or New Brunswick?",
    },
    options: [
      { en: "New Brunswick, in 1785" },
      { en: "Both in the same year" },
      { en: "Neither had one" },
      { en: "Prince Edward Island, in 1773" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Prince Edward Island followed Halifax in 1773; New Brunswick followed in 1785.",
    },
    source: src("Canada’s History: The Beginnings of Democracy"),
  },
  {
    id: "hist-h-033",
    topicId: "history",
    difficulty: "hard",
    prompt: { en: "The Underground Railroad was…" },
    options: [
      { en: "a Christian anti-slavery network" },
      { en: "a secret railway line" },
      { en: "a fur trade route" },
      { en: "a military road" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The Underground Railroad was a Christian anti-slavery network that helped escaped slaves reach Canada.",
    },
    source: src("Canada’s History: Abolition of Slavery"),
  },
  {
    id: "hist-h-034",
    topicId: "history",
    difficulty: "hard",
    prompt: {
      en: "The Provincial Freeman, which Mary Ann Shadd Cary helped found and edit, was a…",
    },
    options: [
      { en: "daily military bulletin" },
      { en: "weekly newspaper" },
      { en: "monthly magazine" },
      { en: "government gazette" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The Provincial Freeman was a weekly newspaper dedicated to anti-slavery, black immigration to Canada, temperance, and upholding British rule.",
    },
    source: src("Canada’s History: Abolition of Slavery"),
  },
  {
    id: "hist-h-035",
    topicId: "history",
    difficulty: "hard",
    prompt: {
      en: "Of the more than 600,000 Canadians who served in the First World War, most were…",
    },
    options: [
      { en: "conscripts" },
      { en: "mercenaries" },
      { en: "volunteers" },
      { en: "British regulars" },
    ],
    answerIndex: 2,
    explanation: { en: "More than 600,000 Canadians served in the war, most of them volunteers." },
    source: src("Canada’s History: The First World War"),
  },
  {
    id: "hist-h-036",
    topicId: "history",
    difficulty: "hard",
    prompt: { en: "At Vimy Ridge, the Canadians secured their reputation as…" },
    options: [
      { en: "the best-dressed troops" },
      { en: "the largest army" },
      { en: "the youngest soldiers" },
      { en: "the “shock troops of the British Empire”" },
    ],
    answerIndex: 3,
    explanation: {
      en: "At Vimy the Canadians secured their reputation for valour as the shock troops of the British Empire.",
    },
    source: src("Canada’s History: The First World War"),
  },
  {
    id: "hist-h-037",
    topicId: "history",
    difficulty: "hard",
    prompt: {
      en: "What was Britain’s position on Canada’s First World War internment of “enemy aliens”?",
    },
    options: [
      { en: "Britain advised against the policy" },
      { en: "Britain ordered it" },
      { en: "Britain funded it" },
      { en: "Britain had no opinion" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Ottawa interned over 8,000 former Austro-Hungarian subjects even though Britain advised against the policy.",
    },
    source: src("Canada’s History: The First World War"),
  },
  {
    id: "hist-h-038",
    topicId: "history",
    difficulty: "hard",
    prompt: { en: "Before becoming Canada’s greatest soldier, General Sir Arthur Currie was a…" },
    options: [
      { en: "regular British officer" },
      { en: "reserve officer" },
      { en: "naval commander" },
      { en: "war correspondent" },
    ],
    answerIndex: 1,
    explanation: { en: "Sir Arthur Currie, a reserve officer, became Canada’s greatest soldier." },
    source: src("Canada’s History: The First World War"),
  },
  {
    id: "hist-h-039",
    topicId: "history",
    difficulty: "hard",
    prompt: {
      en: "The Vimy Memorial in France honours those who served and died at Vimy Ridge, described as…",
    },
    options: [
      { en: "the last battle of the war" },
      { en: "a naval victory" },
      { en: "the first British victory of the First World War" },
      { en: "a peace conference site" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The Vimy Memorial honours those who served and died in the Battle of Vimy Ridge on April 9, 1917, the first British victory of the First World War.",
    },
    source: src("Canada’s History: The First World War"),
  },
  {
    id: "hist-h-040",
    topicId: "history",
    difficulty: "hard",
    prompt: {
      en: "Most Canadian women gained the federal vote in 1918; Quebec granted women the vote in 1940 — how many years later?",
    },
    options: [{ en: "12 years" }, { en: "20 years" }, { en: "32 years" }, { en: "22 years" }],
    answerIndex: 3,
    explanation: {
      en: "Quebec granted women the vote in 1940, twenty-two years after most Canadian women gained the federal vote in 1918.",
    },
    source: src("Canada’s History: Women Get the Vote"),
  },
  {
    id: "hist-h-041",
    topicId: "history",
    difficulty: "hard",
    prompt: {
      en: "Dr. Emily Stowe was both the founder of Canada’s women’s suffrage movement and…",
    },
    options: [
      { en: "the first Canadian woman to practise medicine in Canada" },
      { en: "the first woman MP" },
      { en: "the first woman publisher" },
      { en: "the first woman judge" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Dr. Emily Stowe founded the women’s suffrage movement and was the first Canadian woman to practise medicine in Canada.",
    },
    source: src("Canada’s History: Women Get the Vote"),
  },
  {
    id: "hist-h-042",
    topicId: "history",
    difficulty: "hard",
    prompt: { en: "The red poppy honours…" },
    options: [
      { en: "only Vimy veterans" },
      { en: "the sacrifices of over a million who served and the 110,000 who gave their lives" },
      { en: "the founders of Confederation" },
      { en: "the nurses called Bluebirds" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The poppy honours the sacrifices of over a million brave men and women who have served, and the 110,000 who have given their lives.",
    },
    source: src("Canada’s History: Remembrance Day"),
  },
  {
    id: "hist-h-043",
    topicId: "history",
    difficulty: "hard",
    prompt: {
      en: "Lieutenant-Colonel John McCrae, who composed “In Flanders Fields” in 1915, was a…",
    },
    options: [
      { en: "naval captain" },
      { en: "infantry private" },
      { en: "Canadian medical officer" },
      { en: "war artist" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Canadian medical officer Lieutenant-Colonel John McCrae composed the poem In Flanders Fields in 1915.",
    },
    source: src("Canada’s History: Remembrance Day"),
  },
  {
    id: "hist-h-044",
    topicId: "history",
    difficulty: "hard",
    prompt: { en: "The Bank of Canada was created in 1934 as…" },
    options: [
      { en: "a commercial bank" },
      { en: "a military fund" },
      { en: "a stock exchange" },
      {
        en: "a central bank to manage the money supply and bring stability to the financial system",
      },
    ],
    answerIndex: 3,
    explanation: {
      en: "The Bank of Canada, a central bank to manage the money supply and bring stability to the financial system, was created in 1934.",
    },
    source: src("Canada’s History: Between the Wars"),
  },
  {
    id: "hist-h-045",
    topicId: "history",
    difficulty: "hard",
    prompt: { en: "During the Great Depression, farmers in Western Canada were hit hardest by…" },
    options: [
      { en: "low grain prices and a terrible drought" },
      { en: "a plague of locusts only" },
      { en: "floods in the east" },
      { en: "a railway strike" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Farmers in Western Canada were hit hardest by low grain prices and a terrible drought.",
    },
    source: src("Canada’s History: Between the Wars"),
  },
  {
    id: "hist-h-046",
    topicId: "history",
    difficulty: "hard",
    prompt: {
      en: "Compared with other Commonwealth countries, Canada’s contribution to the Allied air effort in the Second World War was…",
    },
    options: [
      { en: "the smallest" },
      { en: "greater than any other Commonwealth country" },
      { en: "limited to training" },
      { en: "only naval" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Canada contributed more to the Allied air effort than any other Commonwealth country, with over 130,000 Allied air crew trained in Canada under the British Commonwealth Air Training Plan.",
    },
    source: src("Canada’s History: The Second World War"),
  },
  {
    id: "hist-h-047",
    topicId: "history",
    difficulty: "hard",
    prompt: { en: "At the end of the Second World War, Canada had the…" },
    options: [
      { en: "largest army in the world" },
      { en: "second-largest air force" },
      { en: "third-largest navy in the world" },
      { en: "smallest merchant fleet" },
    ],
    answerIndex: 2,
    explanation: {
      en: "At the end of the Second World War, Canada had the third-largest navy in the world.",
    },
    source: src("Canada’s History: The Second World War"),
  },
  {
    id: "hist-h-048",
    topicId: "history",
    difficulty: "hard",
    prompt: {
      en: "Canadians fought bravely and suffered losses in the unsuccessful defence of Hong Kong in…",
    },
    options: [{ en: "1939" }, { en: "1940" }, { en: "1942" }, { en: "1941" }],
    answerIndex: 3,
    explanation: {
      en: "The Canadians fought bravely and suffered losses in the unsuccessful defence of Hong Kong (1941) from attack by Imperial Japan.",
    },
    source: src("Canada’s History: The Second World War"),
  },
  {
    id: "hist-h-049",
    topicId: "history",
    difficulty: "hard",
    prompt: { en: "In the Pacific war, Japan…" },
    options: [
      { en: "launched fire balloons over B.C. and the Prairies" },
      { en: "invaded Vancouver" },
      { en: "sank the Canadian fleet at Halifax" },
      { en: "occupied Newfoundland" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Japan invaded the Aleutian Islands, attacked a lighthouse on Vancouver Island, and launched fire balloons over B.C. and the Prairies.",
    },
    source: src("Canada’s History: The Second World War"),
  },
  {
    id: "hist-h-050",
    topicId: "history",
    difficulty: "hard",
    prompt: {
      en: "Despite what advice did Ottawa forcibly relocate Canadians of Japanese origin?",
    },
    options: [
      { en: "Britain ordered the relocation" },
      { en: "The military and the RCMP told Ottawa they posed little danger to Canada" },
      { en: "The US demanded it" },
      { en: "No advice was given" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The relocation occurred even though the military and the RCMP told Ottawa that they posed little danger to Canada.",
    },
    source: src("Canada’s History: The Second World War"),
  },
  {
    id: "hist-h-051",
    topicId: "history",
    difficulty: "hard",
    prompt: { en: "Approximately what share of Allied soldiers on D-Day were Canadian?" },
    options: [
      { en: "One in a hundred" },
      { en: "One in fifty" },
      { en: "One in ten" },
      { en: "One in two" },
    ],
    answerIndex: 2,
    explanation: { en: "Approximately one in ten Allied soldiers on D-Day was Canadian." },
    source: src("Canada’s History: The Second World War"),
  },
  {
    id: "hist-h-052",
    topicId: "history",
    difficulty: "hard",
    prompt: { en: "The German surrender of May 8, 1945, brought to an end…" },
    options: [
      { en: "four years of war in the Pacific" },
      { en: "the First World War" },
      { en: "the War of 1812" },
      { en: "six years of war in Europe" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The German surrender of May 8, 1945, brought to an end six years of war in Europe.",
    },
    source: src("Canada’s History: The Second World War"),
  },
  {
    id: "hist-h-053",
    topicId: "history",
    difficulty: "hard",
    prompt: { en: "Canada’s soldiers began using the maple leaf in the…" },
    options: [{ en: "1850s" }, { en: "1910s" }, { en: "1860s" }, { en: "1940s" }],
    answerIndex: 0,
    explanation: { en: "Canada’s soldiers began using the maple leaf in the 1850s." },
    source: src("Canada’s History: The First World War"),
  },
  {
    id: "hist-h-054",
    topicId: "history",
    difficulty: "hard",
    prompt: {
      en: "The railway made it possible for immigrants to settle in the West and develop…",
    },
    options: [
      { en: "a fishing industry" },
      { en: "a thriving agricultural sector" },
      { en: "a fur monopoly" },
      { en: "a naval base" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Immigrants settled in the West before 1914 and developed a thriving agricultural sector.",
    },
    source: src("Canada’s History: Moving Westward"),
  },
  {
    id: "hist-h-055",
    topicId: "history",
    difficulty: "hard",
    prompt: { en: "Donald Smith, who drove the last spike of the CPR, was…" },
    options: [
      { en: "the prime minister of Canada" },
      { en: "an American investor" },
      { en: "a French engineer" },
      { en: "the Scottish-born director of the CPR" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Donald Smith (Lord Strathcona), the Scottish-born director of the Canadian Pacific Railway, drove the last spike.",
    },
    source: src("Canada’s History: A Railway from Sea to Sea"),
  },
];
