/**
 * Question bank chunk — part of questions.generated.ts. DO NOT EDIT BY HAND.
 */
import type { Question } from "../content";
import { src } from "./shared";

export const historyA: Question[] = [
  {
    id: "hist-e-001",
    topicId: "history",
    difficulty: "easy",
    prompt: {
      en: "When European explorers first reached Canada, what did they call the native peoples, believing they had reached the East Indies?",
    },
    options: [{ en: "Indians" }, { en: "Vikings" }, { en: "Métis" }, { en: "Inuit" }],
    answerIndex: 0,
    explanation: {
      en: "The guide says the first explorers called the native peoples Indians because they thought they had reached the East Indies.",
    },
    source: src("Canada’s History: Aboriginal Peoples"),
  },
  {
    id: "hist-e-002",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "The Huron-Wendat of the Great Lakes region lived mainly as…" },
    options: [
      { en: "fishermen and traders" },
      { en: "farmers and hunters" },
      { en: "nomadic bison followers" },
      { en: "Arctic whalers" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The Huron-Wendat of the Great Lakes region, like the Iroquois, were farmers and hunters.",
    },
    source: src("Canada’s History: Aboriginal Peoples"),
  },
  {
    id: "hist-e-003",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "The Cree and Dene of the Northwest were…" },
    options: [
      { en: "farmers and hunters" },
      { en: "nomadic bison followers" },
      { en: "hunter-gatherers" },
      { en: "coastal fishers" },
    ],
    answerIndex: 2,
    explanation: { en: "The Cree and Dene of the Northwest were hunter-gatherers." },
    source: src("Canada’s History: Aboriginal Peoples"),
  },
  {
    id: "hist-e-004",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "The Sioux were nomadic, following which herd?" },
    options: [{ en: "caribou" }, { en: "elk" }, { en: "reindeer" }, { en: "bison (buffalo)" }],
    answerIndex: 3,
    explanation: { en: "The Sioux were nomadic, following the bison (buffalo) herd." },
    source: src("Canada’s History: Aboriginal Peoples"),
  },
  {
    id: "hist-e-005",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "The Inuit lived off…" },
    options: [
      { en: "Arctic wildlife" },
      { en: "farmed crops" },
      { en: "bison herds" },
      { en: "dried salmon" },
    ],
    answerIndex: 0,
    explanation: { en: "The Inuit lived off Arctic wildlife." },
    source: src("Canada’s History: Aboriginal Peoples"),
  },
  {
    id: "hist-e-006",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "West Coast natives preserved fish by…" },
    options: [
      { en: "salting and freezing" },
      { en: "drying and smoking" },
      { en: "burying in sand" },
      { en: "boiling in oil" },
    ],
    answerIndex: 1,
    explanation: { en: "West Coast natives preserved fish by drying and smoking." },
    source: src("Canada’s History: Aboriginal Peoples"),
  },
  {
    id: "hist-e-007",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "The Vikings who reached Labrador and the island of Newfoundland came from…" },
    options: [{ en: "Norway" }, { en: "Denmark" }, { en: "Iceland" }, { en: "Sweden" }],
    answerIndex: 2,
    explanation: {
      en: "The Vikings from Iceland who colonized Greenland 1,000 years ago also reached Labrador and the island of Newfoundland.",
    },
    source: src("Canada’s History: The First Europeans"),
  },
  {
    id: "hist-e-008",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "The remains of the Viking settlement, a World Heritage site, are at…" },
    options: [
      { en: "Port-Royal" },
      { en: "St. Croix Island" },
      { en: "Fort Garry" },
      { en: "L’Anse aux Meadows" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The remains of their settlement, L’Anse aux Meadows, are a World Heritage site.",
    },
    source: src("Canada’s History: The First Europeans"),
  },
  {
    id: "hist-e-009",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "European exploration began in earnest in 1497 with the expedition of…" },
    options: [
      { en: "John Cabot" },
      { en: "Jacques Cartier" },
      { en: "Samuel de Champlain" },
      { en: "John Graves Simcoe" },
    ],
    answerIndex: 0,
    explanation: {
      en: "European exploration began in earnest in 1497 with the expedition of John Cabot.",
    },
    source: src("Canada’s History: The First Europeans"),
  },
  {
    id: "hist-e-010",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "John Cabot was the first to…" },
    options: [
      { en: "sail the St. Lawrence River" },
      { en: "draw a map of Canada’s East Coast" },
      { en: "found Québec City" },
      { en: "reach Hudson Bay" },
    ],
    answerIndex: 1,
    explanation: { en: "John Cabot was the first to draw a map of Canada’s East Coast." },
    source: src("Canada’s History: The First Europeans"),
  },
  {
    id: "hist-e-011",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "John Cabot was an immigrant to England from…" },
    options: [{ en: "France" }, { en: "Spain" }, { en: "Italy" }, { en: "Portugal" }],
    answerIndex: 2,
    explanation: {
      en: "John Cabot, an Italian immigrant to England, was the first to map Canada’s Atlantic shore.",
    },
    source: src("Canada’s History: The First Europeans"),
  },
  {
    id: "hist-e-012",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "Cabot claimed the “New Founde Land” for…" },
    options: [{ en: "France" }, { en: "Spain" }, { en: "Portugal" }, { en: "England" }],
    answerIndex: 3,
    explanation: {
      en: "Cabot set foot on Newfoundland or Cape Breton Island in 1497 and claimed the New Founde Land for England.",
    },
    source: src("Canada’s History: The First Europeans"),
  },
  {
    id: "hist-e-013",
    topicId: "history",
    difficulty: "easy",
    prompt: {
      en: "Between 1534 and 1542, Jacques Cartier made how many voyages across the Atlantic?",
    },
    options: [{ en: "three" }, { en: "one" }, { en: "five" }, { en: "seven" }],
    answerIndex: 0,
    explanation: {
      en: "Between 1534 and 1542, Jacques Cartier made three voyages across the Atlantic.",
    },
    source: src("Canada’s History: Exploring a River, Naming Canada"),
  },
  {
    id: "hist-e-014",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "Jacques Cartier claimed the land for which king?" },
    options: [
      { en: "King Henry VIII of England" },
      { en: "King Francis I of France" },
      { en: "King Charles II of England" },
      { en: "King Louis XIV of France" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Cartier made three voyages claiming the land for King Francis I of France.",
    },
    source: src("Canada’s History: Exploring a River, Naming Canada"),
  },
  {
    id: "hist-e-015",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "The Iroquoian word “kanata,” which Cartier heard from captured guides, means…" },
    options: [{ en: "river" }, { en: "mountain" }, { en: "village" }, { en: "forest" }],
    answerIndex: 2,
    explanation: {
      en: "Cartier heard two captured guides speak the Iroquoian word kanata, meaning village.",
    },
    source: src("Canada’s History: Exploring a River, Naming Canada"),
  },
  {
    id: "hist-e-016",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "Jacques Cartier was the first European to explore…" },
    options: [
      { en: "Hudson Bay" },
      { en: "the Great Lakes" },
      { en: "the Atlantic shore" },
      { en: "the St. Lawrence River" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Jacques Cartier was the first European to explore the St. Lawrence River and to set eyes on present-day Québec City and Montreal.",
    },
    source: src("Canada’s History: Exploring a River, Naming Canada"),
  },
  {
    id: "hist-e-017",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "In 1604, the first European settlement north of Florida was established by…" },
    options: [
      { en: "Pierre de Monts and Samuel de Champlain" },
      { en: "John Cabot and his crew" },
      { en: "Jacques Cartier and his men" },
      { en: "Count Frontenac and Bishop Laval" },
    ],
    answerIndex: 0,
    explanation: {
      en: "In 1604, the first European settlement north of Florida was established by French explorers Pierre de Monts and Samuel de Champlain.",
    },
    source: src("Canada’s History: Royal New France"),
  },
  {
    id: "hist-e-018",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "In 1608, Champlain built a fortress at what is now…" },
    options: [{ en: "Montreal" }, { en: "Québec City" }, { en: "Halifax" }, { en: "Toronto" }],
    answerIndex: 1,
    explanation: { en: "In 1608 Champlain built a fortress at what is now Québec City." },
    source: src("Canada’s History: Royal New France"),
  },
  {
    id: "hist-e-019",
    topicId: "history",
    difficulty: "easy",
    prompt: {
      en: "Champlain allied the colony with the Algonquin, Montagnais and Huron — historic enemies of the…",
    },
    options: [{ en: "Sioux" }, { en: "Cree" }, { en: "Iroquois" }, { en: "Inuit" }],
    answerIndex: 2,
    explanation: {
      en: "Champlain allied the colony with the Algonquin, Montagnais, and Huron, historic enemies of the Iroquois.",
    },
    source: src("Canada’s History: Royal New France"),
  },
  {
    id: "hist-e-020",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "The French and the Iroquois made peace in…" },
    options: [{ en: "1650" }, { en: "1690" }, { en: "1725" }, { en: "1701" }],
    answerIndex: 3,
    explanation: { en: "The French and the Iroquois made peace in 1701." },
    source: src("Canada’s History: Royal New France"),
  },
  {
    id: "hist-e-021",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "The fur-trade economy was driven by European demand for…" },
    options: [
      { en: "beaver pelts" },
      { en: "bison hides" },
      { en: "seal skins" },
      { en: "deer antlers" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The French and Aboriginal people collaborated in the vast fur-trade economy, driven by the demand for beaver pelts in Europe.",
    },
    source: src("Canada’s History: Royal New France"),
  },
  {
    id: "hist-e-022",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "In 1759, the British defeated the French in the Battle of…" },
    options: [
      { en: "Châteauguay" },
      { en: "Queenston Heights" },
      { en: "the Plains of Abraham at Québec City" },
      { en: "Beaver Dams" },
    ],
    answerIndex: 2,
    explanation: {
      en: "In 1759, the British defeated the French in the Battle of the Plains of Abraham at Québec City — marking the end of France’s empire in America.",
    },
    source: src("Canada’s History: Struggle for a Continent"),
  },
  {
    id: "hist-e-023",
    topicId: "history",
    difficulty: "easy",
    prompt: {
      en: "At the Battle of the Plains of Abraham, the commanders Wolfe and Montcalm both…",
    },
    options: [
      { en: "were taken prisoner" },
      { en: "retreated to Montreal" },
      { en: "were killed leading their troops" },
      { en: "signed a peace treaty" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The commanders of both armies, Brigadier James Wolfe and the Marquis de Montcalm, were killed leading their troops in battle.",
    },
    source: src("Canada’s History: Struggle for a Continent"),
  },
  {
    id: "hist-e-024",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "Following the war, Great Britain renamed the colony the…" },
    options: [
      { en: "Province of Ontario" },
      { en: "Dominion of Canada" },
      { en: "British North America" },
      { en: "Province of Quebec" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Following the war, Great Britain renamed the colony the Province of Quebec.",
    },
    source: src("Canada’s History: The Province of Quebec"),
  },
  {
    id: "hist-e-025",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "The French-speaking Catholic people were known as…" },
    options: [
      { en: "habitants or Canadiens" },
      { en: "voyageurs or coureurs" },
      { en: "Loyalists or Patriots" },
      { en: "Métis or Inuit" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The French-speaking Catholic people, known as habitants or Canadiens, strove to preserve their way of life.",
    },
    source: src("Canada’s History: The Province of Quebec"),
  },
  {
    id: "hist-e-026",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "The Quebec Act was passed in…" },
    options: [{ en: "1763" }, { en: "1774" }, { en: "1791" }, { en: "1840" }],
    answerIndex: 1,
    explanation: { en: "The British Parliament passed the Quebec Act of 1774." },
    source: src("Canada’s History: A Tradition of Accommodation"),
  },
  {
    id: "hist-e-027",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "The Quebec Act of 1774 granted…" },
    options: [
      { en: "independence to Quebec" },
      { en: "an elected assembly" },
      { en: "religious freedom for Catholics" },
      { en: "voting rights to women" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The Quebec Act allowed religious freedom for Catholics and permitted them to hold public office.",
    },
    source: src("Canada’s History: A Tradition of Accommodation"),
  },
  {
    id: "hist-e-028",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "The Quebec Act restored French civil law while maintaining…" },
    options: [
      { en: "French criminal law" },
      { en: "American common law" },
      { en: "no criminal law at all" },
      { en: "British criminal law" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The Quebec Act restored French civil law while maintaining British criminal law.",
    },
    source: src("Canada’s History: A Tradition of Accommodation"),
  },
  {
    id: "hist-e-029",
    topicId: "history",
    difficulty: "easy",
    prompt: {
      en: "In 1776, the 13 British colonies to the south of Quebec declared independence and formed…",
    },
    options: [
      { en: "the United States" },
      { en: "British North America" },
      { en: "the Dominion of Canada" },
      { en: "New France" },
    ],
    answerIndex: 0,
    explanation: {
      en: "In 1776, the 13 British colonies to the south of Quebec declared independence and formed the United States.",
    },
    source: src("Canada’s History: United Empire Loyalists"),
  },
  {
    id: "hist-e-030",
    topicId: "history",
    difficulty: "easy",
    prompt: {
      en: "More than 40,000 people loyal to the Crown fled the American Revolution to settle in Nova Scotia and Quebec. They were called…",
    },
    options: [{ en: "Patriots" }, { en: "Loyalists" }, { en: "Republicans" }, { en: "Federals" }],
    answerIndex: 1,
    explanation: {
      en: "More than 40,000 people loyal to the Crown, called Loyalists, fled the oppression of the American Revolution to settle in Nova Scotia and Quebec.",
    },
    source: src("Canada’s History: United Empire Loyalists"),
  },
  {
    id: "hist-e-031",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "Who led thousands of Loyalist Mohawk Indians into Canada?" },
    options: [
      { en: "John Graves Simcoe" },
      { en: "Charles de Salaberry" },
      { en: "Joseph Brant" },
      { en: "Chief Tecumseh" },
    ],
    answerIndex: 2,
    explanation: { en: "Joseph Brant led thousands of Loyalist Mohawk Indians into Canada." },
    source: src("Canada’s History: United Empire Loyalists"),
  },
  {
    id: "hist-e-032",
    topicId: "history",
    difficulty: "easy",
    prompt: {
      en: "About how many black Loyalists — freedmen and slaves — came north seeking a better life?",
    },
    options: [{ en: "300" }, { en: "30,000" }, { en: "300,000" }, { en: "3,000" }],
    answerIndex: 3,
    explanation: {
      en: "About 3,000 black Loyalists, freedmen and slaves, came north seeking a better life.",
    },
    source: src("Canada’s History: United Empire Loyalists"),
  },
  {
    id: "hist-e-033",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "The first representative assembly was elected in Halifax, Nova Scotia, in…" },
    options: [{ en: "1758" }, { en: "1773" }, { en: "1785" }, { en: "1791" }],
    answerIndex: 0,
    explanation: {
      en: "The first representative assembly was elected in Halifax, Nova Scotia, in 1758.",
    },
    source: src("Canada’s History: The Beginnings of Democracy"),
  },
  {
    id: "hist-e-034",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "The Constitutional Act of 1791 divided the Province of Quebec into…" },
    options: [
      { en: "Ontario and Manitoba" },
      { en: "Upper Canada and Lower Canada" },
      { en: "Nova Scotia and New Brunswick" },
      { en: "Quebec and Acadia" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The Constitutional Act of 1791 divided the Province of Quebec into Upper Canada (later Ontario) and Lower Canada (later Quebec).",
    },
    source: src("Canada’s History: The Beginnings of Democracy"),
  },
  {
    id: "hist-e-035",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "Upper Canada was mainly…" },
    options: [
      { en: "Catholic and French-speaking" },
      { en: "Métis and bilingual" },
      { en: "Loyalist, Protestant and English-speaking" },
      { en: "Aboriginal and nomadic" },
    ],
    answerIndex: 2,
    explanation: { en: "Upper Canada was mainly Loyalist, Protestant and English-speaking." },
    source: src("Canada’s History: The Beginnings of Democracy"),
  },
  {
    id: "hist-e-036",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "Lower Canada was heavily…" },
    options: [
      { en: "Protestant and English-speaking" },
      { en: "Loyalist and Dutch" },
      { en: "American and republican" },
      { en: "Catholic and French-speaking" },
    ],
    answerIndex: 3,
    explanation: { en: "Lower Canada was heavily Catholic and French-speaking." },
    source: src("Canada’s History: The Beginnings of Democracy"),
  },
  {
    id: "hist-e-037",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "Upper Canada later became…" },
    options: [{ en: "Ontario" }, { en: "Quebec" }, { en: "Manitoba" }, { en: "New Brunswick" }],
    answerIndex: 0,
    explanation: { en: "Upper Canada later became Ontario." },
    source: src("Canada’s History: The Beginnings of Democracy"),
  },
  {
    id: "hist-e-038",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "The Constitutional Act of 1791 granted the Canadas, for the first time…" },
    options: [
      { en: "responsible government" },
      { en: "legislative assemblies elected by the people" },
      { en: "the right to trade freely" },
      { en: "separation from Britain" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The Act granted to the Canadas, for the first time, legislative assemblies elected by the people.",
    },
    source: src("Canada’s History: The Beginnings of Democracy"),
  },
  {
    id: "hist-e-039",
    topicId: "history",
    difficulty: "easy",
    prompt: {
      en: "In 1793, Upper Canada, led by John Graves Simcoe, became the first province in the Empire to…",
    },
    options: [
      { en: "abolish the fur trade" },
      { en: "grant women the vote" },
      { en: "move toward abolition of slavery" },
      { en: "build a railway" },
    ],
    answerIndex: 2,
    explanation: {
      en: "In 1793, Upper Canada, led by Lieutenant Governor John Graves Simcoe, became the first province in the Empire to move toward abolition.",
    },
    source: src("Canada’s History: Abolition of Slavery"),
  },
  {
    id: "hist-e-040",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "In 1807, the British Parliament prohibited…" },
    options: [
      { en: "the fur trade" },
      { en: "immigration to Canada" },
      { en: "French civil law" },
      { en: "the buying and selling of slaves" },
    ],
    answerIndex: 3,
    explanation: {
      en: "In 1807, the British Parliament prohibited the buying and selling of slaves.",
    },
    source: src("Canada’s History: Abolition of Slavery"),
  },
  {
    id: "hist-e-041",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "In 1833, Britain…" },
    options: [
      { en: "abolished slavery throughout the Empire" },
      { en: "granted responsible government" },
      { en: "founded the NWMP" },
      { en: "built the Rideau Canal" },
    ],
    answerIndex: 0,
    explanation: { en: "In 1833 Britain abolished slavery throughout the Empire." },
    source: src("Canada’s History: Abolition of Slavery"),
  },
  {
    id: "hist-e-042",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "The Montreal Stock Exchange opened in…" },
    options: [{ en: "1791" }, { en: "1832" }, { en: "1867" }, { en: "1905" }],
    answerIndex: 1,
    explanation: { en: "The Montreal Stock Exchange opened in 1832." },
    source: src("Canada’s History: A Growing Economy"),
  },
  {
    id: "hist-e-043",
    topicId: "history",
    difficulty: "easy",
    prompt: {
      en: "Believing it would be easy to conquer Canada, the United States launched its invasion in…",
    },
    options: [{ en: "June 1805" }, { en: "July 1814" }, { en: "June 1812" }, { en: "August 1815" }],
    answerIndex: 2,
    explanation: {
      en: "Believing it would be easy to conquer Canada, the United States launched an invasion in June 1812.",
    },
    source: src("Canada’s History: The War of 1812: The Fight for Canada"),
  },
  {
    id: "hist-e-044",
    topicId: "history",
    difficulty: "easy",
    prompt: {
      en: "Major-General Sir Isaac Brock captured Detroit but was killed while defending against an American attack at…",
    },
    options: [
      { en: "Châteauguay" },
      { en: "Beaver Dams" },
      { en: "Washington, D.C." },
      { en: "Queenston Heights, near Niagara Falls" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Major-General Sir Isaac Brock captured Detroit but was killed while defending against an American attack at Queenston Heights, near Niagara Falls.",
    },
    source: src("Canada’s History: The War of 1812: The Fight for Canada"),
  },
  {
    id: "hist-e-045",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "Chief Tecumseh led the…" },
    options: [{ en: "Shawnee" }, { en: "Mohawk" }, { en: "Huron" }, { en: "Cree" }],
    answerIndex: 0,
    explanation: {
      en: "Canadian volunteers and First Nations, including Shawnee led by Chief Tecumseh, supported British soldiers in Canada’s defence.",
    },
    source: src("Canada’s History: The War of 1812: The Fight for Canada"),
  },
  {
    id: "hist-e-046",
    topicId: "history",
    difficulty: "easy",
    prompt: {
      en: "In 1813 at Châteauguay, south of Montreal, Charles de Salaberry and 460 soldiers turned back…",
    },
    options: [
      { en: "400 American invaders" },
      { en: "4,000 American invaders" },
      { en: "40,000 American invaders" },
      { en: "400,000 American invaders" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Lieutenant-Colonel Charles de Salaberry and 460 soldiers turned back 4,000 American invaders at Châteauguay.",
    },
    source: src("Canada’s History: The War of 1812: The Fight for Canada"),
  },
  {
    id: "hist-e-047",
    topicId: "history",
    difficulty: "easy",
    prompt: {
      en: "In 1813, the Americans burned Government House and the Parliament Buildings in…",
    },
    options: [
      { en: "Kingston" },
      { en: "Halifax" },
      { en: "York (now Toronto)" },
      { en: "Québec City" },
    ],
    answerIndex: 2,
    explanation: {
      en: "In 1813 the Americans burned Government House and the Parliament Buildings in York (now Toronto).",
    },
    source: src("Canada’s History: The War of 1812: The Fight for Canada"),
  },
  {
    id: "hist-e-048",
    topicId: "history",
    difficulty: "easy",
    prompt: {
      en: "In retaliation in 1814, Major-General Robert Ross led an expedition that burned…",
    },
    options: [
      { en: "the Parliament Buildings in York" },
      { en: "Fort Detroit" },
      { en: "the Citadel at Halifax" },
      { en: "the White House and other public buildings in Washington, D.C." },
    ],
    answerIndex: 3,
    explanation: {
      en: "In retaliation in 1814, Major-General Robert Ross led an expedition from Nova Scotia that burned down the White House and other public buildings in Washington, D.C.",
    },
    source: src("Canada’s History: The War of 1812: The Fight for Canada"),
  },
  {
    id: "hist-e-049",
    topicId: "history",
    difficulty: "easy",
    prompt: {
      en: "In 1813, Laura Secord made a dangerous 19-mile (30 km) journey on foot to warn…",
    },
    options: [
      { en: "Lieutenant James FitzGibbon of a planned American attack" },
      { en: "General Brock of the invasion of Detroit" },
      { en: "Charles de Salaberry at Châteauguay" },
      { en: "the Duke of Wellington at Waterloo" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Laura Secord made a dangerous 19 mile (30 km) journey on foot to warn Lieutenant James FitzGibbon of a planned American attack.",
    },
    source: src("Canada’s History: The War of 1812: The Fight for Canada"),
  },
  {
    id: "hist-e-050",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "Armed rebellions occurred in 1837–38 in the area outside Montreal and in…" },
    options: [{ en: "Halifax" }, { en: "Toronto" }, { en: "Québec City" }, { en: "Kingston" }],
    answerIndex: 1,
    explanation: {
      en: "Armed rebellions occurred in 1837–38 in the area outside Montreal and in Toronto.",
    },
    source: src("Canada’s History: Rebellions of 1837–38"),
  },
  {
    id: "hist-e-051",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "Lord Durham recommended that Upper and Lower Canada be…" },
    options: [
      { en: "granted independence" },
      { en: "returned to France" },
      { en: "merged and given responsible government" },
      { en: "divided into four provinces" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Lord Durham recommended that Upper and Lower Canada be merged and given responsible government.",
    },
    source: src("Canada’s History: Rebellions of 1837–38"),
  },
  {
    id: "hist-e-052",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "Responsible government means that the ministers of the Crown must have…" },
    options: [
      { en: "the King’s personal approval" },
      { en: "lifetime appointments" },
      { en: "military backing" },
      { en: "the support of a majority of the elected representatives" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Responsible government meant that the ministers of the Crown must have the support of a majority of the elected representatives in order to govern.",
    },
    source: src("Canada’s History: Rebellions of 1837–38"),
  },
  {
    id: "hist-e-053",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "In 1840, Upper and Lower Canada were united as the…" },
    options: [
      { en: "Province of Canada" },
      { en: "Dominion of Canada" },
      { en: "Republic of Canada" },
      { en: "Province of Quebec" },
    ],
    answerIndex: 0,
    explanation: { en: "In 1840, Upper and Lower Canada were united as the Province of Canada." },
    source: src("Canada’s History: Responsible Government"),
  },
  {
    id: "hist-e-054",
    topicId: "history",
    difficulty: "easy",
    prompt: {
      en: "The first British North American colony to attain full responsible government was…",
    },
    options: [
      { en: "Upper Canada" },
      { en: "Nova Scotia, in 1847–48" },
      { en: "New Brunswick" },
      { en: "Prince Edward Island" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The first British North American colony to attain full responsible government was Nova Scotia in 1847–48.",
    },
    source: src("Canada’s History: Responsible Government"),
  },
  {
    id: "hist-e-055",
    topicId: "history",
    difficulty: "easy",
    prompt: {
      en: "Sir Louis-Hippolyte La Fontaine became the first leader of a responsible government in the Canadas in…",
    },
    options: [{ en: "1837" }, { en: "1840" }, { en: "1849" }, { en: "1867" }],
    answerIndex: 2,
    explanation: {
      en: "La Fontaine became the first leader of a responsible government in the Canadas in 1849.",
    },
    source: src("Canada’s History: Responsible Government"),
  },
  {
    id: "hist-e-056",
    topicId: "history",
    difficulty: "easy",
    prompt: {
      en: "The men who worked from 1864 to 1867 to establish the new country are known as…",
    },
    options: [
      { en: "the Voyageurs" },
      { en: "the Reformers" },
      { en: "the Patriots" },
      { en: "the Fathers of Confederation" },
    ],
    answerIndex: 3,
    explanation: {
      en: "From 1864 to 1867, representatives worked together to establish a new country. These men are known as the Fathers of Confederation.",
    },
    source: src("Canada’s History: Confederation"),
  },
  {
    id: "hist-e-057",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "Confederation created two levels of government:…" },
    options: [
      { en: "federal and provincial" },
      { en: "British and colonial" },
      { en: "civil and military" },
      { en: "upper and lower" },
    ],
    answerIndex: 0,
    explanation: { en: "They created two levels of government: federal and provincial." },
    source: src("Canada’s History: Confederation"),
  },
  {
    id: "hist-e-058",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "The British North America Act was passed in…" },
    options: [{ en: "1840" }, { en: "1867" }, { en: "1871" }, { en: "1982" }],
    answerIndex: 1,
    explanation: { en: "The British Parliament passed the British North America Act in 1867." },
    source: src("Canada’s History: Confederation"),
  },
  {
    id: "hist-e-059",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "The Dominion of Canada was officially born on…" },
    options: [
      { en: "July 4, 1776" },
      { en: "May 8, 1945" },
      { en: "July 1, 1867" },
      { en: "November 11, 1918" },
    ],
    answerIndex: 2,
    explanation: { en: "The Dominion of Canada was officially born on July 1, 1867." },
    source: src("Canada’s History: Confederation"),
  },
  {
    id: "hist-e-060",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "Until 1982, July 1 was celebrated as…" },
    options: [
      { en: "Empire Day" },
      { en: "Victoria Day" },
      { en: "Vimy Day" },
      { en: "Dominion Day" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Until 1982, July 1 was celebrated as Dominion Day. Today it is officially known as Canada Day.",
    },
    source: src("Canada’s History: Confederation"),
  },
  {
    id: "hist-e-061",
    topicId: "history",
    difficulty: "easy",
    prompt: {
      en: "Each province would elect its own legislature and have control of such areas as…",
    },
    options: [
      { en: "education and health" },
      { en: "defence and currency" },
      { en: "foreign affairs and trade" },
      { en: "immigration and citizenship" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Each province would elect its own legislature and have control of such areas as education and health.",
    },
    source: src("Canada’s History: Confederation"),
  },
  {
    id: "hist-e-062",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "The four original provinces of 1867 were Ontario, Quebec, New Brunswick and…" },
    options: [
      { en: "Manitoba" },
      { en: "Nova Scotia" },
      { en: "British Columbia" },
      { en: "Prince Edward Island" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Ontario and Quebec, together with New Brunswick and Nova Scotia, formed the new country called the Dominion of Canada.",
    },
    source: src("Canada’s History: Confederation"),
  },
  {
    id: "hist-e-063",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "Manitoba and the Northwest Territories joined Confederation in…" },
    options: [{ en: "1867" }, { en: "1871" }, { en: "1870" }, { en: "1873" }],
    answerIndex: 2,
    explanation: { en: "1870 — Manitoba, Northwest Territories (N.W.T.)." },
    source: src("Canada’s History: Expansion of the Dominion"),
  },
  {
    id: "hist-e-064",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "British Columbia joined Confederation in…" },
    options: [{ en: "1867" }, { en: "1870" }, { en: "1873" }, { en: "1871" }],
    answerIndex: 3,
    explanation: { en: "1871 — British Columbia." },
    source: src("Canada’s History: Expansion of the Dominion"),
  },
  {
    id: "hist-e-065",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "Prince Edward Island joined Confederation in…" },
    options: [{ en: "1873" }, { en: "1870" }, { en: "1871" }, { en: "1880" }],
    answerIndex: 0,
    explanation: { en: "1873 — Prince Edward Island." },
    source: src("Canada’s History: Expansion of the Dominion"),
  },
  {
    id: "hist-e-066",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "Alberta and Saskatchewan became provinces in…" },
    options: [{ en: "1898" }, { en: "1905" }, { en: "1949" }, { en: "1999" }],
    answerIndex: 1,
    explanation: { en: "1905 — Alberta, Saskatchewan." },
    source: src("Canada’s History: Expansion of the Dominion"),
  },
  {
    id: "hist-e-067",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "Newfoundland and Labrador joined Canada in…" },
    options: [{ en: "1905" }, { en: "1873" }, { en: "1949" }, { en: "1999" }],
    answerIndex: 2,
    explanation: { en: "1949 — Newfoundland and Labrador." },
    source: src("Canada’s History: Expansion of the Dominion"),
  },
  {
    id: "hist-e-068",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "Nunavut was created in…" },
    options: [{ en: "1949" }, { en: "1905" }, { en: "1870" }, { en: "1999" }],
    answerIndex: 3,
    explanation: { en: "1999 — Nunavut." },
    source: src("Canada’s History: Expansion of the Dominion"),
  },
  {
    id: "hist-e-069",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "Sir John A. Macdonald became Canada’s first Prime Minister in…" },
    options: [{ en: "1867" }, { en: "1873" }, { en: "1885" }, { en: "1905" }],
    answerIndex: 0,
    explanation: {
      en: "In 1867, Sir John Alexander Macdonald, a Father of Confederation, became Canada’s first Prime Minister.",
    },
    source: src("Canada’s History: Canada’s First Prime Minister"),
  },
  {
    id: "hist-e-070",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "Sir John A. Macdonald was born in…" },
    options: [{ en: "England" }, { en: "Scotland" }, { en: "Ireland" }, { en: "Upper Canada" }],
    answerIndex: 1,
    explanation: {
      en: "Born in Scotland on January 11, 1815, he came to Upper Canada as a child.",
    },
    source: src("Canada’s History: Canada’s First Prime Minister"),
  },
  {
    id: "hist-e-071",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "Sir John A. Macdonald’s portrait is on the…" },
    options: [{ en: "$5 bill" }, { en: "$20 bill" }, { en: "$10 bill" }, { en: "$50 bill" }],
    answerIndex: 2,
    explanation: { en: "His portrait is on the $10 bill." },
    source: src("Canada’s History: Canada’s First Prime Minister"),
  },
  {
    id: "hist-e-072",
    topicId: "history",
    difficulty: "easy",
    prompt: {
      en: "When Canada took over the northwest from the Hudson’s Bay Company in 1869, about how many Métis of the Red River were not consulted?",
    },
    options: [{ en: "1,200" }, { en: "120,000" }, { en: "120" }, { en: "12,000" }],
    answerIndex: 3,
    explanation: {
      en: "When Canada took over the vast northwest region from the Hudson’s Bay Company in 1869, the 12,000 Métis of the Red River were not consulted.",
    },
    source: src("Canada’s History: Challenge in the West"),
  },
  {
    id: "hist-e-073",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "Louis Riel led an armed uprising and seized…" },
    options: [
      { en: "Fort Garry, the territorial capital" },
      { en: "Fort Edmonton" },
      { en: "Fort Calgary" },
      { en: "Fort Victoria" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Louis Riel led an armed uprising and seized Fort Garry, the territorial capital.",
    },
    source: src("Canada’s History: Challenge in the West"),
  },
  {
    id: "hist-e-074",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "The second rebellion of 1885 in present-day Saskatchewan led to Riel’s…" },
    options: [
      { en: "election to Parliament" },
      { en: "trial and execution for high treason" },
      { en: "appointment as governor" },
      { en: "exile to France" },
    ],
    answerIndex: 1,
    explanation: {
      en: "A second rebellion in 1885 in present-day Saskatchewan led to Riel’s trial and execution for high treason.",
    },
    source: src("Canada’s History: Challenge in the West"),
  },
  {
    id: "hist-e-075",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "Riel is seen by many as a hero, a defender of Métis rights and the…" },
    options: [
      { en: "founder of the NWMP" },
      { en: "first premier of Manitoba" },
      { en: "father of Manitoba" },
      { en: "builder of the CPR" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Riel is seen by many as a hero, a defender of Métis rights and the father of Manitoba.",
    },
    source: src("Canada’s History: Challenge in the West"),
  },
  {
    id: "hist-e-076",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "Prime Minister Macdonald established the North West Mounted Police in…" },
    options: [{ en: "1867" }, { en: "1870" }, { en: "1885" }, { en: "1873" }],
    answerIndex: 3,
    explanation: {
      en: "After the first Métis uprising, Prime Minister Macdonald established the North West Mounted Police (NWMP) in 1873.",
    },
    source: src("Canada’s History: Challenge in the West"),
  },
  {
    id: "hist-e-077",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "Today, the RCMP — the “Mounties” — are…" },
    options: [
      { en: "the national police force" },
      { en: "a provincial militia" },
      { en: "a railway security service" },
      { en: "a border patrol" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Today, the Royal Canadian Mounted Police (RCMP or “the Mounties”) are the national police force.",
    },
    source: src("Canada’s History: Challenge in the West"),
  },
  {
    id: "hist-e-078",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "British Columbia joined Canada in 1871 after Ottawa promised to build…" },
    options: [
      { en: "a canal to the Pacific" },
      { en: "a railway to the West Coast" },
      { en: "a highway to the West" },
      { en: "a telegraph to Asia" },
    ],
    answerIndex: 1,
    explanation: {
      en: "British Columbia joined Canada in 1871 after Ottawa promised to build a railway to the West Coast.",
    },
    source: src("Canada’s History: A Railway from Sea to Sea"),
  },
  {
    id: "hist-e-079",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "The last spike of the Canadian Pacific Railway was driven on…" },
    options: [
      { en: "July 1, 1867" },
      { en: "May 8, 1945" },
      { en: "November 7, 1885" },
      { en: "November 11, 1918" },
    ],
    answerIndex: 2,
    explanation: {
      en: "On November 7, 1885, Donald Smith (Lord Strathcona) drove the last spike.",
    },
    source: src("Canada’s History: A Railway from Sea to Sea"),
  },
  {
    id: "hist-e-080",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "Who drove the last spike of the CPR?" },
    options: [
      { en: "Sir John A. Macdonald" },
      { en: "Sir Wilfrid Laurier" },
      { en: "Gabriel Dumont" },
      { en: "Donald Smith (Lord Strathcona), the CPR director" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Donald Smith (Lord Strathcona), the Scottish-born director of the Canadian Pacific Railway (CPR), drove the last spike.",
    },
    source: src("Canada’s History: A Railway from Sea to Sea"),
  },
  {
    id: "hist-e-081",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "The CPR was built by…" },
    options: [
      { en: "both European and Chinese labour" },
      { en: "British soldiers only" },
      { en: "American engineers only" },
      { en: "prisoners of war" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The project was financed by British and American investors and built by both European and Chinese labour.",
    },
    source: src("Canada’s History: A Railway from Sea to Sea"),
  },
  {
    id: "hist-e-082",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "In 2006, the Government of Canada apologized for the…" },
    options: [
      { en: "Chinese Exclusion Act" },
      { en: "Head Tax, a race-based entry fee" },
      { en: "Komagata Maru incident" },
      { en: "Japanese internment" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Afterwards the Chinese were subject to discrimination, including the Head Tax, a race-based entry fee. The Government of Canada apologized in 2006 for this discriminatory policy.",
    },
    source: src("Canada’s History: A Railway from Sea to Sea"),
  },
  {
    id: "hist-e-083",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "Sir Wilfrid Laurier became the first…" },
    options: [
      { en: "prime minister of Canada" },
      { en: "Liberal prime minister" },
      { en: "French-Canadian prime minister since Confederation" },
      { en: "prime minister born in Quebec" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Sir Wilfrid Laurier became the first French-Canadian prime minister since Confederation and encouraged immigration to the West.",
    },
    source: src("Canada’s History: Moving Westward"),
  },
  {
    id: "hist-e-084",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "Sir Wilfrid Laurier’s portrait is on the…" },
    options: [{ en: "$10 bill" }, { en: "$20 bill" }, { en: "$50 bill" }, { en: "$5 bill" }],
    answerIndex: 3,
    explanation: { en: "His portrait is on the $5 bill." },
    source: src("Canada’s History: Moving Westward"),
  },
  {
    id: "hist-e-085",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "The Canadian Corps captured Vimy Ridge in…" },
    options: [
      { en: "April 1917" },
      { en: "August 1918" },
      { en: "November 1918" },
      { en: "June 1944" },
    ],
    answerIndex: 0,
    explanation: { en: "The Canadian Corps captured Vimy Ridge in April 1917." },
    source: src("Canada’s History: The First World War"),
  },
  {
    id: "hist-e-086",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "April 9 is celebrated as…" },
    options: [
      { en: "Remembrance Day" },
      { en: "Vimy Day" },
      { en: "Dominion Day" },
      { en: "Canada Day" },
    ],
    answerIndex: 1,
    explanation: { en: "April 9 is celebrated as Vimy Day." },
    source: src("Canada’s History: The First World War"),
  },
  {
    id: "hist-e-087",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "In 1916, Manitoba became the first province to…" },
    options: [
      { en: "abolish slavery" },
      { en: "join Confederation" },
      { en: "grant voting rights to women" },
      { en: "build a railway" },
    ],
    answerIndex: 2,
    explanation: {
      en: "In 1916, Manitoba became the first province to grant voting rights to women.",
    },
    source: src("Canada’s History: Women Get the Vote"),
  },
  {
    id: "hist-e-088",
    topicId: "history",
    difficulty: "easy",
    prompt: { en: "Each year, Canadians observe Remembrance Day on…" },
    options: [{ en: "July 1" }, { en: "April 9" }, { en: "June 6" }, { en: "November 11" }],
    answerIndex: 3,
    explanation: {
      en: "Canadians remember the sacrifices of veterans each year on November 11: Remembrance Day.",
    },
    source: src("Canada’s History: Remembrance Day"),
  },
  {
    id: "hist-m-001",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "Large numbers of Aboriginals died of…" },
    options: [
      { en: "European diseases to which they lacked immunity" },
      { en: "starvation during droughts" },
      { en: "wars with the Vikings" },
      { en: "poisoned trade goods" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Large numbers of Aboriginals died of European diseases to which they lacked immunity.",
    },
    source: src("Canada’s History: Aboriginal Peoples"),
  },
  {
    id: "hist-m-002",
    topicId: "history",
    difficulty: "medium",
    prompt: {
      en: "In the first 200 years of coexistence, Aboriginals and Europeans formed strong…",
    },
    options: [
      { en: "written treaties only" },
      { en: "economic, religious and military bonds" },
      { en: "trade unions" },
      { en: "military alliances only" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Aboriginals and Europeans formed strong economic, religious and military bonds in the first 200 years of coexistence.",
    },
    source: src("Canada’s History: Aboriginal Peoples"),
  },
  {
    id: "hist-m-003",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "Warfare was common among Aboriginal groups as they competed for…" },
    options: [
      { en: "European weapons" },
      { en: "fishing licences" },
      { en: "land, resources and prestige" },
      { en: "railway routes" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Warfare was common among Aboriginal groups as they competed for land, resources and prestige.",
    },
    source: src("Canada’s History: Aboriginal Peoples"),
  },
  {
    id: "hist-m-004",
    topicId: "history",
    difficulty: "medium",
    prompt: {
      en: "Although Cabot claimed land for England in 1497, English settlement did not begin until…",
    },
    options: [{ en: "1500" }, { en: "1550" }, { en: "1600" }, { en: "1610" }],
    answerIndex: 3,
    explanation: { en: "English settlement did not begin until 1610." },
    source: src("Canada’s History: The First Europeans"),
  },
  {
    id: "hist-m-005",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "By which decade did the name “Canada” begin appearing on maps?" },
    options: [{ en: "1550s" }, { en: "1490s" }, { en: "1600s" }, { en: "1700s" }],
    answerIndex: 0,
    explanation: { en: "By the 1550s, the name of Canada began appearing on maps." },
    source: src("Canada’s History: Exploring a River, Naming Canada"),
  },
  {
    id: "hist-m-006",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "After St. Croix Island, the 1604 French settlement moved to…" },
    options: [
      { en: "Québec City" },
      { en: "Port-Royal, in Acadia (present-day Nova Scotia)" },
      { en: "Montreal" },
      { en: "Louisbourg" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The 1604 settlement was first on St. Croix Island, then at Port-Royal, in Acadia (present-day Nova Scotia).",
    },
    source: src("Canada’s History: Royal New France"),
  },
  {
    id: "hist-m-007",
    topicId: "history",
    difficulty: "medium",
    prompt: {
      en: "In 1690, Count Frontenac refused to surrender Quebec to the English, saying his only reply would be…",
    },
    options: [
      { en: "a signed treaty" },
      { en: "a gift of furs" },
      { en: "from the mouths of my cannons" },
      { en: "a duel at dawn" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Count Frontenac refused to surrender Quebec to the English in 1690, saying: My only reply will be from the mouths of my cannons!",
    },
    source: src("Canada’s History: Royal New France"),
  },
  {
    id: "hist-m-008",
    topicId: "history",
    difficulty: "medium",
    prompt: {
      en: "Pierre Le Moyne, Sieur d’Iberville, won victories over the English stretching from…",
    },
    options: [
      { en: "Hudson Bay to the Gulf of Mexico" },
      { en: "Labrador to Florida" },
      { en: "Newfoundland to Jamaica" },
      { en: "James Bay in the north to Nevis in the Caribbean" },
    ],
    answerIndex: 3,
    explanation: {
      en: "D’Iberville won many victories over the English, from James Bay in the north to Nevis in the Caribbean, in the late 17th and early 18th centuries.",
    },
    source: src("Canada’s History: Royal New France"),
  },
  {
    id: "hist-m-009",
    topicId: "history",
    difficulty: "medium",
    prompt: {
      en: "Sir Guy Carleton (Lord Dorchester) defeated an American military invasion of Quebec in…",
    },
    options: [{ en: "1775" }, { en: "1759" }, { en: "1812" }, { en: "1837" }],
    answerIndex: 0,
    explanation: {
      en: "Sir Guy Carleton, as Governor of Quebec, defeated an American military invasion of Quebec in 1775.",
    },
    source: src("Canada’s History: Royal New France"),
  },
  {
    id: "hist-m-010",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "Carleton supervised the Loyalist migration to Nova Scotia and Quebec in…" },
    options: [{ en: "1776–77" }, { en: "1782–83" }, { en: "1791–92" }, { en: "1812–14" }],
    answerIndex: 1,
    explanation: {
      en: "Carleton supervised the Loyalist migration to Nova Scotia and Quebec in 1782–83.",
    },
    source: src("Canada’s History: Royal New France"),
  },
  {
    id: "hist-m-011",
    topicId: "history",
    difficulty: "medium",
    prompt: {
      en: "In 1670, King Charles II granted the Hudson’s Bay Company exclusive trading rights over…",
    },
    options: [
      { en: "all of New France" },
      { en: "the St. Lawrence River valley" },
      { en: "the watershed draining into Hudson Bay" },
      { en: "the Atlantic fisheries" },
    ],
    answerIndex: 2,
    explanation: {
      en: "In 1670, King Charles II of England granted the Hudson’s Bay Company exclusive trading rights over the watershed draining into Hudson Bay.",
    },
    source: src("Canada’s History: Struggle for a Continent"),
  },
  {
    id: "hist-m-012",
    topicId: "history",
    difficulty: "medium",
    prompt: {
      en: "The skilled and courageous men who travelled by canoe in the fur trade were called…",
    },
    options: [
      { en: "habitants and Canadiens" },
      { en: "rangers and scouts" },
      { en: "sailors and stevedores" },
      { en: "voyageurs and coureurs des bois" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The skilled and courageous men who travelled by canoe were called voyageurs and coureurs des bois.",
    },
    source: src("Canada’s History: Struggle for a Continent"),
  },
  {
    id: "hist-m-013",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "The Quebec Act is described in the guide as…" },
    options: [
      { en: "one of the constitutional foundations of Canada" },
      { en: "a temporary wartime measure" },
      { en: "a trade agreement with France" },
      { en: "a military alliance" },
    ],
    answerIndex: 0,
    explanation: { en: "The Quebec Act is one of the constitutional foundations of Canada." },
    source: src("Canada’s History: A Tradition of Accommodation"),
  },
  {
    id: "hist-m-014",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "Unlike in Britain at the time, the Quebec Act permitted Catholics to…" },
    options: [
      { en: "vote in British elections" },
      { en: "hold public office" },
      { en: "own land in England" },
      { en: "serve in the Royal Navy" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The Quebec Act permitted Catholics to hold public office, a practice not then allowed in Britain.",
    },
    source: src("Canada’s History: A Tradition of Accommodation"),
  },
  {
    id: "hist-m-015",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "The Loyalists came from varied origins, including…" },
    options: [
      { en: "only English and Scottish" },
      { en: "only French and Irish" },
      { en: "Dutch, German, British, Scandinavian and Aboriginal" },
      { en: "only American and Spanish" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The Loyalists came from Dutch, German, British, Scandinavian, Aboriginal and other origins.",
    },
    source: src("Canada’s History: United Empire Loyalists"),
  },
  {
    id: "hist-m-016",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "In 1792, some black Nova Scotians moved on to establish…" },
    options: [
      { en: "Halifax, Nova Scotia" },
      { en: "York, Upper Canada" },
      { en: "Fredericton, New Brunswick" },
      { en: "Freetown, Sierra Leone" },
    ],
    answerIndex: 3,
    explanation: {
      en: "In 1792, some black Nova Scotians moved on to establish Freetown, Sierra Leone (West Africa).",
    },
    source: src("Canada’s History: United Empire Loyalists"),
  },
  {
    id: "hist-m-017",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "Freetown, Sierra Leone, was established as…" },
    options: [
      { en: "a new British colony for freed slaves" },
      { en: "a French trading post" },
      { en: "an American naval base" },
      { en: "a Hudson’s Bay Company fort" },
    ],
    answerIndex: 0,
    explanation: { en: "Freetown was a new British colony for freed slaves." },
    source: src("Canada’s History: United Empire Loyalists"),
  },
  {
    id: "hist-m-018",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "The Atlantic colonies and the two Canadas were known collectively as…" },
    options: [
      { en: "New France" },
      { en: "British North America" },
      { en: "the Dominion of Canada" },
      { en: "Upper Canada" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The Atlantic colonies and the two Canadas were known collectively as British North America.",
    },
    source: src("Canada’s History: The Beginnings of Democracy"),
  },
  {
    id: "hist-m-019",
    topicId: "history",
    difficulty: "medium",
    prompt: {
      en: "On January 21, 1793, the first elected Assembly of Lower Canada debated whether to…",
    },
    options: [
      { en: "abolish slavery" },
      { en: "join the United States" },
      { en: "use both French and English" },
      { en: "build the Rideau Canal" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The first elected Assembly of Lower Canada debated whether to use both French and English on January 21, 1793.",
    },
    source: src("Canada’s History: The Beginnings of Democracy"),
  },
  {
    id: "hist-m-020",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "The first movement to abolish the transatlantic slave trade emerged in…" },
    options: [
      { en: "the French Assembly in 1789" },
      { en: "the US Congress in 1800" },
      { en: "the United Nations in 1945" },
      { en: "the British Parliament in the late 1700s" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The first movement to abolish the transatlantic slave trade emerged in the British Parliament in the late 1700s.",
    },
    source: src("Canada’s History: Abolition of Slavery"),
  },
  {
    id: "hist-m-021",
    topicId: "history",
    difficulty: "medium",
    prompt: {
      en: "Thousands of slaves escaped from the United States, “followed the North Star,” and settled in Canada via the…",
    },
    options: [
      { en: "Underground Railroad, a Christian anti-slavery network" },
      { en: "Canadian Pacific Railway" },
      { en: "St. Lawrence Seaway" },
      { en: "Rideau Canal" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Thousands of slaves escaped from the United States, followed the North Star and settled in Canada via the Underground Railroad, a Christian anti-slavery network.",
    },
    source: src("Canada’s History: Abolition of Slavery"),
  },
  {
    id: "hist-m-022",
    topicId: "history",
    difficulty: "medium",
    prompt: { en: "Mary Ann Shadd Cary became the first woman publisher in Canada in…" },
    options: [{ en: "1833" }, { en: "1853" }, { en: "1918" }, { en: "1921" }],
    answerIndex: 1,
    explanation: {
      en: "In 1853 Mary Ann Shadd Cary became the first woman publisher in Canada, helping to found and edit The Provincial Freeman.",
    },
    source: src("Canada’s History: Abolition of Slavery"),
  },
];
