/**
 * Question bank chunk — part of questions.generated.ts. DO NOT EDIT BY HAND.
 */
import type { Question } from "../content";
import { src } from "./shared";

export const peopleB: Question[] = [
  {
    id: "ppl-m-021",
    topicId: "people",
    difficulty: "medium",
    prompt: {
      en: "Joseph Howe worked in parallel with La Fontaine and Baldwin toward responsible government in which colony?",
    },
    options: [
      { en: "Nova Scotia" },
      { en: "New Brunswick" },
      { en: "Prince Edward Island" },
      { en: "Newfoundland" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Reformers such as Sir Louis-Hippolyte La Fontaine and Robert Baldwin, in parallel with Joseph Howe in Nova Scotia, worked with British governors toward responsible government.",
    },
    source: src("Canada's History: Responsible Government"),
  },
  {
    id: "ppl-m-022",
    topicId: "people",
    difficulty: "medium",
    prompt: { en: "Which governor of United Canada introduced responsible government in 1848–49?" },
    options: [
      { en: "Lord Durham" },
      { en: "Lord Grey" },
      { en: "Sir Guy Carleton" },
      { en: "Lord Elgin" },
    ],
    answerIndex: 3,
    explanation: {
      en: "In 1848–49 the governor of United Canada, Lord Elgin, with encouragement from London, introduced responsible government.",
    },
    source: src("Canada's History: Responsible Government"),
  },
  {
    id: "ppl-m-023",
    topicId: "people",
    difficulty: "medium",
    prompt: { en: "Which two reformers of the 1830s later became Fathers of Confederation?" },
    options: [
      { en: "Louis Riel and Gabriel Dumont" },
      { en: "Joseph Howe and John Graves Simcoe" },
      { en: "Sir Étienne-Paschal Taché and Sir George-Étienne Cartier" },
      { en: "Robert Baldwin and Lord Elgin" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Some reformers, including Sir Étienne-Paschal Taché and Sir George-Étienne Cartier, later became Fathers of Confederation.",
    },
    source: src("Canada's History: Rebellions of 1837–38"),
  },
  {
    id: "ppl-m-024",
    topicId: "people",
    difficulty: "medium",
    prompt: {
      en: "Cartier led Quebec into Confederation and helped negotiate the entry of which regions into Canada?",
    },
    options: [
      { en: "Alberta, Saskatchewan and the Yukon" },
      { en: "The Northwest Territories, Manitoba and British Columbia" },
      { en: "Prince Edward Island and Newfoundland" },
      { en: "The Arctic Islands and Nunavut" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Cartier led Quebec into Confederation and helped negotiate the entry of the Northwest Territories, Manitoba and British Columbia into Canada.",
    },
    source: src("Canada's History: Canada's First Prime Minister"),
  },
  {
    id: "ppl-m-025",
    topicId: "people",
    difficulty: "medium",
    prompt: { en: "Before entering politics, Macdonald was a lawyer in which Ontario city?" },
    options: [{ en: "Kingston" }, { en: "Toronto" }, { en: "Ottawa" }, { en: "Hamilton" }],
    answerIndex: 0,
    explanation: {
      en: "He was a lawyer in Kingston, Ontario, a gifted politician and a colourful personality.",
    },
    source: src("Canada's History: Canada's First Prime Minister"),
  },
  {
    id: "ppl-m-026",
    topicId: "people",
    difficulty: "medium",
    prompt: {
      en: "When Canada took over the northwest from the Hudson's Bay Company in 1869, how many Métis of the Red River were not consulted?",
    },
    options: [{ en: "3,000" }, { en: "40,000" }, { en: "1,200" }, { en: "12,000" }],
    answerIndex: 3,
    explanation: {
      en: "When Canada took over the vast northwest region from the Hudson's Bay Company in 1869, the 12,000 Métis of the Red River were not consulted.",
    },
    source: src("Canada's History: Challenge in the West"),
  },
  {
    id: "ppl-m-027",
    topicId: "people",
    difficulty: "medium",
    prompt: {
      en: "In response, Louis Riel led an armed uprising and seized which fort, the territorial capital?",
    },
    options: [
      { en: "Fort Calgary" },
      { en: "Fort Edmonton" },
      { en: "Fort Garry" },
      { en: "Fort Victoria" },
    ],
    answerIndex: 2,
    explanation: {
      en: "In response, Louis Riel led an armed uprising and seized Fort Garry, the territorial capital.",
    },
    source: src("Canada's History: Challenge in the West"),
  },
  {
    id: "ppl-m-028",
    topicId: "people",
    difficulty: "medium",
    prompt: { en: "Riel was elected to Parliament, but what happened?" },
    options: [
      { en: "He became Speaker of the House" },
      { en: "He never took his seat" },
      { en: "He was appointed to the Senate" },
      { en: "He resigned the same day" },
    ],
    answerIndex: 1,
    explanation: { en: "Riel was elected to Parliament but never took his seat." },
    source: src("Canada's History: Challenge in the West"),
  },
  {
    id: "ppl-m-029",
    topicId: "people",
    difficulty: "medium",
    prompt: { en: "Macdonald established the NWMP in 1873 for which purposes?" },
    options: [
      { en: "To pacify the West and assist in negotiations with the Indians" },
      { en: "To build the Canadian Pacific Railway" },
      { en: "To collect customs duties at the border" },
      { en: "To guard the gold fields of the Klondike" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Prime Minister Macdonald established the North West Mounted Police (NWMP) in 1873 to pacify the West and assist in negotiations with the Indians.",
    },
    source: src("Canada's History: Challenge in the West"),
  },
  {
    id: "ppl-m-030",
    topicId: "people",
    difficulty: "medium",
    prompt: { en: "The NWMP founded which forts that today are cities and towns?" },
    options: [
      { en: "Fort Garry and Fort Edmonton" },
      { en: "Fort Langley and Fort Victoria" },
      { en: "Fort Henry and Fort York" },
      { en: "Fort Calgary and Fort MacLeod" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The NWMP founded Fort Calgary, Fort MacLeod and other centres that today are cities and towns.",
    },
    source: src("Canada's History: Challenge in the West"),
  },
  {
    id: "ppl-m-031",
    topicId: "people",
    difficulty: "medium",
    prompt: { en: "British Columbia joined Canada in 1871 after Ottawa promised what?" },
    options: [
      { en: "To grant it responsible government" },
      { en: "To make Victoria the national capital" },
      { en: "To build a railway to the West Coast" },
      { en: "To abolish the Head Tax" },
    ],
    answerIndex: 2,
    explanation: {
      en: "British Columbia joined Canada in 1871 after Ottawa promised to build a railway to the West Coast.",
    },
    source: src("Canada's History: A Railway from Sea to Sea"),
  },
  {
    id: "ppl-m-032",
    topicId: "people",
    difficulty: "medium",
    prompt: {
      en: "The CPR was financed by British and American investors and built by which labourers?",
    },
    options: [
      { en: "British soldiers and sailors" },
      { en: "European and Chinese labour" },
      { en: "American engineers only" },
      { en: "French-Canadian voyageurs only" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The project was financed by British and American investors and built by both European and Chinese labour.",
    },
    source: src("Canada's History: A Railway from Sea to Sea"),
  },
  {
    id: "ppl-m-033",
    topicId: "people",
    difficulty: "medium",
    prompt: {
      en: "In 2006, the Government of Canada apologized for which discriminatory policy toward Chinese immigrants?",
    },
    options: [
      { en: "The Head Tax, a race-based entry fee" },
      { en: "The internment of Ukrainian men" },
      { en: "The deportation of the Acadians" },
      { en: "The residential school system" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Afterwards the Chinese were subject to discrimination, including the Head Tax, a race-based entry fee; the Government of Canada apologized in 2006 for this discriminatory policy.",
    },
    source: src("Canada's History: A Railway from Sea to Sea"),
  },
  {
    id: "ppl-m-034",
    topicId: "people",
    difficulty: "medium",
    prompt: { en: "As prime minister, Laurier encouraged immigration to which part of Canada?" },
    options: [
      { en: "The Maritimes" },
      { en: "The North" },
      { en: "The Atlantic provinces" },
      { en: "The West" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Sir Wilfrid Laurier became the first French-Canadian prime minister since Confederation and encouraged immigration to the West.",
    },
    source: src("Canada's History: Moving Westward"),
  },
  {
    id: "ppl-m-035",
    topicId: "people",
    difficulty: "medium",
    prompt: { en: "Who invented basketball in 1891?" },
    options: [
      { en: "Mike Lazaridis" },
      { en: "Alexander Graham Bell" },
      { en: "James Naismith" },
      { en: "Joseph-Armand Bombardier" },
    ],
    answerIndex: 2,
    explanation: { en: "Basketball was invented by Canadian James Naismith in 1891." },
    source: src("Modern Canada"),
  },
  {
    id: "ppl-m-036",
    topicId: "people",
    difficulty: "medium",
    prompt: { en: "Who invented the Canadarm, the robotic arm used in outer space?" },
    options: [
      { en: "Bombardier Inc." },
      { en: "SPAR Aerospace / National Research Council" },
      { en: "Research in Motion" },
      { en: "Bell Canada" },
    ],
    answerIndex: 1,
    explanation: {
      en: "SPAR Aerospace and the National Research Council invented the Canadarm, a robotic arm used in outer space.",
    },
    source: src("Modern Canada: Great Canadian Discoveries and Inventions"),
  },
  {
    id: "ppl-m-037",
    topicId: "people",
    difficulty: "medium",
    prompt: {
      en: "In the Boer War (1899–1902), over 7,000 Canadians volunteered and over how many died?",
    },
    options: [{ en: "260" }, { en: "60" }, { en: "2,600" }, { en: "7,000" }],
    answerIndex: 0,
    explanation: {
      en: "Over 7,000 volunteered to fight in the South African War (1899–1902), popularly known as the Boer War, and over 260 died.",
    },
    source: src("Canada's History: The First World War"),
  },
  {
    id: "ppl-m-038",
    topicId: "people",
    difficulty: "medium",
    prompt: { en: "In 1900, Canadian victories at which two battles strengthened national pride?" },
    options: [
      { en: "Vimy Ridge and Amiens" },
      { en: "Dieppe and Juno Beach" },
      { en: "Queenston Heights and Châteauguay" },
      { en: "Paardeberg and Lillefontein" },
    ],
    answerIndex: 3,
    explanation: {
      en: "In 1900, Canadians took part in the battles of Paardeberg (“Horse Mountain”) and Lillefontein, victories that strengthened national pride in Canada.",
    },
    source: src("Canada's History: The First World War"),
  },
  {
    id: "ppl-m-039",
    topicId: "people",
    difficulty: "medium",
    prompt: {
      en: "In the First World War, more than 600,000 Canadians served out of a total population of how many?",
    },
    options: [
      { en: "Eleven and a half million" },
      { en: "Three million" },
      { en: "Eight million" },
      { en: "One million" },
    ],
    answerIndex: 2,
    explanation: {
      en: "More than 600,000 Canadians served in the war, most of them volunteers, out of a total population of eight million.",
    },
    source: src("Canada's History: The First World War"),
  },
  {
    id: "ppl-m-040",
    topicId: "people",
    difficulty: "medium",
    prompt: { en: "At Vimy Ridge, how many Canadians were killed or wounded?" },
    options: [{ en: "1,000" }, { en: "10,000" }, { en: "60,000" }, { en: "100,000" }],
    answerIndex: 1,
    explanation: {
      en: "The Canadian Corps captured Vimy Ridge in April 1917, with 10,000 killed or wounded.",
    },
    source: src("Canada's History: The First World War"),
  },
  {
    id: "ppl-m-041",
    topicId: "people",
    difficulty: "medium",
    prompt: {
      en: "The Vimy Memorial, honouring those who served and died at Vimy Ridge, stands in which country?",
    },
    options: [{ en: "France" }, { en: "Belgium" }, { en: "Canada" }, { en: "England" }],
    answerIndex: 0,
    explanation: {
      en: "The Vimy Memorial in France honours those who served and died in the Battle of Vimy Ridge on April 9, 1917.",
    },
    source: src("Canada's History: The First World War"),
  },
  {
    id: "ppl-m-042",
    topicId: "people",
    difficulty: "medium",
    prompt: { en: "The Canadian Corps earned a reputation as the “shock troops” of whom?" },
    options: [
      { en: "The French Army" },
      { en: "The American Expeditionary Force" },
      { en: "The League of Nations" },
      { en: "The British Empire" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The Canadian Corps captured Vimy Ridge, securing the Canadians' reputation for valour as the “shock troops of the British Empire.”",
    },
    source: src("Canada's History: The First World War"),
  },
  {
    id: "ppl-m-043",
    topicId: "people",
    difficulty: "medium",
    prompt: { en: "The Germans called the Battle of Amiens on August 8, 1918 what?" },
    options: [
      { en: "“The miracle of the Marne”" },
      { en: "“The triumph of the Somme”" },
      { en: "“The black day of the German Army”" },
      { en: "“The folly of Flanders”" },
    ],
    answerIndex: 2,
    explanation: {
      en: "These included the victorious Battle of Amiens on August 8, 1918—which the Germans called “the black day of the German Army.”",
    },
    source: src("Canada's History: The First World War"),
  },
  {
    id: "ppl-m-044",
    topicId: "people",
    difficulty: "medium",
    prompt: { en: "The First World War ended with the Armistice on which date?" },
    options: [
      { en: "May 8, 1945" },
      { en: "November 11, 1918" },
      { en: "June 6, 1944" },
      { en: "April 9, 1917" },
    ],
    answerIndex: 1,
    explanation: {
      en: "With Germany and Austria's surrender, the war ended in the Armistice on November 11, 1918.",
    },
    source: src("Canada's History: The First World War"),
  },
  {
    id: "ppl-m-045",
    topicId: "people",
    difficulty: "medium",
    prompt: { en: "In total, how many Canadians were killed and wounded in the First World War?" },
    options: [
      { en: "60,000 killed and 170,000 wounded" },
      { en: "44,000 killed and 110,000 wounded" },
      { en: "10,000 killed and 60,000 wounded" },
      { en: "170,000 killed and 60,000 wounded" },
    ],
    answerIndex: 0,
    explanation: { en: "In total 60,000 Canadians were killed and 170,000 wounded." },
    source: src("Canada's History: The First World War"),
  },
  {
    id: "ppl-m-046",
    topicId: "people",
    difficulty: "medium",
    prompt: { en: "Dr. Emily Stowe was the first Canadian woman to do what?" },
    options: [
      { en: "Serve as a Member of Parliament" },
      { en: "Publish a newspaper" },
      { en: "Command an army regiment" },
      { en: "Practise medicine in Canada" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Its founder in Canada was Dr. Emily Stowe, the first Canadian woman to practise medicine in Canada.",
    },
    source: src("Canada's History: Women Get the Vote"),
  },
  {
    id: "ppl-m-047",
    topicId: "people",
    difficulty: "medium",
    prompt: {
      en: "In 1918, most Canadian female citizens aged how many and over were granted the federal vote?",
    },
    options: [{ en: "18" }, { en: "25" }, { en: "21" }, { en: "30" }],
    answerIndex: 2,
    explanation: {
      en: "In 1918, most Canadian female citizens aged 21 and over were granted the right to vote in federal elections.",
    },
    source: src("Canada's History: Women Get the Vote"),
  },
  {
    id: "ppl-m-048",
    topicId: "people",
    difficulty: "medium",
    prompt: {
      en: "Due largely to the work of Thérèse Casgrain and others, Quebec granted women the vote in which year?",
    },
    options: [{ en: "1916" }, { en: "1940" }, { en: "1918" }, { en: "1921" }],
    answerIndex: 1,
    explanation: {
      en: "Due to the work of Thérèse Casgrain and others, Quebec granted women the vote in 1940.",
    },
    source: src("Canada's History: Women Get the Vote"),
  },
  {
    id: "ppl-m-049",
    topicId: "people",
    difficulty: "medium",
    prompt: { en: "The “Bluebirds” were more than 3,000 nurses serving in which corps?" },
    options: [
      { en: "The Royal Canadian Army Medical Corps" },
      { en: "The Royal Canadian Air Force" },
      { en: "The Canadian Red Cross Society" },
      { en: "The Victorian Order of Nurses" },
    ],
    answerIndex: 0,
    explanation: {
      en: "More than 3,000 nurses, nicknamed “Bluebirds,” served in the Royal Canadian Army Medical Corps, 2,500 of them overseas.",
    },
    source: src("Canada's History: Women Get the Vote"),
  },
  {
    id: "ppl-m-050",
    topicId: "people",
    difficulty: "medium",
    prompt: {
      en: "Phil Edwards, born in British Guiana, won bronze medals for Canada at which three Olympics?",
    },
    options: [
      { en: "1924, 1928 and 1932" },
      { en: "1932, 1936 and 1948" },
      { en: "1928, 1936 and 1952" },
      { en: "1928, 1932 and 1936" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Phil Edwards was a Canadian track and field champion who won bronze medals for Canada in the 1928, 1932, and 1936 Olympics.",
    },
    source: src("Canada's History: Women Get the Vote"),
  },
  {
    id: "ppl-m-051",
    topicId: "people",
    difficulty: "medium",
    prompt: { en: "Phil Edwards graduated from the medical school of which university?" },
    options: [
      { en: "The University of Toronto" },
      { en: "Queen's University" },
      { en: "McGill University" },
      { en: "Dalhousie University" },
    ],
    answerIndex: 2,
    explanation: {
      en: "He graduated from McGill University Medical School, served as a captain in the Canadian Army, and became a Montreal doctor expert in tropical diseases.",
    },
    source: src("Canada's History: Women Get the Vote"),
  },
  {
    id: "ppl-m-052",
    topicId: "people",
    difficulty: "medium",
    prompt: { en: "During the Great Depression, unemployment reached 27% in which year?" },
    options: [{ en: "1929" }, { en: "1933" }, { en: "1939" }, { en: "1934" }],
    answerIndex: 1,
    explanation: { en: "Unemployment reached 27% in 1933 and many businesses were wiped out." },
    source: src("Canada's History: Between the Wars"),
  },
  {
    id: "ppl-m-053",
    topicId: "people",
    difficulty: "medium",
    prompt: {
      en: "The Bank of Canada, created to manage the money supply and bring stability to the financial system, was established in which year?",
    },
    options: [{ en: "1934" }, { en: "1929" }, { en: "1940" }, { en: "1867" }],
    answerIndex: 0,
    explanation: {
      en: "The Bank of Canada, a central bank to manage the money supply and bring stability to the financial system, was created in 1934.",
    },
    source: src("Canada's History: Between the Wars"),
  },
  {
    id: "ppl-m-054",
    topicId: "people",
    difficulty: "medium",
    prompt: {
      en: "In the Second World War, more than one million Canadians and Newfoundlanders served; how many were killed?",
    },
    options: [{ en: "60,000" }, { en: "110,000" }, { en: "11,500" }, { en: "44,000" }],
    answerIndex: 3,
    explanation: {
      en: "More than one million Canadians and Newfoundlanders served in the Second World War, out of a population of 11.5 million; of these, 44,000 were killed.",
    },
    source: src("Canada's History: The Second World War"),
  },
  {
    id: "ppl-m-055",
    topicId: "people",
    difficulty: "medium",
    prompt: {
      en: "On D-Day, June 6, 1944, how many Canadian troops stormed and captured Juno Beach?",
    },
    options: [{ en: "1,500" }, { en: "150,000" }, { en: "15,000" }, { en: "6,000" }],
    answerIndex: 2,
    explanation: {
      en: "In the epic invasion of Normandy on June 6, 1944, known as D-Day, 15,000 Canadian troops stormed and captured Juno Beach from the German Army.",
    },
    source: src("Canada's History: The D-Day Invasion, June 6, 1944"),
  },
  {
    id: "ppl-m-056",
    topicId: "people",
    difficulty: "medium",
    prompt: { en: "Approximately what fraction of Allied soldiers on D-Day were Canadian?" },
    options: [
      { en: "One in a hundred" },
      { en: "One in ten" },
      { en: "One in four" },
      { en: "One in two" },
    ],
    answerIndex: 1,
    explanation: { en: "Approximately one in ten Allied soldiers on D-Day was Canadian." },
    source: src("Canada's History: The D-Day Invasion, June 6, 1944"),
  },
  {
    id: "ppl-m-057",
    topicId: "people",
    difficulty: "medium",
    prompt: { en: "The Canadian Army liberated which country in 1944–45?" },
    options: [{ en: "The Netherlands" }, { en: "Belgium" }, { en: "Italy" }, { en: "Norway" }],
    answerIndex: 0,
    explanation: {
      en: "The Canadian Army liberated the Netherlands in 1944–45 and helped force the German surrender of May 8, 1945.",
    },
    source: src("Canada's History: The D-Day Invasion, June 6, 1944"),
  },
  {
    id: "ppl-m-058",
    topicId: "people",
    difficulty: "medium",
    prompt: { en: "Germany surrendered on May 8, 1945. On which date did Japan surrender?" },
    options: [
      { en: "September 2, 1945" },
      { en: "June 6, 1944" },
      { en: "November 11, 1918" },
      { en: "August 14, 1945" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Japan surrendered on August 14, 1945—the end of four years of war in the Pacific.",
    },
    source: src("Canada's History: The Second World War"),
  },
  {
    id: "ppl-m-059",
    topicId: "people",
    difficulty: "medium",
    prompt: {
      en: "In the Pacific war, Canadian prisoners of war were grossly maltreated by Japan after being captured at which battle?",
    },
    options: [
      { en: "Dieppe (1942)" },
      { en: "Juno Beach (1944)" },
      { en: "Hong Kong (1941)" },
      { en: "Ortona (1943)" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The Canadians suffered losses in the unsuccessful defence of Hong Kong (1941), and Japan grossly maltreated Canadian prisoners of war captured at Hong Kong.",
    },
    source: src("Canada's History: The Second World War"),
  },
  {
    id: "ppl-m-060",
    topicId: "people",
    difficulty: "medium",
    prompt: {
      en: "In 1988, the Government of Canada apologized and compensated victims for which wartime wrong?",
    },
    options: [
      { en: "The internment of Ukrainian men as enemy aliens" },
      {
        en: "The forcible relocation of Canadians of Japanese origin and the sale of their property without compensation",
      },
      { en: "The deportation of black Loyalists" },
      { en: "The burning of Washington, D.C." },
    ],
    answerIndex: 1,
    explanation: {
      en: "The Government of Canada apologized in 1988 for wartime wrongs — the forcible relocation of Canadians of Japanese origin and the sale of their property without compensation — and compensated the victims.",
    },
    source: src("Canada's History: The Second World War"),
  },
  {
    id: "ppl-m-061",
    topicId: "people",
    difficulty: "medium",
    prompt: { en: "Over 130,000 Allied air crew were trained in Canada under which plan?" },
    options: [
      { en: "The British Commonwealth Air Training Plan" },
      { en: "The Marshall Plan" },
      { en: "The Manhattan Project" },
      { en: "The Lend-Lease Program" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Canada contributed more to the Allied air effort than any other Commonwealth country, with over 130,000 Allied air crew trained in Canada under the British Commonwealth Air Training Plan.",
    },
    source: src("Canada's History: The Second World War"),
  },
  {
    id: "ppl-m-062",
    topicId: "people",
    difficulty: "medium",
    prompt: {
      en: "At the end of the Second World War, Canada had the what-largest navy in the world?",
    },
    options: [
      { en: "Largest" },
      { en: "Fifth-largest" },
      { en: "Tenth-largest" },
      { en: "Third-largest" },
    ],
    answerIndex: 3,
    explanation: {
      en: "At the end of the Second World War, Canada had the third-largest navy in the world.",
    },
    source: src("Canada's History: The Second World War"),
  },
  {
    id: "ppl-m-063",
    topicId: "people",
    difficulty: "medium",
    prompt: { en: "The Royal Canadian Navy saw its finest hour in which battle?" },
    options: [
      { en: "The Battle of Britain" },
      { en: "The Battle of Trafalgar" },
      { en: "The Battle of the Atlantic" },
      { en: "The Battle of Jutland" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The Royal Canadian Navy (RCN) saw its finest hour in the Battle of the Atlantic, protecting convoys of merchant ships against German submarines.",
    },
    source: src("Canada's History: The Second World War"),
  },
  {
    id: "ppl-m-064",
    topicId: "people",
    difficulty: "medium",
    prompt: { en: "In the Korean War (1950–53), Canada suffered how many dead and wounded?" },
    options: [
      { en: "5,000 dead and 10,000 wounded" },
      { en: "500 dead and 1,000 wounded" },
      { en: "50 dead and 100 wounded" },
      { en: "1,000 dead and 500 wounded" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Canada participated in the UN operation defending South Korea in the Korean War (1950–53), with 500 dead and 1,000 wounded.",
    },
    source: src("Modern Canada: International Engagement"),
  },
  {
    id: "ppl-m-065",
    topicId: "people",
    difficulty: "medium",
    prompt: {
      en: "Canada formed NORAD (the North American Aerospace Defence Command) with which country?",
    },
    options: [
      { en: "The United States" },
      { en: "Britain" },
      { en: "France" },
      { en: "The Soviet Union" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Canada joined with the United States in the North American Aerospace Defence Command (NORAD).",
    },
    source: src("Modern Canada: International Engagement"),
  },
  {
    id: "ppl-m-066",
    topicId: "people",
    difficulty: "medium",
    prompt: { en: "The Official Languages Act of 1969 guarantees what?" },
    options: [
      { en: "That Quebec is the only bilingual province" },
      { en: "Free French classes for all newcomers" },
      { en: "That Parliament debates only in English" },
      { en: "French and English services in the federal government across Canada" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The Official Languages Act (1969) guarantees French and English services in the federal government across Canada.",
    },
    source: src("Modern Canada: Canada and Quebec"),
  },
  {
    id: "ppl-m-067",
    topicId: "people",
    difficulty: "medium",
    prompt: { en: "In 1963, Parliament established which Royal Commission?" },
    options: [
      { en: "The Royal Commission on the Status of Women" },
      { en: "The Royal Commission on Aboriginal Peoples" },
      { en: "The Royal Commission on Bilingualism and Biculturalism" },
      { en: "The Royal Commission on Banking" },
    ],
    answerIndex: 2,
    explanation: {
      en: "In 1963 Parliament established the Royal Commission on Bilingualism and Biculturalism, which led to the Official Languages Act.",
    },
    source: src("Modern Canada: Canada and Quebec"),
  },
  {
    id: "ppl-m-068",
    topicId: "people",
    difficulty: "medium",
    prompt: {
      en: "In 1970, Canada helped found which international association of French-speaking countries?",
    },
    options: [
      { en: "The Commonwealth of Nations" },
      { en: "La Francophonie" },
      { en: "The Organisation of American States" },
      { en: "The Arab League" },
    ],
    answerIndex: 1,
    explanation: {
      en: "In 1970, Canada helped found La Francophonie, an international association of French-speaking countries.",
    },
    source: src("Modern Canada: Canada and Quebec"),
  },
  {
    id: "ppl-m-069",
    topicId: "people",
    difficulty: "medium",
    prompt: {
      en: "The movement for Quebec sovereignty was defeated in referendums in which two years?",
    },
    options: [
      { en: "1980 and 1995" },
      { en: "1970 and 1980" },
      { en: "1995 and 2005" },
      { en: "1969 and 1982" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The movement for Quebec sovereignty gained strength but was defeated in a referendum in the province in 1980, and sovereignty was again defeated in a second referendum in 1995.",
    },
    source: src("Modern Canada: Canada and Quebec"),
  },
  {
    id: "ppl-m-070",
    topicId: "people",
    difficulty: "medium",
    prompt: {
      en: "In 1982, the Constitution was amended without the agreement of which province?",
    },
    options: [{ en: "Ontario" }, { en: "Alberta" }, { en: "Newfoundland" }, { en: "Quebec" }],
    answerIndex: 3,
    explanation: {
      en: "After much negotiation, in 1982 the Constitution was amended without the agreement of Quebec.",
    },
    source: src("Modern Canada: Canada and Quebec"),
  },
  {
    id: "ppl-h-001",
    topicId: "people",
    difficulty: "hard",
    prompt: {
      en: "Which British commander was killed at the Battle of the Plains of Abraham in 1759?",
    },
    options: [
      { en: "The Marquis de Montcalm" },
      { en: "Major-General Sir Isaac Brock" },
      { en: "Brigadier James Wolfe" },
      { en: "Lieutenant-Colonel Charles de Salaberry" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Both commanders were killed at the Plains of Abraham; Brigadier James Wolfe led the British army, while the Marquis de Montcalm led the French.",
    },
    source: src("Canada's History: Struggle for a Continent"),
  },
  {
    id: "ppl-h-002",
    topicId: "people",
    difficulty: "hard",
    prompt: {
      en: "Which general was killed at Queenston Heights in 1812, rather than at the Plains of Abraham in 1759?",
    },
    options: [
      { en: "Brigadier James Wolfe" },
      { en: "Major-General Sir Isaac Brock" },
      { en: "The Marquis de Montcalm" },
      { en: "Major-General Robert Ross" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Sir Isaac Brock was killed defending Queenston Heights in 1812; Wolfe and Montcalm were the commanders killed at the Plains of Abraham in 1759.",
    },
    source: src("Canada's History: The War of 1812: The Fight for Canada"),
  },
  {
    id: "ppl-h-003",
    topicId: "people",
    difficulty: "hard",
    prompt: { en: "In July 1812, Detroit was captured by whom?" },
    options: [
      { en: "Major-General Sir Isaac Brock" },
      { en: "Lieutenant-Colonel Charles de Salaberry" },
      { en: "Chief Tecumseh" },
      { en: "Lieutenant James FitzGibbon" },
    ],
    answerIndex: 0,
    explanation: {
      en: "In July 1812, Major-General Sir Isaac Brock captured Detroit; de Salaberry's victory was at Châteauguay in 1813.",
    },
    source: src("Canada's History: The War of 1812: The Fight for Canada"),
  },
  {
    id: "ppl-h-004",
    topicId: "people",
    difficulty: "hard",
    prompt: {
      en: "John Buchan, the 1st Baron Tweedsmuir, served as Governor General of Canada during which years?",
    },
    options: [{ en: "1909–14" }, { en: "1952–59" }, { en: "1921–26" }, { en: "1935–40" }],
    answerIndex: 3,
    explanation: {
      en: "John Buchan, the 1st Baron Tweedsmuir, was a popular Governor General of Canada (1935–40).",
    },
    source: src("Who We Are: Unity in Diversity"),
  },
  {
    id: "ppl-h-005",
    topicId: "people",
    difficulty: "hard",
    prompt: {
      en: "Lord Tweedsmuir said immigrant groups “should retain their individuality” and each do what?",
    },
    options: [
      { en: "Assimilate into English-speaking Protestant culture" },
      { en: "Abandon their old loyalties entirely" },
      { en: "Make its contribution to the national character" },
      { en: "Seek separate political representation" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Tweedsmuir said immigrant groups “should retain their individuality and each make its contribution to the national character.”",
    },
    source: src("Who We Are: Unity in Diversity"),
  },
  {
    id: "ppl-h-006",
    topicId: "people",
    difficulty: "hard",
    prompt: { en: "Lord Grey donated the Grey Cup in 1909 while holding which office?" },
    options: [
      { en: "Prime Minister" },
      { en: "Governor General" },
      { en: "Chief Justice" },
      { en: "Mayor of Ottawa" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Professional teams in the Canadian Football League compete for the championship Grey Cup, donated by Lord Grey, the Governor General, in 1909.",
    },
    source: src("Modern Canada: Arts and Culture in Canada"),
  },
  {
    id: "ppl-h-007",
    topicId: "people",
    difficulty: "hard",
    prompt: { en: "Marshall McLuhan and Harold Innis are described in the guide as what?" },
    options: [
      { en: "Pioneer thinkers" },
      { en: "Nobel Prize-winning scientists" },
      { en: "Fathers of Confederation" },
      { en: "Group of Seven painters" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Marshall McLuhan and Harold Innis were pioneer thinkers whose work changed the way the world communicates.",
    },
    source: src("Modern Canada: Arts and Culture in Canada"),
  },
  {
    id: "ppl-h-008",
    topicId: "people",
    difficulty: "hard",
    prompt: {
      en: "Which Nobel Prize-winning scientist named in the guide was a refugee from Nazi Germany?",
    },
    options: [
      { en: "John Polanyi" },
      { en: "Michael Smith" },
      { en: "Bertram Brockhouse" },
      { en: "Gerhard Herzberg" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Gerhard Herzberg, a refugee from Nazi Germany, was one of the Nobel Prize-winning scientists named in the guide.",
    },
    source: src("Modern Canada: Arts and Culture in Canada"),
  },
  {
    id: "ppl-h-009",
    topicId: "people",
    difficulty: "hard",
    prompt: {
      en: "Which of the following is named in the guide as a Nobel Prize-winning scientist?",
    },
    options: [
      { en: "Marshall McLuhan" },
      { en: "Dr. Wilder Penfield" },
      { en: "John Polanyi" },
      { en: "Harold Innis" },
    ],
    answerIndex: 2,
    explanation: {
      en: "John Polanyi is named among the Nobel Prize-winning scientists; McLuhan and Innis were pioneer thinkers, and Penfield was a brain surgeon.",
    },
    source: src("Modern Canada: Arts and Culture in Canada"),
  },
  {
    id: "ppl-h-010",
    topicId: "people",
    difficulty: "hard",
    prompt: {
      en: "Sir Frederick Banting and Charles Best discovered insulin, a hormone to treat diabetes that has saved how many lives worldwide?",
    },
    options: [{ en: "6 million" }, { en: "16 million" }, { en: "160 million" }, { en: "16,000" }],
    answerIndex: 1,
    explanation: {
      en: "Sir Frederick Banting of Toronto and Charles Best discovered Insulin, a hormone to treat diabetes that has saved 16 million lives worldwide.",
    },
    source: src("Modern Canada: Great Canadian Discoveries and Inventions"),
  },
  {
    id: "ppl-h-011",
    topicId: "people",
    difficulty: "hard",
    prompt: {
      en: "Alexander Graham Bell hit on the idea of the telephone at his summer house in which country?",
    },
    options: [{ en: "Canada" }, { en: "Scotland" }, { en: "The United States" }, { en: "England" }],
    answerIndex: 0,
    explanation: {
      en: "Alexander Graham Bell hit on the idea of the telephone at his summer house in Canada.",
    },
    source: src("Modern Canada: Great Canadian Discoveries and Inventions"),
  },
  {
    id: "ppl-h-012",
    topicId: "people",
    difficulty: "hard",
    prompt: {
      en: "Which British Columbian circled the globe in a wheelchair in 1985 to raise funds for spinal cord research?",
    },
    options: [
      { en: "Terry Fox" },
      { en: "Donovan Bailey" },
      { en: "Mark Tewksbury" },
      { en: "Rick Hansen" },
    ],
    answerIndex: 3,
    explanation: {
      en: "In 1985, fellow British Columbian Rick Hansen circled the globe in a wheelchair to raise funds for spinal cord research; Terry Fox's run was the 1980 Marathon of Hope for cancer research.",
    },
    source: src("Modern Canada: Arts and Culture in Canada"),
  },
  {
    id: "ppl-h-013",
    topicId: "people",
    difficulty: "hard",
    prompt: { en: "What was the outcome of Terry Fox's 1980 Marathon of Hope?" },
    options: [
      { en: "He completed the run across Canada in 143 days" },
      { en: "He raised enough to cure cancer in his lifetime" },
      {
        en: "He did not finish the run and ultimately lost his battle with cancer, though yearly fundraising events continue in his name",
      },
      { en: "He stopped at the Ontario border and never ran again" },
    ],
    answerIndex: 2,
    explanation: {
      en: "While he did not finish the run and ultimately lost his battle with cancer, his legacy continues through yearly fundraising events in his name.",
    },
    source: src("Modern Canada: Arts and Culture in Canada"),
  },
  {
    id: "ppl-h-014",
    topicId: "people",
    difficulty: "hard",
    prompt: { en: "Which group were pioneers of modern abstract art in Quebec in the 1950s?" },
    options: [
      { en: "The Group of Seven" },
      { en: "Les Automatistes" },
      { en: "The Hudson River School" },
      { en: "The Beaver Hall Group" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Les Automatistes of Quebec were pioneers of modern abstract art in the 1950s, most notably Jean-Paul Riopelle.",
    },
    source: src("Modern Canada: Arts and Culture in Canada"),
  },
  {
    id: "ppl-h-015",
    topicId: "people",
    difficulty: "hard",
    prompt: {
      en: "Louis-Philippe Hébert, the celebrated sculptor of historical figures, was from which province?",
    },
    options: [
      { en: "Quebec" },
      { en: "Ontario" },
      { en: "British Columbia" },
      { en: "Nova Scotia" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Quebec's Louis-Philippe Hébert was a celebrated sculptor of historical figures.",
    },
    source: src("Modern Canada: Arts and Culture in Canada"),
  },
  {
    id: "ppl-h-016",
    topicId: "people",
    difficulty: "hard",
    prompt: { en: "“The Jack Pine” is a painting by whom?" },
    options: [
      { en: "Emily Carr" },
      { en: "Jean-Paul Riopelle" },
      { en: "Bill Reid" },
      { en: "Tom Thomson" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The guide illustrates its arts section with “The Jack Pine,” by Tom Thomson.",
    },
    source: src("Modern Canada: Arts and Culture in Canada"),
  },
  {
    id: "ppl-h-017",
    topicId: "people",
    difficulty: "hard",
    prompt: { en: "Haida artist Bill Reid is shown in the guide carving what?" },
    options: [
      { en: "A soapstone bear" },
      { en: "An Inuit print" },
      { en: "A totem pole" },
      { en: "A marble statue" },
    ],
    answerIndex: 2,
    explanation: { en: "The guide shows Haida artist Bill Reid carving a totem pole." },
    source: src("Who We Are: Unity in Diversity"),
  },
  {
    id: "ppl-h-018",
    topicId: "people",
    difficulty: "hard",
    prompt: {
      en: "Which of the following is named in the guide among Canada's men and women of letters?",
    },
    options: [
      { en: "Louis-Philippe Hébert" },
      { en: "Margaret Laurence" },
      { en: "Denys Arcand" },
      { en: "Wayne Gretzky" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Men and women of letters named in the guide include Margaret Laurence; Hébert was a sculptor, Arcand a filmmaker, and Gretzky a hockey player.",
    },
    source: src("Modern Canada: Arts and Culture in Canada"),
  },
  {
    id: "ppl-h-019",
    topicId: "people",
    difficulty: "hard",
    prompt: {
      en: "Sir Ernest MacMillan and Healey Willan won renown in Canada and abroad in which field?",
    },
    options: [{ en: "Music" }, { en: "Literature" }, { en: "Painting" }, { en: "Film" }],
    answerIndex: 0,
    explanation: {
      en: "Musicians such as Sir Ernest MacMillan and Healey Willan won renown in Canada and abroad.",
    },
    source: src("Modern Canada: Arts and Culture in Canada"),
  },
  {
    id: "ppl-h-020",
    topicId: "people",
    difficulty: "hard",
    prompt: {
      en: "Whose films have been popular in Quebec and across the country and won international awards?",
    },
    options: [
      { en: "Norman Jewison" },
      { en: "Atom Egoyan" },
      { en: "James Naismith" },
      { en: "Denys Arcand" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The films of Denys Arcand have been popular in Quebec and across the country, and have won international awards.",
    },
    source: src("Modern Canada: Arts and Culture in Canada"),
  },
  {
    id: "ppl-h-021",
    topicId: "people",
    difficulty: "hard",
    prompt: { en: "John Diefenbaker, the 13th Prime Minister, served during which years?" },
    options: [
      { en: "July 11, 1896 – October 6, 1911" },
      { en: "1867 – 1873" },
      { en: "June 21, 1957 – April 22, 1963" },
      { en: "1911 – 1920" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The guide lists John Diefenbaker as the 13th Prime Minister, serving June 21, 1957 – April 22, 1963.",
    },
    source: src("Memorable Quotes"),
  },
  {
    id: "ppl-h-022",
    topicId: "people",
    difficulty: "hard",
    prompt: { en: "Sir Wilfrid Laurier, the 7th Prime Minister, served during which years?" },
    options: [
      { en: "June 21, 1957 – April 22, 1963" },
      { en: "July 11, 1896 – October 6, 1911" },
      { en: "1867 – 1873" },
      { en: "1849 – 1854" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The guide lists Sir Wilfrid Laurier as the 7th Prime Minister, serving July 11, 1896 – October 6, 1911.",
    },
    source: src("Memorable Quotes"),
  },
  {
    id: "ppl-h-023",
    topicId: "people",
    difficulty: "hard",
    prompt: { en: "Who assigned Canada's national colours, white and red, in 1921?" },
    options: [
      { en: "King George V" },
      { en: "Queen Victoria" },
      { en: "King Charles II" },
      { en: "Sir John A. Macdonald" },
    ],
    answerIndex: 0,
    explanation: {
      en: "King George V assigned Canada's national colours (white and red) in 1921, the colours of the national flag today.",
    },
    source: src("Canada's History: Confederation"),
  },
  {
    id: "ppl-h-024",
    topicId: "people",
    difficulty: "hard",
    prompt: { en: "In which year were Aboriginal people granted the right to vote?" },
    options: [{ en: "1948" }, { en: "1940" }, { en: "1918" }, { en: "1960" }],
    answerIndex: 3,
    explanation: {
      en: "Aboriginal people were granted the vote in 1960; today every citizen over the age of 18 may vote.",
    },
    source: src("Modern Canada: A Changing Society"),
  },
  {
    id: "ppl-h-025",
    topicId: "people",
    difficulty: "hard",
    prompt: { en: "Which group were the last of Asian descent to gain the vote, in 1948?" },
    options: [
      { en: "Chinese-Canadians" },
      { en: "South Asian Canadians" },
      { en: "Japanese-Canadians" },
      { en: "Korean-Canadians" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Most Canadians of Asian descent had in the past been denied the vote; in 1948 the last of these, the Japanese-Canadians, gained the right to vote.",
    },
    source: src("Modern Canada: A Changing Society"),
  },
  {
    id: "ppl-h-026",
    topicId: "people",
    difficulty: "hard",
    prompt: { en: "Olympian Marjorie Turner-Bailey of Nova Scotia is a descendant of whom?" },
    options: [
      { en: "United Empire Loyalists from New York" },
      {
        en: "Black Loyalists, escaped slaves and freed men and women of African origin who fled to Canada in the 1780s",
      },
      { en: "Acadian deportees of the Great Upheaval" },
      { en: "Métis voyageurs of the Red River" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Olympian Marjorie Turner-Bailey of Nova Scotia is a descendant of black Loyalists, escaped slaves and freed men and women of African origin who in the 1780s fled to Canada from America.",
    },
    source: src("Who We Are: Diversity in Canada"),
  },
  {
    id: "ppl-h-027",
    topicId: "people",
    difficulty: "hard",
    prompt: {
      en: "The Duke of Wellington, who played a direct role in founding the national capital, defeated Napoleon in which year?",
    },
    options: [{ en: "1815" }, { en: "1814" }, { en: "1812" }, { en: "1805" }],
    answerIndex: 0,
    explanation: {
      en: "Wellington, who defeated Napoleon in 1815, chose Bytown (Ottawa) as the endpoint of the Rideau Canal and therefore played a direct role in founding the national capital.",
    },
    source: src("Canada's History: The War of 1812: The Fight for Canada"),
  },
  {
    id: "ppl-h-028",
    topicId: "people",
    difficulty: "hard",
    prompt: { en: "Wellington sent some of his best soldiers to defend Canada in which year?" },
    options: [{ en: "1812" }, { en: "1815" }, { en: "1816" }, { en: "1814" }],
    answerIndex: 3,
    explanation: {
      en: "The Duke of Wellington sent some of his best soldiers to defend Canada in 1814.",
    },
    source: src("Canada's History: The War of 1812: The Fight for Canada"),
  },
  {
    id: "ppl-h-029",
    topicId: "people",
    difficulty: "hard",
    prompt: {
      en: "Which general led the 1814 expedition that burned Washington, D.C., and was buried in Halifax with full military honours?",
    },
    options: [
      { en: "Major-General Sir Isaac Brock" },
      { en: "General Sir Arthur Currie" },
      { en: "Major-General Robert Ross" },
      { en: "The Duke of Wellington" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Major-General Robert Ross led the 1814 expedition that burned Washington, D.C.; he died in battle soon afterwards and was buried in Halifax with full military honours.",
    },
    source: src("Canada's History: The War of 1812: The Fight for Canada"),
  },
  {
    id: "ppl-h-030",
    topicId: "people",
    difficulty: "hard",
    prompt: {
      en: "Which lieutenant-governor both founded the City of York (now Toronto) and made Upper Canada the first province in the Empire to move toward abolishing slavery?",
    },
    options: [
      { en: "Sir Guy Carleton" },
      { en: "John Graves Simcoe" },
      { en: "Lord Elgin" },
      { en: "Lord Durham" },
    ],
    answerIndex: 1,
    explanation: {
      en: "John Graves Simcoe was Upper Canada's first Lieutenant Governor and founder of York (now Toronto), and under his leadership Upper Canada became the first province in the Empire to move toward abolition in 1793.",
    },
    source: src("Canada's History: Abolition of Slavery"),
  },
  {
    id: "ppl-h-031",
    topicId: "people",
    difficulty: "hard",
    prompt: {
      en: "The Provincial Freeman, the weekly newspaper Mary Ann Shadd Cary helped found and edit, was dedicated to which causes?",
    },
    options: [
      { en: "Anti-slavery, black immigration to Canada, temperance and upholding British rule" },
      { en: "Women's suffrage, prohibition and free trade" },
      { en: "Responsible government and Confederation" },
      { en: "French language rights and Catholic education" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The Provincial Freeman was a weekly newspaper dedicated to anti-slavery, black immigration to Canada, temperance (urging people to drink less alcohol), and upholding British rule.",
    },
    source: src("Canada's History: Abolition of Slavery"),
  },
  {
    id: "ppl-h-032",
    topicId: "people",
    difficulty: "hard",
    prompt: {
      en: "Which hero of New France won many victories over the English, from James Bay in the north to Nevis in the Caribbean?",
    },
    options: [
      { en: "Count Frontenac" },
      { en: "Sir Guy Carleton" },
      { en: "Jean Talon" },
      { en: "Pierre Le Moyne, Sieur d'Iberville" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Pierre Le Moyne, Sieur d'Iberville, was a great hero of New France, winning many victories over the English, from James Bay in the north to Nevis in the Caribbean.",
    },
    source: src("Canada's History: Royal New France"),
  },
  {
    id: "ppl-h-033",
    topicId: "people",
    difficulty: "hard",
    prompt: {
      en: "Outstanding leaders like Jean Talon, Bishop Laval and Count Frontenac built a French Empire in North America stretching from where to where?",
    },
    options: [
      { en: "From the Atlantic to the Pacific" },
      { en: "From the St. Lawrence to the Mississippi" },
      { en: "From Hudson Bay to the Gulf of Mexico" },
      { en: "From Newfoundland to Louisiana" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Outstanding leaders like Jean Talon, Bishop Laval, and Count Frontenac built a French Empire in North America that reached from Hudson Bay to the Gulf of Mexico.",
    },
    source: src("Canada's History: Royal New France"),
  },
  {
    id: "ppl-h-034",
    topicId: "people",
    difficulty: "hard",
    prompt: {
      en: "Louis Riel's 1885 trial and execution for high treason was strongly opposed in which province?",
    },
    options: [{ en: "Ontario" }, { en: "Quebec" }, { en: "Manitoba" }, { en: "New Brunswick" }],
    answerIndex: 1,
    explanation: {
      en: "Riel's trial and execution for high treason was a decision strongly opposed in Quebec.",
    },
    source: src("Canada's History: Challenge in the West"),
  },
  {
    id: "ppl-h-035",
    topicId: "people",
    difficulty: "hard",
    prompt: {
      en: "Louis Riel's second rebellion in 1885 took place in present-day which province?",
    },
    options: [{ en: "Saskatchewan" }, { en: "Manitoba" }, { en: "Alberta" }, { en: "Ontario" }],
    answerIndex: 0,
    explanation: {
      en: "A second rebellion in 1885 in present-day Saskatchewan led to Riel's trial and execution for high treason.",
    },
    source: src("Canada's History: Challenge in the West"),
  },
  {
    id: "ppl-h-036",
    topicId: "people",
    difficulty: "hard",
    prompt: {
      en: "Which of these cities began as a fort founded by the North West Mounted Police?",
    },
    options: [
      { en: "Regina" },
      { en: "Winnipeg" },
      { en: "Ottawa" },
      { en: "Calgary (Fort Calgary)" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The NWMP founded Fort Calgary and Fort MacLeod, which today are cities; Regina became the NWMP's headquarters rather than a fort it founded.",
    },
    source: src("Canada's History: Challenge in the West"),
  },
  {
    id: "ppl-h-037",
    topicId: "people",
    difficulty: "hard",
    prompt: {
      en: "The guide's 1886 photograph of a Chinese workers' camp on the CPR was taken at which location?",
    },
    options: [
      { en: "Glacier, B.C." },
      { en: "Winnipeg, Manitoba" },
      { en: "Kamloops, B.C." },
      { en: "Calgary, Alberta" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The guide shows a Chinese workers' camp on the CPR at Kamloops, B.C., in 1886.",
    },
    source: src("Canada's History: A Railway from Sea to Sea"),
  },
  {
    id: "ppl-h-038",
    topicId: "people",
    difficulty: "hard",
    prompt: {
      en: "Which of these battles was NOT fought by the Canadian Corps under General Sir Arthur Currie during the last hundred days of 1918?",
    },
    options: [{ en: "Amiens" }, { en: "Vimy Ridge" }, { en: "Arras" }, { en: "Mons" }],
    answerIndex: 1,
    explanation: {
      en: "Under Currie in the last hundred days the Corps fought at Amiens, Arras, Canal du Nord, Cambrai and Mons; Vimy Ridge was captured in April 1917.",
    },
    source: src("Canada's History: The First World War"),
  },
  {
    id: "ppl-h-039",
    topicId: "people",
    difficulty: "hard",
    prompt: {
      en: "The guide's caption describes the Battle of Vimy Ridge (April 9, 1917) as what?",
    },
    options: [
      { en: "The first British victory of the First World War" },
      { en: "The bloodiest battle of the war" },
      { en: "The last battle of the war" },
      { en: "The birth of the Royal Canadian Air Force" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The Vimy Memorial in France honours those who served and died in the Battle of Vimy Ridge on April 9, 1917, the first British victory of the First World War.",
    },
    source: src("Canada's History: The First World War"),
  },
  {
    id: "ppl-h-040",
    topicId: "people",
    difficulty: "hard",
    prompt: {
      en: "Lieutenant-Colonel John McCrae, who composed “In Flanders Fields” in 1915, served as a Canadian what?",
    },
    options: [
      { en: "Infantry general" },
      { en: "Naval captain" },
      { en: "War correspondent" },
      { en: "Medical officer" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Canadian medical officer Lieutenant-Colonel John McCrae composed the poem “In Flanders Fields” in 1915.",
    },
    source: src("Canada's History: Women Get the Vote"),
  },
  {
    id: "ppl-h-041",
    topicId: "people",
    difficulty: "hard",
    prompt: {
      en: "According to the guide, how many Canadians have given their lives in all wars, honoured each Remembrance Day?",
    },
    options: [{ en: "60,000" }, { en: "44,000" }, { en: "110,000" }, { en: "1,000,000" }],
    answerIndex: 2,
    explanation: {
      en: "Canadians observe a moment of silence to honour the sacrifices of over a million brave men and women who have served, and the 110,000 who have given their lives.",
    },
    source: src("Canada's History: Women Get the Vote"),
  },
  {
    id: "ppl-h-042",
    topicId: "people",
    difficulty: "hard",
    prompt: { en: "Of the more than 3,000 “Bluebird” nurses, how many served overseas?" },
    options: [{ en: "3,000" }, { en: "2,500" }, { en: "500" }, { en: "1,000" }],
    answerIndex: 1,
    explanation: {
      en: "More than 3,000 nurses, nicknamed “Bluebirds,” served in the Royal Canadian Army Medical Corps, 2,500 of them overseas.",
    },
    source: src("Canada's History: Women Get the Vote"),
  },
  {
    id: "ppl-h-043",
    topicId: "people",
    difficulty: "hard",
    prompt: { en: "In 1917, which women were the FIRST to be given the federal vote?" },
    options: [
      { en: "Nurses at the battle front" },
      { en: "Women related to men in active wartime service" },
      { en: "All women aged 21 and over" },
      { en: "Women in Quebec" },
    ],
    answerIndex: 0,
    explanation: {
      en: "In 1917 the federal government gave women the right to vote in federal elections — first to nurses at the battle front, then to women who were related to men in active wartime service.",
    },
    source: src("Canada's History: Women Get the Vote"),
  },
  {
    id: "ppl-h-044",
    topicId: "people",
    difficulty: "hard",
    prompt: {
      en: "Mathew Evans and Henry Woodward sold their light-bulb patent to Thomas Edison, who did what “more famously”?",
    },
    options: [
      { en: "Invented the telephone" },
      { en: "Built the first radio" },
      { en: "Discovered insulin" },
      { en: "Commercialized the light bulb" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Evans and Woodward together invented the first electric light bulb and later sold the patent to Thomas Edison who, more famously, commercialized the light bulb.",
    },
    source: src("Modern Canada: Great Canadian Discoveries and Inventions"),
  },
  {
    id: "ppl-h-045",
    topicId: "people",
    difficulty: "hard",
    prompt: { en: "Dr. Wilder Penfield was known by which nickname?" },
    options: [
      { en: "“Canada's greatest soldier”" },
      { en: "“The father of Manitoba”" },
      { en: "“The greatest living Canadian”" },
      { en: "“The hero of Queenston Heights”" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Dr. Wilder Penfield was a pioneering brain surgeon at McGill University in Montreal, and was known as “the greatest living Canadian.”",
    },
    source: src("Modern Canada: Great Canadian Discoveries and Inventions"),
  },
  {
    id: "ppl-h-046",
    topicId: "people",
    difficulty: "hard",
    prompt: {
      en: "Champlain allied with the Algonquin, Montagnais and Huron — historic enemies of which confederation?",
    },
    options: [{ en: "The Sioux" }, { en: "The Iroquois" }, { en: "The Cree" }, { en: "The Dene" }],
    answerIndex: 1,
    explanation: {
      en: "Champlain allied the colony with the Algonquin, Montagnais, and Huron, historic enemies of the Iroquois, a confederation of five (later six) First Nations.",
    },
    source: src("Canada's History: Royal New France"),
  },
  {
    id: "ppl-h-047",
    topicId: "people",
    difficulty: "hard",
    prompt: {
      en: "English settlement of Canada did not begin until which year, more than a century after Cabot's 1497 voyage?",
    },
    options: [{ en: "1610" }, { en: "1604" }, { en: "1608" }, { en: "1534" }],
    answerIndex: 0,
    explanation: {
      en: "English settlement did not begin until 1610, more than a century after Cabot's 1497 voyage.",
    },
    source: src("Canada's History: The First Europeans"),
  },
  {
    id: "ppl-h-048",
    topicId: "people",
    difficulty: "hard",
    prompt: { en: "Cartier's three voyages across the Atlantic spanned which years?" },
    options: [
      { en: "1497 to 1502" },
      { en: "1604 to 1608" },
      { en: "1534 to 1539" },
      { en: "1534 to 1542" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Between 1534 and 1542, Jacques Cartier made three voyages across the Atlantic.",
    },
    source: src("Canada's History: Exploring a River, Naming Canada"),
  },
  {
    id: "ppl-h-049",
    topicId: "people",
    difficulty: "hard",
    prompt: {
      en: "On January 21, 1793, the first elected Assembly of Lower Canada debated in Québec City whether to use which two languages?",
    },
    options: [
      { en: "French and Latin" },
      { en: "English and Gaelic" },
      { en: "French and English" },
      { en: "French and Mi'kmaq" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The first elected Assembly of Lower Canada, in Québec City, debated whether to use both French and English on January 21, 1793.",
    },
    source: src("Canada's History: The Beginnings of Democracy"),
  },
  {
    id: "ppl-h-050",
    topicId: "people",
    difficulty: "hard",
    prompt: {
      en: "In 1793 Upper Canada moved toward abolition under Simcoe; in which year did the British Parliament prohibit the buying and selling of slaves?",
    },
    options: [{ en: "1793" }, { en: "1807" }, { en: "1833" }, { en: "1774" }],
    answerIndex: 1,
    explanation: {
      en: "In 1807, the British Parliament prohibited the buying and selling of slaves, and in 1833 abolished slavery throughout the Empire.",
    },
    source: src("Canada's History: Abolition of Slavery"),
  },
];
