/**
 * Question bank chunk — part of questions.generated.ts. DO NOT EDIT BY HAND.
 */
import type { Question } from "../content";
import { src } from "./shared";

export const peopleA: Question[] = [
  {
    id: "ppl-e-001",
    topicId: "people",
    difficulty: "easy",
    prompt: { en: "Who was Canada's first Prime Minister?" },
    options: [
      { en: "Sir Wilfrid Laurier" },
      { en: "Sir Robert Borden" },
      { en: "John Diefenbaker" },
      { en: "Sir John A. Macdonald" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Sir John A. Macdonald, a Father of Confederation, became Canada's first Prime Minister in 1867.",
    },
    source: src("Canada's History: Canada's First Prime Minister"),
  },
  {
    id: "ppl-e-002",
    topicId: "people",
    difficulty: "easy",
    prompt: { en: "Sir John A. Macdonald's portrait appears on which Canadian banknote?" },
    options: [
      { en: "The $10 bill" },
      { en: "The $5 bill" },
      { en: "The $20 bill" },
      { en: "The $50 bill" },
    ],
    answerIndex: 0,
    explanation: { en: "Sir John A. Macdonald's portrait is on the $10 bill." },
    source: src("Canada's History: Canada's First Prime Minister"),
  },
  {
    id: "ppl-e-003",
    topicId: "people",
    difficulty: "easy",
    prompt: { en: "Parliament has recognized which date as Sir John A. Macdonald Day?" },
    options: [{ en: "July 1" }, { en: "January 11" }, { en: "November 11" }, { en: "October 6" }],
    answerIndex: 1,
    explanation: {
      en: "Parliament has recognized January 11, Macdonald's birthday, as Sir John A. Macdonald Day.",
    },
    source: src("Canada's History: Canada's First Prime Minister"),
  },
  {
    id: "ppl-e-004",
    topicId: "people",
    difficulty: "easy",
    prompt: { en: "Who hit on the idea of the telephone at his summer house in Canada?" },
    options: [
      { en: "Reginald Fessenden" },
      { en: "Sir Sandford Fleming" },
      { en: "Alexander Graham Bell" },
      { en: "Dr. John A. Hopps" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Alexander Graham Bell hit on the idea of the telephone at his summer house in Canada.",
    },
    source: src("Modern Canada: Great Canadian Discoveries and Inventions"),
  },
  {
    id: "ppl-e-005",
    topicId: "people",
    difficulty: "easy",
    prompt: { en: "Whose 1497 expedition was the first to draw a map of Canada's East Coast?" },
    options: [
      { en: "Jacques Cartier" },
      { en: "Samuel de Champlain" },
      { en: "Pierre de Monts" },
      { en: "John Cabot" },
    ],
    answerIndex: 3,
    explanation: {
      en: "European exploration began in earnest in 1497 with the expedition of John Cabot, the first to draw a map of Canada's East Coast.",
    },
    source: src("Canada's History: The First Europeans"),
  },
  {
    id: "ppl-e-006",
    topicId: "people",
    difficulty: "easy",
    prompt: {
      en: "John Cabot, an Italian immigrant to England, claimed the “New Founde Land” for which country?",
    },
    options: [{ en: "England" }, { en: "France" }, { en: "Spain" }, { en: "Portugal" }],
    answerIndex: 0,
    explanation: {
      en: "Cabot set foot on Newfoundland or Cape Breton Island in 1497 and claimed the New Founde Land for England.",
    },
    source: src("Canada's History: The First Europeans"),
  },
  {
    id: "ppl-e-007",
    topicId: "people",
    difficulty: "easy",
    prompt: {
      en: "Between 1534 and 1542, who made three voyages across the Atlantic, claiming land for King Francis I of France?",
    },
    options: [
      { en: "John Cabot" },
      { en: "Jacques Cartier" },
      { en: "Samuel de Champlain" },
      { en: "Pierre Le Moyne, Sieur d'Iberville" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Between 1534 and 1542, Jacques Cartier made three voyages across the Atlantic, claiming the land for King Francis I of France.",
    },
    source: src("Canada's History: Exploring a River, Naming Canada"),
  },
  {
    id: "ppl-e-008",
    topicId: "people",
    difficulty: "easy",
    prompt: { en: "Jacques Cartier was the first European to explore which river?" },
    options: [
      { en: "The Ottawa River" },
      { en: "The Fraser River" },
      { en: "The St. Lawrence River" },
      { en: "The Mackenzie River" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Jacques Cartier was the first European to explore the St. Lawrence River and to set eyes on present-day Québec City and Montreal.",
    },
    source: src("Canada's History: Exploring a River, Naming Canada"),
  },
  {
    id: "ppl-e-009",
    topicId: "people",
    difficulty: "easy",
    prompt: {
      en: "Cartier heard his captured guides use the Iroquoian word “kanata.” What does it mean?",
    },
    options: [{ en: "“River”" }, { en: "“King”" }, { en: "“Land”" }, { en: "“Village”" }],
    answerIndex: 3,
    explanation: {
      en: "Cartier heard two captured guides speak the Iroquoian word kanata, meaning “village,” from which the name Canada began appearing on maps by the 1550s.",
    },
    source: src("Canada's History: Exploring a River, Naming Canada"),
  },
  {
    id: "ppl-e-010",
    topicId: "people",
    difficulty: "easy",
    prompt: { en: "In 1608, who built a fortress at what is now Québec City?" },
    options: [
      { en: "Samuel de Champlain" },
      { en: "Jacques Cartier" },
      { en: "Pierre de Monts" },
      { en: "Count Frontenac" },
    ],
    answerIndex: 0,
    explanation: { en: "In 1608 Champlain built a fortress at what is now Québec City." },
    source: src("Canada's History: Royal New France"),
  },
  {
    id: "ppl-e-011",
    topicId: "people",
    difficulty: "easy",
    prompt: {
      en: "In 1604, the first European settlement north of Florida was established at St. Croix Island and then Port-Royal by whom?",
    },
    options: [
      { en: "John Cabot and Jacques Cartier" },
      { en: "Pierre de Monts and Samuel de Champlain" },
      { en: "Jean Talon and Bishop Laval" },
      { en: "Count Frontenac and Pierre Le Moyne" },
    ],
    answerIndex: 1,
    explanation: {
      en: "In 1604, the first European settlement north of Florida was established by French explorers Pierre de Monts and Samuel de Champlain, first on St. Croix Island, then at Port-Royal in Acadia.",
    },
    source: src("Canada's History: Royal New France"),
  },
  {
    id: "ppl-e-012",
    topicId: "people",
    difficulty: "easy",
    prompt: {
      en: "At the Battle of the Plains of Abraham in 1759, which two commanders were killed leading their troops?",
    },
    options: [
      { en: "Sir Isaac Brock and Chief Tecumseh" },
      { en: "Charles de Salaberry and James FitzGibbon" },
      { en: "Brigadier James Wolfe and the Marquis de Montcalm" },
      { en: "Robert Ross and Arthur Currie" },
    ],
    answerIndex: 2,
    explanation: {
      en: "In 1759, the British defeated the French in the Battle of the Plains of Abraham at Québec City; the commanders of both armies, Brigadier James Wolfe and the Marquis de Montcalm, were killed leading their troops.",
    },
    source: src("Canada's History: Struggle for a Continent"),
  },
  {
    id: "ppl-e-013",
    topicId: "people",
    difficulty: "easy",
    prompt: {
      en: "The British victory at the Plains of Abraham in 1759 marked the end of whose empire in America?",
    },
    options: [
      { en: "Spain's empire" },
      { en: "Portugal's empire" },
      { en: "The Netherlands' empire" },
      { en: "France's empire" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The 1759 British victory at the Plains of Abraham marked the end of France's empire in America.",
    },
    source: src("Canada's History: Struggle for a Continent"),
  },
  {
    id: "ppl-e-014",
    topicId: "people",
    difficulty: "easy",
    prompt: {
      en: "In 1690, who refused to surrender Quebec to the English, declaring, “My only reply will be from the mouths of my cannons!”?",
    },
    options: [
      { en: "Count Frontenac" },
      { en: "Sir Guy Carleton" },
      { en: "The Marquis de Montcalm" },
      { en: "Pierre Le Moyne, Sieur d'Iberville" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Count Frontenac refused to surrender Quebec to the English in 1690, saying: “My only reply will be from the mouths of my cannons!”",
    },
    source: src("Canada's History: Royal New France"),
  },
  {
    id: "ppl-e-015",
    topicId: "people",
    difficulty: "easy",
    prompt: {
      en: "As Governor of Quebec, Sir Guy Carleton (Lord Dorchester) is noted for which achievement?",
    },
    options: [
      { en: "Driving the last spike of the Canadian Pacific Railway" },
      {
        en: "Defending the rights of the Canadiens and defeating an American invasion of Quebec in 1775",
      },
      { en: "Founding the city of York, now Toronto" },
      { en: "Discovering insulin with Charles Best" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Sir Guy Carleton (Lord Dorchester), as Governor of Quebec, defended the rights of the Canadiens and defeated an American military invasion of Quebec in 1775.",
    },
    source: src("Canada's History: Royal New France"),
  },
  {
    id: "ppl-e-016",
    topicId: "people",
    difficulty: "easy",
    prompt: {
      en: "In July 1812 Major-General Sir Isaac Brock captured Detroit, but he was killed defending against an American attack at which battle?",
    },
    options: [
      { en: "The Plains of Abraham" },
      { en: "Châteauguay" },
      { en: "Queenston Heights, near Niagara Falls" },
      { en: "Beaver Dams" },
    ],
    answerIndex: 2,
    explanation: {
      en: "In July, Major-General Sir Isaac Brock captured Detroit but was killed while defending against an American attack at Queenston Heights, near Niagara Falls, a battle the Americans lost.",
    },
    source: src("Canada's History: The War of 1812: The Fight for Canada"),
  },
  {
    id: "ppl-e-017",
    topicId: "people",
    difficulty: "easy",
    prompt: {
      en: "Which Shawnee chief led First Nations supporting British soldiers in Canada's defence during the War of 1812?",
    },
    options: [
      { en: "Joseph Brant" },
      { en: "Gabriel Dumont" },
      { en: "Louis Riel" },
      { en: "Chief Tecumseh" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Canadian volunteers and First Nations, including Shawnee led by Chief Tecumseh, supported British soldiers in Canada's defence.",
    },
    source: src("Canada's History: The War of 1812: The Fight for Canada"),
  },
  {
    id: "ppl-e-018",
    topicId: "people",
    difficulty: "easy",
    prompt: {
      en: "In 1813, Lieutenant-Colonel Charles de Salaberry and 460 soldiers, mostly French Canadiens, turned back how many American invaders at Châteauguay?",
    },
    options: [{ en: "4,000" }, { en: "460" }, { en: "1,812" }, { en: "10,000" }],
    answerIndex: 0,
    explanation: {
      en: "In 1813, Lieutenant-Colonel Charles de Salaberry and 460 soldiers, mostly French Canadiens, turned back 4,000 American invaders at Châteauguay, south of Montreal.",
    },
    source: src("Canada's History: The War of 1812: The Fight for Canada"),
  },
  {
    id: "ppl-e-019",
    topicId: "people",
    difficulty: "easy",
    prompt: {
      en: "In 1813, who made a dangerous 19-mile (30 km) journey on foot to warn Lieutenant James FitzGibbon of a planned American attack?",
    },
    options: [
      { en: "Mary Ann Shadd Cary" },
      { en: "Laura Secord" },
      { en: "Agnes Macphail" },
      { en: "Dr. Emily Stowe" },
    ],
    answerIndex: 1,
    explanation: {
      en: "In 1813, Laura Secord, pioneer wife and mother of five children, made a dangerous 19-mile (30 km) journey on foot to warn Lieutenant James FitzGibbon of a planned American attack.",
    },
    source: src("Canada's History: The War of 1812: The Fight for Canada"),
  },
  {
    id: "ppl-e-020",
    topicId: "people",
    difficulty: "easy",
    prompt: {
      en: "In retaliation for the burning of York in 1813, whose 1814 expedition burned down the White House in Washington, D.C.?",
    },
    options: [
      { en: "Major-General Sir Isaac Brock" },
      { en: "The Duke of Wellington" },
      { en: "Major-General Robert Ross" },
      { en: "General Sir Arthur Currie" },
    ],
    answerIndex: 2,
    explanation: {
      en: "In retaliation in 1814, Major-General Robert Ross led an expedition from Nova Scotia that burned down the White House and other public buildings in Washington, D.C.",
    },
    source: src("Canada's History: The War of 1812: The Fight for Canada"),
  },
  {
    id: "ppl-e-021",
    topicId: "people",
    difficulty: "easy",
    prompt: {
      en: "Who led thousands of Loyalist Mohawk Indians into Canada after the American Revolution?",
    },
    options: [
      { en: "Chief Tecumseh" },
      { en: "Gabriel Dumont" },
      { en: "Louis Riel" },
      { en: "Joseph Brant" },
    ],
    answerIndex: 3,
    explanation: { en: "Joseph Brant led thousands of Loyalist Mohawk Indians into Canada." },
    source: src("Canada's History: United Empire Loyalists"),
  },
  {
    id: "ppl-e-022",
    topicId: "people",
    difficulty: "easy",
    prompt: {
      en: "Who was Upper Canada's first Lieutenant Governor and founder of the City of York (now Toronto)?",
    },
    options: [
      { en: "John Graves Simcoe" },
      { en: "Sir Guy Carleton" },
      { en: "Lord Elgin" },
      { en: "Lord Durham" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Lieutenant Governor John Graves Simcoe was Upper Canada's first Lieutenant Governor and founder of the City of York (now Toronto).",
    },
    source: src("Canada's History: Abolition of Slavery"),
  },
  {
    id: "ppl-e-023",
    topicId: "people",
    difficulty: "easy",
    prompt: {
      en: "In 1793, Upper Canada became the first province in the British Empire to do what?",
    },
    options: [
      { en: "Grant women the right to vote" },
      { en: "Move toward the abolition of slavery" },
      { en: "Establish responsible government" },
      { en: "Join Confederation" },
    ],
    answerIndex: 1,
    explanation: {
      en: "In 1793, Upper Canada, led by Lieutenant Governor John Graves Simcoe, became the first province in the Empire to move toward abolition.",
    },
    source: src("Canada's History: Abolition of Slavery"),
  },
  {
    id: "ppl-e-024",
    topicId: "people",
    difficulty: "easy",
    prompt: {
      en: "In 1853, who became the first woman publisher in Canada, helping to found and edit The Provincial Freeman?",
    },
    options: [
      { en: "Agnes Macphail" },
      { en: "Dr. Emily Stowe" },
      { en: "Mary Ann Shadd Cary" },
      { en: "Thérèse Casgrain" },
    ],
    answerIndex: 2,
    explanation: {
      en: "In 1853 Mary Ann Shadd Cary became the first woman publisher in Canada, helping to found and edit The Provincial Freeman, a weekly newspaper dedicated to anti-slavery and other causes.",
    },
    source: src("Canada's History: Abolition of Slavery"),
  },
  {
    id: "ppl-e-025",
    topicId: "people",
    difficulty: "easy",
    prompt: { en: "The Duke of Wellington chose Bytown (Ottawa) as the endpoint of which canal?" },
    options: [
      { en: "The Lachine Canal" },
      { en: "The Welland Canal" },
      { en: "The Erie Canal" },
      { en: "The Rideau Canal" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The Duke of Wellington chose Bytown (Ottawa) as the endpoint of the Rideau Canal, part of a network of forts to prevent the U.S.A. from invading Canada again.",
    },
    source: src("Canada's History: The War of 1812: The Fight for Canada"),
  },
  {
    id: "ppl-e-026",
    topicId: "people",
    difficulty: "easy",
    prompt: {
      en: "Laura Secord's 1813 warning to Lieutenant FitzGibbon contributed to victory at which battle?",
    },
    options: [
      { en: "The Battle of Beaver Dams" },
      { en: "The Battle of Châteauguay" },
      { en: "The Battle of Queenston Heights" },
      { en: "The Battle of Vimy Ridge" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Her bravery contributed to victory at the Battle of Beaver Dams, and she is recognized as a heroine to this day.",
    },
    source: src("Canada's History: The War of 1812: The Fight for Canada"),
  },
  {
    id: "ppl-e-027",
    topicId: "people",
    difficulty: "easy",
    prompt: { en: "After the rebellions of 1837–38, Lord Durham recommended which two reforms?" },
    options: [
      { en: "Granting immediate independence to both Canadas" },
      { en: "Merging Upper and Lower Canada and granting responsible government" },
      { en: "Adopting American republican values and joining the United States" },
      { en: "Abolishing the elected legislative assemblies" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Lord Durham recommended that Upper and Lower Canada be merged and given responsible government, meaning ministers of the Crown must have the support of a majority of the elected representatives.",
    },
    source: src("Canada's History: Rebellions of 1837–38"),
  },
  {
    id: "ppl-e-028",
    topicId: "people",
    difficulty: "easy",
    prompt: {
      en: "Sir Louis-Hippolyte La Fontaine, a champion of French language rights, became what in 1849?",
    },
    options: [
      { en: "Canada's first Prime Minister" },
      { en: "The first Governor General of Canada" },
      { en: "The first leader of a responsible government in the Canadas" },
      { en: "The founder of the North West Mounted Police" },
    ],
    answerIndex: 2,
    explanation: {
      en: "La Fontaine, a champion of democracy and French language rights, became the first leader of a responsible government in the Canadas in 1849.",
    },
    source: src("Canada's History: Responsible Government"),
  },
  {
    id: "ppl-e-029",
    topicId: "people",
    difficulty: "easy",
    prompt: {
      en: "Which was the first British North American colony to attain full responsible government, in 1847–48?",
    },
    options: [
      { en: "Upper Canada" },
      { en: "Lower Canada" },
      { en: "New Brunswick" },
      { en: "Nova Scotia" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The first British North American colony to attain full responsible government was Nova Scotia in 1847–48.",
    },
    source: src("Canada's History: Responsible Government"),
  },
  {
    id: "ppl-e-030",
    topicId: "people",
    difficulty: "easy",
    prompt: { en: "The Dominion of Canada was officially born on which date?" },
    options: [
      { en: "July 1, 1867" },
      { en: "July 4, 1776" },
      { en: "November 11, 1918" },
      { en: "May 8, 1945" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The British Parliament passed the British North America Act in 1867, and the Dominion of Canada was officially born on July 1, 1867.",
    },
    source: src("Canada's History: Confederation"),
  },
  {
    id: "ppl-e-031",
    topicId: "people",
    difficulty: "easy",
    prompt: { en: "Which British Act created the Dominion of Canada in 1867?" },
    options: [
      { en: "The Quebec Act" },
      { en: "The British North America Act" },
      { en: "The Constitutional Act" },
      { en: "The Official Languages Act" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The British Parliament passed the British North America Act in 1867, creating the Dominion of Canada.",
    },
    source: src("Canada's History: Confederation"),
  },
  {
    id: "ppl-e-032",
    topicId: "people",
    difficulty: "easy",
    prompt: { en: "Which four provinces formed the new Dominion of Canada in 1867?" },
    options: [
      { en: "Ontario, Quebec, Manitoba and British Columbia" },
      { en: "Ontario, Quebec, Alberta and Saskatchewan" },
      { en: "Ontario, Quebec, New Brunswick and Nova Scotia" },
      { en: "Nova Scotia, New Brunswick, Prince Edward Island and Newfoundland" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The old Province of Canada was split into Ontario and Quebec, which, together with New Brunswick and Nova Scotia, formed the new Dominion of Canada.",
    },
    source: src("Canada's History: Confederation"),
  },
  {
    id: "ppl-e-033",
    topicId: "people",
    difficulty: "easy",
    prompt: { en: "Who is described as the key architect of Confederation from Quebec?" },
    options: [
      { en: "Sir Wilfrid Laurier" },
      { en: "Louis Riel" },
      { en: "Joseph Howe" },
      { en: "Sir George-Étienne Cartier" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Sir George-Étienne Cartier was the key architect of Confederation from Quebec, leading Quebec into Confederation.",
    },
    source: src("Canada's History: Canada's First Prime Minister"),
  },
  {
    id: "ppl-e-034",
    topicId: "people",
    difficulty: "easy",
    prompt: {
      en: "Who suggested the term “Dominion of Canada” in 1864, inspired by Psalm 72's “dominion from sea to sea”?",
    },
    options: [
      { en: "Sir Leonard Tilley" },
      { en: "Sir John A. Macdonald" },
      { en: "Sir George-Étienne Cartier" },
      { en: "Lord Durham" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Sir Leonard Tilley, an elected official and Father of Confederation from New Brunswick, suggested the term Dominion of Canada in 1864, inspired by Psalm 72.",
    },
    source: src("Canada's History: Dominion from Sea to Sea"),
  },
  {
    id: "ppl-e-035",
    topicId: "people",
    difficulty: "easy",
    prompt: { en: "Who drove the last spike of the Canadian Pacific Railway on November 7, 1885?" },
    options: [
      { en: "Sir John A. Macdonald" },
      { en: "Donald Smith (Lord Strathcona)" },
      { en: "Sir Sandford Fleming" },
      { en: "Sir Wilfrid Laurier" },
    ],
    answerIndex: 1,
    explanation: {
      en: "On November 7, 1885, Donald Smith (Lord Strathcona), the Scottish-born director of the Canadian Pacific Railway, drove the last spike.",
    },
    source: src("Canada's History: A Railway from Sea to Sea"),
  },
  {
    id: "ppl-e-036",
    topicId: "people",
    difficulty: "easy",
    prompt: { en: "Who became the first French-Canadian prime minister since Confederation?" },
    options: [
      { en: "Sir John A. Macdonald" },
      { en: "Louis Riel" },
      { en: "Sir Wilfrid Laurier" },
      { en: "Sir George-Étienne Cartier" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Sir Wilfrid Laurier became the first French-Canadian prime minister since Confederation and encouraged immigration to the West.",
    },
    source: src("Canada's History: Moving Westward"),
  },
  {
    id: "ppl-e-037",
    topicId: "people",
    difficulty: "easy",
    prompt: { en: "Sir Wilfrid Laurier's portrait appears on which Canadian banknote?" },
    options: [
      { en: "The $10 bill" },
      { en: "The $20 bill" },
      { en: "The $100 bill" },
      { en: "The $5 bill" },
    ],
    answerIndex: 3,
    explanation: { en: "Sir Wilfrid Laurier's portrait is on the $5 bill." },
    source: src("Canada's History: Moving Westward"),
  },
  {
    id: "ppl-e-038",
    topicId: "people",
    difficulty: "easy",
    prompt: { en: "Sir Wilfrid Laurier was which number Prime Minister of Canada?" },
    options: [{ en: "The 7th" }, { en: "The 1st" }, { en: "The 13th" }, { en: "The 10th" }],
    answerIndex: 0,
    explanation: { en: "The guide lists Sir Wilfrid Laurier as the 7th Prime Minister of Canada." },
    source: src("Memorable Quotes"),
  },
  {
    id: "ppl-e-039",
    topicId: "people",
    difficulty: "easy",
    prompt: { en: "John Diefenbaker was which number Prime Minister of Canada?" },
    options: [{ en: "The 7th" }, { en: "The 13th" }, { en: "The 1st" }, { en: "The 3rd" }],
    answerIndex: 1,
    explanation: { en: "The guide lists John Diefenbaker as the 13th Prime Minister of Canada." },
    source: src("Memorable Quotes"),
  },
  {
    id: "ppl-e-040",
    topicId: "people",
    difficulty: "easy",
    prompt: { en: "Which Canadian company created the BlackBerry?" },
    options: [
      { en: "Nortel" },
      { en: "Bombardier" },
      { en: "Research in Motion (RIM)" },
      { en: "Corel" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Mike Lazaridis and Jim Balsillie of Research in Motion (RIM), a wireless communications company, created the BlackBerry.",
    },
    source: src("Modern Canada: Great Canadian Discoveries and Inventions"),
  },
  {
    id: "ppl-e-041",
    topicId: "people",
    difficulty: "easy",
    prompt: {
      en: "Who said: “I would build a nation great among the nations of the world,” speaking of marble, granite and oak?",
    },
    options: [
      { en: "John Diefenbaker" },
      { en: "Sir Arthur Currie" },
      { en: "Lord Tweedsmuir" },
      { en: "Sir Wilfrid Laurier" },
    ],
    answerIndex: 3,
    explanation: {
      en: "This is the memorable quote of Sir Wilfrid Laurier, 7th Prime Minister of Canada.",
    },
    source: src("Memorable Quotes"),
  },
  {
    id: "ppl-e-042",
    topicId: "people",
    difficulty: "easy",
    prompt: {
      en: "Louis Riel is seen by many as a hero, a defender of Métis rights, and the father of which province?",
    },
    options: [{ en: "Manitoba" }, { en: "Saskatchewan" }, { en: "Alberta" }, { en: "Ontario" }],
    answerIndex: 0,
    explanation: {
      en: "Riel is seen by many as a hero, a defender of Métis rights and the father of Manitoba.",
    },
    source: src("Canada's History: Challenge in the West"),
  },
  {
    id: "ppl-e-043",
    topicId: "people",
    difficulty: "easy",
    prompt: { en: "Louis Riel was tried and executed in 1885 for which crime?" },
    options: [{ en: "Murder" }, { en: "High treason" }, { en: "Piracy" }, { en: "Espionage" }],
    answerIndex: 1,
    explanation: {
      en: "A second rebellion in 1885 in present-day Saskatchewan led to Riel's trial and execution for high treason.",
    },
    source: src("Canada's History: Challenge in the West"),
  },
  {
    id: "ppl-e-044",
    topicId: "people",
    difficulty: "easy",
    prompt: { en: "Who was the Métis' greatest military leader?" },
    options: [
      { en: "Louis Riel" },
      { en: "Joseph Brant" },
      { en: "Gabriel Dumont" },
      { en: "Chief Tecumseh" },
    ],
    answerIndex: 2,
    explanation: { en: "Gabriel Dumont was the Métis' greatest military leader." },
    source: src("Canada's History: Challenge in the West"),
  },
  {
    id: "ppl-e-045",
    topicId: "people",
    difficulty: "easy",
    prompt: {
      en: "Prime Minister Macdonald established the North West Mounted Police in which year?",
    },
    options: [{ en: "1867" }, { en: "1885" }, { en: "1905" }, { en: "1873" }],
    answerIndex: 3,
    explanation: {
      en: "After the first Métis uprising, Prime Minister Macdonald established the North West Mounted Police (NWMP) in 1873.",
    },
    source: src("Canada's History: Challenge in the West"),
  },
  {
    id: "ppl-e-046",
    topicId: "people",
    difficulty: "easy",
    prompt: { en: "Which city became the headquarters of the North West Mounted Police?" },
    options: [{ en: "Regina" }, { en: "Calgary" }, { en: "Winnipeg" }, { en: "Edmonton" }],
    answerIndex: 0,
    explanation: {
      en: "The NWMP founded Fort Calgary, Fort MacLeod and other centres; Regina became its headquarters.",
    },
    source: src("Canada's History: Challenge in the West"),
  },
  {
    id: "ppl-e-047",
    topicId: "people",
    difficulty: "easy",
    prompt: {
      en: "Which Mounted Policeman is described as “a great frontier hero,” a “Mounted Policeman, and soldier of the Queen”?",
    },
    options: [
      { en: "Sir John A. Macdonald" },
      { en: "Major General Sir Sam Steele" },
      { en: "Donald Smith" },
      { en: "Sir Arthur Currie" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Major General Sir Sam Steele is described as a great frontier hero, Mounted Policeman, and soldier of the Queen.",
    },
    source: src("Canada's History: Challenge in the West"),
  },
  {
    id: "ppl-e-048",
    topicId: "people",
    difficulty: "easy",
    prompt: { en: "Today, the Royal Canadian Mounted Police (the “Mounties”) serve as what?" },
    options: [
      { en: "The Prime Minister's personal guard" },
      { en: "Ontario's provincial police" },
      { en: "Canada's national police force" },
      { en: "Canada's border agency" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Today, the Royal Canadian Mounted Police (RCMP or “the Mounties”) are the national police force and one of Canada's best-known symbols.",
    },
    source: src("Canada's History: Challenge in the West"),
  },
  {
    id: "ppl-e-049",
    topicId: "people",
    difficulty: "easy",
    prompt: { en: "Sir Frederick Banting of Toronto and Charles Best discovered what?" },
    options: [
      { en: "The cardiac pacemaker" },
      { en: "The electric light bulb" },
      { en: "The world system of standard time zones" },
      { en: "Insulin, a hormone to treat diabetes" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Sir Frederick Banting of Toronto and Charles Best discovered Insulin, a hormone to treat diabetes that has saved 16 million lives worldwide.",
    },
    source: src("Modern Canada: Great Canadian Discoveries and Inventions"),
  },
  {
    id: "ppl-e-050",
    topicId: "people",
    difficulty: "easy",
    prompt: { en: "Who invented the snowmobile, a light-weight winter vehicle?" },
    options: [
      { en: "Joseph-Armand Bombardier" },
      { en: "Alexander Graham Bell" },
      { en: "Mike Lazaridis" },
      { en: "Reginald Fessenden" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Joseph-Armand Bombardier invented the snowmobile, a light-weight winter vehicle.",
    },
    source: src("Modern Canada: Great Canadian Discoveries and Inventions"),
  },
  {
    id: "ppl-e-051",
    topicId: "people",
    difficulty: "easy",
    prompt: {
      en: "Who was the pioneering brain surgeon at McGill University known as “the greatest living Canadian”?",
    },
    options: [
      { en: "Charles Best" },
      { en: "Wilder Penfield" },
      { en: "Frederick Banting" },
      { en: "Reginald Fessenden" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Dr. Wilder Penfield was a pioneering brain surgeon at McGill University in Montreal, known as “the greatest living Canadian.”",
    },
    source: src("Modern Canada: Great Canadian Discoveries and Inventions"),
  },
  {
    id: "ppl-e-052",
    topicId: "people",
    difficulty: "easy",
    prompt: {
      en: "Who invented the first electric light bulb and later sold the patent to Thomas Edison?",
    },
    options: [
      { en: "Alexander Graham Bell and Charles Best" },
      { en: "Joseph-Armand Bombardier and John Hopps" },
      { en: "Mathew Evans and Henry Woodward" },
      { en: "Reginald Fessenden and Wilder Penfield" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Mathew Evans and Henry Woodward together invented the first electric light bulb and later sold the patent to Thomas Edison.",
    },
    source: src("Modern Canada: Great Canadian Discoveries and Inventions"),
  },
  {
    id: "ppl-e-053",
    topicId: "people",
    difficulty: "easy",
    prompt: { en: "Reginald Fessenden contributed to the invention of radio by doing what first?" },
    options: [
      { en: "Building the first television set" },
      { en: "Inventing the telephone" },
      { en: "Launching a communications satellite" },
      { en: "Sending the first wireless voice message in the world" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Reginald Fessenden contributed to the invention of radio, sending the first wireless voice message in the world.",
    },
    source: src("Modern Canada: Great Canadian Discoveries and Inventions"),
  },
  {
    id: "ppl-e-054",
    topicId: "people",
    difficulty: "easy",
    prompt: {
      en: "Dr. Wilder Penfield was a pioneering brain surgeon at which university, and was known as “the greatest living Canadian”?",
    },
    options: [
      { en: "McGill University in Montreal" },
      { en: "The University of Toronto" },
      { en: "McMaster University" },
      { en: "The University of British Columbia" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Dr. Wilder Penfield was a pioneering brain surgeon at McGill University in Montreal, and was known as “the greatest living Canadian.”",
    },
    source: src("Modern Canada: Great Canadian Discoveries and Inventions"),
  },
  {
    id: "ppl-e-055",
    topicId: "people",
    difficulty: "easy",
    prompt: { en: "Who invented the first cardiac pacemaker?" },
    options: [
      { en: "Dr. Wilder Penfield" },
      { en: "Dr. John A. Hopps" },
      { en: "Sir Frederick Banting" },
      { en: "Charles Best" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Dr. John A. Hopps invented the first cardiac pacemaker, used today to save the lives of people with heart disorders.",
    },
    source: src("Modern Canada: Great Canadian Discoveries and Inventions"),
  },
  {
    id: "ppl-e-056",
    topicId: "people",
    difficulty: "easy",
    prompt: { en: "The Canadarm, a robotic arm used in outer space, was invented by whom?" },
    options: [
      { en: "Research in Motion" },
      { en: "The Canadian Space Agency alone" },
      { en: "SPAR Aerospace / National Research Council" },
      { en: "Bell Laboratories" },
    ],
    answerIndex: 2,
    explanation: {
      en: "SPAR Aerospace / National Research Council invented the Canadarm, a robotic arm used in outer space.",
    },
    source: src("Modern Canada: Great Canadian Discoveries and Inventions"),
  },
  {
    id: "ppl-e-057",
    topicId: "people",
    difficulty: "easy",
    prompt: {
      en: "Mike Lazaridis and Jim Balsillie founded which wireless communications company, known for the BlackBerry?",
    },
    options: [
      { en: "Nortel" },
      { en: "SPAR Aerospace" },
      { en: "Bombardier" },
      { en: "Research in Motion (RIM)" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Mike Lazaridis and Jim Balsillie of Research in Motion (RIM), a wireless communications company known for its most famous invention, the BlackBerry.",
    },
    source: src("Modern Canada: Great Canadian Discoveries and Inventions"),
  },
  {
    id: "ppl-e-058",
    topicId: "people",
    difficulty: "easy",
    prompt: {
      en: "The Group of Seven, founded in 1920, developed a style of painting to capture what?",
    },
    options: [
      { en: "Canada's rugged wilderness landscapes" },
      { en: "Portraits of prime ministers" },
      { en: "Abstract city scenes" },
      { en: "Inuit soapstone carvings" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The Group of Seven, founded in 1920, developed a style of painting to capture the rugged wilderness landscapes.",
    },
    source: src("Modern Canada: Arts and Culture in Canada"),
  },
  {
    id: "ppl-e-059",
    topicId: "people",
    difficulty: "easy",
    prompt: { en: "Emily Carr painted the forests and Aboriginal artifacts of which region?" },
    options: [
      { en: "The Maritimes" },
      { en: "The West Coast" },
      { en: "The Prairies" },
      { en: "The Arctic" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Emily Carr painted the forests and Aboriginal artifacts of the West Coast.",
    },
    source: src("Modern Canada: Arts and Culture in Canada"),
  },
  {
    id: "ppl-e-060",
    topicId: "people",
    difficulty: "easy",
    prompt: {
      en: "Jean-Paul Riopelle was most notably associated with which pioneering art movement?",
    },
    options: [
      { en: "The Group of Seven" },
      { en: "The Hudson River School" },
      { en: "Les Automatistes of Quebec, pioneers of modern abstract art in the 1950s" },
      { en: "The Impressionists of Montreal" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Les Automatistes of Quebec were pioneers of modern abstract art in the 1950s, most notably Jean-Paul Riopelle.",
    },
    source: src("Modern Canada: Arts and Culture in Canada"),
  },
  {
    id: "ppl-e-061",
    topicId: "people",
    difficulty: "easy",
    prompt: { en: "Kenojuak Ashevak pioneered modern Inuit art with which media?" },
    options: [
      { en: "Oil portraits and murals" },
      { en: "Bronze statues" },
      { en: "Watercolour landscapes" },
      { en: "Etchings, prints and soapstone sculptures" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Kenojuak Ashevak pioneered modern Inuit art with etchings, prints and soapstone sculptures.",
    },
    source: src("Modern Canada: Arts and Culture in Canada"),
  },
  {
    id: "ppl-e-062",
    topicId: "people",
    difficulty: "easy",
    prompt: { en: "Louis-Philippe Hébert of Quebec was a celebrated sculptor of what?" },
    options: [
      { en: "Historical figures" },
      { en: "Inuit soapstone animals" },
      { en: "Abstract steel forms" },
      { en: "Totem poles" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Quebec's Louis-Philippe Hébert was a celebrated sculptor of historical figures.",
    },
    source: src("Modern Canada: Arts and Culture in Canada"),
  },
  {
    id: "ppl-e-063",
    topicId: "people",
    difficulty: "easy",
    prompt: { en: "Basketball was invented in 1891 by which Canadian?" },
    options: [
      { en: "Wayne Gretzky" },
      { en: "James Naismith" },
      { en: "Paul Henderson" },
      { en: "Donovan Bailey" },
    ],
    answerIndex: 1,
    explanation: { en: "Basketball was invented by Canadian James Naismith in 1891." },
    source: src("Modern Canada: Arts and Culture in Canada"),
  },
  {
    id: "ppl-e-064",
    topicId: "people",
    difficulty: "easy",
    prompt: {
      en: "In 1972, Paul Henderson scored the winning goal for Canada in which famous event?",
    },
    options: [
      { en: "The Stanley Cup Final" },
      { en: "The 1972 Winter Olympics" },
      { en: "The Canada-Soviet Summit Series" },
      { en: "The Grey Cup" },
    ],
    answerIndex: 2,
    explanation: {
      en: "In 1972, Paul Henderson scored the winning goal for Canada in the Canada-Soviet Summit Series, often called “the goal heard around the world.”",
    },
    source: src("Modern Canada: Arts and Culture in Canada"),
  },
  {
    id: "ppl-e-065",
    topicId: "people",
    difficulty: "easy",
    prompt: {
      en: "Wayne Gretzky, one of the greatest hockey players of all time, played for the Edmonton Oilers during which years?",
    },
    options: [
      { en: "1988 to 1996" },
      { en: "1972 to 1979" },
      { en: "1996 to 2002" },
      { en: "1979 to 1988" },
    ],
    answerIndex: 3,
    explanation: {
      en: "One of the greatest hockey players of all time, Wayne Gretzky, played for the Edmonton Oilers from 1979 to 1988.",
    },
    source: src("Modern Canada: Arts and Culture in Canada"),
  },
  {
    id: "ppl-e-066",
    topicId: "people",
    difficulty: "easy",
    prompt: {
      en: "In 1996, Donovan Bailey became a world record sprinter and double Olympic gold medallist at which Games?",
    },
    options: [
      { en: "The Olympic Summer Games" },
      { en: "The Olympic Winter Games" },
      { en: "The Commonwealth Games" },
      { en: "The Pan American Games" },
    ],
    answerIndex: 0,
    explanation: {
      en: "In 1996 at the Olympic Summer Games, Donovan Bailey became a world record sprinter and double Olympic gold medallist.",
    },
    source: src("Modern Canada: Arts and Culture in Canada"),
  },
  {
    id: "ppl-e-067",
    topicId: "people",
    difficulty: "easy",
    prompt: { en: "Chantal Petitclerc is celebrated as a world champion in which discipline?" },
    options: [
      { en: "Figure skating" },
      { en: "Wheelchair racing" },
      { en: "Downhill skiing" },
      { en: "Marathon swimming" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Chantal Petitclerc became a world champion wheelchair racer and Paralympic gold medalist.",
    },
    source: src("Modern Canada: Arts and Culture in Canada"),
  },
  {
    id: "ppl-e-068",
    topicId: "people",
    difficulty: "easy",
    prompt: { en: "Terry Fox lost his right leg to cancer at what age?" },
    options: [{ en: "12" }, { en: "21" }, { en: "18" }, { en: "25" }],
    answerIndex: 2,
    explanation: {
      en: "In 1980, Terry Fox, a British Columbian who lost his right leg to cancer at the age of 18, began his cross-country run.",
    },
    source: src("Modern Canada: Arts and Culture in Canada"),
  },
  {
    id: "ppl-e-069",
    topicId: "people",
    difficulty: "easy",
    prompt: {
      en: "What was the name of Terry Fox's 1980 cross-country run to raise money for cancer research?",
    },
    options: [
      { en: "The Hope Relay" },
      { en: "The Cross-Canada Trek" },
      { en: "The Victory Lap" },
      { en: "The Marathon of Hope" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Terry Fox began a cross-country run, the “Marathon of Hope,” to raise money for cancer research.",
    },
    source: src("Modern Canada: Arts and Culture in Canada"),
  },
  {
    id: "ppl-e-070",
    topicId: "people",
    difficulty: "easy",
    prompt: {
      en: "In 1985, a fellow British Columbian circled the globe in a wheelchair to raise funds for what cause?",
    },
    options: [
      { en: "Spinal cord research" },
      { en: "Cancer research" },
      { en: "Diabetes research" },
      { en: "Heart disease research" },
    ],
    answerIndex: 0,
    explanation: {
      en: "In 1985, fellow British Columbian Rick Hansen circled the globe in a wheelchair to raise funds for spinal cord research.",
    },
    source: src("Modern Canada: Arts and Culture in Canada"),
  },
  {
    id: "ppl-e-071",
    topicId: "people",
    difficulty: "easy",
    prompt: {
      en: "Mark Tewksbury was an Olympic gold medallist and a prominent activist for which Canadians?",
    },
    options: [
      { en: "Indigenous athletes" },
      { en: "Gay and lesbian Canadians" },
      { en: "Paralympic athletes" },
      { en: "Francophone athletes" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Mark Tewksbury is described as an Olympic gold medallist and prominent activist for gay and lesbian Canadians.",
    },
    source: src("Modern Canada: Arts and Culture in Canada"),
  },
  {
    id: "ppl-e-072",
    topicId: "people",
    difficulty: "easy",
    prompt: {
      en: "Catriona Le May Doan carried the flag after winning a gold medal in speed skating at which Olympic Winter Games?",
    },
    options: [
      { en: "The 2010 Olympic Winter Games" },
      { en: "The 1998 Olympic Winter Games" },
      { en: "The 2002 Olympic Winter Games" },
      { en: "The 2006 Olympic Winter Games" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Catriona Le May Doan carries the flag after winning a gold medal in speed skating at the 2002 Olympic Winter Games.",
    },
    source: src("Modern Canada: Arts and Culture in Canada"),
  },
  {
    id: "ppl-e-073",
    topicId: "people",
    difficulty: "easy",
    prompt: { en: "Lieutenant-Colonel John McCrae composed which famous poem in 1915?" },
    options: [
      { en: "“O Canada”" },
      { en: "“The Maple Leaf Forever”" },
      { en: "“God Save the King”" },
      { en: "“In Flanders Fields”" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Canadian medical officer Lieutenant-Colonel John McCrae composed the poem “In Flanders Fields” in 1915; it is often recited on Remembrance Day.",
    },
    source: src("Canada's History: Women Get the Vote"),
  },
  {
    id: "ppl-e-074",
    topicId: "people",
    difficulty: "easy",
    prompt: {
      en: "The Canadian Corps captured Vimy Ridge in April 1917. Which date is celebrated as Vimy Day?",
    },
    options: [{ en: "April 9" }, { en: "April 17" }, { en: "November 11" }, { en: "July 1" }],
    answerIndex: 0,
    explanation: {
      en: "The Canadian Corps captured Vimy Ridge in April 1917, and April 9 is celebrated as Vimy Day.",
    },
    source: src("Canada's History: The First World War"),
  },
  {
    id: "ppl-e-075",
    topicId: "people",
    difficulty: "easy",
    prompt: { en: "General Sir Arthur Currie is described in the guide as what?" },
    options: [
      { en: "Canada's first general" },
      { en: "Canada's greatest soldier" },
      { en: "The founder of the RCMP" },
      { en: "The hero of Queenston Heights" },
    ],
    answerIndex: 1,
    explanation: {
      en: "In 1918, under the command of General Sir Arthur Currie, Canada's greatest soldier, the Canadian Corps advanced in the last hundred days.",
    },
    source: src("Canada's History: The First World War"),
  },
  {
    id: "ppl-e-076",
    topicId: "people",
    difficulty: "easy",
    prompt: { en: "In 1916, which province became the first to grant voting rights to women?" },
    options: [{ en: "Quebec" }, { en: "Ontario" }, { en: "Manitoba" }, { en: "Nova Scotia" }],
    answerIndex: 2,
    explanation: {
      en: "In 1916, Manitoba became the first province to grant voting rights to women.",
    },
    source: src("Canada's History: Women Get the Vote"),
  },
  {
    id: "ppl-e-077",
    topicId: "people",
    difficulty: "easy",
    prompt: {
      en: "In 1917, the federal government of which prime minister gave women the right to vote in federal elections?",
    },
    options: [
      { en: "Sir Wilfrid Laurier" },
      { en: "Sir John A. Macdonald" },
      { en: "John Diefenbaker" },
      { en: "Sir Robert Borden" },
    ],
    answerIndex: 3,
    explanation: {
      en: "In 1917, thanks to the leadership of women such as Dr. Stowe, the federal government of Sir Robert Borden gave women the right to vote in federal elections.",
    },
    source: src("Canada's History: Women Get the Vote"),
  },
  {
    id: "ppl-e-078",
    topicId: "people",
    difficulty: "easy",
    prompt: { en: "In 1921, who became the first woman MP — a farmer and teacher?" },
    options: [
      { en: "Agnes Macphail" },
      { en: "Dr. Emily Stowe" },
      { en: "Thérèse Casgrain" },
      { en: "Mary Ann Shadd Cary" },
    ],
    answerIndex: 0,
    explanation: { en: "In 1921 Agnes Macphail, a farmer and teacher, became the first woman MP." },
    source: src("Canada's History: Women Get the Vote"),
  },
  {
    id: "ppl-e-079",
    topicId: "people",
    difficulty: "easy",
    prompt: {
      en: "The effort by women to achieve the right to vote is known as the women's suffrage movement. Who was its founder in Canada?",
    },
    options: [
      { en: "Agnes Macphail" },
      { en: "Dr. Emily Stowe" },
      { en: "Thérèse Casgrain" },
      { en: "Mary Ann Shadd Cary" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The effort by women to achieve the right to vote is known as the women's suffrage movement, and its founder in Canada was Dr. Emily Stowe.",
    },
    source: src("Canada's History: Women Get the Vote"),
  },
  {
    id: "ppl-e-080",
    topicId: "people",
    difficulty: "easy",
    prompt: {
      en: "Which Europeans reached Labrador and Newfoundland 1,000 years ago, leaving remains at l'Anse aux Meadows?",
    },
    options: [
      { en: "The Romans from Italy" },
      { en: "The Phoenicians from Tyre" },
      { en: "The Vikings from Iceland" },
      { en: "The Greeks from Athens" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The Vikings from Iceland who colonized Greenland 1,000 years ago also reached Labrador and the island of Newfoundland; the remains of their settlement, l'Anse aux Meadows, are a World Heritage site.",
    },
    source: src("Canada's History: The First Europeans"),
  },
  {
    id: "ppl-m-001",
    topicId: "people",
    difficulty: "medium",
    prompt: { en: "John Cabot was an immigrant to England from which country?" },
    options: [{ en: "Italy" }, { en: "France" }, { en: "Spain" }, { en: "Ireland" }],
    answerIndex: 0,
    explanation: { en: "John Cabot is described as an Italian immigrant to England." },
    source: src("Canada's History: The First Europeans"),
  },
  {
    id: "ppl-m-002",
    topicId: "people",
    difficulty: "medium",
    prompt: { en: "Where did John Cabot set foot in 1497?" },
    options: [
      { en: "Labrador or Baffin Island" },
      { en: "Nova Scotia or Prince Edward Island" },
      { en: "Hudson Bay or James Bay" },
      { en: "Newfoundland or Cape Breton Island" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Cabot set foot on Newfoundland or Cape Breton Island in 1497 and claimed the New Founde Land for England.",
    },
    source: src("Canada's History: The First Europeans"),
  },
  {
    id: "ppl-m-003",
    topicId: "people",
    difficulty: "medium",
    prompt: { en: "Jacques Cartier claimed land for which French king?" },
    options: [
      { en: "King Louis XIV" },
      { en: "King Henry IV" },
      { en: "King Francis I" },
      { en: "Napoleon Bonaparte" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Between 1534 and 1542, Jacques Cartier made three voyages across the Atlantic, claiming the land for King Francis I of France.",
    },
    source: src("Canada's History: Exploring a River, Naming Canada"),
  },
  {
    id: "ppl-m-004",
    topicId: "people",
    difficulty: "medium",
    prompt: {
      en: "The 1604 settlement was first established on which island, in present-day Maine?",
    },
    options: [
      { en: "Anticosti Island" },
      { en: "St. Croix Island" },
      { en: "Manhattan Island" },
      { en: "Baffin Island" },
    ],
    answerIndex: 1,
    explanation: {
      en: "In 1604, the first European settlement north of Florida was established by Pierre de Monts and Samuel de Champlain, first on St. Croix Island (in present-day Maine), then at Port-Royal in Acadia.",
    },
    source: src("Canada's History: Royal New France"),
  },
  {
    id: "ppl-m-005",
    topicId: "people",
    difficulty: "medium",
    prompt: { en: "Port-Royal was in Acadia, in present-day which province?" },
    options: [{ en: "Nova Scotia" }, { en: "New Brunswick" }, { en: "Quebec" }, { en: "Maine" }],
    answerIndex: 0,
    explanation: { en: "Port-Royal was in Acadia, which is present-day Nova Scotia." },
    source: src("Canada's History: Royal New France"),
  },
  {
    id: "ppl-m-006",
    topicId: "people",
    difficulty: "medium",
    prompt: { en: "Champlain allied the colony with which three First Nations?" },
    options: [
      { en: "The Iroquois, Sioux and Cree" },
      { en: "The Huron, Iroquois and Mohawk" },
      { en: "The Cree, Dene and Sioux" },
      { en: "The Algonquin, Montagnais and Huron" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Champlain allied the colony with the Algonquin, Montagnais, and Huron, historic enemies of the Iroquois.",
    },
    source: src("Canada's History: Royal New France"),
  },
  {
    id: "ppl-m-007",
    topicId: "people",
    difficulty: "medium",
    prompt: { en: "The Iroquois were a confederation of how many First Nations?" },
    options: [{ en: "Three" }, { en: "Ten" }, { en: "Five (later six)" }, { en: "Twelve" }],
    answerIndex: 2,
    explanation: {
      en: "The Iroquois were a confederation of five (later six) First Nations who battled with the French settlements for a century.",
    },
    source: src("Canada's History: Royal New France"),
  },
  {
    id: "ppl-m-008",
    topicId: "people",
    difficulty: "medium",
    prompt: { en: "The French and the Iroquois made peace in which year?" },
    options: [{ en: "1759" }, { en: "1701" }, { en: "1690" }, { en: "1774" }],
    answerIndex: 1,
    explanation: { en: "The French and the Iroquois made peace in 1701." },
    source: src("Canada's History: Royal New France"),
  },
  {
    id: "ppl-m-009",
    topicId: "people",
    difficulty: "medium",
    prompt: { en: "The vast fur-trade economy was driven by European demand for which pelts?" },
    options: [
      { en: "Beaver pelts" },
      { en: "Fox pelts" },
      { en: "Seal pelts" },
      { en: "Mink pelts" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The French and Aboriginal people collaborated in the vast fur-trade economy, driven by the demand for beaver pelts in Europe.",
    },
    source: src("Canada's History: Royal New France"),
  },
  {
    id: "ppl-m-010",
    topicId: "people",
    difficulty: "medium",
    prompt: {
      en: "Pierre Le Moyne, Sieur d'Iberville, won many victories over the English from James Bay in the north to which Caribbean island?",
    },
    options: [{ en: "Jamaica" }, { en: "Barbados" }, { en: "Cuba" }, { en: "Nevis" }],
    answerIndex: 3,
    explanation: {
      en: "Pierre Le Moyne, Sieur d'Iberville, was a great hero of New France, winning many victories over the English, from James Bay in the north to Nevis in the Caribbean.",
    },
    source: src("Canada's History: Royal New France"),
  },
  {
    id: "ppl-m-011",
    topicId: "people",
    difficulty: "medium",
    prompt: {
      en: "Sir Guy Carleton supervised the Loyalist migration to Nova Scotia and Quebec in which years?",
    },
    options: [{ en: "1775–76" }, { en: "1812–14" }, { en: "1782–83" }, { en: "1867–68" }],
    answerIndex: 2,
    explanation: {
      en: "Sir Guy Carleton supervised the Loyalist migration to Nova Scotia and Quebec in 1782–83.",
    },
    source: src("Canada's History: Royal New France"),
  },
  {
    id: "ppl-m-012",
    topicId: "people",
    difficulty: "medium",
    prompt: { en: "Which prime minister encouraged immigration to the West in the early 1900s?" },
    options: [
      { en: "Sir John A. Macdonald" },
      { en: "Sir Wilfrid Laurier" },
      { en: "Sir Robert Borden" },
      { en: "William Lyon Mackenzie King" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Sir Wilfrid Laurier, the first French-Canadian prime minister since Confederation, encouraged immigration to the West.",
    },
    source: src("Canada's History"),
  },
  {
    id: "ppl-m-013",
    topicId: "people",
    difficulty: "medium",
    prompt: {
      en: "In 1792, some black Nova Scotians moved on to establish Freetown in which West African country?",
    },
    options: [{ en: "Sierra Leone" }, { en: "Ghana" }, { en: "Liberia" }, { en: "Nigeria" }],
    answerIndex: 0,
    explanation: {
      en: "In 1792, some black Nova Scotians, who were given poor land, moved on to establish Freetown, Sierra Leone (West Africa), a new British colony for freed slaves.",
    },
    source: src("Canada's History: United Empire Loyalists"),
  },
  {
    id: "ppl-m-014",
    topicId: "people",
    difficulty: "medium",
    prompt: {
      en: "The Quebec Act of 1774 allowed religious freedom for Catholics and permitted them to do what, a practice not then allowed in Britain?",
    },
    options: [
      { en: "Vote in the British Parliament" },
      { en: "Own land in England" },
      { en: "Serve as military officers" },
      { en: "Hold public office" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The Quebec Act allowed religious freedom for Catholics and permitted them to hold public office, a practice not then allowed in Britain.",
    },
    source: src("Canada's History: A Tradition of Accommodation"),
  },
  {
    id: "ppl-m-015",
    topicId: "people",
    difficulty: "medium",
    prompt: {
      en: "The Quebec Act of 1774 restored French civil law while maintaining which other law?",
    },
    options: [
      { en: "French criminal law" },
      { en: "British civil law" },
      { en: "British criminal law" },
      { en: "Indigenous customary law" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The Quebec Act restored French civil law while maintaining British criminal law.",
    },
    source: src("Canada's History: A Tradition of Accommodation"),
  },
  {
    id: "ppl-m-016",
    topicId: "people",
    difficulty: "medium",
    prompt: { en: "The first representative assembly was elected in which city in 1758?" },
    options: [
      { en: "Québec City" },
      { en: "Halifax, Nova Scotia" },
      { en: "York (Toronto)" },
      { en: "Charlottetown" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The first representative assembly was elected in Halifax, Nova Scotia, in 1758.",
    },
    source: src("Canada's History: The Beginnings of Democracy"),
  },
  {
    id: "ppl-m-017",
    topicId: "people",
    difficulty: "medium",
    prompt: {
      en: "The Constitutional Act of 1791 divided the Province of Quebec into which two colonies?",
    },
    options: [
      { en: "Upper Canada and Lower Canada" },
      { en: "Ontario and Quebec" },
      { en: "New Brunswick and Nova Scotia" },
      { en: "Canada East and Canada West" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The Constitutional Act of 1791 divided the Province of Quebec into Upper Canada (later Ontario) and Lower Canada (later Quebec).",
    },
    source: src("Canada's History: The Beginnings of Democracy"),
  },
  {
    id: "ppl-m-018",
    topicId: "people",
    difficulty: "medium",
    prompt: {
      en: "Under the 1791 Act, Lower Canada (later Quebec) was described as which of these?",
    },
    options: [
      { en: "Mainly Loyalist, Protestant and English-speaking" },
      { en: "Mostly Scottish Presbyterian settlers" },
      { en: "Predominantly German-speaking farmers" },
      { en: "Heavily Catholic and French-speaking" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Lower Canada (later Quebec) was heavily Catholic and French-speaking, while Upper Canada was mainly Loyalist, Protestant and English-speaking.",
    },
    source: src("Canada's History: The Beginnings of Democracy"),
  },
  {
    id: "ppl-m-019",
    topicId: "people",
    difficulty: "medium",
    prompt: {
      en: "Lord Durham's recommendation that the Canadiens assimilate into English-speaking Protestant culture demonstrated what?",
    },
    options: [
      { en: "A deep respect for French-Canadian identity" },
      { en: "Support for the Quiet Revolution" },
      { en: "A complete lack of understanding of French Canadians" },
      { en: "Approval of the Quebec Act" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Durham's recommendation that Canadiens assimilate demonstrated a complete lack of understanding of French Canadians, who sought to uphold the distinct identity of French Canada.",
    },
    source: src("Canada's History: Rebellions of 1837–38"),
  },
  {
    id: "ppl-m-020",
    topicId: "people",
    difficulty: "medium",
    prompt: { en: "In 1840, Upper and Lower Canada were united as what?" },
    options: [
      { en: "The Dominion of Canada" },
      { en: "The Province of Canada" },
      { en: "British North America" },
      { en: "The Province of Quebec" },
    ],
    answerIndex: 1,
    explanation: { en: "In 1840, Upper and Lower Canada were united as the Province of Canada." },
    source: src("Canada's History: Responsible Government"),
  },
];
