/**
 * Question bank chunk — part of questions.generated.ts. DO NOT EDIT BY HAND.
 */
import type { Question } from "../content";
import { src } from "./shared";

export const rightsB: Question[] = [
  {
    id: "rts-m-019",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "The guide states: Canada is personified by the Sovereign just as…" },
    options: [
      { en: "the flag is personified by the people" },
      { en: "the people are personified by Parliament" },
      { en: "the Sovereign is personified by Canada" },
      { en: "Canada is personified by the flag" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The guide states: Canada is personified by the Sovereign just as the Sovereign is personified by Canada.",
    },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "rts-m-020",
    topicId: "rights",
    difficulty: "medium",
    prompt: {
      en: "The citizenship responsibility is called protecting and ___ our heritage and environment.",
    },
    options: [{ en: "selling" }, { en: "ignoring" }, { en: "taxing" }, { en: "enjoying" }],
    answerIndex: 3,
    explanation: {
      en: "The responsibility is named protecting and enjoying our heritage and environment.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-m-021",
    topicId: "rights",
    difficulty: "medium",
    prompt: {
      en: "Under the rule of law, ___ are regulated by laws and not by arbitrary actions.",
    },
    options: [
      { en: "Individuals and governments" },
      { en: "Only newcomers" },
      { en: "Only politicians" },
      { en: "Only judges" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Individuals and governments are regulated by laws and not by arbitrary actions.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-m-022",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "Serving in the local reserves helps Canadians gain…" },
    options: [
      { en: "a university degree" },
      { en: "valuable experience, skills and contacts" },
      { en: "a pension immediately" },
      { en: "foreign citizenship" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Serving in the reserves lets Canadians gain valuable experience, skills and contacts.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-m-023",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "Volunteers donate their time to help…" },
    options: [
      { en: "only their families" },
      { en: "the government" },
      { en: "people in need" },
      { en: "corporations" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Volunteers donate their time to help people in need, among other community activities.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-m-024",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "Which barbaric cultural practice is specifically named in the guide?" },
    options: [
      { en: "Wearing a headscarf" },
      { en: "Arranged marriage" },
      { en: "Fasting" },
      { en: "Female genital mutilation" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Female genital mutilation is specifically named among the barbaric cultural practices.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-m-025",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "Getting a job, taking care of one's family and working hard are described as…" },
    options: [
      { en: "important Canadian values" },
      { en: "legal requirements" },
      { en: "optional hobbies" },
      { en: "provincial laws" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Getting a job, taking care of one's family and working hard in keeping with one's abilities are important Canadian values.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-m-026",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "Mobility rights let Canadians live and work anywhere…" },
    options: [
      { en: "in the world" },
      { en: "they choose in Canada" },
      { en: "without a passport" },
      { en: "for free" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Mobility rights mean Canadians can live and work anywhere they choose in Canada.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-m-027",
    topicId: "rights",
    difficulty: "medium",
    prompt: {
      en: "The Charter will not adversely affect any treaty or ___ of Aboriginal peoples.",
    },
    options: [
      { en: "laws of other countries" },
      { en: "provincial programs" },
      { en: "other rights or freedoms" },
      { en: "private contracts" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The Charter will not adversely affect any treaty or other rights or freedoms of Aboriginal peoples.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-m-028",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "The Oath promises that new citizens will ___ observe the laws of Canada." },
    options: [{ en: "sometimes" }, { en: "rarely" }, { en: "secretly" }, { en: "faithfully" }],
    answerIndex: 3,
    explanation: { en: "The Oath promises: I will faithfully observe the laws of Canada." },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "rts-m-029",
    topicId: "rights",
    difficulty: "medium",
    prompt: {
      en: "The Constitution was amended in 1982 to ___ the Canadian Charter of Rights and Freedoms.",
    },
    options: [{ en: "entrench" }, { en: "abolish" }, { en: "ignore" }, { en: "replace" }],
    answerIndex: 0,
    explanation: {
      en: "The Constitution was amended in 1982 to entrench the Canadian Charter of Rights and Freedoms.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-m-030",
    topicId: "rights",
    difficulty: "medium",
    prompt: {
      en: "The tradition of ordered liberty dates back to the ___ of Magna Carta in 1215.",
    },
    options: [{ en: "printing" }, { en: "signing" }, { en: "discovery" }, { en: "translation" }],
    answerIndex: 1,
    explanation: {
      en: "The tradition dates back to the signing of Magna Carta in 1215 in England.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-m-031",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "Citizens' rights and responsibilities are ___ by Canadian law." },
    options: [{ en: "ignored" }, { en: "delayed" }, { en: "secured" }, { en: "limited" }],
    answerIndex: 2,
    explanation: { en: "These come to us from our history and are secured by Canadian law." },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-m-032",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "Serving on a jury is legally required…" },
    options: [
      { en: "every year" },
      { en: "only for serious crimes" },
      { en: "after age 50" },
      { en: "when called to do so" },
    ],
    answerIndex: 3,
    explanation: { en: "When called to do so, you are legally required to serve on a jury." },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-m-033",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "___ do not extend to barbaric cultural practices." },
    options: [
      { en: "Canada's openness and generosity" },
      { en: "Canada's borders" },
      { en: "Canada's provinces" },
      { en: "Canada's courts" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Canada's openness and generosity do not extend to barbaric cultural practices.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-m-034",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "The amended Constitution was proclaimed in…" },
    options: [{ en: "London" }, { en: "Ottawa" }, { en: "Toronto" }, { en: "Quebec City" }],
    answerIndex: 1,
    explanation: {
      en: "Queen Elizabeth II proclaimed the amended Constitution in Ottawa in 1982.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-m-035",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "New citizens swear to ___ true allegiance to His Majesty." },
    options: [{ en: "give" }, { en: "lend" }, { en: "bear" }, { en: "sell" }],
    answerIndex: 2,
    explanation: {
      en: "The Oath says: I will be faithful and bear true allegiance to His Majesty.",
    },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "rts-m-036",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "In Canada, rights come with…" },
    options: [{ en: "money" }, { en: "rewards" }, { en: "exceptions" }, { en: "responsibilities" }],
    answerIndex: 3,
    explanation: { en: "In Canada, rights come with responsibilities." },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-m-037",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "The Charter right that gives French and English equal status is called…" },
    options: [
      { en: "Official Language Rights" },
      { en: "Multiculturalism Rights" },
      { en: "Mobility Rights" },
      { en: "Voting Rights" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The right is named Official Language Rights (alongside Minority Language Educational Rights).",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-m-038",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "Canadians work hard to respect ___ and live in harmony." },
    options: [{ en: "silence" }, { en: "pluralism" }, { en: "tradition" }, { en: "authority" }],
    answerIndex: 1,
    explanation: { en: "Canadians work hard to respect pluralism and live in harmony." },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-m-039",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "Serving in the regular Canadian Forces is described as an…" },
    options: [
      { en: "easy way out" },
      { en: "short internship" },
      { en: "excellent career choice" },
      { en: "unpaid duty" },
    ],
    answerIndex: 2,
    explanation: { en: "Serving in the regular Canadian Forces is an excellent career choice." },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-m-040",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "Through the cadets, young people learn…" },
    options: [
      { en: "only military drills" },
      { en: "how to avoid service" },
      { en: "foreign languages" },
      { en: "discipline, responsibility, and skills" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Young people can learn discipline, responsibility, and skills by getting involved in the cadets.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-m-041",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "Which responsibility involves getting a job and taking care of one's family?" },
    options: [
      { en: "Taking responsibility for oneself and one's family" },
      { en: "Serving on a jury" },
      { en: "Voting in elections" },
      { en: "Obeying the law" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Taking responsibility for oneself and one's family covers getting a job and taking care of one's family.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-m-042",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "Volunteers may help at a food bank or…" },
    options: [
      { en: "political party" },
      { en: "other charity" },
      { en: "private club" },
      { en: "sports team" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Volunteering at a food bank or other charity is listed as helping others in the community.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-m-043",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "The French version of the Oath begins with…" },
    options: [
      { en: "Bonjour Canada" },
      { en: "Vive le Canada" },
      { en: "Je jure (ou j'affirme solennellement)" },
      { en: "Je suis Canadien" },
    ],
    answerIndex: 2,
    explanation: { en: "The French Oath begins: Je jure (ou j'affirme solennellement)." },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "rts-m-044",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "The French phrase À ses héritiers et successeurs corresponds to…" },
    options: [
      { en: "King of Canada" },
      { en: "the laws of Canada" },
      { en: "my duties as a citizen" },
      { en: "His Heirs and Successors" },
    ],
    answerIndex: 3,
    explanation: {
      en: "À ses héritiers et successeurs is the French rendering of His Heirs and Successors.",
    },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "rts-m-045",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "Le serment de citoyenneté is the French title of…" },
    options: [
      { en: "The Oath of Citizenship" },
      { en: "The national anthem" },
      { en: "The Charter of Rights" },
      { en: "The Constitution Act" },
    ],
    answerIndex: 0,
    explanation: { en: "The guide titles the French Oath Le serment de citoyenneté." },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "rts-m-046",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "Mobility rights include the freedom to enter and ___ the country freely." },
    options: [{ en: "paint" }, { en: "leave" }, { en: "divide" }, { en: "tax" }],
    answerIndex: 1,
    explanation: { en: "Mobility rights include entering and leaving the country freely." },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-m-047",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "The responsibility to vote includes ___ elections." },
    options: [
      { en: "American" },
      { en: "European" },
      { en: "provincial or territorial" },
      { en: "school board" },
    ],
    answerIndex: 2,
    explanation: { en: "Citizens vote in federal, provincial or territorial and local elections." },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-m-048",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "Mobility rights let Canadians live and ___ anywhere they choose in Canada." },
    options: [{ en: "vote" }, { en: "rest" }, { en: "shop" }, { en: "work" }],
    answerIndex: 3,
    explanation: {
      en: "Mobility rights mean Canadians can live and work anywhere they choose in Canada.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-m-049",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "New citizens swear: That I will be ___ and bear true allegiance." },
    options: [{ en: "faithful" }, { en: "silent" }, { en: "absent" }, { en: "late" }],
    answerIndex: 0,
    explanation: { en: "The Oath says: That I will be faithful and bear true allegiance." },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "rts-m-050",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "Which word does NOT appear in the second fundamental freedom?" },
    options: [{ en: "thought" }, { en: "religion" }, { en: "belief" }, { en: "expression" }],
    answerIndex: 1,
    explanation: {
      en: "The second freedom is thought, belief, opinion and expression — religion appears in the first freedom instead.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-m-051",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "Allegiance is sworn to ___ Majesty King Charles the Third." },
    options: [{ en: "Her" }, { en: "Their" }, { en: "His" }, { en: "Your" }],
    answerIndex: 2,
    explanation: { en: "The Oath swears allegiance to His Majesty King Charles the Third." },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "rts-m-052",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "Canadians may serve in the Coast Guard or emergency services…" },
    options: [
      { en: "in another country" },
      { en: "only in Ottawa" },
      { en: "for foreign governments" },
      { en: "in your community" },
    ],
    answerIndex: 3,
    explanation: {
      en: "You may serve in the Coast Guard or emergency services in your community.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-m-053",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "Serving on a jury is a privilege that makes the justice system ___." },
    options: [{ en: "work" }, { en: "profit" }, { en: "wait" }, { en: "close" }],
    answerIndex: 0,
    explanation: { en: "Serving on a jury is a privilege that makes the justice system work." },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-m-054",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "The guide speaks of Canada's natural, cultural and ___ heritage." },
    options: [{ en: "sporting" }, { en: "architectural" }, { en: "musical" }, { en: "digital" }],
    answerIndex: 1,
    explanation: { en: "Citizens protect Canada's natural, cultural and architectural heritage." },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-m-055",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "The Charter right protecting treaty rights from adverse effects is called…" },
    options: [
      { en: "Mobility Rights" },
      { en: "Official Language Rights" },
      { en: "Aboriginal Peoples' Rights" },
      { en: "Multiculturalism" },
    ],
    answerIndex: 2,
    explanation: { en: "The right is named Aboriginal Peoples' Rights in the Charter list." },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-m-056",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "Which list names ONLY sources of Canadian law?" },
    options: [
      { en: "The American Constitution and the Magna Carta" },
      { en: "United Nations resolutions only" },
      { en: "Religious laws and military orders" },
      { en: "English common law, the civil code of France, and laws passed by Parliament" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Canadian law has several sources, including laws passed by Parliament, English common law, and the civil code of France.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-m-057",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "Citizens' rights and responsibilities reflect our shared…" },
    options: [
      { en: "traditions, identity, and values" },
      { en: "borders, taxes, and laws" },
      { en: "anthem, flag, and motto" },
      { en: "courts, police, and prisons" },
    ],
    answerIndex: 0,
    explanation: { en: "They reflect our shared traditions, identity, and values." },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-m-058",
    topicId: "rights",
    difficulty: "medium",
    prompt: {
      en: "In our constitutional monarchy, the constitution, the flag and the country are encompassed by…",
    },
    options: [
      { en: "Parliament" },
      { en: "the Sovereign" },
      { en: "the courts" },
      { en: "the provinces" },
    ],
    answerIndex: 1,
    explanation: {
      en: "In our constitutional monarchy, these elements are encompassed by the Sovereign.",
    },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "rts-m-059",
    topicId: "rights",
    difficulty: "medium",
    prompt: {
      en: "Freedom of conscience and religion is the ___ fundamental freedom listed in the guide.",
    },
    options: [{ en: "second" }, { en: "fourth" }, { en: "first" }, { en: "third" }],
    answerIndex: 2,
    explanation: {
      en: "Freedom of conscience and religion is listed first among the four fundamental freedoms.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-m-060",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "In the guide, other gender-based violence is listed among…" },
    options: [
      { en: "volunteer activities" },
      { en: "Charter rights" },
      { en: "military duties" },
      { en: "barbaric cultural practices" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Other gender-based violence is listed among the barbaric cultural practices.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-m-061",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "To help prepare for the Oath ceremony, the guide suggests using…" },
    options: [
      { en: "the video The Oath of Citizenship" },
      { en: "a newspaper" },
      { en: "a dictionary" },
      { en: "a map of Canada" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The guide says: To help you prepare, use this video (The Oath of Citizenship).",
    },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "rts-m-062",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "In the French Oath, Que je serai fidèle means the new citizen will be…" },
    options: [{ en: "silent" }, { en: "faithful" }, { en: "present" }, { en: "grateful" }],
    answerIndex: 1,
    explanation: { en: "Que je serai fidèle is the French rendering of That I will be faithful." },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "rts-m-063",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "About how many Canadians volunteer in their communities?" },
    options: [{ en: "Dozens" }, { en: "Hundreds" }, { en: "Millions" }, { en: "None" }],
    answerIndex: 2,
    explanation: {
      en: "Millions of volunteers freely donate their time to help others without pay.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-h-001",
    topicId: "rights",
    difficulty: "hard",
    prompt: {
      en: "Which is the exact opening phrase of the Canadian Charter of Rights and Freedoms?",
    },
    options: [
      {
        en: "Whereas Canada is founded upon principles that recognize the supremacy of God and the rule of law.",
      },
      { en: "Whereas Canada is founded upon the principles of liberty and democracy." },
      { en: "Canada is founded upon principles recognizing God and justice." },
      { en: "We, the people of Canada, establish this Charter." },
    ],
    answerIndex: 0,
    explanation: {
      en: "The Charter begins with the exact words: Whereas Canada is founded upon principles that recognize the supremacy of God and the rule of law.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-h-002",
    topicId: "rights",
    difficulty: "hard",
    prompt: { en: "The Charter's opening words name which two principles?" },
    options: [
      { en: "The supremacy of Parliament and the rule of the majority" },
      { en: "The supremacy of God and the rule of law" },
      { en: "Liberty and equality for all" },
      { en: "Peace, order and good government" },
    ],
    answerIndex: 1,
    explanation: { en: "The opening phrase names the supremacy of God and the rule of law." },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-h-003",
    topicId: "rights",
    difficulty: "hard",
    prompt: {
      en: "Which of these is one of the four fundamental freedoms, rather than an additional Charter right?",
    },
    options: [
      { en: "Mobility Rights" },
      { en: "Official Language Rights" },
      { en: "Freedom of association" },
      { en: "Aboriginal Peoples' Rights" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Freedom of association is one of the four fundamental freedoms; the others are additional rights the Charter sets out.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-h-004",
    topicId: "rights",
    difficulty: "hard",
    prompt: { en: "Which of the following is NOT a source of Canadian law?" },
    options: [
      { en: "English common law" },
      { en: "The civil code of France" },
      { en: "Laws passed by Parliament" },
      { en: "The Constitution of the United States" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Canadian law's sources include laws passed by Parliament, English common law, the civil code of France and the unwritten constitution — not the US Constitution.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-h-005",
    topicId: "rights",
    difficulty: "hard",
    prompt: { en: "Which statement about the sources of Canadian law is TRUE?" },
    options: [
      {
        en: "Canadian law has several sources, including English common law and the civil code of France",
      },
      { en: "All Canadian law comes from English common law" },
      { en: "Canada's only source of law is the Charter" },
      { en: "The unwritten constitution comes from France" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Canadian law has several sources, including laws passed by Parliament and the provincial legislatures, English common law, the civil code of France and the unwritten constitution inherited from Great Britain.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-h-006",
    topicId: "rights",
    difficulty: "hard",
    prompt: {
      en: "In the Oath, allegiance to the King comes ___ the promise to observe the laws.",
    },
    options: [{ en: "instead of" }, { en: "before" }, { en: "after" }, { en: "unrelated to" }],
    answerIndex: 1,
    explanation: {
      en: "The Oath first swears allegiance to His Majesty and then promises to faithfully observe the laws of Canada.",
    },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "rts-h-007",
    topicId: "rights",
    difficulty: "hard",
    prompt: { en: "Because the Oath says I swear (or affirm), a new citizen may…" },
    options: [
      { en: "skip the ceremony" },
      { en: "take the Oath later" },
      { en: "affirm the Oath rather than swear it" },
      { en: "whisper the Oath" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The wording I swear (or affirm) means a new citizen may affirm the Oath instead of swearing it.",
    },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "rts-h-008",
    topicId: "rights",
    difficulty: "hard",
    prompt: {
      en: "The guide describes the principle that Canada is personified by the Sovereign as…",
    },
    options: [
      { en: "an ancient and complex rule" },
      { en: "a controversial idea" },
      { en: "a temporary arrangement" },
      { en: "a remarkably simple yet powerful principle" },
    ],
    answerIndex: 3,
    explanation: { en: "The guide calls it a remarkably simple yet powerful principle." },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "rts-h-009",
    topicId: "rights",
    difficulty: "hard",
    prompt: { en: "Which statement about jury duty is TRUE?" },
    options: [
      { en: "It is legally required when called and is described as a privilege" },
      { en: "It is voluntary and always unpaid" },
      { en: "Only lawyers may serve" },
      { en: "It applies only in Quebec" },
    ],
    answerIndex: 0,
    explanation: {
      en: "When called, you are legally required to serve, and serving on a jury is described as a privilege.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-h-010",
    topicId: "rights",
    difficulty: "hard",
    prompt: { en: "Obeying the law appears in the guide as a…" },
    options: [
      { en: "suggestion" },
      { en: "citizenship responsibility" },
      { en: "provincial program" },
      { en: "military duty" },
    ],
    answerIndex: 1,
    explanation: { en: "Obeying the law is listed under Citizenship Responsibilities." },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-h-011",
    topicId: "rights",
    difficulty: "hard",
    prompt: { en: "Which statement about defending Canada is TRUE?" },
    options: [
      { en: "Military service is compulsory" },
      { en: "Serving is forbidden to newcomers" },
      {
        en: "There is no compulsory military service, but serving in the regular Forces is a noble way to contribute to Canada",
      },
      { en: "Only the navy accepts volunteers" },
    ],
    answerIndex: 2,
    explanation: {
      en: "There is no compulsory military service, but serving in the regular Canadian Forces is a noble way to contribute to Canada.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-h-012",
    topicId: "rights",
    difficulty: "hard",
    prompt: { en: "Which pairing of a Charter right and its description is correct?" },
    options: [
      { en: "Mobility Rights — French and English have equal status" },
      { en: "Official Language Rights — the right to a passport" },
      { en: "Aboriginal Peoples' Rights — the right to vote" },
      { en: "Mobility Rights — Canadians can live and work anywhere they choose in Canada" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Mobility rights mean Canadians can live and work anywhere they choose in Canada.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-h-013",
    topicId: "rights",
    difficulty: "hard",
    prompt: { en: "Which Charter right and description are correctly matched?" },
    options: [
      {
        en: "Official Language Rights — French and English have equal status in Parliament and throughout the government",
      },
      { en: "Mobility Rights — French and English have equal status" },
      { en: "Multiculturalism — the right to a passport" },
      { en: "Aboriginal Peoples' Rights — equal status of languages" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Official Language Rights mean French and English have equal status in Parliament and throughout the government.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-h-014",
    topicId: "rights",
    difficulty: "hard",
    prompt: { en: "Which of these correctly pairs a Charter right with what it means?" },
    options: [
      { en: "Mobility Rights — treaty rights" },
      {
        en: "Aboriginal Peoples' Rights — the Charter will not adversely affect any treaty or other rights or freedoms of Aboriginal peoples",
      },
      { en: "Official Language Rights — Aboriginal rights" },
      { en: "Multiculturalism — the right to vote" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Aboriginal Peoples' Rights mean the Charter will not adversely affect any treaty or other rights or freedoms of Aboriginal peoples.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-h-015",
    topicId: "rights",
    difficulty: "hard",
    prompt: { en: "Which correctly matches a Charter concept to its description?" },
    options: [
      { en: "Multiculturalism — a provincial holiday" },
      { en: "Mobility Rights — celebrating diversity" },
      {
        en: "Multiculturalism — a fundamental characteristic of the Canadian heritage and identity",
      },
      { en: "Official Language Rights — pluralism" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Multiculturalism is a fundamental characteristic of the Canadian heritage and identity.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-h-016",
    topicId: "rights",
    difficulty: "hard",
    prompt: { en: "The tradition of ordered liberty described in the guide is how old?" },
    options: [
      { en: "80 years old" },
      { en: "8,000 years old" },
      { en: "18 years old" },
      { en: "800 years old" },
    ],
    answerIndex: 3,
    explanation: { en: "The guide describes an 800-year-old tradition of ordered liberty." },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-h-017",
    topicId: "rights",
    difficulty: "hard",
    prompt: { en: "Which event began the 800-year-old tradition of ordered liberty?" },
    options: [
      { en: "The signing of the Magna Carta in 1215" },
      { en: "The Charter of 1982" },
      { en: "Confederation in 1867" },
      { en: "The discovery of Canada" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The tradition dates back to the signing of Magna Carta in 1215 in England.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-h-018",
    topicId: "rights",
    difficulty: "hard",
    prompt: { en: "The four fundamental freedoms come from…" },
    options: [
      { en: "the Charter of 1982" },
      { en: "a United Nations treaty" },
      { en: "the French Revolution" },
      { en: "an 800-year-old tradition of ordered liberty" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The four freedoms are secured by an 800-year-old tradition of ordered liberty dating back to Magna Carta.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-h-019",
    topicId: "rights",
    difficulty: "hard",
    prompt: {
      en: "Which freedom protects joining clubs and organizations, as distinct from gathering in public?",
    },
    options: [
      { en: "Freedom of peaceful assembly" },
      { en: "Freedom of conscience" },
      { en: "Freedom of association" },
      { en: "Freedom of the press" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Freedom of association protects joining groups, while freedom of peaceful assembly covers gathering in public.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-h-020",
    topicId: "rights",
    difficulty: "hard",
    prompt: { en: "Which statement about the four fundamental freedoms is TRUE?" },
    options: [
      {
        en: "They are freedom of conscience and religion; freedom of thought, belief, opinion and expression; freedom of peaceful assembly; and freedom of association",
      },
      { en: "They include mobility rights and language rights" },
      { en: "They were created by the Charter in 1982" },
      { en: "They apply only to citizens born in Canada" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The four freedoms are conscience and religion; thought, belief, opinion and expression; peaceful assembly; and association.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-h-021",
    topicId: "rights",
    difficulty: "hard",
    prompt: { en: "Which statement about equality in Canada is TRUE?" },
    options: [
      {
        en: "Men and women are equal under the law, and those guilty of barbaric cultural practices are severely punished under Canada's criminal laws",
      },
      { en: "Men and women have different legal rights" },
      { en: "Barbaric cultural practices are tolerated" },
      { en: "Equality applies only to citizens born in Canada" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Men and women are equal under the law, and those guilty of these crimes are severely punished under Canada's criminal laws.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-h-022",
    topicId: "rights",
    difficulty: "hard",
    prompt: { en: "The French Oath refers to Le roi Charles Trois. This is…" },
    options: [
      { en: "the Prime Minister" },
      { en: "King Charles the Third" },
      { en: "the Governor General" },
      { en: "a former king" },
    ],
    answerIndex: 1,
    explanation: { en: "Le roi Charles Trois is the French rendering of King Charles the Third." },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "rts-h-023",
    topicId: "rights",
    difficulty: "hard",
    prompt: { en: "The Charter's opening phrase underlines which two things?" },
    options: [
      { en: "Military strength and wealth" },
      { en: "Freedom of speech and free trade" },
      {
        en: "The importance of religious traditions to Canadian society and the dignity and worth of the human person",
      },
      { en: "Equality and prosperity" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The phrase underlines the importance of religious traditions to Canadian society and the dignity and worth of the human person.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-h-024",
    topicId: "rights",
    difficulty: "hard",
    prompt: { en: "Who proclaimed the amended Constitution, and where?" },
    options: [
      { en: "King Charles III in London" },
      { en: "The Prime Minister in Toronto" },
      { en: "The Governor General in Quebec City" },
      { en: "Queen Elizabeth II in Ottawa" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Queen Elizabeth II proclaimed the amended Constitution in Ottawa in 1982.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-h-025",
    topicId: "rights",
    difficulty: "hard",
    prompt: {
      en: "In the Oath, the phrase His Heirs and Successors comes directly after the title…",
    },
    options: [
      { en: "King of Canada" },
      { en: "Defender of the Faith" },
      { en: "Head of State" },
      { en: "Lord of Canada" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The Oath reads: King Charles the Third, King of Canada, His Heirs and Successors.",
    },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "rts-h-026",
    topicId: "rights",
    difficulty: "hard",
    prompt: {
      en: "According to Understanding the Oath, loyalty is professed to a person rather than to…",
    },
    options: [
      { en: "fellow citizens" },
      {
        en: "a document such as a constitution, a banner such as a flag, or a geopolitical entity such as a country",
      },
      { en: "the Sovereign" },
      { en: "the government" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Loyalty is professed to a person, not to a document such as a constitution, a banner such as a flag, or a geopolitical entity such as a country.",
    },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "rts-h-027",
    topicId: "rights",
    difficulty: "hard",
    prompt: {
      en: "Which of these is NOT part of taking responsibility for oneself and one's family?",
    },
    options: [
      { en: "Getting a job" },
      { en: "Taking care of one's family" },
      { en: "Serving on a jury" },
      { en: "Working hard in keeping with one's abilities" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Serving on a jury is a separate citizenship responsibility, not part of taking responsibility for oneself and one's family.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-h-028",
    topicId: "rights",
    difficulty: "hard",
    prompt: { en: "Every citizen has a role to play in avoiding waste and pollution while…" },
    options: [
      { en: "building new highways" },
      { en: "expanding cities" },
      { en: "increasing tourism" },
      {
        en: "protecting Canada's natural, cultural and architectural heritage for future generations",
      },
    ],
    answerIndex: 3,
    explanation: {
      en: "Every citizen has a role in avoiding waste and pollution while protecting Canada's natural, cultural and architectural heritage for future generations.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-h-029",
    topicId: "rights",
    difficulty: "hard",
    prompt: { en: "Which statement about the cadets is TRUE?" },
    options: [
      {
        en: "Young people learn discipline, responsibility, and skills, and can learn more at www.cadets.ca",
      },
      { en: "Cadets is only for adults" },
      { en: "Cadets is a paid full-time job" },
      { en: "Cadets requires moving to Ottawa" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Young people can learn discipline, responsibility, and skills by getting involved in the cadets (www.cadets.ca).",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-h-030",
    topicId: "rights",
    difficulty: "hard",
    prompt: { en: "Which statement about the reserves is TRUE?" },
    options: [
      { en: "Reserves are full-time only" },
      {
        en: "Canadians can serve in their local part-time navy, militia and air reserves and gain valuable experience, skills and contacts",
      },
      { en: "Reserves do not accept citizens" },
      { en: "Reserves require living in Ottawa" },
    ],
    answerIndex: 1,
    explanation: {
      en: "You can serve in your local part-time navy, militia and air reserves and gain valuable experience, skills and contacts.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-h-031",
    topicId: "rights",
    difficulty: "hard",
    prompt: { en: "Which statement about equality in Canada is FALSE?" },
    options: [
      { en: "Men and women are equal under the law" },
      { en: "Those guilty of gender-based violence are severely punished" },
      { en: "Barbaric cultural practices are tolerated as private matters" },
      { en: "Forced marriage is not tolerated" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Canada's openness and generosity do not extend to barbaric cultural practices, so they are not tolerated.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-h-032",
    topicId: "rights",
    difficulty: "hard",
    prompt: { en: "Which of the following is NOT part of mobility rights?" },
    options: [
      { en: "Living and working anywhere in Canada" },
      { en: "Entering and leaving the country freely" },
      { en: "Applying for a passport" },
      { en: "The right to vote in provincial elections" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Mobility rights cover living and working anywhere, entering and leaving freely, and applying for a passport — voting is a separate responsibility.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-h-033",
    topicId: "rights",
    difficulty: "hard",
    prompt: {
      en: "The Charter names Official Language Rights and Minority Language Educational Rights. How many distinct rights are named here?",
    },
    options: [{ en: "Two" }, { en: "One" }, { en: "Three" }, { en: "Four" }],
    answerIndex: 0,
    explanation: {
      en: "Two distinct rights are named: Official Language Rights and Minority Language Educational Rights.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-h-034",
    topicId: "rights",
    difficulty: "hard",
    prompt: { en: "Canadians celebrate the gift of one another's presence and…" },
    options: [
      { en: "work hard to earn more money" },
      { en: "work hard to respect pluralism and live in harmony" },
      { en: "work hard to build monuments" },
      { en: "work hard to learn history" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Canadians celebrate the gift of one another's presence and work hard to respect pluralism and live in harmony.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-h-035",
    topicId: "rights",
    difficulty: "hard",
    prompt: { en: "In the Oath, new citizens swear to be faithful and bear true allegiance to…" },
    options: [
      { en: "the Canadian people" },
      { en: "the Charter of Rights" },
      { en: "the Prime Minister" },
      { en: "His Majesty King Charles the Third, King of Canada, His Heirs and Successors" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The full allegiance line is: His Majesty King Charles the Third, King of Canada, His Heirs and Successors.",
    },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "rts-h-036",
    topicId: "rights",
    difficulty: "hard",
    prompt: { en: "The French phrase Y compris la Constitution corresponds to…" },
    options: [
      { en: "the laws of Britain" },
      { en: "my duties as a citizen" },
      { en: "the King of Canada" },
      { en: "Including the Constitution" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Y compris la Constitution is the French rendering of Including the Constitution.",
    },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "rts-h-037",
    topicId: "rights",
    difficulty: "hard",
    prompt: { en: "The French phrase Et porterai sincère allégeance corresponds to…" },
    options: [
      { en: "And bear true allegiance" },
      { en: "I swear or affirm" },
      { en: "the laws of Canada" },
      { en: "my fellow citizens" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Et porterai sincère allégeance is the French rendering of And bear true allegiance.",
    },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "rts-h-038",
    topicId: "rights",
    difficulty: "hard",
    prompt: {
      en: "Which citizenship responsibility is most closely connected to the justice system?",
    },
    options: [
      { en: "Helping in the community" },
      { en: "Serving on a jury" },
      { en: "Voting in elections" },
      { en: "Protecting the environment" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Serving on a jury makes the justice system work through impartial juries made up of citizens.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-h-039",
    topicId: "rights",
    difficulty: "hard",
    prompt: {
      en: "Which responsibility is tied to one of Canada's founding principles, the rule of law?",
    },
    options: [
      { en: "Voting in elections" },
      { en: "Helping in the community" },
      { en: "Obeying the law" },
      { en: "Serving on a jury" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Obeying the law is the responsibility tied to the founding principle of the rule of law.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-h-040",
    topicId: "rights",
    difficulty: "hard",
    prompt: { en: "About how many Canadians volunteer? The guide says…" },
    options: [{ en: "thousands" }, { en: "hundreds" }, { en: "dozens" }, { en: "millions" }],
    answerIndex: 3,
    explanation: {
      en: "The guide says millions of volunteers freely donate their time to help others without pay.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-h-041",
    topicId: "rights",
    difficulty: "hard",
    prompt: {
      en: "What was amended in 1982 to entrench the Canadian Charter of Rights and Freedoms?",
    },
    options: [
      { en: "The Constitution of Canada" },
      { en: "The Magna Carta" },
      { en: "The British Parliament" },
      { en: "The French civil code" },
    ],
    answerIndex: 0,
    explanation: { en: "The Constitution of Canada was amended in 1982 to entrench the Charter." },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-h-042",
    topicId: "rights",
    difficulty: "hard",
    prompt: { en: "The amended Constitution was proclaimed by Queen Elizabeth II in Ottawa in…" },
    options: [{ en: "1867" }, { en: "1982" }, { en: "1215" }, { en: "2001" }],
    answerIndex: 1,
    explanation: {
      en: "Queen Elizabeth II proclaimed the amended Constitution in Ottawa in 1982.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-h-043",
    topicId: "rights",
    difficulty: "hard",
    prompt: { en: "Serving in the military is…" },
    options: [
      { en: "a listed citizenship responsibility" },
      { en: "required of all newcomers" },
      { en: "not listed as a citizenship responsibility; there is no compulsory service" },
      { en: "forbidden to citizens" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Military service is not among the listed citizenship responsibilities, and there is no compulsory military service in Canada.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-h-044",
    topicId: "rights",
    difficulty: "hard",
    prompt: { en: "In the second fundamental freedom, which noun is listed first?" },
    options: [{ en: "belief" }, { en: "opinion" }, { en: "expression" }, { en: "thought" }],
    answerIndex: 3,
    explanation: {
      en: "The freedom reads: freedom of thought, belief, opinion and expression — thought comes first.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-h-045",
    topicId: "rights",
    difficulty: "hard",
    prompt: {
      en: "The French Oath ends Et que je remplirai loyalement mes obligations de citoyen canadien, which corresponds to…",
    },
    options: [
      { en: "And fulfil my duties as a Canadian citizen" },
      { en: "I swear or affirm" },
      { en: "the King of Canada" },
      { en: "the laws of Canada" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The closing French line renders And fulfil my duties as a Canadian citizen.",
    },
    source: src("The Oath of Citizenship"),
  },
];
