/**
 * Question bank chunk — part of questions.generated.ts. DO NOT EDIT BY HAND.
 */
import type { Question } from "../content";
import { src } from "./shared";

export const rightsA: Question[] = [
  {
    id: "rts-e-001",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "Which of the following is one of the four fundamental freedoms in Canada?" },
    options: [
      { en: "Freedom of conscience and religion" },
      { en: "The right to free university education" },
      { en: "The right to drive without a licence" },
      { en: "Freedom from paying taxes" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Freedom of conscience and religion is one of the four fundamental freedoms rooted in the 800-year-old tradition of ordered liberty.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-002",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "Freedom of speech and of the press are part of which fundamental freedom?" },
    options: [
      { en: "Freedom of peaceful assembly" },
      { en: "Freedom of thought, belief, opinion and expression" },
      { en: "Freedom of association" },
      { en: "The right to a passport" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The guide lists freedom of thought, belief, opinion and expression, including freedom of speech and of the press.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-003",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "The fundamental freedom of assembly is described as freedom of ___ assembly." },
    options: [{ en: "unlimited" }, { en: "secret" }, { en: "peaceful" }, { en: "paid" }],
    answerIndex: 2,
    explanation: {
      en: "The guide lists freedom of peaceful assembly among the four fundamental freedoms.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-004",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "Which of the following is NOT one of the four fundamental freedoms?" },
    options: [
      { en: "Freedom of conscience and religion" },
      { en: "Freedom of association" },
      { en: "Freedom of peaceful assembly" },
      { en: "The right to free health care" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The four fundamental freedoms are conscience and religion; thought, belief, opinion and expression; peaceful assembly; and association.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-005",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "In what year was the Magna Carta signed?" },
    options: [{ en: "1215" }, { en: "1492" }, { en: "1776" }, { en: "1982" }],
    answerIndex: 0,
    explanation: {
      en: "The 800-year-old tradition of ordered liberty dates back to the signing of Magna Carta in 1215 in England.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-006",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "The Magna Carta is also known as the…" },
    options: [
      { en: "Charter of the Forest" },
      { en: "Great Charter of Freedoms" },
      { en: "Bill of Rights" },
      { en: "Constitution Act" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The guide notes Magna Carta is also known as the Great Charter of Freedoms.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-007",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "Habeas corpus is the right to…" },
    options: [
      { en: "vote in federal elections" },
      { en: "own property anywhere" },
      { en: "challenge unlawful detention by the state" },
      { en: "a free lawyer in civil court" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Habeas corpus, the right to challenge unlawful detention by the state, comes from English common law.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-008",
    topicId: "rights",
    difficulty: "easy",
    prompt: {
      en: "In which year was the Constitution amended to entrench the Canadian Charter of Rights and Freedoms?",
    },
    options: [{ en: "1867" }, { en: "1949" }, { en: "1960" }, { en: "1982" }],
    answerIndex: 3,
    explanation: {
      en: "The Constitution of Canada was amended in 1982 to entrench the Canadian Charter of Rights and Freedoms.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-009",
    topicId: "rights",
    difficulty: "easy",
    prompt: {
      en: "Amira moves from Halifax to Vancouver for a new job. Which Charter right protects her choice?",
    },
    options: [
      { en: "Mobility Rights" },
      { en: "The right to free housing" },
      { en: "Voting rights" },
      { en: "The right to a government job" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Mobility rights mean Canadians can live and work anywhere they choose in Canada.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-010",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "Under mobility rights, Canadians may…" },
    options: [
      { en: "vote in any country's elections" },
      { en: "apply for a passport" },
      { en: "avoid paying taxes" },
      { en: "serve on any jury" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Mobility rights include the right to enter and leave the country freely and to apply for a passport.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-011",
    topicId: "rights",
    difficulty: "easy",
    prompt: {
      en: "Which two languages have equal status in Parliament and throughout the government?",
    },
    options: [
      { en: "English and Spanish" },
      { en: "English and Mandarin" },
      { en: "French and English" },
      { en: "French and German" },
    ],
    answerIndex: 2,
    explanation: {
      en: "French and English have equal status in Parliament and throughout the government.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-012",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "Multiculturalism is described as…" },
    options: [
      { en: "a recent government policy" },
      { en: "a provincial program" },
      { en: "a requirement for newcomers only" },
      { en: "a fundamental characteristic of the Canadian heritage and identity" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The guide calls multiculturalism a fundamental characteristic of the Canadian heritage and identity.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-013",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "In Canada, men and women are…" },
    options: [
      { en: "equal under the law" },
      { en: "given different legal rights" },
      { en: "equal only in the workplace" },
      { en: "subject to different criminal laws" },
    ],
    answerIndex: 0,
    explanation: { en: "In Canada, men and women are equal under the law." },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-014",
    topicId: "rights",
    difficulty: "easy",
    prompt: {
      en: "Which of the following is listed as a barbaric cultural practice not tolerated in Canada?",
    },
    options: [
      { en: "Multicultural festivals" },
      { en: "Forced marriage" },
      { en: "Religious holidays" },
      { en: "Traditional weddings" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Forced marriage is listed among the barbaric cultural practices that Canada does not tolerate.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-015",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "Those guilty of honour killings and other gender-based violence are…" },
    options: [
      { en: "given a warning" },
      { en: "fined a small amount" },
      { en: "severely punished under Canada's criminal laws" },
      { en: "asked to leave the country" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Those guilty of these crimes are severely punished under Canada's criminal laws.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-016",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "One of Canada's founding principles is…" },
    options: [
      { en: "the divine right of kings" },
      { en: "majority rule without limits" },
      { en: "the separation of church and state" },
      { en: "the rule of law" },
    ],
    answerIndex: 3,
    explanation: { en: "One of Canada's founding principles is the rule of law." },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-017",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "Under the rule of law, no person or group is…" },
    options: [
      { en: "above the law" },
      { en: "allowed to vote" },
      { en: "required to pay taxes" },
      { en: "permitted to travel" },
    ],
    answerIndex: 0,
    explanation: { en: "The guide states that no person or group is above the law." },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-018",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "When called to serve on a jury, a Canadian citizen is…" },
    options: [
      { en: "invited but free to refuse" },
      { en: "legally required to serve" },
      { en: "paid a full salary" },
      { en: "excused automatically" },
    ],
    answerIndex: 1,
    explanation: { en: "When called to do so, you are legally required to serve on a jury." },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-019",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "The right to vote comes with…" },
    options: [
      { en: "a tax refund" },
      { en: "a free bus pass" },
      { en: "a responsibility to vote" },
      { en: "a government job" },
    ],
    answerIndex: 2,
    explanation: { en: "The guide says the right to vote comes with a responsibility to vote." },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-020",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "Which statement about military service in Canada is true?" },
    options: [
      { en: "All men must serve for two years" },
      { en: "Military service is required at age 18" },
      { en: "Only citizens born in Canada may serve" },
      { en: "There is no compulsory military service in Canada" },
    ],
    answerIndex: 3,
    explanation: { en: "The guide states there is no compulsory military service in Canada." },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-021",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "In the Oath of Citizenship, new citizens swear allegiance to…" },
    options: [
      { en: "His Majesty King Charles the Third" },
      { en: "the Prime Minister of Canada" },
      { en: "the Canadian flag" },
      { en: "the Constitution alone" },
    ],
    answerIndex: 0,
    explanation: {
      en: "New citizens swear to bear true allegiance to His Majesty King Charles the Third.",
    },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "rts-e-022",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "When do new citizens repeat the Oath of Citizenship?" },
    options: [
      { en: "When they first arrive in Canada" },
      { en: "At the citizenship ceremony" },
      { en: "At their first job interview" },
      { en: "When they turn 18" },
    ],
    answerIndex: 1,
    explanation: { en: "At the citizenship ceremony, you will repeat the Oath of Citizenship." },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "rts-e-023",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "In the Oath, King Charles the Third is given the title…" },
    options: [
      { en: "Defender of Canada" },
      { en: "Head of Parliament" },
      { en: "King of Canada" },
      { en: "Lord of the Provinces" },
    ],
    answerIndex: 2,
    explanation: { en: "The Oath addresses him as King Charles the Third, King of Canada." },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "rts-e-024",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "The Oath recognizes the Aboriginal and treaty rights of…" },
    options: [
      { en: "First Nations only" },
      { en: "Inuit and Métis only" },
      { en: "newcomers and refugees" },
      { en: "First Nations, Inuit and Métis peoples" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The Oath refers to the Aboriginal and treaty rights of First Nations, Inuit and Métis peoples.",
    },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "rts-e-025",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "The Oath of Citizenship begins with the words…" },
    options: [
      { en: "I swear (or affirm)" },
      { en: "I promise Canada" },
      { en: "We the people" },
      { en: "Hear me now" },
    ],
    answerIndex: 0,
    explanation: { en: "The Oath begins: I swear (or affirm) that I will be faithful…" },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "rts-e-026",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "Which is an example of helping others in the community?" },
    options: [
      { en: "Cheering at a hockey game" },
      { en: "Volunteering at a food bank" },
      { en: "Shopping at the mall" },
      { en: "Watching television" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Volunteering at a food bank or other charity is given as an example of helping others in the community.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-027",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "Taking responsibility for oneself and one's family includes…" },
    options: [
      { en: "buying a bigger house" },
      { en: "travelling every year" },
      { en: "taking care of one's family" },
      { en: "retiring early" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Taking care of one's family is part of taking responsibility for oneself and one's family.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-028",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "Canadians protect their heritage and environment for…" },
    options: [
      { en: "tourists" },
      { en: "the government" },
      { en: "foreign investors" },
      { en: "future generations" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Citizens protect Canada's natural, cultural and architectural heritage for future generations.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-029",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "Every citizen has a role to play in avoiding…" },
    options: [
      { en: "waste and pollution" },
      { en: "all technology" },
      { en: "public transit" },
      { en: "community events" },
    ],
    answerIndex: 0,
    explanation: { en: "Every citizen has a role to play in avoiding waste and pollution." },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-030",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "The regular Canadian Forces consist of the…" },
    options: [
      { en: "police, fire and ambulance services" },
      { en: "navy, army and air force" },
      { en: "coast guard, reserves and cadets" },
      { en: "army and navy only" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Serving in the regular Canadian Forces means the navy, army and air force.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-031",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "Young people can learn discipline, responsibility and skills by joining the…" },
    options: [{ en: "hockey league" }, { en: "choir" }, { en: "cadets" }, { en: "debate club" }],
    answerIndex: 2,
    explanation: {
      en: "Young people can learn discipline, responsibility, and skills by getting involved in the cadets.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-032",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "The guide gives these as examples of community emergency services:" },
    options: [
      { en: "The army and navy" },
      { en: "The coast guard and reserves" },
      { en: "Hospitals and schools" },
      { en: "a police force or fire department" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Canadians may serve in emergency services in their community such as a police force or fire department.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-033",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "French and English have equal status in…" },
    options: [
      { en: "Parliament and throughout the government" },
      { en: "only in Quebec" },
      { en: "only in federal courts" },
      { en: "schools but not government" },
    ],
    answerIndex: 0,
    explanation: {
      en: "French and English have equal status in Parliament and throughout the government.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-034",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "Canadians celebrate…" },
    options: [
      { en: "only their own culture" },
      { en: "the gift of one another's presence" },
      { en: "public holidays alone" },
      { en: "sporting victories" },
    ],
    answerIndex: 1,
    explanation: { en: "The guide says Canadians celebrate the gift of one another's presence." },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-035",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "Canadians work hard to respect pluralism and…" },
    options: [
      { en: "avoid newcomers" },
      { en: "speak one language" },
      { en: "live in harmony" },
      { en: "follow one religion" },
    ],
    answerIndex: 2,
    explanation: { en: "Canadians work hard to respect pluralism and live in harmony." },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-036",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "The rights guaranteed in the Charter will not…" },
    options: [
      { en: "apply in Quebec" },
      { en: "protect newcomers" },
      { en: "be written down" },
      { en: "adversely affect any treaty or other rights or freedoms of Aboriginal peoples" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The rights guaranteed in the Charter will not adversely affect any treaty or other rights or freedoms of Aboriginal peoples.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-037",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "In the Oath, new citizens promise to faithfully observe…" },
    options: [
      { en: "the laws of Canada" },
      { en: "the laws of Britain" },
      { en: "only provincial laws" },
      { en: "traffic laws only" },
    ],
    answerIndex: 0,
    explanation: { en: "The Oath promises: I will faithfully observe the laws of Canada." },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "rts-e-038",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "The Oath ends with a promise to…" },
    options: [
      { en: "serve in the military" },
      { en: "fulfil my duties as a Canadian citizen" },
      { en: "pay higher taxes" },
      { en: "learn French" },
    ],
    answerIndex: 1,
    explanation: { en: "The Oath ends: and fulfil my duties as a Canadian citizen." },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "rts-e-039",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "In Canada, citizens profess loyalty to…" },
    options: [
      { en: "a written constitution" },
      { en: "the national flag" },
      { en: "a person who represents all Canadians" },
      { en: "the land itself" },
    ],
    answerIndex: 2,
    explanation: {
      en: "In Canada, we profess our loyalty to a person who represents all Canadians.",
    },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "rts-e-040",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "Canada's system, in which the Sovereign personifies the country, is called a…" },
    options: [
      { en: "republic" },
      { en: "direct democracy" },
      { en: "one-party state" },
      { en: "constitutional monarchy" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The guide says: In our constitutional monarchy, these elements are encompassed by the Sovereign.",
    },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "rts-e-041",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "Which of these community activities is mentioned in the guide?" },
    options: [
      { en: "Encouraging newcomers to integrate" },
      { en: "Organizing protests" },
      { en: "Running a business" },
      { en: "Coaching professional sports" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Encouraging newcomers to integrate is listed as a way of helping others in the community.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-042",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "Work contributes to…" },
    options: [
      { en: "longer vacations" },
      { en: "personal dignity and self-respect" },
      { en: "higher taxes" },
      { en: "shorter work weeks" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Work contributes to personal dignity and self-respect, and to Canada's prosperity.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-043",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "The justice system depends on…" },
    options: [
      { en: "paid professional jurors" },
      { en: "government officials only" },
      { en: "impartial juries made up of citizens" },
      { en: "foreign judges" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The justice system works as it depends on impartial juries made up of citizens.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-044",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "Serving on a jury is described as…" },
    options: [
      { en: "a burden" },
      { en: "a paid job" },
      { en: "a punishment" },
      { en: "a privilege" },
    ],
    answerIndex: 3,
    explanation: { en: "Serving on a jury is a privilege that makes the justice system work." },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-045",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "Canadians can serve part-time in their local…" },
    options: [
      { en: "navy, militia and air reserves" },
      { en: "regular army units" },
      { en: "foreign legion" },
      { en: "provincial police" },
    ],
    answerIndex: 0,
    explanation: { en: "You can serve in your local part-time navy, militia and air reserves." },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-046",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "Besides the Canadian Forces, Canadians may also serve in the…" },
    options: [
      { en: "United Nations army" },
      { en: "Coast Guard" },
      { en: "foreign navy" },
      { en: "private security firms" },
    ],
    answerIndex: 1,
    explanation: {
      en: "You may also serve in the Coast Guard or emergency services in your community.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-047",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "By protecting their community, Canadians follow in the footsteps of…" },
    options: [
      { en: "famous athletes" },
      { en: "European settlers only" },
      { en: "Canadians before them who made sacrifices in the service of the country" },
      { en: "their employers" },
    ],
    answerIndex: 2,
    explanation: {
      en: "By helping to protect your community, you follow in the footsteps of Canadians before you who made sacrifices in the service of our country.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-048",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "The current Oath of Citizenship refers to…" },
    options: [
      { en: "the rights of newcomers" },
      { en: "provincial constitutions" },
      { en: "the national anthem" },
      { en: "the Aboriginal and treaty rights of Indigenous peoples in Canada" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The Oath now refers to the Aboriginal and treaty rights of Indigenous peoples in Canada.",
    },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "rts-e-049",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "The study guide presents the Oath of Citizenship in…" },
    options: [
      { en: "English and French" },
      { en: "English only" },
      { en: "French only" },
      { en: "English and Spanish" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The guide gives the Oath in English and in French as Le serment de citoyenneté.",
    },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "rts-e-050",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "Canadian citizens' rights and responsibilities…" },
    options: [
      { en: "were invented in 1982" },
      {
        en: "come to us from our history, are secured by Canadian law, and reflect our shared traditions, identity and values",
      },
      { en: "come only from the Charter" },
      { en: "apply only to newcomers" },
    ],
    answerIndex: 1,
    explanation: {
      en: "These come to us from our history, are secured by Canadian law, and reflect our shared traditions, identity, and values.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-051",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "Which of the following is a source of Canadian law?" },
    options: [
      { en: "The American Bill of Rights" },
      { en: "United Nations resolutions" },
      { en: "English common law" },
      { en: "Religious scripture" },
    ],
    answerIndex: 2,
    explanation: { en: "Canadian law has several sources, including English common law." },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-052",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "The civil code of France is…" },
    options: [
      { en: "the only source of Canadian law" },
      { en: "not used in Canada" },
      { en: "a criminal code" },
      { en: "a source of Canadian law" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The civil code of France is listed as one of the sources of Canadian law.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-053",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "Canada inherited its unwritten constitution from…" },
    options: [
      { en: "Great Britain" },
      { en: "France" },
      { en: "the United States" },
      { en: "the United Nations" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Canadian law includes the unwritten constitution that we have inherited from Great Britain.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-054",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "Canadian law includes laws passed by…" },
    options: [
      { en: "city councils only" },
      { en: "Parliament and the provincial legislatures" },
      { en: "the courts alone" },
      { en: "the Sovereign personally" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Canadian law includes laws passed by Parliament and the provincial legislatures.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-055",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "The responsibility to vote covers elections at which levels?" },
    options: [
      { en: "Federal only" },
      { en: "Federal and provincial only" },
      { en: "Federal, provincial or territorial, and local" },
      { en: "Local only" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The right to vote comes with a responsibility to vote in federal, provincial or territorial and local elections.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-056",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "Habeas corpus comes from…" },
    options: [
      { en: "the Charter of 1982" },
      { en: "French civil law" },
      { en: "the Magna Carta directly" },
      { en: "English common law" },
    ],
    answerIndex: 3,
    explanation: { en: "Habeas corpus comes from English common law." },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-057",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "The Canadian Charter of Rights and Freedoms begins with the word…" },
    options: [{ en: "Whereas" }, { en: "We" }, { en: "In" }, { en: "Be" }],
    answerIndex: 0,
    explanation: {
      en: "The Charter begins with the words, Whereas Canada is founded upon principles…",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-058",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "Volunteering is an excellent way to…" },
    options: [
      { en: "avoid taxes" },
      { en: "gain useful skills and develop friends and contacts" },
      { en: "get rich" },
      { en: "skip jury duty" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Volunteering is an excellent way to gain useful skills and develop friends and contacts.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-059",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "In the Oath, His Heirs and Successors refers to the heirs and successors of…" },
    options: [
      { en: "the Prime Minister" },
      { en: "the Governor General" },
      { en: "His Majesty King Charles the Third" },
      { en: "Parliament" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The Oath swears allegiance to His Majesty King Charles the Third, King of Canada, His Heirs and Successors.",
    },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "rts-e-060",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "Millions of volunteers freely donate their time to help others…" },
    options: [
      { en: "for high pay" },
      { en: "only on holidays" },
      { en: "for school credit" },
      { en: "without pay" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Millions of volunteers freely donate their time to help others without pay.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-061",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "Which is a way to help others in the community?" },
    options: [
      { en: "Assisting at your child's school" },
      { en: "Complaining online" },
      { en: "Avoiding neighbours" },
      { en: "Working overtime" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Assisting at your child's school is listed as a way of helping others in the community.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-062",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "Canadians protect their…" },
    options: [
      { en: "personal savings" },
      { en: "natural, cultural and architectural heritage" },
      { en: "private property only" },
      { en: "foreign investments" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Citizens protect Canada's natural, cultural and architectural heritage for future generations.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-063",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "Loyalty in Canada is professed to a person, not to…" },
    options: [
      { en: "a person who represents all Canadians" },
      { en: "the Sovereign" },
      { en: "a document such as a constitution" },
      { en: "the King" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Loyalty is professed to a person, not to a document such as a constitution.",
    },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "rts-e-064",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "Taking responsibility for oneself includes…" },
    options: [
      { en: "winning the lottery" },
      { en: "inheriting money" },
      { en: "avoiding work" },
      { en: "getting a job" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Getting a job is part of taking responsibility for oneself and one's family.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-065",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "Important Canadian values include working hard…" },
    options: [
      { en: "in keeping with one's abilities" },
      { en: "only for high pay" },
      { en: "without rest" },
      { en: "for the government" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Working hard in keeping with one's abilities is described as an important Canadian value.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-066",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "Individuals and governments are regulated by laws and not by…" },
    options: [
      { en: "written rules" },
      { en: "arbitrary actions" },
      { en: "court decisions" },
      { en: "public opinion" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Individuals and governments are regulated by laws and not by arbitrary actions.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-067",
    topicId: "rights",
    difficulty: "easy",
    prompt: {
      en: "Yusuf travels abroad for a vacation and returns to Canada freely. Which right protects this?",
    },
    options: [
      { en: "Official Language Rights" },
      { en: "Aboriginal Peoples' Rights" },
      { en: "Mobility Rights" },
      { en: "The right to vote" },
    ],
    answerIndex: 2,
    explanation: { en: "Mobility rights include entering and leaving the country freely." },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-068",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "Canada's openness and generosity do not extend to…" },
    options: [
      { en: "multicultural festivals" },
      { en: "religious celebrations" },
      { en: "community volunteering" },
      { en: "barbaric cultural practices" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Canada's openness and generosity do not extend to barbaric cultural practices.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-069",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "Which of the following is NOT listed among the barbaric cultural practices?" },
    options: [
      { en: "Arranged marriage" },
      { en: "Forced marriage" },
      { en: "Honour killings" },
      { en: "Female genital mutilation" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The guide lists forced marriage, honour killings, female genital mutilation, spousal abuse and other gender-based violence — not arranged marriage.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-070",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "Serving in the regular Canadian Forces is described as…" },
    options: [
      { en: "a last resort" },
      { en: "a noble way to contribute to Canada" },
      { en: "mandatory for all" },
      { en: "a temporary job" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Serving in the regular Canadian Forces is a noble way to contribute to Canada.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-071",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "Which of these is listed as a barbaric cultural practice?" },
    options: [
      { en: "Public dancing" },
      { en: "Wearing traditional clothing" },
      { en: "Spousal abuse" },
      { en: "Speaking another language" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Spousal abuse is listed among the barbaric cultural practices Canada does not tolerate.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-e-072",
    topicId: "rights",
    difficulty: "easy",
    prompt: { en: "Work contributes to Canada's…" },
    options: [{ en: "population" }, { en: "military" }, { en: "borders" }, { en: "prosperity" }],
    answerIndex: 3,
    explanation: {
      en: "Work contributes to personal dignity and self-respect, and to Canada's prosperity.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-m-001",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "The Magna Carta was signed in…" },
    options: [{ en: "England" }, { en: "France" }, { en: "Canada" }, { en: "Scotland" }],
    answerIndex: 0,
    explanation: { en: "The signing of Magna Carta in 1215 took place in England." },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-m-002",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "The 800-year-old tradition inherited by Canadians is described as one of…" },
    options: [
      { en: "ordered democracy" },
      { en: "ordered liberty" },
      { en: "ordered equality" },
      { en: "ordered prosperity" },
    ],
    answerIndex: 1,
    explanation: { en: "Canadians are secured an 800-year-old tradition of ordered liberty." },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-m-003",
    topicId: "rights",
    difficulty: "medium",
    prompt: {
      en: "According to the Charter's opening words, Canada is founded upon principles that recognize the supremacy of…",
    },
    options: [{ en: "Parliament" }, { en: "the people" }, { en: "God" }, { en: "the courts" }],
    answerIndex: 2,
    explanation: {
      en: "The Charter begins: Whereas Canada is founded upon principles that recognize the supremacy of God and the rule of law.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-m-004",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "The Charter's opening words also recognize…" },
    options: [
      { en: "the supremacy of Parliament" },
      { en: "the right to vote" },
      { en: "free trade" },
      { en: "the rule of law" },
    ],
    answerIndex: 3,
    explanation: { en: "The opening phrase recognizes the supremacy of God and the rule of law." },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-m-005",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "The Charter's opening phrase underlines the importance of…" },
    options: [
      { en: "religious traditions to Canadian society" },
      { en: "military traditions" },
      { en: "economic growth" },
      { en: "technological progress" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The phrase underlines the importance of religious traditions to Canadian society.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-m-006",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "The Charter's opening phrase also underlines…" },
    options: [
      { en: "the power of the state" },
      { en: "the dignity and worth of the human person" },
      { en: "the wealth of the nation" },
      { en: "the size of the country" },
    ],
    answerIndex: 1,
    explanation: { en: "The phrase also underlines the dignity and worth of the human person." },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-m-007",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "Who proclaimed the amended Constitution in 1982?" },
    options: [
      { en: "King Charles the Third" },
      { en: "Queen Victoria" },
      { en: "Queen Elizabeth II" },
      { en: "King George VI" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Queen Elizabeth II proclaimed the amended Constitution in Ottawa in 1982.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-m-008",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "The website given in the guide for Canadian Forces careers is…" },
    options: [
      { en: "www.canada.ca" },
      { en: "www.army.ca" },
      { en: "www.defence.ca" },
      { en: "www.forces.ca" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Serving in the regular Canadian Forces is an excellent career choice (www.forces.ca).",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-m-009",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "The website given in the guide for the cadets program is…" },
    options: [
      { en: "www.cadets.ca" },
      { en: "www.youth.ca" },
      { en: "www.forces.ca" },
      { en: "www.cadets.com" },
    ],
    answerIndex: 0,
    explanation: { en: "Young people can get involved in the cadets (www.cadets.ca)." },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-m-010",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "Besides Official Language Rights, the Charter sets out…" },
    options: [
      { en: "Property Rights" },
      { en: "Minority Language Educational Rights" },
      { en: "Workers' Rights" },
      { en: "Travel Rights" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The guide lists Official Language Rights and Minority Language Educational Rights.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-m-011",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "The Charter will not adversely affect any ___ rights of Aboriginal peoples." },
    options: [{ en: "voting" }, { en: "hunting" }, { en: "treaty" }, { en: "property" }],
    answerIndex: 2,
    explanation: {
      en: "The Charter will not adversely affect any treaty or other rights or freedoms of Aboriginal peoples.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-m-012",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "The Charter attempts to…" },
    options: [
      { en: "replace all provincial laws" },
      { en: "list every Canadian law" },
      { en: "abolish the common law" },
      { en: "summarize fundamental freedoms while also setting out additional rights" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The Charter attempts to summarize fundamental freedoms while also setting out additional rights.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-m-013",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "Which option gives the complete wording of the second fundamental freedom?" },
    options: [
      {
        en: "Freedom of thought, belief, opinion and expression, including freedom of speech and of the press",
      },
      { en: "Freedom of speech" },
      { en: "Freedom of the press" },
      { en: "Freedom of thought and belief" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The full wording is freedom of thought, belief, opinion and expression, including freedom of speech and of the press.",
    },
    source: src("Rights and Responsibilities of Citizenship"),
  },
  {
    id: "rts-m-014",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "According to the Oath, the Constitution…" },
    options: [
      { en: "was written in 1867" },
      {
        en: "recognizes and affirms the Aboriginal and treaty rights of First Nations, Inuit and Métis peoples",
      },
      { en: "applies only in Ontario" },
      { en: "was abolished" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The Oath refers to the Constitution which recognizes and affirms the Aboriginal and treaty rights of First Nations, Inuit and Métis peoples.",
    },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "rts-m-015",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "The Oath promises to observe the laws of Canada…" },
    options: [
      { en: "except in Quebec" },
      { en: "only when convenient" },
      { en: "including the Constitution" },
      { en: "except for newcomers" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The Oath promises to faithfully observe the laws of Canada, including the Constitution.",
    },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "rts-m-016",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "The guide says Canadians do not profess loyalty to…" },
    options: [
      { en: "the Sovereign" },
      { en: "a person who represents all Canadians" },
      { en: "the King" },
      { en: "a banner such as a flag" },
    ],
    answerIndex: 3,
    explanation: { en: "Loyalty is professed to a person, not to a banner such as a flag." },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "rts-m-017",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "Which of the following is NOT something Canadians profess loyalty to?" },
    options: [
      { en: "a geopolitical entity such as a country" },
      { en: "the Sovereign" },
      { en: "a person who represents all Canadians" },
      { en: "the King" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Loyalty is professed to a person, not to a geopolitical entity such as a country.",
    },
    source: src("The Oath of Citizenship"),
  },
  {
    id: "rts-m-018",
    topicId: "rights",
    difficulty: "medium",
    prompt: { en: "In our constitutional monarchy, the Sovereign may be a…" },
    options: [
      { en: "President" },
      { en: "Queen or King" },
      { en: "Prime Minister" },
      { en: "Governor General" },
    ],
    answerIndex: 1,
    explanation: { en: "The elements are encompassed by the Sovereign (Queen or King)." },
    source: src("The Oath of Citizenship"),
  },
];
