/**
 * Question bank chunk — part of questions.generated.ts. DO NOT EDIT BY HAND.
 */
import type { Question } from "../content";
import { src } from "./shared";

export const symbolsB: Question[] = [
  {
    id: "sym-m-016",
    topicId: "symbols",
    difficulty: "medium",
    prompt: { en: "The legislatures of the other provinces are built in which styles?" },
    options: [
      { en: "Gothic and Tudor" },
      { en: "Baroque, Romanesque and neoclassical" },
      { en: "Art deco and modernist" },
      { en: "Colonial and Victorian" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The legislatures of the other provinces are Baroque, Romanesque and neoclassical.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-m-017",
    topicId: "symbols",
    difficulty: "medium",
    prompt: { en: "Lord Stanley, who donated the Stanley Cup in 1892, held which position?" },
    options: [
      { en: "Prime Minister" },
      { en: "Mayor of Montreal" },
      { en: "Governor General" },
      { en: "Chief Justice" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The Stanley Cup was donated by Lord Stanley, the Governor General, in 1892.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-m-018",
    topicId: "symbols",
    difficulty: "medium",
    prompt: { en: "The Clarkson Cup was established in 2005 by whom?" },
    options: [
      { en: "Lord Stanley" },
      { en: "Adrienne Clarkson" },
      { en: "Michaëlle Jean" },
      { en: "Julie Payette" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The Clarkson Cup was established in 2005 by Adrienne Clarkson, the 26th Governor General.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-m-019",
    topicId: "symbols",
    difficulty: "medium",
    prompt: {
      en: "Adrienne Clarkson, who established the Clarkson Cup, was notable as which of the following?",
    },
    options: [
      { en: "The 26th Governor General and the first of Asian origin" },
      { en: "The first woman Prime Minister" },
      { en: "The first Chief Justice of Canada" },
      { en: "The longest-serving Senator" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Adrienne Clarkson was the 26th Governor General and the first of Asian origin.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-m-020",
    topicId: "symbols",
    difficulty: "medium",
    prompt: { en: "The beaver became an emblem of the St. Jean Baptiste Society in which year?" },
    options: [{ en: "1801" }, { en: "1825" }, { en: "1830" }, { en: "1834" }],
    answerIndex: 3,
    explanation: { en: "The beaver became an emblem of the St. Jean Baptiste Society in 1834." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-m-021",
    topicId: "symbols",
    difficulty: "medium",
    prompt: { en: "The beaver appears on the coats of arms of which two provinces?" },
    options: [
      { en: "Ontario and Quebec" },
      { en: "Saskatchewan and Alberta" },
      { en: "Manitoba and British Columbia" },
      { en: "Nova Scotia and New Brunswick" },
    ],
    answerIndex: 1,
    explanation: { en: "The beaver can be seen on the coats of arms of Saskatchewan and Alberta." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-m-022",
    topicId: "symbols",
    difficulty: "medium",
    prompt: { en: "The beaver appears on the coats of arms of which two cities?" },
    options: [
      { en: "Vancouver and Calgary" },
      { en: "Ottawa and Edmonton" },
      { en: "Halifax and Winnipeg" },
      { en: "Montreal and Toronto" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The beaver appears on the coats of arms of cities such as Montreal and Toronto.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-m-023",
    topicId: "symbols",
    difficulty: "medium",
    prompt: {
      en: "English speakers and French speakers have lived together in Canada for more than how long?",
    },
    options: [{ en: "100 years" }, { en: "200 years" }, { en: "300 years" }, { en: "500 years" }],
    answerIndex: 2,
    explanation: {
      en: "Anglophones and Francophones have lived together in partnership and creative tension for more than 300 years.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-m-024",
    topicId: "symbols",
    difficulty: "medium",
    prompt: {
      en: "One objective of the Official Languages Act is to establish equality between French and English in Parliament, the Government of Canada and what else?",
    },
    options: [
      { en: "Institutions subject to the Act" },
      { en: "The courts of Quebec" },
      { en: "Public schools" },
      { en: "Private businesses" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The Act aims to establish equality between French and English in Parliament, the Government of Canada and institutions subject to the Act.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-m-025",
    topicId: "symbols",
    difficulty: "medium",
    prompt: { en: "The Official Languages Act aims to maintain and develop which communities?" },
    options: [
      { en: "Official language minority communities" },
      { en: "Rural farming communities" },
      { en: "Coastal fishing communities" },
      { en: "Northern mining communities" },
    ],
    answerIndex: 0,
    explanation: {
      en: "One objective is to maintain and develop official language minority communities in Canada.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-m-026",
    topicId: "symbols",
    difficulty: "medium",
    prompt: {
      en: "The Official Languages Act aims to promote equality of French and English in which sphere?",
    },
    options: [
      { en: "In Parliament only" },
      { en: "In the courts only" },
      { en: "In government hiring only" },
      { en: "In Canadian society" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The Act aims to promote equality of French and English in Canadian society.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-m-027",
    topicId: "symbols",
    difficulty: "medium",
    prompt: { en: "'O Canada' was first sung in which city in 1880?" },
    options: [{ en: "Ottawa" }, { en: "Québec City" }, { en: "Montreal" }, { en: "Toronto" }],
    answerIndex: 1,
    explanation: { en: "'O Canada' was first sung in Québec City in 1880." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-m-028",
    topicId: "symbols",
    difficulty: "medium",
    prompt: { en: "What is the opening line of the English version of 'O Canada'?" },
    options: [
      { en: "True patriot love in all thy sons command" },
      { en: "God keep our land glorious and free" },
      { en: "O Canada! Our home and native land!" },
      { en: "The true North strong and free!" },
    ],
    answerIndex: 2,
    explanation: { en: "The English anthem opens with 'O Canada! Our home and native land!'" },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-m-029",
    topicId: "symbols",
    difficulty: "medium",
    prompt: { en: "The second line of the English 'O Canada' is which of the following?" },
    options: [
      { en: "With shining hearts we see thee fall" },
      { en: "From sea to sea we sing thy praise" },
      { en: "Land of hope and glory" },
      { en: "True patriot love in all thy sons command" },
    ],
    answerIndex: 3,
    explanation: {
      en: "'True patriot love in all thy sons command' is the second line of 'O Canada'.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-m-030",
    topicId: "symbols",
    difficulty: "medium",
    prompt: { en: "Which line appears in the English version of 'O Canada'?" },
    options: [
      { en: "With glowing hearts we see thee rise" },
      { en: "With beating hearts we watch thee fall" },
      { en: "With joyful hearts we sing thy praise" },
      { en: "With thankful hearts we stand as one" },
    ],
    answerIndex: 0,
    explanation: { en: "'With glowing hearts we see thee rise' is a line from 'O Canada'." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-m-031",
    topicId: "symbols",
    difficulty: "medium",
    prompt: { en: "Complete the lyric: 'From far and wide, ...'" },
    options: [
      { en: "O Canada we sing to thee" },
      { en: "O Canada we stand on guard for thee" },
      { en: "O Canada we praise thy name" },
      { en: "O Canada we call to thee" },
    ],
    answerIndex: 1,
    explanation: { en: "The lyric is 'From far and wide, O Canada we stand on guard for thee'." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-m-032",
    topicId: "symbols",
    difficulty: "medium",
    prompt: { en: "Which of these is a line from the English version of 'O Canada'?" },
    options: [
      { en: "God save our land forever free" },
      { en: "God keep our land glorious and free" },
      { en: "Lord keep our nation safe and free" },
      { en: "Heaven guard our home and land" },
    ],
    answerIndex: 1,
    explanation: { en: "'God keep our land glorious and free!' is a line from 'O Canada'." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-m-033",
    topicId: "symbols",
    difficulty: "medium",
    prompt: { en: "What is the title of Canada's Royal Anthem?" },
    options: [
      { en: "O Canada" },
      { en: "The Maple Leaf Forever" },
      { en: "God Save the King (or Queen)" },
      { en: "Rule Britannia" },
    ],
    answerIndex: 2,
    explanation: { en: "Canada's Royal Anthem is 'God Save the King (or Queen)'." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-m-034",
    topicId: "symbols",
    difficulty: "medium",
    prompt: { en: "What is the opening line of the English Royal Anthem?" },
    options: [
      { en: "Long live our noble King" },
      { en: "God save our gracious King" },
      { en: "God save The King" },
      { en: "Hail to our noble King" },
    ],
    answerIndex: 1,
    explanation: { en: "The Royal Anthem opens with 'God save our gracious King'." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-m-035",
    topicId: "symbols",
    difficulty: "medium",
    prompt: { en: "Which lyric appears in the English Royal Anthem?" },
    options: [
      { en: "Long to reign over us" },
      { en: "Long may she wave" },
      { en: "Forever strong and free" },
      { en: "Ever onward" },
    ],
    answerIndex: 0,
    explanation: { en: "'Long to reign over us' appears in the English Royal Anthem." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-m-036",
    topicId: "symbols",
    difficulty: "medium",
    prompt: { en: "What is the French title of Canada's Royal Anthem?" },
    options: [
      { en: "Ô Canada" },
      { en: "Vive le Canada" },
      { en: "Chant du Roi" },
      { en: "Dieu protège le Roi" },
    ],
    answerIndex: 3,
    explanation: { en: "The French version of the Royal Anthem is titled 'Dieu protège le Roi'." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-m-037",
    topicId: "symbols",
    difficulty: "medium",
    prompt: { en: "Queen Elizabeth II marked her Golden Jubilee in which year?" },
    options: [{ en: "1997" }, { en: "2002" }, { en: "2007" }, { en: "2012" }],
    answerIndex: 1,
    explanation: { en: "Queen Elizabeth II marked her Golden Jubilee in 2002." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-m-038",
    topicId: "symbols",
    difficulty: "medium",
    prompt: {
      en: "The Crown is a symbol of government including Parliament, the legislatures, the courts and which others?",
    },
    options: [
      { en: "The banks and the media" },
      { en: "Schools and hospitals" },
      { en: "Provincial parks and museums" },
      { en: "Police services and the Canadian Forces" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The Crown is a symbol of government, including Parliament, the legislatures, the courts, police services and the Canadian Forces.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-m-039",
    topicId: "symbols",
    difficulty: "medium",
    prompt: { en: "Official awards called honours consist of which three things?" },
    options: [
      { en: "Trophies, plaques and ribbons" },
      { en: "Certificates, pins and banners" },
      { en: "Orders, decorations and medals" },
      { en: "Crowns, sceptres and seals" },
    ],
    answerIndex: 2,
    explanation: { en: "Honours consist of orders, decorations, and medals." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-m-040",
    topicId: "symbols",
    difficulty: "medium",
    prompt: {
      en: "Canada started its own honours system with the Order of Canada in the centennial year of Confederation. What was that year?",
    },
    options: [{ en: "1967" }, { en: "1965" }, { en: "1972" }, { en: "1982" }],
    answerIndex: 0,
    explanation: {
      en: "Canada started its own honours system with the Order of Canada in 1967, the centennial of Confederation.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-m-041",
    topicId: "symbols",
    difficulty: "medium",
    prompt: {
      en: "According to Discover Canada, if you know fellow citizens worthy of recognition, what are you welcome to do?",
    },
    options: [
      { en: "Nominate them for honours" },
      { en: "Write to the Prime Minister" },
      { en: "Donate to their campaign" },
      { en: "Invite them to Parliament" },
    ],
    answerIndex: 0,
    explanation: {
      en: "If you know of fellow citizens worthy of recognition, you are welcome to nominate them for honours.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-m-042",
    topicId: "symbols",
    difficulty: "medium",
    prompt: { en: "How many Canadians have been awarded the Victoria Cross since 1854?" },
    options: [{ en: "54" }, { en: "72" }, { en: "88" }, { en: "96" }],
    answerIndex: 3,
    explanation: { en: "The Victoria Cross has been awarded to 96 Canadians since 1854." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-m-043",
    topicId: "symbols",
    difficulty: "medium",
    prompt: {
      en: "Flying ace Billy Bishop, a Victoria Cross recipient, was born in which Ontario town?",
    },
    options: [{ en: "Kingston" }, { en: "Hamilton" }, { en: "Owen Sound" }, { en: "Windsor" }],
    answerIndex: 2,
    explanation: { en: "Billy Bishop was born in Owen Sound, Ontario." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-m-044",
    topicId: "symbols",
    difficulty: "medium",
    prompt: {
      en: "Which Victoria Cross recipient was the first black man to be awarded the V.C.?",
    },
    options: [
      { en: "Alexander Roberts Dunn" },
      { en: "Filip Konowal" },
      { en: "William Hall" },
      { en: "Paul Triquet" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Able Seaman William Hall of Horton, Nova Scotia, was the first black man to be awarded the V.C.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-m-045",
    topicId: "symbols",
    difficulty: "medium",
    prompt: { en: "Who was the last Canadian to receive the Victoria Cross to date?" },
    options: [
      { en: "Billy Bishop" },
      { en: "Paul Triquet" },
      { en: "Filip Konowal" },
      { en: "Robert Hampton Gray" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Lieutenant Robert Hampton Gray was the last Canadian to receive the V.C. to date.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-m-046",
    topicId: "symbols",
    difficulty: "medium",
    prompt: { en: "Victoria Day is the Monday preceding which date?" },
    options: [{ en: "May 25" }, { en: "May 1" }, { en: "June 1" }, { en: "June 24" }],
    answerIndex: 0,
    explanation: { en: "Victoria Day is the Monday preceding May 25." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-m-047",
    topicId: "symbols",
    difficulty: "medium",
    prompt: { en: "Easter Monday is which day?" },
    options: [
      { en: "The Friday before Easter" },
      { en: "The Sunday of Easter" },
      { en: "The Monday immediately following Easter Sunday" },
      { en: "The second Monday of April" },
    ],
    answerIndex: 2,
    explanation: { en: "Easter Monday is the Monday immediately following Easter Sunday." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-m-048",
    topicId: "symbols",
    difficulty: "medium",
    prompt: { en: "Good Friday is which day?" },
    options: [
      { en: "The Monday after Easter" },
      { en: "The last Friday of March" },
      { en: "The first Friday of April" },
      { en: "The Friday immediately preceding Easter Sunday" },
    ],
    answerIndex: 3,
    explanation: { en: "Good Friday is the Friday immediately preceding Easter Sunday." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-m-049",
    topicId: "symbols",
    difficulty: "medium",
    prompt: { en: "Fête Nationale on June 24 is also known as the feast of whom?" },
    options: [
      { en: "St. Patrick" },
      { en: "St. Andrew" },
      { en: "St. John the Baptist" },
      { en: "St. George" },
    ],
    answerIndex: 2,
    explanation: { en: "Fête Nationale (Quebec) on June 24 is the Feast of St. John the Baptist." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-m-050",
    topicId: "symbols",
    difficulty: "medium",
    prompt: { en: "The Parliament Buildings embody which traditions?" },
    options: [
      { en: "British and American" },
      { en: "French, English and Aboriginal" },
      { en: "French and Dutch" },
      { en: "English and Scottish" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The Parliament Buildings embody the French, English and Aboriginal traditions.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-m-051",
    topicId: "symbols",
    difficulty: "medium",
    prompt: {
      en: "Some provincial legislatures are neoclassical, reflecting the Greco-Roman heritage of Western civilization, in which democracy did what?",
    },
    options: [
      { en: "Originated" },
      { en: "Was banned" },
      { en: "Was reformed" },
      { en: "Was exported" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The legislatures reflect the Greco-Roman heritage of Western civilization in which democracy originated.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-m-052",
    topicId: "symbols",
    difficulty: "medium",
    prompt: {
      en: "Which team is shown in a Discover Canada photograph as the 1978 Stanley Cup Champions?",
    },
    options: [
      { en: "Toronto Maple Leafs" },
      { en: "Edmonton Oilers" },
      { en: "Boston Bruins" },
      { en: "Montreal Canadiens" },
    ],
    answerIndex: 3,
    explanation: {
      en: "A Discover Canada photograph shows the Montreal Canadiens as the 1978 Stanley Cup Champions.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-h-001",
    topicId: "symbols",
    difficulty: "hard",
    prompt: {
      en: "Which statement correctly distinguishes the Union Jack from the 1965 Canadian flag?",
    },
    options: [
      { en: "The Union Jack is the national flag and the 1965 flag is the Royal Flag" },
      { en: "Both are national flags used interchangeably" },
      { en: "The Union Jack is the official Royal Flag while the 1965 flag is the national flag" },
      { en: "Neither has any official status in Canada" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The Union Jack is Canada's official Royal Flag; the red-white-red maple leaf flag raised in 1965 is the national flag.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-h-002",
    topicId: "symbols",
    difficulty: "hard",
    prompt: {
      en: "Since which year has the Canadian Red Ensign been carried officially by veterans?",
    },
    options: [{ en: "1965" }, { en: "2005" }, { en: "1995" }, { en: "2015" }],
    answerIndex: 1,
    explanation: {
      en: "The Canadian Red Ensign has been carried officially by veterans since 2005.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-h-003",
    topicId: "symbols",
    difficulty: "hard",
    prompt: {
      en: "'O Canada' was first sung in 1880 but was only proclaimed the National Anthem a full century later. In which year?",
    },
    options: [{ en: "1980" }, { en: "1970" }, { en: "1990" }, { en: "1960" }],
    answerIndex: 0,
    explanation: {
      en: "'O Canada' was first sung in Québec City in 1880 and proclaimed as the National Anthem in 1980.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-h-004",
    topicId: "symbols",
    difficulty: "hard",
    prompt: { en: "The Royal Anthem may be played or sung on which occasions?" },
    options: [
      { en: "Only when the Sovereign visits Canada" },
      { en: "Only on the Sovereign's birthday" },
      { en: "Only at military ceremonies" },
      { en: "Any occasion when Canadians wish to honour the Sovereign" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The Royal Anthem can be played or sung on any occasion when Canadians wish to honour the Sovereign.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-h-005",
    topicId: "symbols",
    difficulty: "hard",
    prompt: { en: "Which line is repeated as the final two lines of the English 'O Canada'?" },
    options: [
      { en: "The true North strong and free" },
      { en: "O Canada, we stand on guard for thee" },
      { en: "God keep our land glorious and free" },
      { en: "From far and wide, O Canada" },
    ],
    answerIndex: 1,
    explanation: {
      en: "'O Canada, we stand on guard for thee' is sung twice as the final two lines of the anthem.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-h-006",
    topicId: "symbols",
    difficulty: "hard",
    prompt: { en: "In the French anthem, 'Terre de nos aïeux' refers to what?" },
    options: [
      { en: "Land of the brave" },
      { en: "Land of glory" },
      { en: "Land of our hopes" },
      { en: "Land of our ancestors" },
    ],
    answerIndex: 3,
    explanation: {
      en: "'Terre de nos aïeux' means 'land of our ancestors' in the opening line of the French anthem.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-h-007",
    topicId: "symbols",
    difficulty: "hard",
    prompt: { en: "In the French 'O Canada', the singer's arm knows how to wield what?" },
    options: [{ en: "Peace" }, { en: "The seas" }, { en: "The sword" }, { en: "Bridges" }],
    answerIndex: 2,
    explanation: {
      en: "The French anthem sings 'Car ton bras sait porter l'épée' — thy arm knows how to wield the sword.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-h-008",
    topicId: "symbols",
    difficulty: "hard",
    prompt: { en: "Complete the French lyric: 'Car ton bras sait porter l'épée, ...'" },
    options: [
      { en: "Il sait porter la croix" },
      { en: "Il sait porter la couronne" },
      { en: "Il sait porter l'anneau" },
      { en: "Il sait porter le sceptre" },
    ],
    answerIndex: 0,
    explanation: {
      en: "'Il sait porter la croix' (it knows how to bear the cross) follows the line about the sword in the French anthem.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-h-009",
    topicId: "symbols",
    difficulty: "hard",
    prompt: { en: "Complete the French lyric: 'Ton histoire est une épopée...'" },
    options: [
      { en: "des plus brillants exploits" },
      { en: "des plus sombres défaites" },
      { en: "des plus lointains rivages" },
      { en: "des plus grands sacrifices" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The French anthem sings 'Ton histoire est une épopée des plus brillants exploits' (thy history is an epic of the most brilliant exploits).",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-h-010",
    topicId: "symbols",
    difficulty: "hard",
    prompt: { en: "Which line closes the French version of 'O Canada'?" },
    options: [
      { en: "Et ta force, d'espoir armée, gardera nos champs et nos toits" },
      { en: "Et ton courage, éprouvé, défendra nos villes et nos ports" },
      { en: "Et ta gloire, à jamais gravée, chantera nos monts et nos bois" },
      { en: "Et ta valeur, de foi trempée, protégera nos foyers et nos droits" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The French anthem ends with 'Et ta valeur, de foi trempée, protégera nos foyers et nos droits'.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-h-011",
    topicId: "symbols",
    difficulty: "hard",
    prompt: { en: "The second line of the French 'O Canada' is which of the following?" },
    options: [
      { en: "Ton front est ceint de lauriers d'argent" },
      { en: "Ton front est ceint de fleurons glorieux" },
      { en: "Ton front est ceint d'étoiles d'or" },
      { en: "Ton front est ceint de rameaux d'olivier" },
    ],
    answerIndex: 1,
    explanation: {
      en: "'Ton front est ceint de fleurons glorieux' (thy brow is wreathed with glorious fleurons) is the second line of the French anthem.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-h-012",
    topicId: "symbols",
    difficulty: "hard",
    prompt: { en: "Which phrase appears in the French Royal Anthem?" },
    options: [
      { en: "Dieu sauve le Roi" },
      { en: "Vive le Roi!" },
      { en: "Honneur au Roi" },
      { en: "Gloire au Roi" },
    ],
    answerIndex: 1,
    explanation: {
      en: "'Vive le Roi!' (Long live the King!) is the refrain of the French Royal Anthem, 'Dieu protège le Roi'.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-h-013",
    topicId: "symbols",
    difficulty: "hard",
    prompt: { en: "Complete the lyric from the English Royal Anthem: 'Send him victorious, ...'" },
    options: [
      { en: "Make him mighty, strong and glorious" },
      { en: "Keep him valiant, brave and glorious" },
      { en: "Guide him onward, proud and glorious" },
      { en: "Send him victorious, happy and glorious" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The English Royal Anthem sings 'Send him victorious, happy and glorious, long to reign over us'.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-h-014",
    topicId: "symbols",
    difficulty: "hard",
    prompt: {
      en: "Queen Elizabeth II's Diamond Jubilee in 2012 marked how many years as Sovereign?",
    },
    options: [{ en: "60" }, { en: "50" }, { en: "70" }, { en: "25" }],
    answerIndex: 0,
    explanation: { en: "The Diamond Jubilee in 2012 celebrated 60 years as Sovereign." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-h-015",
    topicId: "symbols",
    difficulty: "hard",
    prompt: {
      en: "Canada has been a constitutional monarchy in its own right since Confederation in 1867, during whose reign?",
    },
    options: [
      { en: "King George III" },
      { en: "Queen Anne" },
      { en: "Queen Victoria" },
      { en: "King Edward VII" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Canada has been a constitutional monarchy in its own right since Confederation in 1867 during Queen Victoria's reign.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-h-016",
    topicId: "symbols",
    difficulty: "hard",
    prompt: {
      en: "Who was the first Canadian to be awarded the Victoria Cross, for his role in the Charge of the Light Brigade at Balaclava in 1854?",
    },
    options: [
      { en: "William Hall" },
      { en: "Alexander Roberts Dunn" },
      { en: "Filip Konowal" },
      { en: "Billy Bishop" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Lieutenant Alexander Roberts Dunn, born in present-day Toronto, served in the British Army at Balaclava in the Crimean War and was the first Canadian awarded the Victoria Cross.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-h-017",
    topicId: "symbols",
    difficulty: "hard",
    prompt: {
      en: "William Hall of Horton, Nova Scotia, the first black man awarded the Victoria Cross, was the child of whom?",
    },
    options: [
      { en: "British soldiers" },
      { en: "Irish immigrants" },
      { en: "American slaves" },
      { en: "Loyalist refugees" },
    ],
    answerIndex: 2,
    explanation: {
      en: "William Hall's parents were American slaves; he earned the V.C. for his role in the Siege of Lucknow during the Indian Rebellion of 1857.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-h-018",
    topicId: "symbols",
    difficulty: "hard",
    prompt: {
      en: "Filip Konowal, born in Ukraine, earned the Victoria Cross at the Battle of Hill 70 in 1917 and was notable as what?",
    },
    options: [
      { en: "The youngest Canadian recipient" },
      { en: "The first member of the Canadian Corps not born in the British Empire to receive it" },
      { en: "The only naval recipient" },
      { en: "The first recipient from Quebec" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Konowal became the first member of the Canadian Corps not born in the British Empire to be awarded the V.C.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-h-019",
    topicId: "symbols",
    difficulty: "hard",
    prompt: {
      en: "Paul Triquet of Cabano, Quebec, earned the Victoria Cross leading his men in the attack on Casa Berardi in Italy in 1943 and later became what?",
    },
    options: [
      { en: "A Brigadier" },
      { en: "An Air Marshal" },
      { en: "A Senator" },
      { en: "A Governor General" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Captain Paul Triquet earned the V.C. at Casa Berardi in Italy in 1943 and was later a Brigadier.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-h-020",
    topicId: "symbols",
    difficulty: "hard",
    prompt: {
      en: "Lieutenant Robert Hampton Gray, a navy pilot born in Trail, B.C., earned the Victoria Cross in August 1945 for what action?",
    },
    options: [
      { en: "Leading the Dieppe Raid" },
      { en: "Rescuing prisoners of war" },
      { en: "Defending Hong Kong" },
      { en: "Bombing and sinking a Japanese warship" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Gray was killed while bombing and sinking a Japanese warship in August 1945, a few days before the end of the Second World War.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-h-021",
    topicId: "symbols",
    difficulty: "hard",
    prompt: {
      en: "The Victoria Cross is awarded for the most conspicuous bravery, a daring or pre-eminent act of valour or self-sacrifice, or extreme devotion to duty in the presence of whom?",
    },
    options: [
      { en: "The Sovereign" },
      { en: "The enemy" },
      { en: "One's commanding officer" },
      { en: "Parliament" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The V.C. is awarded for extreme devotion to duty in the presence of the enemy.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-h-022",
    topicId: "symbols",
    difficulty: "hard",
    prompt: {
      en: "The fleur-de-lys became the symbol of French royalty for more than a thousand years, including which colony?",
    },
    options: [
      { en: "New Spain" },
      { en: "New Amsterdam" },
      { en: "New England" },
      { en: "New France" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The fleur-de-lys was the symbol of French royalty for more than a thousand years, including the colony of New France.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-h-023",
    topicId: "symbols",
    difficulty: "hard",
    prompt: { en: "Red and white have been the colours of France and England since when?" },
    options: [
      { en: "The Renaissance" },
      { en: "The Roman era" },
      { en: "The Middle Ages" },
      { en: "The 1800s" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Red and white had been colours of France and England since the Middle Ages.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-h-024",
    topicId: "symbols",
    difficulty: "hard",
    prompt: {
      en: "The Books of Remembrance record the names of those who died serving Canada in wars or while in what circumstance?",
    },
    options: [
      { en: "While on duty" },
      { en: "While in training" },
      { en: "While abroad" },
      { en: "While in uniform" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The Books of Remembrance record those who died serving Canada in wars or while on duty.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-h-025",
    topicId: "symbols",
    difficulty: "hard",
    prompt: { en: "Which pairing of Parliament Buildings events and dates is correct?" },
    options: [
      { en: "Centre Block fire 1916; Peace Tower completed 1927" },
      { en: "Centre Block fire 1922; Peace Tower completed 1916" },
      { en: "Centre Block fire 1927; Peace Tower completed 1916" },
      { en: "Centre Block fire 1916; Peace Tower completed 1922" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The Centre Block was destroyed by an accidental fire in 1916 and rebuilt in 1922, while the Peace Tower was completed in 1927.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-h-026",
    topicId: "symbols",
    difficulty: "hard",
    prompt: {
      en: "According to Discover Canada, what is true about the memorable quotes by Laurier and Diefenbaker?",
    },
    options: [
      { en: "They must be memorized for the citizenship test" },
      { en: "They appear on Canadian currency" },
      { en: "They are read aloud at citizenship ceremonies" },
      { en: "They do not need to be learned for the citizenship test" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Discover Canada explicitly states that these quotes do not need to be learned for the citizenship test.",
    },
    source: src("Memorable Quotes"),
  },
  {
    id: "sym-h-027",
    topicId: "symbols",
    difficulty: "hard",
    prompt: { en: "Who said: 'I am a Canadian, a free Canadian, free to speak without fear...'?" },
    options: [
      { en: "John Diefenbaker" },
      { en: "Sir Wilfrid Laurier" },
      { en: "Sir John A. Macdonald" },
      { en: "Pierre Trudeau" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The quote is by John Diefenbaker, the 13th Prime Minister of Canada (1957–1963).",
    },
    source: src("Memorable Quotes"),
  },
  {
    id: "sym-h-028",
    topicId: "symbols",
    difficulty: "hard",
    prompt: {
      en: "Sir Wilfrid Laurier, quoted in Discover Canada about building a nation 'great among the nations of the world,' was which Prime Minister of Canada?",
    },
    options: [{ en: "The 5th" }, { en: "The 10th" }, { en: "The 7th" }, { en: "The 13th" }],
    answerIndex: 2,
    explanation: { en: "Sir Wilfrid Laurier was the 7th Prime Minister of Canada (1896–1911)." },
    source: src("Memorable Quotes"),
  },
  {
    id: "sym-h-029",
    topicId: "symbols",
    difficulty: "hard",
    prompt: { en: "Which team won gold in men's hockey at the 2010 Winter Olympics in Vancouver?" },
    options: [
      { en: "Team USA" },
      { en: "Team Russia" },
      { en: "Team Sweden" },
      { en: "Team Canada" },
    ],
    answerIndex: 3,
    explanation: {
      en: "A Discover Canada photograph notes that Team Canada won gold in men's hockey at the 2010 Winter Olympics in Vancouver.",
    },
    source: src("Memorable Quotes"),
  },
  {
    id: "sym-h-030",
    topicId: "symbols",
    difficulty: "hard",
    prompt: {
      en: "Jazz pianist Oscar Peterson received the Order of Canada in 1973 from which Governor General?",
    },
    options: [
      { en: "Vincent Massey" },
      { en: "Roland Michener" },
      { en: "Adrienne Clarkson" },
      { en: "Ed Schreyer" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Oscar Peterson received the Order of Canada from Roland Michener, the 20th Governor General, in 1973.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-h-031",
    topicId: "symbols",
    difficulty: "hard",
    prompt: {
      en: "Vincent Massey, whose portrait appears in a Discover Canada photograph, was which Governor General of Canada?",
    },
    options: [{ en: "The 16th" }, { en: "The 20th" }, { en: "The 18th" }, { en: "The 22nd" }],
    answerIndex: 2,
    explanation: {
      en: "Vincent Massey, shown in a portrait in the photograph, was the 18th Governor General.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-h-032",
    topicId: "symbols",
    difficulty: "hard",
    prompt: {
      en: "How does Discover Canada describe the relationship between the French and English words of the National Anthem?",
    },
    options: [
      { en: "The French is a direct translation of the English" },
      { en: "The English is a direct translation of the French" },
      { en: "French and English Canadians sing different words" },
      { en: "Both versions share the same opening line" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Discover Canada states that French and English Canadians sing different words to the National Anthem — they are not translations of each other.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-h-033",
    topicId: "symbols",
    difficulty: "hard",
    prompt: { en: "In which language is Canada's national motto 'A Mari Usque Ad Mare' written?" },
    options: [{ en: "French" }, { en: "English" }, { en: "Latin" }, { en: "Greek" }],
    answerIndex: 2,
    explanation: { en: "The motto 'A Mari Usque Ad Mare' is written in Latin." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-h-034",
    topicId: "symbols",
    difficulty: "hard",
    prompt: { en: "The fleur-de-lys appears on which two flags mentioned in Discover Canada?" },
    options: [
      { en: "The Union Jack and the 1965 flag" },
      { en: "The Canadian Red Ensign and Quebec's 1948 flag" },
      { en: "The 1965 flag and Ontario's flag" },
      { en: "The Red Ensign and the Union Jack" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The fleur-de-lys was included in the Canadian Red Ensign and is the basis of Quebec's 1948 flag.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-h-035",
    topicId: "symbols",
    difficulty: "hard",
    prompt: {
      en: "The Stanley Cup was donated in 1892 and the Clarkson Cup was established in 2005. About how many years apart were they established?",
    },
    options: [
      { en: "About 113 years" },
      { en: "About 83 years" },
      { en: "About 123 years" },
      { en: "About 103 years" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The Stanley Cup was donated in 1892 and the Clarkson Cup established in 2005, about 113 years apart.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-h-036",
    topicId: "symbols",
    difficulty: "hard",
    prompt: { en: "The Snowbirds are officially known as which squadron?" },
    options: [
      { en: "400 Tactical Helicopter Squadron" },
      { en: "409 Tactical Fighter Squadron" },
      { en: "416 Tactical Fighter Squadron" },
      { en: "431 Air Demonstration Squadron" },
    ],
    answerIndex: 3,
    explanation: { en: "The Snowbirds are the 431 Air Demonstration Squadron." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-h-037",
    topicId: "symbols",
    difficulty: "hard",
    prompt: {
      en: "Canada's coat of arms contains symbols of England, France, Scotland and Ireland. What else does it contain?",
    },
    options: [
      { en: "Blue maple leaves" },
      { en: "Red maple leaves" },
      { en: "Golden lions" },
      { en: "A beaver" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The arms contain symbols of England, France, Scotland and Ireland as well as red maple leaves.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-h-038",
    topicId: "symbols",
    difficulty: "hard",
    prompt: {
      en: "Which statement best describes when the Royal Anthem is used versus the National Anthem?",
    },
    options: [
      {
        en: "The Royal Anthem is sung daily in schools; the National Anthem only at citizenship ceremonies",
      },
      { en: "Both are sung together on all official occasions" },
      {
        en: "The Royal Anthem honours the Sovereign; 'O Canada' is the National Anthem of the country",
      },
      { en: "The Royal Anthem replaced 'O Canada' in 1980" },
    ],
    answerIndex: 2,
    explanation: {
      en: "'O Canada' is the National Anthem, while 'God Save the King (or Queen)' is the Royal Anthem played when Canadians wish to honour the Sovereign.",
    },
    source: src("Canadian Symbols"),
  },
];
