/**
 * Question bank chunk — part of questions.generated.ts. DO NOT EDIT BY HAND.
 */
import type { Question } from "../content";
import { src } from "./shared";

export const symbolsA: Question[] = [
  {
    id: "sym-e-001",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "Which of these is described as Canada's best-known symbol?" },
    options: [
      { en: "The beaver" },
      { en: "The fleur-de-lys" },
      { en: "The maple leaf" },
      { en: "The Crown" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Discover Canada states that the maple leaf is Canada's best-known symbol.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-002",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "On which date is Canada Day celebrated?" },
    options: [{ en: "July 4" }, { en: "July 1" }, { en: "June 24" }, { en: "September 1" }],
    answerIndex: 1,
    explanation: { en: "Canada Day is celebrated on July 1 each year." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-003",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "What is the title of Canada's National Anthem?" },
    options: [
      { en: "O Canada" },
      { en: "God Save the King" },
      { en: "The Maple Leaf Forever" },
      { en: "True North" },
    ],
    answerIndex: 0,
    explanation: { en: "Canada's National Anthem is 'O Canada'." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-004",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "In what year was the new Canadian flag raised for the first time?" },
    options: [{ en: "1960" }, { en: "1967" }, { en: "1970" }, { en: "1965" }],
    answerIndex: 3,
    explanation: { en: "A new Canadian flag was raised for the first time in 1965." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-005",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "The beaver, a Canadian symbol, appears on which coin?" },
    options: [
      { en: "One-cent coin" },
      { en: "Five-cent coin" },
      { en: "Ten-cent coin" },
      { en: "Twenty-five-cent coin" },
    ],
    answerIndex: 1,
    explanation: { en: "The industrious beaver can be seen on the five-cent coin." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-006",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "Which sport is considered Canada's national winter sport?" },
    options: [{ en: "Lacrosse" }, { en: "Curling" }, { en: "Soccer" }, { en: "Ice hockey" }],
    answerIndex: 3,
    explanation: { en: "Hockey is considered Canada's national winter sport." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-007",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "Which sport is Canada's official summer sport?" },
    options: [{ en: "Ice hockey" }, { en: "Curling" }, { en: "Lacrosse" }, { en: "Soccer" }],
    answerIndex: 2,
    explanation: { en: "Lacrosse is Canada's official summer sport." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-008",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "Remembrance Day is observed on which date?" },
    options: [
      { en: "November 11" },
      { en: "November 20" },
      { en: "October 11" },
      { en: "December 7" },
    ],
    answerIndex: 0,
    explanation: { en: "Remembrance Day is observed on November 11." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-009",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "What are Canada's national colours?" },
    options: [
      { en: "Red and white" },
      { en: "Blue and white" },
      { en: "Red and gold" },
      { en: "Green and white" },
    ],
    answerIndex: 0,
    explanation: { en: "Red and white are Canada's national colours." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-010",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "The motto 'A Mari Usque Ad Mare' means what in English?" },
    options: [
      { en: "From east to west" },
      { en: "Strength through unity" },
      { en: "Peace, order and good government" },
      { en: "From sea to sea" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The national motto 'A Mari Usque Ad Mare' is Latin for 'from sea to sea'.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-011",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "Which flag is Canada's official Royal Flag?" },
    options: [
      { en: "The Canadian Red Ensign" },
      { en: "The Union Jack" },
      { en: "The Royal Standard of Scotland" },
      { en: "The flag of the Royal Military College" },
    ],
    answerIndex: 1,
    explanation: { en: "The Union Jack is Canada's official Royal Flag." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-012",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "In which year was 'O Canada' proclaimed as the National Anthem?" },
    options: [{ en: "1867" }, { en: "1880" }, { en: "1980" }, { en: "1967" }],
    answerIndex: 2,
    explanation: { en: "'O Canada' was proclaimed as the National Anthem in 1980." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-013",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "Lacrosse was first played by whom?" },
    options: [
      { en: "French settlers" },
      { en: "British soldiers" },
      { en: "Scottish pioneers" },
      { en: "Aboriginals" },
    ],
    answerIndex: 3,
    explanation: { en: "Lacrosse is an ancient sport first played by Aboriginals." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-014",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "Who donated the Stanley Cup?" },
    options: [
      { en: "Lord Stanley" },
      { en: "Adrienne Clarkson" },
      { en: "Queen Victoria" },
      { en: "Sir John A. Macdonald" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The Stanley Cup was donated by Lord Stanley, the Governor General, in 1892.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-015",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "Which sport has the most registered players of any game in Canada?" },
    options: [{ en: "Ice hockey" }, { en: "Lacrosse" }, { en: "Soccer" }, { en: "Curling" }],
    answerIndex: 2,
    explanation: { en: "Soccer has the most registered players of any game in Canada." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-016",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "What is Canada's most popular spectator sport?" },
    options: [{ en: "Canadian football" }, { en: "Hockey" }, { en: "Curling" }, { en: "Soccer" }],
    answerIndex: 1,
    explanation: { en: "Hockey is Canada's most popular spectator sport." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-017",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "What are Canada's two official languages?" },
    options: [
      { en: "English and German" },
      { en: "English and Spanish" },
      { en: "English and French" },
      { en: "English and Italian" },
    ],
    answerIndex: 2,
    explanation: { en: "English and French are Canada's two official languages." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-018",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "What is the highest honour available to Canadians?" },
    options: [
      { en: "The Order of Canada" },
      { en: "The Victoria Cross" },
      { en: "The Clarkson Cup" },
      { en: "The Stanley Cup" },
    ],
    answerIndex: 1,
    explanation: { en: "The Victoria Cross (V.C.) is the highest honour available to Canadians." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-019",
    topicId: "symbols",
    difficulty: "easy",
    prompt: {
      en: "In which year did Canada start its own honours system with the Order of Canada?",
    },
    options: [{ en: "1967" }, { en: "1980" }, { en: "1952" }, { en: "1999" }],
    answerIndex: 0,
    explanation: {
      en: "Canada started its own honours system with the Order of Canada in 1967, the centennial of Confederation.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-020",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "For about how long did the Canadian Red Ensign serve as Canada's flag?" },
    options: [
      { en: "About 25 years" },
      { en: "About 50 years" },
      { en: "About 75 years" },
      { en: "About 100 years" },
    ],
    answerIndex: 3,
    explanation: { en: "The Canadian Red Ensign served as the Canadian flag for about 100 years." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-021",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "Queen Elizabeth II has been Queen of Canada since which year?" },
    options: [{ en: "1947" }, { en: "1952" }, { en: "1965" }, { en: "1977" }],
    answerIndex: 1,
    explanation: { en: "Queen Elizabeth II has been Queen of Canada since 1952." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-022",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "For about how long has the Crown been a symbol of the state in Canada?" },
    options: [
      { en: "About 100 years" },
      { en: "About 200 years" },
      { en: "About 300 years" },
      { en: "About 400 years" },
    ],
    answerIndex: 3,
    explanation: { en: "The Crown has been a symbol of the state in Canada for 400 years." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-023",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "The fleur-de-lys became the symbol of what?" },
    options: [
      { en: "The Hudson's Bay Company" },
      { en: "The Canadian Forces" },
      { en: "French royalty" },
      { en: "The Province of Ontario" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The fleur-de-lys became the symbol of French royalty for more than a thousand years.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-024",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "The Peace Tower was completed in memory of which war?" },
    options: [
      { en: "The First World War" },
      { en: "The Second World War" },
      { en: "The War of 1812" },
      { en: "The Crimean War" },
    ],
    answerIndex: 0,
    explanation: { en: "The Peace Tower was completed in 1927 in memory of the First World War." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-025",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "Maple leaves are carved into the headstones of which people?" },
    options: [
      { en: "Canada's fallen soldiers" },
      { en: "Canada's Governors General" },
      { en: "Famous Canadian artists" },
      { en: "The Fathers of Confederation" },
    ],
    answerIndex: 0,
    explanation: {
      en: "Maple leaves are carved into the headstones of Canada's fallen soldiers buried overseas and in Canada.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-026",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "Canada's coat of arms can be seen on which of the following?" },
    options: [
      { en: "Hockey jerseys" },
      { en: "Passports only" },
      { en: "Postage stamps only" },
      { en: "Dollar bills" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Today the coat of arms can be seen on dollar bills, government documents and public buildings.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-027",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "Ice hockey was developed in Canada during which century?" },
    options: [{ en: "The 1700s" }, { en: "The 1800s" }, { en: "The 1900s" }, { en: "The 1600s" }],
    answerIndex: 1,
    explanation: { en: "Ice hockey was developed in Canada in the 1800s." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-028",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "What is Canada's second most popular sport?" },
    options: [{ en: "Hockey" }, { en: "Curling" }, { en: "Canadian football" }, { en: "Soccer" }],
    answerIndex: 2,
    explanation: { en: "Canadian football is the second most popular sport in Canada." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-029",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "Curling was introduced to Canada by whom?" },
    options: [
      { en: "French settlers" },
      { en: "Irish immigrants" },
      { en: "British soldiers" },
      { en: "Scottish pioneers" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Curling, an ice game introduced by Scottish pioneers, is popular in Canada.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-030",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "What is hockey played on quiet streets commonly called?" },
    options: [
      { en: "Road hockey or street hockey" },
      { en: "Pond hockey" },
      { en: "Ice hockey" },
      { en: "Field hockey" },
    ],
    answerIndex: 0,
    explanation: { en: "Many young Canadians play road hockey or street hockey on quiet streets." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-031",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "The National Hockey League plays for which championship trophy?" },
    options: [
      { en: "The Clarkson Cup" },
      { en: "The Grey Cup" },
      { en: "The Stanley Cup" },
      { en: "The Memorial Cup" },
    ],
    answerIndex: 2,
    explanation: { en: "The National Hockey League plays for the championship Stanley Cup." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-032",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "The Clarkson Cup is awarded for which sport?" },
    options: [
      { en: "Women's hockey" },
      { en: "Men's soccer" },
      { en: "Curling" },
      { en: "Lacrosse" },
    ],
    answerIndex: 0,
    explanation: { en: "The Clarkson Cup is awarded for women's hockey." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-033",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "For generations, Canadian children have collected what?" },
    options: [
      { en: "Baseball cards" },
      { en: "Stamp albums" },
      { en: "Hockey cards" },
      { en: "Comic books" },
    ],
    answerIndex: 2,
    explanation: { en: "Canadian children have collected hockey cards for generations." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-034",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "On which occasions can the Royal Anthem be played or sung?" },
    options: [
      { en: "Only on Canada Day" },
      { en: "Any occasion when Canadians wish to honour the Sovereign" },
      { en: "Only at citizenship ceremonies" },
      { en: "Only on Remembrance Day" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The Royal Anthem can be played or sung on any occasion when Canadians wish to honour the Sovereign.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-035",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "How do the French and English versions of 'O Canada' compare?" },
    options: [
      { en: "They have different words" },
      { en: "They are word-for-word translations" },
      { en: "The French version is much longer" },
      { en: "Only the music is different" },
    ],
    answerIndex: 0,
    explanation: {
      en: "French and English Canadians sing different words to the National Anthem.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-036",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "Which line is from Canada's National Anthem?" },
    options: [
      { en: "Land of the silver birch" },
      { en: "From Atlantic to Pacific" },
      { en: "O beautiful for spacious skies" },
      { en: "The true North strong and free" },
    ],
    answerIndex: 3,
    explanation: { en: "'The true North strong and free!' is a line from 'O Canada'." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-037",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "How does the French version of the anthem begin?" },
    options: [
      { en: "O Canada! Notre patrie" },
      { en: "O Canada! Terre de nos aïeux" },
      { en: "O Canada! Pays bien-aimé" },
      { en: "O Canada! Terre promise" },
    ],
    answerIndex: 1,
    explanation: { en: "The French anthem begins 'O Canada! Terre de nos aïeux'." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-038",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "Victoria Day celebrates whose birthday?" },
    options: [
      { en: "Queen Victoria's" },
      { en: "The Governor General's" },
      { en: "Sir John A. Macdonald's" },
      { en: "The Sovereign's" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Victoria Day is the Sovereign's Birthday, held on the Monday preceding May 25.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-039",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "Thanksgiving Day falls on which day?" },
    options: [
      { en: "The first Monday of October" },
      { en: "The third Monday of October" },
      { en: "The second Monday of October" },
      { en: "The last Sunday of October" },
    ],
    answerIndex: 2,
    explanation: { en: "Thanksgiving Day is the second Monday of October." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-040",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "Christmas Day is celebrated on which date?" },
    options: [
      { en: "December 25" },
      { en: "December 26" },
      { en: "December 24" },
      { en: "January 1" },
    ],
    answerIndex: 0,
    explanation: { en: "Christmas Day is December 25." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-041",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "New Year's Day is on which date?" },
    options: [
      { en: "January 1" },
      { en: "January 11" },
      { en: "December 31" },
      { en: "February 1" },
    ],
    answerIndex: 0,
    explanation: { en: "New Year's Day is January 1." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-042",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "Labour Day is observed on which day?" },
    options: [
      { en: "The first Sunday of September" },
      { en: "The last Friday of August" },
      { en: "The second Monday of September" },
      { en: "The first Monday of September" },
    ],
    answerIndex: 3,
    explanation: { en: "Labour Day is the first Monday of September." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-043",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "In which year did Parliament pass the Official Languages Act?" },
    options: [{ en: "1965" }, { en: "1969" }, { en: "1971" }, { en: "1982" }],
    answerIndex: 1,
    explanation: { en: "Parliament passed the Official Languages Act in 1969." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-044",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "Applicants aged 55 and over are exempted from which citizenship requirement?" },
    options: [
      { en: "The residency requirement" },
      { en: "The knowledge of Canada requirement" },
      { en: "The knowledge of English or French requirement" },
      { en: "The oath of citizenship" },
    ],
    answerIndex: 2,
    explanation: {
      en: "Adult applicants 55 years of age and over are exempted from the English or French language requirement.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-045",
    topicId: "symbols",
    difficulty: "easy",
    prompt: {
      en: "To become a Canadian citizen, an adult applicant must have adequate knowledge of which language?",
    },
    options: [
      { en: "English only" },
      { en: "French only" },
      { en: "The language of their province" },
      { en: "English or French" },
    ],
    answerIndex: 3,
    explanation: {
      en: "You must have adequate knowledge of English or French to become a Canadian citizen.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-046",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "Canada adopted an official coat of arms and national motto after which event?" },
    options: [
      { en: "Confederation" },
      { en: "The First World War" },
      { en: "The Second World War" },
      { en: "The 1967 centennial" },
    ],
    answerIndex: 1,
    explanation: {
      en: "As an expression of national pride after the First World War, Canada adopted an official coat of arms and a national motto.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-047",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "The Parliament Buildings were completed in which decade?" },
    options: [{ en: "The 1860s" }, { en: "The 1830s" }, { en: "The 1850s" }, { en: "The 1900s" }],
    answerIndex: 0,
    explanation: { en: "The Parliament Buildings were completed in the 1860s." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-048",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "Which is the only part of the original Parliament building still remaining?" },
    options: [
      { en: "The Centre Block" },
      { en: "The Peace Tower" },
      { en: "The Library" },
      { en: "The Memorial Chamber" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The Library is the only part of the original Parliament building remaining.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-049",
    topicId: "symbols",
    difficulty: "easy",
    prompt: {
      en: "The Centre Block of Parliament was rebuilt in which year after an accidental fire?",
    },
    options: [{ en: "1918" }, { en: "1920" }, { en: "1922" }, { en: "1927" }],
    answerIndex: 2,
    explanation: {
      en: "The Centre Block was destroyed by an accidental fire in 1916 and rebuilt in 1922.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-050",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "In which year did Quebec adopt its own flag?" },
    options: [{ en: "1945" }, { en: "1948" }, { en: "1952" }, { en: "1960" }],
    answerIndex: 1,
    explanation: {
      en: "In 1948 Quebec adopted its own flag, based on the Cross and the fleur-de-lys.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-051",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "Who adopted maple leaves as a symbol in the 1700s?" },
    options: [
      { en: "French-Canadians" },
      { en: "English settlers" },
      { en: "Scottish pioneers" },
      { en: "Irish immigrants" },
    ],
    answerIndex: 0,
    explanation: { en: "Maple leaves were adopted as a symbol by French-Canadians in the 1700s." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-052",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "The beaver was adopted centuries ago as a symbol of which organization?" },
    options: [
      { en: "The Canadian Pacific Railway" },
      { en: "The Royal Bank of Canada" },
      { en: "The St. Jean Baptiste Society" },
      { en: "The Hudson's Bay Company" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The beaver was adopted centuries ago as a symbol of the Hudson's Bay Company.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-053",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "The St. Jean Baptiste Society is best described as what?" },
    options: [
      { en: "A trade union" },
      { en: "A French-Canadian patriotic association" },
      { en: "A military regiment" },
      { en: "A political party" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The St. Jean Baptiste Society is a French-Canadian patriotic association.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-054",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "Fête Nationale is celebrated in Quebec on which date?" },
    options: [{ en: "July 1" }, { en: "July 24" }, { en: "June 21" }, { en: "June 24" }],
    answerIndex: 3,
    explanation: { en: "Fête Nationale (Quebec) is June 24, the Feast of St. John the Baptist." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-055",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "Boxing Day is observed on which date?" },
    options: [
      { en: "December 24" },
      { en: "December 25" },
      { en: "December 26" },
      { en: "January 2" },
    ],
    answerIndex: 2,
    explanation: { en: "Boxing Day is December 26." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-056",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "Vimy Day is observed on which date?" },
    options: [{ en: "April 9" }, { en: "April 17" }, { en: "May 9" }, { en: "June 6" }],
    answerIndex: 0,
    explanation: { en: "Vimy Day is April 9." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-057",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "Sir Wilfrid Laurier Day is on which date?" },
    options: [
      { en: "November 20" },
      { en: "November 11" },
      { en: "January 11" },
      { en: "February 15" },
    ],
    answerIndex: 0,
    explanation: { en: "Sir Wilfrid Laurier Day is November 20." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-058",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "Sir John A. Macdonald Day is on which date?" },
    options: [{ en: "January 1" }, { en: "February 11" }, { en: "March 11" }, { en: "January 11" }],
    answerIndex: 3,
    explanation: { en: "Sir John A. Macdonald Day is January 11." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-059",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "The Snowbirds are best known as what?" },
    options: [
      { en: "A hockey team" },
      { en: "A Canadian icon" },
      { en: "A naval fleet" },
      { en: "A mountain range" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The Snowbirds (431 Air Demonstration Squadron) are described as a Canadian icon.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-e-060",
    topicId: "symbols",
    difficulty: "easy",
    prompt: { en: "Queen Elizabeth II celebrated her Diamond Jubilee in which year?" },
    options: [{ en: "2002" }, { en: "2007" }, { en: "2012" }, { en: "2017" }],
    answerIndex: 2,
    explanation: {
      en: "Queen Elizabeth II celebrated her Diamond Jubilee, 60 years as Sovereign, in 2012.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-m-001",
    topicId: "symbols",
    difficulty: "medium",
    prompt: {
      en: "The red-white-red pattern of the Canadian flag comes from the flag of which institution?",
    },
    options: [
      { en: "The Royal Canadian Mint" },
      { en: "The Hudson's Bay Company" },
      { en: "The Royal Military College, Kingston" },
      { en: "The Parliament of Canada" },
    ],
    answerIndex: 2,
    explanation: {
      en: "The red-white-red pattern comes from the flag of the Royal Military College, Kingston.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-m-002",
    topicId: "symbols",
    difficulty: "medium",
    prompt: { en: "The Royal Military College in Kingston was founded in which year?" },
    options: [{ en: "1876" }, { en: "1867" }, { en: "1885" }, { en: "1901" }],
    answerIndex: 0,
    explanation: { en: "The Royal Military College, Kingston, was founded in 1876." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-m-003",
    topicId: "symbols",
    difficulty: "medium",
    prompt: { en: "Since which year have red and white been the national colours of Canada?" },
    options: [{ en: "1867" }, { en: "1921" }, { en: "1945" }, { en: "1965" }],
    answerIndex: 1,
    explanation: { en: "Red and white have been the national colours of Canada since 1921." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-m-004",
    topicId: "symbols",
    difficulty: "medium",
    prompt: { en: "Since the 1850s, maple leaves have appeared on what?" },
    options: [
      { en: "Dollar bills" },
      { en: "Ship sails" },
      { en: "Railway cars" },
      { en: "Canadian uniforms and insignia" },
    ],
    answerIndex: 3,
    explanation: {
      en: "Maple leaves have appeared on Canadian uniforms and insignia since the 1850s.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-m-005",
    topicId: "symbols",
    difficulty: "medium",
    prompt: { en: "The fleur-de-lys was adopted by the French king in which year?" },
    options: [{ en: "476" }, { en: "496" }, { en: "800" }, { en: "1066" }],
    answerIndex: 1,
    explanation: {
      en: "It is said the lily flower (fleur-de-lys) was adopted by the French king in the year 496.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-m-006",
    topicId: "symbols",
    difficulty: "medium",
    prompt: {
      en: "The fleur-de-lys was included in the Canadian Red Ensign after being revived at which event?",
    },
    options: [
      { en: "The War of 1812" },
      { en: "Confederation" },
      { en: "The 1967 centennial" },
      { en: "The adoption of the Charter" },
    ],
    answerIndex: 1,
    explanation: {
      en: "Revived at Confederation, the fleur-de-lys was included in the Canadian Red Ensign.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-m-007",
    topicId: "symbols",
    difficulty: "medium",
    prompt: { en: "Quebec's 1948 flag is based on which two symbols?" },
    options: [
      { en: "The maple leaf and the beaver" },
      { en: "The Union Jack and the Crown" },
      { en: "The Cross and the fleur-de-lys" },
      { en: "The star and the wheat sheaf" },
    ],
    answerIndex: 2,
    explanation: {
      en: "In 1948 Quebec adopted its own flag, based on the Cross and the fleur-de-lys.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-m-008",
    topicId: "symbols",
    difficulty: "medium",
    prompt: {
      en: "Canada's coat of arms contains the symbols of England, France, Scotland and Ireland along with what?",
    },
    options: [
      { en: "Red maple leaves" },
      { en: "Blue maple leaves" },
      { en: "Golden wheat" },
      { en: "A polar bear" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The arms contain symbols of England, France, Scotland and Ireland as well as red maple leaves.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-m-009",
    topicId: "symbols",
    difficulty: "medium",
    prompt: { en: "Canada's coat of arms can be seen on government documents and where else?" },
    options: [
      { en: "Dollar bills" },
      { en: "Hockey arenas" },
      { en: "Airports only" },
      { en: "Licence plates" },
    ],
    answerIndex: 0,
    explanation: {
      en: "The arms can be seen on dollar bills, government documents and public buildings.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-m-010",
    topicId: "symbols",
    difficulty: "medium",
    prompt: {
      en: "The Parliament Buildings are built in the Gothic Revival style popular in the time of which monarch?",
    },
    options: [
      { en: "King George III" },
      { en: "Queen Anne" },
      { en: "King Edward VII" },
      { en: "Queen Victoria" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The Parliament Buildings embody the Gothic Revival architecture popular in the time of Queen Victoria.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-m-011",
    topicId: "symbols",
    difficulty: "medium",
    prompt: {
      en: "The Centre Block of Parliament was destroyed by an accidental fire in which year?",
    },
    options: [{ en: "1916" }, { en: "1914" }, { en: "1918" }, { en: "1922" }],
    answerIndex: 0,
    explanation: { en: "The Centre Block was destroyed by an accidental fire in 1916." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-m-012",
    topicId: "symbols",
    difficulty: "medium",
    prompt: { en: "In which year was the Peace Tower completed?" },
    options: [{ en: "1916" }, { en: "1922" }, { en: "1927" }, { en: "1931" }],
    answerIndex: 2,
    explanation: { en: "The Peace Tower was completed in 1927 in memory of the First World War." },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-m-013",
    topicId: "symbols",
    difficulty: "medium",
    prompt: { en: "The Books of Remembrance contain the names of soldiers, sailors and whom?" },
    options: [
      { en: "Nurses" },
      { en: "Firefighters" },
      { en: "Police officers" },
      { en: "Airmen" },
    ],
    answerIndex: 3,
    explanation: {
      en: "The Books of Remembrance record the names of soldiers, sailors and airmen who died serving Canada.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-m-014",
    topicId: "symbols",
    difficulty: "medium",
    prompt: { en: "Where is the Memorial Chamber that holds the Books of Remembrance located?" },
    options: [
      { en: "In the Centre Block" },
      { en: "Within the Peace Tower" },
      { en: "In the Library of Parliament" },
      { en: "In the Senate chamber" },
    ],
    answerIndex: 1,
    explanation: {
      en: "The Memorial Chamber within the Peace Tower contains the Books of Remembrance.",
    },
    source: src("Canadian Symbols"),
  },
  {
    id: "sym-m-015",
    topicId: "symbols",
    difficulty: "medium",
    prompt: { en: "The Quebec National Assembly is built in which architectural style?" },
    options: [
      { en: "Gothic Revival" },
      { en: "Baroque" },
      { en: "French Second Empire" },
      { en: "Neoclassical" },
    ],
    answerIndex: 2,
    explanation: { en: "The Quebec National Assembly is built in the French Second Empire style." },
    source: src("Canadian Symbols"),
  },
];
