// UI strings for 'ar' — chunk of strings.generated.ts. DO NOT EDIT BY HAND.
import type { StringKey } from "../strings.generated";

export const ar: Record<StringKey, string> = {
  "actions.askAi": `اسأل الذكاء الاصطناعي`,
  "actions.mockExam": `امتحان وهمي`,
  "actions.practice": `ممارسة`,
  "actions.quickActions": `Quick actions`,
  "actions.study": `دراسة`,
  "assistant.aiEyebrow": `AI study assistant`,
  "assistant.answerLanguage": `لغة الإجابة`,
  "assistant.charLimit": `{n} characters left`,
  "assistant.checkingMaterial": `Checking the study material…`,
  "assistant.clearChat": `Clear chat`,
  "assistant.copied": `منقول`,
  "assistant.copy": `نسخ`,
  "assistant.description": `Answers are written by AI using only this app's study material, with sources shown. AI can still make mistakes — check important details on the official Government of Canada pages. Not legal or immigration advice.`,
  "assistant.enFrancais": `باللغة الفرنسية`,
  "assistant.error": `حدث خطأ ما. يرجى المحاولة مرة أخرى.`,
  "assistant.fromAppContent": `من محتوى التطبيق المعتمد`,
  "assistant.groundedBadge": `Source-grounded`,
  "assistant.helpful": `مفيد`,
  "assistant.inputPlaceholder": `اطرح سؤالاً حول الجنسية الكندية...`,
  "assistant.myAppLanguage": `My app language`,
  "assistant.notCovered": `Not covered — see official page`,
  "assistant.notHelpful": `غير مفيد`,
  "assistant.openAssistant": `Open study assistant`,
  "assistant.openLink": `Open assistant`,
  "assistant.practiceThis": `ممارسة هذا`,
  "assistant.questionAriaLabel": `Your question`,
  "assistant.reportIncorrect": `Report an incorrect answer`,
  "assistant.send": `Send`,
  "assistant.showSource": `Show source`,
  "assistant.simpleEnglish": `الإنجليزية البسيطة`,
  "assistant.source": `مصدر`,
  "assistant.starter1": `What are the three parts of Parliament?`,
  "assistant.starter2": `Explain the Charter simply`,
  "assistant.starter3": `Who represents the King in Canada?`,
  "assistant.starter4": `What does the knowledge test cover?`,
  "assistant.suggestedQuestions": `الأسئلة المقترحة`,
  "assistant.thinking": `التفكير…`,
  "assistant.title": `مساعد دراسة`,
  "assistant.tryAgain": `Try again`,
  "assistant.tryAsking": `Try asking:`,
  "assistant.vocabularyLabel": `Vocabulary:`,
  "assistant.whyItMatters": `لماذا يهم للاختبار`,
  "auth.account": `Account`,
  "auth.checkEmail": `Check your email to confirm your account, then sign in.`,
  "auth.close": `Close`,
  "auth.codeLabel": `Verification code`,
  "auth.codeResent": `New code sent. Check your email.`,
  "auth.codeSent": `Code sent! Check your email and enter the 6-digit code.`,
  "auth.createAccount": `Create account`,
  "auth.dataDeletedMsg": `Your progress and profile data were deleted.`,
  "auth.deleteConfirm": `Tap again to permanently delete`,
  "auth.deleteData": `Delete my data`,
  "auth.email": `Email`,
  "auth.haveAccount": `Already have an account?`,
  "auth.mfaCodeLabel": `Authenticator code`,
  "auth.mfaDisable": `Disable 2FA`,
  "auth.mfaDisabledMsg": `Two-factor authentication is now OFF.`,
  "auth.mfaEnable": `Enable 2FA`,
  "auth.mfaEnabledMsg": `Two-factor authentication is now ON for your account.`,
  "auth.mfaPendingWarn": `2FA code still needed to finish signing in.`,
  "auth.mfaPrompt": `This account uses 2FA — enter the code from your authenticator app.`,
  "auth.mfaScanHint": `Scan this QR code with your authenticator app (Google Authenticator, Authy, 1Password…), then enter the 6-digit code it shows.`,
  "auth.mfaSetupTitle": `Set up two-factor authentication`,
  "auth.mfaSubtitle": `Enter the 6-digit code from your authenticator app.`,
  "auth.mfaTitle": `Two-factor authentication`,
  "auth.noAccount": `Don't have an account?`,
  "auth.password": `Password`,
  "auth.passwordHint": `At least 6 characters`,
  "auth.privacy": `Privacy`,
  "auth.privacyNote": `Your email and progress are private — only you can see them.`,
  "auth.resendCode": `Resend code`,
  "auth.security": `Security`,
  "auth.signIn": `Sign in`,
  "auth.signOut": `Sign out`,
  "auth.signUp": `Sign up`,
  "auth.subtitle": `Save your progress across devices. Your data stays private.`,
  "auth.title": `Account`,
  "auth.verify": `Verify`,
  "auth.verifyCodeSubtitle": `We sent a 6-digit code to your email. Enter it below to finish signing up.`,
  "auth.verifyCodeTitle": `Enter your code`,
  "auth.working": `Please wait…`,
  "bookmarks.continueStudying": `Continue studying`,
  "bookmarks.empty": `لا توجد إشارات مرجعية حتى الآن. اضغط على النجمة على أي سؤال لحفظه للمراجعة.`,
  "bookmarks.emptyQuestions": `Nothing saved yet. Tap ☆ on a practice question.`,
  "bookmarks.emptySections": `Nothing saved yet. Tap ☆ while reading a section.`,
  "bookmarks.remove": `إزالة`,
  "bookmarks.savedForReview": `تم حفظها للمراجعة`,
  "bookmarks.savedQuestions": `Saved questions ({n})`,
  "bookmarks.savedSections": `Saved sections ({n})`,
  "bookmarks.search": `Search bookmarks…`,
  "bookmarks.title": `الإشارات المرجعية`,
  "cards.answered": `أجاب`,
  "cards.bookmarks": `تم حفظها للمراجعة`,
  "cards.bookmarksLabel": `الإشارات المرجعية`,
  "cards.continueLearning": `مواصلة التعلم`,
  "cards.correct": `صحيح`,
  "cards.dailyGoal": `{done}/{total} أسئلة اليوم`,
  "cards.dailyGoalLabel": `الهدف اليومي`,
  "cards.dailyGoalTitle": `Daily goal`,
  "cards.mockExam.subtitle": `توقيت · 20 سؤالا`,
  "cards.mockExam.title": `امتحان وهمي`,
  "cards.officialInfo.button": `افتح canada.ca`,
  "cards.officialInfo.subtitle": `قم بزيارة canada.ca للحصول على التفاصيل الرسمية`,
  "cards.officialInfo.title": `المعلومات الرسمية`,
  "cards.progress": `التقدم`,
  "cards.progressDetails": `التفاصيل`,
  "cards.recentlyStudied": `درس مؤخرا`,
  "cards.sections": `الأقسام`,
  "cards.studyAssistant.subtitle": `اسأل أي شيء عن المواد الدراسية`,
  "cards.studyAssistant.title": `مساعد دراسة`,
  "cards.todaysRecommendation": `توصية اليوم`,
  "cards.verifiedSource.subtext": `تم فحص المحتوى مقابل المصادر الرسمية. مساعدة دراسية مستقلة - غير تابعة أو معتمدة من قبل حكومة كندا أو IRCC.`,
  "cards.verifiedSource.title": `مصدر تم التحقق منه`,
  "common.back": `العودة`,
  "common.cancel": `إلغاء`,
  "common.close": `إغلاق`,
  "common.continue": `متابعة`,
  "common.done": `تم`,
  "common.emptyBookmarks": `لم يتم حفظ أي شيء حتى الآن`,
  "common.emptyRecentlyStudied": `لم تتم دراسة أي شيء حتى الآن — اختر موضوعًا للبدء.`,
  "common.loading": `جارٍ التحميل…`,
  "common.next": `التالي`,
  "common.of": `من`,
  "common.previous": `السابق`,
  "common.retry": `أعد المحاولة`,
  "common.save": `حفظ`,
  "exam.allTopics": `جميع المواضيع`,
  "exam.answeredCount": `{n} answered`,
  "exam.autosaveNote": `Your answers are saved as you go, so closing the app won't lose your progress.`,
  "exam.cancel": `إلغاء`,
  "exam.confirm": `تأكيد`,
  "exam.confirmEnd": `{n} الأسئلة لم تتم الإجابة عليها وسيتم وضع علامة عليها بأنها غير صحيحة.`,
  "exam.confirmEndTitle": `إنهاء الامتحان؟`,
  "exam.endExamEarly": `إنهاء الامتحان في وقت مبكر`,
  "exam.examDisclaimer": `تعكس هذه النتيجة نماذج أسئلة هذا التطبيق فقط.`,
  "exam.finishExam": `Finish exam`,
  "exam.newExam": `امتحان جديد`,
  "exam.noMistakes": `لا توجد أخطاء — النتيجة المثالية!`,
  "exam.pastAttempts": `Past attempts`,
  "exam.questionAriaLabel": `Question {n}`,
  "exam.questionCount": `عدد الأسئلة`,
  "exam.questionOf": `Question {n} of {total}`,
  "exam.questionPalette": `أسئلة`,
  "exam.questionsOption": `{n} questions`,
  "exam.resultsTitle": `درجاتك`,
  "exam.reviewMistakes": `راجع أخطائك ({n})`,
  "exam.scoreLine": `{correct} of {total} correct`,
  "exam.seeProgress": `See progress`,
  "exam.setupDescription": `This is a practice simulation built from this app's study questions. It is not the official test and does not predict your result.`,
  "exam.setupTitle": `قم بإعداد الامتحان الوهمي الخاص بك`,
  "exam.simulationNote": `Practice simulation · not official`,
  "exam.startExam": `بدء الامتحان`,
  "exam.timeLeft": `الوقت المتبقي`,
  "exam.timedLabel": `توقيت`,
  "exam.timedToggle": `محددة بوقت (90 ثانية لكل سؤال)`,
  "exam.title": `امتحان وهمي`,
  "exam.topicFilter": `الموضوع`,
  "exam.untimedLabel": `غير محدد التوقيت`,
  "footer.disclaimer": `Citizen Prep هي أداة مساعدة دراسية مستقلة. ليست تابعة أو معتمدة من قبل حكومة كندا أو IRCC. لا يمكن أن يضمن نتيجة ناجحة.`,
  "header.appName": `إعدادية المواطن`,
  "header.tagline": `أداة دراسة مستقلة · غير رسمية`,
  "hero.sectionsProgress": `{done} of {total} sections · {percent}% complete`,
  "hero.subtitle": `أداة دراسة مستقلة · الإنجليزية والفرنسية · لا حاجة لحساب`,
  "hero.title": `الاستعداد لاختبار المواطنة الخاصة بك`,
  "nav.exam": `الامتحان`,
  "nav.home": `الصفحة الرئيسية`,
  "nav.practice": `ممارسة`,
  "nav.progress": `التقدم`,
  "nav.topics": `المواضيع`,
  "practice.allLevels": `All levels`,
  "practice.allTopics": `جميع المواضيع`,
  "practice.askAiAbout": `اسأل الذكاء الاصطناعي عن هذا السؤال`,
  "practice.bookmarkQuestion": `سؤال المرجعية`,
  "practice.bookmarked": `إشارة مرجعية`,
  "practice.checkAnswer": `التحقق من الإجابة`,
  "practice.correct": `صحيح`,
  "practice.demoContent": `المحتوى التجريبي`,
  "practice.difficulty": `صعوبة`,
  "practice.easy": `سهل`,
  "practice.explanation": `شرح`,
  "practice.filters": `Filters`,
  "practice.hard": `صعب`,
  "practice.incorrect": `ليس تماما`,
  "practice.medium": `متوسط`,
  "practice.nextQuestion": `السؤال التالي`,
  "practice.questionCounter": `Practice question {n} of {total}`,
  "practice.reportIssue": `الإبلاغ عن مشكلة`,
  "practice.title": `Practice`,
  "practice.topicFilter": `الموضوع`,
  "practice.tryAgain": `حاول مرة أخرى`,
  "progress.accuracy": `الدقة`,
  "progress.clearProgressDesc": `This deletes your answers, completions, bookmarks and exam history from this device. It cannot be undone.`,
  "progress.clearProgressLabel": `Clear all study progress`,
  "progress.confirmClear": `Yes, clear everything`,
  "progress.dailyGoal": `الهدف اليومي`,
  "progress.details": `التفاصيل`,
  "progress.examHistory": `تاريخ الامتحان`,
  "progress.noExams": `لم يتم إجراء أي امتحانات بعد.`,
  "progress.noWrongAnswers": `No incorrect answers to review right now.`,
  "progress.overview": `Overview`,
  "progress.perTopic": `لكل موضوع`,
  "progress.questionsAnswered": `تمت الإجابة على الأسئلة`,
  "progress.reset": `Reset`,
  "progress.retryTopic": `أعد محاولة هذا الموضوع`,
  "progress.sectionsDone": `اكتملت الأقسام`,
  "progress.suggestedNext": `Suggested next: {topic}`,
  "progress.title": `التقدم`,
  "progress.topicCompletion": `Topic completion`,
  "report.detailsPlaceholder": `Tell us more (optional)`,
  "report.incorrectAnswer": `Incorrect answer`,
  "report.outdatedInfo": `Outdated information`,
  "report.submit": `Submit report`,
  "report.technicalIssue": `Technical issue`,
  "report.thanks": `Thanks — reports are stored locally on this device.`,
  "report.translationProblem": `Translation problem`,
  "report.unclearExplanation": `Explication peu claire`,
  "settings.about": `About this app`,
  "settings.appInterfaceLanguage": `لغة واجهة التطبيق`,
  "settings.clearProgress": `تقدم واضح`,
  "settings.clearProgressConfirm": `هل أنت متأكد؟ سيؤدي هذا إلى حذف كل تقدمك.`,
  "settings.interfaceDescription": `Menus, buttons and navigation.`,
  "settings.language": `اللغة`,
  "settings.machineNote": `Machine-translated content has not been checked by a human reviewer. Nothing here is labelled as reviewed unless it has actually been reviewed.`,
  "settings.machineTranslatedBadge": `مترجم آليًا`,
  "settings.manageProgress": `Manage your progress data`,
  "settings.notAvailable": `غير متوفر بعد`,
  "settings.officialGuideLink": `Official study guide`,
  "settings.officialTestLink": `Official citizenship test information`,
  "settings.privacy": `Privacy`,
  "settings.privacyText": `Your answers, bookmarks and settings are stored only on this device. No account is needed. Questions you ask the study assistant are sent to an AI service to generate answers.`,
  "settings.reviewedBadge": `تمت المراجعة`,
  "settings.studyContentLanguage": `دراسة لغة المحتوى`,
  "settings.studyDescription": `Learning text and explanations. You can read in one language while navigating in another.`,
  "settings.textSize": `حجم النص`,
  "settings.title": `الإعدادات`,
  "topics.askAssistant": `اسأل المساعد عن هذا القسم`,
  "topics.bookmarkSection": `Bookmark section`,
  "topics.bookmarkedSection": `Bookmarked`,
  "topics.completed": `مكتمل`,
  "topics.continueLearningCard": `مواصلة التعلم`,
  "topics.demoSourceNote": `Original sample question — not an official exam question`,
  "topics.lastVerified": `Last verified {date}`,
  "topics.markComplete": `وضع علامة كمكتملة`,
  "topics.markIncomplete": `وضع علامة على أنها غير مكتملة`,
  "topics.minRead": `{n} min read`,
  "topics.next": `التالي`,
  "topics.openOfficialPage": `فتح الصفحة الرسمية`,
  "topics.paraphrasedSourceNote": `Paraphrased from official material`,
  "topics.practiceTopic": `Practise this topic`,
  "topics.previous": `السابق`,
  "topics.reportIssue": `الإبلاغ عن مشكلة`,
  "topics.reviewedOn": `reviewed {date}`,
  "topics.reviewedTranslation": `ترجمة تمت مراجعتها`,
  "topics.section": `القسم`,
  "topics.sections": `أقسام`,
  "topics.source": `مصدر`,
  "topics.sourcesDescription": `Study text here is paraphrased from the Government of Canada citizenship study guide and reviewed on the dates shown. Practice questions are researched from the official study guide.`,
  "topics.sourcesHeading": `Content sources and review dates`,
  "topics.studyLanguageLabel": `Study content language`,
  "topics.title": `موضوعات الدراسة`,
  "topics.vocabulary": `المفردات`,
};
