// UI strings for 'bg' — chunk of strings.generated.ts. DO NOT EDIT BY HAND.
import type { StringKey } from "../strings.generated";

export const bg: Record<StringKey, string> = {
  "actions.askAi": `Попитайте AI`,
  "actions.mockExam": `Пробен изпит`,
  "actions.practice": `Практикувайте`,
  "actions.quickActions": `Quick actions`,
  "actions.study": `Проучване`,
  "assistant.aiEyebrow": `Помощник по изучаване на AI`,
  "assistant.answerLanguage": `Език за отговор`,
  "assistant.charLimit": `Остават {n} знака`,
  "assistant.checkingMaterial": `Проверка на учебния материал...`,
  "assistant.clearChat": `Изчистване на чата`,
  "assistant.copied": `Копирано`,
  "assistant.copy": `копие`,
  "assistant.description": `Отговорите са написани от AI, използвайки само учебния материал на това приложение, с показани източници. AI все още може да прави грешки - проверете важни подробности на официалните страници на правителството на Канада. Не правни или имиграционни съвети.`,
  "assistant.enFrancais": `En français`,
  "assistant.error": `Нещо се обърка. Моля, опитайте отново.`,
  "assistant.fromAppContent": `От одобрено съдържание на приложението`,
  "assistant.groundedBadge": `Основан на източника`,
  "assistant.helpful": `полезно`,
  "assistant.inputPlaceholder": `Задайте въпрос относно канадското гражданство...`,
  "assistant.myAppLanguage": `Моят език на приложението`,
  "assistant.notCovered": `Не се покрива — вижте официалната страница`,
  "assistant.notHelpful": `Не е полезно`,
  "assistant.openAssistant": `Отворен асистент за обучение`,
  "assistant.openLink": `Отворете асистент`,
  "assistant.practiceThis": `Практикувайте това`,
  "assistant.questionAriaLabel": `Your question`,
  "assistant.reportIncorrect": `Докладвайте за неправилен отговор`,
  "assistant.send": `Изпратете`,
  "assistant.showSource": `Показване на източника`,
  "assistant.simpleEnglish": `Прост английски`,
  "assistant.source": `Източник`,
  "assistant.starter1": `Кои са трите части на парламента?`,
  "assistant.starter2": `Обяснете Хартата просто`,
  "assistant.starter3": `Кой представлява краля в Канада?`,
  "assistant.starter4": `Какво обхваща проверката на знанията?`,
  "assistant.suggestedQuestions": `Предложени въпроси`,
  "assistant.thinking": `мислене...`,
  "assistant.title": `Учебен асистент`,
  "assistant.tryAgain": `Опитайте отново`,
  "assistant.tryAsking": `Опитайте да попитате:`,
  "assistant.vocabularyLabel": `Речник:`,
  "assistant.whyItMatters": `Защо има значение за теста`,
  "auth.account": `Account`,
  "auth.checkEmail": `Check your email to confirm your account, then sign in.`,
  "auth.close": `Close`,
  "auth.codeLabel": `Verification code`,
  "auth.codeResent": `New code sent. Check your email.`,
  "auth.codeSent": `Code sent! Check your email and enter the 6-digit code.`,
  "auth.createAccount": `Create account`,
  "auth.dataDeletedMsg": `Your progress and profile data were deleted.`,
  "auth.deleteConfirm": `Tap again to permanently delete`,
  "auth.deleteData": `Delete my data`,
  "auth.email": `Email`,
  "auth.haveAccount": `Already have an account?`,
  "auth.mfaCodeLabel": `Authenticator code`,
  "auth.mfaDisable": `Disable 2FA`,
  "auth.mfaDisabledMsg": `Two-factor authentication is now OFF.`,
  "auth.mfaEnable": `Enable 2FA`,
  "auth.mfaEnabledMsg": `Two-factor authentication is now ON for your account.`,
  "auth.mfaPendingWarn": `2FA code still needed to finish signing in.`,
  "auth.mfaPrompt": `This account uses 2FA — enter the code from your authenticator app.`,
  "auth.mfaScanHint": `Scan this QR code with your authenticator app (Google Authenticator, Authy, 1Password…), then enter the 6-digit code it shows.`,
  "auth.mfaSetupTitle": `Set up two-factor authentication`,
  "auth.mfaSubtitle": `Enter the 6-digit code from your authenticator app.`,
  "auth.mfaTitle": `Two-factor authentication`,
  "auth.noAccount": `Don't have an account?`,
  "auth.password": `Password`,
  "auth.passwordHint": `At least 6 characters`,
  "auth.privacy": `Privacy`,
  "auth.privacyNote": `Your email and progress are private — only you can see them.`,
  "auth.resendCode": `Resend code`,
  "auth.security": `Security`,
  "auth.signIn": `Sign in`,
  "auth.signOut": `Sign out`,
  "auth.signUp": `Sign up`,
  "auth.subtitle": `Save your progress across devices. Your data stays private.`,
  "auth.title": `Account`,
  "auth.verify": `Verify`,
  "auth.verifyCodeSubtitle": `We sent a 6-digit code to your email. Enter it below to finish signing up.`,
  "auth.verifyCodeTitle": `Enter your code`,
  "auth.working": `Please wait…`,
  "bookmarks.continueStudying": `Продължавайте да учите`,
  "bookmarks.empty": `Все още няма отметки. Докоснете звездата върху всеки въпрос, за да го запазите за преглед.`,
  "bookmarks.emptyQuestions": `Все още нищо не е запазено. Докоснете ☆ върху практически въпрос.`,
  "bookmarks.emptySections": `Все още нищо не е запазено. Докоснете ☆, докато четете раздел.`,
  "bookmarks.remove": `Премахнете`,
  "bookmarks.savedForReview": `запазени за преглед`,
  "bookmarks.savedQuestions": `Запазени въпроси ({n})`,
  "bookmarks.savedSections": `Запазени секции ({n})`,
  "bookmarks.search": `Търсене в отметки...`,
  "bookmarks.title": `Отметки`,
  "cards.answered": `Отговорено`,
  "cards.bookmarks": `запазени за преглед`,
  "cards.bookmarksLabel": `Отметки`,
  "cards.continueLearning": `Продължете да учите`,
  "cards.correct": `Правилно`,
  "cards.dailyGoal": `{done}/{total} въпроса днес`,
  "cards.dailyGoalLabel": `Дневна цел`,
  "cards.dailyGoalTitle": `Daily goal`,
  "cards.mockExam.subtitle": `Време · 20 въпроса`,
  "cards.mockExam.title": `Пробен изпит`,
  "cards.officialInfo.button": `Отворете canada.ca`,
  "cards.officialInfo.subtitle": `Посетете canada.ca за официални подробности`,
  "cards.officialInfo.title": `Официална информация`,
  "cards.progress": `Напредък`,
  "cards.progressDetails": `Подробности`,
  "cards.recentlyStudied": `Наскоро проучен`,
  "cards.sections": `Раздели`,
  "cards.studyAssistant.subtitle": `Попитайте нещо относно учебния материал`,
  "cards.studyAssistant.title": `Учебен асистент`,
  "cards.todaysRecommendation": `Днешната препоръка`,
  "cards.verifiedSource.subtext": `Съдържанието е проверено спрямо официални източници. Независима учебна помощ — не е свързана с или одобрена от правителството на Канада или IRCC.`,
  "cards.verifiedSource.title": `Проверен източник`,
  "common.back": `Назад`,
  "common.cancel": `Отказ`,
  "common.close": `затвори`,
  "common.continue": `Продължи`,
  "common.done": `Готово`,
  "common.emptyBookmarks": `Все още нищо не е запазено`,
  "common.emptyRecentlyStudied": `Все още няма нищо проучено — изберете тема, за да започнете.`,
  "common.loading": `Зарежда се...`,
  "common.next": `Следваща`,
  "common.of": `на`,
  "common.previous": `Предишен`,
  "common.retry": `Опитайте отново`,
  "common.save": `Запазване`,
  "exam.allTopics": `Всички теми`,
  "exam.answeredCount": `{n} answered`,
  "exam.autosaveNote": `Вашите отговори се запазват, докато вървите, така че затварянето на приложението няма да загуби напредъка ви.`,
  "exam.cancel": `Отказ`,
  "exam.confirm": `Потвърдете`,
  "exam.confirmEnd": `{n} въпроса са без отговор и ще бъдат маркирани като неправилни.`,
  "exam.confirmEndTitle": `Край на изпита?`,
  "exam.endExamEarly": `Край на изпита по-рано`,
  "exam.examDisclaimer": `Този резултат отразява само примерните въпроси на това приложение.`,
  "exam.finishExam": `Завършете изпита`,
  "exam.newExam": `Нов изпит`,
  "exam.noMistakes": `Без грешки — перфектен резултат!`,
  "exam.pastAttempts": `Минали опити`,
  "exam.questionAriaLabel": `Въпрос {n}`,
  "exam.questionCount": `Брой въпроси`,
  "exam.questionOf": `Въпрос {n} от {total}`,
  "exam.questionPalette": `Въпроси`,
  "exam.questionsOption": `{n} questions`,
  "exam.resultsTitle": `Вашият резултат`,
  "exam.reviewMistakes": `Прегледайте грешките си ({n})`,
  "exam.scoreLine": `{correct} от {total} правилни`,
  "exam.seeProgress": `Вижте напредъка`,
  "exam.setupDescription": `Това е практическа симулация, изградена от учебните въпроси на това приложение. Това не е официалният тест и не предсказва вашия резултат.`,
  "exam.setupTitle": `Настройте пробния си изпит`,
  "exam.simulationNote": `Симулация на практика · не е официално`,
  "exam.startExam": `Започнете изпит`,
  "exam.timeLeft": `Остава време`,
  "exam.timedLabel": `време`,
  "exam.timedToggle": `Време (90 секунди на въпрос)`,
  "exam.title": `Пробен изпит`,
  "exam.topicFilter": `Тема`,
  "exam.untimedLabel": `ненасрочен`,
  "footer.disclaimer": `Citizen Prep е независимо учебно помагало. Не е свързан с или одобрен от правителството на Канада или IRCC. Не може да гарантира преминаващ резултат.`,
  "header.appName": `Гражданска подготовка`,
  "header.tagline": `Инструмент за независимо проучване · Не е официално`,
  "hero.sectionsProgress": `{done} of {total} sections · {percent}% complete`,
  "hero.subtitle": `Инструмент за независимо обучение · английски и френски · не е необходим акаунт`,
  "hero.title": `Подгответе се за вашия тест за гражданство`,
  "nav.exam": `Изпит`,
  "nav.home": `Начало`,
  "nav.practice": `Практикувайте`,
  "nav.progress": `Напредък`,
  "nav.topics": `Теми`,
  "practice.allLevels": `Всички нива`,
  "practice.allTopics": `Всички теми`,
  "practice.askAiAbout": `Попитайте AI за този въпрос`,
  "practice.bookmarkQuestion": `Въпрос за отметка`,
  "practice.bookmarked": `Маркиран`,
  "practice.checkAnswer": `Проверете отговора`,
  "practice.correct": `Правилно`,
  "practice.demoContent": `Демо съдържание`,
  "practice.difficulty": `Трудност`,
  "practice.easy": `лесно`,
  "practice.explanation": `Обяснение`,
  "practice.filters": `Филтри`,
  "practice.hard": `трудно`,
  "practice.incorrect": `Не съвсем`,
  "practice.medium": `Среден`,
  "practice.nextQuestion": `Следващ въпрос`,
  "practice.questionCounter": `Практически въпрос {n} от {total}`,
  "practice.reportIssue": `Докладвайте за проблем`,
  "practice.title": `Практикувайте`,
  "practice.topicFilter": `Тема`,
  "practice.tryAgain": `Опитайте отново`,
  "progress.accuracy": `точност`,
  "progress.clearProgressDesc": `Това изтрива вашите отговори, завършвания, отметки и история на изпитите от това устройство. Не може да се отмени.`,
  "progress.clearProgressLabel": `Изчистете целия напредък на проучването`,
  "progress.confirmClear": `Yes, clear everything`,
  "progress.dailyGoal": `Дневна цел`,
  "progress.details": `Подробности`,
  "progress.examHistory": `История на изпитите`,
  "progress.noExams": `Все още няма взети изпити.`,
  "progress.noWrongAnswers": `Няма неправилни отговори за преглед в момента.`,
  "progress.overview": `Преглед`,
  "progress.perTopic": `По тема`,
  "progress.questionsAnswered": `Отговорени въпроси`,
  "progress.reset": `Нулиране`,
  "progress.retryTopic": `Опитайте отново тази тема`,
  "progress.sectionsDone": `Завършени секции`,
  "progress.suggestedNext": `Предложено следващо: {topic}`,
  "progress.title": `Напредък`,
  "progress.topicCompletion": `Завършване на темата`,
  "report.detailsPlaceholder": `Разкажете ни повече (по избор)`,
  "report.incorrectAnswer": `Неправилен отговор`,
  "report.outdatedInfo": `Остаряла информация`,
  "report.submit": `Изпратете отчет`,
  "report.technicalIssue": `Технически проблем`,
  "report.thanks": `Благодаря — отчетите се съхраняват локално на това устройство.`,
  "report.translationProblem": `Проблем с превода`,
  "report.unclearExplanation": `Обяснение peu claire`,
  "settings.about": `Относно това приложение`,
  "settings.appInterfaceLanguage": `Език на интерфейса на приложението`,
  "settings.clearProgress": `Ясен напредък`,
  "settings.clearProgressConfirm": `сигурен ли си Това ще изтрие целия ви напредък.`,
  "settings.interfaceDescription": `Менюта, бутони и навигация.`,
  "settings.language": `език`,
  "settings.machineNote": `Машинно преведеното съдържание не е проверено от рецензент. Нищо тук не е обозначено като прегледано, освен ако действително не е прегледано.`,
  "settings.machineTranslatedBadge": `Машинен превод`,
  "settings.manageProgress": `Управлявайте данните за напредъка си`,
  "settings.notAvailable": `Все още не е наличен`,
  "settings.officialGuideLink": `Официално учебно ръководство`,
  "settings.officialTestLink": `Информация за официалния тест за гражданство`,
  "settings.privacy": `Поверителност`,
  "settings.privacyText": `Вашите отговори, отметки и настройки се съхраняват само на това устройство. No account is needed. Въпросите, които задавате на асистента по обучението, се изпращат до услуга за изкуствен интелект, за да генерира отговори.`,
  "settings.reviewedBadge": `Прегледано`,
  "settings.studyContentLanguage": `Език на учебното съдържание`,
  "settings.studyDescription": `Учебен текст и обяснения. Можете да четете на един език, докато навигирате на друг.`,
  "settings.textSize": `Размер на текста`,
  "settings.title": `Настройки`,
  "topics.askAssistant": `Попитайте асистента за този раздел`,
  "topics.bookmarkSection": `Секция за отметки`,
  "topics.bookmarkedSection": `Маркиран`,
  "topics.completed": `Завършено`,
  "topics.continueLearningCard": `Продължете да учите`,
  "topics.demoSourceNote": `Оригинален примерен въпрос — не е официален изпитен въпрос`,
  "topics.lastVerified": `Последна проверка {date}`,
  "topics.markComplete": `Маркирайте като завършен`,
  "topics.markIncomplete": `Отбелязване като незавършено`,
  "topics.minRead": `{n} мин. прочетено`,
  "topics.next": `Следваща`,
  "topics.openOfficialPage": `Отворете официалната страница`,
  "topics.paraphrasedSourceNote": `Перифразирано от официални материали`,
  "topics.practiceTopic": `Практикувайте тази тема`,
  "topics.previous": `Предишен`,
  "topics.reportIssue": `Докладвайте за проблем`,
  "topics.reviewedOn": `reviewed {date}`,
  "topics.reviewedTranslation": `Прегледан превод`,
  "topics.section": `Раздел`,
  "topics.sections": `секции`,
  "topics.source": `Източник`,
  "topics.sourcesDescription": `Текстът за обучение тук е перифразиран от учебното ръководство за гражданство на правителството на Канада и е прегледан на посочените дати. Практическите въпроси се изследват от официалното учебно ръководство.`,
  "topics.sourcesHeading": `Източници на съдържание и дати на преглед`,
  "topics.studyLanguageLabel": `Език на учебното съдържание`,
  "topics.title": `Учебни теми`,
  "topics.vocabulary": `Речник`,
};
