// UI strings for 'bs' — chunk of strings.generated.ts. DO NOT EDIT BY HAND.
import type { StringKey } from "../strings.generated";

export const bs: Record<StringKey, string> = {
  "actions.askAi": `Pitajte AI`,
  "actions.mockExam": `Mock ispit`,
  "actions.practice": `Vježbajte`,
  "actions.quickActions": `Quick actions`,
  "actions.study": `Studija`,
  "assistant.aiEyebrow": `Asistent za učenje AI`,
  "assistant.answerLanguage": `Jezik odgovora`,
  "assistant.charLimit": `Preostalo znakova: {n}`,
  "assistant.checkingMaterial": `Provjera materijala za učenje…`,
  "assistant.clearChat": `Obriši chat`,
  "assistant.copied": `Kopirano`,
  "assistant.copy": `Kopiraj`,
  "assistant.description": `Odgovore piše AI koristeći samo materijal za učenje ove aplikacije, s prikazanim izvorima. AI još uvijek može pogriješiti - provjerite važne detalje na službenim stranicama Vlade Kanade. Nije pravni savjet ili savjet za imigraciju.`,
  "assistant.enFrancais": `En français`,
  "assistant.error": `Nešto je pošlo po zlu. Molimo pokušajte ponovo.`,
  "assistant.fromAppContent": `Iz odobrenog sadržaja aplikacije`,
  "assistant.groundedBadge": `Izvorno utemeljeno`,
  "assistant.helpful": `Korisno`,
  "assistant.inputPlaceholder": `Postavite pitanje o kanadskom državljanstvu…`,
  "assistant.myAppLanguage": `Moj jezik aplikacije`,
  "assistant.notCovered": `Nije pokriveno — pogledajte zvaničnu stranicu`,
  "assistant.notHelpful": `Nije korisno`,
  "assistant.openAssistant": `Otvoreni studijski asistent`,
  "assistant.openLink": `Otvoreni asistent`,
  "assistant.practiceThis": `Vežbaj ovo`,
  "assistant.questionAriaLabel": `Vaše pitanje`,
  "assistant.reportIncorrect": `Prijavite netačan odgovor`,
  "assistant.send": `Pošalji`,
  "assistant.showSource": `Prikaži izvor`,
  "assistant.simpleEnglish": `Simple English`,
  "assistant.source": `Izvor`,
  "assistant.starter1": `Koja su tri dijela parlamenta?`,
  "assistant.starter2": `Jednostavno objasnite Povelju`,
  "assistant.starter3": `Who represents the King in Canada?`,
  "assistant.starter4": `What does the knowledge test cover?`,
  "assistant.suggestedQuestions": `Predložena pitanja`,
  "assistant.thinking": `Razmišljajući…`,
  "assistant.title": `Studijski asistent`,
  "assistant.tryAgain": `Pokušajte ponovo`,
  "assistant.tryAsking": `Pokušajte pitati:`,
  "assistant.vocabularyLabel": `vokabular:`,
  "assistant.whyItMatters": `Zašto je to važno za test`,
  "bookmarks.continueStudying": `Nastavite sa učenjem`,
  "bookmarks.empty": `Još nema oznaka. Dodirnite zvjezdicu na bilo kojem pitanju da ga sačuvate za pregled.`,
  "bookmarks.emptyQuestions": `Još ništa nije sačuvano. Dodirnite ☆ na pitanje za vježbu.`,
  "bookmarks.emptySections": `Još ništa nije sačuvano. Dodirnite ☆ dok čitate dio.`,
  "bookmarks.remove": `Ukloni`,
  "bookmarks.savedForReview": `sačuvano za pregled`,
  "bookmarks.savedQuestions": `Sačuvana pitanja ({n})`,
  "bookmarks.savedSections": `Sačuvani odjeljci ({n})`,
  "bookmarks.search": `Pretraži oznake…`,
  "bookmarks.title": `Bookmarks`,
  "cards.answered": `Odgovoreno`,
  "cards.bookmarks": `sačuvano za pregled`,
  "cards.bookmarksLabel": `Bookmarks`,
  "cards.continueLearning": `Nastavite sa učenjem`,
  "cards.correct": `Tačno`,
  "cards.dailyGoal": `{done}/{total} pitanja danas`,
  "cards.dailyGoalLabel": `Dnevni cilj`,
  "cards.dailyGoalTitle": `Daily goal`,
  "cards.mockExam.subtitle": `Vremenski · 20 pitanja`,
  "cards.mockExam.title": `Mock ispit`,
  "cards.officialInfo.button": `Otvorite canada.ca`,
  "cards.officialInfo.subtitle": `Posjetite canada.ca za zvanične detalje`,
  "cards.officialInfo.title": `Zvanične informacije`,
  "cards.progress": `Napredak`,
  "cards.progressDetails": `Detalji`,
  "cards.recentlyStudied": `Nedavno studirao`,
  "cards.sections": `Sekcije`,
  "cards.studyAssistant.subtitle": `Pitajte bilo šta o materijalu za učenje`,
  "cards.studyAssistant.title": `Studijski asistent`,
  "cards.todaysRecommendation": `Današnja preporuka`,
  "cards.verifiedSource.subtext": `Sadržaj provjeren u odnosu na službene izvore. Nezavisna pomoć za studiranje — nije povezana sa vladom Kanade ili IRCC-om niti je odobrena od strane Vlade Kanade.`,
  "cards.verifiedSource.title": `Provjereni izvor`,
  "common.back": `Nazad`,
  "common.cancel": `Otkaži`,
  "common.close": `Zatvori`,
  "common.continue": `Nastavi`,
  "common.done": `Gotovo`,
  "common.emptyBookmarks": `Još ništa nije sačuvano`,
  "common.emptyRecentlyStudied": `Još ništa nije proučeno - odaberite temu za početak.`,
  "common.loading": `Učitavanje…`,
  "common.next": `Sledeći`,
  "common.of": `of`,
  "common.previous": `Prethodno`,
  "common.retry": `Pokušajte ponovo`,
  "common.save": `Sačuvaj`,
  "exam.allTopics": `Sve teme`,
  "exam.answeredCount": `{n} je odgovorio`,
  "exam.autosaveNote": `Vaši odgovori se pohranjuju dok idete, tako da zatvaranjem aplikacije nećete izgubiti napredak.`,
  "exam.cancel": `Otkaži`,
  "exam.confirm": `Potvrdi`,
  "exam.confirmEnd": `{n} pitanja su bez odgovora i bit će označena kao netačna.`,
  "exam.confirmEndTitle": `Završiti ispit?`,
  "exam.endExamEarly": `Završi ispit ranije`,
  "exam.examDisclaimer": `Ovaj rezultat odražava samo uzorke pitanja ove aplikacije.`,
  "exam.finishExam": `Završi ispit`,
  "exam.newExam": `Novi ispit`,
  "exam.noMistakes": `Bez grešaka — savršen rezultat!`,
  "exam.pastAttempts": `Prošli pokušaji`,
  "exam.questionAriaLabel": `Pitanje {n}`,
  "exam.questionCount": `Broj pitanja`,
  "exam.questionOf": `Pitanje {n} od {total}`,
  "exam.questionPalette": `Pitanja`,
  "exam.questionsOption": `{n} pitanja`,
  "exam.resultsTitle": `Tvoj rezultat`,
  "exam.reviewMistakes": `Pregledajte svoje greške ({n})`,
  "exam.scoreLine": `{correct} of {total} correct`,
  "exam.seeProgress": `Pogledajte napredak`,
  "exam.setupDescription": `Ovo je praktična simulacija napravljena od studijskih pitanja ove aplikacije. To nije službeni test i ne predviđa vaš rezultat.`,
  "exam.setupTitle": `Postavite svoj probni ispit`,
  "exam.simulationNote": `Vježbajte simulaciju · nije zvanično`,
  "exam.startExam": `Počni ispit`,
  "exam.timeLeft": `Ostalo je vrijeme`,
  "exam.timedLabel": `vremenski`,
  "exam.timedToggle": `Tempirano (90 sekundi po pitanju)`,
  "exam.title": `Mock ispit`,
  "exam.topicFilter": `Tema`,
  "exam.untimedLabel": `untimed`,
  "footer.disclaimer": `Citizen Prep je nezavisno pomagalo za učenje. Nije povezan ili odobren od strane Vlade Kanade ili IRCC-a. Ne može garantovati prolazan rezultat.`,
  "header.appName": `Citizen Prep`,
  "header.tagline": `Nezavisno sredstvo za proučavanje · Nije zvanično`,
  "hero.sectionsProgress": `{done} of {total} sections · {percent}% complete`,
  "hero.subtitle": `Alat za nezavisno učenje · engleski i francuski · nije potreban račun`,
  "hero.title": `Pripremite se za test državljanstva`,
  "nav.exam": `Ispit`,
  "nav.home": `Dom`,
  "nav.practice": `Vježbajte`,
  "nav.progress": `Napredak`,
  "nav.topics": `Teme`,
  "practice.allLevels": `Svi nivoi`,
  "practice.allTopics": `Sve teme`,
  "practice.askAiAbout": `Pitajte AI o ovom pitanju`,
  "practice.bookmarkQuestion": `Označite pitanje`,
  "practice.bookmarked": `Bookmarked`,
  "practice.checkAnswer": `Provjerite odgovor`,
  "practice.correct": `Tačno`,
  "practice.demoContent": `Demo sadržaj`,
  "practice.difficulty": `Poteškoće`,
  "practice.easy": `Lako`,
  "practice.explanation": `Objašnjenje`,
  "practice.filters": `Filteri`,
  "practice.hard": `Teško`,
  "practice.incorrect": `Ne baš`,
  "practice.medium": `Srednje`,
  "practice.nextQuestion": `Sljedeće pitanje`,
  "practice.questionCounter": `Vježbajte pitanje {n} od {total}`,
  "practice.reportIssue": `Prijavite problem`,
  "practice.title": `Vježbajte`,
  "practice.topicFilter": `Tema`,
  "practice.tryAgain": `Pokušajte ponovo`,
  "progress.accuracy": `Preciznost`,
  "progress.clearProgressDesc": `Ovo briše vaše odgovore, popunjene zadatke, oznake i historiju ispita sa ovog uređaja. Ne može se poništiti.`,
  "progress.clearProgressLabel": `Obrišite sav napredak učenja`,
  "progress.confirmClear": `Da, očisti sve`,
  "progress.dailyGoal": `Dnevni cilj`,
  "progress.details": `Detalji`,
  "progress.examHistory": `Istorija ispita`,
  "progress.noExams": `Još nema položenih ispita.`,
  "progress.noWrongAnswers": `Trenutno nema netačnih odgovora za pregled.`,
  "progress.overview": `Pregled`,
  "progress.perTopic": `Po temi`,
  "progress.questionsAnswered": `Odgovori na pitanja`,
  "progress.reset": `Reset`,
  "progress.retryTopic": `Pokušajte ponovo ovu temu`,
  "progress.sectionsDone": `Sekcije završene`,
  "progress.suggestedNext": `Predloženo sljedeće: {topic}`,
  "progress.title": `Napredak`,
  "progress.topicCompletion": `Završetak teme`,
  "report.detailsPlaceholder": `Recite nam više (opcionalno)`,
  "report.incorrectAnswer": `Netačan odgovor`,
  "report.outdatedInfo": `Zastarjele informacije`,
  "report.submit": `Pošalji izvještaj`,
  "report.technicalIssue": `Tehničko pitanje`,
  "report.thanks": `Hvala — izvještaji se pohranjuju lokalno na ovom uređaju.`,
  "report.translationProblem": `Problem sa prevodom`,
  "report.unclearExplanation": `Objašnjenje peu claire`,
  "settings.about": `O ovoj aplikaciji`,
  "settings.appInterfaceLanguage": `Jezik interfejsa aplikacije`,
  "settings.clearProgress": `Jasan napredak`,
  "settings.clearProgressConfirm": `Jeste li sigurni? Ovo će izbrisati sav vaš napredak.`,
  "settings.interfaceDescription": `Meniji, dugmad i navigacija.`,
  "settings.language": `Jezik`,
  "settings.machineNote": `Mašinski preveden sadržaj nije provjerio ljudski recenzent. Ništa ovdje nije označeno kao recenzirano osim ako nije stvarno pregledano.`,
  "settings.machineTranslatedBadge": `Mašinski prevedeno`,
  "settings.manageProgress": `Upravljajte svojim podacima o napretku`,
  "settings.notAvailable": `Još nije dostupno`,
  "settings.officialGuideLink": `Zvanični vodič za učenje`,
  "settings.officialTestLink": `Informacije o službenom testu državljanstva`,
  "settings.privacy": `Privatnost`,
  "settings.privacyText": `Vaši odgovori, oznake i postavke se pohranjuju samo na ovom uređaju. Račun nije potreban. Pitanja koja postavite asistentu za učenje šalju se AI servisu da generiše odgovore.`,
  "settings.reviewedBadge": `Recenzirano`,
  "settings.studyContentLanguage": `Učite jezik sadržaja`,
  "settings.studyDescription": `Učenje teksta i objašnjenja. Možete čitati na jednom jeziku dok se krećete na drugom.`,
  "settings.textSize": `Veličina teksta`,
  "settings.title": `Postavke`,
  "topics.askAssistant": `Pitajte asistenta o ovom dijelu`,
  "topics.bookmarkSection": `Označi odjeljak`,
  "topics.bookmarkedSection": `Bookmarked`,
  "topics.completed": `Završeno`,
  "topics.continueLearningCard": `Nastavite sa učenjem`,
  "topics.demoSourceNote": `Originalni uzorak pitanja — nije službeno ispitno pitanje`,
  "topics.lastVerified": `Posljednja potvrđena {date}`,
  "topics.markComplete": `Označi kao završeno`,
  "topics.markIncomplete": `Označi kao nepotpuno`,
  "topics.minRead": `{n} min čitanja`,
  "topics.next": `Sledeći`,
  "topics.openOfficialPage": `Otvorite zvaničnu stranicu`,
  "topics.paraphrasedSourceNote": `Parafrazirano iz službenog materijala`,
  "topics.practiceTopic": `Vežbajte ovu temu`,
  "topics.previous": `Prethodno`,
  "topics.reportIssue": `Prijavite problem`,
  "topics.reviewedOn": `recenzirano {date}`,
  "topics.reviewedTranslation": `Pregledani prijevod`,
  "topics.section": `Sekcija`,
  "topics.sections": `sekcije`,
  "topics.source": `Izvor`,
  "topics.sourcesDescription": `Tekst studije ovdje je parafraziran iz vodiča za proučavanje državljanstva Vlade Kanade i pregledan na prikazane datume. Pitanja za vježbu istražuju se iz službenog vodiča za učenje.`,
  "topics.sourcesHeading": `Izvori sadržaja i datumi pregleda`,
  "topics.studyLanguageLabel": `Učite jezik sadržaja`,
  "topics.title": `Teme za učenje`,
  "topics.vocabulary": `Vokabular`,
};
