// UI strings for 'ca' — chunk of strings.generated.ts. DO NOT EDIT BY HAND.
import type { StringKey } from "../strings.generated";

export const ca: Record<StringKey, string> = {
  "actions.askAi": `Pregunta a AI`,
  "actions.mockExam": `Examen simulat`,
  "actions.practice": `Pràctica`,
  "actions.quickActions": `Quick actions`,
  "actions.study": `Estudiar`,
  "assistant.aiEyebrow": `Auxiliar d'estudi d'IA`,
  "assistant.answerLanguage": `Llenguatge de resposta`,
  "assistant.charLimit": `Queden {n} caràcters`,
  "assistant.checkingMaterial": `Comprovant el material d'estudi...`,
  "assistant.clearChat": `Esborra el xat`,
  "assistant.copied": `Copiat`,
  "assistant.copy": `Còpia`,
  "assistant.description": `Les respostes són escrites per AI utilitzant només el material d'estudi d'aquesta aplicació, amb les fonts mostrades. La IA encara pot cometre errors: consulteu els detalls importants a les pàgines oficials del govern del Canadà. No assessorament legal o d'immigració.`,
  "assistant.enFrancais": `En francès`,
  "assistant.error": `Alguna cosa va fallar. Si us plau, torna-ho a provar.`,
  "assistant.fromAppContent": `Del contingut de l'aplicació aprovat`,
  "assistant.groundedBadge": `Basat en la font`,
  "assistant.helpful": `Útil`,
  "assistant.inputPlaceholder": `Fes una pregunta sobre la ciutadania canadenca...`,
  "assistant.myAppLanguage": `Idioma de la meva aplicació`,
  "assistant.notCovered": `No cobert — vegeu la pàgina oficial`,
  "assistant.notHelpful": `No útil`,
  "assistant.openAssistant": `Auxiliar d'estudi obert`,
  "assistant.openLink": `Obre l'assistent`,
  "assistant.practiceThis": `Practica això`,
  "assistant.questionAriaLabel": `La teva pregunta`,
  "assistant.reportIncorrect": `Informar d'una resposta incorrecta`,
  "assistant.send": `Enviar`,
  "assistant.showSource": `Mostra la font`,
  "assistant.simpleEnglish": `Anglès senzill`,
  "assistant.source": `Font`,
  "assistant.starter1": `Quines són les tres parts del Parlament?`,
  "assistant.starter2": `Explica simplement la Carta`,
  "assistant.starter3": `Qui representa el rei al Canadà?`,
  "assistant.starter4": `Què cobreix la prova de coneixements?`,
  "assistant.suggestedQuestions": `Preguntes suggerides`,
  "assistant.thinking": `Pensant…`,
  "assistant.title": `Auxiliar d'estudis`,
  "assistant.tryAgain": `Torna-ho a provar`,
  "assistant.tryAsking": `Prova de preguntar:`,
  "assistant.vocabularyLabel": `Vocabulari:`,
  "assistant.whyItMatters": `Per què és important per a la prova`,
  "auth.account": `Account`,
  "auth.checkEmail": `Check your email to confirm your account, then sign in.`,
  "auth.close": `Close`,
  "auth.codeLabel": `Verification code`,
  "auth.codeResent": `New code sent. Check your email.`,
  "auth.codeSent": `Code sent! Check your email and enter the 6-digit code.`,
  "auth.createAccount": `Create account`,
  "auth.dataDeletedMsg": `Your progress and profile data were deleted.`,
  "auth.deleteConfirm": `Tap again to permanently delete`,
  "auth.deleteData": `Delete my data`,
  "auth.email": `Email`,
  "auth.haveAccount": `Already have an account?`,
  "auth.mfaCodeLabel": `Authenticator code`,
  "auth.mfaDisable": `Disable 2FA`,
  "auth.mfaDisabledMsg": `Two-factor authentication is now OFF.`,
  "auth.mfaEnable": `Enable 2FA`,
  "auth.mfaEnabledMsg": `Two-factor authentication is now ON for your account.`,
  "auth.mfaPendingWarn": `2FA code still needed to finish signing in.`,
  "auth.mfaPrompt": `This account uses 2FA — enter the code from your authenticator app.`,
  "auth.mfaScanHint": `Scan this QR code with your authenticator app (Google Authenticator, Authy, 1Password…), then enter the 6-digit code it shows.`,
  "auth.mfaSetupTitle": `Set up two-factor authentication`,
  "auth.mfaSubtitle": `Enter the 6-digit code from your authenticator app.`,
  "auth.mfaTitle": `Two-factor authentication`,
  "auth.noAccount": `Don't have an account?`,
  "auth.password": `Password`,
  "auth.passwordHint": `At least 6 characters`,
  "auth.privacy": `Privacy`,
  "auth.privacyNote": `Your email and progress are private — only you can see them.`,
  "auth.resendCode": `Resend code`,
  "auth.security": `Security`,
  "auth.signIn": `Sign in`,
  "auth.signOut": `Sign out`,
  "auth.signUp": `Sign up`,
  "auth.subtitle": `Save your progress across devices. Your data stays private.`,
  "auth.title": `Account`,
  "auth.verify": `Verify`,
  "auth.verifyCodeSubtitle": `We sent a 6-digit code to your email. Enter it below to finish signing up.`,
  "auth.verifyCodeTitle": `Enter your code`,
  "auth.working": `Please wait…`,
  "bookmarks.continueStudying": `Continuar estudiant`,
  "bookmarks.empty": `Encara no hi ha cap marcador. Toca l'estrella de qualsevol pregunta per desar-la per revisar-la.`,
  "bookmarks.emptyQuestions": `Encara no s'ha guardat res. Toca ☆ en una pregunta pràctica.`,
  "bookmarks.emptySections": `Encara no s'ha guardat res. Toqueu ☆ mentre llegiu una secció.`,
  "bookmarks.remove": `Eliminar`,
  "bookmarks.savedForReview": `guardat per a revisió`,
  "bookmarks.savedQuestions": `Preguntes desades ({n})`,
  "bookmarks.savedSections": `Seccions desades ({n})`,
  "bookmarks.search": `Cerca adreces d'interès...`,
  "bookmarks.title": `Adreces d'interès`,
  "cards.answered": `Respon`,
  "cards.bookmarks": `guardat per a revisió`,
  "cards.bookmarksLabel": `Adreces d'interès`,
  "cards.continueLearning": `Continuar aprenent`,
  "cards.correct": `Correcte`,
  "cards.dailyGoal": `{done}/{total} questions today`,
  "cards.dailyGoalLabel": `Objectiu diari`,
  "cards.dailyGoalTitle": `Daily goal`,
  "cards.mockExam.subtitle": `Temporitzat · 20 preguntes`,
  "cards.mockExam.title": `Examen simulat`,
  "cards.officialInfo.button": `Obre canada.ca`,
  "cards.officialInfo.subtitle": `Visiteu canada.ca per obtenir informació oficial`,
  "cards.officialInfo.title": `Informació oficial`,
  "cards.progress": `Progrés`,
  "cards.progressDetails": `Detalls`,
  "cards.recentlyStudied": `Estudiada recentment`,
  "cards.sections": `Seccions`,
  "cards.studyAssistant.subtitle": `Pregunta qualsevol cosa sobre el material d'estudi`,
  "cards.studyAssistant.title": `Auxiliar d'estudis`,
  "cards.todaysRecommendation": `La recomanació d'avui`,
  "cards.verifiedSource.subtext": `Contingut contrastat amb fonts oficials. Ajuda per a l'estudi independent: no afiliada ni avalada pel Govern del Canadà o IRCC.`,
  "cards.verifiedSource.title": `Font verificada`,
  "common.back": `Enrere`,
  "common.cancel": `Cancel·la`,
  "common.close": `Tancar`,
  "common.continue": `Continua`,
  "common.done": `Fet`,
  "common.emptyBookmarks": `Encara no s'ha guardat res`,
  "common.emptyRecentlyStudied": `Encara no s'ha estudiat res: trieu un tema per començar.`,
  "common.loading": `S'està carregant…`,
  "common.next": `A continuació`,
  "common.of": `de`,
  "common.previous": `Anterior`,
  "common.retry": `Torna-ho a provar`,
  "common.save": `Desa`,
  "exam.allTopics": `Tots els temes`,
  "exam.answeredCount": `{n} va respondre`,
  "exam.autosaveNote": `Les teves respostes es desen a mesura que avances, de manera que tanques l'aplicació no perdràs el teu progrés.`,
  "exam.cancel": `Cancel·la`,
  "exam.confirm": `Confirmeu`,
  "exam.confirmEnd": `{n} preguntes no s'han contestat i es marcaran com a incorrectes.`,
  "exam.confirmEndTitle": `Finalitzar l'examen?`,
  "exam.endExamEarly": `Finalitzar l'examen abans d'hora`,
  "exam.examDisclaimer": `Aquesta puntuació només reflecteix les preguntes de mostra d'aquesta aplicació.`,
  "exam.finishExam": `Acaba l'examen`,
  "exam.newExam": `Nou examen`,
  "exam.noMistakes": `Sense errors: puntuació perfecta!`,
  "exam.pastAttempts": `Intents passats`,
  "exam.questionAriaLabel": `Pregunta {n}`,
  "exam.questionCount": `Nombre de preguntes`,
  "exam.questionOf": `Pregunta {n} de {total}`,
  "exam.questionPalette": `Preguntes`,
  "exam.questionsOption": `{n} preguntes`,
  "exam.resultsTitle": `La teva puntuació`,
  "exam.reviewMistakes": `Revisa els teus errors ({n})`,
  "exam.scoreLine": `{correct} de {total} correcte`,
  "exam.seeProgress": `Veure progrés`,
  "exam.setupDescription": `Aquesta és una simulació pràctica creada a partir de les preguntes d'estudi d'aquesta aplicació. No és la prova oficial i no prediu el vostre resultat.`,
  "exam.setupTitle": `Configura el teu examen simulat`,
  "exam.simulationNote": `Pràctica de simulació · no oficial`,
  "exam.startExam": `Començar l'examen`,
  "exam.timeLeft": `Queda temps`,
  "exam.timedLabel": `cronometrada`,
  "exam.timedToggle": `Cronometrat (90 segons per pregunta)`,
  "exam.title": `Examen simulat`,
  "exam.topicFilter": `Tema`,
  "exam.untimedLabel": `sense temps`,
  "footer.disclaimer": `Citizen Prep és una ajuda d'estudi independent. No està afiliat ni avalat pel Govern del Canadà o IRCC. No pot garantir un resultat aprovat.`,
  "header.appName": `Preparació Ciutadana`,
  "header.tagline": `Eina d'estudi independent · No oficial`,
  "hero.sectionsProgress": `{done} of {total} sections · {percent}% complete`,
  "hero.subtitle": `Eina d'estudi independent · Anglès i francès · no cal cap compte`,
  "hero.title": `Prepareu-vos per a la vostra prova de ciutadania`,
  "nav.exam": `Examen`,
  "nav.home": `a casa`,
  "nav.practice": `Pràctica`,
  "nav.progress": `Progrés`,
  "nav.topics": `Temes`,
  "practice.allLevels": `Tots els nivells`,
  "practice.allTopics": `Tots els temes`,
  "practice.askAiAbout": `Pregunta a AI sobre aquesta pregunta`,
  "practice.bookmarkQuestion": `Pregunta de marcador`,
  "practice.bookmarked": `Marcat com a favorits`,
  "practice.checkAnswer": `Comprova la resposta`,
  "practice.correct": `Correcte`,
  "practice.demoContent": `Contingut de demostració`,
  "practice.difficulty": `Dificultat`,
  "practice.easy": `Fàcil`,
  "practice.explanation": `Explicació`,
  "practice.filters": `Filtres`,
  "practice.hard": `Dur`,
  "practice.incorrect": `No del tot`,
  "practice.medium": `Mitjana`,
  "practice.nextQuestion": `Següent pregunta`,
  "practice.questionCounter": `Pregunta pràctica {n} de {total}`,
  "practice.reportIssue": `Informar d'un problema`,
  "practice.title": `Pràctica`,
  "practice.topicFilter": `Tema`,
  "practice.tryAgain": `Torna-ho a provar`,
  "progress.accuracy": `Precisió`,
  "progress.clearProgressDesc": `Això suprimirà les teves respostes, finalitzacions, adreces d'interès i l'historial d'exàmens d'aquest dispositiu. No es pot desfer.`,
  "progress.clearProgressLabel": `Esborra tot el progrés de l'estudi`,
  "progress.confirmClear": `Sí, aclareix-ho tot`,
  "progress.dailyGoal": `Objectiu diari`,
  "progress.details": `Detalls`,
  "progress.examHistory": `Historial d'exàmens`,
  "progress.noExams": `Encara no s'han fet exàmens.`,
  "progress.noWrongAnswers": `No hi ha respostes incorrectes per revisar ara mateix.`,
  "progress.overview": `Visió general`,
  "progress.perTopic": `Per tema`,
  "progress.questionsAnswered": `Preguntes contestades`,
  "progress.reset": `Restableix`,
  "progress.retryTopic": `Torna a provar aquest tema`,
  "progress.sectionsDone": `Seccions acabades`,
  "progress.suggestedNext": `Suggested next: {topic}`,
  "progress.title": `Progrés`,
  "progress.topicCompletion": `Finalització del tema`,
  "report.detailsPlaceholder": `Explica'ns més (opcional)`,
  "report.incorrectAnswer": `Resposta incorrecta`,
  "report.outdatedInfo": `Informació obsoleta`,
  "report.submit": `Presentar informe`,
  "report.technicalIssue": `Problema tècnic`,
  "report.thanks": `Gràcies: els informes s'emmagatzemen localment en aquest dispositiu.`,
  "report.translationProblem": `Problema de traducció`,
  "report.unclearExplanation": `Explicació peu clare`,
  "settings.about": `Sobre aquesta aplicació`,
  "settings.appInterfaceLanguage": `Idioma de la interfície de l'aplicació`,
  "settings.clearProgress": `Progrés clar`,
  "settings.clearProgressConfirm": `N'estàs segur? Això suprimirà tot el vostre progrés.`,
  "settings.interfaceDescription": `Menús, botons i navegació.`,
  "settings.language": `Llengua`,
  "settings.machineNote": `Un revisor humà no ha comprovat el contingut traduït automàticament. Res aquí no s'etiqueta com a revisat tret que s'hagi revisat realment.`,
  "settings.machineTranslatedBadge": `Traduït automàticament`,
  "settings.manageProgress": `Gestioneu les vostres dades de progrés`,
  "settings.notAvailable": `Encara no disponible`,
  "settings.officialGuideLink": `Guia oficial d'estudi`,
  "settings.officialTestLink": `Informació oficial de la prova de ciutadania`,
  "settings.privacy": `Privadesa`,
  "settings.privacyText": `Les vostres respostes, adreces d'interès i configuració només s'emmagatzemen en aquest dispositiu. No cal cap compte. Les preguntes que feu a l'assistent d'estudi s'envien a un servei d'IA per generar respostes.`,
  "settings.reviewedBadge": `Revisat`,
  "settings.studyContentLanguage": `Estudiar el llenguatge dels continguts`,
  "settings.studyDescription": `Aprenentatge de textos i explicacions. Podeu llegir en un idioma mentre navegueu per un altre.`,
  "settings.textSize": `Mida del text`,
  "settings.title": `Configuració`,
  "topics.askAssistant": `Pregunteu a l'assistent sobre aquesta secció`,
  "topics.bookmarkSection": `Secció de marcadors`,
  "topics.bookmarkedSection": `Marcat com a favorits`,
  "topics.completed": `Completat`,
  "topics.continueLearningCard": `Continuar aprenent`,
  "topics.demoSourceNote": `Pregunta de mostra original: no és una pregunta d'examen oficial`,
  "topics.lastVerified": `Darrera verificació {date}`,
  "topics.markComplete": `Marca com a complet`,
  "topics.markIncomplete": `Marca com a incomplet`,
  "topics.minRead": `{n} minuts de lectura`,
  "topics.next": `A continuació`,
  "topics.openOfficialPage": `Obriu la pàgina oficial`,
  "topics.paraphrasedSourceNote": `Parafrasejat de material oficial`,
  "topics.practiceTopic": `Practica aquest tema`,
  "topics.previous": `Anterior`,
  "topics.reportIssue": `Informar d'un problema`,
  "topics.reviewedOn": `revisat el {date}`,
  "topics.reviewedTranslation": `Traducció revisada`,
  "topics.section": `Secció`,
  "topics.sections": `seccions`,
  "topics.source": `Font`,
  "topics.sourcesDescription": `El text de l'estudi aquí es parafraseja de la guia d'estudi de la ciutadania del Govern del Canadà i es revisa en les dates mostrades. Les preguntes pràctiques s'investiguen a partir de la guia d'estudi oficial.`,
  "topics.sourcesHeading": `Fonts de contingut i dates de revisió`,
  "topics.studyLanguageLabel": `Estudiar el llenguatge dels continguts`,
  "topics.title": `Temes d'estudi`,
  "topics.vocabulary": `Vocabulari`,
};
