// UI strings for 'cs' — chunk of strings.generated.ts. DO NOT EDIT BY HAND.
import type { StringKey } from "../strings.generated";

export const cs: Record<StringKey, string> = {
  "actions.askAi": `Zeptejte se AI`,
  "actions.mockExam": `Falešná zkouška`,
  "actions.practice": `Praxe`,
  "actions.quickActions": `Quick actions`,
  "actions.study": `Studium`,
  "assistant.aiEyebrow": `Studijní asistent AI`,
  "assistant.answerLanguage": `Jazyk odpovědi`,
  "assistant.charLimit": `Zbývá {n} znaků`,
  "assistant.checkingMaterial": `Kontrola studijních materiálů…`,
  "assistant.clearChat": `Vymazat chat`,
  "assistant.copied": `Zkopírováno`,
  "assistant.copy": `Kopírovat`,
  "assistant.description": `Odpovědi píše umělá inteligence pouze za použití studijního materiálu této aplikace se zobrazenými zdroji. Umělá inteligence může stále dělat chyby – zkontrolujte důležité podrobnosti na oficiálních stránkách kanadské vlády. Ne právní nebo imigrační poradenství.`,
  "assistant.enFrancais": `En français`,
  "assistant.error": `Něco se pokazilo. Zkuste to prosím znovu.`,
  "assistant.fromAppContent": `Ze schváleného obsahu aplikace`,
  "assistant.groundedBadge": `Zdroj uzemněný`,
  "assistant.helpful": `Užitečné`,
  "assistant.inputPlaceholder": `Zeptejte se na kanadské občanství…`,
  "assistant.myAppLanguage": `Můj jazyk aplikace`,
  "assistant.notCovered": `Nepokryté – viz oficiální stránka`,
  "assistant.notHelpful": `Není užitečné`,
  "assistant.openAssistant": `Otevřená studijní referentka`,
  "assistant.openLink": `Otevřete asistenta`,
  "assistant.practiceThis": `Cvičte to`,
  "assistant.questionAriaLabel": `Vaše otázka`,
  "assistant.reportIncorrect": `Nahlásit nesprávnou odpověď`,
  "assistant.send": `Odeslat`,
  "assistant.showSource": `Zobrazit zdroj`,
  "assistant.simpleEnglish": `Jednoduchá angličtina`,
  "assistant.source": `Zdroj`,
  "assistant.starter1": `Jaké jsou tři části parlamentu?`,
  "assistant.starter2": `Vysvětlete Chartu jednoduše`,
  "assistant.starter3": `Kdo zastupuje krále v Kanadě?`,
  "assistant.starter4": `Co zahrnuje znalostní test?`,
  "assistant.suggestedQuestions": `Navrhované otázky`,
  "assistant.thinking": `Přemýšlím…`,
  "assistant.title": `Studijní referent`,
  "assistant.tryAgain": `Zkuste to znovu`,
  "assistant.tryAsking": `Zkuste se zeptat:`,
  "assistant.vocabularyLabel": `slovní zásoba:`,
  "assistant.whyItMatters": `Proč je to pro test důležité`,
  "auth.account": `Account`,
  "auth.checkEmail": `Check your email to confirm your account, then sign in.`,
  "auth.close": `Close`,
  "auth.codeLabel": `Verification code`,
  "auth.codeResent": `New code sent. Check your email.`,
  "auth.codeSent": `Code sent! Check your email and enter the 6-digit code.`,
  "auth.createAccount": `Create account`,
  "auth.dataDeletedMsg": `Your progress and profile data were deleted.`,
  "auth.deleteConfirm": `Tap again to permanently delete`,
  "auth.deleteData": `Delete my data`,
  "auth.email": `Email`,
  "auth.haveAccount": `Already have an account?`,
  "auth.mfaCodeLabel": `Authenticator code`,
  "auth.mfaDisable": `Disable 2FA`,
  "auth.mfaDisabledMsg": `Two-factor authentication is now OFF.`,
  "auth.mfaEnable": `Enable 2FA`,
  "auth.mfaEnabledMsg": `Two-factor authentication is now ON for your account.`,
  "auth.mfaPendingWarn": `2FA code still needed to finish signing in.`,
  "auth.mfaPrompt": `This account uses 2FA — enter the code from your authenticator app.`,
  "auth.mfaScanHint": `Scan this QR code with your authenticator app (Google Authenticator, Authy, 1Password…), then enter the 6-digit code it shows.`,
  "auth.mfaSetupTitle": `Set up two-factor authentication`,
  "auth.mfaSubtitle": `Enter the 6-digit code from your authenticator app.`,
  "auth.mfaTitle": `Two-factor authentication`,
  "auth.noAccount": `Don't have an account?`,
  "auth.password": `Password`,
  "auth.passwordHint": `At least 6 characters`,
  "auth.privacy": `Privacy`,
  "auth.privacyNote": `Your email and progress are private — only you can see them.`,
  "auth.resendCode": `Resend code`,
  "auth.security": `Security`,
  "auth.signIn": `Sign in`,
  "auth.signOut": `Sign out`,
  "auth.signUp": `Sign up`,
  "auth.subtitle": `Save your progress across devices. Your data stays private.`,
  "auth.title": `Account`,
  "auth.verify": `Verify`,
  "auth.verifyCodeSubtitle": `We sent a 6-digit code to your email. Enter it below to finish signing up.`,
  "auth.verifyCodeTitle": `Enter your code`,
  "auth.working": `Please wait…`,
  "bookmarks.continueStudying": `Pokračujte ve studiu`,
  "bookmarks.empty": `Zatím žádné záložky. Klepnutím na hvězdičku u jakékoli otázky ji uložíte ke kontrole.`,
  "bookmarks.emptyQuestions": `Zatím není nic uloženo. Klepněte na ☆ na cvičné otázce.`,
  "bookmarks.emptySections": `Zatím není nic uloženo. Při čtení sekce klepněte na ☆.`,
  "bookmarks.remove": `Odebrat`,
  "bookmarks.savedForReview": `uloženy ke kontrole`,
  "bookmarks.savedQuestions": `Uložené otázky ({n})`,
  "bookmarks.savedSections": `Uložené sekce ({n})`,
  "bookmarks.search": `Hledat v záložkách…`,
  "bookmarks.title": `Záložky`,
  "cards.answered": `Odpovězeno`,
  "cards.bookmarks": `uloženy ke kontrole`,
  "cards.bookmarksLabel": `Záložky`,
  "cards.continueLearning": `Pokračujte v učení`,
  "cards.correct": `Správně`,
  "cards.dailyGoal": `{done}/{total} otázek dnes`,
  "cards.dailyGoalLabel": `Denní cíl`,
  "cards.dailyGoalTitle": `Daily goal`,
  "cards.mockExam.subtitle": `Časově · 20 otázek`,
  "cards.mockExam.title": `Falešná zkouška`,
  "cards.officialInfo.button": `Otevřete canada.ca`,
  "cards.officialInfo.subtitle": `Oficiální podrobnosti najdete na canada.ca`,
  "cards.officialInfo.title": `Oficiální informace`,
  "cards.progress": `Pokrok`,
  "cards.progressDetails": `Podrobnosti`,
  "cards.recentlyStudied": `Nedávno studoval`,
  "cards.sections": `Sekce`,
  "cards.studyAssistant.subtitle": `Zeptejte se na cokoliv ohledně studijního materiálu`,
  "cards.studyAssistant.title": `Studijní referent`,
  "cards.todaysRecommendation": `Dnešní doporučení`,
  "cards.verifiedSource.subtext": `Obsah zkontrolován podle oficiálních zdrojů. Nezávislá studijní pomůcka – není přidružena ani schválena vládou Kanady nebo IRCC.`,
  "cards.verifiedSource.title": `Ověřený zdroj`,
  "common.back": `Zpět`,
  "common.cancel": `Zrušit`,
  "common.close": `Zavřít`,
  "common.continue": `Pokračujte`,
  "common.done": `Hotovo`,
  "common.emptyBookmarks": `Zatím není nic uloženo`,
  "common.emptyRecentlyStudied": `Zatím není nic prostudováno – začněte výběrem tématu.`,
  "common.loading": `Načítání…`,
  "common.next": `Další`,
  "common.of": `z`,
  "common.previous": `Předchozí`,
  "common.retry": `Zkuste to znovu`,
  "common.save": `Uložit`,
  "exam.allTopics": `Všechna témata`,
  "exam.answeredCount": `{n} odpověděl`,
  "exam.autosaveNote": `Vaše odpovědi se průběžně ukládají, takže zavřením aplikace nepřijdete o svůj postup.`,
  "exam.cancel": `Zrušit`,
  "exam.confirm": `Potvrďte`,
  "exam.confirmEnd": `Otázky ({n}) jsou nezodpovězené a budou označeny jako nesprávné.`,
  "exam.confirmEndTitle": `Ukončit zkoušku?`,
  "exam.endExamEarly": `Ukončete zkoušku dříve`,
  "exam.examDisclaimer": `Toto skóre odráží pouze vzorové otázky této aplikace.`,
  "exam.finishExam": `Dokončete zkoušku`,
  "exam.newExam": `Nová zkouška`,
  "exam.noMistakes": `Žádné chyby – perfektní skóre!`,
  "exam.pastAttempts": `Minulé pokusy`,
  "exam.questionAriaLabel": `otázka {n}`,
  "exam.questionCount": `Počet otázek`,
  "exam.questionOf": `Otázka {n} z {total}`,
  "exam.questionPalette": `Otázky`,
  "exam.questionsOption": `{n} otázek`,
  "exam.resultsTitle": `Vaše skóre`,
  "exam.reviewMistakes": `Zkontrolujte své chyby ({n})`,
  "exam.scoreLine": `{correct} z {total} správně`,
  "exam.seeProgress": `Viz pokrok`,
  "exam.setupDescription": `Toto je cvičná simulace postavená na studijních otázkách této aplikace. Není to oficiální test a nepředpovídá váš výsledek.`,
  "exam.setupTitle": `Nastavte si falešnou zkoušku`,
  "exam.simulationNote": `Cvičební simulace · není oficiální`,
  "exam.startExam": `Zahájit zkoušku`,
  "exam.timeLeft": `Zbývá čas`,
  "exam.timedLabel": `načasované`,
  "exam.timedToggle": `Časově (90 sekund na otázku)`,
  "exam.title": `Falešná zkouška`,
  "exam.topicFilter": `Téma`,
  "exam.untimedLabel": `nenačasované`,
  "footer.disclaimer": `Citizen Prep je nezávislá studijní pomůcka. Není přidružena ani schválena vládou Kanady nebo IRCC. Nemůže zaručit úspěšný výsledek.`,
  "header.appName": `Občanská příprava`,
  "header.tagline": `Nezávislý studijní nástroj · Neoficiální`,
  "hero.sectionsProgress": `{done} of {total} sections · {percent}% complete`,
  "hero.subtitle": `Nezávislý studijní nástroj · Angličtina a francouzština · není potřeba žádný účet`,
  "hero.title": `Připravte se na zkoušku občanství`,
  "nav.exam": `Zkouška`,
  "nav.home": `Domů`,
  "nav.practice": `Praxe`,
  "nav.progress": `Pokrok`,
  "nav.topics": `Témata`,
  "practice.allLevels": `Všechny úrovně`,
  "practice.allTopics": `Všechna témata`,
  "practice.askAiAbout": `Zeptejte se AI na tuto otázku`,
  "practice.bookmarkQuestion": `Otázka na záložku`,
  "practice.bookmarked": `Záložka`,
  "practice.checkAnswer": `Zkontrolujte odpověď`,
  "practice.correct": `Správně`,
  "practice.demoContent": `Demo obsah`,
  "practice.difficulty": `Obtížnost`,
  "practice.easy": `Snadno`,
  "practice.explanation": `Vysvětlení`,
  "practice.filters": `Filtry`,
  "practice.hard": `Těžko`,
  "practice.incorrect": `Ne tak docela`,
  "practice.medium": `Střední`,
  "practice.nextQuestion": `Další otázka`,
  "practice.questionCounter": `Cvičná otázka {n} z {total}`,
  "practice.reportIssue": `Nahlásit problém`,
  "practice.title": `Praxe`,
  "practice.topicFilter": `Téma`,
  "practice.tryAgain": `Zkuste to znovu`,
  "progress.accuracy": `Přesnost`,
  "progress.clearProgressDesc": `Tím se z tohoto zařízení odstraní vaše odpovědi, dokončení, záložky a historie zkoušek. Nelze to vrátit zpět.`,
  "progress.clearProgressLabel": `Vymazat veškerý pokrok ve studiu`,
  "progress.confirmClear": `Ano, vymazat vše`,
  "progress.dailyGoal": `Denní cíl`,
  "progress.details": `Podrobnosti`,
  "progress.examHistory": `Historie zkoušek`,
  "progress.noExams": `Zatím nebyly provedeny žádné zkoušky.`,
  "progress.noWrongAnswers": `Momentálně nejsou žádné nesprávné odpovědi ke kontrole.`,
  "progress.overview": `Přehled`,
  "progress.perTopic": `Podle tématu`,
  "progress.questionsAnswered": `Otázky zodpovězeny`,
  "progress.reset": `Resetovat`,
  "progress.retryTopic": `Zkuste toto téma znovu`,
  "progress.sectionsDone": `Sekce dokončeny`,
  "progress.suggestedNext": `Další návrh: {topic}`,
  "progress.title": `Pokrok`,
  "progress.topicCompletion": `Dokončení tématu`,
  "report.detailsPlaceholder": `Řekněte nám více (volitelné)`,
  "report.incorrectAnswer": `Nesprávná odpověď`,
  "report.outdatedInfo": `Zastaralé informace`,
  "report.submit": `Odeslat zprávu`,
  "report.technicalIssue": `Technický problém`,
  "report.thanks": `Díky – přehledy se ukládají lokálně na tomto zařízení.`,
  "report.translationProblem": `Problém s překladem`,
  "report.unclearExplanation": `Vysvětlení peu claire`,
  "settings.about": `O této aplikaci`,
  "settings.appInterfaceLanguage": `Jazyk rozhraní aplikace`,
  "settings.clearProgress": `Jasný pokrok`,
  "settings.clearProgressConfirm": `jsi si jistý? Tímto smažete veškerý váš postup.`,
  "settings.interfaceDescription": `Nabídky, tlačítka a navigace.`,
  "settings.language": `Jazyk`,
  "settings.machineNote": `Strojově přeložený obsah nebyl zkontrolován lidským recenzentem. Nic zde není označeno jako recenzované, pokud to skutečně nebylo zkontrolováno.`,
  "settings.machineTranslatedBadge": `Strojově přeloženo`,
  "settings.manageProgress": `Spravujte své údaje o pokroku`,
  "settings.notAvailable": `Zatím nedostupné`,
  "settings.officialGuideLink": `Oficiální studijní průvodce`,
  "settings.officialTestLink": `Oficiální informace o testu občanství`,
  "settings.privacy": `soukromí`,
  "settings.privacyText": `Vaše odpovědi, záložky a nastavení jsou uloženy pouze v tomto zařízení. Není potřeba žádný účet. Otázky, které položíte studijní referentce, jsou zasílány do služby AI, aby vygenerovala odpovědi.`,
  "settings.reviewedBadge": `Zkontrolováno`,
  "settings.studyContentLanguage": `Studijní obsahový jazyk`,
  "settings.studyDescription": `Učební text a vysvětlení. Můžete číst v jednom jazyce a navigovat v jiném.`,
  "settings.textSize": `Velikost textu`,
  "settings.title": `Nastavení`,
  "topics.askAssistant": `Zeptejte se asistenta na tuto sekci`,
  "topics.bookmarkSection": `Sekce záložek`,
  "topics.bookmarkedSection": `Záložka`,
  "topics.completed": `Dokončeno`,
  "topics.continueLearningCard": `Pokračujte v učení`,
  "topics.demoSourceNote": `Původní vzorová otázka – není oficiální zkušební otázka`,
  "topics.lastVerified": `Naposledy ověřeno {date}`,
  "topics.markComplete": `Označit jako dokončené`,
  "topics.markIncomplete": `Označit jako neúplné`,
  "topics.minRead": `čtení {n} min`,
  "topics.next": `Další`,
  "topics.openOfficialPage": `Otevřete oficiální stránku`,
  "topics.paraphrasedSourceNote": `Parafrázováno z oficiálních materiálů`,
  "topics.practiceTopic": `Procvičte si toto téma`,
  "topics.previous": `Předchozí`,
  "topics.reportIssue": `Nahlásit problém`,
  "topics.reviewedOn": `recenzováno {date}`,
  "topics.reviewedTranslation": `Recenzovaný překlad`,
  "topics.section": `sekce`,
  "topics.sections": `sekce`,
  "topics.source": `Zdroj`,
  "topics.sourcesDescription": `Zde uvedený studijní text je parafrázován z příručky kanadské vlády pro studium občanství a je zkontrolován v uvedených datech. Praktické otázky jsou zkoumány z oficiální studijní příručky.`,
  "topics.sourcesHeading": `Zdroje obsahu a data recenzí`,
  "topics.studyLanguageLabel": `Studijní obsahový jazyk`,
  "topics.title": `Studijní témata`,
  "topics.vocabulary": `Slovní zásoba`,
};
