// UI strings for 'cy' — chunk of strings.generated.ts. DO NOT EDIT BY HAND.
import type { StringKey } from "../strings.generated";

export const cy: Record<StringKey, string> = {
  "actions.askAi": `Gofynnwch AI`,
  "actions.mockExam": `Ffug arholiad`,
  "actions.practice": `Ymarfer`,
  "actions.quickActions": `Quick actions`,
  "actions.study": `Astudio`,
  "assistant.aiEyebrow": `Cynorthwyydd astudio AI`,
  "assistant.answerLanguage": `Ateb iaith`,
  "assistant.charLimit": `{n} nod ar ôl`,
  "assistant.checkingMaterial": `Wrthi'n gwirio'r deunydd astudio…`,
  "assistant.clearChat": `Clirio sgwrs`,
  "assistant.copied": `Wedi'i gopïo`,
  "assistant.copy": `Copi`,
  "assistant.description": `Ysgrifennir atebion gan AI gan ddefnyddio deunydd astudio'r ap hwn yn unig, a dangosir ffynonellau. Gall AI wneud camgymeriadau o hyd - gwiriwch fanylion pwysig ar dudalennau swyddogol Llywodraeth Canada. Nid cyngor cyfreithiol na chyngor mewnfudo.`,
  "assistant.enFrancais": `En français`,
  "assistant.error": `Aeth rhywbeth o'i le. Ceisiwch eto.`,
  "assistant.fromAppContent": `O gynnwys app cymeradwy`,
  "assistant.groundedBadge": `Yn seiliedig ar ffynhonnell`,
  "assistant.helpful": `Cymwynasgar`,
  "assistant.inputPlaceholder": `Gofynnwch gwestiwn am ddinasyddiaeth Canada…`,
  "assistant.myAppLanguage": `Iaith fy ap`,
  "assistant.notCovered": `Heb ei gynnwys - gweler y dudalen swyddogol`,
  "assistant.notHelpful": `Ddim yn ddefnyddiol`,
  "assistant.openAssistant": `Cynorthwyydd astudio agored`,
  "assistant.openLink": `Cynorthwyydd agored`,
  "assistant.practiceThis": `Ymarferwch hyn`,
  "assistant.questionAriaLabel": `Eich cwestiwn`,
  "assistant.reportIncorrect": `Rhoi gwybod am ateb anghywir`,
  "assistant.send": `Anfon`,
  "assistant.showSource": `Dangos ffynhonnell`,
  "assistant.simpleEnglish": `Saesneg syml`,
  "assistant.source": `Ffynhonnell`,
  "assistant.starter1": `Beth yw tair rhan y Senedd?`,
  "assistant.starter2": `Eglurwch y Siarter yn syml`,
  "assistant.starter3": `Pwy sy'n cynrychioli'r Brenin yng Nghanada?`,
  "assistant.starter4": `Beth mae'r prawf gwybodaeth yn ei gwmpasu?`,
  "assistant.suggestedQuestions": `Cwestiynau a awgrymir`,
  "assistant.thinking": `Meddwl…`,
  "assistant.title": `Cynorthwyydd astudio`,
  "assistant.tryAgain": `Ceisiwch eto`,
  "assistant.tryAsking": `Ceisiwch ofyn:`,
  "assistant.vocabularyLabel": `Geirfa:`,
  "assistant.whyItMatters": `Pam ei fod yn bwysig ar gyfer y prawf`,
  "auth.account": `Account`,
  "auth.checkEmail": `Check your email to confirm your account, then sign in.`,
  "auth.close": `Close`,
  "auth.codeLabel": `Verification code`,
  "auth.codeResent": `New code sent. Check your email.`,
  "auth.codeSent": `Code sent! Check your email and enter the 6-digit code.`,
  "auth.createAccount": `Create account`,
  "auth.dataDeletedMsg": `Your progress and profile data were deleted.`,
  "auth.deleteConfirm": `Tap again to permanently delete`,
  "auth.deleteData": `Delete my data`,
  "auth.email": `Email`,
  "auth.haveAccount": `Already have an account?`,
  "auth.mfaCodeLabel": `Authenticator code`,
  "auth.mfaDisable": `Disable 2FA`,
  "auth.mfaDisabledMsg": `Two-factor authentication is now OFF.`,
  "auth.mfaEnable": `Enable 2FA`,
  "auth.mfaEnabledMsg": `Two-factor authentication is now ON for your account.`,
  "auth.mfaPendingWarn": `2FA code still needed to finish signing in.`,
  "auth.mfaPrompt": `This account uses 2FA — enter the code from your authenticator app.`,
  "auth.mfaScanHint": `Scan this QR code with your authenticator app (Google Authenticator, Authy, 1Password…), then enter the 6-digit code it shows.`,
  "auth.mfaSetupTitle": `Set up two-factor authentication`,
  "auth.mfaSubtitle": `Enter the 6-digit code from your authenticator app.`,
  "auth.mfaTitle": `Two-factor authentication`,
  "auth.noAccount": `Don't have an account?`,
  "auth.password": `Password`,
  "auth.passwordHint": `At least 6 characters`,
  "auth.privacy": `Privacy`,
  "auth.privacyNote": `Your email and progress are private — only you can see them.`,
  "auth.resendCode": `Resend code`,
  "auth.security": `Security`,
  "auth.signIn": `Sign in`,
  "auth.signOut": `Sign out`,
  "auth.signUp": `Sign up`,
  "auth.subtitle": `Save your progress across devices. Your data stays private.`,
  "auth.title": `Account`,
  "auth.verify": `Verify`,
  "auth.verifyCodeSubtitle": `We sent a 6-digit code to your email. Enter it below to finish signing up.`,
  "auth.verifyCodeTitle": `Enter your code`,
  "auth.working": `Please wait…`,
  "bookmarks.continueStudying": `Parhewch i astudio`,
  "bookmarks.empty": `Dim nodau tudalen eto. Tapiwch y seren ar unrhyw gwestiwn i'w gadw i'w adolygu.`,
  "bookmarks.emptyQuestions": `Dim byd wedi'i arbed eto. Tap ☆ ar gwestiwn ymarfer.`,
  "bookmarks.emptySections": `Dim byd wedi'i arbed eto. Tap ☆ wrth ddarllen adran.`,
  "bookmarks.remove": `Dileu`,
  "bookmarks.savedForReview": `cadw ar gyfer adolygiad`,
  "bookmarks.savedQuestions": `Cwestiynau wedi'u cadw ({n})`,
  "bookmarks.savedSections": `Adrannau wedi'u cadw ({n})`,
  "bookmarks.search": `Chwilio nodau tudalen…`,
  "bookmarks.title": `Llyfrnodau`,
  "cards.answered": `Atebwyd`,
  "cards.bookmarks": `cadw ar gyfer adolygiad`,
  "cards.bookmarksLabel": `Llyfrnodau`,
  "cards.continueLearning": `Parhau i ddysgu`,
  "cards.correct": `Cywir`,
  "cards.dailyGoal": `{done}/{total} questions today`,
  "cards.dailyGoalLabel": `Nod dyddiol`,
  "cards.dailyGoalTitle": `Daily goal`,
  "cards.mockExam.subtitle": `Wedi'i amseru · 20 cwestiwn`,
  "cards.mockExam.title": `Ffug arholiad`,
  "cards.officialInfo.button": `Agor canada.ca`,
  "cards.officialInfo.subtitle": `Ewch i canada.ca am fanylion swyddogol`,
  "cards.officialInfo.title": `Gwybodaeth swyddogol`,
  "cards.progress": `Cynnydd`,
  "cards.progressDetails": `Manylion`,
  "cards.recentlyStudied": `Astudiwyd yn ddiweddar`,
  "cards.sections": `Adrannau`,
  "cards.studyAssistant.subtitle": `Gofynnwch unrhyw beth am y deunydd astudio`,
  "cards.studyAssistant.title": `Cynorthwyydd astudio`,
  "cards.todaysRecommendation": `Argymhelliad heddiw`,
  "cards.verifiedSource.subtext": `Cynnwys wedi'i wirio yn erbyn ffynonellau swyddogol. Cymorth astudio annibynnol - heb fod yn gysylltiedig â neu wedi'i gymeradwyo gan Lywodraeth Canada neu IRCC.`,
  "cards.verifiedSource.title": `Ffynhonnell wedi'i dilysu`,
  "common.back": `Yn ol`,
  "common.cancel": `Canslo`,
  "common.close": `Cau`,
  "common.continue": `Parhewch`,
  "common.done": `Wedi'i wneud`,
  "common.emptyBookmarks": `Dim byd wedi'i arbed eto`,
  "common.emptyRecentlyStudied": `Dim byd wedi'i astudio eto - dewiswch bwnc i ddechrau.`,
  "common.loading": `Wrthi'n llwytho…`,
  "common.next": `Nesaf`,
  "common.of": `o`,
  "common.previous": `Blaenorol`,
  "common.retry": `Ceisiwch eto`,
  "common.save": `Arbed`,
  "exam.allTopics": `Pob pwnc`,
  "exam.answeredCount": `Atebodd {n}`,
  "exam.autosaveNote": `Mae eich atebion yn cael eu cadw wrth i chi fynd, felly ni fydd cau'r ap yn colli'ch cynnydd.`,
  "exam.cancel": `Canslo`,
  "exam.confirm": `Cadarnhau`,
  "exam.confirmEnd": `Mae {n} cwestiwn heb eu hateb a byddant yn cael eu marcio'n anghywir.`,
  "exam.confirmEndTitle": `Diwedd arholiad?`,
  "exam.endExamEarly": `Gorffen arholiad yn gynnar`,
  "exam.examDisclaimer": `Mae'r sgôr hwn yn adlewyrchu cwestiynau sampl yr ap hwn yn unig.`,
  "exam.finishExam": `Gorffen arholiad`,
  "exam.newExam": `Arholiad newydd`,
  "exam.noMistakes": `Dim camgymeriadau - sgôr berffaith!`,
  "exam.pastAttempts": `Ymdrechion yn y gorffennol`,
  "exam.questionAriaLabel": `Cwestiwn {n}`,
  "exam.questionCount": `Nifer y cwestiynau`,
  "exam.questionOf": `Cwestiwn {n} o {total}`,
  "exam.questionPalette": `Cwestiynau`,
  "exam.questionsOption": `{n} cwestiwn`,
  "exam.resultsTitle": `Eich sgôr`,
  "exam.reviewMistakes": `Adolygwch eich camgymeriadau ({n})`,
  "exam.scoreLine": `{correct} of {total} correct`,
  "exam.seeProgress": `Gweld cynnydd`,
  "exam.setupDescription": `Mae hwn yn efelychiad ymarfer a adeiladwyd o gwestiynau astudio'r app hwn. Nid dyma'r prawf swyddogol ac nid yw'n rhagweld eich canlyniad.`,
  "exam.setupTitle": `Trefnwch eich ffug arholiad`,
  "exam.simulationNote": `Efelychiad ymarfer · ddim yn swyddogol`,
  "exam.startExam": `Dechrau arholiad`,
  "exam.timeLeft": `Amser ar ôl`,
  "exam.timedLabel": `amseru`,
  "exam.timedToggle": `Wedi'i amseru (90 eiliad y cwestiwn)`,
  "exam.title": `Ffug arholiad`,
  "exam.topicFilter": `Testun`,
  "exam.untimedLabel": `diamser`,
  "footer.disclaimer": `Mae Citizen Prep yn gymorth astudio annibynnol. Heb fod yn gysylltiedig â neu wedi'i gymeradwyo gan Lywodraeth Canada neu IRCC. Ni all warantu canlyniad pasio.`,
  "header.appName": `Paratoi ar gyfer y Dinesydd`,
  "header.tagline": `Offeryn astudio annibynnol · Ddim yn swyddogol`,
  "hero.sectionsProgress": `{done} of {total} sections · {percent}% complete`,
  "hero.subtitle": `Offeryn astudio annibynnol · Saesneg a Ffrangeg · dim angen cyfrif`,
  "hero.title": `Paratowch ar gyfer eich prawf dinasyddiaeth`,
  "nav.exam": `Arholiad`,
  "nav.home": `Cartref`,
  "nav.practice": `Ymarfer`,
  "nav.progress": `Cynnydd`,
  "nav.topics": `Pynciau`,
  "practice.allLevels": `Pob lefel`,
  "practice.allTopics": `Pob pwnc`,
  "practice.askAiAbout": `Gofynnwch i AI am y cwestiwn hwn`,
  "practice.bookmarkQuestion": `Cwestiwn llyfrnod`,
  "practice.bookmarked": `Llyfrnodi`,
  "practice.checkAnswer": `Gwirio ateb`,
  "practice.correct": `Cywir`,
  "practice.demoContent": `Cynnwys demo`,
  "practice.difficulty": `Anhawster`,
  "practice.easy": `Hawdd`,
  "practice.explanation": `Eglurhad`,
  "practice.filters": `Hidlau`,
  "practice.hard": `Caled`,
  "practice.incorrect": `Ddim yn hollol`,
  "practice.medium": `Canolig`,
  "practice.nextQuestion": `Cwestiwn nesaf`,
  "practice.questionCounter": `Cwestiwn ymarfer {n} o {total}`,
  "practice.reportIssue": `Rhoi gwybod am fater`,
  "practice.title": `Ymarfer`,
  "practice.topicFilter": `Testun`,
  "practice.tryAgain": `Ceisiwch eto`,
  "progress.accuracy": `Cywirdeb`,
  "progress.clearProgressDesc": `Mae hyn yn dileu eich atebion, cwblhau, nodau tudalen a hanes arholiadau o'r ddyfais hon. Ni ellir ei ddadwneud.`,
  "progress.clearProgressLabel": `Clirio holl gynnydd yr astudiaeth`,
  "progress.confirmClear": `Ie, cliriwch bopeth`,
  "progress.dailyGoal": `Nod dyddiol`,
  "progress.details": `Manylion`,
  "progress.examHistory": `Hanes arholiadau`,
  "progress.noExams": `Dim arholiadau wedi'u cymryd eto.`,
  "progress.noWrongAnswers": `Dim atebion anghywir i'w hadolygu ar hyn o bryd.`,
  "progress.overview": `Trosolwg`,
  "progress.perTopic": `Fesul pwnc`,
  "progress.questionsAnswered": `Cwestiynau wedi'u hateb`,
  "progress.reset": `Ailosod`,
  "progress.retryTopic": `Rhowch gynnig arall ar y pwnc hwn`,
  "progress.sectionsDone": `Adrannau wedi'u cwblhau`,
  "progress.suggestedNext": `Awgrymir nesaf: {topic}`,
  "progress.title": `Cynnydd`,
  "progress.topicCompletion": `Cwblhau pwnc`,
  "report.detailsPlaceholder": `Dywedwch fwy wrthym (dewisol)`,
  "report.incorrectAnswer": `Ateb anghywir`,
  "report.outdatedInfo": `Gwybodaeth hen ffasiwn`,
  "report.submit": `Cyflwyno adroddiad`,
  "report.technicalIssue": `Mater technegol`,
  "report.thanks": `Diolch - mae adroddiadau'n cael eu storio'n lleol ar y ddyfais hon.`,
  "report.translationProblem": `Problem cyfieithu`,
  "report.unclearExplanation": `Explication peu claire`,
  "settings.about": `Ynglŷn â'r app hwn`,
  "settings.appInterfaceLanguage": `Iaith rhyngwyneb ap`,
  "settings.clearProgress": `Cynnydd amlwg`,
  "settings.clearProgressConfirm": `Ydych chi'n siŵr? Bydd hyn yn dileu eich holl gynnydd.`,
  "settings.interfaceDescription": `Bwydlenni, botymau a llywio.`,
  "settings.language": `Iaith`,
  "settings.machineNote": `Nid yw cynnwys wedi'i gyfieithu â pheiriant wedi'i wirio gan adolygydd dynol. Nid oes dim byd yma wedi'i labelu fel adolygiad oni bai ei fod wedi'i adolygu mewn gwirionedd.`,
  "settings.machineTranslatedBadge": `Wedi'i gyfieithu â pheiriant`,
  "settings.manageProgress": `Rheoli eich data cynnydd`,
  "settings.notAvailable": `Ddim ar gael eto`,
  "settings.officialGuideLink": `Canllaw astudio swyddogol`,
  "settings.officialTestLink": `Gwybodaeth prawf dinasyddiaeth swyddogol`,
  "settings.privacy": `Preifatrwydd`,
  "settings.privacyText": `Mae eich atebion, nodau tudalen a gosodiadau yn cael eu storio ar y ddyfais hon yn unig. Nid oes angen cyfrif. Mae cwestiynau rydych chi'n eu gofyn i'r cynorthwyydd astudio yn cael eu hanfon at wasanaeth AI i gynhyrchu atebion.`,
  "settings.reviewedBadge": `Adolygwyd`,
  "settings.studyContentLanguage": `Astudiwch iaith cynnwys`,
  "settings.studyDescription": `Dysgu testun ac esboniadau. Gallwch ddarllen mewn un iaith tra'n llywio mewn iaith arall.`,
  "settings.textSize": `Maint testun`,
  "settings.title": `Gosodiadau`,
  "topics.askAssistant": `Gofynnwch i'r cynorthwyydd am yr adran hon`,
  "topics.bookmarkSection": `Adran nod tudalen`,
  "topics.bookmarkedSection": `Llyfrnodi`,
  "topics.completed": `Cwblhawyd`,
  "topics.continueLearningCard": `Parhau i ddysgu`,
  "topics.demoSourceNote": `Cwestiwn sampl gwreiddiol - nid cwestiwn arholiad swyddogol`,
  "topics.lastVerified": `{date} a ddilyswyd ddiwethaf`,
  "topics.markComplete": `Marciwch ei fod yn gyflawn`,
  "topics.markIncomplete": `Marciwch fel anghyflawn`,
  "topics.minRead": `{n} mun darllen`,
  "topics.next": `Nesaf`,
  "topics.openOfficialPage": `Agor tudalen swyddogol`,
  "topics.paraphrasedSourceNote": `Aralleirio o ddeunydd swyddogol`,
  "topics.practiceTopic": `Ymarfer y pwnc hwn`,
  "topics.previous": `Blaenorol`,
  "topics.reportIssue": `Rhoi gwybod am fater`,
  "topics.reviewedOn": `reviewed {date}`,
  "topics.reviewedTranslation": `Cyfieithiad wedi'i adolygu`,
  "topics.section": `Adran`,
  "topics.sections": `adrannau`,
  "topics.source": `Ffynhonnell`,
  "topics.sourcesDescription": `Mae testun astudio yma wedi'i aralleirio o ganllaw astudio dinasyddiaeth Llywodraeth Canada a'i adolygu ar y dyddiadau a ddangosir. Ymchwilir i gwestiynau ymarfer o'r canllaw astudio swyddogol.`,
  "topics.sourcesHeading": `Ffynonellau cynnwys a dyddiadau adolygu`,
  "topics.studyLanguageLabel": `Astudiwch iaith cynnwys`,
  "topics.title": `Astudiwch bynciau`,
  "topics.vocabulary": `Geirfa`,
};
