// UI strings for 'da' — chunk of strings.generated.ts. DO NOT EDIT BY HAND.
import type { StringKey } from "../strings.generated";

export const da: Record<StringKey, string> = {
  "actions.askAi": `Spørg AI`,
  "actions.mockExam": `Spoteksamen`,
  "actions.practice": `Øv`,
  "actions.quickActions": `Quick actions`,
  "actions.study": `Studie`,
  "assistant.aiEyebrow": `AI studieassistent`,
  "assistant.answerLanguage": `Svarsprog`,
  "assistant.charLimit": `{n} tegn tilbage`,
  "assistant.checkingMaterial": `Kontrollerer studiematerialet...`,
  "assistant.clearChat": `Ryd chat`,
  "assistant.copied": `Kopieret`,
  "assistant.copy": `Kopiér`,
  "assistant.description": `Svarene er skrevet af AI ved hjælp af kun denne app's undersøgelsesmateriale, med kilder vist. AI kan stadig lave fejl - tjek vigtige detaljer på Canadas officielle sider. Ikke juridisk rådgivning eller immigrationsrådgivning.`,
  "assistant.enFrancais": `En français`,
  "assistant.error": `Noget gik galt. Prøv venligst igen.`,
  "assistant.fromAppContent": `Fra godkendt appindhold`,
  "assistant.groundedBadge": `Kildebaseret`,
  "assistant.helpful": `Hjælpsom`,
  "assistant.inputPlaceholder": `Stil et spørgsmål om canadisk statsborgerskab...`,
  "assistant.myAppLanguage": `Mit app sprog`,
  "assistant.notCovered": `Ikke dækket - se officiel side`,
  "assistant.notHelpful": `Ikke nyttigt`,
  "assistant.openAssistant": `Åben studieassistent`,
  "assistant.openLink": `Åbn assistent`,
  "assistant.practiceThis": `Øv dette`,
  "assistant.questionAriaLabel": `Dit spørgsmål`,
  "assistant.reportIncorrect": `Rapporter et forkert svar`,
  "assistant.send": `Send`,
  "assistant.showSource": `Vis kilde`,
  "assistant.simpleEnglish": `Simpelt engelsk`,
  "assistant.source": `Kilde`,
  "assistant.starter1": `Hvad er de tre dele af Folketinget?`,
  "assistant.starter2": `Forklar charteret enkelt`,
  "assistant.starter3": `Hvem repræsenterer kongen i Canada?`,
  "assistant.starter4": `Hvad dækker videnstesten over?`,
  "assistant.suggestedQuestions": `Foreslåede spørgsmål`,
  "assistant.thinking": `Tænker...`,
  "assistant.title": `Studieassistent`,
  "assistant.tryAgain": `Prøv igen`,
  "assistant.tryAsking": `Prøv at spørge:`,
  "assistant.vocabularyLabel": `Ordforråd:`,
  "assistant.whyItMatters": `Hvorfor det er vigtigt for testen`,
  "auth.account": `Account`,
  "auth.checkEmail": `Check your email to confirm your account, then sign in.`,
  "auth.close": `Close`,
  "auth.codeLabel": `Verification code`,
  "auth.codeResent": `New code sent. Check your email.`,
  "auth.codeSent": `Code sent! Check your email and enter the 6-digit code.`,
  "auth.createAccount": `Create account`,
  "auth.dataDeletedMsg": `Your progress and profile data were deleted.`,
  "auth.deleteConfirm": `Tap again to permanently delete`,
  "auth.deleteData": `Delete my data`,
  "auth.email": `Email`,
  "auth.haveAccount": `Already have an account?`,
  "auth.mfaCodeLabel": `Authenticator code`,
  "auth.mfaDisable": `Disable 2FA`,
  "auth.mfaDisabledMsg": `Two-factor authentication is now OFF.`,
  "auth.mfaEnable": `Enable 2FA`,
  "auth.mfaEnabledMsg": `Two-factor authentication is now ON for your account.`,
  "auth.mfaPendingWarn": `2FA code still needed to finish signing in.`,
  "auth.mfaPrompt": `This account uses 2FA — enter the code from your authenticator app.`,
  "auth.mfaScanHint": `Scan this QR code with your authenticator app (Google Authenticator, Authy, 1Password…), then enter the 6-digit code it shows.`,
  "auth.mfaSetupTitle": `Set up two-factor authentication`,
  "auth.mfaSubtitle": `Enter the 6-digit code from your authenticator app.`,
  "auth.mfaTitle": `Two-factor authentication`,
  "auth.noAccount": `Don't have an account?`,
  "auth.password": `Password`,
  "auth.passwordHint": `At least 6 characters`,
  "auth.privacy": `Privacy`,
  "auth.privacyNote": `Your email and progress are private — only you can see them.`,
  "auth.resendCode": `Resend code`,
  "auth.security": `Security`,
  "auth.signIn": `Sign in`,
  "auth.signOut": `Sign out`,
  "auth.signUp": `Sign up`,
  "auth.subtitle": `Save your progress across devices. Your data stays private.`,
  "auth.title": `Account`,
  "auth.verify": `Verify`,
  "auth.verifyCodeSubtitle": `We sent a 6-digit code to your email. Enter it below to finish signing up.`,
  "auth.verifyCodeTitle": `Enter your code`,
  "auth.working": `Please wait…`,
  "bookmarks.continueStudying": `Fortsæt med at studere`,
  "bookmarks.empty": `Ingen bogmærker endnu. Tryk på stjernen på ethvert spørgsmål for at gemme det til gennemgang.`,
  "bookmarks.emptyQuestions": `Intet er gemt endnu. Tryk ☆ på et øvelsesspørgsmål.`,
  "bookmarks.emptySections": `Intet er gemt endnu. Tryk på ☆, mens du læser et afsnit.`,
  "bookmarks.remove": `Fjern`,
  "bookmarks.savedForReview": `gemt til gennemgang`,
  "bookmarks.savedQuestions": `Gemte spørgsmål ({n})`,
  "bookmarks.savedSections": `Gemte sektioner ({n})`,
  "bookmarks.search": `Søg bogmærker...`,
  "bookmarks.title": `Bogmærker`,
  "cards.answered": `Besvarede`,
  "cards.bookmarks": `gemt til gennemgang`,
  "cards.bookmarksLabel": `Bogmærker`,
  "cards.continueLearning": `Fortsæt med at lære`,
  "cards.correct": `Korrekt`,
  "cards.dailyGoal": `{done}/{total} spørgsmål i dag`,
  "cards.dailyGoalLabel": `Dagligt mål`,
  "cards.dailyGoalTitle": `Daily goal`,
  "cards.mockExam.subtitle": `Tidsbestemt · 20 spørgsmål`,
  "cards.mockExam.title": `Spoteksamen`,
  "cards.officialInfo.button": `Åbn canada.ca`,
  "cards.officialInfo.subtitle": `Besøg canada.ca for officielle detaljer`,
  "cards.officialInfo.title": `Officielle oplysninger`,
  "cards.progress": `Fremskridt`,
  "cards.progressDetails": `Detaljer`,
  "cards.recentlyStudied": `For nylig studeret`,
  "cards.sections": `Afsnit`,
  "cards.studyAssistant.subtitle": `Spørg hvad som helst om studiematerialet`,
  "cards.studyAssistant.title": `Studieassistent`,
  "cards.todaysRecommendation": `Dagens anbefaling`,
  "cards.verifiedSource.subtext": `Indhold kontrolleret mod officielle kilder. Uafhængig studiehjælp — ikke tilknyttet eller godkendt af Canadas regering eller IRCC.`,
  "cards.verifiedSource.title": `Verificeret kilde`,
  "common.back": `Tilbage`,
  "common.cancel": `Annuller`,
  "common.close": `Luk`,
  "common.continue": `Fortsæt`,
  "common.done": `Færdig`,
  "common.emptyBookmarks": `Intet er gemt endnu`,
  "common.emptyRecentlyStudied": `Intet studeret endnu - vælg et emne for at begynde.`,
  "common.loading": `Indlæser...`,
  "common.next": `Næste`,
  "common.of": `af`,
  "common.previous": `Forrige`,
  "common.retry": `Prøv igen`,
  "common.save": `Gem`,
  "exam.allTopics": `Alle emner`,
  "exam.answeredCount": `{n} svarede`,
  "exam.autosaveNote": `Dine svar gemmes, mens du går, så du mister ikke dine fremskridt ved at lukke appen.`,
  "exam.cancel": `Annuller`,
  "exam.confirm": `Bekræft`,
  "exam.confirmEnd": `{n} spørgsmål er ubesvarede og vil blive markeret som forkerte.`,
  "exam.confirmEndTitle": `Afslutte eksamen?`,
  "exam.endExamEarly": `Afslut eksamen tidligt`,
  "exam.examDisclaimer": `Denne score afspejler kun denne app's prøvespørgsmål.`,
  "exam.finishExam": `Afslut eksamen`,
  "exam.newExam": `Ny eksamen`,
  "exam.noMistakes": `Ingen fejl - perfekt score!`,
  "exam.pastAttempts": `Tidligere forsøg`,
  "exam.questionAriaLabel": `Spørgsmål {n}`,
  "exam.questionCount": `Antal spørgsmål`,
  "exam.questionOf": `Spørgsmål {n} af {total}`,
  "exam.questionPalette": `Spørgsmål`,
  "exam.questionsOption": `{n} spørgsmål`,
  "exam.resultsTitle": `Din score`,
  "exam.reviewMistakes": `Gennemgå dine fejl ({n})`,
  "exam.scoreLine": `{correct} of {total} correct`,
  "exam.seeProgress": `Se fremskridt`,
  "exam.setupDescription": `Dette er en øvelsessimulering bygget ud fra denne app's undersøgelsesspørgsmål. Det er ikke den officielle test og forudsiger ikke dit resultat.`,
  "exam.setupTitle": `Indstil din falske eksamen`,
  "exam.simulationNote": `Øv simulering · ikke officiel`,
  "exam.startExam": `Start eksamen`,
  "exam.timeLeft": `Tid tilbage`,
  "exam.timedLabel": `tidsindstillet`,
  "exam.timedToggle": `Tidsbestemt (90 sekunder pr. spørgsmål)`,
  "exam.title": `Spoteksamen`,
  "exam.topicFilter": `Emne`,
  "exam.untimedLabel": `utidsbestemt`,
  "footer.disclaimer": `Citizen Prep er et uafhængigt studiehjælpemiddel. Ikke tilknyttet eller godkendt af Canadas regering eller IRCC. Det kan ikke garantere et bestået resultat.`,
  "header.appName": `Borgerforberedelse`,
  "header.tagline": `Uafhængigt studieværktøj · Ikke officielt`,
  "hero.sectionsProgress": `{done} of {total} sections · {percent}% complete`,
  "hero.subtitle": `Uafhængigt studieværktøj · Engelsk og fransk · ingen konto nødvendig`,
  "hero.title": `Forbered dig på din statsborgerskabsprøve`,
  "nav.exam": `Eksamen`,
  "nav.home": `Hjem`,
  "nav.practice": `Øv`,
  "nav.progress": `Fremskridt`,
  "nav.topics": `Emner`,
  "practice.allLevels": `Alle niveauer`,
  "practice.allTopics": `Alle emner`,
  "practice.askAiAbout": `Spørg AI om dette spørgsmål`,
  "practice.bookmarkQuestion": `Bogmærke spørgsmål`,
  "practice.bookmarked": `Bogmærket`,
  "practice.checkAnswer": `Tjek svaret`,
  "practice.correct": `Korrekt`,
  "practice.demoContent": `Demo indhold`,
  "practice.difficulty": `Sværhedsgrad`,
  "practice.easy": `Nemt`,
  "practice.explanation": `Forklaring`,
  "practice.filters": `Filtre`,
  "practice.hard": `Hårdt`,
  "practice.incorrect": `Ikke helt`,
  "practice.medium": `Medium`,
  "practice.nextQuestion": `Næste spørgsmål`,
  "practice.questionCounter": `Øv spørgsmål {n} af {total}`,
  "practice.reportIssue": `Rapporter et problem`,
  "practice.title": `Øv`,
  "practice.topicFilter": `Emne`,
  "practice.tryAgain": `Prøv igen`,
  "progress.accuracy": `Nøjagtighed`,
  "progress.clearProgressDesc": `Dette sletter dine svar, fuldførelser, bogmærker og eksamenshistorik fra denne enhed. Det kan ikke fortrydes.`,
  "progress.clearProgressLabel": `Ryd alle studiefremskridt`,
  "progress.confirmClear": `Ja, ryd alt`,
  "progress.dailyGoal": `Dagligt mål`,
  "progress.details": `Detaljer`,
  "progress.examHistory": `Eksamenshistorie`,
  "progress.noExams": `Ingen eksamener taget endnu.`,
  "progress.noWrongAnswers": `Ingen forkerte svar at gennemgå lige nu.`,
  "progress.overview": `Oversigt`,
  "progress.perTopic": `Per emne`,
  "progress.questionsAnswered": `Spørgsmål besvaret`,
  "progress.reset": `Nulstil`,
  "progress.retryTopic": `Prøv dette emne igen`,
  "progress.sectionsDone": `Afsnit afsluttet`,
  "progress.suggestedNext": `Foreslået næste: {topic}`,
  "progress.title": `Fremskridt`,
  "progress.topicCompletion": `Emneafslutning`,
  "report.detailsPlaceholder": `Fortæl os mere (valgfrit)`,
  "report.incorrectAnswer": `Forkert svar`,
  "report.outdatedInfo": `Forældede oplysninger`,
  "report.submit": `Indsend rapport`,
  "report.technicalIssue": `Teknisk problem`,
  "report.thanks": `Tak – rapporter gemmes lokalt på denne enhed.`,
  "report.translationProblem": `Oversættelsesproblem`,
  "report.unclearExplanation": `Forklaring peu claire`,
  "settings.about": `Om denne app`,
  "settings.appInterfaceLanguage": `App interface sprog`,
  "settings.clearProgress": `Klare fremskridt`,
  "settings.clearProgressConfirm": `Er du sikker? Dette vil slette alle dine fremskridt.`,
  "settings.interfaceDescription": `Menuer, knapper og navigation.`,
  "settings.language": `Sprog`,
  "settings.machineNote": `Maskinoversat indhold er ikke blevet kontrolleret af en menneskelig anmelder. Intet her er mærket som gennemgået, medmindre det faktisk er blevet gennemgået.`,
  "settings.machineTranslatedBadge": `Maskinoversat`,
  "settings.manageProgress": `Administrer dine fremskridtsdata`,
  "settings.notAvailable": `Ikke tilgængelig endnu`,
  "settings.officialGuideLink": `Officiel studievejledning`,
  "settings.officialTestLink": `Officiel information om statsborgerskabstest`,
  "settings.privacy": `Privatliv`,
  "settings.privacyText": `Dine svar, bogmærker og indstillinger gemmes kun på denne enhed. Ingen konto er nødvendig. Spørgsmål, du stiller studieassistenten, sendes til en AI-tjeneste for at generere svar.`,
  "settings.reviewedBadge": `Gennemgået`,
  "settings.studyContentLanguage": `Studer indholdssprog`,
  "settings.studyDescription": `Lære tekst og forklaringer. Du kan læse på ét sprog, mens du navigerer på et andet.`,
  "settings.textSize": `Tekststørrelse`,
  "settings.title": `Indstillinger`,
  "topics.askAssistant": `Spørg assistenten om dette afsnit`,
  "topics.bookmarkSection": `Bogmærke sektion`,
  "topics.bookmarkedSection": `Bogmærket`,
  "topics.completed": `Afsluttet`,
  "topics.continueLearningCard": `Fortsæt med at lære`,
  "topics.demoSourceNote": `Oprindeligt prøvespørgsmål — ikke et officielt eksamensspørgsmål`,
  "topics.lastVerified": `Sidst bekræftet {date}`,
  "topics.markComplete": `Markér som fuldført`,
  "topics.markIncomplete": `Markér som ufuldstændig`,
  "topics.minRead": `{n} min læst`,
  "topics.next": `Næste`,
  "topics.openOfficialPage": `Åbn officiel side`,
  "topics.paraphrasedSourceNote": `Omskrevet fra officielt materiale`,
  "topics.practiceTopic": `Øv dette emne`,
  "topics.previous": `Forrige`,
  "topics.reportIssue": `Rapporter et problem`,
  "topics.reviewedOn": `reviewed {date}`,
  "topics.reviewedTranslation": `Gennemgået oversættelse`,
  "topics.section": `Sektion`,
  "topics.sections": `sektioner`,
  "topics.source": `Kilde`,
  "topics.sourcesDescription": `Studieteksten her er omskrevet fra Canadas regerings studievejledning til statsborgerskab og gennemgået på de viste datoer. Praksisspørgsmål undersøges fra den officielle studievejledning.`,
  "topics.sourcesHeading": `Indholdskilder og anmeldelsesdatoer`,
  "topics.studyLanguageLabel": `Studer indholdssprog`,
  "topics.title": `Studieemner`,
  "topics.vocabulary": `Ordforråd`,
};
