// UI strings for 'de' — chunk of strings.generated.ts. DO NOT EDIT BY HAND.
import type { StringKey } from "../strings.generated";

export const de: Record<StringKey, string> = {
  "actions.askAi": `Fragen Sie die KI`,
  "actions.mockExam": `Scheinprüfung`,
  "actions.practice": `Üben`,
  "actions.quickActions": `Quick actions`,
  "actions.study": `Studieren`,
  "assistant.aiEyebrow": `KI-Studienassistent`,
  "assistant.answerLanguage": `Antwortsprache`,
  "assistant.charLimit": `{n} Zeichen übrig`,
  "assistant.checkingMaterial": `Überprüfung des Lernmaterials…`,
  "assistant.clearChat": `Klarer Chat`,
  "assistant.copied": `Kopiert`,
  "assistant.copy": `Kopieren`,
  "assistant.description": `Die Antworten werden von der KI ausschließlich unter Verwendung des Lernmaterials dieser App unter Angabe der Quellen verfasst. KI kann immer noch Fehler machen – wichtige Details finden Sie auf den offiziellen Seiten der kanadischen Regierung. Keine Rechts- oder Einwanderungsberatung.`,
  "assistant.enFrancais": `Auf Französisch`,
  "assistant.error": `Etwas ist schief gelaufen. Bitte versuchen Sie es erneut.`,
  "assistant.fromAppContent": `Aus genehmigten App-Inhalten`,
  "assistant.groundedBadge": `Quellengegründet`,
  "assistant.helpful": `Hilfreich`,
  "assistant.inputPlaceholder": `Stellen Sie eine Frage zur kanadischen Staatsbürgerschaft ...`,
  "assistant.myAppLanguage": `Meine App-Sprache`,
  "assistant.notCovered": `Nicht abgedeckt – siehe offizielle Seite`,
  "assistant.notHelpful": `Nicht hilfreich`,
  "assistant.openAssistant": `Offener Studienassistent`,
  "assistant.openLink": `Assistent öffnen`,
  "assistant.practiceThis": `Üben Sie dies`,
  "assistant.questionAriaLabel": `Deine Frage`,
  "assistant.reportIncorrect": `Melden Sie eine falsche Antwort`,
  "assistant.send": `Senden`,
  "assistant.showSource": `Quelle anzeigen`,
  "assistant.simpleEnglish": `Einfaches Englisch`,
  "assistant.source": `Quelle`,
  "assistant.starter1": `Was sind die drei Teile des Parlaments?`,
  "assistant.starter2": `Erklären Sie die Charta einfach`,
  "assistant.starter3": `Wer vertritt den König in Kanada?`,
  "assistant.starter4": `Was deckt der Wissenstest ab?`,
  "assistant.suggestedQuestions": `Vorgeschlagene Fragen`,
  "assistant.thinking": `Denken…`,
  "assistant.title": `Studienassistent`,
  "assistant.tryAgain": `Versuchen Sie es erneut`,
  "assistant.tryAsking": `Versuchen Sie zu fragen:`,
  "assistant.vocabularyLabel": `Wortschatz:`,
  "assistant.whyItMatters": `Warum es für den Test wichtig ist`,
  "bookmarks.continueStudying": `Studieren Sie weiter`,
  "bookmarks.empty": `Noch keine Lesezeichen. Tippen Sie bei einer Frage auf den Stern, um sie zur Überprüfung zu speichern.`,
  "bookmarks.emptyQuestions": `Noch nichts gespeichert. Tippen Sie bei einer Übungsfrage auf ☆.`,
  "bookmarks.emptySections": `Noch nichts gespeichert. Tippen Sie beim Lesen eines Abschnitts auf ☆.`,
  "bookmarks.remove": `Entfernen`,
  "bookmarks.savedForReview": `zur Überprüfung gespeichert`,
  "bookmarks.savedQuestions": `Gespeicherte Fragen ({n})`,
  "bookmarks.savedSections": `Gespeicherte Abschnitte ({n})`,
  "bookmarks.search": `Lesezeichen durchsuchen…`,
  "bookmarks.title": `Lesezeichen`,
  "cards.answered": `Beantwortet`,
  "cards.bookmarks": `zur Überprüfung gespeichert`,
  "cards.bookmarksLabel": `Lesezeichen`,
  "cards.continueLearning": `Lernen Sie weiter`,
  "cards.correct": `Richtig`,
  "cards.dailyGoal": `{done}/{total} Fragen heute`,
  "cards.dailyGoalLabel": `Tagesziel`,
  "cards.dailyGoalTitle": `Daily goal`,
  "cards.mockExam.subtitle": `Zeitgesteuert · 20 Fragen`,
  "cards.mockExam.title": `Scheinprüfung`,
  "cards.officialInfo.button": `Öffnen Sie canada.ca`,
  "cards.officialInfo.subtitle": `Offizielle Details finden Sie auf canada.ca`,
  "cards.officialInfo.title": `Offizielle Informationen`,
  "cards.progress": `Fortschritt`,
  "cards.progressDetails": `Einzelheiten`,
  "cards.recentlyStudied": `Kürzlich untersucht`,
  "cards.sections": `Abschnitte`,
  "cards.studyAssistant.subtitle": `Fragen Sie alles zum Lernmaterial`,
  "cards.studyAssistant.title": `Studienassistent`,
  "cards.todaysRecommendation": `Die heutige Empfehlung`,
  "cards.verifiedSource.subtext": `Inhalt anhand offizieller Quellen überprüft. Unabhängige Studienhilfe – nicht mit der kanadischen Regierung oder dem IRCC verbunden oder von diesen unterstützt.`,
  "cards.verifiedSource.title": `Verifizierte Quelle`,
  "common.back": `Zurück`,
  "common.cancel": `Abbrechen`,
  "common.close": `Schließen`,
  "common.continue": `Weiter`,
  "common.done": `Fertig`,
  "common.emptyBookmarks": `Noch nichts gespeichert`,
  "common.emptyRecentlyStudied": `Noch nichts untersucht – wählen Sie zunächst ein Thema aus.`,
  "common.loading": `Laden…`,
  "common.next": `Als nächstes`,
  "common.of": `von`,
  "common.previous": `Zurück`,
  "common.retry": `Versuchen Sie es noch einmal`,
  "common.save": `Speichern`,
  "exam.allTopics": `Alle Themen`,
  "exam.answeredCount": `{n} antwortete`,
  "exam.autosaveNote": `Ihre Antworten werden gespeichert, sodass Ihr Fortschritt beim Schließen der App nicht verloren geht.`,
  "exam.cancel": `Abbrechen`,
  "exam.confirm": `Bestätigen`,
  "exam.confirmEnd": `{n} Fragen sind unbeantwortet und werden als falsch markiert.`,
  "exam.confirmEndTitle": `Prüfung beenden?`,
  "exam.endExamEarly": `Beenden Sie die Prüfung vorzeitig`,
  "exam.examDisclaimer": `Diese Punktzahl spiegelt nur die Beispielfragen dieser App wider.`,
  "exam.finishExam": `Prüfung beenden`,
  "exam.newExam": `Neue Prüfung`,
  "exam.noMistakes": `Keine Fehler – perfekte Punktzahl!`,
  "exam.pastAttempts": `Vergangene Versuche`,
  "exam.questionAriaLabel": `Frage {n}`,
  "exam.questionCount": `Anzahl der Fragen`,
  "exam.questionOf": `Frage {n} von {total}`,
  "exam.questionPalette": `Fragen`,
  "exam.questionsOption": `{n} Fragen`,
  "exam.resultsTitle": `Ihr Punktestand`,
  "exam.reviewMistakes": `Überprüfen Sie Ihre Fehler ({n})`,
  "exam.scoreLine": `{correct} von {total} richtig`,
  "exam.seeProgress": `Sehen Sie sich den Fortschritt an`,
  "exam.setupDescription": `Dies ist eine Übungssimulation, die aus den Lernfragen dieser App erstellt wurde. Es handelt sich nicht um den offiziellen Test, der Ihr Ergebnis nicht vorhersagt.`,
  "exam.setupTitle": `Richten Sie Ihre Probeprüfung ein`,
  "exam.simulationNote": `Übungssimulation · nicht offiziell`,
  "exam.startExam": `Prüfung starten`,
  "exam.timeLeft": `Noch Zeit`,
  "exam.timedLabel": `zeitgesteuert`,
  "exam.timedToggle": `Zeitgesteuert (90 Sekunden pro Frage)`,
  "exam.title": `Scheinprüfung`,
  "exam.topicFilter": `Thema`,
  "exam.untimedLabel": `ohne Zeitangabe`,
  "footer.disclaimer": `Citizen Prep ist eine unabhängige Lernhilfe. Nicht mit der kanadischen Regierung oder dem IRCC verbunden oder von diesen unterstützt. Es kann kein bestandenes Ergebnis garantiert werden.`,
  "header.appName": `Bürgervorbereitung`,
  "header.tagline": `Unabhängiges Lerntool · Nicht offiziell`,
  "hero.sectionsProgress": `{done} of {total} sections · {percent}% complete`,
  "hero.subtitle": `Unabhängiges Lerntool · Englisch und Französisch · kein Konto erforderlich`,
  "hero.title": `Bereiten Sie sich auf Ihren Einbürgerungstest vor`,
  "nav.exam": `Prüfung`,
  "nav.home": `Zuhause`,
  "nav.practice": `Üben`,
  "nav.progress": `Fortschritt`,
  "nav.topics": `Themen`,
  "practice.allLevels": `Alle Ebenen`,
  "practice.allTopics": `Alle Themen`,
  "practice.askAiAbout": `Stellen Sie AI diese Frage`,
  "practice.bookmarkQuestion": `Lesezeichenfrage`,
  "practice.bookmarked": `Mit Lesezeichen versehen`,
  "practice.checkAnswer": `Antwort prüfen`,
  "practice.correct": `Richtig`,
  "practice.demoContent": `Demoinhalt`,
  "practice.difficulty": `Schwierigkeit`,
  "practice.easy": `Einfach`,
  "practice.explanation": `Erklärung`,
  "practice.filters": `Filter`,
  "practice.hard": `Schwer`,
  "practice.incorrect": `Nicht ganz`,
  "practice.medium": `Mittel`,
  "practice.nextQuestion": `Nächste Frage`,
  "practice.questionCounter": `Übungsfrage {n} von {total}`,
  "practice.reportIssue": `Melden Sie ein Problem`,
  "practice.title": `Üben`,
  "practice.topicFilter": `Thema`,
  "practice.tryAgain": `Versuchen Sie es erneut`,
  "progress.accuracy": `Genauigkeit`,
  "progress.clearProgressDesc": `Dadurch werden Ihre Antworten, Abschlüsse, Lesezeichen und der Prüfungsverlauf von diesem Gerät gelöscht. Es kann nicht rückgängig gemacht werden.`,
  "progress.clearProgressLabel": `Löschen Sie alle Lernfortschritte`,
  "progress.confirmClear": `Ja, alles löschen`,
  "progress.dailyGoal": `Tagesziel`,
  "progress.details": `Einzelheiten`,
  "progress.examHistory": `Prüfungsverlauf`,
  "progress.noExams": `Noch keine Prüfungen abgelegt.`,
  "progress.noWrongAnswers": `Im Moment gibt es keine falschen Antworten zur Überprüfung.`,
  "progress.overview": `Übersicht`,
  "progress.perTopic": `Pro Thema`,
  "progress.questionsAnswered": `Fragen beantwortet`,
  "progress.reset": `Zurücksetzen`,
  "progress.retryTopic": `Versuchen Sie dieses Thema noch einmal`,
  "progress.sectionsDone": `Abschnitte abgeschlossen`,
  "progress.suggestedNext": `Als nächstes vorgeschlagen: {topic}`,
  "progress.title": `Fortschritt`,
  "progress.topicCompletion": `Themenabschluss`,
  "report.detailsPlaceholder": `Erzählen Sie uns mehr (optional)`,
  "report.incorrectAnswer": `Falsche Antwort`,
  "report.outdatedInfo": `Veraltete Informationen`,
  "report.submit": `Bericht absenden`,
  "report.technicalIssue": `Technisches Problem`,
  "report.thanks": `Vielen Dank – Berichte werden lokal auf diesem Gerät gespeichert.`,
  "report.translationProblem": `Übersetzungsproblem`,
  "report.unclearExplanation": `Erklärung peu claire`,
  "settings.about": `Über diese App`,
  "settings.appInterfaceLanguage": `Sprache der App-Oberfläche`,
  "settings.clearProgress": `Klarer Fortschritt`,
  "settings.clearProgressConfirm": `Bist du sicher? Dadurch werden alle Ihre Fortschritte gelöscht.`,
  "settings.interfaceDescription": `Menüs, Schaltflächen und Navigation.`,
  "settings.language": `Sprache`,
  "settings.machineNote": `Maschinell übersetzte Inhalte wurden nicht von einem menschlichen Prüfer überprüft. Hier wird nichts als überprüft gekennzeichnet, es sei denn, es wurde tatsächlich überprüft.`,
  "settings.machineTranslatedBadge": `Maschinell übersetzt`,
  "settings.manageProgress": `Verwalten Sie Ihre Fortschrittsdaten`,
  "settings.notAvailable": `Noch nicht verfügbar`,
  "settings.officialGuideLink": `Offizieller Studienführer`,
  "settings.officialTestLink": `Offizielle Informationen zum Einbürgerungstest`,
  "settings.privacy": `Privatsphäre`,
  "settings.privacyText": `Ihre Antworten, Lesezeichen und Einstellungen werden nur auf diesem Gerät gespeichert. Es ist kein Konto erforderlich. Fragen, die Sie dem Studienassistenten stellen, werden an einen KI-Dienst gesendet, um Antworten zu generieren.`,
  "settings.reviewedBadge": `Bewertet`,
  "settings.studyContentLanguage": `Studieren Sie die Inhaltssprache`,
  "settings.studyDescription": `Lerntexte und Erklärungen. Sie können in einer Sprache lesen und gleichzeitig in einer anderen navigieren.`,
  "settings.textSize": `Textgröße`,
  "settings.title": `Einstellungen`,
  "topics.askAssistant": `Fragen Sie den Assistenten nach diesem Abschnitt`,
  "topics.bookmarkSection": `Abschnitt „Lesezeichen“.`,
  "topics.bookmarkedSection": `Mit Lesezeichen versehen`,
  "topics.completed": `Abgeschlossen`,
  "topics.continueLearningCard": `Lernen Sie weiter`,
  "topics.demoSourceNote": `Ursprüngliche Beispielfrage – keine offizielle Prüfungsfrage`,
  "topics.lastVerified": `Zuletzt überprüft am {date}`,
  "topics.markComplete": `Als abgeschlossen markieren`,
  "topics.markIncomplete": `Als unvollständig markieren`,
  "topics.minRead": `{n} Min. gelesen`,
  "topics.next": `Als nächstes`,
  "topics.openOfficialPage": `Offizielle Seite öffnen`,
  "topics.paraphrasedSourceNote": `Paraphrasiert aus offiziellem Material`,
  "topics.practiceTopic": `Üben Sie dieses Thema`,
  "topics.previous": `Zurück`,
  "topics.reportIssue": `Melden Sie ein Problem`,
  "topics.reviewedOn": `reviewed {date}`,
  "topics.reviewedTranslation": `Überprüfte Übersetzung`,
  "topics.section": `Abschnitt`,
  "topics.sections": `Abschnitte`,
  "topics.source": `Quelle`,
  "topics.sourcesDescription": `Der Studientext hier ist eine Paraphrase aus dem Studienführer zur Staatsbürgerschaft der kanadischen Regierung und wurde an den angegebenen Daten überprüft. Übungsfragen werden anhand des offiziellen Studienführers recherchiert.`,
  "topics.sourcesHeading": `Inhaltsquellen und Überprüfungsdaten`,
  "topics.studyLanguageLabel": `Studieren Sie die Inhaltssprache`,
  "topics.title": `Studienthemen`,
  "topics.vocabulary": `Wortschatz`,
};
