// UI strings for 'el' — chunk of strings.generated.ts. DO NOT EDIT BY HAND.
import type { StringKey } from "../strings.generated";

export const el: Record<StringKey, string> = {
  "actions.askAi": `Ρωτήστε το AI`,
  "actions.mockExam": `Παροδική εξέταση`,
  "actions.practice": `Εξάσκηση`,
  "actions.quickActions": `Quick actions`,
  "actions.study": `Μελέτη`,
  "assistant.aiEyebrow": `Βοηθός μελέτης AI`,
  "assistant.answerLanguage": `Γλώσσα απαντήσεων`,
  "assistant.charLimit": `Απομένουν {n} χαρακτήρες`,
  "assistant.checkingMaterial": `Έλεγχος του υλικού μελέτης…`,
  "assistant.clearChat": `Εκκαθάριση συνομιλίας`,
  "assistant.copied": `Αντιγράφηκε`,
  "assistant.copy": `Αντιγραφή`,
  "assistant.description": `Οι απαντήσεις γράφονται από την τεχνητή νοημοσύνη χρησιμοποιώντας μόνο το υλικό μελέτης αυτής της εφαρμογής, με τις πηγές να εμφανίζονται. Η τεχνητή νοημοσύνη μπορεί ακόμα να κάνει λάθη — ελέγξτε σημαντικές λεπτομέρειες στις επίσημες σελίδες της κυβέρνησης του Καναδά. Όχι νομικές συμβουλές ή συμβουλές για τη μετανάστευση.`,
  "assistant.enFrancais": `Γαλλικά`,
  "assistant.error": `Κάτι πήγε στραβά. Δοκιμάστε ξανά.`,
  "assistant.fromAppContent": `Από εγκεκριμένο περιεχόμενο εφαρμογής`,
  "assistant.groundedBadge": `Με βάση την πηγή`,
  "assistant.helpful": `Χρήσιμο`,
  "assistant.inputPlaceholder": `Κάντε μια ερώτηση σχετικά με την καναδική υπηκοότητα…`,
  "assistant.myAppLanguage": `Η γλώσσα της εφαρμογής μου`,
  "assistant.notCovered": `Δεν καλύπτεται — δείτε την επίσημη σελίδα`,
  "assistant.notHelpful": `Δεν είναι χρήσιμο`,
  "assistant.openAssistant": `Βοηθός ανοιχτής μελέτης`,
  "assistant.openLink": `Ανοιχτός βοηθός`,
  "assistant.practiceThis": `Εξάσκηση σε αυτό`,
  "assistant.questionAriaLabel": `Η ερώτησή σας`,
  "assistant.reportIncorrect": `Αναφέρετε μια λανθασμένη απάντηση`,
  "assistant.send": `Αποστολή`,
  "assistant.showSource": `Εμφάνιση πηγής`,
  "assistant.simpleEnglish": `Απλά αγγλικά`,
  "assistant.source": `Πηγή`,
  "assistant.starter1": `Ποια είναι τα τρία μέρη της Βουλής;`,
  "assistant.starter2": `Εξηγήστε απλά τον Χάρτη`,
  "assistant.starter3": `Ποιος εκπροσωπεί τον Βασιλιά στον Καναδά;`,
  "assistant.starter4": `Τι καλύπτει το τεστ γνώσεων;`,
  "assistant.suggestedQuestions": `Προτεινόμενες ερωτήσεις`,
  "assistant.thinking": `Σκέψη…`,
  "assistant.title": `Βοηθός σπουδών`,
  "assistant.tryAgain": `Προσπαθήστε ξανά`,
  "assistant.tryAsking": `Δοκιμάστε να ρωτήσετε:`,
  "assistant.vocabularyLabel": `Λεξιλόγιο:`,
  "assistant.whyItMatters": `Γιατί έχει σημασία για το τεστ`,
  "bookmarks.continueStudying": `Συνέχισε τη μελέτη`,
  "bookmarks.empty": `Δεν υπάρχουν ακόμη σελιδοδείκτες. Πατήστε το αστέρι σε οποιαδήποτε ερώτηση για να την αποθηκεύσετε για έλεγχο.`,
  "bookmarks.emptyQuestions": `Δεν έχει αποθηκευτεί τίποτα ακόμα. Πατήστε ☆ σε μια ερώτηση εξάσκησης.`,
  "bookmarks.emptySections": `Δεν έχει αποθηκευτεί τίποτα ακόμα. Πατήστε ☆ ενώ διαβάζετε μια ενότητα.`,
  "bookmarks.remove": `Αφαίρεση`,
  "bookmarks.savedForReview": `αποθηκεύτηκε για έλεγχο`,
  "bookmarks.savedQuestions": `Αποθηκευμένες ερωτήσεις ({n})`,
  "bookmarks.savedSections": `Αποθηκευμένες ενότητες ({n})`,
  "bookmarks.search": `Αναζήτηση σελιδοδεικτών…`,
  "bookmarks.title": `Σελιδοδείκτες`,
  "cards.answered": `Απάντησε`,
  "cards.bookmarks": `αποθηκεύτηκε για έλεγχο`,
  "cards.bookmarksLabel": `Σελιδοδείκτες`,
  "cards.continueLearning": `Συνεχίστε να μαθαίνετε`,
  "cards.correct": `Σωστό`,
  "cards.dailyGoal": `{done}/{total} ερωτήσεις σήμερα`,
  "cards.dailyGoalLabel": `Καθημερινός στόχος`,
  "cards.dailyGoalTitle": `Daily goal`,
  "cards.mockExam.subtitle": `Χρονοδιάγραμμα · 20 ερωτήσεις`,
  "cards.mockExam.title": `Παροδική εξέταση`,
  "cards.officialInfo.button": `Ανοίξτε το canada.ca`,
  "cards.officialInfo.subtitle": `Επισκεφτείτε το canada.ca για επίσημες λεπτομέρειες`,
  "cards.officialInfo.title": `Επίσημες πληροφορίες`,
  "cards.progress": `Πρόοδος`,
  "cards.progressDetails": `Λεπτομέρειες`,
  "cards.recentlyStudied": `Πρόσφατα μελετημένο`,
  "cards.sections": `Ενότητες`,
  "cards.studyAssistant.subtitle": `Ρωτήστε οτιδήποτε σχετικά με το υλικό μελέτης`,
  "cards.studyAssistant.title": `Βοηθός σπουδών`,
  "cards.todaysRecommendation": `Η σημερινή σύσταση`,
  "cards.verifiedSource.subtext": `Το περιεχόμενο ελέγχεται από επίσημες πηγές. Ανεξάρτητο βοήθημα σπουδών — δεν συνδέεται ούτε εγκρίνεται από την κυβέρνηση του Καναδά ή το IRCC.`,
  "cards.verifiedSource.title": `Επαληθευμένη πηγή`,
  "common.back": `Πίσω`,
  "common.cancel": `Ακύρωση`,
  "common.close": `Κλείσιμο`,
  "common.continue": `Συνέχεια`,
  "common.done": `Έγινε`,
  "common.emptyBookmarks": `Δεν έχει αποθηκευτεί τίποτα ακόμα`,
  "common.emptyRecentlyStudied": `Τίποτα δεν έχει μελετηθεί ακόμα - επιλέξτε ένα θέμα για να ξεκινήσετε.`,
  "common.loading": `Φόρτωση…`,
  "common.next": `Επόμενο`,
  "common.of": `του`,
  "common.previous": `Προηγούμενο`,
  "common.retry": `Επανάληψη`,
  "common.save": `Αποθήκευση`,
  "exam.allTopics": `Όλα τα θέματα`,
  "exam.answeredCount": `Ο {n} απάντησε`,
  "exam.autosaveNote": `Οι απαντήσεις σας αποθηκεύονται καθώς πηγαίνετε, οπότε το κλείσιμο της εφαρμογής δεν θα χάσει την πρόοδό σας.`,
  "exam.cancel": `Ακύρωση`,
  "exam.confirm": `Επιβεβαίωση`,
  "exam.confirmEnd": `{n} ερωτήσεις είναι αναπάντητα και θα επισημανθούν ως λανθασμένες.`,
  "exam.confirmEndTitle": `Τέλος εξέτασης;`,
  "exam.endExamEarly": `Τελειώστε νωρίς τις εξετάσεις`,
  "exam.examDisclaimer": `Αυτή η βαθμολογία αντικατοπτρίζει μόνο δείγματα ερωτήσεων αυτής της εφαρμογής.`,
  "exam.finishExam": `Τελειώστε τις εξετάσεις`,
  "exam.newExam": `Νέα εξέταση`,
  "exam.noMistakes": `Χωρίς λάθη - τέλειο σκορ!`,
  "exam.pastAttempts": `Προηγούμενες προσπάθειες`,
  "exam.questionAriaLabel": `Ερώτηση {n}`,
  "exam.questionCount": `Αριθμός ερωτήσεων`,
  "exam.questionOf": `Ερώτηση {n} από {total}`,
  "exam.questionPalette": `Ερωτήσεις`,
  "exam.questionsOption": `{n} ερωτήσεις`,
  "exam.resultsTitle": `Η βαθμολογία σας`,
  "exam.reviewMistakes": `Ελέγξτε τα λάθη σας ({n})`,
  "exam.scoreLine": `{correct} από {total} σωστά`,
  "exam.seeProgress": `Δείτε την πρόοδο`,
  "exam.setupDescription": `Αυτή είναι μια προσομοίωση πρακτικής που βασίζεται στις ερωτήσεις μελέτης αυτής της εφαρμογής. Δεν είναι το επίσημο τεστ και δεν προβλέπει το αποτέλεσμά σας.`,
  "exam.setupTitle": `Ρυθμίστε την εικονική σας εξέταση`,
  "exam.simulationNote": `Εξάσκηση προσομοίωσης · μη επίσημο`,
  "exam.startExam": `Έναρξη εξέτασης`,
  "exam.timeLeft": `Χρόνος που απομένει`,
  "exam.timedLabel": `χρονομετρημένη`,
  "exam.timedToggle": `Χρονοδιάγραμμα (90 δευτερόλεπτα ανά ερώτηση)`,
  "exam.title": `Παροδική εξέταση`,
  "exam.topicFilter": `Θέμα`,
  "exam.untimedLabel": `άχρονο`,
  "footer.disclaimer": `Το Citizen Prep είναι ένα ανεξάρτητο βοήθημα μελέτης. Δεν συνδέεται ούτε υποστηρίζεται από την Κυβέρνηση του Καναδά ή το IRCC. Δεν μπορεί να εγγυηθεί ένα περαστικό αποτέλεσμα.`,
  "header.appName": `Πολίτης Προετ`,
  "header.tagline": `Ανεξάρτητο εργαλείο μελέτης · Μη επίσημο`,
  "hero.sectionsProgress": `{done} of {total} sections · {percent}% complete`,
  "hero.subtitle": `Ανεξάρτητο εργαλείο μελέτης · Αγγλικά & Γαλλικά · δεν απαιτείται λογαριασμός`,
  "hero.title": `Προετοιμαστείτε για το τεστ υπηκοότητας`,
  "nav.exam": `Εξεταστική`,
  "nav.home": `Σπίτι`,
  "nav.practice": `Εξάσκηση`,
  "nav.progress": `Πρόοδος`,
  "nav.topics": `Θέματα`,
  "practice.allLevels": `Όλα τα επίπεδα`,
  "practice.allTopics": `Όλα τα θέματα`,
  "practice.askAiAbout": `Ρωτήστε AI για αυτήν την ερώτηση`,
  "practice.bookmarkQuestion": `Ερώτηση σελιδοδείκτη`,
  "practice.bookmarked": `Σελιδοδείκτη`,
  "practice.checkAnswer": `Ελέγξτε την απάντηση`,
  "practice.correct": `Σωστό`,
  "practice.demoContent": `Περιεχόμενο επίδειξης`,
  "practice.difficulty": `Δυσκολία`,
  "practice.easy": `Εύκολο`,
  "practice.explanation": `Εξήγηση`,
  "practice.filters": `Φίλτρα`,
  "practice.hard": `Σκληρό`,
  "practice.incorrect": `Όχι ακριβώς`,
  "practice.medium": `Μεσαίο`,
  "practice.nextQuestion": `Επόμενη ερώτηση`,
  "practice.questionCounter": `Ερώτηση εξάσκησης {n} από {total}`,
  "practice.reportIssue": `Αναφέρετε ένα πρόβλημα`,
  "practice.title": `Εξάσκηση`,
  "practice.topicFilter": `Θέμα`,
  "practice.tryAgain": `Προσπαθήστε ξανά`,
  "progress.accuracy": `Ακρίβεια`,
  "progress.clearProgressDesc": `Αυτό διαγράφει τις απαντήσεις, τις ολοκληρώσεις, τους σελιδοδείκτες και το ιστορικό των εξετάσεων από αυτήν τη συσκευή. Δεν μπορεί να αναιρεθεί.`,
  "progress.clearProgressLabel": `Διαγράψτε όλη την πρόοδο της μελέτης`,
  "progress.confirmClear": `Ναι, ξεκαθάρισε τα πάντα`,
  "progress.dailyGoal": `Καθημερινός στόχος`,
  "progress.details": `Λεπτομέρειες`,
  "progress.examHistory": `Ιστορικό εξετάσεων`,
  "progress.noExams": `Δεν έχουν γίνει ακόμα εξετάσεις.`,
  "progress.noWrongAnswers": `Δεν υπάρχουν εσφαλμένες απαντήσεις προς αναθεώρηση αυτήν τη στιγμή.`,
  "progress.overview": `Επισκόπηση`,
  "progress.perTopic": `Ανά θέμα`,
  "progress.questionsAnswered": `Απαντήθηκαν ερωτήσεις`,
  "progress.reset": `Επαναφορά`,
  "progress.retryTopic": `Δοκιμάστε ξανά αυτό το θέμα`,
  "progress.sectionsDone": `Ολοκληρώθηκαν οι ενότητες`,
  "progress.suggestedNext": `Προτείνεται επόμενο: {topic}`,
  "progress.title": `Πρόοδος`,
  "progress.topicCompletion": `Συμπλήρωση θέματος`,
  "report.detailsPlaceholder": `Πείτε μας περισσότερα (προαιρετικά)`,
  "report.incorrectAnswer": `Λανθασμένη απάντηση`,
  "report.outdatedInfo": `Ξεπερασμένες πληροφορίες`,
  "report.submit": `Υποβολή αναφοράς`,
  "report.technicalIssue": `Τεχνικό θέμα`,
  "report.thanks": `Ευχαριστώ — οι αναφορές αποθηκεύονται τοπικά σε αυτήν τη συσκευή.`,
  "report.translationProblem": `Πρόβλημα μετάφρασης`,
  "report.unclearExplanation": `Εξήγηση peu claire`,
  "settings.about": `Σχετικά με αυτήν την εφαρμογή`,
  "settings.appInterfaceLanguage": `Γλώσσα διεπαφής εφαρμογής`,
  "settings.clearProgress": `Σαφής πρόοδος`,
  "settings.clearProgressConfirm": `Είσαι σίγουρος; Αυτό θα διαγράψει όλη την πρόοδό σας.`,
  "settings.interfaceDescription": `Μενού, κουμπιά και πλοήγηση.`,
  "settings.language": `Γλώσσα`,
  "settings.machineNote": `Το μηχάνημα μεταφρασμένο περιεχόμενο δεν έχει ελεγχθεί από ανθρώπινο κριτή. Τίποτα εδώ δεν χαρακτηρίζεται ως αναθεωρημένο εκτός εάν έχει πραγματικά ελεγχθεί.`,
  "settings.machineTranslatedBadge": `Μηχανική μετάφραση`,
  "settings.manageProgress": `Διαχειριστείτε τα δεδομένα προόδου σας`,
  "settings.notAvailable": `Δεν είναι ακόμη διαθέσιμο`,
  "settings.officialGuideLink": `Επίσημος οδηγός σπουδών`,
  "settings.officialTestLink": `Πληροφορίες για τις επίσημες εξετάσεις υπηκοότητας`,
  "settings.privacy": `Απόρρητο`,
  "settings.privacyText": `Οι απαντήσεις, οι σελιδοδείκτες και οι ρυθμίσεις σας αποθηκεύονται μόνο σε αυτήν τη συσκευή. Δεν απαιτείται λογαριασμός. Οι ερωτήσεις που κάνετε στον βοηθό μελέτης αποστέλλονται σε μια υπηρεσία τεχνητής νοημοσύνης για τη δημιουργία απαντήσεων.`,
  "settings.reviewedBadge": `Αξιολογήθηκε`,
  "settings.studyContentLanguage": `Μελέτη γλώσσας περιεχομένου`,
  "settings.studyDescription": `Μαθησιακό κείμενο και επεξηγήσεις. Μπορείτε να διαβάσετε σε μια γλώσσα ενώ πλοηγείστε σε μια άλλη.`,
  "settings.textSize": `Μέγεθος κειμένου`,
  "settings.title": `Ρυθμίσεις`,
  "topics.askAssistant": `Ρωτήστε τον βοηθό για αυτήν την ενότητα`,
  "topics.bookmarkSection": `Ενότητα σελιδοδεικτών`,
  "topics.bookmarkedSection": `Σελιδοδείκτη`,
  "topics.completed": `Ολοκληρώθηκε`,
  "topics.continueLearningCard": `Συνεχίστε να μαθαίνετε`,
  "topics.demoSourceNote": `Πρωτότυπο δείγμα ερώτησης — όχι επίσημη ερώτηση εξέτασης`,
  "topics.lastVerified": `Τελευταία επαλήθευση {date}`,
  "topics.markComplete": `Επισήμανση ως ολοκληρωμένου`,
  "topics.markIncomplete": `Επισήμανση ως μη ολοκληρωμένη`,
  "topics.minRead": `{n} λεπτά ανάγνωσης`,
  "topics.next": `Επόμενο`,
  "topics.openOfficialPage": `Ανοίξτε την επίσημη σελίδα`,
  "topics.paraphrasedSourceNote": `Παράφραση από επίσημο υλικό`,
  "topics.practiceTopic": `Εξάσκηση σε αυτό το θέμα`,
  "topics.previous": `Προηγούμενο`,
  "topics.reportIssue": `Αναφέρετε ένα πρόβλημα`,
  "topics.reviewedOn": `reviewed {date}`,
  "topics.reviewedTranslation": `Αναθεωρημένη μετάφραση`,
  "topics.section": `Ενότητα`,
  "topics.sections": `τμήματα`,
  "topics.source": `Πηγή`,
  "topics.sourcesDescription": `Το κείμενο της μελέτης εδώ παραφράζεται από τον οδηγό μελέτης ιθαγένειας της κυβέρνησης του Καναδά και αναθεωρείται στις εμφανιζόμενες ημερομηνίες. Οι ερωτήσεις εξάσκησης ερευνώνται από τον επίσημο οδηγό μελέτης.`,
  "topics.sourcesHeading": `Πηγές περιεχομένου και ημερομηνίες αναθεώρησης`,
  "topics.studyLanguageLabel": `Μελέτη γλώσσας περιεχομένου`,
  "topics.title": `Θέματα μελέτης`,
  "topics.vocabulary": `Λεξιλόγιο`,
};
