// UI strings for 'en' — chunk of strings.generated.ts. DO NOT EDIT BY HAND.
import type { StringKey } from "../strings.generated";

export const en: Record<StringKey, string> = {
  "actions.askAi": `Ask AI`,
  "actions.mockExam": `Mock exam`,
  "actions.practice": `Practice`,
  "actions.quickActions": `Quick actions`,
  "actions.study": `Study`,
  "assistant.aiEyebrow": `AI study assistant`,
  "assistant.answerLanguage": `Answer language`,
  "assistant.charLimit": `{n} characters left`,
  "assistant.checkingMaterial": `Checking the study material…`,
  "assistant.clearChat": `Clear chat`,
  "assistant.copied": `Copied`,
  "assistant.copy": `Copy`,
  "assistant.description": `Answers are written by AI using only this app's study material, with sources shown. AI can still make mistakes — check important details on the official Government of Canada pages. Not legal or immigration advice.`,
  "assistant.enFrancais": `En français`,
  "assistant.error": `Something went wrong. Please try again.`,
  "assistant.fromAppContent": `From approved app content`,
  "assistant.groundedBadge": `Source-grounded`,
  "assistant.helpful": `Helpful`,
  "assistant.inputPlaceholder": `Ask a question about Canadian citizenship…`,
  "assistant.myAppLanguage": `My app language`,
  "assistant.notCovered": `Not covered — see official page`,
  "assistant.notHelpful": `Not helpful`,
  "assistant.openAssistant": `Open study assistant`,
  "assistant.openLink": `Open assistant`,
  "assistant.practiceThis": `Practice this`,
  "assistant.questionAriaLabel": `Your question`,
  "assistant.reportIncorrect": `Report an incorrect answer`,
  "assistant.send": `Send`,
  "assistant.showSource": `Show source`,
  "assistant.simpleEnglish": `Simple English`,
  "assistant.source": `Source`,
  "assistant.starter1": `What are the three parts of Parliament?`,
  "assistant.starter2": `Explain the Charter simply`,
  "assistant.starter3": `Who represents the King in Canada?`,
  "assistant.starter4": `What does the knowledge test cover?`,
  "assistant.suggestedQuestions": `Suggested questions`,
  "assistant.thinking": `Thinking…`,
  "assistant.title": `Study assistant`,
  "assistant.tryAgain": `Try again`,
  "assistant.tryAsking": `Try asking:`,
  "assistant.vocabularyLabel": `Vocabulary:`,
  "assistant.whyItMatters": `Why it matters for the test`,
  "bookmarks.continueStudying": `Continue studying`,
  "bookmarks.empty": `No bookmarks yet. Tap the star on any question to save it for review.`,
  "bookmarks.emptyQuestions": `Nothing saved yet. Tap ☆ on a practice question.`,
  "bookmarks.emptySections": `Nothing saved yet. Tap ☆ while reading a section.`,
  "bookmarks.remove": `Remove`,
  "bookmarks.savedForReview": `saved for review`,
  "bookmarks.savedQuestions": `Saved questions ({n})`,
  "bookmarks.savedSections": `Saved sections ({n})`,
  "bookmarks.search": `Search bookmarks…`,
  "bookmarks.title": `Bookmarks`,
  "cards.answered": `Answered`,
  "cards.bookmarks": `saved for review`,
  "cards.bookmarksLabel": `Bookmarks`,
  "cards.continueLearning": `Continue learning`,
  "cards.correct": `Correct`,
  "cards.dailyGoal": `{done}/{total} questions today`,
  "cards.dailyGoalLabel": `Daily goal`,
  "cards.dailyGoalTitle": `Daily goal`,
  "cards.mockExam.subtitle": `Timed · 20 questions`,
  "cards.mockExam.title": `Mock exam`,
  "cards.officialInfo.button": `Open canada.ca`,
  "cards.officialInfo.subtitle": `Visit canada.ca for official details`,
  "cards.officialInfo.title": `Official information`,
  "cards.progress": `Progress`,
  "cards.progressDetails": `Details`,
  "cards.recentlyStudied": `Recently studied`,
  "cards.sections": `Sections`,
  "cards.studyAssistant.subtitle": `Ask anything about the study material`,
  "cards.studyAssistant.title": `Study assistant`,
  "cards.todaysRecommendation": `Today's recommendation`,
  "cards.verifiedSource.subtext": `Content checked against official sources. Independent study aid — not affiliated with or endorsed by the Government of Canada or IRCC.`,
  "cards.verifiedSource.title": `Verified source`,
  "common.back": `Back`,
  "common.cancel": `Cancel`,
  "common.close": `Close`,
  "common.continue": `Continue`,
  "common.done": `Done`,
  "common.emptyBookmarks": `Nothing saved yet`,
  "common.emptyRecentlyStudied": `Nothing studied yet — pick a topic to begin.`,
  "common.loading": `Loading…`,
  "common.next": `Next`,
  "common.of": `of`,
  "common.previous": `Previous`,
  "common.retry": `Retry`,
  "common.save": `Save`,
  "exam.allTopics": `All topics`,
  "exam.answeredCount": `{n} answered`,
  "exam.autosaveNote": `Your answers are saved as you go, so closing the app won't lose your progress.`,
  "exam.cancel": `Cancel`,
  "exam.confirm": `Confirm`,
  "exam.confirmEnd": `{n} questions are unanswered and will be marked incorrect.`,
  "exam.confirmEndTitle": `End exam?`,
  "exam.endExamEarly": `End exam early`,
  "exam.examDisclaimer": `This score reflects this app's sample questions only.`,
  "exam.finishExam": `Finish exam`,
  "exam.newExam": `New exam`,
  "exam.noMistakes": `No mistakes — perfect score!`,
  "exam.pastAttempts": `Past attempts`,
  "exam.questionAriaLabel": `Question {n}`,
  "exam.questionCount": `Number of questions`,
  "exam.questionOf": `Question {n} of {total}`,
  "exam.questionPalette": `Questions`,
  "exam.questionsOption": `{n} questions`,
  "exam.resultsTitle": `Your score`,
  "exam.reviewMistakes": `Review your mistakes ({n})`,
  "exam.scoreLine": `{correct} of {total} correct`,
  "exam.seeProgress": `See progress`,
  "exam.setupDescription": `This is a practice simulation built from this app's study questions. It is not the official test and does not predict your result.`,
  "exam.setupTitle": `Set up your mock exam`,
  "exam.simulationNote": `Practice simulation · not official`,
  "exam.startExam": `Start exam`,
  "exam.timeLeft": `Time left`,
  "exam.timedLabel": `timed`,
  "exam.timedToggle": `Timed (90 seconds per question)`,
  "exam.title": `Mock exam`,
  "exam.topicFilter": `Topic`,
  "exam.untimedLabel": `untimed`,
  "footer.disclaimer": `Citizen Prep is an independent study aid. Not affiliated with or endorsed by the Government of Canada or IRCC. It cannot guarantee a passing result.`,
  "header.appName": `Citizen Prep`,
  "header.tagline": `Independent study tool · Not official`,
  "hero.sectionsProgress": `{done} of {total} sections · {percent}% complete`,
  "hero.subtitle": `Independent study tool · 40 languages · no account needed`,
  "hero.title": `Prepare for your citizenship test`,
  "nav.exam": `Exam`,
  "nav.home": `Home`,
  "nav.practice": `Practice`,
  "nav.progress": `Progress`,
  "nav.topics": `Topics`,
  "practice.allLevels": `All levels`,
  "practice.allTopics": `All topics`,
  "practice.askAiAbout": `Ask AI about this question`,
  "practice.bookmarkQuestion": `Bookmark question`,
  "practice.bookmarked": `Bookmarked`,
  "practice.checkAnswer": `Check answer`,
  "practice.correct": `Correct`,
  "practice.demoContent": `Demo content`,
  "practice.difficulty": `Difficulty`,
  "practice.easy": `Easy`,
  "practice.explanation": `Explanation`,
  "practice.filters": `Filters`,
  "practice.hard": `Hard`,
  "practice.incorrect": `Not quite`,
  "practice.medium": `Medium`,
  "practice.nextQuestion": `Next question`,
  "practice.questionCounter": `Practice question {n} of {total}`,
  "practice.reportIssue": `Report an issue`,
  "practice.title": `Practice`,
  "practice.topicFilter": `Topic`,
  "practice.tryAgain": `Try again`,
  "progress.accuracy": `Accuracy`,
  "progress.clearProgressDesc": `This deletes your answers, completions, bookmarks and exam history from this device. It cannot be undone.`,
  "progress.clearProgressLabel": `Clear all study progress`,
  "progress.confirmClear": `Yes, clear everything`,
  "progress.dailyGoal": `Daily goal`,
  "progress.details": `Details`,
  "progress.examHistory": `Exam history`,
  "progress.noExams": `No exams taken yet.`,
  "progress.noWrongAnswers": `No incorrect answers to review right now.`,
  "progress.overview": `Overview`,
  "progress.perTopic": `Per topic`,
  "progress.questionsAnswered": `Questions answered`,
  "progress.reset": `Reset`,
  "progress.retryTopic": `Retry this topic`,
  "progress.sectionsDone": `Sections completed`,
  "progress.suggestedNext": `Suggested next: {topic}`,
  "progress.title": `Progress`,
  "progress.topicCompletion": `Topic completion`,
  "report.detailsPlaceholder": `Tell us more (optional)`,
  "report.incorrectAnswer": `Incorrect answer`,
  "report.outdatedInfo": `Outdated information`,
  "report.submit": `Submit report`,
  "report.technicalIssue": `Technical issue`,
  "report.thanks": `Thanks — reports are stored locally on this device.`,
  "report.translationProblem": `Translation problem`,
  "report.unclearExplanation": `Explication peu claire`,
  "settings.about": `About this app`,
  "settings.appInterfaceLanguage": `App interface language`,
  "settings.clearProgress": `Clear progress`,
  "settings.clearProgressConfirm": `Are you sure? This will delete all your progress.`,
  "settings.interfaceDescription": `Menus, buttons and navigation.`,
  "settings.language": `Language`,
  "settings.machineNote": `Machine-translated content has not been checked by a human reviewer. Nothing here is labelled as reviewed unless it has actually been reviewed.`,
  "settings.machineTranslatedBadge": `Machine-translated`,
  "settings.manageProgress": `Manage your progress data`,
  "settings.notAvailable": `Not yet available`,
  "settings.officialGuideLink": `Official study guide`,
  "settings.officialTestLink": `Official citizenship test information`,
  "settings.privacy": `Privacy`,
  "settings.privacyText": `Your answers, bookmarks and settings are stored only on this device. No account is needed. Questions you ask the study assistant are sent to an AI service to generate answers.`,
  "settings.reviewedBadge": `Reviewed`,
  "settings.studyContentLanguage": `Study content language`,
  "settings.studyDescription": `Learning text and explanations. You can read in one language while navigating in another.`,
  "settings.textSize": `Text size`,
  "settings.title": `Settings`,
  "topics.askAssistant": `Ask the assistant about this section`,
  "topics.bookmarkSection": `Bookmark section`,
  "topics.bookmarkedSection": `Bookmarked`,
  "topics.completed": `Completed`,
  "topics.continueLearningCard": `Continue learning`,
  "topics.demoSourceNote": `Original sample question — not an official exam question`,
  "topics.lastVerified": `Last verified {date}`,
  "topics.markComplete": `Mark as complete`,
  "topics.markIncomplete": `Mark as incomplete`,
  "topics.minRead": `{n} min read`,
  "topics.next": `Next`,
  "topics.openOfficialPage": `Open official page`,
  "topics.paraphrasedSourceNote": `Paraphrased from official material`,
  "topics.practiceTopic": `Practise this topic`,
  "topics.previous": `Previous`,
  "topics.reportIssue": `Report an issue`,
  "topics.reviewedOn": `reviewed {date}`,
  "topics.reviewedTranslation": `Reviewed translation`,
  "topics.section": `Section`,
  "topics.sections": `sections`,
  "topics.source": `Source`,
  "topics.sourcesDescription": `Study text here is paraphrased from the Government of Canada citizenship study guide and reviewed on the dates shown. Practice questions are researched from the official study guide.`,
  "topics.sourcesHeading": `Content sources and review dates`,
  "topics.studyLanguageLabel": `Study content language`,
  "topics.title": `Study topics`,
  "topics.vocabulary": `Vocabulary`,
};
