// UI strings for 'es' — chunk of strings.generated.ts. DO NOT EDIT BY HAND.
import type { StringKey } from "../strings.generated";

export const es: Record<StringKey, string> = {
  "actions.askAi": `Pregúntale a la IA`,
  "actions.mockExam": `examen simulado`,
  "actions.practice": `Practica`,
  "actions.quickActions": `Quick actions`,
  "actions.study": `estudiar`,
  "assistant.aiEyebrow": `asistente de estudio de IA`,
  "assistant.answerLanguage": `Idioma de respuesta`,
  "assistant.charLimit": `Quedan {n} caracteres`,
  "assistant.checkingMaterial": `Revisando el material de estudio...`,
  "assistant.clearChat": `Borrar chat`,
  "assistant.copied": `Copiado`,
  "assistant.copy": `Copiar`,
  "assistant.description": `Las respuestas las escribe AI utilizando únicamente el material de estudio de esta aplicación, y se muestran las fuentes. La IA aún puede cometer errores: consulte detalles importantes en las páginas oficiales del Gobierno de Canadá. No asesoramiento legal o de inmigración.`,
  "assistant.enFrancais": `En francés`,
  "assistant.error": `Algo salió mal. Por favor inténtalo de nuevo.`,
  "assistant.fromAppContent": `Del contenido de la aplicación aprobada`,
  "assistant.groundedBadge": `Basado en la fuente`,
  "assistant.helpful": `Útil`,
  "assistant.inputPlaceholder": `Haga una pregunta sobre la ciudadanía canadiense...`,
  "assistant.myAppLanguage": `Idioma de mi aplicación`,
  "assistant.notCovered": `No cubierto - ver página oficial`,
  "assistant.notHelpful": `No es útil`,
  "assistant.openAssistant": `asistente de estudio abierto`,
  "assistant.openLink": `asistente abierto`,
  "assistant.practiceThis": `Practica esto`,
  "assistant.questionAriaLabel": `Tu pregunta`,
  "assistant.reportIncorrect": `Informar una respuesta incorrecta`,
  "assistant.send": `enviar`,
  "assistant.showSource": `Mostrar fuente`,
  "assistant.simpleEnglish": `ingles sencillo`,
  "assistant.source": `Fuente`,
  "assistant.starter1": `¿Cuáles son las tres partes del Parlamento?`,
  "assistant.starter2": `Explicar la Carta de forma sencilla`,
  "assistant.starter3": `¿Quién representa al Rey en Canadá?`,
  "assistant.starter4": `¿Qué cubre la prueba de conocimientos?`,
  "assistant.suggestedQuestions": `Preguntas sugeridas`,
  "assistant.thinking": `Pensando…`,
  "assistant.title": `asistente de estudio`,
  "assistant.tryAgain": `Inténtalo de nuevo`,
  "assistant.tryAsking": `Intenta preguntar:`,
  "assistant.vocabularyLabel": `Vocabulario:`,
  "assistant.whyItMatters": `Por qué es importante para la prueba`,
  "auth.account": `Account`,
  "auth.checkEmail": `Check your email to confirm your account, then sign in.`,
  "auth.close": `Close`,
  "auth.codeLabel": `Verification code`,
  "auth.codeResent": `New code sent. Check your email.`,
  "auth.codeSent": `Code sent! Check your email and enter the 6-digit code.`,
  "auth.createAccount": `Create account`,
  "auth.dataDeletedMsg": `Your progress and profile data were deleted.`,
  "auth.deleteConfirm": `Tap again to permanently delete`,
  "auth.deleteData": `Delete my data`,
  "auth.email": `Email`,
  "auth.haveAccount": `Already have an account?`,
  "auth.mfaCodeLabel": `Authenticator code`,
  "auth.mfaDisable": `Disable 2FA`,
  "auth.mfaDisabledMsg": `Two-factor authentication is now OFF.`,
  "auth.mfaEnable": `Enable 2FA`,
  "auth.mfaEnabledMsg": `Two-factor authentication is now ON for your account.`,
  "auth.mfaPendingWarn": `2FA code still needed to finish signing in.`,
  "auth.mfaPrompt": `This account uses 2FA — enter the code from your authenticator app.`,
  "auth.mfaScanHint": `Scan this QR code with your authenticator app (Google Authenticator, Authy, 1Password…), then enter the 6-digit code it shows.`,
  "auth.mfaSetupTitle": `Set up two-factor authentication`,
  "auth.mfaSubtitle": `Enter the 6-digit code from your authenticator app.`,
  "auth.mfaTitle": `Two-factor authentication`,
  "auth.noAccount": `Don't have an account?`,
  "auth.password": `Password`,
  "auth.passwordHint": `At least 6 characters`,
  "auth.privacy": `Privacy`,
  "auth.privacyNote": `Your email and progress are private — only you can see them.`,
  "auth.resendCode": `Resend code`,
  "auth.security": `Security`,
  "auth.signIn": `Sign in`,
  "auth.signOut": `Sign out`,
  "auth.signUp": `Sign up`,
  "auth.subtitle": `Save your progress across devices. Your data stays private.`,
  "auth.title": `Account`,
  "auth.verify": `Verify`,
  "auth.verifyCodeSubtitle": `We sent a 6-digit code to your email. Enter it below to finish signing up.`,
  "auth.verifyCodeTitle": `Enter your code`,
  "auth.working": `Please wait…`,
  "bookmarks.continueStudying": `seguir estudiando`,
  "bookmarks.empty": `Aún no hay marcadores. Toque la estrella en cualquier pregunta para guardarla y revisarla.`,
  "bookmarks.emptyQuestions": `Nada guardado todavía. Toca ☆ en una pregunta de práctica.`,
  "bookmarks.emptySections": `Nada guardado todavía. Toque ☆ mientras lee una sección.`,
  "bookmarks.remove": `Quitar`,
  "bookmarks.savedForReview": `guardado para revisión`,
  "bookmarks.savedQuestions": `Preguntas guardadas ({n})`,
  "bookmarks.savedSections": `Secciones guardadas ({n})`,
  "bookmarks.search": `Buscar marcadores…`,
  "bookmarks.title": `Marcadores`,
  "cards.answered": `Respondido`,
  "cards.bookmarks": `guardado para revisión`,
  "cards.bookmarksLabel": `Marcadores`,
  "cards.continueLearning": `Continuar aprendiendo`,
  "cards.correct": `Correcto`,
  "cards.dailyGoal": `{done}/{total} questions today`,
  "cards.dailyGoalLabel": `Meta diaria`,
  "cards.dailyGoalTitle": `Daily goal`,
  "cards.mockExam.subtitle": `Cronometrado · 20 preguntas`,
  "cards.mockExam.title": `examen simulado`,
  "cards.officialInfo.button": `Abrir canada.ca`,
  "cards.officialInfo.subtitle": `Visite canada.ca para obtener detalles oficiales`,
  "cards.officialInfo.title": `Información oficial`,
  "cards.progress": `Progreso`,
  "cards.progressDetails": `Detalles`,
  "cards.recentlyStudied": `Estudiado recientemente`,
  "cards.sections": `Secciones`,
  "cards.studyAssistant.subtitle": `Preguntar cualquier cosa sobre el material de estudio.`,
  "cards.studyAssistant.title": `asistente de estudio`,
  "cards.todaysRecommendation": `La recomendación de hoy`,
  "cards.verifiedSource.subtext": `Contenido cotejado con fuentes oficiales. Ayuda para estudios independientes: no afiliada ni respaldada por el Gobierno de Canadá o el IRCC.`,
  "cards.verifiedSource.title": `Fuente verificada`,
  "common.back": `Atrás`,
  "common.cancel": `Cancelar`,
  "common.close": `Cerrar`,
  "common.continue": `Continuar`,
  "common.done": `hecho`,
  "common.emptyBookmarks": `Nada guardado aún`,
  "common.emptyRecentlyStudied": `Aún no hay nada estudiado: elige un tema para comenzar.`,
  "common.loading": `Cargando…`,
  "common.next": `Siguiente`,
  "common.of": `de`,
  "common.previous": `Anterior`,
  "common.retry": `Reintentar`,
  "common.save": `Guardar`,
  "exam.allTopics": `Todos los temas`,
  "exam.answeredCount": `{n} respondió`,
  "exam.autosaveNote": `Tus respuestas se guardan a medida que avanzas, por lo que cerrar la aplicación no perderá tu progreso.`,
  "exam.cancel": `Cancelar`,
  "exam.confirm": `Confirmar`,
  "exam.confirmEnd": `{n} preguntas no tienen respuesta y se marcarán como incorrectas.`,
  "exam.confirmEndTitle": `¿Terminar el examen?`,
  "exam.endExamEarly": `Terminar el examen temprano`,
  "exam.examDisclaimer": `Esta puntuación refleja únicamente las preguntas de muestra de esta aplicación.`,
  "exam.finishExam": `terminar el examen`,
  "exam.newExam": `Nuevo examen`,
  "exam.noMistakes": `Sin errores: ¡puntuación perfecta!`,
  "exam.pastAttempts": `Intentos pasados`,
  "exam.questionAriaLabel": `Pregunta {n}`,
  "exam.questionCount": `Número de preguntas`,
  "exam.questionOf": `Pregunta {n} de {total}`,
  "exam.questionPalette": `Preguntas`,
  "exam.questionsOption": `{n} preguntas`,
  "exam.resultsTitle": `Tu puntuación`,
  "exam.reviewMistakes": `Revisa tus errores ({n})`,
  "exam.scoreLine": `{correct} of {total} correct`,
  "exam.seeProgress": `Ver progreso`,
  "exam.setupDescription": `Esta es una simulación de práctica creada a partir de las preguntas de estudio de esta aplicación. No es la prueba oficial y no predice su resultado.`,
  "exam.setupTitle": `Configure su examen simulado`,
  "exam.simulationNote": `Práctica de simulación · no oficial`,
  "exam.startExam": `Iniciar examen`,
  "exam.timeLeft": `Tiempo restante`,
  "exam.timedLabel": `cronometrado`,
  "exam.timedToggle": `Cronometrado (90 segundos por pregunta)`,
  "exam.title": `examen simulado`,
  "exam.topicFilter": `Tema`,
  "exam.untimedLabel": `sin tiempo`,
  "footer.disclaimer": `Citizen Prep es una ayuda de estudio independiente. No afiliado ni respaldado por el Gobierno de Canadá o el IRCC. No puede garantizar un resultado aprobado.`,
  "header.appName": `Preparación ciudadana`,
  "header.tagline": `Herramienta de estudio independiente · No oficial`,
  "hero.sectionsProgress": `{done} of {total} sections · {percent}% complete`,
  "hero.subtitle": `Herramienta de estudio independiente · Inglés y francés · no se necesita cuenta`,
  "hero.title": `Prepárate para tu prueba de ciudadanía`,
  "nav.exam": `examen`,
  "nav.home": `Inicio`,
  "nav.practice": `Practica`,
  "nav.progress": `Progreso`,
  "nav.topics": `Temas`,
  "practice.allLevels": `Todos los niveles`,
  "practice.allTopics": `Todos los temas`,
  "practice.askAiAbout": `Pregúntale a AI sobre esta pregunta`,
  "practice.bookmarkQuestion": `Pregunta de marcador`,
  "practice.bookmarked": `Marcado como favorito`,
  "practice.checkAnswer": `comprobar respuesta`,
  "practice.correct": `Correcto`,
  "practice.demoContent": `Contenido de demostración`,
  "practice.difficulty": `dificultad`,
  "practice.easy": `fácil`,
  "practice.explanation": `Explicación`,
  "practice.filters": `Filtros`,
  "practice.hard": `duro`,
  "practice.incorrect": `No del todo`,
  "practice.medium": `Medio`,
  "practice.nextQuestion": `Siguiente pregunta`,
  "practice.questionCounter": `Pregunta de práctica {n} de {total}`,
  "practice.reportIssue": `Informar un problema`,
  "practice.title": `Practica`,
  "practice.topicFilter": `Tema`,
  "practice.tryAgain": `Inténtalo de nuevo`,
  "progress.accuracy": `Precisión`,
  "progress.clearProgressDesc": `Esto elimina sus respuestas, completaciones, marcadores e historial de exámenes de este dispositivo. No se puede deshacer.`,
  "progress.clearProgressLabel": `Borrar todo el progreso del estudio`,
  "progress.confirmClear": `Si, borrar todo`,
  "progress.dailyGoal": `Meta diaria`,
  "progress.details": `Detalles`,
  "progress.examHistory": `historial de exámenes`,
  "progress.noExams": `Aún no se han realizado exámenes.`,
  "progress.noWrongAnswers": `No hay respuestas incorrectas para revisar en este momento.`,
  "progress.overview": `Descripción general`,
  "progress.perTopic": `Por tema`,
  "progress.questionsAnswered": `Preguntas respondidas`,
  "progress.reset": `Reiniciar`,
  "progress.retryTopic": `Reintentar este tema`,
  "progress.sectionsDone": `Secciones completadas`,
  "progress.suggestedNext": `Suggested next: {topic}`,
  "progress.title": `Progreso`,
  "progress.topicCompletion": `Finalización del tema`,
  "report.detailsPlaceholder": `Cuéntanos más (opcional)`,
  "report.incorrectAnswer": `respuesta incorrecta`,
  "report.outdatedInfo": `Información desactualizada`,
  "report.submit": `Enviar informe`,
  "report.technicalIssue": `Problema técnico`,
  "report.thanks": `Gracias. Los informes se almacenan localmente en este dispositivo.`,
  "report.translationProblem": `Problema de traducción`,
  "report.unclearExplanation": `Explicación pequeña Claire`,
  "settings.about": `Acerca de esta aplicación`,
  "settings.appInterfaceLanguage": `Idioma de la interfaz de la aplicación`,
  "settings.clearProgress": `Progreso claro`,
  "settings.clearProgressConfirm": `¿Estás seguro? Esto eliminará todo tu progreso.`,
  "settings.interfaceDescription": `Menús, botones y navegación.`,
  "settings.language": `Idioma`,
  "settings.machineNote": `El contenido traducido automáticamente no ha sido revisado por un revisor humano. Nada aquí está etiquetado como revisado a menos que realmente haya sido revisado.`,
  "settings.machineTranslatedBadge": `Traducido automáticamente`,
  "settings.manageProgress": `Gestiona tus datos de progreso`,
  "settings.notAvailable": `Aún no disponible`,
  "settings.officialGuideLink": `guía de estudio oficial`,
  "settings.officialTestLink": `Información oficial del examen de ciudadanía.`,
  "settings.privacy": `Privacidad`,
  "settings.privacyText": `Sus respuestas, marcadores y configuraciones se almacenan únicamente en este dispositivo. No se necesita ninguna cuenta. Las preguntas que le hace al asistente del estudio se envían a un servicio de inteligencia artificial para generar respuestas.`,
  "settings.reviewedBadge": `Revisado`,
  "settings.studyContentLanguage": `Idioma del contenido del estudio`,
  "settings.studyDescription": `Texto de aprendizaje y explicaciones. Puedes leer en un idioma mientras navegas en otro.`,
  "settings.textSize": `Tamaño del texto`,
  "settings.title": `Configuración`,
  "topics.askAssistant": `Pregunta al asistente sobre esta sección`,
  "topics.bookmarkSection": `Sección de marcadores`,
  "topics.bookmarkedSection": `Marcado como favorito`,
  "topics.completed": `Completado`,
  "topics.continueLearningCard": `Continuar aprendiendo`,
  "topics.demoSourceNote": `Pregunta de muestra original: no es una pregunta de examen oficial`,
  "topics.lastVerified": `Última verificación {date}`,
  "topics.markComplete": `Marcar como completo`,
  "topics.markIncomplete": `Marcar como incompleto`,
  "topics.minRead": `{n} minutos de lectura`,
  "topics.next": `Siguiente`,
  "topics.openOfficialPage": `Abrir página oficial`,
  "topics.paraphrasedSourceNote": `Parafraseado del material oficial.`,
  "topics.practiceTopic": `practica este tema`,
  "topics.previous": `Anterior`,
  "topics.reportIssue": `Informar un problema`,
  "topics.reviewedOn": `reviewed {date}`,
  "topics.reviewedTranslation": `Traducción revisada`,
  "topics.section": `Sección`,
  "topics.sections": `secciones`,
  "topics.source": `Fuente`,
  "topics.sourcesDescription": `El texto de estudio aquí está parafraseado de la guía de estudio de ciudadanía del Gobierno de Canadá y revisado en las fechas que se muestran. Las preguntas de práctica se investigan a partir de la guía de estudio oficial.`,
  "topics.sourcesHeading": `Fuentes de contenido y fechas de revisión`,
  "topics.studyLanguageLabel": `Idioma del contenido del estudio`,
  "topics.title": `Temas de estudio`,
  "topics.vocabulary": `Vocabulario`,
};
