// UI strings for 'et' — chunk of strings.generated.ts. DO NOT EDIT BY HAND.
import type { StringKey } from "../strings.generated";

export const et: Record<StringKey, string> = {
  "actions.askAi": `Küsige AI-st`,
  "actions.mockExam": `Proovieksam`,
  "actions.practice": `Harjuta`,
  "actions.quickActions": `Quick actions`,
  "actions.study": `Uuring`,
  "assistant.aiEyebrow": `AI õppeassistent`,
  "assistant.answerLanguage": `Vastuste keel`,
  "assistant.charLimit": `{n} tähemärki jäänud`,
  "assistant.checkingMaterial": `Õppematerjali kontrollimine…`,
  "assistant.clearChat": `Tühjenda vestlus`,
  "assistant.copied": `Kopeeritud`,
  "assistant.copy": `Kopeeri`,
  "assistant.description": `Vastused kirjutas tehisintellekt, kasutades ainult selle rakenduse õppematerjali ja näidatud allikad. AI võib endiselt teha vigu – vaadake olulisi üksikasju Kanada valitsuse ametlikel lehtedel. Mitte juriidiline ega immigratsiooninõustamine.`,
  "assistant.enFrancais": `En français`,
  "assistant.error": `Midagi läks valesti. Palun proovi uuesti.`,
  "assistant.fromAppContent": `Rakenduse kinnitatud sisust`,
  "assistant.groundedBadge": `Allikaga maandatud`,
  "assistant.helpful": `Abiks`,
  "assistant.inputPlaceholder": `Esitage küsimus Kanada kodakondsuse kohta…`,
  "assistant.myAppLanguage": `Minu rakenduse keel`,
  "assistant.notCovered": `Pole kaetud - vaadake ametlikku lehte`,
  "assistant.notHelpful": `Ei ole abiks`,
  "assistant.openAssistant": `Avatud õppeassistent`,
  "assistant.openLink": `Ava assistent`,
  "assistant.practiceThis": `Harjuta seda`,
  "assistant.questionAriaLabel": `Teie küsimus`,
  "assistant.reportIncorrect": `Teatage valest vastusest`,
  "assistant.send": `Saada`,
  "assistant.showSource": `Näita allikat`,
  "assistant.simpleEnglish": `Lihtne inglise keel`,
  "assistant.source": `Allikas`,
  "assistant.starter1": `Mis on parlamendi kolm osa?`,
  "assistant.starter2": `Selgitage hartat lihtsalt`,
  "assistant.starter3": `Kes esindab Kanadas kuningat?`,
  "assistant.starter4": `Mida teadmiste kontroll hõlmab?`,
  "assistant.suggestedQuestions": `Soovitatud küsimused`,
  "assistant.thinking": `Mõeldes…`,
  "assistant.title": `Õppeassistent`,
  "assistant.tryAgain": `Proovi uuesti`,
  "assistant.tryAsking": `Proovige küsida:`,
  "assistant.vocabularyLabel": `Sõnavara:`,
  "assistant.whyItMatters": `Miks see testi jaoks oluline on`,
  "auth.account": `Account`,
  "auth.checkEmail": `Check your email to confirm your account, then sign in.`,
  "auth.close": `Close`,
  "auth.codeLabel": `Verification code`,
  "auth.codeResent": `New code sent. Check your email.`,
  "auth.codeSent": `Code sent! Check your email and enter the 6-digit code.`,
  "auth.createAccount": `Create account`,
  "auth.dataDeletedMsg": `Your progress and profile data were deleted.`,
  "auth.deleteConfirm": `Tap again to permanently delete`,
  "auth.deleteData": `Delete my data`,
  "auth.email": `Email`,
  "auth.haveAccount": `Already have an account?`,
  "auth.mfaCodeLabel": `Authenticator code`,
  "auth.mfaDisable": `Disable 2FA`,
  "auth.mfaDisabledMsg": `Two-factor authentication is now OFF.`,
  "auth.mfaEnable": `Enable 2FA`,
  "auth.mfaEnabledMsg": `Two-factor authentication is now ON for your account.`,
  "auth.mfaPendingWarn": `2FA code still needed to finish signing in.`,
  "auth.mfaPrompt": `This account uses 2FA — enter the code from your authenticator app.`,
  "auth.mfaScanHint": `Scan this QR code with your authenticator app (Google Authenticator, Authy, 1Password…), then enter the 6-digit code it shows.`,
  "auth.mfaSetupTitle": `Set up two-factor authentication`,
  "auth.mfaSubtitle": `Enter the 6-digit code from your authenticator app.`,
  "auth.mfaTitle": `Two-factor authentication`,
  "auth.noAccount": `Don't have an account?`,
  "auth.password": `Password`,
  "auth.passwordHint": `At least 6 characters`,
  "auth.privacy": `Privacy`,
  "auth.privacyNote": `Your email and progress are private — only you can see them.`,
  "auth.resendCode": `Resend code`,
  "auth.security": `Security`,
  "auth.signIn": `Sign in`,
  "auth.signOut": `Sign out`,
  "auth.signUp": `Sign up`,
  "auth.subtitle": `Save your progress across devices. Your data stays private.`,
  "auth.title": `Account`,
  "auth.verify": `Verify`,
  "auth.verifyCodeSubtitle": `We sent a 6-digit code to your email. Enter it below to finish signing up.`,
  "auth.verifyCodeTitle": `Enter your code`,
  "auth.working": `Please wait…`,
  "bookmarks.continueStudying": `Jätkake õppimist`,
  "bookmarks.empty": `Järjehoidjaid pole veel. Puudutage mis tahes küsimusel tärni, et see ülevaatamiseks salvestada.`,
  "bookmarks.emptyQuestions": `Midagi pole veel salvestatud. Puudutage harjutusküsimust ☆.`,
  "bookmarks.emptySections": `Midagi pole veel salvestatud. Puudutage jaotise lugemise ajal ikooni ☆.`,
  "bookmarks.remove": `Eemalda`,
  "bookmarks.savedForReview": `salvestatud ülevaatamiseks`,
  "bookmarks.savedQuestions": `Salvestatud küsimused ({n})`,
  "bookmarks.savedSections": `Salvestatud jaotised ({n})`,
  "bookmarks.search": `Otsi järjehoidjaid…`,
  "bookmarks.title": `Järjehoidjad`,
  "cards.answered": `Vastatud`,
  "cards.bookmarks": `salvestatud ülevaatamiseks`,
  "cards.bookmarksLabel": `Järjehoidjad`,
  "cards.continueLearning": `Jätkake õppimist`,
  "cards.correct": `Õige`,
  "cards.dailyGoal": `{done}/{total} küsimust täna`,
  "cards.dailyGoalLabel": `Päevane eesmärk`,
  "cards.dailyGoalTitle": `Daily goal`,
  "cards.mockExam.subtitle": `Ajastatud · 20 küsimust`,
  "cards.mockExam.title": `Proovieksam`,
  "cards.officialInfo.button": `Avage canada.ca`,
  "cards.officialInfo.subtitle": `Ametlike üksikasjade saamiseks külastage veebisaiti canada.ca`,
  "cards.officialInfo.title": `Ametlik teave`,
  "cards.progress": `Edusammud`,
  "cards.progressDetails": `Üksikasjad`,
  "cards.recentlyStudied": `Hiljuti õppinud`,
  "cards.sections": `Sektsioonid`,
  "cards.studyAssistant.subtitle": `Küsige midagi õppematerjali kohta`,
  "cards.studyAssistant.title": `Õppeassistent`,
  "cards.todaysRecommendation": `Tänane soovitus`,
  "cards.verifiedSource.subtext": `Sisu kontrolliti ametlike allikatega võrreldes. Sõltumatu õppevahend – ei ole Kanada valitsuse ega IRCC-ga seotud ega nende poolt heaks kiidetud.`,
  "cards.verifiedSource.title": `Kinnitatud allikas`,
  "common.back": `Tagasi`,
  "common.cancel": `Tühista`,
  "common.close": `Sule`,
  "common.continue": `Jätka`,
  "common.done": `Valmis`,
  "common.emptyBookmarks": `Midagi pole veel salvestatud`,
  "common.emptyRecentlyStudied": `Midagi pole veel uuritud – alustamiseks valige teema.`,
  "common.loading": `Laadimine…`,
  "common.next": `Edasi`,
  "common.of": `kohta`,
  "common.previous": `Eelmine`,
  "common.retry": `Proovi uuesti`,
  "common.save": `Salvesta`,
  "exam.allTopics": `Kõik teemad`,
  "exam.answeredCount": `{n} vastas`,
  "exam.autosaveNote": `Teie vastused salvestatakse töö käigus, nii et rakenduse sulgemine ei kaota teie edusamme.`,
  "exam.cancel": `Tühista`,
  "exam.confirm": `Kinnita`,
  "exam.confirmEnd": `{n} küsimust on vastamata ja need märgitakse valeks.`,
  "exam.confirmEndTitle": `Kas lõpetada eksam?`,
  "exam.endExamEarly": `Lõpeta eksam varakult`,
  "exam.examDisclaimer": `See skoor kajastab ainult selle rakenduse näidisküsimusi.`,
  "exam.finishExam": `Lõpeta eksam`,
  "exam.newExam": `Uus eksam`,
  "exam.noMistakes": `Pole vigu – ideaalne tulemus!`,
  "exam.pastAttempts": `Varasemad katsed`,
  "exam.questionAriaLabel": `küsimus {n}`,
  "exam.questionCount": `Küsimuste arv`,
  "exam.questionOf": `{n}. küsimus {total}-st`,
  "exam.questionPalette": `Küsimused`,
  "exam.questionsOption": `{n} küsimust`,
  "exam.resultsTitle": `Teie skoor`,
  "exam.reviewMistakes": `Vaadake oma vead üle ({n})`,
  "exam.scoreLine": `{correct}/{total} õige`,
  "exam.seeProgress": `Vaadake edusamme`,
  "exam.setupDescription": `See on selle rakenduse õppeküsimuste põhjal koostatud praktikasimulatsioon. See ei ole ametlik test ega ennusta teie tulemust.`,
  "exam.setupTitle": `Seadistage proovieksam`,
  "exam.simulationNote": `Praktika simulatsiooni · pole ametlik`,
  "exam.startExam": `Alusta eksamit`,
  "exam.timeLeft": `Aega jäänud`,
  "exam.timedLabel": `ajastatud`,
  "exam.timedToggle": `Ajastatud (90 sekundit küsimuse kohta)`,
  "exam.title": `Proovieksam`,
  "exam.topicFilter": `Teema`,
  "exam.untimedLabel": `ajata`,
  "footer.disclaimer": `Citizen Prep on sõltumatu õppevahend. Ei ole Kanada valitsuse ega IRCC-ga seotud ega nende poolt heaks kiidetud. See ei saa garanteerida mööduvat tulemust.`,
  "header.appName": `Kodaniku ettevalmistus`,
  "header.tagline": `Sõltumatu õppevahend · Ei ole ametlik`,
  "hero.sectionsProgress": `{done} of {total} sections · {percent}% complete`,
  "hero.subtitle": `Sõltumatu õppevahend · inglise ja prantsuse keel · konto pole vajalik`,
  "hero.title": `Valmistuge kodakondsuseksamiks`,
  "nav.exam": `Eksam`,
  "nav.home": `Kodu`,
  "nav.practice": `Harjuta`,
  "nav.progress": `Edusammud`,
  "nav.topics": `Teemad`,
  "practice.allLevels": `Kõik tasemed`,
  "practice.allTopics": `Kõik teemad`,
  "practice.askAiAbout": `Küsige AI-lt selle küsimuse kohta`,
  "practice.bookmarkQuestion": `Järjehoidja küsimus`,
  "practice.bookmarked": `Järjehoidjasse lisatud`,
  "practice.checkAnswer": `Kontrolli vastust`,
  "practice.correct": `Õige`,
  "practice.demoContent": `Demo sisu`,
  "practice.difficulty": `Raskus`,
  "practice.easy": `Lihtne`,
  "practice.explanation": `Selgitus`,
  "practice.filters": `Filtrid`,
  "practice.hard": `Raske`,
  "practice.incorrect": `Mitte päris`,
  "practice.medium": `Keskmine`,
  "practice.nextQuestion": `Järgmine küsimus`,
  "practice.questionCounter": `Harjutusküsimus {n}/{total}`,
  "practice.reportIssue": `Teatage probleemist`,
  "practice.title": `Harjuta`,
  "practice.topicFilter": `Teema`,
  "practice.tryAgain": `Proovi uuesti`,
  "progress.accuracy": `Täpsus`,
  "progress.clearProgressDesc": `See kustutab sellest seadmest teie vastused, lõpetamised, järjehoidjad ja eksamite ajaloo. Seda ei saa tagasi võtta.`,
  "progress.clearProgressLabel": `Kustutage kogu õppetöö`,
  "progress.confirmClear": `Jah, puhastage kõik`,
  "progress.dailyGoal": `Päevane eesmärk`,
  "progress.details": `Üksikasjad`,
  "progress.examHistory": `Eksami ajalugu`,
  "progress.noExams": `Eksameid pole veel tehtud.`,
  "progress.noWrongAnswers": `Praegu pole ülevaatamiseks valesid vastuseid.`,
  "progress.overview": `Ülevaade`,
  "progress.perTopic": `Teema järgi`,
  "progress.questionsAnswered": `Küsimustele vastatud`,
  "progress.reset": `Lähtesta`,
  "progress.retryTopic": `Proovi seda teemat uuesti`,
  "progress.sectionsDone": `Lõigud valmis`,
  "progress.suggestedNext": `Soovitatud järgmine: {topic}`,
  "progress.title": `Edusammud`,
  "progress.topicCompletion": `Teema lõpetamine`,
  "report.detailsPlaceholder": `Rääkige meile rohkem (valikuline)`,
  "report.incorrectAnswer": `Vale vastus`,
  "report.outdatedInfo": `Aegunud teave`,
  "report.submit": `Esitage aruanne`,
  "report.technicalIssue": `Tehniline probleem`,
  "report.thanks": `Täname – aruanded salvestatakse sellesse seadmesse kohapeal.`,
  "report.translationProblem": `Tõlkeprobleem`,
  "report.unclearExplanation": `Selgitus peu claire`,
  "settings.about": `Teave selle rakenduse kohta`,
  "settings.appInterfaceLanguage": `Rakenduse liidese keel`,
  "settings.clearProgress": `Selge edasiminek`,
  "settings.clearProgressConfirm": `Oled sa kindel? See kustutab kõik teie edusammud.`,
  "settings.interfaceDescription": `Menüüd, nupud ja navigeerimine.`,
  "settings.language": `Keel`,
  "settings.machineNote": `Masintõlgitud sisu pole inimestest ülevaataja kontrollinud. Midagi siin ei märgita arvustatuks, kui see pole tegelikult üle vaadatud.`,
  "settings.machineTranslatedBadge": `Masintõlgitud`,
  "settings.manageProgress": `Hallake oma edenemisandmeid`,
  "settings.notAvailable": `Pole veel saadaval`,
  "settings.officialGuideLink": `Ametlik õppejuhend`,
  "settings.officialTestLink": `Ametlik kodakondsuse testi teave`,
  "settings.privacy": `Privaatsus`,
  "settings.privacyText": `Teie vastused, järjehoidjad ja seaded salvestatakse ainult sellesse seadmesse. Kontot pole vaja. Küsimused, mille küsite õppeassistendile, saadetakse vastuste saamiseks tehisintellektiteenusele.`,
  "settings.reviewedBadge": `Üle vaadatud`,
  "settings.studyContentLanguage": `Õppesisu keel`,
  "settings.studyDescription": `Teksti ja selgituste õppimine. Saate lugeda ühes keeles ja navigeerida teises keeles.`,
  "settings.textSize": `Teksti suurus`,
  "settings.title": `Seaded`,
  "topics.askAssistant": `Küsige assistendilt selle jaotise kohta`,
  "topics.bookmarkSection": `Järjehoidjate jaotis`,
  "topics.bookmarkedSection": `Järjehoidjasse lisatud`,
  "topics.completed": `Lõpetatud`,
  "topics.continueLearningCard": `Jätkake õppimist`,
  "topics.demoSourceNote": `Algne näidisküsimus – mitte ametlik eksamiküsimus`,
  "topics.lastVerified": `Viimati kinnitatud {date}`,
  "topics.markComplete": `Märgi lõpetatuks`,
  "topics.markIncomplete": `Märgi mittetäielikuks`,
  "topics.minRead": `{n} min lugemist`,
  "topics.next": `Edasi`,
  "topics.openOfficialPage": `Ava ametlik leht`,
  "topics.paraphrasedSourceNote": `Parafraseeritud ametlikust materjalist`,
  "topics.practiceTopic": `Harjutage seda teemat`,
  "topics.previous": `Eelmine`,
  "topics.reportIssue": `Teatage probleemist`,
  "topics.reviewedOn": `üle vaadatud {date}`,
  "topics.reviewedTranslation": `Läbi vaadatud tõlge`,
  "topics.section": `jaotis`,
  "topics.sections": `lõigud`,
  "topics.source": `Allikas`,
  "topics.sourcesDescription": `Siinne õppetekst on ümbersõnastatud Kanada valitsuse kodakondsuse õppejuhendist ja vaadatud näidatud kuupäevadel. Praktikaküsimusi uuritakse ametlikust õppejuhendist.`,
  "topics.sourcesHeading": `Sisuallikad ja arvustuste kuupäevad`,
  "topics.studyLanguageLabel": `Õppesisu keel`,
  "topics.title": `Õppeteemad`,
  "topics.vocabulary": `Sõnavara`,
};
