// UI strings for 'eu' — chunk of strings.generated.ts. DO NOT EDIT BY HAND.
import type { StringKey } from "../strings.generated";

export const eu: Record<StringKey, string> = {
  "actions.askAi": `Galdetu AI`,
  "actions.mockExam": `Azterketa simulatua`,
  "actions.practice": `Praktikatu`,
  "actions.quickActions": `Quick actions`,
  "actions.study": `Aztertu`,
  "assistant.aiEyebrow": `AI ikasketa laguntzailea`,
  "assistant.answerLanguage": `Erantzun hizkuntza`,
  "assistant.charLimit": `{n} karaktere geratzen dira`,
  "assistant.checkingMaterial": `Ikasmateriala egiaztatzen...`,
  "assistant.clearChat": `Garbitu txata`,
  "assistant.copied": `Kopiatua`,
  "assistant.copy": `Kopiatu`,
  "assistant.description": `Erantzunak AI-k idazten ditu aplikazio honen ikasmateriala soilik erabiliz, iturriak erakutsita. Intelek oraindik akatsak egin ditzake: egiaztatu xehetasun garrantzitsuak Kanadako Gobernuaren orri ofizialetan. Ez legezko edo immigraziorako aholkularitza.`,
  "assistant.enFrancais": `frantsesez`,
  "assistant.error": `Zerbait gaizki joan da. Mesedez, saiatu berriro.`,
  "assistant.fromAppContent": `Onartutako aplikazioaren edukitik`,
  "assistant.groundedBadge": `Iturburuan oinarritua`,
  "assistant.helpful": `Lagungarria`,
  "assistant.inputPlaceholder": `Egin galdera bat Kanadako herritartasunari buruz...`,
  "assistant.myAppLanguage": `Nire aplikazioaren hizkuntza`,
  "assistant.notCovered": `Estali gabe — ikusi orri ofiziala`,
  "assistant.notHelpful": `Ez da lagungarria`,
  "assistant.openAssistant": `Ikasketa laguntzaile irekia`,
  "assistant.openLink": `Ireki laguntzailea`,
  "assistant.practiceThis": `Praktikatu hau`,
  "assistant.questionAriaLabel": `Zure galdera`,
  "assistant.reportIncorrect": `Eman erantzun oker baten berri`,
  "assistant.send": `Bidali`,
  "assistant.showSource": `Erakutsi iturria`,
  "assistant.simpleEnglish": `Ingeles sinplea`,
  "assistant.source": `Iturria`,
  "assistant.starter1": `Zeintzuk dira Parlamentuaren hiru zatiak?`,
  "assistant.starter2": `Azaldu karta besterik gabe`,
  "assistant.starter3": `Nork ordezkatzen du erregea Kanadan?`,
  "assistant.starter4": `Zer jasotzen du ezagutza probak?`,
  "assistant.suggestedQuestions": `Iradokitako galderak`,
  "assistant.thinking": `Pentsatzen…`,
  "assistant.title": `Ikasketa laguntzailea`,
  "assistant.tryAgain": `Saiatu berriro`,
  "assistant.tryAsking": `Saiatu galdetzen:`,
  "assistant.vocabularyLabel": `Hiztegia:`,
  "assistant.whyItMatters": `Zergatik axola zaio probarako`,
  "auth.account": `Account`,
  "auth.checkEmail": `Check your email to confirm your account, then sign in.`,
  "auth.close": `Close`,
  "auth.codeLabel": `Verification code`,
  "auth.codeResent": `New code sent. Check your email.`,
  "auth.codeSent": `Code sent! Check your email and enter the 6-digit code.`,
  "auth.createAccount": `Create account`,
  "auth.dataDeletedMsg": `Your progress and profile data were deleted.`,
  "auth.deleteConfirm": `Tap again to permanently delete`,
  "auth.deleteData": `Delete my data`,
  "auth.email": `Email`,
  "auth.haveAccount": `Already have an account?`,
  "auth.mfaCodeLabel": `Authenticator code`,
  "auth.mfaDisable": `Disable 2FA`,
  "auth.mfaDisabledMsg": `Two-factor authentication is now OFF.`,
  "auth.mfaEnable": `Enable 2FA`,
  "auth.mfaEnabledMsg": `Two-factor authentication is now ON for your account.`,
  "auth.mfaPendingWarn": `2FA code still needed to finish signing in.`,
  "auth.mfaPrompt": `This account uses 2FA — enter the code from your authenticator app.`,
  "auth.mfaScanHint": `Scan this QR code with your authenticator app (Google Authenticator, Authy, 1Password…), then enter the 6-digit code it shows.`,
  "auth.mfaSetupTitle": `Set up two-factor authentication`,
  "auth.mfaSubtitle": `Enter the 6-digit code from your authenticator app.`,
  "auth.mfaTitle": `Two-factor authentication`,
  "auth.noAccount": `Don't have an account?`,
  "auth.password": `Password`,
  "auth.passwordHint": `At least 6 characters`,
  "auth.privacy": `Privacy`,
  "auth.privacyNote": `Your email and progress are private — only you can see them.`,
  "auth.resendCode": `Resend code`,
  "auth.security": `Security`,
  "auth.signIn": `Sign in`,
  "auth.signOut": `Sign out`,
  "auth.signUp": `Sign up`,
  "auth.subtitle": `Save your progress across devices. Your data stays private.`,
  "auth.title": `Account`,
  "auth.verify": `Verify`,
  "auth.verifyCodeSubtitle": `We sent a 6-digit code to your email. Enter it below to finish signing up.`,
  "auth.verifyCodeTitle": `Enter your code`,
  "auth.working": `Please wait…`,
  "bookmarks.continueStudying": `Jarraitu ikasten`,
  "bookmarks.empty": `Oraindik ez dago laster-markarik. Sakatu izarra edozein galderari berrikusteko gordetzeko.`,
  "bookmarks.emptyQuestions": `Oraindik ez da ezer gorde. Sakatu ☆ praktika-galdera batean.`,
  "bookmarks.emptySections": `Oraindik ez da ezer gorde. Sakatu ☆ atal bat irakurtzen duzun bitartean.`,
  "bookmarks.remove": `Kendu`,
  "bookmarks.savedForReview": `berrikusteko gorde da`,
  "bookmarks.savedQuestions": `Gordetako galderak ({n})`,
  "bookmarks.savedSections": `Gordetako atalak ({n})`,
  "bookmarks.search": `Bilatu laster-markak…`,
  "bookmarks.title": `Laster-markak`,
  "cards.answered": `Erantzun`,
  "cards.bookmarks": `berrikusteko gorde da`,
  "cards.bookmarksLabel": `Laster-markak`,
  "cards.continueLearning": `Ikasten jarraitu`,
  "cards.correct": `Zuzena`,
  "cards.dailyGoal": `{done}/{total} questions today`,
  "cards.dailyGoalLabel": `Eguneko helburua`,
  "cards.dailyGoalTitle": `Daily goal`,
  "cards.mockExam.subtitle": `Kronometratua · 20 galdera`,
  "cards.mockExam.title": `Azterketa simulatua`,
  "cards.officialInfo.button": `Ireki canada.ca`,
  "cards.officialInfo.subtitle": `Bisitatu canada.ca xehetasun ofizialetarako`,
  "cards.officialInfo.title": `Informazio ofiziala`,
  "cards.progress": `Aurrerapena`,
  "cards.progressDetails": `Xehetasunak`,
  "cards.recentlyStudied": `Duela gutxi aztertua`,
  "cards.sections": `Atalak`,
  "cards.studyAssistant.subtitle": `Galdetu ezer ikasmaterialari buruz`,
  "cards.studyAssistant.title": `Ikasketa laguntzailea`,
  "cards.todaysRecommendation": `Gaurko gomendioa`,
  "cards.verifiedSource.subtext": `Iturri ofizialekin egiaztatutako edukia. Ikasketa-laguntza independentea - Kanadako Gobernuarekin edo IRCCrekin afiliatuta edo babestuta ez dagoena.`,
  "cards.verifiedSource.title": `Egiaztatutako iturria`,
  "common.back": `Itzuli`,
  "common.cancel": `Utzi`,
  "common.close": `Itxi`,
  "common.continue": `Jarraitu`,
  "common.done": `Eginda`,
  "common.emptyBookmarks": `Oraindik ez da ezer gorde`,
  "common.emptyRecentlyStudied": `Oraindik ez da ezer aztertu — aukeratu gai bat hasteko.`,
  "common.loading": `Kargatzen…`,
  "common.next": `Hurrengoa`,
  "common.of": `de`,
  "common.previous": `Aurrekoa`,
  "common.retry": `Saiatu berriro`,
  "common.save": `Gorde`,
  "exam.allTopics": `Gai guztiak`,
  "exam.answeredCount": `{n}-k erantzun zuen`,
  "exam.autosaveNote": `Zure erantzunak joan ahala gordetzen dira, beraz, aplikazioa ixteak ez du zure aurrerapena galduko.`,
  "exam.cancel": `Utzi`,
  "exam.confirm": `Berretsi`,
  "exam.confirmEnd": `{n} galdera erantzun gabe daude eta okerrak markatuko dira.`,
  "exam.confirmEndTitle": `Azterketa amaitu?`,
  "exam.endExamEarly": `Amaitu azterketa goiz`,
  "exam.examDisclaimer": `Puntuazio honek aplikazio honen lagin-galderak soilik islatzen ditu.`,
  "exam.finishExam": `Amaitu azterketa`,
  "exam.newExam": `Azterketa berria`,
  "exam.noMistakes": `Akatsik ez - puntuazio perfektua!`,
  "exam.pastAttempts": `Iraganeko saiakerak`,
  "exam.questionAriaLabel": `{n} galdera`,
  "exam.questionCount": `Galdera kopurua`,
  "exam.questionOf": `Question {n} of {total}`,
  "exam.questionPalette": `Galderak`,
  "exam.questionsOption": `{n} galdera`,
  "exam.resultsTitle": `Zure puntuazioa`,
  "exam.reviewMistakes": `Berrikusi zure akatsak ({n})`,
  "exam.scoreLine": `{correct} of {total} correct`,
  "exam.seeProgress": `Ikusi aurrerapena`,
  "exam.setupDescription": `Hau aplikazio honen azterketa-galderetatik sortutako praktika-simulazioa da. Ez da proba ofiziala eta ez du zure emaitza iragartzen.`,
  "exam.setupTitle": `Konfiguratu zure azterketa simulatua`,
  "exam.simulationNote": `Praktika simulazioa · ez ofiziala`,
  "exam.startExam": `Hasi azterketa`,
  "exam.timeLeft": `Denbora geratzen da`,
  "exam.timedLabel": `kronometratua`,
  "exam.timedToggle": `Kronometratua (90 segundo galdera bakoitzeko)`,
  "exam.title": `Azterketa simulatua`,
  "exam.topicFilter": `Gaia`,
  "exam.untimedLabel": `denborarik gabekoa`,
  "footer.disclaimer": `Citizen Prep ikasketa-laguntza independente bat da. Kanadako Gobernuarekin edo IRCCrekin afiliatuta edo babestuta ez dago. Ezin du emaitza iragankorra bermatu.`,
  "header.appName": `Herritarren Prestaketa`,
  "header.tagline": `Ikasketa tresna independentea · Ez ofiziala`,
  "hero.sectionsProgress": `{done} of {total} sections · {percent}% complete`,
  "hero.subtitle": `Ikasteko tresna independentea · Ingelesa eta frantsesa · Ez da konturik behar`,
  "hero.title": `Prestatu zure herritartasun probarako`,
  "nav.exam": `Azterketa`,
  "nav.home": `Hasiera`,
  "nav.practice": `Praktikatu`,
  "nav.progress": `Aurrerapena`,
  "nav.topics": `Gaiak`,
  "practice.allLevels": `Maila guztiak`,
  "practice.allTopics": `Gai guztiak`,
  "practice.askAiAbout": `Galdetu AI galdera honi buruz`,
  "practice.bookmarkQuestion": `Laster-markako galdera`,
  "practice.bookmarked": `Laster-marka jarrita`,
  "practice.checkAnswer": `Egiaztatu erantzuna`,
  "practice.correct": `Zuzena`,
  "practice.demoContent": `Demo edukia`,
  "practice.difficulty": `Zailtasuna`,
  "practice.easy": `Erraza`,
  "practice.explanation": `Azalpena`,
  "practice.filters": `Iragazkiak`,
  "practice.hard": `Gogorra`,
  "practice.incorrect": `Ez guztiz`,
  "practice.medium": `Ertaina`,
  "practice.nextQuestion": `Hurrengo galdera`,
  "practice.questionCounter": `Praktikatu galdera {n}/{total}`,
  "practice.reportIssue": `Arazo baten berri eman`,
  "practice.title": `Praktikatu`,
  "practice.topicFilter": `Gaia`,
  "practice.tryAgain": `Saiatu berriro`,
  "progress.accuracy": `Zehaztasuna`,
  "progress.clearProgressDesc": `Honek zure erantzunak, osaketak, laster-markak eta azterketen historia ezabatzen ditu gailu honetatik. Ezin da desegin.`,
  "progress.clearProgressLabel": `Garbitu ikasketen aurrerapen guztiak`,
  "progress.confirmClear": `Bai, garbitu dena`,
  "progress.dailyGoal": `Eguneko helburua`,
  "progress.details": `Xehetasunak`,
  "progress.examHistory": `Azterketen historia`,
  "progress.noExams": `Oraindik ez da azterketarik egin.`,
  "progress.noWrongAnswers": `Ez dago erantzun okerrik berrikusteko momentu honetan.`,
  "progress.overview": `Ikuspegi orokorra`,
  "progress.perTopic": `Gai bakoitzeko`,
  "progress.questionsAnswered": `Galderak erantzunak`,
  "progress.reset": `Berrezarri`,
  "progress.retryTopic": `Saiatu berriro gai hau`,
  "progress.sectionsDone": `Atalak amaituta`,
  "progress.suggestedNext": `Suggested next: {topic}`,
  "progress.title": `Aurrerapena`,
  "progress.topicCompletion": `Gaia osatzea`,
  "report.detailsPlaceholder": `Esaiguzu gehiago (aukerakoa)`,
  "report.incorrectAnswer": `Erantzun okerra`,
  "report.outdatedInfo": `Informazio zaharkitua`,
  "report.submit": `Txostena aurkeztu`,
  "report.technicalIssue": `Gai teknikoa`,
  "report.thanks": `Eskerrik asko — txostenak lokalean gordetzen dira gailu honetan.`,
  "report.translationProblem": `Itzulpen arazoa`,
  "report.unclearExplanation": `Azalpena peu claire`,
  "settings.about": `Aplikazio honi buruz`,
  "settings.appInterfaceLanguage": `Aplikazioaren interfazearen hizkuntza`,
  "settings.clearProgress": `Garbitu aurrerapena`,
  "settings.clearProgressConfirm": `Ziur al zaude? Honek zure aurrerapen guztiak ezabatuko ditu.`,
  "settings.interfaceDescription": `Menuak, botoiak eta nabigazioa.`,
  "settings.language": `Hizkuntza`,
  "settings.machineNote": `Automatikoki itzulitako edukia ez du egiaztatu giza ebaluatzaile batek. Hemen ezer ez da berrikusi gisa etiketatuta, benetan berrikusi ez bada.`,
  "settings.machineTranslatedBadge": `Automatikoki itzulia`,
  "settings.manageProgress": `Kudeatu zure aurrerapen datuak`,
  "settings.notAvailable": `Oraindik ez dago eskuragarri`,
  "settings.officialGuideLink": `Ikasketa-gida ofiziala`,
  "settings.officialTestLink": `Herritartasun probaren informazio ofiziala`,
  "settings.privacy": `Pribatutasuna`,
  "settings.privacyText": `Zure erantzunak, laster-markak eta ezarpenak gailu honetan soilik gordetzen dira. Ez da konturik behar. Ikasketa laguntzaileari egiten dizkiozun galderak AI zerbitzu batera bidaltzen dira erantzunak sortzeko.`,
  "settings.reviewedBadge": `Berrikusi`,
  "settings.studyContentLanguage": `Edukien hizkuntza aztertzea`,
  "settings.studyDescription": `Ikasteko testua eta azalpenak. Hizkuntza batean irakur dezakezu beste batean nabigatzen duzun bitartean.`,
  "settings.textSize": `Testuaren tamaina`,
  "settings.title": `Ezarpenak`,
  "topics.askAssistant": `Galdetu laguntzaileari atal honi buruz`,
  "topics.bookmarkSection": `Laster-marken atala`,
  "topics.bookmarkedSection": `Laster-marka jarrita`,
  "topics.completed": `Osatua`,
  "topics.continueLearningCard": `Ikasten jarraitu`,
  "topics.demoSourceNote": `Jatorrizko lagin-galdera - ez da azterketa-galdera ofiziala`,
  "topics.lastVerified": `Azken egiaztatutako {date}`,
  "topics.markComplete": `Markatu osatu gisa`,
  "topics.markIncomplete": `Markatu osatugabe gisa`,
  "topics.minRead": `{n} minutuko irakurketa`,
  "topics.next": `Hurrengoa`,
  "topics.openOfficialPage": `Ireki orri ofiziala`,
  "topics.paraphrasedSourceNote": `Material ofizialetik parafraseatua`,
  "topics.practiceTopic": `Landu gai hau`,
  "topics.previous": `Aurrekoa`,
  "topics.reportIssue": `Arazo baten berri eman`,
  "topics.reviewedOn": `reviewed {date}`,
  "topics.reviewedTranslation": `Berrikusitako itzulpena`,
  "topics.section": `atala`,
  "topics.sections": `atalak`,
  "topics.source": `Iturria`,
  "topics.sourcesDescription": `Hemen aztertzeko testua Kanadako Gobernuaren hiritartasunaren azterketa gidaliburutik parafraseatzen da eta erakusten diren datetan berrikusten da. Praktika-galderak ikasketa-gida ofizialetik ikertzen dira.`,
  "topics.sourcesHeading": `Edukien iturriak eta berrikuspen datak`,
  "topics.studyLanguageLabel": `Edukien hizkuntza aztertzea`,
  "topics.title": `Ikasgaiak`,
  "topics.vocabulary": `Hiztegia`,
};
