// UI strings for 'fi' — chunk of strings.generated.ts. DO NOT EDIT BY HAND.
import type { StringKey } from "../strings.generated";

export const fi: Record<StringKey, string> = {
  "actions.askAi": `Kysy AI`,
  "actions.mockExam": `Vale koe`,
  "actions.practice": `Harjoittele`,
  "actions.quickActions": `Quick actions`,
  "actions.study": `Opiskelu`,
  "assistant.aiEyebrow": `Tekoälyn opintoavustaja`,
  "assistant.answerLanguage": `Vastauksen kieli`,
  "assistant.charLimit": `{n} merkkiä jäljellä`,
  "assistant.checkingMaterial": `Tarkistetaan oppimateriaalia…`,
  "assistant.clearChat": `Tyhjennä chat`,
  "assistant.copied": `Kopioitu`,
  "assistant.copy": `Kopioi`,
  "assistant.description": `Tekoäly on kirjoittanut vastaukset käyttämällä vain tämän sovelluksen oppimateriaalia ja lähteet näkyvät. Tekoäly voi silti tehdä virheitä – tarkista tärkeät tiedot Kanadan hallituksen virallisilla sivuilla. Ei laki- tai maahanmuuttoneuvontaa.`,
  "assistant.enFrancais": `En français`,
  "assistant.error": `Jotain meni pieleen. Yritä uudelleen.`,
  "assistant.fromAppContent": `Hyväksytystä sovelluksen sisällöstä`,
  "assistant.groundedBadge": `Lähde-maadoitettu`,
  "assistant.helpful": `Hyödyllinen`,
  "assistant.inputPlaceholder": `Esitä kysymys Kanadan kansalaisuudesta…`,
  "assistant.myAppLanguage": `Sovellukseni kieli`,
  "assistant.notCovered": `Ei kuulu - katso virallinen sivu`,
  "assistant.notHelpful": `Ei auta`,
  "assistant.openAssistant": `Avoin opinto-avustaja`,
  "assistant.openLink": `Avaa avustaja`,
  "assistant.practiceThis": `Harjoittele tätä`,
  "assistant.questionAriaLabel": `Kysymyksesi`,
  "assistant.reportIncorrect": `Ilmoita väärästä vastauksesta`,
  "assistant.send": `Lähetä`,
  "assistant.showSource": `Näytä lähde`,
  "assistant.simpleEnglish": `Yksinkertaista englantia`,
  "assistant.source": `Lähde`,
  "assistant.starter1": `Mitkä ovat eduskunnan kolme osaa?`,
  "assistant.starter2": `Selitä peruskirja yksinkertaisesti`,
  "assistant.starter3": `Kuka edustaa kuningasta Kanadassa?`,
  "assistant.starter4": `Mitä tietokoe kattaa?`,
  "assistant.suggestedQuestions": `Ehdotetut kysymykset`,
  "assistant.thinking": `Mietitään…`,
  "assistant.title": `Opinto-avustaja`,
  "assistant.tryAgain": `Yritä uudelleen`,
  "assistant.tryAsking": `Kokeile kysyä:`,
  "assistant.vocabularyLabel": `Sanasto:`,
  "assistant.whyItMatters": `Miksi sillä on merkitystä testin kannalta`,
  "auth.account": `Account`,
  "auth.checkEmail": `Check your email to confirm your account, then sign in.`,
  "auth.close": `Close`,
  "auth.codeLabel": `Verification code`,
  "auth.codeResent": `New code sent. Check your email.`,
  "auth.codeSent": `Code sent! Check your email and enter the 6-digit code.`,
  "auth.createAccount": `Create account`,
  "auth.dataDeletedMsg": `Your progress and profile data were deleted.`,
  "auth.deleteConfirm": `Tap again to permanently delete`,
  "auth.deleteData": `Delete my data`,
  "auth.email": `Email`,
  "auth.haveAccount": `Already have an account?`,
  "auth.mfaCodeLabel": `Authenticator code`,
  "auth.mfaDisable": `Disable 2FA`,
  "auth.mfaDisabledMsg": `Two-factor authentication is now OFF.`,
  "auth.mfaEnable": `Enable 2FA`,
  "auth.mfaEnabledMsg": `Two-factor authentication is now ON for your account.`,
  "auth.mfaPendingWarn": `2FA code still needed to finish signing in.`,
  "auth.mfaPrompt": `This account uses 2FA — enter the code from your authenticator app.`,
  "auth.mfaScanHint": `Scan this QR code with your authenticator app (Google Authenticator, Authy, 1Password…), then enter the 6-digit code it shows.`,
  "auth.mfaSetupTitle": `Set up two-factor authentication`,
  "auth.mfaSubtitle": `Enter the 6-digit code from your authenticator app.`,
  "auth.mfaTitle": `Two-factor authentication`,
  "auth.noAccount": `Don't have an account?`,
  "auth.password": `Password`,
  "auth.passwordHint": `At least 6 characters`,
  "auth.privacy": `Privacy`,
  "auth.privacyNote": `Your email and progress are private — only you can see them.`,
  "auth.resendCode": `Resend code`,
  "auth.security": `Security`,
  "auth.signIn": `Sign in`,
  "auth.signOut": `Sign out`,
  "auth.signUp": `Sign up`,
  "auth.subtitle": `Save your progress across devices. Your data stays private.`,
  "auth.title": `Account`,
  "auth.verify": `Verify`,
  "auth.verifyCodeSubtitle": `We sent a 6-digit code to your email. Enter it below to finish signing up.`,
  "auth.verifyCodeTitle": `Enter your code`,
  "auth.working": `Please wait…`,
  "bookmarks.continueStudying": `Jatka opiskelua`,
  "bookmarks.empty": `Ei vielä kirjanmerkkejä. Napauta minkä tahansa kysymyksen tähteä tallentaaksesi sen tarkistettavaksi.`,
  "bookmarks.emptyQuestions": `Mitään ei ole vielä tallennettu. Napauta harjoituskysymystä ☆.`,
  "bookmarks.emptySections": `Mitään ei ole vielä tallennettu. Napauta ☆ lukiessasi osiota.`,
  "bookmarks.remove": `Poista`,
  "bookmarks.savedForReview": `tallennettu tarkistettavaksi`,
  "bookmarks.savedQuestions": `Tallennetut kysymykset ({n})`,
  "bookmarks.savedSections": `Tallennetut osiot ({n})`,
  "bookmarks.search": `Hae kirjanmerkkejä…`,
  "bookmarks.title": `Kirjanmerkit`,
  "cards.answered": `Vastattu`,
  "cards.bookmarks": `tallennettu tarkistettavaksi`,
  "cards.bookmarksLabel": `Kirjanmerkit`,
  "cards.continueLearning": `Jatka oppimista`,
  "cards.correct": `oikein`,
  "cards.dailyGoal": `{done}/{total} kysymystä tänään`,
  "cards.dailyGoalLabel": `Päivittäinen tavoite`,
  "cards.dailyGoalTitle": `Daily goal`,
  "cards.mockExam.subtitle": `Ajastettu · 20 kysymystä`,
  "cards.mockExam.title": `Vale koe`,
  "cards.officialInfo.button": `Avaa canada.ca`,
  "cards.officialInfo.subtitle": `Käy osoitteessa canada.ca saadaksesi viralliset tiedot`,
  "cards.officialInfo.title": `Virallinen tieto`,
  "cards.progress": `Edistyminen`,
  "cards.progressDetails": `Yksityiskohdat`,
  "cards.recentlyStudied": `Äskettäin opiskellut`,
  "cards.sections": `Osat`,
  "cards.studyAssistant.subtitle": `Kysy mitä tahansa oppimateriaalista`,
  "cards.studyAssistant.title": `Opinto-avustaja`,
  "cards.todaysRecommendation": `Tämän päivän suositus`,
  "cards.verifiedSource.subtext": `Sisältö on tarkistettu virallisista lähteistä. Riippumaton opintotuki – ei ole sidoksissa Kanadan hallitukseen tai IRCC:hen tai ole niiden tukema.`,
  "cards.verifiedSource.title": `Vahvistettu lähde`,
  "common.back": `Takaisin`,
  "common.cancel": `Peruuta`,
  "common.close": `Sulje`,
  "common.continue": `Jatka`,
  "common.done": `Valmis`,
  "common.emptyBookmarks": `Mitään ei ole vielä tallennettu`,
  "common.emptyRecentlyStudied": `Mitään ei ole vielä tutkittu – aloita valitsemalla aihe.`,
  "common.loading": `Ladataan…`,
  "common.next": `Seuraavaksi`,
  "common.of": `/`,
  "common.previous": `Edellinen`,
  "common.retry": `Yritä uudelleen`,
  "common.save": `Tallenna`,
  "exam.allTopics": `Kaikki aiheet`,
  "exam.answeredCount": `{n} vastasi`,
  "exam.autosaveNote": `Vastauksesi tallentuvat edetessäsi, joten sovelluksen sulkeminen ei menetä edistymistäsi.`,
  "exam.cancel": `Peruuta`,
  "exam.confirm": `Vahvista`,
  "exam.confirmEnd": `{n} kysymystä on vastaamatta ja ne merkitään virheellisiksi.`,
  "exam.confirmEndTitle": `Loppuko koe?`,
  "exam.endExamEarly": `Päätä koe aikaisin`,
  "exam.examDisclaimer": `Tämä pistemäärä heijastaa vain tämän sovelluksen esimerkkikysymyksiä.`,
  "exam.finishExam": `Suorita koe`,
  "exam.newExam": `Uusi tentti`,
  "exam.noMistakes": `Ei virheitä – täydellinen tulos!`,
  "exam.pastAttempts": `Menneitä yrityksiä`,
  "exam.questionAriaLabel": `Kysymys {n}`,
  "exam.questionCount": `Kysymysten määrä`,
  "exam.questionOf": `Kysymys {n} / {total}`,
  "exam.questionPalette": `Kysymyksiä`,
  "exam.questionsOption": `{n} kysymystä`,
  "exam.resultsTitle": `Sinun pisteesi`,
  "exam.reviewMistakes": `Tarkista virheesi ({n})`,
  "exam.scoreLine": `{correct}/{total} oikein`,
  "exam.seeProgress": `Katso edistystä`,
  "exam.setupDescription": `Tämä on harjoitussimulaatio, joka on rakennettu tämän sovelluksen tutkimuskysymyksistä. Se ei ole virallinen testi, eikä se ennusta tulostasi.`,
  "exam.setupTitle": `Määritä valekoe`,
  "exam.simulationNote": `Harjoittele simulaatiota · ei virallista`,
  "exam.startExam": `Aloita koe`,
  "exam.timeLeft": `Aikaa jäljellä`,
  "exam.timedLabel": `ajoitettu`,
  "exam.timedToggle": `Ajastettu (90 sekuntia per kysymys)`,
  "exam.title": `Vale koe`,
  "exam.topicFilter": `Aihe`,
  "exam.untimedLabel": `ajastamaton`,
  "footer.disclaimer": `Citizen Prep on itsenäinen opintotuki. Ei liity Kanadan hallitukseen tai IRCC:hen tai ole niiden tukema. Se ei voi taata ohimenevää tulosta.`,
  "header.appName": `Citizen Prep`,
  "header.tagline": `Riippumaton tutkimustyökalu · Ei virallinen`,
  "hero.sectionsProgress": `{done} of {total} sections · {percent}% complete`,
  "hero.subtitle": `Itsenäinen opiskelutyökalu · Englanti ja ranska · tiliä ei tarvita`,
  "hero.title": `Valmistaudu kansalaisuuskokeeseen`,
  "nav.exam": `Tentti`,
  "nav.home": `Kotiin`,
  "nav.practice": `Harjoittele`,
  "nav.progress": `Edistyminen`,
  "nav.topics": `Aiheet`,
  "practice.allLevels": `Kaikki tasot`,
  "practice.allTopics": `Kaikki aiheet`,
  "practice.askAiAbout": `Kysy AI:ltä tästä kysymyksestä`,
  "practice.bookmarkQuestion": `Kirjanmerkki kysymys`,
  "practice.bookmarked": `Lisätty kirjanmerkkeihin`,
  "practice.checkAnswer": `Tarkista vastaus`,
  "practice.correct": `oikein`,
  "practice.demoContent": `Demosisältö`,
  "practice.difficulty": `Vaikeus`,
  "practice.easy": `Helppoa`,
  "practice.explanation": `Selitys`,
  "practice.filters": `Suodattimet`,
  "practice.hard": `Kovaa`,
  "practice.incorrect": `Ei aivan`,
  "practice.medium": `Keskikokoinen`,
  "practice.nextQuestion": `Seuraava kysymys`,
  "practice.questionCounter": `Harjoituskysymys {n}/{total}`,
  "practice.reportIssue": `Ilmoita ongelmasta`,
  "practice.title": `Harjoittele`,
  "practice.topicFilter": `Aihe`,
  "practice.tryAgain": `Yritä uudelleen`,
  "progress.accuracy": `Tarkkuus`,
  "progress.clearProgressDesc": `Tämä poistaa vastauksesi, suorituksesi, kirjanmerkkisi ja koehistoriasi tältä laitteelta. Sitä ei voi kumota.`,
  "progress.clearProgressLabel": `Tyhjennä kaikki opintojen edistyminen`,
  "progress.confirmClear": `Kyllä, tyhjennä kaikki`,
  "progress.dailyGoal": `Päivittäinen tavoite`,
  "progress.details": `Yksityiskohdat`,
  "progress.examHistory": `Tenttihistoria`,
  "progress.noExams": `Ei vielä kokeita.`,
  "progress.noWrongAnswers": `Ei vääriä vastauksia tarkastettavaksi juuri nyt.`,
  "progress.overview": `Yleiskatsaus`,
  "progress.perTopic": `Aihekohtaisesti`,
  "progress.questionsAnswered": `Kysymyksiin vastattu`,
  "progress.reset": `Nollaa`,
  "progress.retryTopic": `Yritä tätä aihetta uudelleen`,
  "progress.sectionsDone": `Osat suoritettu`,
  "progress.suggestedNext": `Ehdotettu seuraavaksi: {topic}`,
  "progress.title": `Edistyminen`,
  "progress.topicCompletion": `Aiheen viimeistely`,
  "report.detailsPlaceholder": `Kerro meille lisää (valinnainen)`,
  "report.incorrectAnswer": `Väärä vastaus`,
  "report.outdatedInfo": `Vanhentunutta tietoa`,
  "report.submit": `Lähetä raportti`,
  "report.technicalIssue": `Tekninen ongelma`,
  "report.thanks": `Kiitos – raportit tallennetaan paikallisesti tälle laitteelle.`,
  "report.translationProblem": `Käännösongelma`,
  "report.unclearExplanation": `Selitys peu claire`,
  "settings.about": `Tietoja tästä sovelluksesta`,
  "settings.appInterfaceLanguage": `Sovelluksen käyttöliittymän kieli`,
  "settings.clearProgress": `Selkeää edistystä`,
  "settings.clearProgressConfirm": `Oletko varma? Tämä poistaa kaiken edistymisesi.`,
  "settings.interfaceDescription": `Valikot, painikkeet ja navigointi.`,
  "settings.language": `Kieli`,
  "settings.machineNote": `Ihmisarvostelija ei ole tarkistanut konekäännettyä sisältöä. Mitään tässä ei merkitä arvostetuksi, ellei sitä ole todella arvosteltu.`,
  "settings.machineTranslatedBadge": `Konekäännetty`,
  "settings.manageProgress": `Hallinnoi edistymistietojasi`,
  "settings.notAvailable": `Ei vielä saatavilla`,
  "settings.officialGuideLink": `Virallinen opinto-opas`,
  "settings.officialTestLink": `Viralliset kansalaisuustestin tiedot`,
  "settings.privacy": `Yksityisyys`,
  "settings.privacyText": `Vastauksesi, kirjanmerkkisi ja asetuksesi tallennetaan vain tälle laitteelle. Tiliä ei tarvita. Opintoavustajalle esittämäsi kysymykset lähetetään tekoälypalveluun vastausten luomiseksi.`,
  "settings.reviewedBadge": `Arvosteltu`,
  "settings.studyContentLanguage": `Opintosisällön kieli`,
  "settings.studyDescription": `Tekstin ja selitysten oppiminen. Voit lukea yhdellä kielellä ja navigoida toisella kielellä.`,
  "settings.textSize": `Tekstin koko`,
  "settings.title": `Asetukset`,
  "topics.askAssistant": `Kysy tästä osiosta avustajalta`,
  "topics.bookmarkSection": `Kirjanmerkkiosio`,
  "topics.bookmarkedSection": `Lisätty kirjanmerkkeihin`,
  "topics.completed": `Valmis`,
  "topics.continueLearningCard": `Jatka oppimista`,
  "topics.demoSourceNote": `Alkuperäinen esimerkkikysymys – ei virallinen koekysymys`,
  "topics.lastVerified": `Viimeksi vahvistettu {date}`,
  "topics.markComplete": `Merkitse valmiiksi`,
  "topics.markIncomplete": `Merkitse keskeneräiseksi`,
  "topics.minRead": `{n} min lukeminen`,
  "topics.next": `Seuraavaksi`,
  "topics.openOfficialPage": `Avaa virallinen sivu`,
  "topics.paraphrasedSourceNote": `Parafraasoitu virallisesta materiaalista`,
  "topics.practiceTopic": `Harjoittele tätä aihetta`,
  "topics.previous": `Edellinen`,
  "topics.reportIssue": `Ilmoita ongelmasta`,
  "topics.reviewedOn": `arvosteltu {date}`,
  "topics.reviewedTranslation": `Tarkistettu käännös`,
  "topics.section": `osio`,
  "topics.sections": `osiot`,
  "topics.source": `Lähde`,
  "topics.sourcesDescription": `Tässä oleva tutkimusteksti on muutettu Kanadan hallituksen kansalaisuusopinto-oppaasta, ja se on tarkistettu ilmoitettuina päivämäärinä. Harjoituskysymykset tutkitaan virallisesta opinto-oppaasta.`,
  "topics.sourcesHeading": `Sisältölähteet ja arvostelupäivät`,
  "topics.studyLanguageLabel": `Opintosisällön kieli`,
  "topics.title": `Opiskeluaiheita`,
  "topics.vocabulary": `Sanasto`,
};
