// UI strings for 'fr' — chunk of strings.generated.ts. DO NOT EDIT BY HAND.
import type { StringKey } from "../strings.generated";

export const fr: Record<StringKey, string> = {
  "actions.askAi": `Poser une question`,
  "actions.mockExam": `Examen blanc`,
  "actions.practice": `Pratique`,
  "actions.quickActions": `Actions rapides`,
  "actions.study": `Étudier`,
  "assistant.aiEyebrow": `Assistant d'étude IA`,
  "assistant.answerLanguage": `Langue de réponse`,
  "assistant.charLimit": `{n} caractères restants`,
  "assistant.checkingMaterial": `Vérification du matériel d'étude…`,
  "assistant.clearChat": `Effacer le chat`,
  "assistant.copied": `Copié`,
  "assistant.copy": `Copier`,
  "assistant.description": `Les réponses sont générées par l'IA en utilisant uniquement le matériel d'étude de cette application.`,
  "assistant.enFrancais": `En français`,
  "assistant.error": `Une erreur s'est produite. Veuillez réessayer.`,
  "assistant.fromAppContent": `D'après le contenu approuvé de l'application`,
  "assistant.groundedBadge": `Basé sur les sources`,
  "assistant.helpful": `Utile`,
  "assistant.inputPlaceholder": `Posez une question sur la citoyenneté canadienne…`,
  "assistant.myAppLanguage": `Ma langue d'application`,
  "assistant.notCovered": `Non couvert — voir le guide officiel`,
  "assistant.notHelpful": `Pas utile`,
  "assistant.openAssistant": `Ouvrir l'assistant d'étude`,
  "assistant.openLink": `Ouvrir l'assistant`,
  "assistant.practiceThis": `Pratiquez ceci`,
  "assistant.questionAriaLabel": `Votre question`,
  "assistant.reportIncorrect": `Signaler une réponse incorrecte`,
  "assistant.send": `Envoyer`,
  "assistant.showSource": `Afficher la source`,
  "assistant.simpleEnglish": `Anglais simple`,
  "assistant.source": `Source`,
  "assistant.starter1": `Quelles sont les trois parties du Parlement ?`,
  "assistant.starter2": `Expliquez la Charte en termes simples`,
  "assistant.starter3": `Qui représente le Roi au Canada ?`,
  "assistant.starter4": `Que couvre le test de connaissances ?`,
  "assistant.suggestedQuestions": `Questions suggérées`,
  "assistant.thinking": `Réflexion…`,
  "assistant.title": `Assistant d'étude`,
  "assistant.tryAgain": `Réessayer`,
  "assistant.tryAsking": `Essayez de demander :`,
  "assistant.vocabularyLabel": `Vocabulaire :`,
  "assistant.whyItMatters": `Pourquoi c'est important pour l'examen`,
  "auth.account": `Compte`,
  "auth.checkEmail": `Vérifiez votre e-mail pour confirmer votre compte, puis connectez-vous.`,
  "auth.close": `Fermer`,
  "auth.codeLabel": `Code de vérification`,
  "auth.codeResent": `Nouveau code envoyé. Vérifiez votre e-mail.`,
  "auth.codeSent": `Code envoyé ! Vérifiez votre e-mail et saisissez le code à 6 chiffres.`,
  "auth.createAccount": `Créer un compte`,
  "auth.dataDeletedMsg": `Vos données de progression et de profil ont été supprimées.`,
  "auth.deleteConfirm": `Touchez à nouveau pour supprimer définitivement`,
  "auth.deleteData": `Supprimer mes données`,
  "auth.email": `E-mail`,
  "auth.haveAccount": `Déjà un compte ?`,
  "auth.mfaCodeLabel": `Code d'authentification`,
  "auth.mfaDisable": `Désactiver la 2FA`,
  "auth.mfaDisabledMsg": `L'authentification à deux facteurs est maintenant DÉSACTIVÉE.`,
  "auth.mfaEnable": `Activer la 2FA`,
  "auth.mfaEnabledMsg": `L'authentification à deux facteurs est maintenant ACTIVÉE pour votre compte.`,
  "auth.mfaPendingWarn": `Code 2FA encore requis pour terminer la connexion.`,
  "auth.mfaPrompt": `Ce compte utilise la 2FA — saisissez le code de votre application d'authentification.`,
  "auth.mfaScanHint": `Scannez ce QR code avec votre application d'authentification (Google Authenticator, Authy, 1Password…), puis saisissez le code à 6 chiffres affiché.`,
  "auth.mfaSetupTitle": `Configurer l'authentification à deux facteurs`,
  "auth.mfaSubtitle": `Saisissez le code à 6 chiffres de votre application d'authentification.`,
  "auth.mfaTitle": `Authentification à deux facteurs`,
  "auth.noAccount": `Pas encore de compte ?`,
  "auth.password": `Mot de passe`,
  "auth.passwordHint": `Au moins 6 caractères`,
  "auth.privacy": `Confidentialité`,
  "auth.privacyNote": `Votre e-mail et votre progression sont privés — vous seul pouvez les voir.`,
  "auth.resendCode": `Renvoyer le code`,
  "auth.security": `Sécurité`,
  "auth.signIn": `Se connecter`,
  "auth.signOut": `Se déconnecter`,
  "auth.signUp": `S'inscrire`,
  "auth.subtitle": `Sauvegardez votre progression sur tous vos appareils. Vos données restent privées.`,
  "auth.title": `Compte`,
  "auth.verify": `Vérifier`,
  "auth.verifyCodeSubtitle": `Nous avons envoyé un code à 6 chiffres à votre e-mail. Saisissez-le ci-dessous pour terminer l'inscription.`,
  "auth.verifyCodeTitle": `Saisissez votre code`,
  "auth.working": `Veuillez patienter…`,
  "bookmarks.continueStudying": `Continuer à étudier`,
  "bookmarks.empty": `Aucun favori pour le moment. Touchez l'étoile sur une question pour l'enregistrer et la réviser plus tard.`,
  "bookmarks.emptyQuestions": `Rien enregistré pour le moment. Touchez l'icône de signet sur une question pour l'enregistrer ici.`,
  "bookmarks.emptySections": `Rien enregistré pour le moment. Touchez l'icône de signet pendant la lecture d'une section pour l'enregistrer ici.`,
  "bookmarks.remove": `Supprimer`,
  "bookmarks.savedForReview": `enregistrés pour révision`,
  "bookmarks.savedQuestions": `Questions enregistrées ({n})`,
  "bookmarks.savedSections": `Sections enregistrées ({n})`,
  "bookmarks.search": `Rechercher dans les signets…`,
  "bookmarks.title": `Favoris`,
  "cards.answered": `Répondues`,
  "cards.bookmarks": `enregistrés pour révision`,
  "cards.bookmarksLabel": `Favoris`,
  "cards.continueLearning": `Poursuivre l'apprentissage`,
  "cards.correct": `Correctes`,
  "cards.dailyGoal": `{done}/{total} questions aujourd'hui`,
  "cards.dailyGoalLabel": `Objectif quotidien`,
  "cards.dailyGoalTitle": `Objectif quotidien`,
  "cards.mockExam.subtitle": `Chronométré · 20 questions`,
  "cards.mockExam.title": `Examen blanc`,
  "cards.officialInfo.button": `Ouvrir canada.ca`,
  "cards.officialInfo.subtitle": `Consultez canada.ca pour les détails officiels`,
  "cards.officialInfo.title": `Informations officielles`,
  "cards.progress": `Progrès`,
  "cards.progressDetails": `Détails`,
  "cards.recentlyStudied": `Récemment étudié`,
  "cards.sections": `Sections`,
  "cards.studyAssistant.subtitle": `Posez vos questions sur la matière d'étude`,
  "cards.studyAssistant.title": `Assistant d'étude`,
  "cards.todaysRecommendation": `Recommandation du jour`,
  "cards.verifiedSource.subtext": `Contenu vérifié par rapport aux sources officielles. Outil d'étude indépendant — non affilié au gouvernement du Canada ni à IRCC, et non approuvé par eux.`,
  "cards.verifiedSource.title": `Source vérifiée`,
  "common.back": `Retour`,
  "common.cancel": `Annuler`,
  "common.close": `Fermer`,
  "common.continue": `Continuer`,
  "common.done": `Terminé`,
  "common.emptyBookmarks": `Rien d'enregistré pour le moment`,
  "common.emptyRecentlyStudied": `Rien d'étudié pour le moment — choisissez un sujet pour commencer.`,
  "common.loading": `Chargement…`,
  "common.next": `Suivant`,
  "common.of": `sur`,
  "common.previous": `Précédent`,
  "common.retry": `Réessayer`,
  "common.save": `Enregistrer`,
  "exam.allTopics": `Tous les sujets`,
  "exam.answeredCount": `{n} répondues`,
  "exam.autosaveNote": `Vos réponses sont enregistrées pour conserver votre progression si vous partez.`,
  "exam.cancel": `Annuler`,
  "exam.confirm": `Confirmer`,
  "exam.confirmEnd": `{n} questions sont sans réponse et seront marquées comme incorrectes.`,
  "exam.confirmEndTitle": `Terminer l'examen ?`,
  "exam.endExamEarly": `Terminer l'examen`,
  "exam.examDisclaimer": `Ce résultat reflète uniquement les questions d'exemple de cette application.`,
  "exam.finishExam": `Terminer l'examen`,
  "exam.newExam": `Nouvel examen`,
  "exam.noMistakes": `Aucune erreur — score parfait !`,
  "exam.pastAttempts": `Tentatives précédentes`,
  "exam.questionAriaLabel": `Question {n}`,
  "exam.questionCount": `Nombre de questions`,
  "exam.questionOf": `Question {n} sur {total}`,
  "exam.questionPalette": `Questions`,
  "exam.questionsOption": `{n} questions`,
  "exam.resultsTitle": `Votre résultat`,
  "exam.reviewMistakes": `Revoir vos erreurs ({n})`,
  "exam.scoreLine": `{correct} sur {total} bonnes réponses`,
  "exam.seeProgress": `Voir la progression`,
  "exam.setupDescription": `Ceci est une simulation d'entraînement construite à partir des questions d'étude de cette application.`,
  "exam.setupTitle": `Configurez votre examen blanc`,
  "exam.simulationNote": `Simulation d'entraînement · non officiel`,
  "exam.startExam": `Commencer l'examen`,
  "exam.timeLeft": `Temps restant`,
  "exam.timedLabel": `chronométré`,
  "exam.timedToggle": `Chronométré (90 secondes par question)`,
  "exam.title": `Examen blanc`,
  "exam.topicFilter": `Sujet`,
  "exam.untimedLabel": `non chronométré`,
  "footer.disclaimer": `Citizen Prep est un outil d'étude indépendant. Non affilié au gouvernement du Canada ni à IRCC, et non approuvé par eux. Il ne peut garantir la réussite à l'examen.`,
  "header.appName": `Citizen Prep`,
  "header.tagline": `Outil d'étude indépendant · Non officiel`,
  "hero.sectionsProgress": `{done} sur {total} sections · {percent}% terminé`,
  "hero.subtitle": `Outil d'étude indépendant · Anglais et français · aucun compte requis`,
  "hero.title": `Préparez votre examen de citoyenneté`,
  "nav.exam": `Examen`,
  "nav.home": `Accueil`,
  "nav.practice": `Pratique`,
  "nav.progress": `Progrès`,
  "nav.topics": `Sujets`,
  "practice.allLevels": `Tous les niveaux`,
  "practice.allTopics": `Tous les sujets`,
  "practice.askAiAbout": `Poser une question à l'IA sur cette question`,
  "practice.bookmarkQuestion": `Ajouter aux favoris`,
  "practice.bookmarked": `Ajouté aux favoris`,
  "practice.checkAnswer": `Vérifier la réponse`,
  "practice.correct": `Correct`,
  "practice.demoContent": `Contenu de démonstration`,
  "practice.difficulty": `Difficulté`,
  "practice.easy": `Facile`,
  "practice.explanation": `Explication`,
  "practice.filters": `Filtres`,
  "practice.hard": `Difficile`,
  "practice.incorrect": `Pas tout à fait`,
  "practice.medium": `Moyen`,
  "practice.nextQuestion": `Question suivante`,
  "practice.questionCounter": `Question de pratique {n} sur {total}`,
  "practice.reportIssue": `Signaler un problème`,
  "practice.title": `Pratique`,
  "practice.topicFilter": `Sujet`,
  "practice.tryAgain": `Réessayer`,
  "progress.accuracy": `Précision`,
  "progress.clearProgressDesc": `Cela supprimera vos réponses, achèvements, signets et historique d'examens.`,
  "progress.clearProgressLabel": `Effacer toute la progression d'étude`,
  "progress.confirmClear": `Oui, tout effacer`,
  "progress.dailyGoal": `Objectif quotidien`,
  "progress.details": `Détails`,
  "progress.examHistory": `Historique des examens`,
  "progress.noExams": `Aucun examen passé pour le moment.`,
  "progress.noWrongAnswers": `Aucune mauvaise réponse à revoir pour le moment.`,
  "progress.overview": `Aperçu`,
  "progress.perTopic": `Par sujet`,
  "progress.questionsAnswered": `Questions répondues`,
  "progress.reset": `Réinitialiser`,
  "progress.retryTopic": `Réessayer ce sujet`,
  "progress.sectionsDone": `Sections terminées`,
  "progress.suggestedNext": `Suggestion suivante : {topic}`,
  "progress.title": `Progrès`,
  "progress.topicCompletion": `Achèvement du sujet`,
  "report.detailsPlaceholder": `Dites-nous en plus (facultatif)`,
  "report.incorrectAnswer": `Réponse incorrecte`,
  "report.outdatedInfo": `Informations obsolètes`,
  "report.submit": `Envoyer le rapport`,
  "report.technicalIssue": `Problème technique`,
  "report.thanks": `Merci — les rapports sont stockés localement sur cet appareil.`,
  "report.translationProblem": `Problème de traduction`,
  "report.unclearExplanation": `Explication peu claire`,
  "settings.about": `À propos de cette application`,
  "settings.appInterfaceLanguage": `Langue de l'interface`,
  "settings.clearProgress": `Effacer la progression`,
  "settings.clearProgressConfirm": `Êtes-vous sûr ? Cela supprimera toute votre progression.`,
  "settings.interfaceDescription": `Menus, boutons et navigation.`,
  "settings.language": `Langue`,
  "settings.machineNote": `Le contenu traduit automatiquement n'a pas été révisé par un humain.`,
  "settings.machineTranslatedBadge": `Traduit automatiquement`,
  "settings.manageProgress": `Gérer vos données de progression`,
  "settings.notAvailable": `Bientôt disponible`,
  "settings.officialGuideLink": `Guide d'étude officiel`,
  "settings.officialTestLink": `Informations officielles sur le test de citoyenneté`,
  "settings.privacy": `Confidentialité`,
  "settings.privacyText": `Vos réponses, signets et paramètres sont stockés uniquement sur cet appareil.`,
  "settings.reviewedBadge": `Révisé`,
  "settings.studyContentLanguage": `Langue du contenu d'étude`,
  "settings.studyDescription": `Textes d'étude et explications. Vous pouvez lire dans une langue et pratiquer dans une autre.`,
  "settings.textSize": `Taille du texte`,
  "settings.title": `Paramètres`,
  "topics.askAssistant": `Poser une question à l'assistant sur cette section`,
  "topics.bookmarkSection": `Ajouter un signet à la section`,
  "topics.bookmarkedSection": `En signet`,
  "topics.completed": `Terminé`,
  "topics.continueLearningCard": `Poursuivre l'apprentissage`,
  "topics.demoSourceNote": `Question d'exemple originale — pas une question officielle`,
  "topics.lastVerified": `Dernière vérification : {date}`,
  "topics.markComplete": `Marquer comme terminé`,
  "topics.markIncomplete": `Marquer comme non terminé`,
  "topics.minRead": `{n} min de lecture`,
  "topics.next": `Suivant`,
  "topics.openOfficialPage": `Ouvrir la page officielle`,
  "topics.paraphrasedSourceNote": `Paraphrasé du matériel officiel`,
  "topics.practiceTopic": `Pratiquer ce sujet`,
  "topics.previous": `Précédent`,
  "topics.reportIssue": `Signaler un problème`,
  "topics.reviewedOn": `Révisé le {date}`,
  "topics.reviewedTranslation": `Traduction révisée`,
  "topics.section": `Section`,
  "topics.sections": `sections`,
  "topics.source": `Source`,
  "topics.sourcesDescription": `Le texte d'étude ici est une paraphrase du guide d'étude officiel.`,
  "topics.sourcesHeading": `Sources du contenu et dates de révision`,
  "topics.studyLanguageLabel": `Langue du contenu d'étude`,
  "topics.title": `Sujets d'étude`,
  "topics.vocabulary": `Vocabulaire`,
};
