// UI strings for 'fr' — chunk of strings.generated.ts. DO NOT EDIT BY HAND.
import type { StringKey } from "../strings.generated";

export const fr: Record<StringKey, string> = {
  "actions.askAi": `Poser une question`,
  "actions.mockExam": `Examen blanc`,
  "actions.practice": `Pratique`,
  "actions.quickActions": `Actions rapides`,
  "actions.study": `Étudier`,
  "assistant.aiEyebrow": `Assistant d'étude IA`,
  "assistant.answerLanguage": `Langue de réponse`,
  "assistant.charLimit": `{n} caractères restants`,
  "assistant.checkingMaterial": `Vérification du matériel d'étude…`,
  "assistant.clearChat": `Effacer la discussion`,
  "assistant.copied": `Copié`,
  "assistant.copy": `Copier`,
  "assistant.description": `Les réponses sont rédigées par l'IA en utilisant uniquement le matériel d'étude de cette application, avec les sources indiquées. L'IA peut encore faire des erreurs — vérifiez les détails importants sur les pages officielles du gouvernement du Canada. Ce n'est pas un avis juridique ni un conseil en immigration.`,
  "assistant.enFrancais": `En français`,
  "assistant.error": `Une erreur s'est produite. Veuillez réessayer.`,
  "assistant.fromAppContent": `D'après le contenu approuvé de l'application`,
  "assistant.groundedBadge": `Basé sur les sources`,
  "assistant.helpful": `Utile`,
  "assistant.inputPlaceholder": `Posez une question sur la citoyenneté canadienne…`,
  "assistant.myAppLanguage": `Ma langue d'application`,
  "assistant.notCovered": `Non couvert — voir la page officielle`,
  "assistant.notHelpful": `Pas utile`,
  "assistant.openAssistant": `Ouvrir l'assistant d'étude`,
  "assistant.openLink": `Ouvrir l'assistant`,
  "assistant.practiceThis": `Pratiquez ceci`,
  "assistant.questionAriaLabel": `Votre question`,
  "assistant.reportIncorrect": `Signaler une réponse incorrecte`,
  "assistant.send": `Envoyer`,
  "assistant.showSource": `Voir la source`,
  "assistant.simpleEnglish": `Anglais simple`,
  "assistant.source": `Source`,
  "assistant.starter1": `Quelles sont les trois parties du Parlement ?`,
  "assistant.starter2": `Expliquez la Charte simplement`,
  "assistant.starter3": `Qui représente le Roi au Canada ?`,
  "assistant.starter4": `Que couvre l'examen de connaissances ?`,
  "assistant.suggestedQuestions": `Questions suggérées`,
  "assistant.thinking": `Réflexion…`,
  "assistant.title": `Assistant d'étude`,
  "assistant.tryAgain": `Réessayer`,
  "assistant.tryAsking": `Essayez de demander :`,
  "assistant.vocabularyLabel": `Vocabulaire :`,
  "assistant.whyItMatters": `Pourquoi c'est important pour l'examen`,
  "bookmarks.continueStudying": `Continuer l'étude`,
  "bookmarks.empty": `Aucun favori pour le moment. Touchez l'étoile sur une question pour l'enregistrer et la réviser plus tard.`,
  "bookmarks.emptyQuestions": `Rien d'enregistré pour le moment. Touchez ☆ sur une question d'entraînement.`,
  "bookmarks.emptySections": `Rien d'enregistré pour le moment. Touchez ☆ pendant la lecture d'une section.`,
  "bookmarks.remove": `Supprimer`,
  "bookmarks.savedForReview": `enregistrés pour révision`,
  "bookmarks.savedQuestions": `Questions enregistrées ({n})`,
  "bookmarks.savedSections": `Sections enregistrées ({n})`,
  "bookmarks.search": `Rechercher dans les favoris…`,
  "bookmarks.title": `Favoris`,
  "cards.answered": `Répondues`,
  "cards.bookmarks": `enregistrés pour révision`,
  "cards.bookmarksLabel": `Favoris`,
  "cards.continueLearning": `Poursuivre l'apprentissage`,
  "cards.correct": `Correctes`,
  "cards.dailyGoal": `{done}/{total} questions aujourd'hui`,
  "cards.dailyGoalLabel": `Objectif quotidien`,
  "cards.dailyGoalTitle": `Objectif du jour`,
  "cards.mockExam.subtitle": `Chronométré · 20 questions`,
  "cards.mockExam.title": `Examen blanc`,
  "cards.officialInfo.button": `Ouvrir canada.ca`,
  "cards.officialInfo.subtitle": `Consultez canada.ca pour les détails officiels`,
  "cards.officialInfo.title": `Informations officielles`,
  "cards.progress": `Progrès`,
  "cards.progressDetails": `Détails`,
  "cards.recentlyStudied": `Récemment étudié`,
  "cards.sections": `Sections`,
  "cards.studyAssistant.subtitle": `Posez vos questions sur la matière d'étude`,
  "cards.studyAssistant.title": `Assistant d'étude`,
  "cards.todaysRecommendation": `Recommandation du jour`,
  "cards.verifiedSource.subtext": `Contenu vérifié par rapport aux sources officielles. Outil d'étude indépendant — non affilié au gouvernement du Canada ni à IRCC, et non approuvé par eux.`,
  "cards.verifiedSource.title": `Source vérifiée`,
  "common.back": `Retour`,
  "common.cancel": `Annuler`,
  "common.close": `Fermer`,
  "common.continue": `Continuer`,
  "common.done": `Terminé`,
  "common.emptyBookmarks": `Rien d'enregistré pour le moment`,
  "common.emptyRecentlyStudied": `Rien d'étudié pour le moment — choisissez un sujet pour commencer.`,
  "common.loading": `Chargement…`,
  "common.next": `Suivant`,
  "common.of": `sur`,
  "common.previous": `Précédent`,
  "common.retry": `Réessayer`,
  "common.save": `Enregistrer`,
  "exam.allTopics": `Tous les sujets`,
  "exam.answeredCount": `{n} répondues`,
  "exam.autosaveNote": `Vos réponses sont enregistrées au fur et à mesure, donc fermer l'application ne fera pas perdre votre progression.`,
  "exam.cancel": `Annuler`,
  "exam.confirm": `Confirmer`,
  "exam.confirmEnd": `{n} questions sont sans réponse et seront marquées comme incorrectes.`,
  "exam.confirmEndTitle": `Terminer l'examen ?`,
  "exam.endExamEarly": `Terminer l'examen`,
  "exam.examDisclaimer": `Ce résultat reflète uniquement les questions d'exemple de cette application.`,
  "exam.finishExam": `Terminer l'examen`,
  "exam.newExam": `Nouvel examen`,
  "exam.noMistakes": `Aucune erreur — score parfait !`,
  "exam.pastAttempts": `Tentatives précédentes`,
  "exam.questionAriaLabel": `Question {n}`,
  "exam.questionCount": `Nombre de questions`,
  "exam.questionOf": `Question {n} sur {total}`,
  "exam.questionPalette": `Questions`,
  "exam.questionsOption": `{n} questions`,
  "exam.resultsTitle": `Votre résultat`,
  "exam.reviewMistakes": `Revoir vos erreurs ({n})`,
  "exam.scoreLine": `{correct} sur {total} bonnes réponses`,
  "exam.seeProgress": `Voir la progression`,
  "exam.setupDescription": `Ceci est une simulation d'entraînement basée sur les questions d'étude de cette application. Ce n'est pas l'examen officiel et ne prédit pas votre résultat.`,
  "exam.setupTitle": `Configurez votre examen blanc`,
  "exam.simulationNote": `Simulation d'entraînement · non officiel`,
  "exam.startExam": `Commencer l'examen`,
  "exam.timeLeft": `Temps restant`,
  "exam.timedLabel": `chronométré`,
  "exam.timedToggle": `Chronométré (90 secondes par question)`,
  "exam.title": `Examen blanc`,
  "exam.topicFilter": `Sujet`,
  "exam.untimedLabel": `non chronométré`,
  "footer.disclaimer": `Citizen Prep est un outil d'étude indépendant. Non affilié au gouvernement du Canada ni à IRCC, et non approuvé par eux. Il ne peut garantir la réussite à l'examen.`,
  "header.appName": `Citizen Prep`,
  "header.tagline": `Outil d'étude indépendant · Non officiel`,
  "hero.sectionsProgress": `{done} sections sur {total} · {percent} % terminé`,
  "hero.subtitle": `Outil d'étude indépendant · 40 langues · aucun compte requis`,
  "hero.title": `Préparez votre examen de citoyenneté`,
  "nav.exam": `Examen`,
  "nav.home": `Accueil`,
  "nav.practice": `Pratique`,
  "nav.progress": `Progrès`,
  "nav.topics": `Sujets`,
  "practice.allLevels": `Tous les niveaux`,
  "practice.allTopics": `Tous les sujets`,
  "practice.askAiAbout": `Poser une question à l'IA sur cette question`,
  "practice.bookmarkQuestion": `Ajouter aux favoris`,
  "practice.bookmarked": `Ajouté aux favoris`,
  "practice.checkAnswer": `Vérifier la réponse`,
  "practice.correct": `Correct`,
  "practice.demoContent": `Contenu de démonstration`,
  "practice.difficulty": `Difficulté`,
  "practice.easy": `Facile`,
  "practice.explanation": `Explication`,
  "practice.filters": `Filtres`,
  "practice.hard": `Difficile`,
  "practice.incorrect": `Pas tout à fait`,
  "practice.medium": `Moyen`,
  "practice.nextQuestion": `Question suivante`,
  "practice.questionCounter": `Question de pratique {n} sur {total}`,
  "practice.reportIssue": `Signaler un problème`,
  "practice.title": `Entraînement`,
  "practice.topicFilter": `Sujet`,
  "practice.tryAgain": `Réessayer`,
  "progress.accuracy": `Précision`,
  "progress.clearProgressDesc": `Cela supprime vos réponses, complétions, favoris et historique d'examens de cet appareil. Cette action est irréversible.`,
  "progress.clearProgressLabel": `Effacer toute la progression d'étude`,
  "progress.confirmClear": `Oui, tout effacer`,
  "progress.dailyGoal": `Objectif quotidien`,
  "progress.details": `Détails`,
  "progress.examHistory": `Historique des examens`,
  "progress.noExams": `Aucun examen passé pour le moment.`,
  "progress.noWrongAnswers": `Aucune mauvaise réponse à revoir pour le moment.`,
  "progress.overview": `Aperçu`,
  "progress.perTopic": `Par sujet`,
  "progress.questionsAnswered": `Questions répondues`,
  "progress.reset": `Réinitialiser`,
  "progress.retryTopic": `Réessayer ce sujet`,
  "progress.sectionsDone": `Sections terminées`,
  "progress.suggestedNext": `Prochain suggéré : {topic}`,
  "progress.title": `Progrès`,
  "progress.topicCompletion": `Progression par sujet`,
  "report.detailsPlaceholder": `Dites-nous en plus (facultatif)`,
  "report.incorrectAnswer": `Réponse incorrecte`,
  "report.outdatedInfo": `Information périmée`,
  "report.submit": `Envoyer le signalement`,
  "report.technicalIssue": `Problème technique`,
  "report.thanks": `Merci — les signalements sont conservés localement sur cet appareil.`,
  "report.translationProblem": `Problème de traduction`,
  "report.unclearExplanation": `Explication peu claire`,
  "settings.about": `À propos de cette application`,
  "settings.appInterfaceLanguage": `Langue de l'interface`,
  "settings.clearProgress": `Effacer la progression`,
  "settings.clearProgressConfirm": `Êtes-vous sûr ? Cela supprimera toute votre progression.`,
  "settings.interfaceDescription": `Menus, boutons et navigation.`,
  "settings.language": `Langue`,
  "settings.machineNote": `Le contenu traduit automatiquement n'a pas été vérifié par un réviseur humain. Rien n'est étiqueté comme révisé sauf s'il a réellement été révisé.`,
  "settings.machineTranslatedBadge": `Traduit automatiquement`,
  "settings.manageProgress": `Gérer vos données de progression`,
  "settings.notAvailable": `Bientôt disponible`,
  "settings.officialGuideLink": `Guide d'étude officiel`,
  "settings.officialTestLink": `Informations officielles sur l'examen de citoyenneté`,
  "settings.privacy": `Confidentialité`,
  "settings.privacyText": `Vos réponses, favoris et réglages sont conservés uniquement sur cet appareil. Aucun compte n'est nécessaire. Les questions posées à l'assistant d'étude sont envoyées à un service d'IA pour générer les réponses.`,
  "settings.reviewedBadge": `Révisé`,
  "settings.studyContentLanguage": `Langue du contenu d'étude`,
  "settings.studyDescription": `Textes d'apprentissage et explications. Vous pouvez lire dans une langue tout en naviguant dans une autre.`,
  "settings.textSize": `Taille du texte`,
  "settings.title": `Paramètres`,
  "topics.askAssistant": `Poser une question à l'assistant sur cette section`,
  "topics.bookmarkSection": `Ajouter aux favoris`,
  "topics.bookmarkedSection": `Ajouté aux favoris`,
  "topics.completed": `Terminé`,
  "topics.continueLearningCard": `Poursuivre l'apprentissage`,
  "topics.demoSourceNote": `Question d'exemple originale — pas une question d'examen officielle`,
  "topics.lastVerified": `Dernière vérification : {date}`,
  "topics.markComplete": `Marquer comme terminé`,
  "topics.markIncomplete": `Marquer comme non terminé`,
  "topics.minRead": `{n} min de lecture`,
  "topics.next": `Suivant`,
  "topics.openOfficialPage": `Ouvrir la page officielle`,
  "topics.paraphrasedSourceNote": `Paraphrasé à partir de documents officiels`,
  "topics.practiceTopic": `S'entraîner sur ce sujet`,
  "topics.previous": `Précédent`,
  "topics.reportIssue": `Signaler un problème`,
  "topics.reviewedOn": `révisé le {date}`,
  "topics.reviewedTranslation": `Traduction révisée`,
  "topics.section": `Section`,
  "topics.sections": `sections`,
  "topics.source": `Source`,
  "topics.sourcesDescription": `Le texte d'étude est paraphrasé à partir du guide d'étude officiel du gouvernement du Canada et révisé aux dates indiquées. Les questions d'entraînement sont basées sur le guide d'étude officiel.`,
  "topics.sourcesHeading": `Sources du contenu et dates de révision`,
  "topics.studyLanguageLabel": `Langue du contenu d'étude`,
  "topics.title": `Sujets d'étude`,
  "topics.vocabulary": `Vocabulaire`,
};
