// UI strings for 'ga' — chunk of strings.generated.ts. DO NOT EDIT BY HAND.
import type { StringKey } from "../strings.generated";

export const ga: Record<StringKey, string> = {
  "actions.askAi": `Iarr ar AI`,
  "actions.mockExam": `Scrúdú bréige`,
  "actions.practice": `Cleachtadh`,
  "actions.quickActions": `Quick actions`,
  "actions.study": `Staidéar`,
  "assistant.aiEyebrow": `Cúntóir staidéir AI`,
  "assistant.answerLanguage": `Freagra teanga`,
  "assistant.charLimit": `{n} carachtair fágtha`,
  "assistant.checkingMaterial": `An t-ábhar staidéir á sheiceáil…`,
  "assistant.clearChat": `Glan an comhrá`,
  "assistant.copied": `Cóipeáladh`,
  "assistant.copy": `Cóip`,
  "assistant.description": `Scríobhann AI na freagraí agus úsáid á baint as ábhar staidéir na haipe seo amháin, agus léirítear na foinsí. Is féidir le AI botúin a dhéanamh fós - seiceáil sonraí tábhachtacha ar leathanaigh oifigiúla Rialtas Cheanada. Ní comhairle dlí ná inimirce.`,
  "assistant.enFrancais": `sa Fhrainc`,
  "assistant.error": `Chuaigh rud éigin mícheart. Bain triail eile as.`,
  "assistant.fromAppContent": `Ó ábhar app ceadaithe`,
  "assistant.groundedBadge": `Foinse-bhunaithe`,
  "assistant.helpful": `Cabhrach`,
  "assistant.inputPlaceholder": `Cuir ceist faoi shaoránacht Cheanada…`,
  "assistant.myAppLanguage": `Mo theanga app`,
  "assistant.notCovered": `Gan a bheith clúdaithe - féach leathanach oifigiúil`,
  "assistant.notHelpful": `Gan cabhrach`,
  "assistant.openAssistant": `Cúntóir staidéir oscailte`,
  "assistant.openLink": `Oscail cúntóir`,
  "assistant.practiceThis": `Cleachtaigh seo`,
  "assistant.questionAriaLabel": `Do cheist`,
  "assistant.reportIncorrect": `Tuairiscigh freagra mícheart`,
  "assistant.send": `Seol`,
  "assistant.showSource": `Taispeáin foinse`,
  "assistant.simpleEnglish": `Béarla simplí`,
  "assistant.source": `Foinse`,
  "assistant.starter1": `Cad iad na trí chuid den Pharlaimint?`,
  "assistant.starter2": `Mínigh an Chairt go simplí`,
  "assistant.starter3": `Cé a dhéanann ionadaíocht ar an Rí i gCeanada?`,
  "assistant.starter4": `Cad a chlúdaíonn an tástáil eolais?`,
  "assistant.suggestedQuestions": `Ceisteanna molta`,
  "assistant.thinking": `Ag smaoineamh…`,
  "assistant.title": `Cúntóir staidéir`,
  "assistant.tryAgain": `Bain triail eile as`,
  "assistant.tryAsking": `Bain triail as ag iarraidh:`,
  "assistant.vocabularyLabel": `Stór Focal:`,
  "assistant.whyItMatters": `Cén fáth go bhfuil sé tábhachtach don tástáil`,
  "auth.account": `Account`,
  "auth.checkEmail": `Check your email to confirm your account, then sign in.`,
  "auth.close": `Close`,
  "auth.codeLabel": `Verification code`,
  "auth.codeResent": `New code sent. Check your email.`,
  "auth.codeSent": `Code sent! Check your email and enter the 6-digit code.`,
  "auth.createAccount": `Create account`,
  "auth.dataDeletedMsg": `Your progress and profile data were deleted.`,
  "auth.deleteConfirm": `Tap again to permanently delete`,
  "auth.deleteData": `Delete my data`,
  "auth.email": `Email`,
  "auth.haveAccount": `Already have an account?`,
  "auth.mfaCodeLabel": `Authenticator code`,
  "auth.mfaDisable": `Disable 2FA`,
  "auth.mfaDisabledMsg": `Two-factor authentication is now OFF.`,
  "auth.mfaEnable": `Enable 2FA`,
  "auth.mfaEnabledMsg": `Two-factor authentication is now ON for your account.`,
  "auth.mfaPendingWarn": `2FA code still needed to finish signing in.`,
  "auth.mfaPrompt": `This account uses 2FA — enter the code from your authenticator app.`,
  "auth.mfaScanHint": `Scan this QR code with your authenticator app (Google Authenticator, Authy, 1Password…), then enter the 6-digit code it shows.`,
  "auth.mfaSetupTitle": `Set up two-factor authentication`,
  "auth.mfaSubtitle": `Enter the 6-digit code from your authenticator app.`,
  "auth.mfaTitle": `Two-factor authentication`,
  "auth.noAccount": `Don't have an account?`,
  "auth.password": `Password`,
  "auth.passwordHint": `At least 6 characters`,
  "auth.privacy": `Privacy`,
  "auth.privacyNote": `Your email and progress are private — only you can see them.`,
  "auth.resendCode": `Resend code`,
  "auth.security": `Security`,
  "auth.signIn": `Sign in`,
  "auth.signOut": `Sign out`,
  "auth.signUp": `Sign up`,
  "auth.subtitle": `Save your progress across devices. Your data stays private.`,
  "auth.title": `Account`,
  "auth.verify": `Verify`,
  "auth.verifyCodeSubtitle": `We sent a 6-digit code to your email. Enter it below to finish signing up.`,
  "auth.verifyCodeTitle": `Enter your code`,
  "auth.working": `Please wait…`,
  "bookmarks.continueStudying": `Lean ort ag staidéar`,
  "bookmarks.empty": `Níl aon leabharmharcanna fós. Tapáil an réalta ar aon cheist chun é a shábháil le haghaidh athbhreithniú.`,
  "bookmarks.emptyQuestions": `Ní dhéanfaidh aon ní a shábháil fós. Tapáil ☆ ar cheist chleachtaidh.`,
  "bookmarks.emptySections": `Ní dhéanfaidh aon ní a shábháil fós. Tapáil ☆ agus tú ag léamh alt.`,
  "bookmarks.remove": `Bain`,
  "bookmarks.savedForReview": `shábháil le haghaidh athbhreithnithe`,
  "bookmarks.savedQuestions": `Ceisteanna sábháilte ({n})`,
  "bookmarks.savedSections": `Codanna sábháilte ({n})`,
  "bookmarks.search": `Cuardaigh leabharmharcanna…`,
  "bookmarks.title": `Leabharmharcanna`,
  "cards.answered": `D'fhreagair`,
  "cards.bookmarks": `shábháil le haghaidh athbhreithnithe`,
  "cards.bookmarksLabel": `Leabharmharcanna`,
  "cards.continueLearning": `Leanúint ar aghaidh ag foghlaim`,
  "cards.correct": `Ceart`,
  "cards.dailyGoal": `{done}/{total} questions today`,
  "cards.dailyGoalLabel": `Sprioc laethúil`,
  "cards.dailyGoalTitle": `Daily goal`,
  "cards.mockExam.subtitle": `Tráthúil · 20 ceist`,
  "cards.mockExam.title": `Scrúdú bréige`,
  "cards.officialInfo.button": `Oscail canada.ca`,
  "cards.officialInfo.subtitle": `Tabhair cuairt ar canada.ca le haghaidh sonraí oifigiúla`,
  "cards.officialInfo.title": `Eolas oifigiúil`,
  "cards.progress": `Dul chun cinn`,
  "cards.progressDetails": `Sonraí`,
  "cards.recentlyStudied": `Le déanaí staidéar`,
  "cards.sections": `Ailt`,
  "cards.studyAssistant.subtitle": `Cuir ceist ar bith faoin ábhar staidéir`,
  "cards.studyAssistant.title": `Cúntóir staidéir`,
  "cards.todaysRecommendation": `Moladh an lae inniu`,
  "cards.verifiedSource.subtext": `Ábhar seiceáilte i gcoinne foinsí oifigiúla. Cúnamh staidéir neamhspleách — nach bhfuil cleamhnaithe le nó formhuinithe ag Rialtas Cheanada nó IRCC.`,
  "cards.verifiedSource.title": `Foinse deimhnithe`,
  "common.back": `Ar ais`,
  "common.cancel": `Cealaigh`,
  "common.close": `Dún`,
  "common.continue": `Lean ort`,
  "common.done": `Déanta`,
  "common.emptyBookmarks": `Ní dhéanfaidh aon ní a shábháil fós`,
  "common.emptyRecentlyStudied": `Níl aon staidéar déanta fós - roghnaigh topaic le tosú.`,
  "common.loading": `Á lódáil…`,
  "common.next": `Ar aghaidh`,
  "common.of": `de`,
  "common.previous": `Roimhe Seo`,
  "common.retry": `Bain triail eile as`,
  "common.save": `Sábháil`,
  "exam.allTopics": `Gach ábhar`,
  "exam.answeredCount": `D'fhreagair {n}`,
  "exam.autosaveNote": `Sábháiltear do fhreagraí de réir mar a théann tú ar aghaidh, mar sin ní chaillfear do dhul chun cinn má dhún tú an aip.`,
  "exam.cancel": `Cealaigh`,
  "exam.confirm": `Deimhnigh`,
  "exam.confirmEnd": `Tá {n} ceist gan freagra agus marcálfar iad mícheart.`,
  "exam.confirmEndTitle": `Scrúdú deireadh?`,
  "exam.endExamEarly": `Críochnaigh an scrúdú go luath`,
  "exam.examDisclaimer": `Léiríonn an scór seo ceisteanna samplacha na haipe seo amháin.`,
  "exam.finishExam": `Críochnaigh scrúdú`,
  "exam.newExam": `Scrúdú nua`,
  "exam.noMistakes": `Gan botúin - scór foirfe!`,
  "exam.pastAttempts": `Iarrachtaí san am atá caite`,
  "exam.questionAriaLabel": `Ceist {n}`,
  "exam.questionCount": `Líon ceisteanna`,
  "exam.questionOf": `Question {n} of {total}`,
  "exam.questionPalette": `Ceisteanna`,
  "exam.questionsOption": `{n} ceisteanna`,
  "exam.resultsTitle": `Do scór`,
  "exam.reviewMistakes": `Athbhreithnigh do bhotúin ({n})`,
  "exam.scoreLine": `{correct} de {total} ceart`,
  "exam.seeProgress": `Féach ar an dul chun cinn`,
  "exam.setupDescription": `Is insamhalta cleachtais é seo a tógadh ó cheisteanna staidéir an aip seo. Ní hé an tástáil oifigiúil í agus ní dhéanann sé do thoradh a thuar.`,
  "exam.setupTitle": `Socraigh do scrúdú bréige`,
  "exam.simulationNote": `Insamhalta cleachtaidh · ní oifigiúil`,
  "exam.startExam": `Tosaigh scrúdú`,
  "exam.timeLeft": `Am fágtha`,
  "exam.timedLabel": `uainithe`,
  "exam.timedToggle": `Tráthúil (90 soicind in aghaidh na ceiste)`,
  "exam.title": `Scrúdú bréige`,
  "exam.topicFilter": `Topaic`,
  "exam.untimedLabel": `gan am`,
  "footer.disclaimer": `Is áis neamhspleách staidéir é Citizen Prep. Nach bhfuil cleamhnaithe le nó formhuinithe ag Rialtas Cheanada nó IRCC. Ní féidir leis toradh a rith a ráthú.`,
  "header.appName": `Citizen Prep`,
  "header.tagline": `Uirlis staidéir neamhspleách · Neamhoifigiúil`,
  "hero.sectionsProgress": `{done} of {total} sections · {percent}% complete`,
  "hero.subtitle": `Uirlis neamhspleách staidéir · Béarla & Fraincis · níl gá le cuntas`,
  "hero.title": `Ullmhaigh do thástáil saoránachta`,
  "nav.exam": `Scrúdú`,
  "nav.home": `Baile`,
  "nav.practice": `Cleachtadh`,
  "nav.progress": `Dul chun cinn`,
  "nav.topics": `Ábhair`,
  "practice.allLevels": `Gach leibhéal`,
  "practice.allTopics": `Gach ábhar`,
  "practice.askAiAbout": `Cuir ceist ar AI faoin gceist seo`,
  "practice.bookmarkQuestion": `Ceist leabharmharc`,
  "practice.bookmarked": `Leabharmharcáilte`,
  "practice.checkAnswer": `Seiceáil an freagra`,
  "practice.correct": `Ceart`,
  "practice.demoContent": `Ábhar taispeána`,
  "practice.difficulty": `Deacracht`,
  "practice.easy": `Éasca`,
  "practice.explanation": `Míniú`,
  "practice.filters": `Scagairí`,
  "practice.hard": `Deacair`,
  "practice.incorrect": `Ní leor`,
  "practice.medium": `Meánach`,
  "practice.nextQuestion": `An chéad cheist eile`,
  "practice.questionCounter": `Ceist cleachtaidh {n} de {total}`,
  "practice.reportIssue": `Tuairiscigh saincheist`,
  "practice.title": `Cleachtadh`,
  "practice.topicFilter": `Topaic`,
  "practice.tryAgain": `Bain triail eile as`,
  "progress.accuracy": `Cruinneas`,
  "progress.clearProgressDesc": `Scriosann sé seo do chuid freagraí, críochnaithe, leabharmharcanna agus stair scrúduithe ón ngléas seo. Ní féidir é a chealú.`,
  "progress.clearProgressLabel": `Glan gach dul chun cinn staidéir`,
  "progress.confirmClear": `Sea, soiléir gach rud`,
  "progress.dailyGoal": `Sprioc laethúil`,
  "progress.details": `Sonraí`,
  "progress.examHistory": `Stair na scrúduithe`,
  "progress.noExams": `Níor tógadh aon scrúduithe fós.`,
  "progress.noWrongAnswers": `Níl freagraí míchearta le hathbhreithniú faoi láthair.`,
  "progress.overview": `Forbhreathnú`,
  "progress.perTopic": `De réir ábhair`,
  "progress.questionsAnswered": `Freagraíodh ceisteanna`,
  "progress.reset": `Athshocraigh`,
  "progress.retryTopic": `Bain triail eile as an ábhar seo`,
  "progress.sectionsDone": `Codanna críochnaithe`,
  "progress.suggestedNext": `Molta an chéad cheann eile: {topic}`,
  "progress.title": `Dul chun cinn`,
  "progress.topicCompletion": `Críochnú ábhar`,
  "report.detailsPlaceholder": `Inis dúinn níos mó (roghnach)`,
  "report.incorrectAnswer": `Freagra mícheart`,
  "report.outdatedInfo": `Eolas as dáta`,
  "report.submit": `Tuairisc a chur isteach`,
  "report.technicalIssue": `Saincheist theicniúil`,
  "report.thanks": `Go raibh maith agat - stóráiltear tuairiscí go háitiúil ar an ngléas seo.`,
  "report.translationProblem": `Fadhb aistriúcháin`,
  "report.unclearExplanation": `Míniú peu claire`,
  "settings.about": `Maidir leis an aip seo`,
  "settings.appInterfaceLanguage": `Teanga comhéadan app`,
  "settings.clearProgress": `Dul chun cinn soiléir`,
  "settings.clearProgressConfirm": `An bhfuil tú cinnte? Scriosfaidh sé seo do dhul chun cinn go léir.`,
  "settings.interfaceDescription": `Roghchláir, cnaipí agus nascleanúint.`,
  "settings.language": `Teanga`,
  "settings.machineNote": `Níl ábhar a aistrítear le meaisín seiceáilte ag léirmheastóir daonna. Níl aon rud anseo lipéadaithe mar athbhreithniú mura bhfuil sé athbhreithniú i ndáiríre.`,
  "settings.machineTranslatedBadge": `Meaisín-aistrithe`,
  "settings.manageProgress": `Bainistigh do shonraí dul chun cinn`,
  "settings.notAvailable": `Níl sé ar fáil fós`,
  "settings.officialGuideLink": `Treoir oifigiúil staidéir`,
  "settings.officialTestLink": `Faisnéis tástála saoránachta oifigiúil`,
  "settings.privacy": `Príobháideacht`,
  "settings.privacyText": `Stóráiltear do fhreagraí, leabharmharcanna agus socruithe ar an ngléas seo amháin. Níl aon chuntas ag teastáil. Seoltar ceisteanna a chuireann tú ar an gcúntóir staidéir chuig seirbhís AI chun freagraí a ghiniúint.`,
  "settings.reviewedBadge": `Athbhreithnithe`,
  "settings.studyContentLanguage": `Déan staidéar ar theanga an ábhair`,
  "settings.studyDescription": `Ag foghlaim téacs agus mínithe. Is féidir leat léamh i dteanga amháin agus tú ag nascleanúint i dteanga eile.`,
  "settings.textSize": `Méid an téacs`,
  "settings.title": `Socruithe`,
  "topics.askAssistant": `Cuir ceist ar an gcúntóir faoin gcuid seo`,
  "topics.bookmarkSection": `Rannóg leabharmharc`,
  "topics.bookmarkedSection": `Leabharmharcáilte`,
  "topics.completed": `Críochnaithe`,
  "topics.continueLearningCard": `Leanúint ar aghaidh ag foghlaim`,
  "topics.demoSourceNote": `Ceist shamplach bhunaidh — ní ceist scrúdaithe oifigiúil í`,
  "topics.lastVerified": `{date} fíoraithe is déanaí`,
  "topics.markComplete": `Marcáil mar iomlán`,
  "topics.markIncomplete": `Marcáil mar neamhiomlán`,
  "topics.minRead": `{n} nóim léite`,
  "topics.next": `Ar aghaidh`,
  "topics.openOfficialPage": `Oscail leathanach oifigiúil`,
  "topics.paraphrasedSourceNote": `Athinsint ó ábhar oifigiúil`,
  "topics.practiceTopic": `Cleachtaigh an topaic seo`,
  "topics.previous": `Roimhe Seo`,
  "topics.reportIssue": `Tuairiscigh saincheist`,
  "topics.reviewedOn": `athbhreithnithe {date}`,
  "topics.reviewedTranslation": `Aistriúchán athbhreithnithe`,
  "topics.section": `Alt`,
  "topics.sections": `ailt`,
  "topics.source": `Foinse`,
  "topics.sourcesDescription": `Athraítear an téacs staidéir anseo ó threoir staidéir saoránachta Rialtas Cheanada agus athbhreithnítear é ar na dátaí a thaispeántar. Déantar taighde ar cheisteanna cleachtais ón treoir oifigiúil staidéir.`,
  "topics.sourcesHeading": `Foinsí ábhair agus dátaí athbhreithnithe`,
  "topics.studyLanguageLabel": `Déan staidéar ar theanga an ábhair`,
  "topics.title": `Déan staidéar ar thopaicí`,
  "topics.vocabulary": `Stór focal`,
};
