// UI strings for 'gd' — chunk of strings.generated.ts. DO NOT EDIT BY HAND.
import type { StringKey } from "../strings.generated";

export const gd: Record<StringKey, string> = {
  "actions.askAi": `Faighnich dha AI`,
  "actions.mockExam": `Deuchainn meallta`,
  "actions.practice": `Cleachdaich`,
  "actions.quickActions": `Quick actions`,
  "actions.study": `Dèan sgrùdadh`,
  "assistant.aiEyebrow": `Neach-taic ionnsachaidh AI`,
  "assistant.answerLanguage": `Freagair cànan`,
  "assistant.charLimit": `{n} caractaran air fhàgail`,
  "assistant.checkingMaterial": `A’ sgrùdadh an stuth sgrùdaidh…`,
  "assistant.clearChat": `Còmhradh soilleir`,
  "assistant.copied": `Rinn lethbhreac`,
  "assistant.copy": `Dèan lethbhreac`,
  "assistant.description": `Tha freagairtean air an sgrìobhadh le AI a’ cleachdadh dìreach stuth sgrùdaidh an aplacaid seo, le stòran air an sealltainn. Faodaidh AI mearachdan a dhèanamh fhathast - thoir sùil air mion-fhiosrachadh cudromach air duilleagan oifigeil Riaghaltas Chanada. Chan e comhairle laghail no in-imrich.`,
  "assistant.enFrancais": `Anns an Fhraing`,
  "assistant.error": `Chaidh rudeigin ceàrr. Feuch ris a-rithist.`,
  "assistant.fromAppContent": `Bho shusbaint app ceadaichte`,
  "assistant.groundedBadge": `Bun-stèidh`,
  "assistant.helpful": `Cuideachail`,
  "assistant.inputPlaceholder": `Faighnich ceist mu shaoranachd Chanada…`,
  "assistant.myAppLanguage": `Mo chànan app`,
  "assistant.notCovered": `Gun chòmhdach - faic an duilleag oifigeil`,
  "assistant.notHelpful": `Gun chuideachadh`,
  "assistant.openAssistant": `Neach-taic sgrùdaidh fosgailte`,
  "assistant.openLink": `Neach-cuideachaidh fosgailte`,
  "assistant.practiceThis": `Cleachd seo`,
  "assistant.questionAriaLabel": `Do cheist`,
  "assistant.reportIncorrect": `Dèan aithris air freagairt ceàrr`,
  "assistant.send": `Seol`,
  "assistant.showSource": `Seall an tùs`,
  "assistant.simpleEnglish": `Beurla shìmplidh`,
  "assistant.source": `Stòr`,
  "assistant.starter1": `Dè na trì pàirtean den Phàrlamaid?`,
  "assistant.starter2": `Mìnich a’ Chùmhnant gu sìmplidh`,
  "assistant.starter3": `Cò a tha a’ riochdachadh an Rìgh ann an Canada?`,
  "assistant.starter4": `Dè tha an deuchainn eòlais a’ còmhdach?`,
  "assistant.suggestedQuestions": `Ceistean air am moladh`,
  "assistant.thinking": `A’ smaoineachadh…`,
  "assistant.title": `Neach-taic sgrùdaidh`,
  "assistant.tryAgain": `Feuch ris a-rithist`,
  "assistant.tryAsking": `Feuch ri faighneachd:`,
  "assistant.vocabularyLabel": `Briathrachas:`,
  "assistant.whyItMatters": `Carson a tha e cudromach airson na deuchainn`,
  "bookmarks.continueStudying": `Lean air adhart ag ionnsachadh`,
  "bookmarks.empty": `Chan eil comharran-leabhair ann fhathast. Tap air an rionnag air ceist sam bith gus a shàbhaladh airson ath-sgrùdadh.`,
  "bookmarks.emptyQuestions": `Chan eil dad air a shàbhaladh fhathast. Tap air ☆ air ceist cleachdaidh.`,
  "bookmarks.emptySections": `Chan eil dad air a shàbhaladh fhathast. Tap air ☆ fhad ‘s a tha thu a’ leughadh earrann.`,
  "bookmarks.remove": `Thoir air falbh`,
  "bookmarks.savedForReview": `air a shàbhaladh airson ath-sgrùdadh`,
  "bookmarks.savedQuestions": `Ceistean air an sàbhaladh ({n})`,
  "bookmarks.savedSections": `Earrannan glèidhte ({n})`,
  "bookmarks.search": `Rannsaich comharran-leabhair…`,
  "bookmarks.title": `Comharran-leabhair`,
  "cards.answered": `Fhreagair`,
  "cards.bookmarks": `air a shàbhaladh airson ath-sgrùdadh`,
  "cards.bookmarksLabel": `Comharran-leabhair`,
  "cards.continueLearning": `Lean air adhart ag ionnsachadh`,
  "cards.correct": `Ceart`,
  "cards.dailyGoal": `{done}/{total} questions today`,
  "cards.dailyGoalLabel": `Amas làitheil`,
  "cards.dailyGoalTitle": `Daily goal`,
  "cards.mockExam.subtitle": `Ùine · 20 ceist`,
  "cards.mockExam.title": `Deuchainn meallta`,
  "cards.officialInfo.button": `Fosgail canada.ca`,
  "cards.officialInfo.subtitle": `Tadhail air canada.ca airson mion-fhiosrachadh oifigeil`,
  "cards.officialInfo.title": `Fiosrachadh oifigeil`,
  "cards.progress": `Adhartas`,
  "cards.progressDetails": `Mion-fhiosrachadh`,
  "cards.recentlyStudied": `Air a sgrùdadh o chionn ghoirid`,
  "cards.sections": `Earrannan`,
  "cards.studyAssistant.subtitle": `Faighnich dad mun stuth sgrùdaidh`,
  "cards.studyAssistant.title": `Neach-taic sgrùdaidh`,
  "cards.todaysRecommendation": `Moladh an-diugh`,
  "cards.verifiedSource.subtext": `Susbaint air a sgrùdadh an aghaidh stòran oifigeil. Taic sgrùdaidh neo-eisimeileach - gun a bhith ceangailte ri no air aontachadh le Riaghaltas Chanada no IRCC.`,
  "cards.verifiedSource.title": `Stòr air a dhearbhadh`,
  "common.back": `Air ais`,
  "common.cancel": `Sguir dheth`,
  "common.close": `Dùin`,
  "common.continue": `Lean air adhart`,
  "common.done": `Dèanta`,
  "common.emptyBookmarks": `Chan eil dad air a shàbhaladh fhathast`,
  "common.emptyRecentlyStudied": `Chan eil dad air a sgrùdadh fhathast - tagh cuspair airson tòiseachadh.`,
  "common.loading": `A’ luchdachadh…`,
  "common.next": `Air adhart`,
  "common.of": `à`,
  "common.previous": `Roimhe`,
  "common.retry": `Feuch a-rithist`,
  "common.save": `Sàbhail`,
  "exam.allTopics": `A h-uile cuspair`,
  "exam.answeredCount": `Fhreagair {n}`,
  "exam.autosaveNote": `Tha na freagairtean agad air an sàbhaladh mar a thèid thu air adhart, agus mar sin cha chaill dùnadh an aplacaid an adhartas agad.`,
  "exam.cancel": `Sguir dheth`,
  "exam.confirm": `Dearbhaich`,
  "exam.confirmEnd": `Tha {n} ceistean gun fhreagairt agus thèid an comharrachadh ceàrr.`,
  "exam.confirmEndTitle": `Cuir crìoch air an deuchainn?`,
  "exam.endExamEarly": `Crìochnaich an deuchainn tràth`,
  "exam.examDisclaimer": `Chan eil an sgòr seo a’ nochdadh ach ceistean sampaill an aplacaid seo.`,
  "exam.finishExam": `Crìochnaich an deuchainn`,
  "exam.newExam": `Deuchainn ùr`,
  "exam.noMistakes": `Gun mhearachdan - sgòr foirfe!`,
  "exam.pastAttempts": `Oidhirpean san àm a dh'fhalbh`,
  "exam.questionAriaLabel": `Ceist {n}`,
  "exam.questionCount": `Àireamh de cheistean`,
  "exam.questionOf": `Ceist {n} de {total}`,
  "exam.questionPalette": `Ceistean`,
  "exam.questionsOption": `{n} ceistean`,
  "exam.resultsTitle": `An sgòr agad`,
  "exam.reviewMistakes": `Dèan lèirmheas air na mearachdan agad ({n})`,
  "exam.scoreLine": `{correct} of {total} correct`,
  "exam.seeProgress": `Faic adhartas`,
  "exam.setupDescription": `Is e seo atharrais cleachdaidh a chaidh a thogail bho cheistean sgrùdaidh an aplacaid seo. Chan e an deuchainn oifigeil a th’ ann agus chan eil e a’ ro-innse do thoradh.`,
  "exam.setupTitle": `Stèidhich an deuchainn meallta agad`,
  "exam.simulationNote": `Samhlachadh cleachdaidh · chan eil e oifigeil`,
  "exam.startExam": `Tòisich deuchainn`,
  "exam.timeLeft": `Ùine air fhàgail`,
  "exam.timedLabel": `tìmeil`,
  "exam.timedToggle": `Ùine (90 diogan gach ceist)`,
  "exam.title": `Deuchainn meallta`,
  "exam.topicFilter": `Cuspair`,
  "exam.untimedLabel": `gun ùine`,
  "footer.disclaimer": `Tha Citizen Prep na thaic sgrùdaidh neo-eisimeileach. Gun a bhith ceangailte ri no le taic bho Riaghaltas Chanada no IRCC. Chan urrainn dha gealltainn toradh seachad.`,
  "header.appName": `Citizen Prep`,
  "header.tagline": `Inneal sgrùdaidh neo-eisimeileach · Gun a bhith oifigeil`,
  "hero.sectionsProgress": `{done} of {total} sections · {percent}% complete`,
  "hero.subtitle": `Inneal sgrùdaidh neo-eisimeileach · Beurla & Fraingis · chan eil feum air cunntas`,
  "hero.title": `Dèan ullachadh airson do dheuchainn saoranachd`,
  "nav.exam": `Deuchainn`,
  "nav.home": `Dhachaigh`,
  "nav.practice": `Cleachdaich`,
  "nav.progress": `Adhartas`,
  "nav.topics": `Cuspairean`,
  "practice.allLevels": `A h-uile ìre`,
  "practice.allTopics": `A h-uile cuspair`,
  "practice.askAiAbout": `Faighnich dha AI mun cheist seo`,
  "practice.bookmarkQuestion": `Ceist comharra-leabhair`,
  "practice.bookmarked": `Leabhar-chomharraichte`,
  "practice.checkAnswer": `Thoir sùil air an fhreagairt`,
  "practice.correct": `Ceart`,
  "practice.demoContent": `Demo susbaint`,
  "practice.difficulty": `Duilgheadas`,
  "practice.easy": `Furasta`,
  "practice.explanation": `Mìneachadh`,
  "practice.filters": `Criathragan`,
  "practice.hard": `Cruaidh`,
  "practice.incorrect": `Chan eil buileach`,
  "practice.medium": `Meadhanach`,
  "practice.nextQuestion": `An ath cheist`,
  "practice.questionCounter": `Cleachd ceist {n} de {total}`,
  "practice.reportIssue": `Dèan aithris air cùis`,
  "practice.title": `Cleachdaich`,
  "practice.topicFilter": `Cuspair`,
  "practice.tryAgain": `Feuch ris a-rithist`,
  "progress.accuracy": `Cruinneas`,
  "progress.clearProgressDesc": `Sguabaidh seo às do fhreagairtean, crìochnachaidhean, comharran-leabhair agus eachdraidh dheuchainnean bhon inneal seo. Chan urrainnear a chuir dheth.`,
  "progress.clearProgressLabel": `Glan a h-uile adhartas sgrùdaidh`,
  "progress.confirmClear": `Tha, soilleir a h-uile càil`,
  "progress.dailyGoal": `Amas làitheil`,
  "progress.details": `Mion-fhiosrachadh`,
  "progress.examHistory": `Eachdraidh deuchainn`,
  "progress.noExams": `Cha deach deuchainnean sam bith a ghabhail fhathast.`,
  "progress.noWrongAnswers": `Chan eil freagairtean ceàrr ann airson ath-sgrùdadh an-dràsta.`,
  "progress.overview": `Ro-shealladh`,
  "progress.perTopic": `A rèir cuspair`,
  "progress.questionsAnswered": `Ceistean air am freagairt`,
  "progress.reset": `Ath-shuidhich`,
  "progress.retryTopic": `Feuch an cuspair seo a-rithist`,
  "progress.sectionsDone": `Earrannan crìochnaichte`,
  "progress.suggestedNext": `Suggested next: {topic}`,
  "progress.title": `Adhartas`,
  "progress.topicCompletion": `Crìochnachadh cuspair`,
  "report.detailsPlaceholder": `Inns dhuinn barrachd (roghainneil)`,
  "report.incorrectAnswer": `Freagairt ceàrr`,
  "report.outdatedInfo": `Fiosrachadh seann-fhasanta`,
  "report.submit": `Cuir a-steach aithisg`,
  "report.technicalIssue": `Cùis theicnigeach`,
  "report.thanks": `Mòran taing - tha aithisgean air an stòradh gu h-ionadail air an inneal seo.`,
  "report.translationProblem": `Trioblaid eadar-theangachaidh`,
  "report.unclearExplanation": `Mìneachadh peu claire`,
  "settings.about": `Mu dheidhinn an aplacaid seo`,
  "settings.appInterfaceLanguage": `Cànain eadar-aghaidh app`,
  "settings.clearProgress": `Adhartas soilleir`,
  "settings.clearProgressConfirm": `A bheil thu cinnteach? Sguabaidh seo às an adhartas agad gu lèir.`,
  "settings.interfaceDescription": `Clàr-taice, putanan agus seòladh.`,
  "settings.language": `Cànain`,
  "settings.machineNote": `Cha deach susbaint a chaidh eadar-theangachadh le inneal a sgrùdadh le neach-sgrùdaidh daonna. Chan eil dad an seo air a chomharrachadh mar ath-sgrùdadh mura h-eil e air ath-sgrùdadh.`,
  "settings.machineTranslatedBadge": `Inneal-eadar-theangachadh`,
  "settings.manageProgress": `Stiùirich an dàta adhartais agad`,
  "settings.notAvailable": `Chan eil e ri fhaighinn fhathast`,
  "settings.officialGuideLink": `Stiùireadh sgrùdaidh oifigeil`,
  "settings.officialTestLink": `Fiosrachadh oifigeil deuchainn saoranachd`,
  "settings.privacy": `Prìobhaideachd`,
  "settings.privacyText": `Tha na freagairtean, na comharran-lìn agus na roghainnean agad air an stòradh air an inneal seo a-mhàin. Chan eil feum air cunntas. Thèid ceistean a dh’ iarras tu air an neach-cuideachaidh sgrùdaidh a chuir gu seirbheis AI gus freagairtean a ghineadh.`,
  "settings.reviewedBadge": `Ath-sgrùdadh`,
  "settings.studyContentLanguage": `Dèan sgrùdadh air cànan susbaint`,
  "settings.studyDescription": `Ag ionnsachadh teacsa agus mìneachaidhean. Faodaidh tu leughadh ann an aon chànan fhad ‘s a tha thu a’ seòladh ann an cànan eile.`,
  "settings.textSize": `Meud teacsa`,
  "settings.title": `Suidhichidhean`,
  "topics.askAssistant": `Faighnich don neach-cuideachaidh mun roinn seo`,
  "topics.bookmarkSection": `Earrann comharra-leabhair`,
  "topics.bookmarkedSection": `Leabhar-chomharraichte`,
  "topics.completed": `Air a chrìochnachadh`,
  "topics.continueLearningCard": `Lean air adhart ag ionnsachadh`,
  "topics.demoSourceNote": `Ceist sampall tùsail - chan e ceist deuchainn oifigeil`,
  "topics.lastVerified": `{date} air a dhearbhadh mu dheireadh`,
  "topics.markComplete": `Comharraich mar iomlan`,
  "topics.markIncomplete": `Comharraich mar neo-iomlan`,
  "topics.minRead": `{n} mion leugh`,
  "topics.next": `Air adhart`,
  "topics.openOfficialPage": `Fosgail duilleag oifigeil`,
  "topics.paraphrasedSourceNote": `Eadar-theangachadh bho stuthan oifigeil`,
  "topics.practiceTopic": `Cleachd an cuspair seo`,
  "topics.previous": `Roimhe`,
  "topics.reportIssue": `Dèan aithris air cùis`,
  "topics.reviewedOn": `ath-sgrùdadh {date}`,
  "topics.reviewedTranslation": `Eadar-theangachadh ath-sgrùdadh`,
  "topics.section": `Earrann`,
  "topics.sections": `earrannan`,
  "topics.source": `Stòr`,
  "topics.sourcesDescription": `Tha teacsa sgrùdaidh an seo air ath-sgrìobhadh bho stiùireadh sgrùdadh saoranachd Riaghaltas Chanada agus air ath-sgrùdadh air na cinn-latha a tha air an sealltainn. Bithear a’ sgrùdadh cheistean cleachdaidh bhon stiùireadh sgrùdaidh oifigeil.`,
  "topics.sourcesHeading": `Stòran susbaint agus cinn-latha ath-bhreithneachaidh`,
  "topics.studyLanguageLabel": `Dèan sgrùdadh air cànan susbaint`,
  "topics.title": `Dèan sgrùdadh air cuspairean`,
  "topics.vocabulary": `Briathrachas`,
};
