// UI strings for 'gl' — chunk of strings.generated.ts. DO NOT EDIT BY HAND.
import type { StringKey } from "../strings.generated";

export const gl: Record<StringKey, string> = {
  "actions.askAi": `Pregunta a AI`,
  "actions.mockExam": `Simulacro de exame`,
  "actions.practice": `Práctica`,
  "actions.quickActions": `Quick actions`,
  "actions.study": `Estudar`,
  "assistant.aiEyebrow": `Asistente de estudo de IA`,
  "assistant.answerLanguage": `Lingua de resposta`,
  "assistant.charLimit": `Quedan {n} caracteres`,
  "assistant.checkingMaterial": `Comprobando o material de estudo...`,
  "assistant.clearChat": `Borrar o chat`,
  "assistant.copied": `Copiouse`,
  "assistant.copy": `Copiar`,
  "assistant.description": `As respostas son escritas por AI usando só o material de estudo desta aplicación, coas fontes que se mostran. A IA aínda pode cometer erros: consulta os detalles importantes nas páxinas oficiais do Goberno de Canadá. Non asesoramento legal ou de inmigración.`,
  "assistant.enFrancais": `En francés`,
  "assistant.error": `Algo saíu mal. Téntao de novo.`,
  "assistant.fromAppContent": `Do contido da aplicación aprobado`,
  "assistant.groundedBadge": `Baseado na fonte`,
  "assistant.helpful": `Útil`,
  "assistant.inputPlaceholder": `Fai unha pregunta sobre a cidadanía canadense...`,
  "assistant.myAppLanguage": `Idioma da miña aplicación`,
  "assistant.notCovered": `Non cuberto - ver páxina oficial`,
  "assistant.notHelpful": `Non é útil`,
  "assistant.openAssistant": `Asistente de estudo aberto`,
  "assistant.openLink": `Abrir asistente`,
  "assistant.practiceThis": `Practica isto`,
  "assistant.questionAriaLabel": `A túa pregunta`,
  "assistant.reportIncorrect": `Informar dunha resposta incorrecta`,
  "assistant.send": `Enviar`,
  "assistant.showSource": `Mostrar fonte`,
  "assistant.simpleEnglish": `Inglés sinxelo`,
  "assistant.source": `Fonte`,
  "assistant.starter1": `Cales son as tres partes do Parlamento?`,
  "assistant.starter2": `Explica a Carta de forma sinxela`,
  "assistant.starter3": `Quen representa ao Rei en Canadá?`,
  "assistant.starter4": `Que abrangue a proba de coñecementos?`,
  "assistant.suggestedQuestions": `Preguntas suxeridas`,
  "assistant.thinking": `Pensando…`,
  "assistant.title": `Axudante de estudos`,
  "assistant.tryAgain": `Téntao de novo`,
  "assistant.tryAsking": `Proba a preguntar:`,
  "assistant.vocabularyLabel": `Vocabulario:`,
  "assistant.whyItMatters": `Por que é importante para a proba`,
  "bookmarks.continueStudying": `Seguir estudando`,
  "bookmarks.empty": `Aínda non hai marcadores. Toca a estrela en calquera pregunta para gardala para revisala.`,
  "bookmarks.emptyQuestions": `Aínda non se gardou nada. Toca ☆ nunha pregunta de práctica.`,
  "bookmarks.emptySections": `Aínda non se gardou nada. Toca ☆ mentres le unha sección.`,
  "bookmarks.remove": `Eliminar`,
  "bookmarks.savedForReview": `gardado para revisión`,
  "bookmarks.savedQuestions": `Preguntas gardadas ({n})`,
  "bookmarks.savedSections": `Seccións gardadas ({n})`,
  "bookmarks.search": `Buscar marcadores...`,
  "bookmarks.title": `Marcadores`,
  "cards.answered": `Respondido`,
  "cards.bookmarks": `gardado para revisión`,
  "cards.bookmarksLabel": `Marcadores`,
  "cards.continueLearning": `Seguir aprendendo`,
  "cards.correct": `Correcto`,
  "cards.dailyGoal": `{done}/{total} questions today`,
  "cards.dailyGoalLabel": `Obxectivo diario`,
  "cards.dailyGoalTitle": `Daily goal`,
  "cards.mockExam.subtitle": `Cronometrado · 20 preguntas`,
  "cards.mockExam.title": `Simulacro de exame`,
  "cards.officialInfo.button": `Abre canada.ca`,
  "cards.officialInfo.subtitle": `Visita canada.ca para obter detalles oficiais`,
  "cards.officialInfo.title": `Información oficial`,
  "cards.progress": `Progreso`,
  "cards.progressDetails": `Detalles`,
  "cards.recentlyStudied": `Recentemente estudado`,
  "cards.sections": `Seccións`,
  "cards.studyAssistant.subtitle": `Preguntar calquera cousa sobre o material de estudo`,
  "cards.studyAssistant.title": `Axudante de estudos`,
  "cards.todaysRecommendation": `A recomendación de hoxe`,
  "cards.verifiedSource.subtext": `Contido comprobado con fontes oficiais. Axuda de estudo independente: non afiliada nin avalada polo Goberno do Canadá nin polo IRCC.`,
  "cards.verifiedSource.title": `Fonte verificada`,
  "common.back": `De volta`,
  "common.cancel": `Cancelar`,
  "common.close": `Pechar`,
  "common.continue": `Continuar`,
  "common.done": `Feito`,
  "common.emptyBookmarks": `Aínda non se gardou nada`,
  "common.emptyRecentlyStudied": `Aínda non se estudou nada: escolle un tema para comezar.`,
  "common.loading": `Cargando…`,
  "common.next": `A continuación`,
  "common.of": `de`,
  "common.previous": `Anterior`,
  "common.retry": `Volve tentar`,
  "common.save": `Gardar`,
  "exam.allTopics": `Todos os temas`,
  "exam.answeredCount": `{n} respondeu`,
  "exam.autosaveNote": `As túas respostas gárdanse a medida que vaias, polo que se pechas a aplicación non perderás o teu progreso.`,
  "exam.cancel": `Cancelar`,
  "exam.confirm": `Confirmar`,
  "exam.confirmEnd": `{n} preguntas quedan sen resposta e marcaranse como incorrectas.`,
  "exam.confirmEndTitle": `Finalizar o exame?`,
  "exam.endExamEarly": `Remata o exame cedo`,
  "exam.examDisclaimer": `Esta puntuación reflicte só as preguntas de mostra desta aplicación.`,
  "exam.finishExam": `Finalizar exame`,
  "exam.newExam": `Novo exame`,
  "exam.noMistakes": `Sen erros: puntuación perfecta!`,
  "exam.pastAttempts": `Intentos anteriores`,
  "exam.questionAriaLabel": `Pregunta {n}`,
  "exam.questionCount": `Número de preguntas`,
  "exam.questionOf": `Pregunta {n} de {total}`,
  "exam.questionPalette": `Preguntas`,
  "exam.questionsOption": `{n} preguntas`,
  "exam.resultsTitle": `A túa puntuación`,
  "exam.reviewMistakes": `Revisa os teus erros ({n})`,
  "exam.scoreLine": `{correct} of {total} correct`,
  "exam.seeProgress": `Ver progreso`,
  "exam.setupDescription": `Esta é unha simulación práctica construída a partir das preguntas de estudo desta aplicación. Non é a proba oficial e non prevé o teu resultado.`,
  "exam.setupTitle": `Configura o teu exame simulado`,
  "exam.simulationNote": `Práctica de simulación · non oficial`,
  "exam.startExam": `Comeza o exame`,
  "exam.timeLeft": `Queda tempo`,
  "exam.timedLabel": `cronometrado`,
  "exam.timedToggle": `Cronometrado (90 segundos por pregunta)`,
  "exam.title": `Simulacro de exame`,
  "exam.topicFilter": `Tema`,
  "exam.untimedLabel": `sen tempo`,
  "footer.disclaimer": `Citizen Prep é unha axuda de estudo independente. Non está afiliado nin avalado polo Goberno do Canadá nin polo IRCC. Non pode garantir un resultado aprobatorio.`,
  "header.appName": `Preparación Cidadá`,
  "header.tagline": `Ferramenta de estudo independente · Non oficial`,
  "hero.sectionsProgress": `{done} of {total} sections · {percent}% complete`,
  "hero.subtitle": `Ferramenta de estudo independente · Inglés e francés · non se precisa conta`,
  "hero.title": `Prepárate para a túa proba de cidadanía`,
  "nav.exam": `Exame`,
  "nav.home": `Casa`,
  "nav.practice": `Práctica`,
  "nav.progress": `Progreso`,
  "nav.topics": `Temas`,
  "practice.allLevels": `Todos os niveis`,
  "practice.allTopics": `Todos os temas`,
  "practice.askAiAbout": `Pregúntalle a AI sobre esta pregunta`,
  "practice.bookmarkQuestion": `Pregunta de marcador`,
  "practice.bookmarked": `Marcado como favorito`,
  "practice.checkAnswer": `Comproba a resposta`,
  "practice.correct": `Correcto`,
  "practice.demoContent": `Contido de demostración`,
  "practice.difficulty": `Dificultade`,
  "practice.easy": `Doado`,
  "practice.explanation": `Explicación`,
  "practice.filters": `Filtros`,
  "practice.hard": `Difícil`,
  "practice.incorrect": `Non do todo`,
  "practice.medium": `Medio`,
  "practice.nextQuestion": `Próxima pregunta`,
  "practice.questionCounter": `Pregunta práctica {n} de {total}`,
  "practice.reportIssue": `Informar dun problema`,
  "practice.title": `Práctica`,
  "practice.topicFilter": `Tema`,
  "practice.tryAgain": `Téntao de novo`,
  "progress.accuracy": `Precisión`,
  "progress.clearProgressDesc": `Isto elimina as túas respostas, conclusións, marcadores e historial de exames deste dispositivo. Non se pode desfacer.`,
  "progress.clearProgressLabel": `Borrar todo o progreso do estudo`,
  "progress.confirmClear": `Si, claro todo`,
  "progress.dailyGoal": `Obxectivo diario`,
  "progress.details": `Detalles`,
  "progress.examHistory": `Historial de exames`,
  "progress.noExams": `Aínda non se fixo ningún exame.`,
  "progress.noWrongAnswers": `Non hai respostas incorrectas para revisar neste momento.`,
  "progress.overview": `Visión xeral`,
  "progress.perTopic": `Por tema`,
  "progress.questionsAnswered": `Preguntas contestadas`,
  "progress.reset": `Restablecer`,
  "progress.retryTopic": `Volve tentar este tema`,
  "progress.sectionsDone": `Seccións completadas`,
  "progress.suggestedNext": `Suggested next: {topic}`,
  "progress.title": `Progreso`,
  "progress.topicCompletion": `Finalización do tema`,
  "report.detailsPlaceholder": `Cóntanos máis (opcional)`,
  "report.incorrectAnswer": `Resposta incorrecta`,
  "report.outdatedInfo": `Información desactualizada`,
  "report.submit": `Presentar informe`,
  "report.technicalIssue": `Problema técnico`,
  "report.thanks": `Grazas: os informes almacénanse localmente neste dispositivo.`,
  "report.translationProblem": `Problema de tradución`,
  "report.unclearExplanation": `Explicación peu claire`,
  "settings.about": `Sobre esta aplicación`,
  "settings.appInterfaceLanguage": `Idioma da interface da aplicación`,
  "settings.clearProgress": `Progreso claro`,
  "settings.clearProgressConfirm": `Estás seguro? Isto eliminará todo o teu progreso.`,
  "settings.interfaceDescription": `Menús, botóns e navegación.`,
  "settings.language": `Linguaxe`,
  "settings.machineNote": `Un revisor humano non comprobou o contido traducido automático. Nada aquí está etiquetado como revisado a menos que se revisase realmente.`,
  "settings.machineTranslatedBadge": `Traducido á máquina`,
  "settings.manageProgress": `Xestiona os teus datos de progreso`,
  "settings.notAvailable": `Aínda non dispoñible`,
  "settings.officialGuideLink": `Guía oficial de estudo`,
  "settings.officialTestLink": `Información oficial da proba de cidadanía`,
  "settings.privacy": `Privacidade`,
  "settings.privacyText": `As túas respostas, marcadores e configuracións almacénanse só neste dispositivo. Non se precisa ningunha conta. As preguntas que lle fas ao asistente de estudo envíanse a un servizo de IA para xerar respostas.`,
  "settings.reviewedBadge": `Revisado`,
  "settings.studyContentLanguage": `Estudar a linguaxe dos contidos`,
  "settings.studyDescription": `Aprendizaxe de textos e explicacións. Podes ler nun idioma mentres navegas noutro.`,
  "settings.textSize": `Tamaño do texto`,
  "settings.title": `Configuración`,
  "topics.askAssistant": `Pregunta ao asistente sobre esta sección`,
  "topics.bookmarkSection": `Sección de marcadores`,
  "topics.bookmarkedSection": `Marcado como favorito`,
  "topics.completed": `Completado`,
  "topics.continueLearningCard": `Seguir aprendendo`,
  "topics.demoSourceNote": `Pregunta de mostra orixinal: non é unha pregunta de exame oficial`,
  "topics.lastVerified": `Última verificación: {date}`,
  "topics.markComplete": `Marcar como completo`,
  "topics.markIncomplete": `Marcar como incompleto`,
  "topics.minRead": `{n} minutos de lectura`,
  "topics.next": `A continuación`,
  "topics.openOfficialPage": `Abre páxina oficial`,
  "topics.paraphrasedSourceNote": `Parafraseado de material oficial`,
  "topics.practiceTopic": `Practica este tema`,
  "topics.previous": `Anterior`,
  "topics.reportIssue": `Informar dun problema`,
  "topics.reviewedOn": `reviewed {date}`,
  "topics.reviewedTranslation": `Tradución revisada`,
  "topics.section": `Sección`,
  "topics.sections": `seccións`,
  "topics.source": `Fonte`,
  "topics.sourcesDescription": `O texto do estudo aquí está parafraseado da guía de estudo da cidadanía do Goberno de Canadá e revisado nas datas indicadas. As preguntas prácticas son investigadas a partir da guía de estudo oficial.`,
  "topics.sourcesHeading": `Fontes de contido e datas de revisión`,
  "topics.studyLanguageLabel": `Estudar a linguaxe dos contidos`,
  "topics.title": `Temas de estudo`,
  "topics.vocabulary": `Vocabulario`,
};
