// UI strings for 'hr' — chunk of strings.generated.ts. DO NOT EDIT BY HAND.
import type { StringKey } from "../strings.generated";

export const hr: Record<StringKey, string> = {
  "actions.askAi": `Pitajte AI`,
  "actions.mockExam": `Probni ispit`,
  "actions.practice": `Vježbajte`,
  "actions.quickActions": `Quick actions`,
  "actions.study": `studija`,
  "assistant.aiEyebrow": `Asistent na studiju umjetne inteligencije`,
  "assistant.answerLanguage": `Jezik odgovora`,
  "assistant.charLimit": `Preostalo znakova: {n}`,
  "assistant.checkingMaterial": `Provjera gradiva…`,
  "assistant.clearChat": `Obriši chat`,
  "assistant.copied": `Kopirano`,
  "assistant.copy": `Kopiraj`,
  "assistant.description": `Odgovore piše AI koristeći samo materijal za proučavanje ove aplikacije, s prikazanim izvorima. AI još uvijek može pogriješiti — provjerite važne detalje na službenim stranicama Vlade Kanade. Ne pravni ili imigracijski savjet.`,
  "assistant.enFrancais": `En français`,
  "assistant.error": `Nešto nije u redu. Molimo pokušajte ponovo.`,
  "assistant.fromAppContent": `Iz odobrenog sadržaja aplikacije`,
  "assistant.groundedBadge": `Utemeljen na izvoru`,
  "assistant.helpful": `od pomoći`,
  "assistant.inputPlaceholder": `Postavite pitanje o kanadskom državljanstvu...`,
  "assistant.myAppLanguage": `Jezik moje aplikacije`,
  "assistant.notCovered": `Not covered — see official page`,
  "assistant.notHelpful": `Nije od pomoći`,
  "assistant.openAssistant": `Asistent otvorenog studija`,
  "assistant.openLink": `Otvori pomoćnika`,
  "assistant.practiceThis": `Vježbajte ovo`,
  "assistant.questionAriaLabel": `Vaše pitanje`,
  "assistant.reportIncorrect": `Prijavite netočan odgovor`,
  "assistant.send": `poslati`,
  "assistant.showSource": `Prikaži izvor`,
  "assistant.simpleEnglish": `Jednostavan engleski`,
  "assistant.source": `Izvor`,
  "assistant.starter1": `Koja su tri dijela parlamenta?`,
  "assistant.starter2": `Jednostavno objasnite Povelju`,
  "assistant.starter3": `Tko predstavlja kralja u Kanadi?`,
  "assistant.starter4": `Što obuhvaća provjera znanja?`,
  "assistant.suggestedQuestions": `Predložena pitanja`,
  "assistant.thinking": `razmišljanje...`,
  "assistant.title": `Asistent na studiju`,
  "assistant.tryAgain": `Pokušajte ponovno`,
  "assistant.tryAsking": `Pokušajte pitati:`,
  "assistant.vocabularyLabel": `Rječnik:`,
  "assistant.whyItMatters": `Zašto je to važno za test`,
  "auth.account": `Account`,
  "auth.checkEmail": `Check your email to confirm your account, then sign in.`,
  "auth.close": `Close`,
  "auth.codeLabel": `Verification code`,
  "auth.codeResent": `New code sent. Check your email.`,
  "auth.codeSent": `Code sent! Check your email and enter the 6-digit code.`,
  "auth.createAccount": `Create account`,
  "auth.dataDeletedMsg": `Your progress and profile data were deleted.`,
  "auth.deleteConfirm": `Tap again to permanently delete`,
  "auth.deleteData": `Delete my data`,
  "auth.email": `Email`,
  "auth.haveAccount": `Already have an account?`,
  "auth.mfaCodeLabel": `Authenticator code`,
  "auth.mfaDisable": `Disable 2FA`,
  "auth.mfaDisabledMsg": `Two-factor authentication is now OFF.`,
  "auth.mfaEnable": `Enable 2FA`,
  "auth.mfaEnabledMsg": `Two-factor authentication is now ON for your account.`,
  "auth.mfaPendingWarn": `2FA code still needed to finish signing in.`,
  "auth.mfaPrompt": `This account uses 2FA — enter the code from your authenticator app.`,
  "auth.mfaScanHint": `Scan this QR code with your authenticator app (Google Authenticator, Authy, 1Password…), then enter the 6-digit code it shows.`,
  "auth.mfaSetupTitle": `Set up two-factor authentication`,
  "auth.mfaSubtitle": `Enter the 6-digit code from your authenticator app.`,
  "auth.mfaTitle": `Two-factor authentication`,
  "auth.noAccount": `Don't have an account?`,
  "auth.password": `Password`,
  "auth.passwordHint": `At least 6 characters`,
  "auth.privacy": `Privacy`,
  "auth.privacyNote": `Your email and progress are private — only you can see them.`,
  "auth.resendCode": `Resend code`,
  "auth.security": `Security`,
  "auth.signIn": `Sign in`,
  "auth.signOut": `Sign out`,
  "auth.signUp": `Sign up`,
  "auth.subtitle": `Save your progress across devices. Your data stays private.`,
  "auth.title": `Account`,
  "auth.verify": `Verify`,
  "auth.verifyCodeSubtitle": `We sent a 6-digit code to your email. Enter it below to finish signing up.`,
  "auth.verifyCodeTitle": `Enter your code`,
  "auth.working": `Please wait…`,
  "bookmarks.continueStudying": `Nastavite učiti`,
  "bookmarks.empty": `Još nema oznaka. Dodirnite zvjezdicu na bilo kojem pitanju da biste ga spremili za pregled.`,
  "bookmarks.emptyQuestions": `Još ništa nije spremljeno. Tap ☆ on a practice question.`,
  "bookmarks.emptySections": `Još ništa nije spremljeno. Tap ☆ while reading a section.`,
  "bookmarks.remove": `Ukloniti`,
  "bookmarks.savedForReview": `spremljeno za pregled`,
  "bookmarks.savedQuestions": `Spremljena pitanja ({n})`,
  "bookmarks.savedSections": `Spremljeni odjeljci ({n})`,
  "bookmarks.search": `Pretraži oznake...`,
  "bookmarks.title": `Knjižne oznake`,
  "cards.answered": `Odgovoreno`,
  "cards.bookmarks": `spremljeno za pregled`,
  "cards.bookmarksLabel": `Knjižne oznake`,
  "cards.continueLearning": `Nastavite učiti`,
  "cards.correct": `Točno`,
  "cards.dailyGoal": `{done}/{total} pitanja danas`,
  "cards.dailyGoalLabel": `Dnevni cilj`,
  "cards.dailyGoalTitle": `Daily goal`,
  "cards.mockExam.subtitle": `Vremenski · 20 pitanja`,
  "cards.mockExam.title": `Probni ispit`,
  "cards.officialInfo.button": `Otvori canada.ca`,
  "cards.officialInfo.subtitle": `Posjetite canada.ca za službene detalje`,
  "cards.officialInfo.title": `Službena informacija`,
  "cards.progress": `napredak`,
  "cards.progressDetails": `pojedinosti`,
  "cards.recentlyStudied": `Nedavno proučavan`,
  "cards.sections": `Sekcije`,
  "cards.studyAssistant.subtitle": `Pitajte bilo što o materijalu za učenje`,
  "cards.studyAssistant.title": `Asistent na studiju`,
  "cards.todaysRecommendation": `Današnja preporuka`,
  "cards.verifiedSource.subtext": `Sadržaj je provjeren prema službenim izvorima. Neovisna pomoć pri proučavanju — nije povezana s Vladom Kanade ili IRCC-om niti ih podržava.`,
  "cards.verifiedSource.title": `Provjereni izvor`,
  "common.back": `natrag`,
  "common.cancel": `Odustani`,
  "common.close": `Zatvori`,
  "common.continue": `nastavi`,
  "common.done": `Gotovo`,
  "common.emptyBookmarks": `Još ništa nije spremljeno`,
  "common.emptyRecentlyStudied": `Još ništa nije proučavano — odaberite temu za početak.`,
  "common.loading": `učitavanje...`,
  "common.next": `Dalje`,
  "common.of": `od`,
  "common.previous": `Prethodno`,
  "common.retry": `Pokušaj ponovo`,
  "common.save": `spremiti`,
  "exam.allTopics": `Sve teme`,
  "exam.answeredCount": `{n} je odgovorio`,
  "exam.autosaveNote": `Vaši se odgovori spremaju dok idete, tako da zatvaranje aplikacije neće izgubiti vaš napredak.`,
  "exam.cancel": `Odustani`,
  "exam.confirm": `Potvrdi`,
  "exam.confirmEnd": `{n} pitanja su bez odgovora i bit će označena kao netočna.`,
  "exam.confirmEndTitle": `Završiti ispit?`,
  "exam.endExamEarly": `Ranije završite ispit`,
  "exam.examDisclaimer": `Ovaj rezultat odražava samo uzorke pitanja ove aplikacije.`,
  "exam.finishExam": `Završi ispit`,
  "exam.newExam": `Novi ispit`,
  "exam.noMistakes": `Bez pogrešaka — savršen rezultat!`,
  "exam.pastAttempts": `Prošli pokušaji`,
  "exam.questionAriaLabel": `Pitanje {n}`,
  "exam.questionCount": `Broj pitanja`,
  "exam.questionOf": `Pitanje {n} od {total}`,
  "exam.questionPalette": `Pitanja`,
  "exam.questionsOption": `{n} pitanja`,
  "exam.resultsTitle": `Vaš rezultat`,
  "exam.reviewMistakes": `Pregledajte svoje pogreške ({n})`,
  "exam.scoreLine": `{correct} od {total} točnih`,
  "exam.seeProgress": `Vidi napredak`,
  "exam.setupDescription": `Ovo je simulacija prakse izgrađena od pitanja za učenje ove aplikacije. To nije službeni test i ne predviđa vaš rezultat.`,
  "exam.setupTitle": `Pripremite svoj probni ispit`,
  "exam.simulationNote": `Simulacija vježbanja · nije službeno`,
  "exam.startExam": `Započnite ispit`,
  "exam.timeLeft": `Preostalo vrijeme`,
  "exam.timedLabel": `tempirano`,
  "exam.timedToggle": `Vremenski ograničeno (90 sekundi po pitanju)`,
  "exam.title": `Probni ispit`,
  "exam.topicFilter": `Tema`,
  "exam.untimedLabel": `nevremenski`,
  "footer.disclaimer": `Citizen Prep neovisna je pomoć za učenje. Nije povezan s Vladom Kanade ili IRCC-om niti ih podržava. Ne može jamčiti prolazan rezultat.`,
  "header.appName": `Građanin Prep`,
  "header.tagline": `Alat za neovisno proučavanje · Nije službeno`,
  "hero.sectionsProgress": `{done} of {total} sections · {percent}% complete`,
  "hero.subtitle": `Alat za neovisno učenje · engleski i francuski · račun nije potreban`,
  "hero.title": `Pripremite se za ispit za državljanstvo`,
  "nav.exam": `Ispit`,
  "nav.home": `Dom`,
  "nav.practice": `Vježbajte`,
  "nav.progress": `napredak`,
  "nav.topics": `teme`,
  "practice.allLevels": `Sve razine`,
  "practice.allTopics": `Sve teme`,
  "practice.askAiAbout": `Pitajte AI o ovom pitanju`,
  "practice.bookmarkQuestion": `Označite pitanje`,
  "practice.bookmarked": `Označeno`,
  "practice.checkAnswer": `Provjerite odgovor`,
  "practice.correct": `Točno`,
  "practice.demoContent": `Demo sadržaj`,
  "practice.difficulty": `Poteškoće`,
  "practice.easy": `lako`,
  "practice.explanation": `Objašnjenje`,
  "practice.filters": `Filteri`,
  "practice.hard": `teško`,
  "practice.incorrect": `Ne sasvim`,
  "practice.medium": `srednje`,
  "practice.nextQuestion": `Sljedeće pitanje`,
  "practice.questionCounter": `Pitanje za vježbanje {n} od {total}`,
  "practice.reportIssue": `Prijavite problem`,
  "practice.title": `Vježbajte`,
  "practice.topicFilter": `Tema`,
  "practice.tryAgain": `Pokušajte ponovno`,
  "progress.accuracy": `Točnost`,
  "progress.clearProgressDesc": `Ovo briše vaše odgovore, dovršetke, oznake i povijest ispita s ovog uređaja. Ne može se poništiti.`,
  "progress.clearProgressLabel": `Izbriši sav napredak učenja`,
  "progress.confirmClear": `Da, očisti sve`,
  "progress.dailyGoal": `Dnevni cilj`,
  "progress.details": `pojedinosti`,
  "progress.examHistory": `Povijest ispita`,
  "progress.noExams": `Još nema položenih ispita.`,
  "progress.noWrongAnswers": `No incorrect answers to review right now.`,
  "progress.overview": `Pregled`,
  "progress.perTopic": `Po temi`,
  "progress.questionsAnswered": `Odgovoreno na pitanja`,
  "progress.reset": `Resetiraj`,
  "progress.retryTopic": `Pokušajte ponovo ovu temu`,
  "progress.sectionsDone": `Odjeljci dovršeni`,
  "progress.suggestedNext": `Predloženo sljedeće: {topic}`,
  "progress.title": `napredak`,
  "progress.topicCompletion": `Završetak teme`,
  "report.detailsPlaceholder": `Recite nam više (nije obavezno)`,
  "report.incorrectAnswer": `Netočan odgovor`,
  "report.outdatedInfo": `Zastarjele informacije`,
  "report.submit": `Pošalji izvješće`,
  "report.technicalIssue": `Tehnički problem`,
  "report.thanks": `Hvala — izvješća se pohranjuju lokalno na ovom uređaju.`,
  "report.translationProblem": `Problem s prijevodom`,
  "report.unclearExplanation": `Objašnjenje peu claire`,
  "settings.about": `O ovoj aplikaciji`,
  "settings.appInterfaceLanguage": `Jezik sučelja aplikacije`,
  "settings.clearProgress": `Jasan napredak`,
  "settings.clearProgressConfirm": `Jeste li sigurni? Ovo će izbrisati sav vaš napredak.`,
  "settings.interfaceDescription": `Menus, buttons and navigation.`,
  "settings.language": `Jezik`,
  "settings.machineNote": `Strojno preveden sadržaj nije provjerio ljudski recenzent. Ovdje ništa nije označeno kao pregledano osim ako nije stvarno pregledano.`,
  "settings.machineTranslatedBadge": `Strojno prevedeno`,
  "settings.manageProgress": `Manage your progress data`,
  "settings.notAvailable": `Još nije dostupno`,
  "settings.officialGuideLink": `Službeni vodič za učenje`,
  "settings.officialTestLink": `Službeni podaci o testu za državljanstvo`,
  "settings.privacy": `Privatnost`,
  "settings.privacyText": `Vaši odgovori, oznake i postavke pohranjuju se samo na ovom uređaju. Račun nije potreban. Pitanja koja postavljate pomoćniku u učenju šalju se AI službi za generiranje odgovora.`,
  "settings.reviewedBadge": `Pregledano`,
  "settings.studyContentLanguage": `Jezik studija sadržaja`,
  "settings.studyDescription": `Learning text and explanations. Možete čitati na jednom jeziku dok navigirate na drugom.`,
  "settings.textSize": `Veličina teksta`,
  "settings.title": `postavke`,
  "topics.askAssistant": `Pitajte pomoćnika o ovom odjeljku`,
  "topics.bookmarkSection": `Označite odjeljak`,
  "topics.bookmarkedSection": `Označeno`,
  "topics.completed": `Završeno`,
  "topics.continueLearningCard": `Nastavite učiti`,
  "topics.demoSourceNote": `Izvorno ogledno pitanje — nije službeno ispitno pitanje`,
  "topics.lastVerified": `Zadnji put potvrđeno {date}`,
  "topics.markComplete": `Označi kao dovršeno`,
  "topics.markIncomplete": `Označi kao nedovršeno`,
  "topics.minRead": `{n} min čitanja`,
  "topics.next": `Dalje`,
  "topics.openOfficialPage": `Otvori službenu stranicu`,
  "topics.paraphrasedSourceNote": `Parafrazirano iz službenog materijala`,
  "topics.practiceTopic": `Vježbajte ovu temu`,
  "topics.previous": `Prethodno`,
  "topics.reportIssue": `Prijavite problem`,
  "topics.reviewedOn": `pregledano {date}`,
  "topics.reviewedTranslation": `Pregledani prijevod`,
  "topics.section": `odjeljak`,
  "topics.sections": `odjeljci`,
  "topics.source": `Izvor`,
  "topics.sourcesDescription": `Tekst studije ovdje je parafraziran iz Vodiča za studije državljanstva Vlade Kanade i pregledan na prikazane datume. Pitanja za vježbu istražuju se u službenom vodiču za učenje.`,
  "topics.sourcesHeading": `Izvori sadržaja i datumi pregleda`,
  "topics.studyLanguageLabel": `Jezik studija sadržaja`,
  "topics.title": `Studijske teme`,
  "topics.vocabulary": `Rječnik`,
};
