// UI strings for 'hu' — chunk of strings.generated.ts. DO NOT EDIT BY HAND.
import type { StringKey } from "../strings.generated";

export const hu: Record<StringKey, string> = {
  "actions.askAi": `Kérdezd meg az AI-t`,
  "actions.mockExam": `Próbavizsga`,
  "actions.practice": `Gyakorlat`,
  "actions.quickActions": `Quick actions`,
  "actions.study": `Tanulmány`,
  "assistant.aiEyebrow": `AI tanulmányi asszisztens`,
  "assistant.answerLanguage": `Válasz nyelve`,
  "assistant.charLimit": `{n} karakter maradt`,
  "assistant.checkingMaterial": `A tananyag ellenőrzése…`,
  "assistant.clearChat": `Csevegés törlése`,
  "assistant.copied": `Másolva`,
  "assistant.copy": `Másolás`,
  "assistant.description": `A válaszokat a mesterséges intelligencia írja, csak ennek az alkalmazásnak a tananyagát használva, a források feltüntetésével. A mesterséges intelligencia továbbra is hibázhat – tekintse meg a fontos részleteket Kanada kormányának hivatalos oldalain. Nem jogi vagy bevándorlási tanácsadás.`,
  "assistant.enFrancais": `En français`,
  "assistant.error": `Valami elromlott. Kérjük, próbálja újra.`,
  "assistant.fromAppContent": `Jóváhagyott alkalmazástartalomból`,
  "assistant.groundedBadge": `Forrás-földelt`,
  "assistant.helpful": `Hasznos`,
  "assistant.inputPlaceholder": `Tegyen fel kérdést a kanadai állampolgársággal kapcsolatban…`,
  "assistant.myAppLanguage": `Az alkalmazás nyelve`,
  "assistant.notCovered": `Nem terjed ki – lásd a hivatalos oldalt`,
  "assistant.notHelpful": `Nem hasznos`,
  "assistant.openAssistant": `Nyílt tanulmányi asszisztens`,
  "assistant.openLink": `Nyissa meg az asszisztenst`,
  "assistant.practiceThis": `Gyakorold ezt`,
  "assistant.questionAriaLabel": `A kérdésed`,
  "assistant.reportIncorrect": `Helytelen válasz bejelentése`,
  "assistant.send": `Küldés`,
  "assistant.showSource": `Forrás megjelenítése`,
  "assistant.simpleEnglish": `Egyszerű angol`,
  "assistant.source": `Forrás`,
  "assistant.starter1": `Mi a parlament három része?`,
  "assistant.starter2": `Magyarázza el egyszerűen a Chartát`,
  "assistant.starter3": `Ki képviseli a királyt Kanadában?`,
  "assistant.starter4": `Mit takar a tudásvizsga?`,
  "assistant.suggestedQuestions": `Javasolt kérdések`,
  "assistant.thinking": `Gondolkodni…`,
  "assistant.title": `Tanulmányi asszisztens`,
  "assistant.tryAgain": `Próbáld újra`,
  "assistant.tryAsking": `Próbáld meg kérdezni:`,
  "assistant.vocabularyLabel": `Szókincs:`,
  "assistant.whyItMatters": `Miért fontos ez a teszt szempontjából`,
  "auth.account": `Account`,
  "auth.checkEmail": `Check your email to confirm your account, then sign in.`,
  "auth.close": `Close`,
  "auth.codeLabel": `Verification code`,
  "auth.codeResent": `New code sent. Check your email.`,
  "auth.codeSent": `Code sent! Check your email and enter the 6-digit code.`,
  "auth.createAccount": `Create account`,
  "auth.dataDeletedMsg": `Your progress and profile data were deleted.`,
  "auth.deleteConfirm": `Tap again to permanently delete`,
  "auth.deleteData": `Delete my data`,
  "auth.email": `Email`,
  "auth.haveAccount": `Already have an account?`,
  "auth.mfaCodeLabel": `Authenticator code`,
  "auth.mfaDisable": `Disable 2FA`,
  "auth.mfaDisabledMsg": `Two-factor authentication is now OFF.`,
  "auth.mfaEnable": `Enable 2FA`,
  "auth.mfaEnabledMsg": `Two-factor authentication is now ON for your account.`,
  "auth.mfaPendingWarn": `2FA code still needed to finish signing in.`,
  "auth.mfaPrompt": `This account uses 2FA — enter the code from your authenticator app.`,
  "auth.mfaScanHint": `Scan this QR code with your authenticator app (Google Authenticator, Authy, 1Password…), then enter the 6-digit code it shows.`,
  "auth.mfaSetupTitle": `Set up two-factor authentication`,
  "auth.mfaSubtitle": `Enter the 6-digit code from your authenticator app.`,
  "auth.mfaTitle": `Two-factor authentication`,
  "auth.noAccount": `Don't have an account?`,
  "auth.password": `Password`,
  "auth.passwordHint": `At least 6 characters`,
  "auth.privacy": `Privacy`,
  "auth.privacyNote": `Your email and progress are private — only you can see them.`,
  "auth.resendCode": `Resend code`,
  "auth.security": `Security`,
  "auth.signIn": `Sign in`,
  "auth.signOut": `Sign out`,
  "auth.signUp": `Sign up`,
  "auth.subtitle": `Save your progress across devices. Your data stays private.`,
  "auth.title": `Account`,
  "auth.verify": `Verify`,
  "auth.verifyCodeSubtitle": `We sent a 6-digit code to your email. Enter it below to finish signing up.`,
  "auth.verifyCodeTitle": `Enter your code`,
  "auth.working": `Please wait…`,
  "bookmarks.continueStudying": `Folytasd a tanulást`,
  "bookmarks.empty": `Még nincsenek könyvjelzők. Koppintson a csillagra bármely kérdésnél, hogy elmentse azt felülvizsgálatra.`,
  "bookmarks.emptyQuestions": `Még nincs mentve semmi. Koppintson a ☆ elemre egy gyakorló kérdésre.`,
  "bookmarks.emptySections": `Még nincs mentve semmi. Érintse meg a ☆ elemet egy szakasz olvasása közben.`,
  "bookmarks.remove": `Távolítsa el`,
  "bookmarks.savedForReview": `áttekintésre mentve`,
  "bookmarks.savedQuestions": `Mentett kérdések ({n})`,
  "bookmarks.savedSections": `Mentett szakaszok ({n})`,
  "bookmarks.search": `Könyvjelzők keresése…`,
  "bookmarks.title": `Könyvjelzők`,
  "cards.answered": `Válaszolt`,
  "cards.bookmarks": `áttekintésre mentve`,
  "cards.bookmarksLabel": `Könyvjelzők`,
  "cards.continueLearning": `Folytassa a tanulást`,
  "cards.correct": `Helyes`,
  "cards.dailyGoal": `{done}/{total} kérdés ma`,
  "cards.dailyGoalLabel": `Napi cél`,
  "cards.dailyGoalTitle": `Daily goal`,
  "cards.mockExam.subtitle": `Időzített · 20 kérdés`,
  "cards.mockExam.title": `Próbavizsga`,
  "cards.officialInfo.button": `Nyissa meg a canada.ca-t`,
  "cards.officialInfo.subtitle": `A hivatalos részletekért látogasson el a canada.ca oldalra`,
  "cards.officialInfo.title": `Hivatalos információ`,
  "cards.progress": `Haladás`,
  "cards.progressDetails": `Részletek`,
  "cards.recentlyStudied": `Nemrég tanult`,
  "cards.sections": `szakaszok`,
  "cards.studyAssistant.subtitle": `Kérdezz bármit a tananyaggal kapcsolatban`,
  "cards.studyAssistant.title": `Tanulmányi asszisztens`,
  "cards.todaysRecommendation": `Mai ajánlás`,
  "cards.verifiedSource.subtext": `A tartalmat hivatalos forrásokhoz hasonlítottuk. Független tanulmányi segédlet – nem áll kapcsolatban Kanada kormányával vagy az IRCC-vel, illetve nem hagyja jóvá.`,
  "cards.verifiedSource.title": `Ellenőrzött forrás`,
  "common.back": `Vissza`,
  "common.cancel": `Mégsem`,
  "common.close": `Bezárás`,
  "common.continue": `Folytatás`,
  "common.done": `Kész`,
  "common.emptyBookmarks": `Még nincs mentve semmi`,
  "common.emptyRecentlyStudied": `Még nem tanulmányozott semmit – kezdésként válasszon egy témát.`,
  "common.loading": `Betöltés…`,
  "common.next": `Következő`,
  "common.of": `-ból`,
  "common.previous": `Előző`,
  "common.retry": `Próbálja újra`,
  "common.save": `Mentés`,
  "exam.allTopics": `Minden téma`,
  "exam.answeredCount": `{n} válaszolt`,
  "exam.autosaveNote": `Válaszait menet közben menti a rendszer, így az alkalmazás bezárása nem veszíti el az előrehaladást.`,
  "exam.cancel": `Mégsem`,
  "exam.confirm": `Erősítse meg`,
  "exam.confirmEnd": `{n} kérdés megválaszolatlan, és helytelenként lesz megjelölve.`,
  "exam.confirmEndTitle": `Vége a vizsgának?`,
  "exam.endExamEarly": `Végezze el a vizsgát korán`,
  "exam.examDisclaimer": `Ez a pontszám csak az alkalmazás mintakérdéseit tükrözi.`,
  "exam.finishExam": `Vizsga befejezése`,
  "exam.newExam": `Új vizsga`,
  "exam.noMistakes": `Nincs hiba - tökéletes pontszám!`,
  "exam.pastAttempts": `Múltbeli próbálkozások`,
  "exam.questionAriaLabel": `{n}. kérdés`,
  "exam.questionCount": `Kérdések száma`,
  "exam.questionOf": `{n}. kérdés/{total}`,
  "exam.questionPalette": `Kérdések`,
  "exam.questionsOption": `{n} kérdés`,
  "exam.resultsTitle": `A pontszámod`,
  "exam.reviewMistakes": `Tekintse át a hibáit ({n})`,
  "exam.scoreLine": `{total}/{correct} helyes`,
  "exam.seeProgress": `Lásd a fejlődést`,
  "exam.setupDescription": `Ez egy gyakorlati szimuláció, amely az alkalmazás tanulmányi kérdéseiből épül fel. Ez nem a hivatalos teszt, és nem jósolja meg az eredményt.`,
  "exam.setupTitle": `Állítsa be próbavizsgáját`,
  "exam.simulationNote": `Gyakorló szimuláció · nem hivatalos`,
  "exam.startExam": `Indítsa el a vizsgát`,
  "exam.timeLeft": `Maradt idő`,
  "exam.timedLabel": `időzített`,
  "exam.timedToggle": `Időzített (kérdésenként 90 másodperc)`,
  "exam.title": `Próbavizsga`,
  "exam.topicFilter": `Téma`,
  "exam.untimedLabel": `időzítetlen`,
  "footer.disclaimer": `A Citizen Prep egy független tanulmányi segédlet. Nem áll kapcsolatban Kanada kormányával vagy az IRCC-vel, illetve nem hagyja jóvá. Nem garantálja a múló eredményt.`,
  "header.appName": `Citizen Prep`,
  "header.tagline": `Független tanulmányi eszköz · Nem hivatalos`,
  "hero.sectionsProgress": `{done} of {total} sections · {percent}% complete`,
  "hero.subtitle": `Független tanulási eszköz · angol és francia · fiók nem szükséges`,
  "hero.title": `Készüljön fel az állampolgársági vizsgára`,
  "nav.exam": `Vizsga`,
  "nav.home": `Otthon`,
  "nav.practice": `Gyakorlat`,
  "nav.progress": `Haladás`,
  "nav.topics": `Témák`,
  "practice.allLevels": `Minden szinten`,
  "practice.allTopics": `Minden téma`,
  "practice.askAiAbout": `Kérdezd meg az AI-t erről a kérdésről`,
  "practice.bookmarkQuestion": `Könyvjelző kérdés`,
  "practice.bookmarked": `Könyvjelzővel ellátva`,
  "practice.checkAnswer": `Ellenőrizze a választ`,
  "practice.correct": `Helyes`,
  "practice.demoContent": `Demo tartalom`,
  "practice.difficulty": `Nehézség`,
  "practice.easy": `Könnyű`,
  "practice.explanation": `Magyarázat`,
  "practice.filters": `Szűrők`,
  "practice.hard": `Kemény`,
  "practice.incorrect": `Nem egészen`,
  "practice.medium": `Közepes`,
  "practice.nextQuestion": `Következő kérdés`,
  "practice.questionCounter": `Gyakorló kérdés: {n}/{total}`,
  "practice.reportIssue": `Probléma bejelentése`,
  "practice.title": `Gyakorlat`,
  "practice.topicFilter": `Téma`,
  "practice.tryAgain": `Próbáld újra`,
  "progress.accuracy": `Pontosság`,
  "progress.clearProgressDesc": `Ezzel törli válaszait, teljesítéseit, könyvjelzőit és vizsgaelőzményeit erről az eszközről. Nem lehet visszavonni.`,
  "progress.clearProgressLabel": `Törölje az összes tanulmányi előrehaladást`,
  "progress.confirmClear": `Igen, törölj mindent`,
  "progress.dailyGoal": `Napi cél`,
  "progress.details": `Részletek`,
  "progress.examHistory": `Vizsgatörténet`,
  "progress.noExams": `Még nem tettek vizsgát.`,
  "progress.noWrongAnswers": `Jelenleg nincs helytelen válasz.`,
  "progress.overview": `Áttekintés`,
  "progress.perTopic": `Témánként`,
  "progress.questionsAnswered": `Kérdésekre válaszolt`,
  "progress.reset": `Reset`,
  "progress.retryTopic": `Próbáld újra ezt a témát`,
  "progress.sectionsDone": `A szakaszok elkészültek`,
  "progress.suggestedNext": `Javasolt következő: {topic}`,
  "progress.title": `Haladás`,
  "progress.topicCompletion": `Téma befejezése`,
  "report.detailsPlaceholder": `Mondjon el többet (nem kötelező)`,
  "report.incorrectAnswer": `Helytelen válasz`,
  "report.outdatedInfo": `Elavult információ`,
  "report.submit": `Jelentés benyújtása`,
  "report.technicalIssue": `Technikai probléma`,
  "report.thanks": `Köszönjük – a jelentéseket helyileg ezen az eszközön tároljuk.`,
  "report.translationProblem": `Fordítási probléma`,
  "report.unclearExplanation": `Magyarázat peu claire`,
  "settings.about": `Erről az alkalmazásról`,
  "settings.appInterfaceLanguage": `Az alkalmazás felületének nyelve`,
  "settings.clearProgress": `Világos haladás`,
  "settings.clearProgressConfirm": `Biztos vagy benne? Ezzel törli az összes előrehaladását.`,
  "settings.interfaceDescription": `Menük, gombok és navigáció.`,
  "settings.language": `Nyelv`,
  "settings.machineNote": `A géppel lefordított tartalmat emberi ellenőr nem ellenőrizte. Itt semmi sem tekinthető felülvizsgáltnak, kivéve, ha ténylegesen felülvizsgálták.`,
  "settings.machineTranslatedBadge": `Gépi fordítás`,
  "settings.manageProgress": `Kezelje előrehaladási adatait`,
  "settings.notAvailable": `Még nem elérhető`,
  "settings.officialGuideLink": `Hivatalos tanulmányi útmutató`,
  "settings.officialTestLink": `Hivatalos állampolgársági teszt információ`,
  "settings.privacy": `Adatvédelem`,
  "settings.privacyText": `Válaszait, könyvjelzőit és beállításait a rendszer csak ezen az eszközön tárolja. Nincs szükség fiókra. A tanulmányi asszisztensnek feltett kérdéseket a rendszer elküldi egy mesterséges intelligencia-szolgáltatásnak, hogy válaszokat generáljon.`,
  "settings.reviewedBadge": `Áttekintve`,
  "settings.studyContentLanguage": `Tanulmányi tartalom nyelve`,
  "settings.studyDescription": `Szövegtanulás és magyarázatok. Egyik nyelven olvashat, miközben egy másik nyelven navigál.`,
  "settings.textSize": `Szöveg mérete`,
  "settings.title": `Beállítások elemre`,
  "topics.askAssistant": `Kérdezze meg az asszisztenst erről a részről`,
  "topics.bookmarkSection": `Könyvjelző rész`,
  "topics.bookmarkedSection": `Könyvjelzővel ellátva`,
  "topics.completed": `Befejezve`,
  "topics.continueLearningCard": `Folytassa a tanulást`,
  "topics.demoSourceNote": `Eredeti mintakérdés – nem hivatalos vizsgakérdés`,
  "topics.lastVerified": `Utolsó ellenőrzés: {date}`,
  "topics.markComplete": `Megjelölés készként`,
  "topics.markIncomplete": `Megjelölés hiányosként`,
  "topics.minRead": `{n} perc olvasás`,
  "topics.next": `Következő`,
  "topics.openOfficialPage": `Nyissa meg a hivatalos oldalt`,
  "topics.paraphrasedSourceNote": `Hivatalos anyagból átfogalmazva`,
  "topics.practiceTopic": `Gyakorold ezt a témát`,
  "topics.previous": `Előző`,
  "topics.reportIssue": `Probléma bejelentése`,
  "topics.reviewedOn": `reviewed {date}`,
  "topics.reviewedTranslation": `Ellenőrzött fordítás`,
  "topics.section": `szakasz`,
  "topics.sections": `szakaszok`,
  "topics.source": `Forrás`,
  "topics.sourcesDescription": `Az itt található tanulmány szövege a kanadai kormány állampolgársági tanulmányi útmutatójának átfogalmazása, és a feltüntetett dátumokon felülvizsgálva. A gyakorlati kérdéseket a hivatalos tanulmányi útmutatóból kutatják.`,
  "topics.sourcesHeading": `Tartalomforrások és felülvizsgálati dátumok`,
  "topics.studyLanguageLabel": `Tanulmányi tartalom nyelve`,
  "topics.title": `Tanulmányi témák`,
  "topics.vocabulary": `Szókincs`,
};
