// UI strings for 'is' — chunk of strings.generated.ts. DO NOT EDIT BY HAND.
import type { StringKey } from "../strings.generated";

export const is: Record<StringKey, string> = {
  "actions.askAi": `Spyrðu AI`,
  "actions.mockExam": `Sýndarpróf`,
  "actions.practice": `Æfðu þig`,
  "actions.quickActions": `Quick actions`,
  "actions.study": `Nám`,
  "assistant.aiEyebrow": `AI study assistant`,
  "assistant.answerLanguage": `Svarmál`,
  "assistant.charLimit": `{n} stafir eftir`,
  "assistant.checkingMaterial": `Checking the study material…`,
  "assistant.clearChat": `Clear chat`,
  "assistant.copied": `Afritað`,
  "assistant.copy": `Afrita`,
  "assistant.description": `Answers are written by AI using only this app's study material, with sources shown. AI can still make mistakes — check important details on the official Government of Canada pages. Not legal or immigration advice.`,
  "assistant.enFrancais": `En français`,
  "assistant.error": `Eitthvað fór úrskeiðis. Vinsamlegast reyndu aftur.`,
  "assistant.fromAppContent": `Úr viðurkenndu appi efni`,
  "assistant.groundedBadge": `Source-grounded`,
  "assistant.helpful": `Gagnlegt`,
  "assistant.inputPlaceholder": `Spyrðu spurningu um kanadískan ríkisborgararétt...`,
  "assistant.myAppLanguage": `My app language`,
  "assistant.notCovered": `Not covered — see official page`,
  "assistant.notHelpful": `Ekki gagnlegt`,
  "assistant.openAssistant": `Open study assistant`,
  "assistant.openLink": `Open assistant`,
  "assistant.practiceThis": `Æfðu þetta`,
  "assistant.questionAriaLabel": `Your question`,
  "assistant.reportIncorrect": `Report an incorrect answer`,
  "assistant.send": `Send`,
  "assistant.showSource": `Show source`,
  "assistant.simpleEnglish": `Einföld enska`,
  "assistant.source": `Heimild`,
  "assistant.starter1": `What are the three parts of Parliament?`,
  "assistant.starter2": `Explain the Charter simply`,
  "assistant.starter3": `Who represents the King in Canada?`,
  "assistant.starter4": `What does the knowledge test cover?`,
  "assistant.suggestedQuestions": `Tillögur að spurningum`,
  "assistant.thinking": `Er að hugsa…`,
  "assistant.title": `Námsaðstoðarmaður`,
  "assistant.tryAgain": `Try again`,
  "assistant.tryAsking": `Try asking:`,
  "assistant.vocabularyLabel": `Vocabulary:`,
  "assistant.whyItMatters": `Hvers vegna það skiptir máli fyrir prófið`,
  "bookmarks.continueStudying": `Continue studying`,
  "bookmarks.empty": `Engin bókamerki ennþá. Ýttu á stjörnuna á hvaða spurningu sem er til að vista hana til skoðunar.`,
  "bookmarks.emptyQuestions": `Nothing saved yet. Tap ☆ on a practice question.`,
  "bookmarks.emptySections": `Nothing saved yet. Tap ☆ while reading a section.`,
  "bookmarks.remove": `Fjarlægja`,
  "bookmarks.savedForReview": `vistað til skoðunar`,
  "bookmarks.savedQuestions": `Saved questions ({n})`,
  "bookmarks.savedSections": `Saved sections ({n})`,
  "bookmarks.search": `Search bookmarks…`,
  "bookmarks.title": `Bókamerki`,
  "cards.answered": `Svarað`,
  "cards.bookmarks": `vistað til skoðunar`,
  "cards.bookmarksLabel": `Bókamerki`,
  "cards.continueLearning": `Haltu áfram að læra`,
  "cards.correct": `Rétt`,
  "cards.dailyGoal": `{done}/{total} spurningar í dag`,
  "cards.dailyGoalLabel": `Daglegt markmið`,
  "cards.dailyGoalTitle": `Daily goal`,
  "cards.mockExam.subtitle": `Tímasett · 20 spurningar`,
  "cards.mockExam.title": `Sýndarpróf`,
  "cards.officialInfo.button": `Opna canada.ca`,
  "cards.officialInfo.subtitle": `Farðu á canada.ca fyrir opinberar upplýsingar`,
  "cards.officialInfo.title": `Opinberar upplýsingar`,
  "cards.progress": `Framfarir`,
  "cards.progressDetails": `Upplýsingar`,
  "cards.recentlyStudied": `Nýlega rannsökuð`,
  "cards.sections": `Köflum`,
  "cards.studyAssistant.subtitle": `Spyrðu hvað sem er um námsefnið`,
  "cards.studyAssistant.title": `Námsaðstoðarmaður`,
  "cards.todaysRecommendation": `Tilmæli dagsins`,
  "cards.verifiedSource.subtext": `Efni athugað gegn opinberum heimildum. Óháð námsaðstoð - ekki tengd eða samþykkt af ríkisstjórn Kanada eða IRCC.`,
  "cards.verifiedSource.title": `Staðfest heimild`,
  "common.back": `Til baka`,
  "common.cancel": `Hætta við`,
  "common.close": `Loka`,
  "common.continue": `Halda áfram`,
  "common.done": `Búið`,
  "common.emptyBookmarks": `Ekkert vistað ennþá`,
  "common.emptyRecentlyStudied": `Ekkert rannsakað enn - veldu efni til að byrja.`,
  "common.loading": `Hleður…`,
  "common.next": `Næst`,
  "common.of": `af`,
  "common.previous": `Fyrri`,
  "common.retry": `Reyndu aftur`,
  "common.save": `Vista`,
  "exam.allTopics": `Öll efni`,
  "exam.answeredCount": `{n} answered`,
  "exam.autosaveNote": `Your answers are saved as you go, so closing the app won't lose your progress.`,
  "exam.cancel": `Hætta við`,
  "exam.confirm": `Staðfesta`,
  "exam.confirmEnd": `{n} spurningum er ósvarað og verður merkt rangt.`,
  "exam.confirmEndTitle": `Loka prófi?`,
  "exam.endExamEarly": `Ljúktu prófi snemma`,
  "exam.examDisclaimer": `Þetta stig endurspeglar aðeins sýnishornsspurningar þessa forrits.`,
  "exam.finishExam": `Finish exam`,
  "exam.newExam": `Nýtt próf`,
  "exam.noMistakes": `Engin mistök - fullkomið stig!`,
  "exam.pastAttempts": `Past attempts`,
  "exam.questionAriaLabel": `Question {n}`,
  "exam.questionCount": `Fjöldi spurninga`,
  "exam.questionOf": `Question {n} of {total}`,
  "exam.questionPalette": `Spurningar`,
  "exam.questionsOption": `{n} questions`,
  "exam.resultsTitle": `Stig þitt`,
  "exam.reviewMistakes": `Skoðaðu mistökin þín ({n})`,
  "exam.scoreLine": `{correct} of {total} correct`,
  "exam.seeProgress": `See progress`,
  "exam.setupDescription": `This is a practice simulation built from this app's study questions. It is not the official test and does not predict your result.`,
  "exam.setupTitle": `Settu upp sýndarprófið þitt`,
  "exam.simulationNote": `Practice simulation · not official`,
  "exam.startExam": `Byrjaðu próf`,
  "exam.timeLeft": `Tími eftir`,
  "exam.timedLabel": `tímasett`,
  "exam.timedToggle": `Tímasett (90 sekúndur á spurningu)`,
  "exam.title": `Sýndarpróf`,
  "exam.topicFilter": `Umræðuefni`,
  "exam.untimedLabel": `ótímasett`,
  "footer.disclaimer": `Citizen Prep er óháð námsaðstoð. Ekki tengt eða samþykkt af ríkisstjórn Kanada eða IRCC. Það getur ekki tryggt árangurslausa niðurstöðu.`,
  "header.appName": `Borgaraundirbúningur`,
  "header.tagline": `Sjálfstætt námstæki · Ekki opinbert`,
  "hero.sectionsProgress": `{done} of {total} sections · {percent}% complete`,
  "hero.subtitle": `Sjálfstætt námstæki · Enska og franska · engin þörf á reikningi`,
  "hero.title": `Undirbúðu þig fyrir ríkisborgarapróf þitt`,
  "nav.exam": `Próf`,
  "nav.home": `Heim`,
  "nav.practice": `Æfðu þig`,
  "nav.progress": `Framfarir`,
  "nav.topics": `Viðfangsefni`,
  "practice.allLevels": `All levels`,
  "practice.allTopics": `Öll efni`,
  "practice.askAiAbout": `Spyrðu AI um þessa spurningu`,
  "practice.bookmarkQuestion": `Bókamerkja spurningu`,
  "practice.bookmarked": `Bókamerkt`,
  "practice.checkAnswer": `Athugaðu svar`,
  "practice.correct": `Rétt`,
  "practice.demoContent": `Demo efni`,
  "practice.difficulty": `Erfiðleikar`,
  "practice.easy": `Auðvelt`,
  "practice.explanation": `Skýring`,
  "practice.filters": `Filters`,
  "practice.hard": `Erfitt`,
  "practice.incorrect": `Ekki alveg`,
  "practice.medium": `Miðlungs`,
  "practice.nextQuestion": `Næsta spurning`,
  "practice.questionCounter": `Æfðu spurningu {n} af {total}`,
  "practice.reportIssue": `Tilkynna mál`,
  "practice.title": `Practice`,
  "practice.topicFilter": `Umræðuefni`,
  "practice.tryAgain": `Reyndu aftur`,
  "progress.accuracy": `Nákvæmni`,
  "progress.clearProgressDesc": `This deletes your answers, completions, bookmarks and exam history from this device. It cannot be undone.`,
  "progress.clearProgressLabel": `Clear all study progress`,
  "progress.confirmClear": `Yes, clear everything`,
  "progress.dailyGoal": `Daglegt markmið`,
  "progress.details": `Upplýsingar`,
  "progress.examHistory": `Prófsaga`,
  "progress.noExams": `Engin próf tekin ennþá.`,
  "progress.noWrongAnswers": `No incorrect answers to review right now.`,
  "progress.overview": `Overview`,
  "progress.perTopic": `Á hverju efni`,
  "progress.questionsAnswered": `Spurningum svarað`,
  "progress.reset": `Reset`,
  "progress.retryTopic": `Reyndu þetta efni aftur`,
  "progress.sectionsDone": `Köflum lokið`,
  "progress.suggestedNext": `Suggested next: {topic}`,
  "progress.title": `Framfarir`,
  "progress.topicCompletion": `Topic completion`,
  "report.detailsPlaceholder": `Tell us more (optional)`,
  "report.incorrectAnswer": `Incorrect answer`,
  "report.outdatedInfo": `Outdated information`,
  "report.submit": `Submit report`,
  "report.technicalIssue": `Technical issue`,
  "report.thanks": `Thanks — reports are stored locally on this device.`,
  "report.translationProblem": `Translation problem`,
  "report.unclearExplanation": `Explication peu claire`,
  "settings.about": `About this app`,
  "settings.appInterfaceLanguage": `Tungumál appviðmóts`,
  "settings.clearProgress": `Greinar framfarir`,
  "settings.clearProgressConfirm": `Ertu viss? Þetta mun eyða öllum framförum þínum.`,
  "settings.interfaceDescription": `Menus, buttons and navigation.`,
  "settings.language": `Tungumál`,
  "settings.machineNote": `Machine-translated content has not been checked by a human reviewer. Nothing here is labelled as reviewed unless it has actually been reviewed.`,
  "settings.machineTranslatedBadge": `Vélþýtt`,
  "settings.manageProgress": `Manage your progress data`,
  "settings.notAvailable": `Ekki enn í boði`,
  "settings.officialGuideLink": `Official study guide`,
  "settings.officialTestLink": `Official citizenship test information`,
  "settings.privacy": `Privacy`,
  "settings.privacyText": `Your answers, bookmarks and settings are stored only on this device. No account is needed. Questions you ask the study assistant are sent to an AI service to generate answers.`,
  "settings.reviewedBadge": `Farið yfir`,
  "settings.studyContentLanguage": `Lærðu efnismál`,
  "settings.studyDescription": `Learning text and explanations. You can read in one language while navigating in another.`,
  "settings.textSize": `Textastærð`,
  "settings.title": `Stillingar`,
  "topics.askAssistant": `Spyrðu aðstoðarmanninn um þennan hluta`,
  "topics.bookmarkSection": `Bookmark section`,
  "topics.bookmarkedSection": `Bookmarked`,
  "topics.completed": `Lokið`,
  "topics.continueLearningCard": `Haltu áfram að læra`,
  "topics.demoSourceNote": `Original sample question — not an official exam question`,
  "topics.lastVerified": `Síðast staðfest {date}`,
  "topics.markComplete": `Merktu sem lokið`,
  "topics.markIncomplete": `Merktu sem ófullnægjandi`,
  "topics.minRead": `{n} mín. lestur`,
  "topics.next": `Næst`,
  "topics.openOfficialPage": `Opna opinbera síðu`,
  "topics.paraphrasedSourceNote": `Paraphrased from official material`,
  "topics.practiceTopic": `Practise this topic`,
  "topics.previous": `Fyrri`,
  "topics.reportIssue": `Tilkynna mál`,
  "topics.reviewedOn": `reviewed {date}`,
  "topics.reviewedTranslation": `Yfirfarin þýðing`,
  "topics.section": `kafla`,
  "topics.sections": `köflum`,
  "topics.source": `Heimild`,
  "topics.sourcesDescription": `Study text here is paraphrased from the Government of Canada citizenship study guide and reviewed on the dates shown. Practice questions are researched from the official study guide.`,
  "topics.sourcesHeading": `Content sources and review dates`,
  "topics.studyLanguageLabel": `Study content language`,
  "topics.title": `Námsefni`,
  "topics.vocabulary": `Orðaforði`,
};
