// UI strings for 'it' — chunk of strings.generated.ts. DO NOT EDIT BY HAND.
import type { StringKey } from "../strings.generated";

export const it: Record<StringKey, string> = {
  "actions.askAi": `Chiedi all'AI`,
  "actions.mockExam": `Esame simulato`,
  "actions.practice": `Pratica`,
  "actions.quickActions": `Quick actions`,
  "actions.study": `Studia`,
  "assistant.aiEyebrow": `Assistente allo studio dell'IA`,
  "assistant.answerLanguage": `Lingua della risposta`,
  "assistant.charLimit": `{n} caratteri rimasti`,
  "assistant.checkingMaterial": `Controllo del materiale di studio...`,
  "assistant.clearChat": `Chiacchierata chiara`,
  "assistant.copied": `Copiato`,
  "assistant.copy": `Copia`,
  "assistant.description": `Le risposte vengono scritte dall'intelligenza artificiale utilizzando solo il materiale di studio di questa app, con le fonti mostrate. L'intelligenza artificiale può ancora commettere errori: controlla i dettagli importanti sulle pagine ufficiali del governo canadese. Non consulenza legale o sull'immigrazione.`,
  "assistant.enFrancais": `In francese`,
  "assistant.error": `Qualcosa è andato storto. Per favore riprova.`,
  "assistant.fromAppContent": `Dai contenuti dell'app approvati`,
  "assistant.groundedBadge": `Basato sulla fonte`,
  "assistant.helpful": `Utile`,
  "assistant.inputPlaceholder": `Fai una domanda sulla cittadinanza canadese…`,
  "assistant.myAppLanguage": `La lingua della mia app`,
  "assistant.notCovered": `Non coperto: vedi la pagina ufficiale`,
  "assistant.notHelpful": `Non utile`,
  "assistant.openAssistant": `Assistente allo studio aperto`,
  "assistant.openLink": `Assistente aperto`,
  "assistant.practiceThis": `Esercitati in questo`,
  "assistant.questionAriaLabel": `La tua domanda`,
  "assistant.reportIncorrect": `Segnala una risposta errata`,
  "assistant.send": `Invia`,
  "assistant.showSource": `Mostra fonte`,
  "assistant.simpleEnglish": `Inglese semplice`,
  "assistant.source": `Fonte`,
  "assistant.starter1": `Quali sono le tre parti del Parlamento?`,
  "assistant.starter2": `Spiegare la Carta in modo semplice`,
  "assistant.starter3": `Chi rappresenta il re in Canada?`,
  "assistant.starter4": `Cosa copre il test di conoscenza?`,
  "assistant.suggestedQuestions": `Domande suggerite`,
  "assistant.thinking": `Pensando…`,
  "assistant.title": `Assistente allo studio`,
  "assistant.tryAgain": `Riprova`,
  "assistant.tryAsking": `Prova a chiedere:`,
  "assistant.vocabularyLabel": `Vocabolario:`,
  "assistant.whyItMatters": `Perché è importante per il test`,
  "auth.account": `Account`,
  "auth.checkEmail": `Check your email to confirm your account, then sign in.`,
  "auth.close": `Close`,
  "auth.codeLabel": `Verification code`,
  "auth.codeResent": `New code sent. Check your email.`,
  "auth.codeSent": `Code sent! Check your email and enter the 6-digit code.`,
  "auth.createAccount": `Create account`,
  "auth.dataDeletedMsg": `Your progress and profile data were deleted.`,
  "auth.deleteConfirm": `Tap again to permanently delete`,
  "auth.deleteData": `Delete my data`,
  "auth.email": `Email`,
  "auth.haveAccount": `Already have an account?`,
  "auth.mfaCodeLabel": `Authenticator code`,
  "auth.mfaDisable": `Disable 2FA`,
  "auth.mfaDisabledMsg": `Two-factor authentication is now OFF.`,
  "auth.mfaEnable": `Enable 2FA`,
  "auth.mfaEnabledMsg": `Two-factor authentication is now ON for your account.`,
  "auth.mfaPendingWarn": `2FA code still needed to finish signing in.`,
  "auth.mfaPrompt": `This account uses 2FA — enter the code from your authenticator app.`,
  "auth.mfaScanHint": `Scan this QR code with your authenticator app (Google Authenticator, Authy, 1Password…), then enter the 6-digit code it shows.`,
  "auth.mfaSetupTitle": `Set up two-factor authentication`,
  "auth.mfaSubtitle": `Enter the 6-digit code from your authenticator app.`,
  "auth.mfaTitle": `Two-factor authentication`,
  "auth.noAccount": `Don't have an account?`,
  "auth.password": `Password`,
  "auth.passwordHint": `At least 6 characters`,
  "auth.privacy": `Privacy`,
  "auth.privacyNote": `Your email and progress are private — only you can see them.`,
  "auth.resendCode": `Resend code`,
  "auth.security": `Security`,
  "auth.signIn": `Sign in`,
  "auth.signOut": `Sign out`,
  "auth.signUp": `Sign up`,
  "auth.subtitle": `Save your progress across devices. Your data stays private.`,
  "auth.title": `Account`,
  "auth.verify": `Verify`,
  "auth.verifyCodeSubtitle": `We sent a 6-digit code to your email. Enter it below to finish signing up.`,
  "auth.verifyCodeTitle": `Enter your code`,
  "auth.working": `Please wait…`,
  "bookmarks.continueStudying": `Continua a studiare`,
  "bookmarks.empty": `Nessun segnalibro ancora. Tocca la stella su qualsiasi domanda per salvarla per la revisione.`,
  "bookmarks.emptyQuestions": `Niente ancora salvato. Tocca ☆ su una domanda pratica.`,
  "bookmarks.emptySections": `Niente ancora salvato. Tocca ☆ mentre leggi una sezione.`,
  "bookmarks.remove": `Rimuovi`,
  "bookmarks.savedForReview": `salvato per la revisione`,
  "bookmarks.savedQuestions": `Domande salvate ({n})`,
  "bookmarks.savedSections": `Sezioni salvate ({n})`,
  "bookmarks.search": `Cerca segnalibri...`,
  "bookmarks.title": `Segnalibri`,
  "cards.answered": `Risposto`,
  "cards.bookmarks": `salvato per la revisione`,
  "cards.bookmarksLabel": `Segnalibri`,
  "cards.continueLearning": `Continua ad imparare`,
  "cards.correct": `Corretto`,
  "cards.dailyGoal": `{done}/{total} domande oggi`,
  "cards.dailyGoalLabel": `Obiettivo quotidiano`,
  "cards.dailyGoalTitle": `Daily goal`,
  "cards.mockExam.subtitle": `A tempo · 20 domande`,
  "cards.mockExam.title": `Esame simulato`,
  "cards.officialInfo.button": `Apri Canada.ca`,
  "cards.officialInfo.subtitle": `Visita canada.ca per i dettagli ufficiali`,
  "cards.officialInfo.title": `Informazioni ufficiali`,
  "cards.progress": `Progresso`,
  "cards.progressDetails": `Dettagli`,
  "cards.recentlyStudied": `Studiato di recente`,
  "cards.sections": `Sezioni`,
  "cards.studyAssistant.subtitle": `Chiedi qualsiasi cosa sul materiale di studio`,
  "cards.studyAssistant.title": `Assistente allo studio`,
  "cards.todaysRecommendation": `La raccomandazione di oggi`,
  "cards.verifiedSource.subtext": `Contenuto confrontato con fonti ufficiali. Aiuto allo studio indipendente: non affiliato o approvato dal governo del Canada o dall'IRCC.`,
  "cards.verifiedSource.title": `Fonte verificata`,
  "common.back": `Indietro`,
  "common.cancel": `Annulla`,
  "common.close": `Chiudi`,
  "common.continue": `Continua`,
  "common.done": `Fatto`,
  "common.emptyBookmarks": `Niente ancora salvato`,
  "common.emptyRecentlyStudied": `Ancora niente di studiato: scegli un argomento per iniziare.`,
  "common.loading": `Caricamento…`,
  "common.next": `Avanti`,
  "common.of": `di`,
  "common.previous": `Precedente`,
  "common.retry": `Riprova`,
  "common.save": `Salva`,
  "exam.allTopics": `Tutti gli argomenti`,
  "exam.answeredCount": `{n} hanno risposto`,
  "exam.autosaveNote": `Le tue risposte vengono salvate mentre procedi, quindi chiudendo l'app non perderai i tuoi progressi.`,
  "exam.cancel": `Annulla`,
  "exam.confirm": `Conferma`,
  "exam.confirmEnd": `{n} domande sono senza risposta e verranno contrassegnate come errate.`,
  "exam.confirmEndTitle": `Fine esame?`,
  "exam.endExamEarly": `Terminare l'esame in anticipo`,
  "exam.examDisclaimer": `Questo punteggio riflette solo le domande di esempio di questa app.`,
  "exam.finishExam": `Termina l'esame`,
  "exam.newExam": `Nuovo esame`,
  "exam.noMistakes": `Nessun errore: punteggio perfetto!`,
  "exam.pastAttempts": `Tentativi passati`,
  "exam.questionAriaLabel": `Domanda {n}`,
  "exam.questionCount": `Numero di domande`,
  "exam.questionOf": `Question {n} of {total}`,
  "exam.questionPalette": `Domande`,
  "exam.questionsOption": `{n} domande`,
  "exam.resultsTitle": `Il tuo punteggio`,
  "exam.reviewMistakes": `Rivedi i tuoi errori ({n})`,
  "exam.scoreLine": `{correct} of {total} correct`,
  "exam.seeProgress": `Vedi i progressi`,
  "exam.setupDescription": `Questa è una simulazione pratica costruita a partire dalle domande di studio di questa app. Non è il test ufficiale e non prevede il risultato.`,
  "exam.setupTitle": `Imposta il tuo esame simulato`,
  "exam.simulationNote": `Simulazione pratica · non ufficiale`,
  "exam.startExam": `Inizia l'esame`,
  "exam.timeLeft": `Tempo rimasto`,
  "exam.timedLabel": `cronometrato`,
  "exam.timedToggle": `A tempo (90 secondi per domanda)`,
  "exam.title": `Esame simulato`,
  "exam.topicFilter": `Argomento`,
  "exam.untimedLabel": `senza orario`,
  "footer.disclaimer": `Citizen Prep è un sussidio di studio indipendente. Non affiliato o approvato dal governo del Canada o dall'IRCC. Non può garantire un risultato positivo.`,
  "header.appName": `Preparazione del cittadino`,
  "header.tagline": `Strumento di studio indipendente · Non ufficiale`,
  "hero.sectionsProgress": `{done} of {total} sections · {percent}% complete`,
  "hero.subtitle": `Strumento di studio indipendente · Inglese e francese · nessun account necessario`,
  "hero.title": `Preparati per il test di cittadinanza`,
  "nav.exam": `Esame`,
  "nav.home": `Casa`,
  "nav.practice": `Pratica`,
  "nav.progress": `Progresso`,
  "nav.topics": `Argomenti`,
  "practice.allLevels": `Tutti i livelli`,
  "practice.allTopics": `Tutti gli argomenti`,
  "practice.askAiAbout": `Chiedi ad AI riguardo a questa domanda`,
  "practice.bookmarkQuestion": `Domanda sui segnalibri`,
  "practice.bookmarked": `Segnato`,
  "practice.checkAnswer": `Controlla la risposta`,
  "practice.correct": `Corretto`,
  "practice.demoContent": `Contenuti dimostrativi`,
  "practice.difficulty": `Difficoltà`,
  "practice.easy": `Facile`,
  "practice.explanation": `Spiegazione`,
  "practice.filters": `Filtri`,
  "practice.hard": `Difficile`,
  "practice.incorrect": `Non proprio`,
  "practice.medium": `Medio`,
  "practice.nextQuestion": `Prossima domanda`,
  "practice.questionCounter": `Practice question {n} of {total}`,
  "practice.reportIssue": `Segnala un problema`,
  "practice.title": `Pratica`,
  "practice.topicFilter": `Argomento`,
  "practice.tryAgain": `Riprova`,
  "progress.accuracy": `Precisione`,
  "progress.clearProgressDesc": `Questa operazione eliminerà le risposte, i completamenti, i segnalibri e la cronologia degli esami da questo dispositivo. Non è possibile annullarlo.`,
  "progress.clearProgressLabel": `Cancella tutti i progressi dello studio`,
  "progress.confirmClear": `Sì, cancella tutto`,
  "progress.dailyGoal": `Obiettivo quotidiano`,
  "progress.details": `Dettagli`,
  "progress.examHistory": `Storia dell'esame`,
  "progress.noExams": `Nessun esame ancora sostenuto.`,
  "progress.noWrongAnswers": `Nessuna risposta errata da rivedere in questo momento.`,
  "progress.overview": `Panoramica`,
  "progress.perTopic": `Per argomento`,
  "progress.questionsAnswered": `Risposte alle domande`,
  "progress.reset": `Ripristina`,
  "progress.retryTopic": `Riprova questo argomento`,
  "progress.sectionsDone": `Sezioni completate`,
  "progress.suggestedNext": `Prossimo suggerimento: {topic}`,
  "progress.title": `Progresso`,
  "progress.topicCompletion": `Completamento dell'argomento`,
  "report.detailsPlaceholder": `Dicci di più (facoltativo)`,
  "report.incorrectAnswer": `Risposta errata`,
  "report.outdatedInfo": `Informazioni obsolete`,
  "report.submit": `Invia rapporto`,
  "report.technicalIssue": `Problema tecnico`,
  "report.thanks": `Grazie: i rapporti vengono archiviati localmente su questo dispositivo.`,
  "report.translationProblem": `Problema di traduzione`,
  "report.unclearExplanation": `Spiegazione peu claire`,
  "settings.about": `Informazioni su questa app`,
  "settings.appInterfaceLanguage": `Lingua dell'interfaccia dell'app`,
  "settings.clearProgress": `Progressi evidenti`,
  "settings.clearProgressConfirm": `Sei sicuro? Questo cancellerà tutti i tuoi progressi.`,
  "settings.interfaceDescription": `Menu, pulsanti e navigazione.`,
  "settings.language": `Lingua`,
  "settings.machineNote": `I contenuti tradotti automaticamente non sono stati controllati da un revisore umano. Niente qui è etichettato come recensito a meno che non sia stato effettivamente recensito.`,
  "settings.machineTranslatedBadge": `Tradotto automaticamente`,
  "settings.manageProgress": `Gestisci i tuoi dati di avanzamento`,
  "settings.notAvailable": `Non ancora disponibile`,
  "settings.officialGuideLink": `Guida ufficiale allo studio`,
  "settings.officialTestLink": `Informazioni sul test di cittadinanza ufficiale`,
  "settings.privacy": `Privacy`,
  "settings.privacyText": `Le tue risposte, i tuoi segnalibri e le tue impostazioni vengono memorizzati solo su questo dispositivo. Non è necessario alcun account. Le domande che poni all'assistente di studio vengono inviate a un servizio di intelligenza artificiale per generare risposte.`,
  "settings.reviewedBadge": `Recensito`,
  "settings.studyContentLanguage": `Studia la lingua dei contenuti`,
  "settings.studyDescription": `Apprendimento del testo e delle spiegazioni. Puoi leggere in una lingua mentre navighi in un'altra.`,
  "settings.textSize": `Dimensione del testo`,
  "settings.title": `Impostazioni`,
  "topics.askAssistant": `Chiedi all'assistente informazioni su questa sezione`,
  "topics.bookmarkSection": `Sezione segnalibri`,
  "topics.bookmarkedSection": `Segnato`,
  "topics.completed": `Completato`,
  "topics.continueLearningCard": `Continua ad imparare`,
  "topics.demoSourceNote": `Domanda di esempio originale: non è una domanda d'esame ufficiale`,
  "topics.lastVerified": `Ultima verifica {date}`,
  "topics.markComplete": `Contrassegna come completo`,
  "topics.markIncomplete": `Contrassegna come incompleto`,
  "topics.minRead": `{n} minuti di lettura`,
  "topics.next": `Avanti`,
  "topics.openOfficialPage": `Apri la pagina ufficiale`,
  "topics.paraphrasedSourceNote": `Parafrasato da materiale ufficiale`,
  "topics.practiceTopic": `Esercitati su questo argomento`,
  "topics.previous": `Precedente`,
  "topics.reportIssue": `Segnala un problema`,
  "topics.reviewedOn": `reviewed {date}`,
  "topics.reviewedTranslation": `Traduzione rivista`,
  "topics.section": `Sezione`,
  "topics.sections": `sezioni`,
  "topics.source": `Fonte`,
  "topics.sourcesDescription": `Il testo dello studio qui è parafrasato dalla guida allo studio sulla cittadinanza del governo canadese e rivisto nelle date indicate. Le domande pratiche vengono ricercate dalla guida allo studio ufficiale.`,
  "topics.sourcesHeading": `Fonti dei contenuti e date di revisione`,
  "topics.studyLanguageLabel": `Studia la lingua dei contenuti`,
  "topics.title": `Argomenti di studio`,
  "topics.vocabulary": `Vocabolario`,
};
