// UI strings for 'lb' — chunk of strings.generated.ts. DO NOT EDIT BY HAND.
import type { StringKey } from "../strings.generated";

export const lb: Record<StringKey, string> = {
  "actions.askAi": `Frot AI`,
  "actions.mockExam": `Mock Examen`,
  "actions.practice": `Praxis`,
  "actions.quickActions": `Quick actions`,
  "actions.study": `Etude`,
  "assistant.aiEyebrow": `AI Studie Assistent`,
  "assistant.answerLanguage": `Äntwert Sprooch`,
  "assistant.charLimit": `{n} Zeeche lénks`,
  "assistant.checkingMaterial": `Iwwerpréift d'Studiematerial ...`,
  "assistant.clearChat": `Kloer Chat`,
  "assistant.copied": `Copied`,
  "assistant.copy": `Kopie`,
  "assistant.description": `D'Äntwerte gi vun AI geschriwwen mat nëmmen dem Studiematerial vun dëser App, mat Quelle gewisen. AI kann nach ëmmer Feeler maachen - kontrolléiert wichteg Detailer op den offiziellen Regierung vu Kanada Säiten. Net legal oder Immigratiounsberodung.`,
  "assistant.enFrancais": `En français`,
  "assistant.error": `Eppes ass falsch gaangen. Probéiert w.e.g. nach eng Kéier.`,
  "assistant.fromAppContent": `Vun guttgeheescht App Inhalt`,
  "assistant.groundedBadge": `Source-Grondlag`,
  "assistant.helpful": `Hëllefsbereet`,
  "assistant.inputPlaceholder": `Stellt eng Fro iwwer kanadesch Nationalitéit ...`,
  "assistant.myAppLanguage": `Meng App Sprooch`,
  "assistant.notCovered": `Net iwwerdeckt - kuckt offiziell Säit`,
  "assistant.notHelpful": `Net hëllefräich`,
  "assistant.openAssistant": `Open Studie Assistent`,
  "assistant.openLink": `Open Assistent`,
  "assistant.practiceThis": `Praxis dëst`,
  "assistant.questionAriaLabel": `Är Fro`,
  "assistant.reportIncorrect": `Rapport eng falsch Äntwert`,
  "assistant.send": `Schécken`,
  "assistant.showSource": `Quell weisen`,
  "assistant.simpleEnglish": `Einfach Englesch`,
  "assistant.source": `Quell`,
  "assistant.starter1": `Wat sinn déi dräi Deeler vum Parlament?`,
  "assistant.starter2": `Erklärt d'Charta einfach`,
  "assistant.starter3": `Wien representéiert de Kinnek a Kanada?`,
  "assistant.starter4": `Wat deckt de Wëssenstest?`,
  "assistant.suggestedQuestions": `Froe proposéiert`,
  "assistant.thinking": `Denken…`,
  "assistant.title": `Studie Assistent`,
  "assistant.tryAgain": `Probéiert nach eng Kéier`,
  "assistant.tryAsking": `Probéiert ze froen:`,
  "assistant.vocabularyLabel": `Vocabulaire:`,
  "assistant.whyItMatters": `Firwat ass et wichteg fir den Test`,
  "auth.account": `Account`,
  "auth.checkEmail": `Check your email to confirm your account, then sign in.`,
  "auth.close": `Close`,
  "auth.codeLabel": `Verification code`,
  "auth.codeResent": `New code sent. Check your email.`,
  "auth.codeSent": `Code sent! Check your email and enter the 6-digit code.`,
  "auth.createAccount": `Create account`,
  "auth.dataDeletedMsg": `Your progress and profile data were deleted.`,
  "auth.deleteConfirm": `Tap again to permanently delete`,
  "auth.deleteData": `Delete my data`,
  "auth.email": `Email`,
  "auth.haveAccount": `Already have an account?`,
  "auth.mfaCodeLabel": `Authenticator code`,
  "auth.mfaDisable": `Disable 2FA`,
  "auth.mfaDisabledMsg": `Two-factor authentication is now OFF.`,
  "auth.mfaEnable": `Enable 2FA`,
  "auth.mfaEnabledMsg": `Two-factor authentication is now ON for your account.`,
  "auth.mfaPendingWarn": `2FA code still needed to finish signing in.`,
  "auth.mfaPrompt": `This account uses 2FA — enter the code from your authenticator app.`,
  "auth.mfaScanHint": `Scan this QR code with your authenticator app (Google Authenticator, Authy, 1Password…), then enter the 6-digit code it shows.`,
  "auth.mfaSetupTitle": `Set up two-factor authentication`,
  "auth.mfaSubtitle": `Enter the 6-digit code from your authenticator app.`,
  "auth.mfaTitle": `Two-factor authentication`,
  "auth.noAccount": `Don't have an account?`,
  "auth.password": `Password`,
  "auth.passwordHint": `At least 6 characters`,
  "auth.privacy": `Privacy`,
  "auth.privacyNote": `Your email and progress are private — only you can see them.`,
  "auth.resendCode": `Resend code`,
  "auth.security": `Security`,
  "auth.signIn": `Sign in`,
  "auth.signOut": `Sign out`,
  "auth.signUp": `Sign up`,
  "auth.subtitle": `Save your progress across devices. Your data stays private.`,
  "auth.title": `Account`,
  "auth.verify": `Verify`,
  "auth.verifyCodeSubtitle": `We sent a 6-digit code to your email. Enter it below to finish signing up.`,
  "auth.verifyCodeTitle": `Enter your code`,
  "auth.working": `Please wait…`,
  "bookmarks.continueStudying": `Fuert weider ze studéieren`,
  "bookmarks.empty": `Nach keng Lieszeeche. Tippen op de Stär op all Fro fir et fir Iwwerpréiwung ze späicheren.`,
  "bookmarks.emptyQuestions": `Nach näischt gespuert. Tippen ☆ op eng Praxisfro.`,
  "bookmarks.emptySections": `Nach näischt gespuert. Tippen ☆ wärend Dir eng Sektioun liest.`,
  "bookmarks.remove": `Ewechzehuelen`,
  "bookmarks.savedForReview": `gespäichert fir Iwwerpréiwung`,
  "bookmarks.savedQuestions": `Gespäichert Froen ({n})`,
  "bookmarks.savedSections": `Gespäichert Sektiounen ({n})`,
  "bookmarks.search": `Lieszeechen sichen…`,
  "bookmarks.title": `Lieszeeche`,
  "cards.answered": `Geäntwert`,
  "cards.bookmarks": `gespäichert fir Iwwerpréiwung`,
  "cards.bookmarksLabel": `Lieszeeche`,
  "cards.continueLearning": `Continue learning`,
  "cards.correct": `Correct`,
  "cards.dailyGoal": `{done}/{total} questions today`,
  "cards.dailyGoalLabel": `Daily goal`,
  "cards.dailyGoalTitle": `Daily goal`,
  "cards.mockExam.subtitle": `Timed · 20 Froen`,
  "cards.mockExam.title": `Mock Examen`,
  "cards.officialInfo.button": `Open canada.ca`,
  "cards.officialInfo.subtitle": `Besicht canada.ca fir offiziell Detailer`,
  "cards.officialInfo.title": `Offiziell Informatioun`,
  "cards.progress": `Fortschrëtt`,
  "cards.progressDetails": `Detailer`,
  "cards.recentlyStudied": `Viru kuerzem studéiert`,
  "cards.sections": `Sektiounen`,
  "cards.studyAssistant.subtitle": `Frot eppes iwwer d'Studiematerial`,
  "cards.studyAssistant.title": `Studie Assistent`,
  "cards.todaysRecommendation": `Recommandatioun vun haut`,
  "cards.verifiedSource.subtext": `Inhalt iwwerpréift géint offiziell Quellen. Onofhängeg Studiehëllef - net verbonne mat oder ënnerstëtzt vun der Regierung vu Kanada oder IRCC.`,
  "cards.verifiedSource.title": `Verifizéiert Quell`,
  "common.back": `Zréck`,
  "common.cancel": `Ofbriechen`,
  "common.close": `Zoumaachen`,
  "common.continue": `Fuert weider`,
  "common.done": `Done`,
  "common.emptyBookmarks": `Nach näischt gespuert`,
  "common.emptyRecentlyStudied": `Näischt nach studéiert - wielt en Thema fir unzefänken.`,
  "common.loading": `Lueden…`,
  "common.next": `Nächst`,
  "common.of": `vun`,
  "common.previous": `Virdrun`,
  "common.retry": `Nach eng Kéier probéieren`,
  "common.save": `Spueren`,
  "exam.allTopics": `All Themen`,
  "exam.answeredCount": `{n} geäntwert`,
  "exam.autosaveNote": `Är Äntwerte gi gespäichert wéi Dir gitt, sou datt d'App zoumaachen wäert Äre Fortschrëtt net verléieren.`,
  "exam.cancel": `Ofbriechen`,
  "exam.confirm": `Confirméieren`,
  "exam.confirmEnd": `{n} Froen sinn onbeäntwert a gi falsch markéiert.`,
  "exam.confirmEndTitle": `Examen ofschléissen?`,
  "exam.endExamEarly": `Enn Examen fréi`,
  "exam.examDisclaimer": `Dëse Score reflektéiert nëmmen d'Probe Froen vun dëser App.`,
  "exam.finishExam": `Examen fäerdeg`,
  "exam.newExam": `Neien Examen`,
  "exam.noMistakes": `Keng Feeler - perfekt Score!`,
  "exam.pastAttempts": `Vergaangenheet Versich`,
  "exam.questionAriaLabel": `Fro {n}`,
  "exam.questionCount": `Zuel vu Froen`,
  "exam.questionOf": `Question {n} of {total}`,
  "exam.questionPalette": `Froen`,
  "exam.questionsOption": `{n} Froen`,
  "exam.resultsTitle": `Äre Score`,
  "exam.reviewMistakes": `Iwwerpréift Är Feeler ({n})`,
  "exam.scoreLine": `{correct} of {total} correct`,
  "exam.seeProgress": `Gesinn Fortschrëtter`,
  "exam.setupDescription": `Dëst ass eng Praxis Simulatioun gebaut aus de Studie Froen vun dëser App. Et ass net den offiziellen Test a viraussoen net Äert Resultat.`,
  "exam.setupTitle": `Setzt Är Spottprüfung op`,
  "exam.simulationNote": `Praxis Simulatioun · net offiziell`,
  "exam.startExam": `Start Examen`,
  "exam.timeLeft": `Zäit lénks`,
  "exam.timedLabel": `Zäitplang`,
  "exam.timedToggle": `Zäitgeschriwwe (90 Sekonnen pro Fro)`,
  "exam.title": `Mock Examen`,
  "exam.topicFilter": `Thema`,
  "exam.untimedLabel": `untimeed`,
  "footer.disclaimer": `Citizen Prep ass eng onofhängeg Studiehëllef. Net verbonne mat oder ënnerstëtzt vun der Regierung vu Kanada oder IRCC. Et kann net e passéieren Resultat garantéieren.`,
  "header.appName": `Bierger Prep`,
  "header.tagline": `Onofhängeg Etude Outil · Net offiziell`,
  "hero.sectionsProgress": `{done} of {total} sections · {percent}% complete`,
  "hero.subtitle": `Onofhängeg Studieinstrument · Englesch & Franséisch · kee Kont néideg`,
  "hero.title": `Bereet Iech op Är Nationalitéitstest`,
  "nav.exam": `Examen`,
  "nav.home": `Doheem`,
  "nav.practice": `Praxis`,
  "nav.progress": `Fortschrëtt`,
  "nav.topics": `Themen`,
  "practice.allLevels": `All Niveauen`,
  "practice.allTopics": `All Themen`,
  "practice.askAiAbout": `Frot AI iwwer dës Fro`,
  "practice.bookmarkQuestion": `Bookmark Fro`,
  "practice.bookmarked": `Bookmarkéiert`,
  "practice.checkAnswer": `Check Äntwert`,
  "practice.correct": `Correct`,
  "practice.demoContent": `Demo content`,
  "practice.difficulty": `Schwieregkeet`,
  "practice.easy": `Einfach`,
  "practice.explanation": `Erklärung`,
  "practice.filters": `Filteren`,
  "practice.hard": `Schwéier`,
  "practice.incorrect": `Net ganz`,
  "practice.medium": `Mëttelméisseg`,
  "practice.nextQuestion": `Nächst Fro`,
  "practice.questionCounter": `Practice question {n} of {total}`,
  "practice.reportIssue": `Rapport en Thema`,
  "practice.title": `Praxis`,
  "practice.topicFilter": `Thema`,
  "practice.tryAgain": `Probéiert nach eng Kéier`,
  "progress.accuracy": `Genauegkeet`,
  "progress.clearProgressDesc": `Dëst läscht Är Äntwerten, Fäerdegstellungen, Lieszeechen an Examengeschicht vun dësem Apparat. Et kann net réckgängeg gemaach ginn.`,
  "progress.clearProgressLabel": `Kloer all Studie Fortschrëtter`,
  "progress.confirmClear": `Jo, kloer alles`,
  "progress.dailyGoal": `Daily goal`,
  "progress.details": `Detailer`,
  "progress.examHistory": `Examen Geschicht`,
  "progress.noExams": `Nach keng Examen ofgeholl.`,
  "progress.noWrongAnswers": `Keng falsch Äntwerte fir elo ze iwwerpréiwen.`,
  "progress.overview": `Iwwersiicht`,
  "progress.perTopic": `Per Thema`,
  "progress.questionsAnswered": `Froen geäntwert`,
  "progress.reset": `Zerécksetzen`,
  "progress.retryTopic": `Probéiert dëst Thema erëm`,
  "progress.sectionsDone": `Sektiounen ofgeschloss`,
  "progress.suggestedNext": `Suggested next: {topic}`,
  "progress.title": `Fortschrëtt`,
  "progress.topicCompletion": `Thema Ofschloss`,
  "report.detailsPlaceholder": `Sot eis méi (optional)`,
  "report.incorrectAnswer": `Falsch Äntwert`,
  "report.outdatedInfo": `Vergaangen Informatiounen`,
  "report.submit": `Rapport ofginn`,
  "report.technicalIssue": `Technesch Fro`,
  "report.thanks": `Merci - Berichter ginn lokal op dësem Apparat gespäichert.`,
  "report.translationProblem": `Iwwersetzung Problem`,
  "report.unclearExplanation": `Explikatioun peu claire`,
  "settings.about": `Iwwer dës App`,
  "settings.appInterfaceLanguage": `App Interface Sprooch`,
  "settings.clearProgress": `Kloer Fortschrëtt`,
  "settings.clearProgressConfirm": `Sidd Dir sécher? Dëst wäert all Är Fortschrëtter läschen.`,
  "settings.interfaceDescription": `Menue, Knäppercher an Navigatioun.`,
  "settings.language": `Sprooch`,
  "settings.machineNote": `Maschinn iwwersat Inhalt gouf net vun engem mënschleche Rezensor gepréift. Näischt hei gëtt als iwwerpréift bezeechent ausser et ass tatsächlech iwwerpréift ginn.`,
  "settings.machineTranslatedBadge": `Maschinn iwwersat`,
  "settings.manageProgress": `Verwalten Är Fortschrëtterdaten`,
  "settings.notAvailable": `Nach net verfügbar`,
  "settings.officialGuideLink": `Offiziell Studieguide`,
  "settings.officialTestLink": `Offiziell Nationalitéit Test Informatiounen`,
  "settings.privacy": `Privatsphär`,
  "settings.privacyText": `Är Äntwerten, Lieszeechen an Astellunge ginn nëmmen op dësem Apparat gespäichert. Kee Kont ass néideg. Froen déi Dir de Studieassistent stellt ginn un en AI Service geschéckt fir Äntwerten ze generéieren.`,
  "settings.reviewedBadge": `Iwwerpréift`,
  "settings.studyContentLanguage": `Studéiert Inhalt Sprooch`,
  "settings.studyDescription": `Léieren Text an Erklärungen. Dir kënnt an enger Sprooch liesen wärend Dir an enger anerer navigéiert.`,
  "settings.textSize": `Textgréisst`,
  "settings.title": `Astellungen`,
  "topics.askAssistant": `Frot den Assistent iwwer dës Sektioun`,
  "topics.bookmarkSection": `Bookmark Rubrik`,
  "topics.bookmarkedSection": `Bookmarkéiert`,
  "topics.completed": `Ofgeschloss`,
  "topics.continueLearningCard": `Continue learning`,
  "topics.demoSourceNote": `Original Probe Fro - net eng offiziell Examen Fro`,
  "topics.lastVerified": `Lescht verifizéiert {date}`,
  "topics.markComplete": `Markéiert als komplett`,
  "topics.markIncomplete": `Markéiert als onkomplett`,
  "topics.minRead": `{n} min gelies`,
  "topics.next": `Nächst`,
  "topics.openOfficialPage": `Offiziell Säit opmaachen`,
  "topics.paraphrasedSourceNote": `Paraphrased aus offiziellen Material`,
  "topics.practiceTopic": `Praxis dëst Thema`,
  "topics.previous": `Virdrun`,
  "topics.reportIssue": `Rapport en Thema`,
  "topics.reviewedOn": `reviewed {date}`,
  "topics.reviewedTranslation": `Iwwerpréift Iwwersetzung`,
  "topics.section": `Sektioun`,
  "topics.sections": `Sektiounen`,
  "topics.source": `Quell`,
  "topics.sourcesDescription": `Etude Text hei ass paraphrased aus der Regierung vu Kanada Nationalitéit Studie Guide an iwwerpréift op den Datumen gewisen. Praxis Froen ginn aus dem offiziellen Etude Guide recherchéiert.`,
  "topics.sourcesHeading": `Inhalt Quellen an Iwwerpréiwung Datumen`,
  "topics.studyLanguageLabel": `Studéiert Inhalt Sprooch`,
  "topics.title": `Etude Sujeten`,
  "topics.vocabulary": `Vocabulaire`,
};
