// UI strings for 'lt' — chunk of strings.generated.ts. DO NOT EDIT BY HAND.
import type { StringKey } from "../strings.generated";

export const lt: Record<StringKey, string> = {
  "actions.askAi": `Paklauskite AI`,
  "actions.mockExam": `Bandomasis egzaminas`,
  "actions.practice": `Praktika`,
  "actions.quickActions": `Quick actions`,
  "actions.study": `Studijuoti`,
  "assistant.aiEyebrow": `AI studijų asistentas`,
  "assistant.answerLanguage": `Atsakymo kalba`,
  "assistant.charLimit": `Liko {n} simboliai`,
  "assistant.checkingMaterial": `Tikrinama studijų medžiaga…`,
  "assistant.clearChat": `Išvalyti pokalbį`,
  "assistant.copied": `Nukopijuota`,
  "assistant.copy": `Kopijuoti`,
  "assistant.description": `Atsakymus surašo AI, naudodamas tik šios programos studijų medžiagą, nurodant šaltinius. AI vis tiek gali klysti – patikrinkite svarbią informaciją oficialiuose Kanados vyriausybės puslapiuose. Ne teisiniai ar imigracijos patarimai.`,
  "assistant.enFrancais": `En français`,
  "assistant.error": `Kažkas nutiko. Bandykite dar kartą.`,
  "assistant.fromAppContent": `Iš patvirtinto programos turinio`,
  "assistant.groundedBadge": `Įžemintas šaltiniu`,
  "assistant.helpful": `Naudinga`,
  "assistant.inputPlaceholder": `Užduokite klausimą apie Kanados pilietybę…`,
  "assistant.myAppLanguage": `Mano programos kalba`,
  "assistant.notCovered": `Neapimta - žiūrėkite oficialų puslapį`,
  "assistant.notHelpful": `Nepadeda`,
  "assistant.openAssistant": `Atviras studijų asistentas`,
  "assistant.openLink": `Atidaryti asistentą`,
  "assistant.practiceThis": `Praktikuokite tai`,
  "assistant.questionAriaLabel": `Jūsų klausimas`,
  "assistant.reportIncorrect": `Pranešti apie neteisingą atsakymą`,
  "assistant.send": `Siųsti`,
  "assistant.showSource": `Rodyti šaltinį`,
  "assistant.simpleEnglish": `Paprasta anglų kalba`,
  "assistant.source": `Šaltinis`,
  "assistant.starter1": `Kokios yra trys Parlamento dalys?`,
  "assistant.starter2": `Paaiškinkite Chartiją paprastai`,
  "assistant.starter3": `Kas atstovauja karaliui Kanadoje?`,
  "assistant.starter4": `Ką apima žinių patikrinimas?`,
  "assistant.suggestedQuestions": `Siūlomi klausimai`,
  "assistant.thinking": `Galvoju…`,
  "assistant.title": `Studijų asistentas`,
  "assistant.tryAgain": `Bandykite dar kartą`,
  "assistant.tryAsking": `Pabandyk paklausti:`,
  "assistant.vocabularyLabel": `Žodynas:`,
  "assistant.whyItMatters": `Kodėl tai svarbu testui`,
  "auth.account": `Account`,
  "auth.checkEmail": `Check your email to confirm your account, then sign in.`,
  "auth.close": `Close`,
  "auth.codeLabel": `Verification code`,
  "auth.codeResent": `New code sent. Check your email.`,
  "auth.codeSent": `Code sent! Check your email and enter the 6-digit code.`,
  "auth.createAccount": `Create account`,
  "auth.dataDeletedMsg": `Your progress and profile data were deleted.`,
  "auth.deleteConfirm": `Tap again to permanently delete`,
  "auth.deleteData": `Delete my data`,
  "auth.email": `Email`,
  "auth.haveAccount": `Already have an account?`,
  "auth.mfaCodeLabel": `Authenticator code`,
  "auth.mfaDisable": `Disable 2FA`,
  "auth.mfaDisabledMsg": `Two-factor authentication is now OFF.`,
  "auth.mfaEnable": `Enable 2FA`,
  "auth.mfaEnabledMsg": `Two-factor authentication is now ON for your account.`,
  "auth.mfaPendingWarn": `2FA code still needed to finish signing in.`,
  "auth.mfaPrompt": `This account uses 2FA — enter the code from your authenticator app.`,
  "auth.mfaScanHint": `Scan this QR code with your authenticator app (Google Authenticator, Authy, 1Password…), then enter the 6-digit code it shows.`,
  "auth.mfaSetupTitle": `Set up two-factor authentication`,
  "auth.mfaSubtitle": `Enter the 6-digit code from your authenticator app.`,
  "auth.mfaTitle": `Two-factor authentication`,
  "auth.noAccount": `Don't have an account?`,
  "auth.password": `Password`,
  "auth.passwordHint": `At least 6 characters`,
  "auth.privacy": `Privacy`,
  "auth.privacyNote": `Your email and progress are private — only you can see them.`,
  "auth.resendCode": `Resend code`,
  "auth.security": `Security`,
  "auth.signIn": `Sign in`,
  "auth.signOut": `Sign out`,
  "auth.signUp": `Sign up`,
  "auth.subtitle": `Save your progress across devices. Your data stays private.`,
  "auth.title": `Account`,
  "auth.verify": `Verify`,
  "auth.verifyCodeSubtitle": `We sent a 6-digit code to your email. Enter it below to finish signing up.`,
  "auth.verifyCodeTitle": `Enter your code`,
  "auth.working": `Please wait…`,
  "bookmarks.continueStudying": `Toliau mokytis`,
  "bookmarks.empty": `Žymių dar nėra. Palieskite bet kurio klausimo žvaigždutę, kad išsaugotumėte jį peržiūrai.`,
  "bookmarks.emptyQuestions": `Dar nieko neišsaugota. Bakstelėkite ☆ ant praktinio klausimo.`,
  "bookmarks.emptySections": `Dar nieko neišsaugota. Skaitydami skyrių palieskite ☆.`,
  "bookmarks.remove": `Pašalinti`,
  "bookmarks.savedForReview": `išsaugotas peržiūrai`,
  "bookmarks.savedQuestions": `Išsaugoti klausimai ({n})`,
  "bookmarks.savedSections": `Išsaugotos skiltys ({n})`,
  "bookmarks.search": `Ieškoti žymių…`,
  "bookmarks.title": `Žymės`,
  "cards.answered": `Atsakyta`,
  "cards.bookmarks": `išsaugotas peržiūrai`,
  "cards.bookmarksLabel": `Žymės`,
  "cards.continueLearning": `Toliau mokytis`,
  "cards.correct": `Teisingai`,
  "cards.dailyGoal": `{done}/{total} klausimų šiandien`,
  "cards.dailyGoalLabel": `Dienos tikslas`,
  "cards.dailyGoalTitle": `Daily goal`,
  "cards.mockExam.subtitle": `Laiku · 20 klausimų`,
  "cards.mockExam.title": `Bandomasis egzaminas`,
  "cards.officialInfo.button": `Atidarykite canada.ca`,
  "cards.officialInfo.subtitle": `Norėdami gauti oficialios informacijos, apsilankykite canada.ca`,
  "cards.officialInfo.title": `Oficiali informacija`,
  "cards.progress": `Pažanga`,
  "cards.progressDetails": `Detalės`,
  "cards.recentlyStudied": `Neseniai studijavo`,
  "cards.sections": `Skyriai`,
  "cards.studyAssistant.subtitle": `Klauskite bet ko apie studijų medžiagą`,
  "cards.studyAssistant.title": `Studijų asistentas`,
  "cards.todaysRecommendation": `Šios dienos rekomendacija`,
  "cards.verifiedSource.subtext": `Turinys patikrintas pagal oficialius šaltinius. Nepriklausoma studijų pagalba – nesusijusi su Kanados vyriausybe ar IRCC arba jų nepatvirtinta.`,
  "cards.verifiedSource.title": `Patvirtintas šaltinis`,
  "common.back": `Atgal`,
  "common.cancel": `Atšaukti`,
  "common.close": `Uždaryti`,
  "common.continue": `Tęsti`,
  "common.done": `Atlikta`,
  "common.emptyBookmarks": `Dar nieko neišsaugota`,
  "common.emptyRecentlyStudied": `Dar nieko neištirta – norėdami pradėti, pasirinkite temą.`,
  "common.loading": `Įkeliama…`,
  "common.next": `Kitas`,
  "common.of": `iš`,
  "common.previous": `Ankstesnis`,
  "common.retry": `Bandykite dar kartą`,
  "common.save": `Išsaugoti`,
  "exam.allTopics": `Visos temos`,
  "exam.answeredCount": `{n} atsakė`,
  "exam.autosaveNote": `Jūsų atsakymai išsaugomi jums einant, todėl uždarę programą neprarasite pažangos.`,
  "exam.cancel": `Atšaukti`,
  "exam.confirm": `Patvirtinti`,
  "exam.confirmEnd": `{n} klausimai neatsakyti ir bus pažymėti kaip neteisingi.`,
  "exam.confirmEndTitle": `Baigti egzaminą?`,
  "exam.endExamEarly": `Baigti egzaminą anksčiau`,
  "exam.examDisclaimer": `Šis balas atspindi tik šios programos pavyzdinius klausimus.`,
  "exam.finishExam": `Baigti egzaminą`,
  "exam.newExam": `Naujas egzaminas`,
  "exam.noMistakes": `Jokių klaidų – puikus rezultatas!`,
  "exam.pastAttempts": `Praeities bandymai`,
  "exam.questionAriaLabel": `{n} klausimas`,
  "exam.questionCount": `Klausimų skaičius`,
  "exam.questionOf": `{n} klausimas iš {total}`,
  "exam.questionPalette": `Klausimai`,
  "exam.questionsOption": `{n} klausimų`,
  "exam.resultsTitle": `Jūsų rezultatas`,
  "exam.reviewMistakes": `Peržiūrėkite savo klaidas ({n})`,
  "exam.scoreLine": `{correct} iš {total} teisinga`,
  "exam.seeProgress": `Žiūrėti pažangą`,
  "exam.setupDescription": `Tai praktikos modeliavimas, sukurtas iš šios programos studijų klausimų. Tai nėra oficialus testas ir nenumato jūsų rezultato.`,
  "exam.setupTitle": `Nustatykite bandomąjį egzaminą`,
  "exam.simulationNote": `Praktinis modeliavimas · ne oficialus`,
  "exam.startExam": `Pradėti egzaminą`,
  "exam.timeLeft": `Liko laiko`,
  "exam.timedLabel": `su laiku`,
  "exam.timedToggle": `Laiku (90 sekundžių vienam klausimui)`,
  "exam.title": `Bandomasis egzaminas`,
  "exam.topicFilter": `Tema`,
  "exam.untimedLabel": `be laiko`,
  "footer.disclaimer": `„Citizen Prep“ yra nepriklausoma studijų priemonė. Nesusijęs su Kanados vyriausybe ar IRCC arba jų nepatvirtintas. Tai negali garantuoti praeinančio rezultato.`,
  "header.appName": `Piliečio paruošimas`,
  "header.tagline": `Nepriklausoma studijų priemonė · Neoficiali`,
  "hero.sectionsProgress": `{done} of {total} sections · {percent}% complete`,
  "hero.subtitle": `Nepriklausoma studijų priemonė · Anglų ir prancūzų kalba · Nereikia paskyros`,
  "hero.title": `Pasiruoškite pilietybės egzaminui`,
  "nav.exam": `Egzaminas`,
  "nav.home": `Pradžia`,
  "nav.practice": `Praktika`,
  "nav.progress": `Pažanga`,
  "nav.topics": `Temos`,
  "practice.allLevels": `Visi lygiai`,
  "practice.allTopics": `Visos temos`,
  "practice.askAiAbout": `Paklauskite AI šiuo klausimu`,
  "practice.bookmarkQuestion": `Pažymėti klausimą`,
  "practice.bookmarked": `Pažymėta`,
  "practice.checkAnswer": `Patikrinkite atsakymą`,
  "practice.correct": `Teisingai`,
  "practice.demoContent": `Demonstracinis turinys`,
  "practice.difficulty": `Sunkumas`,
  "practice.easy": `Lengva`,
  "practice.explanation": `Paaiškinimas`,
  "practice.filters": `Filtrai`,
  "practice.hard": `Sunku`,
  "practice.incorrect": `Ne visai`,
  "practice.medium": `Vidutinis`,
  "practice.nextQuestion": `Kitas klausimas`,
  "practice.questionCounter": `Praktinis klausimas {n} iš {total}`,
  "practice.reportIssue": `Pranešti apie problemą`,
  "practice.title": `Praktika`,
  "practice.topicFilter": `Tema`,
  "practice.tryAgain": `Bandykite dar kartą`,
  "progress.accuracy": `Tikslumas`,
  "progress.clearProgressDesc": `Taip iš šio įrenginio ištrinami atsakymai, užbaigimai, žymės ir egzaminų istorija. To negalima anuliuoti.`,
  "progress.clearProgressLabel": `Išvalykite visą studijų pažangą`,
  "progress.confirmClear": `Taip, išvalykite viską`,
  "progress.dailyGoal": `Dienos tikslas`,
  "progress.details": `Detalės`,
  "progress.examHistory": `Egzamino istorija`,
  "progress.noExams": `Dar nelaikytų egzaminų.`,
  "progress.noWrongAnswers": `Šiuo metu nėra neteisingų atsakymų, kuriuos reikia peržiūrėti.`,
  "progress.overview": `Apžvalga`,
  "progress.perTopic": `Pagal temą`,
  "progress.questionsAnswered": `Į klausimus atsakyta`,
  "progress.reset": `Nustatyti iš naujo`,
  "progress.retryTopic": `Pabandykite dar kartą šią temą`,
  "progress.sectionsDone": `Skyriai baigti`,
  "progress.suggestedNext": `Siūloma toliau: {topic}`,
  "progress.title": `Pažanga`,
  "progress.topicCompletion": `Temos užbaigimas`,
  "report.detailsPlaceholder": `Papasakokite daugiau (neprivaloma)`,
  "report.incorrectAnswer": `Neteisingas atsakymas`,
  "report.outdatedInfo": `Pasenusi informacija`,
  "report.submit": `Pateikti ataskaitą`,
  "report.technicalIssue": `Techninė problema`,
  "report.thanks": `Ačiū – ataskaitos saugomos lokaliai šiame įrenginyje.`,
  "report.translationProblem": `Vertimo problema`,
  "report.unclearExplanation": `Paaiškinimas peu claire`,
  "settings.about": `Apie šią programėlę`,
  "settings.appInterfaceLanguage": `Programos sąsajos kalba`,
  "settings.clearProgress": `Aiškus progresas`,
  "settings.clearProgressConfirm": `Ar esi tikras? Tai ištrins visą jūsų pažangą.`,
  "settings.interfaceDescription": `Meniu, mygtukai ir navigacija.`,
  "settings.language": `Kalba`,
  "settings.machineNote": `Mašininiu būdu išversto turinio nepatikrino žmogus. Niekas čia nėra pažymėtas kaip peržiūrėtas, nebent jis iš tikrųjų buvo peržiūrėtas.`,
  "settings.machineTranslatedBadge": `Išversta mašininiu būdu`,
  "settings.manageProgress": `Tvarkykite eigos duomenis`,
  "settings.notAvailable": `Dar nepasiekiama`,
  "settings.officialGuideLink": `Oficialus studijų vadovas`,
  "settings.officialTestLink": `Oficiali informacija apie pilietybės testą`,
  "settings.privacy": `Privatumas`,
  "settings.privacyText": `Jūsų atsakymai, žymės ir nustatymai saugomi tik šiame įrenginyje. Paskyros nereikia. Klausimai, kuriuos užduodate studijų asistentui, siunčiami dirbtinio intelekto tarnybai, kad būtų galima gauti atsakymus.`,
  "settings.reviewedBadge": `Peržiūrėta`,
  "settings.studyContentLanguage": `Studijų turinio kalba`,
  "settings.studyDescription": `Mokymasis teksto ir paaiškinimų. Galite skaityti viena kalba, o naršyti kita.`,
  "settings.textSize": `Teksto dydis`,
  "settings.title": `Nustatymai`,
  "topics.askAssistant": `Paklauskite asistento apie šį skyrių`,
  "topics.bookmarkSection": `Žymių skyrius`,
  "topics.bookmarkedSection": `Pažymėta`,
  "topics.completed": `Baigta`,
  "topics.continueLearningCard": `Toliau mokytis`,
  "topics.demoSourceNote": `Originalus klausimo pavyzdys – ne oficialus egzamino klausimas`,
  "topics.lastVerified": `Paskutinį kartą patvirtinta {date}`,
  "topics.markComplete": `Pažymėti kaip užbaigtą`,
  "topics.markIncomplete": `Pažymėti kaip nebaigtą`,
  "topics.minRead": `Skaityti {n} min`,
  "topics.next": `Kitas`,
  "topics.openOfficialPage": `Atidarykite oficialų puslapį`,
  "topics.paraphrasedSourceNote": `Perfrazuota iš oficialios medžiagos`,
  "topics.practiceTopic": `Praktikuokite šią temą`,
  "topics.previous": `Ankstesnis`,
  "topics.reportIssue": `Pranešti apie problemą`,
  "topics.reviewedOn": `reviewed {date}`,
  "topics.reviewedTranslation": `Peržiūrėtas vertimas`,
  "topics.section": `Skyrius`,
  "topics.sections": `skyriuose`,
  "topics.source": `Šaltinis`,
  "topics.sourcesDescription": `Čia pateiktas tyrimo tekstas yra perfrazuotas iš Kanados vyriausybės pilietybės studijų vadovo ir peržiūrimas nurodytomis datomis. Praktiniai klausimai tiriami iš oficialaus studijų vadovo.`,
  "topics.sourcesHeading": `Turinio šaltiniai ir peržiūrų datos`,
  "topics.studyLanguageLabel": `Studijų turinio kalba`,
  "topics.title": `Studijų temos`,
  "topics.vocabulary": `Žodynas`,
};
