// UI strings for 'lv' — chunk of strings.generated.ts. DO NOT EDIT BY HAND.
import type { StringKey } from "../strings.generated";

export const lv: Record<StringKey, string> = {
  "actions.askAi": `Jautājiet AI`,
  "actions.mockExam": `Izmēģinājuma eksāmens`,
  "actions.practice": `Prakse`,
  "actions.quickActions": `Quick actions`,
  "actions.study": `Pētījums`,
  "assistant.aiEyebrow": `AI studiju asistents`,
  "assistant.answerLanguage": `Atbilžu valoda`,
  "assistant.charLimit": `Atlikušas {n} rakstzīmes`,
  "assistant.checkingMaterial": `Mācību materiāla pārbaude…`,
  "assistant.clearChat": `Notīrīt tērzēšanu`,
  "assistant.copied": `Kopēts`,
  "assistant.copy": `Kopēt`,
  "assistant.description": `Atbildes raksta mākslīgais intelekts, izmantojot tikai šīs lietotnes mācību materiālu, norādot avotus. AI joprojām var kļūdīties — pārbaudiet svarīgu informāciju oficiālajās Kanādas valdības lapās. Nav juridiskas vai imigrācijas konsultācijas.`,
  "assistant.enFrancais": `En français`,
  "assistant.error": `Kaut kas nogāja greizi. Lūdzu, mēģiniet vēlreiz.`,
  "assistant.fromAppContent": `No apstiprināta lietotnes satura`,
  "assistant.groundedBadge": `Iezemēts ar avotu`,
  "assistant.helpful": `Noderīgs`,
  "assistant.inputPlaceholder": `Uzdodiet jautājumu par Kanādas pilsonību…`,
  "assistant.myAppLanguage": `Manas lietotnes valoda`,
  "assistant.notCovered": `Nav ietverts — skatiet oficiālo lapu`,
  "assistant.notHelpful": `Nav noderīgi`,
  "assistant.openAssistant": `Atvērtais studiju asistents`,
  "assistant.openLink": `Atvērt palīgu`,
  "assistant.practiceThis": `Praktizējiet šo`,
  "assistant.questionAriaLabel": `Jūsu jautājums`,
  "assistant.reportIncorrect": `Ziņojiet par nepareizu atbildi`,
  "assistant.send": `Sūtīt`,
  "assistant.showSource": `Rādīt avotu`,
  "assistant.simpleEnglish": `Vienkārša angļu valoda`,
  "assistant.source": `Avots`,
  "assistant.starter1": `Kādas ir trīs parlamenta daļas?`,
  "assistant.starter2": `Vienkārši izskaidrojiet hartu`,
  "assistant.starter3": `Kas pārstāv karali Kanādā?`,
  "assistant.starter4": `Ko aptver zināšanu pārbaude?`,
  "assistant.suggestedQuestions": `Ieteiktie jautājumi`,
  "assistant.thinking": `Domājot…`,
  "assistant.title": `Mācību palīgs`,
  "assistant.tryAgain": `Mēģiniet vēlreiz`,
  "assistant.tryAsking": `Mēģiniet jautāt:`,
  "assistant.vocabularyLabel": `Vārdu krājums:`,
  "assistant.whyItMatters": `Kāpēc tas ir svarīgi pārbaudei`,
  "auth.account": `Account`,
  "auth.checkEmail": `Check your email to confirm your account, then sign in.`,
  "auth.close": `Close`,
  "auth.codeLabel": `Verification code`,
  "auth.codeResent": `New code sent. Check your email.`,
  "auth.codeSent": `Code sent! Check your email and enter the 6-digit code.`,
  "auth.createAccount": `Create account`,
  "auth.dataDeletedMsg": `Your progress and profile data were deleted.`,
  "auth.deleteConfirm": `Tap again to permanently delete`,
  "auth.deleteData": `Delete my data`,
  "auth.email": `Email`,
  "auth.haveAccount": `Already have an account?`,
  "auth.mfaCodeLabel": `Authenticator code`,
  "auth.mfaDisable": `Disable 2FA`,
  "auth.mfaDisabledMsg": `Two-factor authentication is now OFF.`,
  "auth.mfaEnable": `Enable 2FA`,
  "auth.mfaEnabledMsg": `Two-factor authentication is now ON for your account.`,
  "auth.mfaPendingWarn": `2FA code still needed to finish signing in.`,
  "auth.mfaPrompt": `This account uses 2FA — enter the code from your authenticator app.`,
  "auth.mfaScanHint": `Scan this QR code with your authenticator app (Google Authenticator, Authy, 1Password…), then enter the 6-digit code it shows.`,
  "auth.mfaSetupTitle": `Set up two-factor authentication`,
  "auth.mfaSubtitle": `Enter the 6-digit code from your authenticator app.`,
  "auth.mfaTitle": `Two-factor authentication`,
  "auth.noAccount": `Don't have an account?`,
  "auth.password": `Password`,
  "auth.passwordHint": `At least 6 characters`,
  "auth.privacy": `Privacy`,
  "auth.privacyNote": `Your email and progress are private — only you can see them.`,
  "auth.resendCode": `Resend code`,
  "auth.security": `Security`,
  "auth.signIn": `Sign in`,
  "auth.signOut": `Sign out`,
  "auth.signUp": `Sign up`,
  "auth.subtitle": `Save your progress across devices. Your data stays private.`,
  "auth.title": `Account`,
  "auth.verify": `Verify`,
  "auth.verifyCodeSubtitle": `We sent a 6-digit code to your email. Enter it below to finish signing up.`,
  "auth.verifyCodeTitle": `Enter your code`,
  "auth.working": `Please wait…`,
  "bookmarks.continueStudying": `Turpiniet mācīties`,
  "bookmarks.empty": `Vēl nav nevienas grāmatzīmes. Pieskarieties zvaigznītei uz jebkura jautājuma, lai saglabātu to pārskatīšanai.`,
  "bookmarks.emptyQuestions": `Vēl nekas nav saglabāts. Pieskarieties ☆ praktiskajam jautājumam.`,
  "bookmarks.emptySections": `Vēl nekas nav saglabāts. Lasot sadaļu, pieskarieties ☆.`,
  "bookmarks.remove": `Noņemt`,
  "bookmarks.savedForReview": `saglabāts pārskatīšanai`,
  "bookmarks.savedQuestions": `Saglabātie jautājumi ({n})`,
  "bookmarks.savedSections": `Saglabātās sadaļas ({n})`,
  "bookmarks.search": `Meklēt grāmatzīmes…`,
  "bookmarks.title": `Grāmatzīmes`,
  "cards.answered": `Atbildēja`,
  "cards.bookmarks": `saglabāts pārskatīšanai`,
  "cards.bookmarksLabel": `Grāmatzīmes`,
  "cards.continueLearning": `Turpiniet mācīties`,
  "cards.correct": `Pareizi`,
  "cards.dailyGoal": `{done}/{total} jautājumi šodien`,
  "cards.dailyGoalLabel": `Dienas mērķis`,
  "cards.dailyGoalTitle": `Daily goal`,
  "cards.mockExam.subtitle": `Laiks · 20 jautājumi`,
  "cards.mockExam.title": `Izmēģinājuma eksāmens`,
  "cards.officialInfo.button": `Atveriet canada.ca`,
  "cards.officialInfo.subtitle": `Apmeklējiet vietni canada.ca, lai iegūtu oficiālu informāciju`,
  "cards.officialInfo.title": `Oficiālā informācija`,
  "cards.progress": `Progress`,
  "cards.progressDetails": `Sīkāka informācija`,
  "cards.recentlyStudied": `Nesen pētīta`,
  "cards.sections": `Sadaļas`,
  "cards.studyAssistant.subtitle": `Jautājiet jebko par mācību materiālu`,
  "cards.studyAssistant.title": `Mācību palīgs`,
  "cards.todaysRecommendation": `Šodienas ieteikums`,
  "cards.verifiedSource.subtext": `Saturs ir pārbaudīts salīdzinājumā ar oficiālajiem avotiem. Neatkarīgs mācību atbalsts — nav saistīts ar Kanādas valdību vai IRCC vai to nav apstiprinājis.`,
  "cards.verifiedSource.title": `Pārbaudīts avots`,
  "common.back": `Atpakaļ`,
  "common.cancel": `Atcelt`,
  "common.close": `Aizvērt`,
  "common.continue": `Turpināt`,
  "common.done": `Gatavs`,
  "common.emptyBookmarks": `Vēl nekas nav saglabāts`,
  "common.emptyRecentlyStudied": `Vēl nekas nav pētīts — lai sāktu, izvēlieties tēmu.`,
  "common.loading": `Notiek ielāde…`,
  "common.next": `Tālāk`,
  "common.of": `no`,
  "common.previous": `Iepriekšējais`,
  "common.retry": `Mēģiniet vēlreiz`,
  "common.save": `Saglabāt`,
  "exam.allTopics": `Visas tēmas`,
  "exam.answeredCount": `{n} atbildēja`,
  "exam.autosaveNote": `Jūsu atbildes tiek saglabātas, kad dodaties, tāpēc, aizverot lietotni, progress netiks zaudēts.`,
  "exam.cancel": `Atcelt`,
  "exam.confirm": `Apstiprināt`,
  "exam.confirmEnd": `{n} jautājumi ir neatbildēti un tiks atzīmēti kā nepareizi.`,
  "exam.confirmEndTitle": `Beigt eksāmenu?`,
  "exam.endExamEarly": `Pabeidziet eksāmenu agri`,
  "exam.examDisclaimer": `Šis rezultāts atspoguļo tikai šīs lietotnes jautājumu paraugus.`,
  "exam.finishExam": `Pabeigt eksāmenu`,
  "exam.newExam": `Jauns eksāmens`,
  "exam.noMistakes": `Nav kļūdu - ideāls rezultāts!`,
  "exam.pastAttempts": `Iepriekšējie mēģinājumi`,
  "exam.questionAriaLabel": `jautājums {n}`,
  "exam.questionCount": `Jautājumu skaits`,
  "exam.questionOf": `{n}. jautājums no {total}`,
  "exam.questionPalette": `Jautājumi`,
  "exam.questionsOption": `{n} jautājumi`,
  "exam.resultsTitle": `Jūsu rezultāts`,
  "exam.reviewMistakes": `Pārskatiet savas kļūdas ({n})`,
  "exam.scoreLine": `Pareizi {correct} no {total}`,
  "exam.seeProgress": `Skatīt progresu`,
  "exam.setupDescription": `Šī ir prakses simulācija, kas veidota no šīs lietotnes pētījuma jautājumiem. Tas nav oficiālais tests un neparedz jūsu rezultātu.`,
  "exam.setupTitle": `Iestatiet izmēģinājuma eksāmenu`,
  "exam.simulationNote": `Prakses simulācija · nav oficiāla`,
  "exam.startExam": `Sāciet eksāmenu`,
  "exam.timeLeft": `Palicis laiks`,
  "exam.timedLabel": `laika ziņā`,
  "exam.timedToggle": `Laiks (90 sekundes vienam jautājumam)`,
  "exam.title": `Izmēģinājuma eksāmens`,
  "exam.topicFilter": `Tēma`,
  "exam.untimedLabel": `bez laika`,
  "footer.disclaimer": `Citizen Prep ir neatkarīgs mācību līdzeklis. Nav saistīts ar Kanādas valdību vai IRCC vai to nav apstiprinājis. Tas nevar garantēt garāmejošu rezultātu.`,
  "header.appName": `Pilsoņu sagatavošana`,
  "header.tagline": `Neatkarīgs mācību līdzeklis · Nav oficiāls`,
  "hero.sectionsProgress": `{done} of {total} sections · {percent}% complete`,
  "hero.subtitle": `Neatkarīgs mācību līdzeklis · angļu un franču valoda · nav nepieciešams konts`,
  "hero.title": `Sagatavojieties pilsonības pārbaudei`,
  "nav.exam": `Eksāmens`,
  "nav.home": `Sākums`,
  "nav.practice": `Prakse`,
  "nav.progress": `Progress`,
  "nav.topics": `Tēmas`,
  "practice.allLevels": `Visi līmeņi`,
  "practice.allTopics": `Visas tēmas`,
  "practice.askAiAbout": `Jautājiet AI par šo jautājumu`,
  "practice.bookmarkQuestion": `Grāmatzīmes jautājums`,
  "practice.bookmarked": `Atzīmēts ar grāmatzīmi`,
  "practice.checkAnswer": `Pārbaudiet atbildi`,
  "practice.correct": `Pareizi`,
  "practice.demoContent": `Demo saturs`,
  "practice.difficulty": `Grūtības`,
  "practice.easy": `Viegli`,
  "practice.explanation": `Paskaidrojums`,
  "practice.filters": `Filtri`,
  "practice.hard": `Grūti`,
  "practice.incorrect": `Ne gluži`,
  "practice.medium": `Vidēja`,
  "practice.nextQuestion": `Nākamais jautājums`,
  "practice.questionCounter": `Prakses jautājums {n} no {total}`,
  "practice.reportIssue": `Ziņot par problēmu`,
  "practice.title": `Prakse`,
  "practice.topicFilter": `Tēma`,
  "practice.tryAgain": `Mēģiniet vēlreiz`,
  "progress.accuracy": `Precizitāte`,
  "progress.clearProgressDesc": `Tādējādi no šīs ierīces tiks dzēstas jūsu atbildes, pabeigtie rezultāti, grāmatzīmes un eksāmenu vēsture. To nevar atsaukt.`,
  "progress.clearProgressLabel": `Notīrīt visu studiju progresu`,
  "progress.confirmClear": `Jā, notīriet visu`,
  "progress.dailyGoal": `Dienas mērķis`,
  "progress.details": `Sīkāka informācija`,
  "progress.examHistory": `Eksāmenu vēsture`,
  "progress.noExams": `Vēl nav nokārtots eksāmens.`,
  "progress.noWrongAnswers": `Pašlaik nav jāpārskata nepareizas atbildes.`,
  "progress.overview": `Pārskats`,
  "progress.perTopic": `Pa tēmu`,
  "progress.questionsAnswered": `Atbildēti jautājumi`,
  "progress.reset": `Atiestatīt`,
  "progress.retryTopic": `Mēģiniet vēlreiz šo tēmu`,
  "progress.sectionsDone": `Sadaļas pabeigtas`,
  "progress.suggestedNext": `Ieteikts nākamais: {topic}`,
  "progress.title": `Progress`,
  "progress.topicCompletion": `Tēmas pabeigšana`,
  "report.detailsPlaceholder": `Pastāstiet mums vairāk (neobligāti)`,
  "report.incorrectAnswer": `Nepareiza atbilde`,
  "report.outdatedInfo": `Novecojusi informācija`,
  "report.submit": `Iesniedziet atskaiti`,
  "report.technicalIssue": `Tehniska problēma`,
  "report.thanks": `Paldies — pārskati tiek glabāti lokāli šajā ierīcē.`,
  "report.translationProblem": `Tulkošanas problēma`,
  "report.unclearExplanation": `Paskaidrojums peu Klēra`,
  "settings.about": `Par šo lietotni`,
  "settings.appInterfaceLanguage": `Lietotnes saskarnes valoda`,
  "settings.clearProgress": `Skaidrs progress`,
  "settings.clearProgressConfirm": `Vai esat pārliecināts? Tas izdzēsīs visu jūsu progresu.`,
  "settings.interfaceDescription": `Izvēlnes, pogas un navigācija.`,
  "settings.language": `Valoda`,
  "settings.machineNote": `Mašīntulkoto saturu nav pārbaudījis cilvēks, kurš pārskatīja. Nekas šeit nav atzīmēts kā pārskatīts, ja vien tas faktiski nav pārskatīts.`,
  "settings.machineTranslatedBadge": `Mašīntulkots`,
  "settings.manageProgress": `Pārvaldiet savus progresa datus`,
  "settings.notAvailable": `Vēl nav pieejams`,
  "settings.officialGuideLink": `Oficiālais mācību ceļvedis`,
  "settings.officialTestLink": `Oficiālā informācija par pilsonības pārbaudi`,
  "settings.privacy": `Privātums`,
  "settings.privacyText": `Jūsu atbildes, grāmatzīmes un iestatījumi tiek saglabāti tikai šajā ierīcē. Konts nav vajadzīgs. Jautājumi, ko uzdodat pētījuma asistentam, tiek nosūtīti AI pakalpojumam, lai ģenerētu atbildes.`,
  "settings.reviewedBadge": `Pārskatīts`,
  "settings.studyContentLanguage": `Studiju satura valoda`,
  "settings.studyDescription": `Teksta un skaidrojumu apguve. Varat lasīt vienā valodā, vienlaikus navigējot citā.`,
  "settings.textSize": `Teksta lielums`,
  "settings.title": `Iestatījumi`,
  "topics.askAssistant": `Jautājiet asistentam par šo sadaļu`,
  "topics.bookmarkSection": `Grāmatzīmju sadaļa`,
  "topics.bookmarkedSection": `Atzīmēts ar grāmatzīmi`,
  "topics.completed": `Pabeigts`,
  "topics.continueLearningCard": `Turpiniet mācīties`,
  "topics.demoSourceNote": `Sākotnējais paraugjautājums — nevis oficiāls eksāmena jautājums`,
  "topics.lastVerified": `Pēdējā verifikācija: {date}`,
  "topics.markComplete": `Atzīmēt kā pabeigtu`,
  "topics.markIncomplete": `Atzīmēt kā nepabeigtu`,
  "topics.minRead": `{n} min lasīšanas`,
  "topics.next": `Tālāk`,
  "topics.openOfficialPage": `Atveriet oficiālo lapu`,
  "topics.paraphrasedSourceNote": `Pārfrāzēts no oficiālā materiāla`,
  "topics.practiceTopic": `Praktizējiet šo tēmu`,
  "topics.previous": `Iepriekšējais`,
  "topics.reportIssue": `Ziņot par problēmu`,
  "topics.reviewedOn": `pārskatīts {date}`,
  "topics.reviewedTranslation": `Recenzēts tulkojums`,
  "topics.section": `sadaļa`,
  "topics.sections": `sadaļas`,
  "topics.source": `Avots`,
  "topics.sourcesDescription": `Pētījuma teksts šeit ir pārfrāzēts no Kanādas valdības pilsonības mācību rokasgrāmatas un ir pārskatīts norādītajos datumos. Prakses jautājumi tiek pētīti oficiālajā mācību rokasgrāmatā.`,
  "topics.sourcesHeading": `Satura avoti un pārskatīšanas datumi`,
  "topics.studyLanguageLabel": `Studiju satura valoda`,
  "topics.title": `Studiju tēmas`,
  "topics.vocabulary": `Vārdu krājums`,
};
