// UI strings for 'mk' — chunk of strings.generated.ts. DO NOT EDIT BY HAND.
import type { StringKey } from "../strings.generated";

export const mk: Record<StringKey, string> = {
  "actions.askAi": `Прашајте вештачка интелигенција`,
  "actions.mockExam": `Лажен испит`,
  "actions.practice": `Вежбајте`,
  "actions.quickActions": `Quick actions`,
  "actions.study": `Студија`,
  "assistant.aiEyebrow": `AI study assistant`,
  "assistant.answerLanguage": `Јазик на одговори`,
  "assistant.charLimit": `Преостанати {n} знаци`,
  "assistant.checkingMaterial": `Checking the study material…`,
  "assistant.clearChat": `Clear chat`,
  "assistant.copied": `Копирано`,
  "assistant.copy": `Копирај`,
  "assistant.description": `Answers are written by AI using only this app's study material, with sources shown. AI can still make mistakes — check important details on the official Government of Canada pages. Not legal or immigration advice.`,
  "assistant.enFrancais": `Француски`,
  "assistant.error": `Нешто тргна наопаку. Ве молиме обидете се повторно.`,
  "assistant.fromAppContent": `Од одобрената содржина на апликацијата`,
  "assistant.groundedBadge": `Source-grounded`,
  "assistant.helpful": `Корисно`,
  "assistant.inputPlaceholder": `Поставете прашање за канадско државјанство…`,
  "assistant.myAppLanguage": `My app language`,
  "assistant.notCovered": `Not covered — see official page`,
  "assistant.notHelpful": `Не е од помош`,
  "assistant.openAssistant": `Open study assistant`,
  "assistant.openLink": `Open assistant`,
  "assistant.practiceThis": `Практикувајте го ова`,
  "assistant.questionAriaLabel": `Your question`,
  "assistant.reportIncorrect": `Report an incorrect answer`,
  "assistant.send": `Send`,
  "assistant.showSource": `Show source`,
  "assistant.simpleEnglish": `Едноставен англиски јазик`,
  "assistant.source": `Извор`,
  "assistant.starter1": `What are the three parts of Parliament?`,
  "assistant.starter2": `Explain the Charter simply`,
  "assistant.starter3": `Who represents the King in Canada?`,
  "assistant.starter4": `What does the knowledge test cover?`,
  "assistant.suggestedQuestions": `Предлог прашања`,
  "assistant.thinking": `Размислувајќи…`,
  "assistant.title": `Студиски асистент`,
  "assistant.tryAgain": `Try again`,
  "assistant.tryAsking": `Try asking:`,
  "assistant.vocabularyLabel": `Vocabulary:`,
  "assistant.whyItMatters": `Зошто е важно за тестот`,
  "bookmarks.continueStudying": `Continue studying`,
  "bookmarks.empty": `Сè уште нема обележувачи. Допрете ја ѕвездата на кое било прашање за да го зачувате за преглед.`,
  "bookmarks.emptyQuestions": `Nothing saved yet. Tap ☆ on a practice question.`,
  "bookmarks.emptySections": `Nothing saved yet. Tap ☆ while reading a section.`,
  "bookmarks.remove": `Отстрани`,
  "bookmarks.savedForReview": `зачувана за преглед`,
  "bookmarks.savedQuestions": `Saved questions ({n})`,
  "bookmarks.savedSections": `Saved sections ({n})`,
  "bookmarks.search": `Search bookmarks…`,
  "bookmarks.title": `Обележувачи`,
  "cards.answered": `Одговорено`,
  "cards.bookmarks": `зачувана за преглед`,
  "cards.bookmarksLabel": `Обележувачи`,
  "cards.continueLearning": `Продолжете да учите`,
  "cards.correct": `Точно`,
  "cards.dailyGoal": `{done}/{total} прашања денес`,
  "cards.dailyGoalLabel": `Дневен гол`,
  "cards.dailyGoalTitle": `Daily goal`,
  "cards.mockExam.subtitle": `Темпирано · 20 прашања`,
  "cards.mockExam.title": `Лажен испит`,
  "cards.officialInfo.button": `Отворете ја Канада.ca`,
  "cards.officialInfo.subtitle": `Посетете ја canada.ca за официјални детали`,
  "cards.officialInfo.title": `Официјални информации`,
  "cards.progress": `Напредок`,
  "cards.progressDetails": `Детали`,
  "cards.recentlyStudied": `Неодамна изучуван`,
  "cards.sections": `Секции`,
  "cards.studyAssistant.subtitle": `Прашајте нешто за студискиот материјал`,
  "cards.studyAssistant.title": `Студиски асистент`,
  "cards.todaysRecommendation": `Денешна препорака`,
  "cards.verifiedSource.subtext": `Содржината е проверена од официјални извори. Независна помош за студирање - не е поврзана или одобрена од Владата на Канада или IRCC.`,
  "cards.verifiedSource.title": `Потврден извор`,
  "common.back": `Назад`,
  "common.cancel": `Откажи`,
  "common.close": `Затвори`,
  "common.continue": `Продолжи`,
  "common.done": `Готово`,
  "common.emptyBookmarks": `Сè уште ништо не е зачувано`,
  "common.emptyRecentlyStudied": `Сè уште ништо не е проучено - изберете тема за почеток.`,
  "common.loading": `Се вчитува…`,
  "common.next": `Следно`,
  "common.of": `на`,
  "common.previous": `Претходна`,
  "common.retry": `Обидете се повторно`,
  "common.save": `Зачувај`,
  "exam.allTopics": `Сите теми`,
  "exam.answeredCount": `{n} answered`,
  "exam.autosaveNote": `Your answers are saved as you go, so closing the app won't lose your progress.`,
  "exam.cancel": `Откажи`,
  "exam.confirm": `Потврди`,
  "exam.confirmEnd": `{n} прашања се неодговорени и ќе бидат означени како неточни.`,
  "exam.confirmEndTitle": `Заврши испитот?`,
  "exam.endExamEarly": `Заврши го испитот рано`,
  "exam.examDisclaimer": `Овој резултат ги одразува само примероците од прашањата на оваа апликација.`,
  "exam.finishExam": `Finish exam`,
  "exam.newExam": `Нов испит`,
  "exam.noMistakes": `Без грешки - совршен резултат!`,
  "exam.pastAttempts": `Past attempts`,
  "exam.questionAriaLabel": `Question {n}`,
  "exam.questionCount": `Број на прашања`,
  "exam.questionOf": `Question {n} of {total}`,
  "exam.questionPalette": `Прашања`,
  "exam.questionsOption": `{n} questions`,
  "exam.resultsTitle": `Вашиот резултат`,
  "exam.reviewMistakes": `Прегледајте ги вашите грешки ({n})`,
  "exam.scoreLine": `{correct} of {total} correct`,
  "exam.seeProgress": `See progress`,
  "exam.setupDescription": `This is a practice simulation built from this app's study questions. It is not the official test and does not predict your result.`,
  "exam.setupTitle": `Поставете го вашиот лажен испит`,
  "exam.simulationNote": `Practice simulation · not official`,
  "exam.startExam": `Започнете го испитот`,
  "exam.timeLeft": `Преостанато време`,
  "exam.timedLabel": `темпиран`,
  "exam.timedToggle": `Временски (90 секунди по прашање)`,
  "exam.title": `Лажен испит`,
  "exam.topicFilter": `Тема`,
  "exam.untimedLabel": `невреме`,
  "footer.disclaimer": `Citizen Prep е независно помагало за учење. Не е поврзано или одобрено од Владата на Канада или IRCC. Не може да гарантира минлив резултат.`,
  "header.appName": `Граѓанин Прет`,
  "header.tagline": `Независна алатка за проучување · Не е официјално`,
  "hero.sectionsProgress": `{done} of {total} sections · {percent}% complete`,
  "hero.subtitle": `Независна алатка за студирање · англиски и француски · не е потребна сметка`,
  "hero.title": `Подгответе се за вашиот тест за државјанство`,
  "nav.exam": `Испит`,
  "nav.home": `Дома`,
  "nav.practice": `Вежбајте`,
  "nav.progress": `Напредок`,
  "nav.topics": `Теми`,
  "practice.allLevels": `All levels`,
  "practice.allTopics": `Сите теми`,
  "practice.askAiAbout": `Прашајте ја вештачката интелигенција за ова прашање`,
  "practice.bookmarkQuestion": `Прашање за обележување`,
  "practice.bookmarked": `Обележан`,
  "practice.checkAnswer": `Проверете го одговорот`,
  "practice.correct": `Точно`,
  "practice.demoContent": `Демо содржина`,
  "practice.difficulty": `Тешкотија`,
  "practice.easy": `Лесно`,
  "practice.explanation": `Објаснување`,
  "practice.filters": `Filters`,
  "practice.hard": `Тешко`,
  "practice.incorrect": `Не баш`,
  "practice.medium": `Средно`,
  "practice.nextQuestion": `Следно прашање`,
  "practice.questionCounter": `Practice question {n} of {total}`,
  "practice.reportIssue": `Пријавете проблем`,
  "practice.title": `Practice`,
  "practice.topicFilter": `Тема`,
  "practice.tryAgain": `Обидете се повторно`,
  "progress.accuracy": `Точност`,
  "progress.clearProgressDesc": `This deletes your answers, completions, bookmarks and exam history from this device. It cannot be undone.`,
  "progress.clearProgressLabel": `Clear all study progress`,
  "progress.confirmClear": `Yes, clear everything`,
  "progress.dailyGoal": `Дневен гол`,
  "progress.details": `Детали`,
  "progress.examHistory": `Историја на испити`,
  "progress.noExams": `Сè уште нема положени испити.`,
  "progress.noWrongAnswers": `No incorrect answers to review right now.`,
  "progress.overview": `Overview`,
  "progress.perTopic": `По тема`,
  "progress.questionsAnswered": `Одговорени прашања`,
  "progress.reset": `Reset`,
  "progress.retryTopic": `Обидете се повторно на оваа тема`,
  "progress.sectionsDone": `Секциите се завршени`,
  "progress.suggestedNext": `Suggested next: {topic}`,
  "progress.title": `Напредок`,
  "progress.topicCompletion": `Topic completion`,
  "report.detailsPlaceholder": `Tell us more (optional)`,
  "report.incorrectAnswer": `Incorrect answer`,
  "report.outdatedInfo": `Outdated information`,
  "report.submit": `Submit report`,
  "report.technicalIssue": `Technical issue`,
  "report.thanks": `Thanks — reports are stored locally on this device.`,
  "report.translationProblem": `Translation problem`,
  "report.unclearExplanation": `Explication peu claire`,
  "settings.about": `About this app`,
  "settings.appInterfaceLanguage": `Јазик на интерфејсот на апликацијата`,
  "settings.clearProgress": `Јасен напредок`,
  "settings.clearProgressConfirm": `Дали си сигурен? Ова ќе го избрише целиот ваш напредок.`,
  "settings.interfaceDescription": `Menus, buttons and navigation.`,
  "settings.language": `Јазик`,
  "settings.machineNote": `Machine-translated content has not been checked by a human reviewer. Nothing here is labelled as reviewed unless it has actually been reviewed.`,
  "settings.machineTranslatedBadge": `Машински преведено`,
  "settings.manageProgress": `Manage your progress data`,
  "settings.notAvailable": `Сè уште не е достапно`,
  "settings.officialGuideLink": `Official study guide`,
  "settings.officialTestLink": `Official citizenship test information`,
  "settings.privacy": `Privacy`,
  "settings.privacyText": `Your answers, bookmarks and settings are stored only on this device. No account is needed. Questions you ask the study assistant are sent to an AI service to generate answers.`,
  "settings.reviewedBadge": `Прегледано`,
  "settings.studyContentLanguage": `Проучете го јазикот на содржината`,
  "settings.studyDescription": `Learning text and explanations. You can read in one language while navigating in another.`,
  "settings.textSize": `Големина на текстот`,
  "settings.title": `Поставки`,
  "topics.askAssistant": `Прашајте го асистентот за овој дел`,
  "topics.bookmarkSection": `Bookmark section`,
  "topics.bookmarkedSection": `Bookmarked`,
  "topics.completed": `Завршено`,
  "topics.continueLearningCard": `Продолжете да учите`,
  "topics.demoSourceNote": `Original sample question — not an official exam question`,
  "topics.lastVerified": `Последно потврдено {date}`,
  "topics.markComplete": `Означи како комплетно`,
  "topics.markIncomplete": `Означи како нецелосно`,
  "topics.minRead": `{n} минути читање`,
  "topics.next": `Следно`,
  "topics.openOfficialPage": `Отворете ја официјалната страница`,
  "topics.paraphrasedSourceNote": `Paraphrased from official material`,
  "topics.practiceTopic": `Practise this topic`,
  "topics.previous": `Претходна`,
  "topics.reportIssue": `Пријавете проблем`,
  "topics.reviewedOn": `reviewed {date}`,
  "topics.reviewedTranslation": `Прегледан превод`,
  "topics.section": `Секција`,
  "topics.sections": `делови`,
  "topics.source": `Извор`,
  "topics.sourcesDescription": `Study text here is paraphrased from the Government of Canada citizenship study guide and reviewed on the dates shown. Practice questions are researched from the official study guide.`,
  "topics.sourcesHeading": `Content sources and review dates`,
  "topics.studyLanguageLabel": `Study content language`,
  "topics.title": `Теми за учење`,
  "topics.vocabulary": `Вокабулар`,
};
