// UI strings for 'mt' — chunk of strings.generated.ts. DO NOT EDIT BY HAND.
import type { StringKey } from "../strings.generated";

export const mt: Record<StringKey, string> = {
  "actions.askAi": `Staqsi lill-AI`,
  "actions.mockExam": `Mock eżami`,
  "actions.practice": `Prattika`,
  "actions.quickActions": `Quick actions`,
  "actions.study": `Studju`,
  "assistant.aiEyebrow": `Assistent tal-istudju tal-AI`,
  "assistant.answerLanguage": `Il-lingwa tat-tweġiba`,
  "assistant.charLimit": `Fadal {n} karattri`,
  "assistant.checkingMaterial": `Tiċċekkja l-materjal tal-istudju...`,
  "assistant.clearChat": `Ċat ċar`,
  "assistant.copied": `Ikkopjati`,
  "assistant.copy": `Kopja`,
  "assistant.description": `It-tweġibiet jinkitbu minn AI billi tuża biss il-materjal ta' studju ta' din l-app, bis-sorsi murija. L-IA xorta tista' tagħmel żbalji — iċċekkja dettalji importanti fuq il-paġni uffiċjali tal-Gvern tal-Kanada. Mhux pariri legali jew dwar l-immigrazzjoni.`,
  "assistant.enFrancais": `En français`,
  "assistant.error": `Xi ħaġa marret ħażin. Jekk jogħġbok erġa' pprova.`,
  "assistant.fromAppContent": `Mill-kontenut tal-app approvat`,
  "assistant.groundedBadge": `Ibbażat fuq l-art`,
  "assistant.helpful": `Jgħin`,
  "assistant.inputPlaceholder": `Staqsi mistoqsija dwar iċ-ċittadinanza Kanadiża...`,
  "assistant.myAppLanguage": `Il-lingwa tal-app tiegħi`,
  "assistant.notCovered": `Mhux kopert — ara l-paġna uffiċjali`,
  "assistant.notHelpful": `Mhux utli`,
  "assistant.openAssistant": `Assistent ta' studju miftuħ`,
  "assistant.openLink": `Assistent miftuħ`,
  "assistant.practiceThis": `Ipprattika dan`,
  "assistant.questionAriaLabel": `Il-mistoqsija tiegħek`,
  "assistant.reportIncorrect": `Irrapporta tweġiba żbaljata`,
  "assistant.send": `Ibgħat`,
  "assistant.showSource": `Uri s-sors`,
  "assistant.simpleEnglish": `Ingliż sempliċi`,
  "assistant.source": `Sors`,
  "assistant.starter1": `X'inhuma t-tliet partijiet tal-Parlament?`,
  "assistant.starter2": `Spjega l-Karta sempliċiment`,
  "assistant.starter3": `Min jirrappreżenta lir-Re fil-Kanada?`,
  "assistant.starter4": `Xi jkopri t-test tal-għarfien?`,
  "assistant.suggestedQuestions": `Mistoqsijiet suġġeriti`,
  "assistant.thinking": `Taħseb...`,
  "assistant.title": `Assistent ta' studju`,
  "assistant.tryAgain": `Erġa' pprova`,
  "assistant.tryAsking": `Ipprova staqsi:`,
  "assistant.vocabularyLabel": `Vokabolarju:`,
  "assistant.whyItMatters": `Għaliex huwa importanti għat-test`,
  "bookmarks.continueStudying": `Kompli tistudja`,
  "bookmarks.empty": `Għadu l-ebda bookmarks. Tektek l-istilla fuq kwalunkwe mistoqsija biex issalvaha għal reviżjoni.`,
  "bookmarks.emptyQuestions": `S'issa xejn ma ġie salvat. Tektek ☆ fuq mistoqsija ta' prattika.`,
  "bookmarks.emptySections": `S'issa xejn ma ġie salvat. Tektek ☆ waqt li taqra taqsima.`,
  "bookmarks.remove": `Neħħi`,
  "bookmarks.savedForReview": `salvati għal reviżjoni`,
  "bookmarks.savedQuestions": `Mistoqsijiet salvati ({n})`,
  "bookmarks.savedSections": `Sezzjonijiet salvati ({n})`,
  "bookmarks.search": `Fittex bookmarks...`,
  "bookmarks.title": `Bookmarks`,
  "cards.answered": `Imwieġba`,
  "cards.bookmarks": `salvati għal reviżjoni`,
  "cards.bookmarksLabel": `Bookmarks`,
  "cards.continueLearning": `Kompli titgħallem`,
  "cards.correct": `Ikkoreġi`,
  "cards.dailyGoal": `{done}/{total} mistoqsijiet illum`,
  "cards.dailyGoalLabel": `Għan ta’ kuljum`,
  "cards.dailyGoalTitle": `Daily goal`,
  "cards.mockExam.subtitle": `Timed · 20 mistoqsija`,
  "cards.mockExam.title": `Mock eżami`,
  "cards.officialInfo.button": `Iftaħ canada.ca`,
  "cards.officialInfo.subtitle": `Żur canada.ca għal dettalji uffiċjali`,
  "cards.officialInfo.title": `Informazzjoni uffiċjali`,
  "cards.progress": `Progress`,
  "cards.progressDetails": `Dettalji`,
  "cards.recentlyStudied": `Studjata riċentement`,
  "cards.sections": `Taqsimiet`,
  "cards.studyAssistant.subtitle": `Staqsi xi ħaġa dwar il-materjal tal-istudju`,
  "cards.studyAssistant.title": `Assistent ta' studju`,
  "cards.todaysRecommendation": `Ir-rakkomandazzjoni tal-lum`,
  "cards.verifiedSource.subtext": `Kontenut iċċekkjat ma' sorsi uffiċjali. Għajnuna ta' studju indipendenti — mhux affiljata ma' jew approvata mill-Gvern tal-Kanada jew l-IRCC.`,
  "cards.verifiedSource.title": `Sors ivverifikat`,
  "common.back": `Lura`,
  "common.cancel": `Ikkanċella`,
  "common.close": `Agħlaq`,
  "common.continue": `Kompli`,
  "common.done": `Magħmul`,
  "common.emptyBookmarks": `S'issa xejn ma ġie salvat`,
  "common.emptyRecentlyStudied": `S'issa xejn ma ġie studjat — agħżel suġġett biex tibda.`,
  "common.loading": `Tagħbija...`,
  "common.next": `Li jmiss`,
  "common.of": `ta`,
  "common.previous": `Preċedenti`,
  "common.retry": `Ipprova mill-ġdid`,
  "common.save": `Ħlief`,
  "exam.allTopics": `Is-suġġetti kollha`,
  "exam.answeredCount": `{n} wieġeb`,
  "exam.autosaveNote": `It-tweġibiet tiegħek jiġu ssejvjati hekk kif tmur, għalhekk meta tagħlaq l-app ma titlefx il-progress tiegħek.`,
  "exam.cancel": `Ikkanċella`,
  "exam.confirm": `Ikkonferma`,
  "exam.confirmEnd": `{n} mistoqsijiet mhumiex imwieġba u se jkunu mmarkati mhux korretti.`,
  "exam.confirmEndTitle": `Tmiem l-eżami?`,
  "exam.endExamEarly": `Tmiem l-eżami kmieni`,
  "exam.examDisclaimer": `Dan il-punteġġ jirrifletti l-kampjuni ta' mistoqsijiet ta' din l-app biss.`,
  "exam.finishExam": `Temm l-eżami`,
  "exam.newExam": `Eżami ġdid`,
  "exam.noMistakes": `Ebda żbalji - punteġġ perfett!`,
  "exam.pastAttempts": `Tentattivi tal-passat`,
  "exam.questionAriaLabel": `Mistoqsija {n}`,
  "exam.questionCount": `Numru ta' mistoqsijiet`,
  "exam.questionOf": `Mistoqsija {n} ta' {total}`,
  "exam.questionPalette": `Mistoqsijiet`,
  "exam.questionsOption": `{n} mistoqsijiet`,
  "exam.resultsTitle": `Il-punteġġ tiegħek`,
  "exam.reviewMistakes": `Irrevedi l-iżbalji tiegħek ({n})`,
  "exam.scoreLine": `{correct} of {total} correct`,
  "exam.seeProgress": `Ara l-progress`,
  "exam.setupDescription": `Din hija simulazzjoni ta' prattika mibnija mill-mistoqsijiet ta' studju ta' din l-app. Mhuwiex it-test uffiċjali u ma jbassarx ir-riżultat tiegħek.`,
  "exam.setupTitle": `Stabbilixxi l-eżami finta tiegħek`,
  "exam.simulationNote": `Simulazzjoni tal-prattika · mhux uffiċjali`,
  "exam.startExam": `Ibda l-eżami`,
  "exam.timeLeft": `Fadal ħin`,
  "exam.timedLabel": `bil-ħin`,
  "exam.timedToggle": `Timed (90 sekonda għal kull mistoqsija)`,
  "exam.title": `Mock eżami`,
  "exam.topicFilter": `Suġġett`,
  "exam.untimedLabel": `bla ħin`,
  "footer.disclaimer": `Citizen Prep hija għajnuna għall-istudju indipendenti. Mhux affiljat ma' jew approvat mill-Gvern tal-Kanada jew IRCC. Ma jistax jiggarantixxi riżultat li jgħaddi.`,
  "header.appName": `Ċittadin Prep`,
  "header.tagline": `Għodda ta' studju indipendenti · Mhux uffiċjali`,
  "hero.sectionsProgress": `{done} of {total} sections · {percent}% complete`,
  "hero.subtitle": `Għodda ta’ studju indipendenti · Ingliż u Franċiż · ebda kont meħtieġ`,
  "hero.title": `Ipprepara għat-test taċ-ċittadinanza tiegħek`,
  "nav.exam": `Eżami`,
  "nav.home": `Dar`,
  "nav.practice": `Prattika`,
  "nav.progress": `Progress`,
  "nav.topics": `Suġġetti`,
  "practice.allLevels": `Il-livelli kollha`,
  "practice.allTopics": `Is-suġġetti kollha`,
  "practice.askAiAbout": `Staqsi lill-AI dwar din il-mistoqsija`,
  "practice.bookmarkQuestion": `Bookmark mistoqsija`,
  "practice.bookmarked": `Bookmarked`,
  "practice.checkAnswer": `Iċċekkja t-tweġiba`,
  "practice.correct": `Ikkoreġi`,
  "practice.demoContent": `Kontenut Demo`,
  "practice.difficulty": `Diffikultà`,
  "practice.easy": `Faċli`,
  "practice.explanation": `Spjegazzjoni`,
  "practice.filters": `Filtri`,
  "practice.hard": `Iebsa`,
  "practice.incorrect": `Mhux pjuttost`,
  "practice.medium": `Medju`,
  "practice.nextQuestion": `Mistoqsija li jmiss`,
  "practice.questionCounter": `Mistoqsija ta' prattika {n} ta' {total}`,
  "practice.reportIssue": `Irrapporta kwistjoni`,
  "practice.title": `Prattika`,
  "practice.topicFilter": `Suġġett`,
  "practice.tryAgain": `Erġa' pprova`,
  "progress.accuracy": `Eżattezza`,
  "progress.clearProgressDesc": `Dan iħassar it-tweġibiet, it-tlestijiet, il-bookmarks u l-istorja tal-eżamijiet tiegħek minn dan l-apparat. Ma jistax jitneħħa.`,
  "progress.clearProgressLabel": `Ċara l-progress kollu tal-istudju`,
  "progress.confirmClear": `Iva, ċar kollox`,
  "progress.dailyGoal": `Għan ta’ kuljum`,
  "progress.details": `Dettalji`,
  "progress.examHistory": `L-istorja tal-eżami`,
  "progress.noExams": `S'issa ma sarux eżamijiet.`,
  "progress.noWrongAnswers": `Ebda tweġibiet żbaljati biex tirrevedi bħalissa.`,
  "progress.overview": `Ħarsa ġenerali`,
  "progress.perTopic": `Għal kull suġġett`,
  "progress.questionsAnswered": `Mistoqsijiet imwieġba`,
  "progress.reset": `Irrisettja`,
  "progress.retryTopic": `Erġa' pprova dan is-suġġett`,
  "progress.sectionsDone": `It-taqsimiet lesti`,
  "progress.suggestedNext": `Suggested next: {topic}`,
  "progress.title": `Progress`,
  "progress.topicCompletion": `Tlestija tas-suġġett`,
  "report.detailsPlaceholder": `Għidilna aktar (mhux obbligatorju)`,
  "report.incorrectAnswer": `Tweġiba żbaljata`,
  "report.outdatedInfo": `Informazzjoni skaduta`,
  "report.submit": `Issottometti rapport`,
  "report.technicalIssue": `Kwistjoni teknika`,
  "report.thanks": `Grazzi — ir-rapporti huma maħżuna lokalment fuq dan l-apparat.`,
  "report.translationProblem": `Problema tat-traduzzjoni`,
  "report.unclearExplanation": `Spjegazzjoni peu claire`,
  "settings.about": `Dwar din l-app`,
  "settings.appInterfaceLanguage": `Lingwa tal-interface tal-app`,
  "settings.clearProgress": `Progress ċar`,
  "settings.clearProgressConfirm": `Int żgur? Dan se jħassar il-progress kollu tiegħek.`,
  "settings.interfaceDescription": `Menus, buttuni u navigazzjoni.`,
  "settings.language": `Lingwa`,
  "settings.machineNote": `Kontenut tradott bil-magni ma ġiex iċċekkjat minn reviżur uman. Xejn hawn mhu ttikkettjat bħala rivedut sakemm ma jkunx fil-fatt ġie rivedut.`,
  "settings.machineTranslatedBadge": `Tradott bil-magna`,
  "settings.manageProgress": `Immaniġġja d-dejta tal-progress tiegħek`,
  "settings.notAvailable": `Għadu mhux disponibbli`,
  "settings.officialGuideLink": `Gwida ta' studju uffiċjali`,
  "settings.officialTestLink": `Informazzjoni uffiċjali dwar it-test taċ-ċittadinanza`,
  "settings.privacy": `Privatezza`,
  "settings.privacyText": `It-tweġibiet, il-bookmarks u s-settings tiegħek huma maħżuna biss fuq dan it-tagħmir. L-ebda kont mhu meħtieġ. Mistoqsijiet li tistaqsi lill-assistent tal-istudju jintbagħtu lil servizz tal-AI biex jiġġenera tweġibiet.`,
  "settings.reviewedBadge": `Riveduta`,
  "settings.studyContentLanguage": `Studja l-lingwa tal-kontenut`,
  "settings.studyDescription": `Test tat-tagħlim u spjegazzjonijiet. Tista' taqra b'lingwa waħda waqt li tkun qed tinnaviga f'oħra.`,
  "settings.textSize": `Daqs tat-test`,
  "settings.title": `Settings`,
  "topics.askAssistant": `Staqsi lill-assistent dwar din it-taqsima`,
  "topics.bookmarkSection": `Sezzjoni Bookmark`,
  "topics.bookmarkedSection": `Bookmarked`,
  "topics.completed": `Imlesta`,
  "topics.continueLearningCard": `Kompli titgħallem`,
  "topics.demoSourceNote": `Mistoqsija oriġinali tal-kampjun — mhux mistoqsija uffiċjali tal-eżami`,
  "topics.lastVerified": `L-aħħar verifikata {date}`,
  "topics.markComplete": `Immarka bħala kompluta`,
  "topics.markIncomplete": `Immarka bħala mhux komplut`,
  "topics.minRead": `{n} min qari`,
  "topics.next": `Li jmiss`,
  "topics.openOfficialPage": `Iftaħ il-paġna uffiċjali`,
  "topics.paraphrasedSourceNote": `Parafrasat minn materjal uffiċjali`,
  "topics.practiceTopic": `Ipprattika dan is-suġġett`,
  "topics.previous": `Preċedenti`,
  "topics.reportIssue": `Irrapporta kwistjoni`,
  "topics.reviewedOn": `reviewed {date}`,
  "topics.reviewedTranslation": `Traduzzjoni riveduta`,
  "topics.section": `Taqsima`,
  "topics.sections": `sezzjonijiet`,
  "topics.source": `Sors`,
  "topics.sourcesDescription": `It-test tal-istudju hawnhekk huwa parafrasat mill-gwida tal-istudju taċ-ċittadinanza tal-Gvern tal-Kanada u rivedut fid-dati murija. Mistoqsijiet prattika huma riċerkati mill-gwida ta 'studju uffiċjali.`,
  "topics.sourcesHeading": `Sorsi tal-kontenut u dati tar-reviżjoni`,
  "topics.studyLanguageLabel": `Studja l-lingwa tal-kontenut`,
  "topics.title": `Suġġetti ta' studju`,
  "topics.vocabulary": `Vokabolarju`,
};
