// UI strings for 'nl' — chunk of strings.generated.ts. DO NOT EDIT BY HAND.
import type { StringKey } from "../strings.generated";

export const nl: Record<StringKey, string> = {
  "actions.askAi": `Vraag het AI`,
  "actions.mockExam": `Proefexamen`,
  "actions.practice": `Oefen`,
  "actions.quickActions": `Quick actions`,
  "actions.study": `Studeer`,
  "assistant.aiEyebrow": `AI-studieassistent`,
  "assistant.answerLanguage": `Antwoordtaal`,
  "assistant.charLimit": `{n} tekens over`,
  "assistant.checkingMaterial": `Het studiemateriaal controleren…`,
  "assistant.clearChat": `Duidelijke chat`,
  "assistant.copied": `Gekopieerd`,
  "assistant.copy": `Kopieer`,
  "assistant.description": `De antwoorden worden door AI geschreven met uitsluitend het studiemateriaal van deze app, waarbij de bronnen worden getoond. AI kan nog steeds fouten maken – bekijk belangrijke details op de officiële pagina’s van de Canadese overheid. Geen juridisch of immigratieadvies.`,
  "assistant.enFrancais": `In het Frans`,
  "assistant.error": `Er is iets misgegaan. Probeer het opnieuw.`,
  "assistant.fromAppContent": `Van goedgekeurde app-inhoud`,
  "assistant.groundedBadge": `Brongeaard`,
  "assistant.helpful": `Handig`,
  "assistant.inputPlaceholder": `Stel een vraag over het Canadese staatsburgerschap...`,
  "assistant.myAppLanguage": `Mijn app-taal`,
  "assistant.notCovered": `Niet gedekt - zie officiële pagina`,
  "assistant.notHelpful": `Niet nuttig`,
  "assistant.openAssistant": `Open studie assistent`,
  "assistant.openLink": `Open assistent`,
  "assistant.practiceThis": `Oefen dit`,
  "assistant.questionAriaLabel": `Jouw vraag`,
  "assistant.reportIncorrect": `Rapporteer een onjuist antwoord`,
  "assistant.send": `Verzenden`,
  "assistant.showSource": `Bron tonen`,
  "assistant.simpleEnglish": `Eenvoudig Engels`,
  "assistant.source": `Bron`,
  "assistant.starter1": `Wat zijn de drie delen van het Parlement?`,
  "assistant.starter2": `Leg het Handvest eenvoudig uit`,
  "assistant.starter3": `Wie vertegenwoordigt de koning in Canada?`,
  "assistant.starter4": `Wat houdt de kennistest in?`,
  "assistant.suggestedQuestions": `Voorgestelde vragen`,
  "assistant.thinking": `Denken…`,
  "assistant.title": `Studie assistent`,
  "assistant.tryAgain": `Probeer het opnieuw`,
  "assistant.tryAsking": `Probeer het volgende te vragen:`,
  "assistant.vocabularyLabel": `Woordenschat:`,
  "assistant.whyItMatters": `Waarom het belangrijk is voor de test`,
  "auth.account": `Account`,
  "auth.checkEmail": `Check your email to confirm your account, then sign in.`,
  "auth.close": `Close`,
  "auth.codeLabel": `Verification code`,
  "auth.codeResent": `New code sent. Check your email.`,
  "auth.codeSent": `Code sent! Check your email and enter the 6-digit code.`,
  "auth.createAccount": `Create account`,
  "auth.dataDeletedMsg": `Your progress and profile data were deleted.`,
  "auth.deleteConfirm": `Tap again to permanently delete`,
  "auth.deleteData": `Delete my data`,
  "auth.email": `Email`,
  "auth.haveAccount": `Already have an account?`,
  "auth.mfaCodeLabel": `Authenticator code`,
  "auth.mfaDisable": `Disable 2FA`,
  "auth.mfaDisabledMsg": `Two-factor authentication is now OFF.`,
  "auth.mfaEnable": `Enable 2FA`,
  "auth.mfaEnabledMsg": `Two-factor authentication is now ON for your account.`,
  "auth.mfaPendingWarn": `2FA code still needed to finish signing in.`,
  "auth.mfaPrompt": `This account uses 2FA — enter the code from your authenticator app.`,
  "auth.mfaScanHint": `Scan this QR code with your authenticator app (Google Authenticator, Authy, 1Password…), then enter the 6-digit code it shows.`,
  "auth.mfaSetupTitle": `Set up two-factor authentication`,
  "auth.mfaSubtitle": `Enter the 6-digit code from your authenticator app.`,
  "auth.mfaTitle": `Two-factor authentication`,
  "auth.noAccount": `Don't have an account?`,
  "auth.password": `Password`,
  "auth.passwordHint": `At least 6 characters`,
  "auth.privacy": `Privacy`,
  "auth.privacyNote": `Your email and progress are private — only you can see them.`,
  "auth.resendCode": `Resend code`,
  "auth.security": `Security`,
  "auth.signIn": `Sign in`,
  "auth.signOut": `Sign out`,
  "auth.signUp": `Sign up`,
  "auth.subtitle": `Save your progress across devices. Your data stays private.`,
  "auth.title": `Account`,
  "auth.verify": `Verify`,
  "auth.verifyCodeSubtitle": `We sent a 6-digit code to your email. Enter it below to finish signing up.`,
  "auth.verifyCodeTitle": `Enter your code`,
  "auth.working": `Please wait…`,
  "bookmarks.continueStudying": `Ga door met studeren`,
  "bookmarks.empty": `Nog geen bladwijzers. Tik op de ster bij een vraag om deze op te slaan ter beoordeling.`,
  "bookmarks.emptyQuestions": `Nog niets opgeslagen. Tik op ☆ op een oefenvraag.`,
  "bookmarks.emptySections": `Nog niets opgeslagen. Tik op ☆ terwijl je een sectie leest.`,
  "bookmarks.remove": `Verwijderen`,
  "bookmarks.savedForReview": `opgeslagen voor beoordeling`,
  "bookmarks.savedQuestions": `Opgeslagen vragen ({n})`,
  "bookmarks.savedSections": `Opgeslagen secties ({n})`,
  "bookmarks.search": `Bladwijzers zoeken…`,
  "bookmarks.title": `Bladwijzers`,
  "cards.answered": `Beantwoord`,
  "cards.bookmarks": `opgeslagen voor beoordeling`,
  "cards.bookmarksLabel": `Bladwijzers`,
  "cards.continueLearning": `Ga door met leren`,
  "cards.correct": `Juist`,
  "cards.dailyGoal": `{done}/{total} questions today`,
  "cards.dailyGoalLabel": `Dagelijks doel`,
  "cards.dailyGoalTitle": `Daily goal`,
  "cards.mockExam.subtitle": `Getimed · 20 vragen`,
  "cards.mockExam.title": `Proefexamen`,
  "cards.officialInfo.button": `Open canada.ca`,
  "cards.officialInfo.subtitle": `Bezoek canada.ca voor officiële details`,
  "cards.officialInfo.title": `Officiële informatie`,
  "cards.progress": `Vooruitgang`,
  "cards.progressDetails": `Details`,
  "cards.recentlyStudied": `Recentelijk bestudeerd`,
  "cards.sections": `Secties`,
  "cards.studyAssistant.subtitle": `Vraag alles over het studiemateriaal`,
  "cards.studyAssistant.title": `Studie assistent`,
  "cards.todaysRecommendation": `De aanbeveling van vandaag`,
  "cards.verifiedSource.subtext": `Inhoud gecontroleerd aan de hand van officiële bronnen. Onafhankelijke studiehulp - niet aangesloten bij of goedgekeurd door de regering van Canada of IRCC.`,
  "cards.verifiedSource.title": `Geverifieerde bron`,
  "common.back": `Terug`,
  "common.cancel": `Annuleer`,
  "common.close": `Sluiten`,
  "common.continue": `Ga door`,
  "common.done": `Klaar`,
  "common.emptyBookmarks": `Nog niets opgeslagen`,
  "common.emptyRecentlyStudied": `Er is nog niets bestudeerd. Kies een onderwerp om te beginnen.`,
  "common.loading": `Laden...`,
  "common.next": `Volgende`,
  "common.of": `van`,
  "common.previous": `Vorige`,
  "common.retry": `Opnieuw proberen`,
  "common.save": `Opslaan`,
  "exam.allTopics": `Alle onderwerpen`,
  "exam.answeredCount": `{n} heeft geantwoord`,
  "exam.autosaveNote": `Uw antwoorden worden onderweg opgeslagen, dus als u de app sluit, gaat uw voortgang niet verloren.`,
  "exam.cancel": `Annuleer`,
  "exam.confirm": `Bevestig`,
  "exam.confirmEnd": `{n} vragen zijn onbeantwoord en worden als onjuist gemarkeerd.`,
  "exam.confirmEndTitle": `Einde examen?`,
  "exam.endExamEarly": `Eindig het examen vroegtijdig`,
  "exam.examDisclaimer": `Deze score weerspiegelt alleen de voorbeeldvragen van deze app.`,
  "exam.finishExam": `Examen afronden`,
  "exam.newExam": `Nieuw examen`,
  "exam.noMistakes": `Geen fouten - perfecte score!`,
  "exam.pastAttempts": `Eerdere pogingen`,
  "exam.questionAriaLabel": `Vraag {n}`,
  "exam.questionCount": `Aantal vragen`,
  "exam.questionOf": `Question {n} of {total}`,
  "exam.questionPalette": `Vragen`,
  "exam.questionsOption": `{n} vragen`,
  "exam.resultsTitle": `Jouw score`,
  "exam.reviewMistakes": `Controleer uw fouten ({n})`,
  "exam.scoreLine": `{correct} of {total} correct`,
  "exam.seeProgress": `Zie voortgang`,
  "exam.setupDescription": `Dit is een praktijksimulatie opgebouwd uit de studievragen van deze app. Het is niet de officiële test en voorspelt niet uw resultaat.`,
  "exam.setupTitle": `Stel uw proefexamen in`,
  "exam.simulationNote": `Oefensimulatie · niet officieel`,
  "exam.startExam": `Examen starten`,
  "exam.timeLeft": `Nog tijd over`,
  "exam.timedLabel": `getimed`,
  "exam.timedToggle": `Getimed (90 seconden per vraag)`,
  "exam.title": `Proefexamen`,
  "exam.topicFilter": `Onderwerp`,
  "exam.untimedLabel": `ongetimed`,
  "footer.disclaimer": `Citizen Prep is een onafhankelijk studiehulpmiddel. Niet aangesloten bij of goedgekeurd door de regering van Canada of IRCC. Het kan geen voldoende resultaat garanderen.`,
  "header.appName": `Burgervoorbereiding`,
  "header.tagline": `Onafhankelijke studietool · Niet officieel`,
  "hero.sectionsProgress": `{done} of {total} sections · {percent}% complete`,
  "hero.subtitle": `Onafhankelijke studietool · Engels en Frans · geen account nodig`,
  "hero.title": `Bereid u voor op uw inburgeringstest`,
  "nav.exam": `Examen`,
  "nav.home": `Thuis`,
  "nav.practice": `Oefen`,
  "nav.progress": `Vooruitgang`,
  "nav.topics": `Onderwerpen`,
  "practice.allLevels": `Alle niveaus`,
  "practice.allTopics": `Alle onderwerpen`,
  "practice.askAiAbout": `Stel AI over deze vraag`,
  "practice.bookmarkQuestion": `Bookmark vraag`,
  "practice.bookmarked": `Gemarkeerd`,
  "practice.checkAnswer": `Controleer antwoord`,
  "practice.correct": `Juist`,
  "practice.demoContent": `Demo-inhoud`,
  "practice.difficulty": `Moeilijkheidsgraad`,
  "practice.easy": `Gemakkelijk`,
  "practice.explanation": `Uitleg`,
  "practice.filters": `Filters`,
  "practice.hard": `Moeilijk`,
  "practice.incorrect": `Niet helemaal`,
  "practice.medium": `Middelmatig`,
  "practice.nextQuestion": `Volgende vraag`,
  "practice.questionCounter": `Practice question {n} of {total}`,
  "practice.reportIssue": `Rapporteer een probleem`,
  "practice.title": `Oefen`,
  "practice.topicFilter": `Onderwerp`,
  "practice.tryAgain": `Probeer het opnieuw`,
  "progress.accuracy": `Nauwkeurigheid`,
  "progress.clearProgressDesc": `Hiermee worden uw antwoorden, voltooiingen, bladwijzers en examengeschiedenis van dit apparaat verwijderd. Het kan niet ongedaan worden gemaakt.`,
  "progress.clearProgressLabel": `Wis alle studievoortgang`,
  "progress.confirmClear": `Ja, alles opruimen`,
  "progress.dailyGoal": `Dagelijks doel`,
  "progress.details": `Details`,
  "progress.examHistory": `Examen geschiedenis`,
  "progress.noExams": `Nog geen examens afgelegd.`,
  "progress.noWrongAnswers": `Er zijn momenteel geen onjuiste antwoorden om te beoordelen.`,
  "progress.overview": `Overzicht`,
  "progress.perTopic": `Per onderwerp`,
  "progress.questionsAnswered": `Vragen beantwoord`,
  "progress.reset": `Opnieuw instellen`,
  "progress.retryTopic": `Probeer dit onderwerp opnieuw`,
  "progress.sectionsDone": `Secties voltooid`,
  "progress.suggestedNext": `Suggested next: {topic}`,
  "progress.title": `Vooruitgang`,
  "progress.topicCompletion": `Onderwerp voltooiing`,
  "report.detailsPlaceholder": `Vertel ons meer (optioneel)`,
  "report.incorrectAnswer": `Onjuist antwoord`,
  "report.outdatedInfo": `Verouderde informatie`,
  "report.submit": `Rapport indienen`,
  "report.technicalIssue": `Technisch probleem`,
  "report.thanks": `Bedankt. Rapporten worden lokaal op dit apparaat opgeslagen.`,
  "report.translationProblem": `Vertaalprobleem`,
  "report.unclearExplanation": `Uitleg peu claire`,
  "settings.about": `Over deze app`,
  "settings.appInterfaceLanguage": `Taal van de app-interface`,
  "settings.clearProgress": `Duidelijke vooruitgang`,
  "settings.clearProgressConfirm": `Weet je het zeker? Hiermee wordt al je voortgang verwijderd.`,
  "settings.interfaceDescription": `Menu's, knoppen en navigatie.`,
  "settings.language": `Taal`,
  "settings.machineNote": `Machinaal vertaalde inhoud is niet gecontroleerd door een menselijke recensent. Niets hier wordt als beoordeeld bestempeld, tenzij het daadwerkelijk is beoordeeld.`,
  "settings.machineTranslatedBadge": `Machinaal vertaald`,
  "settings.manageProgress": `Beheer uw voortgangsgegevens`,
  "settings.notAvailable": `Nog niet beschikbaar`,
  "settings.officialGuideLink": `Officiële studiegids`,
  "settings.officialTestLink": `Officiële informatie over de staatsburgerschapstest`,
  "settings.privacy": `Privacy`,
  "settings.privacyText": `Uw antwoorden, bladwijzers en instellingen worden alleen op dit apparaat opgeslagen. Er is geen account nodig. Vragen die je aan de studieassistent stelt, worden naar een AI-dienst gestuurd om antwoorden te genereren.`,
  "settings.reviewedBadge": `Beoordeeld`,
  "settings.studyContentLanguage": `Bestudeer de inhoudstaal`,
  "settings.studyDescription": `Tekst en uitleg leren. U kunt in de ene taal lezen terwijl u in een andere taal navigeert.`,
  "settings.textSize": `Tekstgrootte`,
  "settings.title": `Instellingen`,
  "topics.askAssistant": `Vraag de assistent naar dit onderdeel`,
  "topics.bookmarkSection": `Bladwijzersectie`,
  "topics.bookmarkedSection": `Gemarkeerd`,
  "topics.completed": `Voltooid`,
  "topics.continueLearningCard": `Ga door met leren`,
  "topics.demoSourceNote": `Originele voorbeeldvraag — geen officiële examenvraag`,
  "topics.lastVerified": `Laatst geverifieerd op {date}`,
  "topics.markComplete": `Markeer als voltooid`,
  "topics.markIncomplete": `Markeer als onvolledig`,
  "topics.minRead": `{n} min gelezen`,
  "topics.next": `Volgende`,
  "topics.openOfficialPage": `Officiële pagina openen`,
  "topics.paraphrasedSourceNote": `Geparafraseerd uit officieel materiaal`,
  "topics.practiceTopic": `Oefen dit onderwerp`,
  "topics.previous": `Vorige`,
  "topics.reportIssue": `Rapporteer een probleem`,
  "topics.reviewedOn": `reviewed {date}`,
  "topics.reviewedTranslation": `Beoordeelde vertaling`,
  "topics.section": `Sectie`,
  "topics.sections": `secties`,
  "topics.source": `Bron`,
  "topics.sourcesDescription": `De studietekst hier is geparafraseerd uit de studiegids voor het staatsburgerschap van de Canadese overheid en beoordeeld op de weergegeven data. Oefenvragen worden onderzocht vanuit de officiële studiegids.`,
  "topics.sourcesHeading": `Inhoudsbronnen en beoordelingsdata`,
  "topics.studyLanguageLabel": `Bestudeer de inhoudstaal`,
  "topics.title": `Onderwerpen bestuderen`,
  "topics.vocabulary": `Woordenschat`,
};
