// UI strings for 'no' — chunk of strings.generated.ts. DO NOT EDIT BY HAND.
import type { StringKey } from "../strings.generated";

export const no: Record<StringKey, string> = {
  "actions.askAi": `Spør AI`,
  "actions.mockExam": `Spoteksamen`,
  "actions.practice": `Øv`,
  "actions.quickActions": `Quick actions`,
  "actions.study": `Studer`,
  "assistant.aiEyebrow": `AI-studieassistent`,
  "assistant.answerLanguage": `Svarspråk`,
  "assistant.charLimit": `{n} tegn igjen`,
  "assistant.checkingMaterial": `Sjekker studiematerialet...`,
  "assistant.clearChat": `Tøm chat`,
  "assistant.copied": `Kopiert`,
  "assistant.copy": `Kopier`,
  "assistant.description": `Svarene er skrevet av AI ved å bruke kun denne appens studiemateriale, med kilder vist. AI kan fortsatt gjøre feil - sjekk viktige detaljer på de offisielle sidene for regjeringen i Canada. Ikke juridisk eller immigrasjonsråd.`,
  "assistant.enFrancais": `En français`,
  "assistant.error": `Noe gikk galt. Vennligst prøv igjen.`,
  "assistant.fromAppContent": `Fra godkjent appinnhold`,
  "assistant.groundedBadge": `Kildebasert`,
  "assistant.helpful": `Nyttig`,
  "assistant.inputPlaceholder": `Still et spørsmål om kanadisk statsborgerskap...`,
  "assistant.myAppLanguage": `Appens språk`,
  "assistant.notCovered": `Ikke dekket - se offisiell side`,
  "assistant.notHelpful": `Ikke nyttig`,
  "assistant.openAssistant": `Åpen studieassistent`,
  "assistant.openLink": `Åpne assistent`,
  "assistant.practiceThis": `Øv på dette`,
  "assistant.questionAriaLabel": `Spørsmålet ditt`,
  "assistant.reportIncorrect": `Rapporter feil svar`,
  "assistant.send": `Send`,
  "assistant.showSource": `Vis kilde`,
  "assistant.simpleEnglish": `Enkel engelsk`,
  "assistant.source": `Kilde`,
  "assistant.starter1": `Hva er de tre delene av Stortinget?`,
  "assistant.starter2": `Forklar charteret enkelt`,
  "assistant.starter3": `Hvem representerer kongen i Canada?`,
  "assistant.starter4": `Hva dekker kunnskapstesten?`,
  "assistant.suggestedQuestions": `Foreslåtte spørsmål`,
  "assistant.thinking": `Tenker...`,
  "assistant.title": `Studieassistent`,
  "assistant.tryAgain": `Prøv igjen`,
  "assistant.tryAsking": `Prøv å spørre:`,
  "assistant.vocabularyLabel": `Ordforråd:`,
  "assistant.whyItMatters": `Hvorfor det er viktig for testen`,
  "bookmarks.continueStudying": `Fortsett å studere`,
  "bookmarks.empty": `Ingen bokmerker ennå. Trykk på stjernen på et spørsmål for å lagre det for vurdering.`,
  "bookmarks.emptyQuestions": `Ingenting er lagret ennå. Trykk ☆ på et øvingsspørsmål.`,
  "bookmarks.emptySections": `Ingenting er lagret ennå. Trykk på ☆ mens du leser en del.`,
  "bookmarks.remove": `Fjern`,
  "bookmarks.savedForReview": `lagret for gjennomgang`,
  "bookmarks.savedQuestions": `Lagrede spørsmål ({n})`,
  "bookmarks.savedSections": `Lagrede seksjoner ({n})`,
  "bookmarks.search": `Søk etter bokmerker...`,
  "bookmarks.title": `Bokmerker`,
  "cards.answered": `Besvart`,
  "cards.bookmarks": `lagret for gjennomgang`,
  "cards.bookmarksLabel": `Bokmerker`,
  "cards.continueLearning": `Fortsett å lære`,
  "cards.correct": `Riktig`,
  "cards.dailyGoal": `{done}/{total} spørsmål i dag`,
  "cards.dailyGoalLabel": `Daglig mål`,
  "cards.dailyGoalTitle": `Daily goal`,
  "cards.mockExam.subtitle": `Tidsbestemt · 20 spørsmål`,
  "cards.mockExam.title": `Spoteksamen`,
  "cards.officialInfo.button": `Åpne canada.ca`,
  "cards.officialInfo.subtitle": `Besøk canada.ca for offisielle detaljer`,
  "cards.officialInfo.title": `Offisiell informasjon`,
  "cards.progress": `Fremgang`,
  "cards.progressDetails": `Detaljer`,
  "cards.recentlyStudied": `Nylig studert`,
  "cards.sections": `Seksjoner`,
  "cards.studyAssistant.subtitle": `Spør hva som helst om studiematerialet`,
  "cards.studyAssistant.title": `Studieassistent`,
  "cards.todaysRecommendation": `Dagens anbefaling`,
  "cards.verifiedSource.subtext": `Innhold sjekket mot offisielle kilder. Uavhengig studiehjelp - ikke tilknyttet eller godkjent av Canadas regjering eller IRCC.`,
  "cards.verifiedSource.title": `Verifisert kilde`,
  "common.back": `Tilbake`,
  "common.cancel": `Avbryt`,
  "common.close": `Lukk`,
  "common.continue": `Fortsett`,
  "common.done": `Ferdig`,
  "common.emptyBookmarks": `Ingenting er lagret ennå`,
  "common.emptyRecentlyStudied": `Ingenting studert ennå - velg et emne for å begynne.`,
  "common.loading": `Laster inn …`,
  "common.next": `Neste`,
  "common.of": `av`,
  "common.previous": `Forrige`,
  "common.retry": `Prøv på nytt`,
  "common.save": `Lagre`,
  "exam.allTopics": `Alle emner`,
  "exam.answeredCount": `{n} svarte`,
  "exam.autosaveNote": `Svarene dine lagres mens du går, så lukking av appen vil ikke miste fremgangen din.`,
  "exam.cancel": `Avbryt`,
  "exam.confirm": `Bekreft`,
  "exam.confirmEnd": `{n} spørsmål er ubesvarte og vil bli merket som feil.`,
  "exam.confirmEndTitle": `Avslutte eksamen?`,
  "exam.endExamEarly": `Avslutt eksamen tidlig`,
  "exam.examDisclaimer": `Denne poengsummen gjenspeiler kun denne appens eksempelspørsmål.`,
  "exam.finishExam": `Fullfør eksamen`,
  "exam.newExam": `Ny eksamen`,
  "exam.noMistakes": `Ingen feil – perfekt poengsum!`,
  "exam.pastAttempts": `Tidligere forsøk`,
  "exam.questionAriaLabel": `Spørsmål {n}`,
  "exam.questionCount": `Antall spørsmål`,
  "exam.questionOf": `Spørsmål {n} av {total}`,
  "exam.questionPalette": `Spørsmål`,
  "exam.questionsOption": `{n} spørsmål`,
  "exam.resultsTitle": `Poengsummen din`,
  "exam.reviewMistakes": `Se gjennom feilene dine ({n})`,
  "exam.scoreLine": `{correct} av {total} riktig`,
  "exam.seeProgress": `Se fremgang`,
  "exam.setupDescription": `Dette er en praksissimulering bygget fra denne appens studiespørsmål. Det er ikke den offisielle testen og forutsier ikke resultatet.`,
  "exam.setupTitle": `Sett opp en falsk eksamen`,
  "exam.simulationNote": `Øv simulering · ikke offisiell`,
  "exam.startExam": `Start eksamen`,
  "exam.timeLeft": `Tid igjen`,
  "exam.timedLabel": `tidsbestemt`,
  "exam.timedToggle": `Tidsbestemt (90 sekunder per spørsmål)`,
  "exam.title": `Spoteksamen`,
  "exam.topicFilter": `Emne`,
  "exam.untimedLabel": `utidsbestemt`,
  "footer.disclaimer": `Citizen Prep er et uavhengig studiehjelpemiddel. Ikke tilknyttet eller godkjent av Canadas regjering eller IRCC. Det kan ikke garantere et bestått resultat.`,
  "header.appName": `Citizen Prep`,
  "header.tagline": `Uavhengig studieverktøy · Ikke offisielt`,
  "hero.sectionsProgress": `{done} of {total} sections · {percent}% complete`,
  "hero.subtitle": `Uavhengig studieverktøy · Engelsk og fransk · ingen konto nødvendig`,
  "hero.title": `Forbered deg på statsborgerskapsprøven`,
  "nav.exam": `Eksamen`,
  "nav.home": `Hjem`,
  "nav.practice": `Øv`,
  "nav.progress": `Fremgang`,
  "nav.topics": `Emner`,
  "practice.allLevels": `Alle nivåer`,
  "practice.allTopics": `Alle emner`,
  "practice.askAiAbout": `Spør AI om dette spørsmålet`,
  "practice.bookmarkQuestion": `Bokmerke spørsmål`,
  "practice.bookmarked": `Bokmerket`,
  "practice.checkAnswer": `Sjekk svaret`,
  "practice.correct": `Riktig`,
  "practice.demoContent": `Demo innhold`,
  "practice.difficulty": `Vanskelighetsgrad`,
  "practice.easy": `Enkelt`,
  "practice.explanation": `Forklaring`,
  "practice.filters": `Filtre`,
  "practice.hard": `Hardt`,
  "practice.incorrect": `Ikke helt`,
  "practice.medium": `Middels`,
  "practice.nextQuestion": `Neste spørsmål`,
  "practice.questionCounter": `Øv spørsmål {n} av {total}`,
  "practice.reportIssue": `Rapporter et problem`,
  "practice.title": `Øv`,
  "practice.topicFilter": `Emne`,
  "practice.tryAgain": `Prøv igjen`,
  "progress.accuracy": `Nøyaktighet`,
  "progress.clearProgressDesc": `Dette sletter svarene, fullføringene, bokmerkene og eksamensloggen fra denne enheten. Det kan ikke angres.`,
  "progress.clearProgressLabel": `Fjern all studiefremgang`,
  "progress.confirmClear": `Ja, fjern alt`,
  "progress.dailyGoal": `Daglig mål`,
  "progress.details": `Detaljer`,
  "progress.examHistory": `Eksamenshistorie`,
  "progress.noExams": `Ingen eksamener tatt ennå.`,
  "progress.noWrongAnswers": `Ingen feil svar å vurdere akkurat nå.`,
  "progress.overview": `Oversikt`,
  "progress.perTopic": `Per emne`,
  "progress.questionsAnswered": `Spørsmål besvart`,
  "progress.reset": `Tilbakestill`,
  "progress.retryTopic": `Prøv dette emnet på nytt`,
  "progress.sectionsDone": `Seksjoner fullført`,
  "progress.suggestedNext": `Foreslått neste: {topic}`,
  "progress.title": `Fremgang`,
  "progress.topicCompletion": `Emneavslutning`,
  "report.detailsPlaceholder": `Fortell oss mer (valgfritt)`,
  "report.incorrectAnswer": `Feil svar`,
  "report.outdatedInfo": `Utdatert informasjon`,
  "report.submit": `Send inn rapport`,
  "report.technicalIssue": `Teknisk problem`,
  "report.thanks": `Takk – rapporter lagres lokalt på denne enheten.`,
  "report.translationProblem": `Oversettelsesproblem`,
  "report.unclearExplanation": `Forklaring peu claire`,
  "settings.about": `Om denne appen`,
  "settings.appInterfaceLanguage": `App-grensesnittspråk`,
  "settings.clearProgress": `Klar fremgang`,
  "settings.clearProgressConfirm": `Er du sikker? Dette vil slette all fremdriften din.`,
  "settings.interfaceDescription": `Menyer, knapper og navigasjon.`,
  "settings.language": `Språk`,
  "settings.machineNote": `Maskinoversatt innhold har ikke blitt sjekket av en menneskelig anmelder. Ingenting her er merket som anmeldt med mindre det faktisk har blitt anmeldt.`,
  "settings.machineTranslatedBadge": `Maskinoversatt`,
  "settings.manageProgress": `Administrer fremdriftsdataene dine`,
  "settings.notAvailable": `Ikke tilgjengelig ennå`,
  "settings.officialGuideLink": `Offisiell studieguide`,
  "settings.officialTestLink": `Offisiell statsborgerskapstestinformasjon`,
  "settings.privacy": `Personvern`,
  "settings.privacyText": `Dine svar, bokmerker og innstillinger lagres kun på denne enheten. Ingen konto er nødvendig. Spørsmål du stiller til studieassistenten sendes til en AI-tjeneste for å generere svar.`,
  "settings.reviewedBadge": `Anmeldt`,
  "settings.studyContentLanguage": `Studer innholdsspråk`,
  "settings.studyDescription": `Lære tekst og forklaringer. Du kan lese på ett språk mens du navigerer på et annet.`,
  "settings.textSize": `Tekststørrelse`,
  "settings.title": `Innstillinger`,
  "topics.askAssistant": `Spør assistenten om denne delen`,
  "topics.bookmarkSection": `Bokmerkeseksjon`,
  "topics.bookmarkedSection": `Bokmerket`,
  "topics.completed": `Fullført`,
  "topics.continueLearningCard": `Fortsett å lære`,
  "topics.demoSourceNote": `Originalt eksempelspørsmål – ikke et offisielt eksamensspørsmål`,
  "topics.lastVerified": `Sist bekreftet {date}`,
  "topics.markComplete": `Merk som fullført`,
  "topics.markIncomplete": `Merk som ufullstendig`,
  "topics.minRead": `{n} min lest`,
  "topics.next": `Neste`,
  "topics.openOfficialPage": `Åpne offisiell side`,
  "topics.paraphrasedSourceNote": `Omskrevet fra offisielt materiale`,
  "topics.practiceTopic": `Øv på dette emnet`,
  "topics.previous": `Forrige`,
  "topics.reportIssue": `Rapporter et problem`,
  "topics.reviewedOn": `anmeldt {date}`,
  "topics.reviewedTranslation": `Gjennomgått oversettelse`,
  "topics.section": `Seksjon`,
  "topics.sections": `seksjoner`,
  "topics.source": `Kilde`,
  "topics.sourcesDescription": `Studieteksten her er omskrevet fra studieveiledningen for statsborgerskap i Canadas regjering og gjennomgått på de viste datoene. Praksisspørsmål er undersøkt fra den offisielle studieveiledningen.`,
  "topics.sourcesHeading": `Innholdskilder og vurderingsdatoer`,
  "topics.studyLanguageLabel": `Studer innholdsspråk`,
  "topics.title": `Studieemner`,
  "topics.vocabulary": `Ordforråd`,
};
