// UI strings for 'pl' — chunk of strings.generated.ts. DO NOT EDIT BY HAND.
import type { StringKey } from "../strings.generated";

export const pl: Record<StringKey, string> = {
  "actions.askAi": `Zapytaj AI`,
  "actions.mockExam": `Próbny egzamin`,
  "actions.practice": `Ćwicz`,
  "actions.quickActions": `Quick actions`,
  "actions.study": `Studiuj`,
  "assistant.aiEyebrow": `Asystent nauki AI`,
  "assistant.answerLanguage": `Język odpowiedzi`,
  "assistant.charLimit": `Pozostało {n} znaków`,
  "assistant.checkingMaterial": `Sprawdzanie materiałów do nauki…`,
  "assistant.clearChat": `Wyczyść czat`,
  "assistant.copied": `Skopiowano`,
  "assistant.copy": `Kopiuj`,
  "assistant.description": `Odpowiedzi są zapisywane przez sztuczną inteligencję wyłącznie przy użyciu materiałów do nauki z tej aplikacji, z pokazanymi źródłami. Sztuczna inteligencja nadal może popełniać błędy — sprawdź ważne szczegóły na oficjalnych stronach rządu Kanady. Nie jest to porada prawna ani imigracyjna.`,
  "assistant.enFrancais": `Français`,
  "assistant.error": `Coś poszło nie tak. Spróbuj ponownie.`,
  "assistant.fromAppContent": `Z zatwierdzonej zawartości aplikacji`,
  "assistant.groundedBadge": `Oparta na źródle`,
  "assistant.helpful": `Pomocne`,
  "assistant.inputPlaceholder": `Zadaj pytanie dotyczące obywatelstwa kanadyjskiego…`,
  "assistant.myAppLanguage": `Mój język aplikacji`,
  "assistant.notCovered": `Nieobjęte — patrz oficjalna strona`,
  "assistant.notHelpful": `Nieprzydatne`,
  "assistant.openAssistant": `Asystent nauki otwartej`,
  "assistant.openLink": `Otwórz asystenta`,
  "assistant.practiceThis": `Poćwicz to`,
  "assistant.questionAriaLabel": `Twoje pytanie`,
  "assistant.reportIncorrect": `Zgłoś błędną odpowiedź`,
  "assistant.send": `Wyślij`,
  "assistant.showSource": `Pokaż źródło`,
  "assistant.simpleEnglish": `Prosty angielski`,
  "assistant.source": `Źródło`,
  "assistant.starter1": `Jakie są trzy części parlamentu?`,
  "assistant.starter2": `Wyjaśnij w prosty sposób Kartę`,
  "assistant.starter3": `Kto reprezentuje króla w Kanadzie?`,
  "assistant.starter4": `Co obejmuje test wiedzy?`,
  "assistant.suggestedQuestions": `Sugerowane pytania`,
  "assistant.thinking": `Myślenie…`,
  "assistant.title": `Asystent naukowy`,
  "assistant.tryAgain": `Spróbuj ponownie`,
  "assistant.tryAsking": `Spróbuj zapytać:`,
  "assistant.vocabularyLabel": `Słownictwo:`,
  "assistant.whyItMatters": `Dlaczego ma to znaczenie dla testu`,
  "auth.account": `Account`,
  "auth.checkEmail": `Check your email to confirm your account, then sign in.`,
  "auth.close": `Close`,
  "auth.codeLabel": `Verification code`,
  "auth.codeResent": `New code sent. Check your email.`,
  "auth.codeSent": `Code sent! Check your email and enter the 6-digit code.`,
  "auth.createAccount": `Create account`,
  "auth.dataDeletedMsg": `Your progress and profile data were deleted.`,
  "auth.deleteConfirm": `Tap again to permanently delete`,
  "auth.deleteData": `Delete my data`,
  "auth.email": `Email`,
  "auth.haveAccount": `Already have an account?`,
  "auth.mfaCodeLabel": `Authenticator code`,
  "auth.mfaDisable": `Disable 2FA`,
  "auth.mfaDisabledMsg": `Two-factor authentication is now OFF.`,
  "auth.mfaEnable": `Enable 2FA`,
  "auth.mfaEnabledMsg": `Two-factor authentication is now ON for your account.`,
  "auth.mfaPendingWarn": `2FA code still needed to finish signing in.`,
  "auth.mfaPrompt": `This account uses 2FA — enter the code from your authenticator app.`,
  "auth.mfaScanHint": `Scan this QR code with your authenticator app (Google Authenticator, Authy, 1Password…), then enter the 6-digit code it shows.`,
  "auth.mfaSetupTitle": `Set up two-factor authentication`,
  "auth.mfaSubtitle": `Enter the 6-digit code from your authenticator app.`,
  "auth.mfaTitle": `Two-factor authentication`,
  "auth.noAccount": `Don't have an account?`,
  "auth.password": `Password`,
  "auth.passwordHint": `At least 6 characters`,
  "auth.privacy": `Privacy`,
  "auth.privacyNote": `Your email and progress are private — only you can see them.`,
  "auth.resendCode": `Resend code`,
  "auth.security": `Security`,
  "auth.signIn": `Sign in`,
  "auth.signOut": `Sign out`,
  "auth.signUp": `Sign up`,
  "auth.subtitle": `Save your progress across devices. Your data stays private.`,
  "auth.title": `Account`,
  "auth.verify": `Verify`,
  "auth.verifyCodeSubtitle": `We sent a 6-digit code to your email. Enter it below to finish signing up.`,
  "auth.verifyCodeTitle": `Enter your code`,
  "auth.working": `Please wait…`,
  "bookmarks.continueStudying": `Kontynuuj naukę`,
  "bookmarks.empty": `Nie ma jeszcze żadnych zakładek. Kliknij gwiazdkę przy dowolnym pytaniu, aby zapisać je do sprawdzenia.`,
  "bookmarks.emptyQuestions": `Nic jeszcze nie zostało zapisane. Kliknij ☆ na pytaniu próbnym.`,
  "bookmarks.emptySections": `Nic jeszcze nie zostało zapisane. Dotknij ☆ podczas czytania sekcji.`,
  "bookmarks.remove": `Usuń`,
  "bookmarks.savedForReview": `zapisane do przeglądu`,
  "bookmarks.savedQuestions": `Zapisane pytania ({n})`,
  "bookmarks.savedSections": `Zapisane sekcje ({n})`,
  "bookmarks.search": `Wyszukaj zakładki…`,
  "bookmarks.title": `Zakładki`,
  "cards.answered": `Odpowiedziano`,
  "cards.bookmarks": `zapisane do przeglądu`,
  "cards.bookmarksLabel": `Zakładki`,
  "cards.continueLearning": `Kontynuuj naukę`,
  "cards.correct": `Poprawne`,
  "cards.dailyGoal": `{done}/{total} questions today`,
  "cards.dailyGoalLabel": `Codzienny cel`,
  "cards.dailyGoalTitle": `Daily goal`,
  "cards.mockExam.subtitle": `Czasowy · 20 pytań`,
  "cards.mockExam.title": `Próbny egzamin`,
  "cards.officialInfo.button": `Otwórz canada.ca`,
  "cards.officialInfo.subtitle": `Oficjalne szczegóły można znaleźć na stronie canada.ca`,
  "cards.officialInfo.title": `Oficjalne informacje`,
  "cards.progress": `Postęp`,
  "cards.progressDetails": `Szczegóły`,
  "cards.recentlyStudied": `Niedawno studiował`,
  "cards.sections": `Sekcje`,
  "cards.studyAssistant.subtitle": `Zapytaj o cokolwiek na temat materiału do nauki`,
  "cards.studyAssistant.title": `Asystent naukowy`,
  "cards.todaysRecommendation": `Dzisiejsza rekomendacja`,
  "cards.verifiedSource.subtext": `Treść sprawdzona w oparciu o oficjalne źródła. Niezależna pomoc naukowa — niepowiązana ani niezatwierdzona przez rząd Kanady ani IRCC.`,
  "cards.verifiedSource.title": `Sprawdzone źródło`,
  "common.back": `Powrót`,
  "common.cancel": `Anuluj`,
  "common.close": `Zamknij`,
  "common.continue": `Kontynuuj`,
  "common.done": `Gotowe`,
  "common.emptyBookmarks": `Nic jeszcze nie zostało zapisane`,
  "common.emptyRecentlyStudied": `Nic jeszcze nie zostało przestudiowane — wybierz temat, od którego chcesz zacząć.`,
  "common.loading": `Ładowanie…`,
  "common.next": `Następny`,
  "common.of": `z`,
  "common.previous": `Poprzedni`,
  "common.retry": `Spróbuj ponownie`,
  "common.save": `Zapisz`,
  "exam.allTopics": `Wszystkie tematy`,
  "exam.answeredCount": `{n} odpowiedział`,
  "exam.autosaveNote": `Twoje odpowiedzi są zapisywane na bieżąco, więc zamknięcie aplikacji nie spowoduje utraty postępów.`,
  "exam.cancel": `Anuluj`,
  "exam.confirm": `Potwierdź`,
  "exam.confirmEnd": `{n} pytań pozostało bez odpowiedzi i zostanie oznaczonych jako nieprawidłowe.`,
  "exam.confirmEndTitle": `Zakończyć egzamin?`,
  "exam.endExamEarly": `Zakończ egzamin wcześniej`,
  "exam.examDisclaimer": `Ten wynik odzwierciedla tylko przykładowe pytania tej aplikacji.`,
  "exam.finishExam": `Zakończ egzamin`,
  "exam.newExam": `Nowy egzamin`,
  "exam.noMistakes": `Żadnych błędów – doskonały wynik!`,
  "exam.pastAttempts": `Wcześniejsze próby`,
  "exam.questionAriaLabel": `Question {n}`,
  "exam.questionCount": `Liczba pytań`,
  "exam.questionOf": `Pytanie {n} z {total}`,
  "exam.questionPalette": `Pytania`,
  "exam.questionsOption": `{n} pytań`,
  "exam.resultsTitle": `Twój wynik`,
  "exam.reviewMistakes": `Przejrzyj swoje błędy ({n})`,
  "exam.scoreLine": `{correct} of {total} correct`,
  "exam.seeProgress": `Zobacz postęp`,
  "exam.setupDescription": `Jest to symulacja ćwiczeń zbudowana na podstawie pytań badawczych tej aplikacji. Nie jest to oficjalny test i nie przewiduje wyniku.`,
  "exam.setupTitle": `Skonfiguruj egzamin próbny`,
  "exam.simulationNote": `Symulacja ćwiczeń · nieoficjalne`,
  "exam.startExam": `Rozpocznij egzamin`,
  "exam.timeLeft": `Pozostał czas`,
  "exam.timedLabel": `na czas`,
  "exam.timedToggle": `Czasowy (90 sekund na pytanie)`,
  "exam.title": `Próbny egzamin`,
  "exam.topicFilter": `Temat`,
  "exam.untimedLabel": `nieograniczony`,
  "footer.disclaimer": `Citizen Prep to niezależna pomoc naukowa. Nie jest powiązany ani nie jest wspierany przez rząd Kanady lub IRCC. Nie może to zagwarantować pozytywnego wyniku.`,
  "header.appName": `Przygotowanie Obywatela`,
  "header.tagline": `Niezależne narzędzie do nauki · Nieoficjalne`,
  "hero.sectionsProgress": `{done} of {total} sections · {percent}% complete`,
  "hero.subtitle": `Niezależne narzędzie do nauki · Angielski i francuski · konto nie jest potrzebne`,
  "hero.title": `Przygotuj się do testu na obywatelstwo`,
  "nav.exam": `Egzamin`,
  "nav.home": `Dom`,
  "nav.practice": `Ćwicz`,
  "nav.progress": `Postęp`,
  "nav.topics": `Tematy`,
  "practice.allLevels": `Wszystkie poziomy`,
  "practice.allTopics": `Wszystkie tematy`,
  "practice.askAiAbout": `Zapytaj AI o to pytanie`,
  "practice.bookmarkQuestion": `Pytanie z zakładką`,
  "practice.bookmarked": `Dodane do zakładek`,
  "practice.checkAnswer": `Sprawdź odpowiedź`,
  "practice.correct": `Poprawne`,
  "practice.demoContent": `Treść demonstracyjna`,
  "practice.difficulty": `Trudność`,
  "practice.easy": `Łatwe`,
  "practice.explanation": `Wyjaśnienie`,
  "practice.filters": `Filtry`,
  "practice.hard": `Ciężko`,
  "practice.incorrect": `Niezupełnie`,
  "practice.medium": `Średni`,
  "practice.nextQuestion": `Następne pytanie`,
  "practice.questionCounter": `Pytanie ćwiczeniowe {n} z {total}`,
  "practice.reportIssue": `Zgłoś problem`,
  "practice.title": `Ćwicz`,
  "practice.topicFilter": `Temat`,
  "practice.tryAgain": `Spróbuj ponownie`,
  "progress.accuracy": `Dokładność`,
  "progress.clearProgressDesc": `Spowoduje to usunięcie Twoich odpowiedzi, ukończeń, zakładek i historii egzaminów z tego urządzenia. Nie można tego cofnąć.`,
  "progress.clearProgressLabel": `Wyczyść cały postęp nauki`,
  "progress.confirmClear": `Tak, wyczyść wszystko`,
  "progress.dailyGoal": `Codzienny cel`,
  "progress.details": `Szczegóły`,
  "progress.examHistory": `Historia egzaminu`,
  "progress.noExams": `Nie zdano jeszcze żadnych egzaminów.`,
  "progress.noWrongAnswers": `W tej chwili nie ma błędnych odpowiedzi do sprawdzenia.`,
  "progress.overview": `Przegląd`,
  "progress.perTopic": `Według tematu`,
  "progress.questionsAnswered": `Odpowiedzi na pytania`,
  "progress.reset": `Zresetuj`,
  "progress.retryTopic": `Spróbuj ponownie poruszyć ten temat`,
  "progress.sectionsDone": `Sekcje ukończone`,
  "progress.suggestedNext": `Suggested next: {topic}`,
  "progress.title": `Postęp`,
  "progress.topicCompletion": `Zakończenie tematu`,
  "report.detailsPlaceholder": `Powiedz nam więcej (opcjonalnie)`,
  "report.incorrectAnswer": `Niepoprawna odpowiedź`,
  "report.outdatedInfo": `Nieaktualne informacje`,
  "report.submit": `Prześlij raport`,
  "report.technicalIssue": `Problem techniczny`,
  "report.thanks": `Dziękujemy — raporty są przechowywane lokalnie na tym urządzeniu.`,
  "report.translationProblem": `Problem z tłumaczeniem`,
  "report.unclearExplanation": `Wyjaśnienie peu claire`,
  "settings.about": `O tej aplikacji`,
  "settings.appInterfaceLanguage": `Język interfejsu aplikacji`,
  "settings.clearProgress": `Wyraźny postęp`,
  "settings.clearProgressConfirm": `Czy jesteś pewien? Spowoduje to usunięcie wszystkich Twoich postępów.`,
  "settings.interfaceDescription": `Menu, przyciski i nawigacja.`,
  "settings.language": `Język`,
  "settings.machineNote": `Treści przetłumaczone maszynowo nie zostały sprawdzone przez weryfikatora. Nic tutaj nie jest oznaczone jako sprawdzone, chyba że faktycznie zostało sprawdzone.`,
  "settings.machineTranslatedBadge": `Tłumaczenie maszynowe`,
  "settings.manageProgress": `Zarządzaj swoimi danymi o postępie`,
  "settings.notAvailable": `Jeszcze niedostępne`,
  "settings.officialGuideLink": `Oficjalny przewodnik po nauce`,
  "settings.officialTestLink": `Oficjalne informacje dotyczące testu na obywatelstwo`,
  "settings.privacy": `Prywatność`,
  "settings.privacyText": `Twoje odpowiedzi, zakładki i ustawienia są przechowywane tylko na tym urządzeniu. Żadne konto nie jest potrzebne. Pytania, które zadajesz asystentowi, są wysyłane do usługi AI w celu wygenerowania odpowiedzi.`,
  "settings.reviewedBadge": `Recenzja`,
  "settings.studyContentLanguage": `Studiuj język treści`,
  "settings.studyDescription": `Nauka tekstu i objaśnień. Możesz czytać w jednym języku, nawigując w innym.`,
  "settings.textSize": `Rozmiar tekstu`,
  "settings.title": `Ustawienia`,
  "topics.askAssistant": `Zapytaj asystenta o tę sekcję`,
  "topics.bookmarkSection": `Sekcja zakładek`,
  "topics.bookmarkedSection": `Dodane do zakładek`,
  "topics.completed": `Ukończono`,
  "topics.continueLearningCard": `Kontynuuj naukę`,
  "topics.demoSourceNote": `Oryginalne przykładowe pytanie — nie jest to oficjalne pytanie egzaminacyjne`,
  "topics.lastVerified": `Ostatnia zweryfikowana {date}`,
  "topics.markComplete": `Oznacz jako ukończone`,
  "topics.markIncomplete": `Oznacz jako niekompletne`,
  "topics.minRead": `{n} min czytania`,
  "topics.next": `Następny`,
  "topics.openOfficialPage": `Otwórz oficjalną stronę`,
  "topics.paraphrasedSourceNote": `Parafraza z oficjalnych materiałów`,
  "topics.practiceTopic": `Poćwicz ten temat`,
  "topics.previous": `Poprzedni`,
  "topics.reportIssue": `Zgłoś problem`,
  "topics.reviewedOn": `reviewed {date}`,
  "topics.reviewedTranslation": `Recenzowane tłumaczenie`,
  "topics.section": `Sekcja`,
  "topics.sections": `sekcje`,
  "topics.source": `Źródło`,
  "topics.sourcesDescription": `Tekst badania jest parafrazą z przewodnika rządu Kanady dotyczącego studiów nad obywatelstwem i sprawdzony we wskazanych datach. Pytania praktyczne są badane na podstawie oficjalnego przewodnika po studiach.`,
  "topics.sourcesHeading": `Źródła treści i daty recenzji`,
  "topics.studyLanguageLabel": `Studiuj język treści`,
  "topics.title": `Tematyka studiów`,
  "topics.vocabulary": `Słownictwo`,
};
