// UI strings for 'pt' — chunk of strings.generated.ts. DO NOT EDIT BY HAND.
import type { StringKey } from "../strings.generated";

export const pt: Record<StringKey, string> = {
  "actions.askAi": `Pergunte à IA`,
  "actions.mockExam": `Exame simulado`,
  "actions.practice": `Pratique`,
  "actions.quickActions": `Quick actions`,
  "actions.study": `Estudo`,
  "assistant.aiEyebrow": `Assistente de estudo de IA`,
  "assistant.answerLanguage": `Idioma de resposta`,
  "assistant.charLimit": `{n} caracteres restantes`,
  "assistant.checkingMaterial": `Verificando o material de estudo…`,
  "assistant.clearChat": `Limpar bate-papo`,
  "assistant.copied": `Copiado`,
  "assistant.copy": `Copiar`,
  "assistant.description": `As respostas são escritas pela IA usando apenas o material de estudo deste aplicativo, com as fontes mostradas. A IA ainda pode cometer erros – verifique detalhes importantes nas páginas oficiais do Governo do Canadá. Não é aconselhamento jurídico ou de imigração.`,
  "assistant.enFrancais": `Em francês`,
  "assistant.error": `Algo deu errado. Por favor, tente novamente.`,
  "assistant.fromAppContent": `Do conteúdo aprovado do aplicativo`,
  "assistant.groundedBadge": `Baseado na fonte`,
  "assistant.helpful": `Útil`,
  "assistant.inputPlaceholder": `Faça uma pergunta sobre a cidadania canadense…`,
  "assistant.myAppLanguage": `Idioma do meu aplicativo`,
  "assistant.notCovered": `Não coberto - consulte a página oficial`,
  "assistant.notHelpful": `Não é útil`,
  "assistant.openAssistant": `Assistente de estudo aberto`,
  "assistant.openLink": `Assistente aberto`,
  "assistant.practiceThis": `Pratique isso`,
  "assistant.questionAriaLabel": `Sua pergunta`,
  "assistant.reportIncorrect": `Informar uma resposta incorreta`,
  "assistant.send": `Enviar`,
  "assistant.showSource": `Mostrar fonte`,
  "assistant.simpleEnglish": `Inglês simples`,
  "assistant.source": `Fonte`,
  "assistant.starter1": `Quais são as três partes do Parlamento?`,
  "assistant.starter2": `Explique a Carta de forma simples`,
  "assistant.starter3": `Quem representa o Rei no Canadá?`,
  "assistant.starter4": `O que o teste de conhecimento cobre?`,
  "assistant.suggestedQuestions": `Perguntas sugeridas`,
  "assistant.thinking": `Pensando…`,
  "assistant.title": `Assistente de estudo`,
  "assistant.tryAgain": `Tente novamente`,
  "assistant.tryAsking": `Experimente perguntar:`,
  "assistant.vocabularyLabel": `Vocabulário:`,
  "assistant.whyItMatters": `Por que isso é importante para o teste`,
  "bookmarks.continueStudying": `Continuar estudando`,
  "bookmarks.empty": `Ainda não há favoritos. Toque na estrela em qualquer pergunta para salvá-la para revisão.`,
  "bookmarks.emptyQuestions": `Nada salvo ainda. Toque em ☆ em uma questão prática.`,
  "bookmarks.emptySections": `Nada salvo ainda. Toque em ☆ enquanto lê uma seção.`,
  "bookmarks.remove": `Remover`,
  "bookmarks.savedForReview": `salvo para revisão`,
  "bookmarks.savedQuestions": `Perguntas salvas ({n})`,
  "bookmarks.savedSections": `Seções salvas ({n})`,
  "bookmarks.search": `Pesquisar favoritos…`,
  "bookmarks.title": `Marcadores`,
  "cards.answered": `Respondido`,
  "cards.bookmarks": `salvo para revisão`,
  "cards.bookmarksLabel": `Marcadores`,
  "cards.continueLearning": `Continuar aprendendo`,
  "cards.correct": `Correto`,
  "cards.dailyGoal": `{done}/{total} questions today`,
  "cards.dailyGoalLabel": `Meta diária`,
  "cards.dailyGoalTitle": `Daily goal`,
  "cards.mockExam.subtitle": `Cronometrado · 20 perguntas`,
  "cards.mockExam.title": `Exame simulado`,
  "cards.officialInfo.button": `Abra canada.ca`,
  "cards.officialInfo.subtitle": `Visite canada.ca para detalhes oficiais`,
  "cards.officialInfo.title": `Informação oficial`,
  "cards.progress": `Progresso`,
  "cards.progressDetails": `Detalhes`,
  "cards.recentlyStudied": `Estudado recentemente`,
  "cards.sections": `Seções`,
  "cards.studyAssistant.subtitle": `Pergunte qualquer coisa sobre o material de estudo`,
  "cards.studyAssistant.title": `Assistente de estudo`,
  "cards.todaysRecommendation": `Recomendação de hoje`,
  "cards.verifiedSource.subtext": `Conteúdo verificado em fontes oficiais. Auxílio de estudo independente - não afiliado ou endossado pelo Governo do Canadá ou IRCC.`,
  "cards.verifiedSource.title": `Fonte verificada`,
  "common.back": `Voltar`,
  "common.cancel": `Cancelar`,
  "common.close": `Fechar`,
  "common.continue": `Continuar`,
  "common.done": `Concluído`,
  "common.emptyBookmarks": `Nada salvo ainda`,
  "common.emptyRecentlyStudied": `Nada estudado ainda – escolha um tópico para começar.`,
  "common.loading": `Carregando…`,
  "common.next": `Próximo`,
  "common.of": `de`,
  "common.previous": `Anterior`,
  "common.retry": `Tentar novamente`,
  "common.save": `Salvar`,
  "exam.allTopics": `Todos os tópicos`,
  "exam.answeredCount": `{n} respondeu`,
  "exam.autosaveNote": `Suas respostas são salvas conforme você avança, portanto, fechar o aplicativo não perderá seu progresso.`,
  "exam.cancel": `Cancelar`,
  "exam.confirm": `Confirmar`,
  "exam.confirmEnd": `{n} perguntas não foram respondidas e serão marcadas como incorretas.`,
  "exam.confirmEndTitle": `Fim do exame?`,
  "exam.endExamEarly": `Terminar o exame mais cedo`,
  "exam.examDisclaimer": `Esta pontuação reflete apenas os exemplos de perguntas deste aplicativo.`,
  "exam.finishExam": `Concluir exame`,
  "exam.newExam": `Novo exame`,
  "exam.noMistakes": `Sem erros – pontuação perfeita!`,
  "exam.pastAttempts": `Tentativas anteriores`,
  "exam.questionAriaLabel": `Pergunta {n}`,
  "exam.questionCount": `Número de perguntas`,
  "exam.questionOf": `Pergunta {n} de {total}`,
  "exam.questionPalette": `Perguntas`,
  "exam.questionsOption": `{n} perguntas`,
  "exam.resultsTitle": `Sua pontuação`,
  "exam.reviewMistakes": `Revise seus erros ({n})`,
  "exam.scoreLine": `{correct} of {total} correct`,
  "exam.seeProgress": `Veja o progresso`,
  "exam.setupDescription": `Esta é uma simulação prática construída a partir das questões de estudo deste aplicativo. Não é o teste oficial e não prevê o seu resultado.`,
  "exam.setupTitle": `Configure seu exame simulado`,
  "exam.simulationNote": `Simulação prática · não oficial`,
  "exam.startExam": `Iniciar exame`,
  "exam.timeLeft": `Tempo restante`,
  "exam.timedLabel": `cronometrado`,
  "exam.timedToggle": `Cronometrado (90 segundos por pergunta)`,
  "exam.title": `Exame simulado`,
  "exam.topicFilter": `Tópico`,
  "exam.untimedLabel": `indeterminado`,
  "footer.disclaimer": `Citizen Prep é um auxílio de estudo independente. Não afiliado ou endossado pelo Governo do Canadá ou IRCC. Não pode garantir um resultado aprovado.`,
  "header.appName": `Preparação Cidadã`,
  "header.tagline": `Ferramenta de estudo independente · Não oficial`,
  "hero.sectionsProgress": `{done} of {total} sections · {percent}% complete`,
  "hero.subtitle": `Ferramenta de estudo independente · Inglês e Francês · não é necessária conta`,
  "hero.title": `Prepare-se para o seu teste de cidadania`,
  "nav.exam": `Exame`,
  "nav.home": `Página inicial`,
  "nav.practice": `Pratique`,
  "nav.progress": `Progresso`,
  "nav.topics": `Tópicos`,
  "practice.allLevels": `Todos os níveis`,
  "practice.allTopics": `Todos os tópicos`,
  "practice.askAiAbout": `Pergunte à IA sobre esta questão`,
  "practice.bookmarkQuestion": `Pergunta de marcador`,
  "practice.bookmarked": `Marcado como favorito`,
  "practice.checkAnswer": `Verifique a resposta`,
  "practice.correct": `Correto`,
  "practice.demoContent": `Conteúdo de demonstração`,
  "practice.difficulty": `Dificuldade`,
  "practice.easy": `Fácil`,
  "practice.explanation": `Explicação`,
  "practice.filters": `Filtros`,
  "practice.hard": `Difícil`,
  "practice.incorrect": `Não exatamente`,
  "practice.medium": `Médio`,
  "practice.nextQuestion": `Próxima pergunta`,
  "practice.questionCounter": `Questão prática {n} de {total}`,
  "practice.reportIssue": `Informar um problema`,
  "practice.title": `Pratique`,
  "practice.topicFilter": `Tópico`,
  "practice.tryAgain": `Tente novamente`,
  "progress.accuracy": `Precisão`,
  "progress.clearProgressDesc": `Isso exclui suas respostas, conclusões, favoritos e histórico de exames deste dispositivo. Não pode ser desfeito.`,
  "progress.clearProgressLabel": `Limpar todo o progresso do estudo`,
  "progress.confirmClear": `Sim, limpe tudo`,
  "progress.dailyGoal": `Meta diária`,
  "progress.details": `Detalhes`,
  "progress.examHistory": `Histórico do exame`,
  "progress.noExams": `Nenhum exame realizado ainda.`,
  "progress.noWrongAnswers": `Não há respostas incorretas para revisar agora.`,
  "progress.overview": `Visão geral`,
  "progress.perTopic": `Por tópico`,
  "progress.questionsAnswered": `Perguntas respondidas`,
  "progress.reset": `Redefinir`,
  "progress.retryTopic": `Tente novamente este tópico`,
  "progress.sectionsDone": `Seções concluídas`,
  "progress.suggestedNext": `Próximo sugerido: {topic}`,
  "progress.title": `Progresso`,
  "progress.topicCompletion": `Conclusão do tópico`,
  "report.detailsPlaceholder": `Conte-nos mais (opcional)`,
  "report.incorrectAnswer": `Resposta incorreta`,
  "report.outdatedInfo": `Informações desatualizadas`,
  "report.submit": `Enviar relatório`,
  "report.technicalIssue": `Problema técnico`,
  "report.thanks": `Obrigado – os relatórios são armazenados localmente neste dispositivo.`,
  "report.translationProblem": `Problema de tradução`,
  "report.unclearExplanation": `Explicação peu claire`,
  "settings.about": `Sobre este aplicativo`,
  "settings.appInterfaceLanguage": `Idioma da interface do aplicativo`,
  "settings.clearProgress": `Progresso claro`,
  "settings.clearProgressConfirm": `Você tem certeza? Isso excluirá todo o seu progresso.`,
  "settings.interfaceDescription": `Menus, botões e navegação.`,
  "settings.language": `Idioma`,
  "settings.machineNote": `O conteúdo traduzido automaticamente não foi verificado por um revisor humano. Nada aqui é rotulado como revisado, a menos que tenha sido realmente revisado.`,
  "settings.machineTranslatedBadge": `Traduzido automaticamente`,
  "settings.manageProgress": `Gerencie seus dados de progresso`,
  "settings.notAvailable": `Ainda não disponível`,
  "settings.officialGuideLink": `Guia de estudo oficial`,
  "settings.officialTestLink": `Informações oficiais do teste de cidadania`,
  "settings.privacy": `Privacidade`,
  "settings.privacyText": `Suas respostas, favoritos e configurações são armazenados somente neste dispositivo. Nenhuma conta é necessária. As perguntas que você faz ao assistente de estudo são enviadas a um serviço de IA para gerar respostas.`,
  "settings.reviewedBadge": `Revisado`,
  "settings.studyContentLanguage": `Estude a linguagem do conteúdo`,
  "settings.studyDescription": `Texto de aprendizagem e explicações. Você pode ler em um idioma enquanto navega em outro.`,
  "settings.textSize": `Tamanho do texto`,
  "settings.title": `Configurações`,
  "topics.askAssistant": `Pergunte ao assistente sobre esta seção`,
  "topics.bookmarkSection": `Seção de favoritos`,
  "topics.bookmarkedSection": `Marcado como favorito`,
  "topics.completed": `Concluído`,
  "topics.continueLearningCard": `Continuar aprendendo`,
  "topics.demoSourceNote": `Exemplo de pergunta original – não é uma pergunta oficial do exame`,
  "topics.lastVerified": `Última verificação em {date}`,
  "topics.markComplete": `Marcar como concluído`,
  "topics.markIncomplete": `Marcar como incompleto`,
  "topics.minRead": `{n} minutos de leitura`,
  "topics.next": `Próximo`,
  "topics.openOfficialPage": `Abrir página oficial`,
  "topics.paraphrasedSourceNote": `Parafraseado de material oficial`,
  "topics.practiceTopic": `Pratique este tópico`,
  "topics.previous": `Anterior`,
  "topics.reportIssue": `Informar um problema`,
  "topics.reviewedOn": `reviewed {date}`,
  "topics.reviewedTranslation": `Tradução revisada`,
  "topics.section": `Seção`,
  "topics.sections": `seções`,
  "topics.source": `Fonte`,
  "topics.sourcesDescription": `O texto do estudo aqui foi parafraseado do guia de estudo de cidadania do Governo do Canadá e revisado nas datas mostradas. As questões práticas são pesquisadas no guia de estudo oficial.`,
  "topics.sourcesHeading": `Fontes de conteúdo e datas de revisão`,
  "topics.studyLanguageLabel": `Estude a linguagem do conteúdo`,
  "topics.title": `Tópicos de estudo`,
  "topics.vocabulary": `Vocabulário`,
};
