// UI strings for 'ro' — chunk of strings.generated.ts. DO NOT EDIT BY HAND.
import type { StringKey } from "../strings.generated";

export const ro: Record<StringKey, string> = {
  "actions.askAi": `Întrebați AI`,
  "actions.mockExam": `Examen simulat`,
  "actions.practice": `Practică`,
  "actions.quickActions": `Quick actions`,
  "actions.study": `Studiază`,
  "assistant.aiEyebrow": `Asistent de studiu AI`,
  "assistant.answerLanguage": `Limbajul răspunsurilor`,
  "assistant.charLimit": `Au rămas {n} caractere`,
  "assistant.checkingMaterial": `Verificarea materialului de studiu...`,
  "assistant.clearChat": `Ștergeți chatul`,
  "assistant.copied": `Copiat`,
  "assistant.copy": `Copiere`,
  "assistant.description": `Răspunsurile sunt scrise de AI folosind doar materialul de studiu al acestei aplicații, cu sursele afișate. Inteligența artificială poate face în continuare greșeli - verificați detaliile importante pe paginile oficiale ale Guvernului Canadei. Nu sunt sfaturi legale sau de imigrare.`,
  "assistant.enFrancais": `En français`,
  "assistant.error": `Ceva a mers prost. Vă rugăm să încercați din nou.`,
  "assistant.fromAppContent": `Din conținutul aplicației aprobat`,
  "assistant.groundedBadge": `Impământat la sursă`,
  "assistant.helpful": `Util`,
  "assistant.inputPlaceholder": `Pune o întrebare despre cetățenia canadiană...`,
  "assistant.myAppLanguage": `Limba aplicației mele`,
  "assistant.notCovered": `Nu este acoperit - vezi pagina oficială`,
  "assistant.notHelpful": `Nu este de ajutor`,
  "assistant.openAssistant": `Asistent de studiu deschis`,
  "assistant.openLink": `Deschide asistentul`,
  "assistant.practiceThis": `Practică asta`,
  "assistant.questionAriaLabel": `Întrebarea ta`,
  "assistant.reportIncorrect": `Raportați un răspuns incorect`,
  "assistant.send": `Trimite`,
  "assistant.showSource": `Afișează sursa`,
  "assistant.simpleEnglish": `Engleză simplă`,
  "assistant.source": `Sursă`,
  "assistant.starter1": `Care sunt cele trei părți ale Parlamentului?`,
  "assistant.starter2": `Explicați simplu Carta`,
  "assistant.starter3": `Cine îl reprezintă pe Rege în Canada?`,
  "assistant.starter4": `Ce acoperă testul de cunoștințe?`,
  "assistant.suggestedQuestions": `Întrebări sugerate`,
  "assistant.thinking": `Gândind…`,
  "assistant.title": `Asistent de studiu`,
  "assistant.tryAgain": `Încercați din nou`,
  "assistant.tryAsking": `Incearca sa intrebi:`,
  "assistant.vocabularyLabel": `Vocabular:`,
  "assistant.whyItMatters": `De ce contează pentru test`,
  "bookmarks.continueStudying": `Continuă să studiezi`,
  "bookmarks.empty": `Încă nu există marcaje. Atingeți steaua pentru orice întrebare pentru a o salva pentru examinare.`,
  "bookmarks.emptyQuestions": `Nimic salvat încă. Atingeți ☆ pe o întrebare de practică.`,
  "bookmarks.emptySections": `Nimic salvat încă. Atingeți ☆ în timp ce citiți o secțiune.`,
  "bookmarks.remove": `Eliminați`,
  "bookmarks.savedForReview": `salvat pentru revizuire`,
  "bookmarks.savedQuestions": `Întrebări salvate ({n})`,
  "bookmarks.savedSections": `Secțiuni salvate ({n})`,
  "bookmarks.search": `Căutați marcaje...`,
  "bookmarks.title": `Marcaje`,
  "cards.answered": `Răspuns`,
  "cards.bookmarks": `salvat pentru revizuire`,
  "cards.bookmarksLabel": `Marcaje`,
  "cards.continueLearning": `Continuați să învățați`,
  "cards.correct": `Corect`,
  "cards.dailyGoal": `{done}/{total} questions today`,
  "cards.dailyGoalLabel": `Scopul zilnic`,
  "cards.dailyGoalTitle": `Daily goal`,
  "cards.mockExam.subtitle": `Cronometrat · 20 de întrebări`,
  "cards.mockExam.title": `Examen simulat`,
  "cards.officialInfo.button": `Deschide canada.ca`,
  "cards.officialInfo.subtitle": `Vizitați canada.ca pentru detalii oficiale`,
  "cards.officialInfo.title": `Informații oficiale`,
  "cards.progress": `Progres`,
  "cards.progressDetails": `Detalii`,
  "cards.recentlyStudied": `Studiat recent`,
  "cards.sections": `Secțiuni`,
  "cards.studyAssistant.subtitle": `Întrebați orice despre materialul de studiu`,
  "cards.studyAssistant.title": `Asistent de studiu`,
  "cards.todaysRecommendation": `Recomandarea de azi`,
  "cards.verifiedSource.subtext": `Conținut verificat față de surse oficiale. Ajutor de studiu independent - nu este afiliat sau aprobat de Guvernul Canadei sau IRCC.`,
  "cards.verifiedSource.title": `Sursa verificata`,
  "common.back": `Înapoi`,
  "common.cancel": `Anulează`,
  "common.close": `Închide`,
  "common.continue": `Continuă`,
  "common.done": `Gata`,
  "common.emptyBookmarks": `Nimic salvat încă`,
  "common.emptyRecentlyStudied": `Nimic studiat încă - alegeți un subiect pentru a începe.`,
  "common.loading": `Se încarcă…`,
  "common.next": `În continuare`,
  "common.of": `de`,
  "common.previous": `Anterior`,
  "common.retry": `Reîncercați`,
  "common.save": `Salvați`,
  "exam.allTopics": `Toate subiectele`,
  "exam.answeredCount": `{n} a răspuns`,
  "exam.autosaveNote": `Răspunsurile dvs. sunt salvate pe măsură ce mergeți, așa că închiderea aplicației nu vă va pierde progresul.`,
  "exam.cancel": `Anulează`,
  "exam.confirm": `Confirmați`,
  "exam.confirmEnd": `{n} întrebări nu au răspuns și vor fi marcate incorecte.`,
  "exam.confirmEndTitle": `Încheierea examenului?`,
  "exam.endExamEarly": `Încheiați examenul devreme`,
  "exam.examDisclaimer": `Acest scor reflectă numai întrebările eșantion ale acestei aplicații.`,
  "exam.finishExam": `Termină examenul`,
  "exam.newExam": `Nou examen`,
  "exam.noMistakes": `Fără greșeli - scor perfect!`,
  "exam.pastAttempts": `Încercările anterioare`,
  "exam.questionAriaLabel": `întrebare {n}`,
  "exam.questionCount": `Numărul de întrebări`,
  "exam.questionOf": `Întrebarea {n} din {total}`,
  "exam.questionPalette": `Întrebări`,
  "exam.questionsOption": `{n} întrebări`,
  "exam.resultsTitle": `Scorul tău`,
  "exam.reviewMistakes": `Examinați-vă greșelile ({n})`,
  "exam.scoreLine": `{correct} of {total} correct`,
  "exam.seeProgress": `Vezi progresul`,
  "exam.setupDescription": `Aceasta este o simulare de practică construită din întrebările de studiu ale acestei aplicații. Nu este testul oficial și nu vă prezice rezultatul.`,
  "exam.setupTitle": `Configurați-vă simularea examenului`,
  "exam.simulationNote": `Simulare practică · nu este oficială`,
  "exam.startExam": `Începe examenul`,
  "exam.timeLeft": `Timp rămas`,
  "exam.timedLabel": `cronometrat`,
  "exam.timedToggle": `Cronometrat (90 de secunde per întrebare)`,
  "exam.title": `Examen simulat`,
  "exam.topicFilter": `Subiect`,
  "exam.untimedLabel": `necronometrat`,
  "footer.disclaimer": `Citizen Prep este un ajutor de studiu independent. Nu este afiliat sau susținut de Guvernul Canadei sau IRCC. Nu poate garanta un rezultat trecător.`,
  "header.appName": `Citizen Prep`,
  "header.tagline": `Instrument de studiu independent · Nu este oficial`,
  "hero.sectionsProgress": `{done} of {total} sections · {percent}% complete`,
  "hero.subtitle": `Instrument de studiu independent · engleză și franceză · nu este nevoie de cont`,
  "hero.title": `Pregătiți-vă pentru testul de cetățenie`,
  "nav.exam": `Examen`,
  "nav.home": `Acasă`,
  "nav.practice": `Practică`,
  "nav.progress": `Progres`,
  "nav.topics": `Subiecte`,
  "practice.allLevels": `Toate nivelurile`,
  "practice.allTopics": `Toate subiectele`,
  "practice.askAiAbout": `Întrebați AI despre această întrebare`,
  "practice.bookmarkQuestion": `Întrebare marcată`,
  "practice.bookmarked": `Marcat`,
  "practice.checkAnswer": `Verificați răspunsul`,
  "practice.correct": `Corect`,
  "practice.demoContent": `Conținut demonstrativ`,
  "practice.difficulty": `Dificultate`,
  "practice.easy": `Ușor`,
  "practice.explanation": `Explicație`,
  "practice.filters": `Filtre`,
  "practice.hard": `Greu`,
  "practice.incorrect": `Nu chiar`,
  "practice.medium": `Mediu`,
  "practice.nextQuestion": `Următoarea întrebare`,
  "practice.questionCounter": `Practică întrebarea {n} din {total}`,
  "practice.reportIssue": `Raportați o problemă`,
  "practice.title": `Practică`,
  "practice.topicFilter": `Subiect`,
  "practice.tryAgain": `Încercați din nou`,
  "progress.accuracy": `Precizie`,
  "progress.clearProgressDesc": `Aceasta vă șterge răspunsurile, completările, marcajele și istoricul examenelor de pe acest dispozitiv. Nu poate fi anulat.`,
  "progress.clearProgressLabel": `Ștergeți tot progresul studiului`,
  "progress.confirmClear": `Da, șterge totul`,
  "progress.dailyGoal": `Scopul zilnic`,
  "progress.details": `Detalii`,
  "progress.examHistory": `Istoricul examenelor`,
  "progress.noExams": `Încă nu au fost luate examene.`,
  "progress.noWrongAnswers": `Nu există răspunsuri incorecte de revizuit în acest moment.`,
  "progress.overview": `Prezentare generală`,
  "progress.perTopic": `Pe subiect`,
  "progress.questionsAnswered": `La întrebări au răspuns`,
  "progress.reset": `Resetați`,
  "progress.retryTopic": `Reîncercați acest subiect`,
  "progress.sectionsDone": `Secțiuni finalizate`,
  "progress.suggestedNext": `Sugerat în continuare: {topic}`,
  "progress.title": `Progres`,
  "progress.topicCompletion": `Completarea subiectului`,
  "report.detailsPlaceholder": `Spune-ne mai multe (opțional)`,
  "report.incorrectAnswer": `Răspuns incorect`,
  "report.outdatedInfo": `Informații învechite`,
  "report.submit": `Trimiteți raportul`,
  "report.technicalIssue": `Problemă tehnică`,
  "report.thanks": `Mulțumesc — rapoartele sunt stocate local pe acest dispozitiv.`,
  "report.translationProblem": `Problema traducerii`,
  "report.unclearExplanation": `Explication peu claire`,
  "settings.about": `Despre această aplicație`,
  "settings.appInterfaceLanguage": `Limba interfeței aplicației`,
  "settings.clearProgress": `Progres clar`,
  "settings.clearProgressConfirm": `esti sigur? Acest lucru va șterge tot progresul dvs.`,
  "settings.interfaceDescription": `Meniuri, butoane și navigare.`,
  "settings.language": `Limba`,
  "settings.machineNote": `Conținutul tradus automat nu a fost verificat de un evaluator uman. Nimic de aici nu este etichetat ca revizuit decât dacă a fost examinat efectiv.`,
  "settings.machineTranslatedBadge": `Tradus automat`,
  "settings.manageProgress": `Gestionați-vă datele de progres`,
  "settings.notAvailable": `Nu este încă disponibil`,
  "settings.officialGuideLink": `Ghid oficial de studiu`,
  "settings.officialTestLink": `Informații oficiale despre testul de cetățenie`,
  "settings.privacy": `Confidențialitate`,
  "settings.privacyText": `Răspunsurile, marcajele și setările dvs. sunt stocate numai pe acest dispozitiv. Nu este nevoie de cont. Întrebările pe care le adresați asistentului de studiu sunt trimise unui serviciu AI pentru a genera răspunsuri.`,
  "settings.reviewedBadge": `Revizuit`,
  "settings.studyContentLanguage": `Studiați limbajul conținutului`,
  "settings.studyDescription": `Învățare text și explicații. Puteți citi într-o limbă în timp ce navigați în alta.`,
  "settings.textSize": `Dimensiunea textului`,
  "settings.title": `Setări`,
  "topics.askAssistant": `Întrebați asistentul despre această secțiune`,
  "topics.bookmarkSection": `Secțiunea de marcaje`,
  "topics.bookmarkedSection": `Marcat`,
  "topics.completed": `Terminat`,
  "topics.continueLearningCard": `Continuați să învățați`,
  "topics.demoSourceNote": `Exemplu de întrebare originală — nu este o întrebare oficială de examen`,
  "topics.lastVerified": `Ultima verificare {date}`,
  "topics.markComplete": `Marcați ca fiind complet`,
  "topics.markIncomplete": `Marcați ca incomplet`,
  "topics.minRead": `{n} minute de citit`,
  "topics.next": `În continuare`,
  "topics.openOfficialPage": `Deschide pagina oficială`,
  "topics.paraphrasedSourceNote": `Parafrazată din material oficial`,
  "topics.practiceTopic": `Practicați acest subiect`,
  "topics.previous": `Anterior`,
  "topics.reportIssue": `Raportați o problemă`,
  "topics.reviewedOn": `revizuit {date}`,
  "topics.reviewedTranslation": `Traducere revizuită`,
  "topics.section": `Sectiunea`,
  "topics.sections": `secțiuni`,
  "topics.source": `Sursă`,
  "topics.sourcesDescription": `Textul de studiu aici este parafrazat din ghidul de studiu al cetățeniei Guvernului Canadei și revizuit la datele afișate. Întrebările practice sunt cercetate din ghidul oficial de studiu.`,
  "topics.sourcesHeading": `Surse de conținut și date de revizuire`,
  "topics.studyLanguageLabel": `Studiați limbajul conținutului`,
  "topics.title": `Subiecte de studiu`,
  "topics.vocabulary": `Vocabular`,
};
