// UI strings for 'ru' — chunk of strings.generated.ts. DO NOT EDIT BY HAND.
import type { StringKey } from "../strings.generated";

export const ru: Record<StringKey, string> = {
  "actions.askAi": `Спросите ИИ`,
  "actions.mockExam": `Пробный экзамен`,
  "actions.practice": `Практика`,
  "actions.quickActions": `Quick actions`,
  "actions.study": `Исследование`,
  "assistant.aiEyebrow": `Ассистент по изучению ИИ`,
  "assistant.answerLanguage": `Язык ответа`,
  "assistant.charLimit": `осталось {n} символов`,
  "assistant.checkingMaterial": `Проверка учебного материала…`,
  "assistant.clearChat": `Очистить чат`,
  "assistant.copied": `Скопировано`,
  "assistant.copy": `Копировать`,
  "assistant.description": `Ответы пишутся ИИ с использованием только учебных материалов этого приложения с указанием источников. ИИ все еще может совершать ошибки — проверяйте важную информацию на официальных страницах правительства Канады. Не юридические или иммиграционные консультации.`,
  "assistant.enFrancais": `На французском языке`,
  "assistant.error": `Что-то пошло не так. Пожалуйста, попробуйте еще раз.`,
  "assistant.fromAppContent": `Из одобренного контента приложения`,
  "assistant.groundedBadge": `Заземленный источник`,
  "assistant.helpful": `Полезно`,
  "assistant.inputPlaceholder": `Задайте вопрос о канадском гражданстве…`,
  "assistant.myAppLanguage": `Мой язык приложения`,
  "assistant.notCovered": `Не покрывается — см. официальную страницу`,
  "assistant.notHelpful": `Бесполезно`,
  "assistant.openAssistant": `Открытый помощник по учебе`,
  "assistant.openLink": `Открытый помощник`,
  "assistant.practiceThis": `Практикуйте это`,
  "assistant.questionAriaLabel": `Ваш вопрос`,
  "assistant.reportIncorrect": `Сообщить о неправильном ответе`,
  "assistant.send": `Отправить`,
  "assistant.showSource": `Показать источник`,
  "assistant.simpleEnglish": `Простой английский`,
  "assistant.source": `Источник`,
  "assistant.starter1": `Каковы три части парламента?`,
  "assistant.starter2": `Объясните Устав просто`,
  "assistant.starter3": `Кто представляет короля в Канаде?`,
  "assistant.starter4": `Что включает в себя проверка знаний?`,
  "assistant.suggestedQuestions": `Предлагаемые вопросы`,
  "assistant.thinking": `Думая…`,
  "assistant.title": `Ассистент по учебе`,
  "assistant.tryAgain": `Попробуйте еще раз`,
  "assistant.tryAsking": `Попробуйте спросить:`,
  "assistant.vocabularyLabel": `Словарь:`,
  "assistant.whyItMatters": `Почему это важно для теста`,
  "auth.account": `Account`,
  "auth.checkEmail": `Check your email to confirm your account, then sign in.`,
  "auth.close": `Close`,
  "auth.codeLabel": `Verification code`,
  "auth.codeResent": `New code sent. Check your email.`,
  "auth.codeSent": `Code sent! Check your email and enter the 6-digit code.`,
  "auth.createAccount": `Create account`,
  "auth.dataDeletedMsg": `Your progress and profile data were deleted.`,
  "auth.deleteConfirm": `Tap again to permanently delete`,
  "auth.deleteData": `Delete my data`,
  "auth.email": `Email`,
  "auth.haveAccount": `Already have an account?`,
  "auth.mfaCodeLabel": `Authenticator code`,
  "auth.mfaDisable": `Disable 2FA`,
  "auth.mfaDisabledMsg": `Two-factor authentication is now OFF.`,
  "auth.mfaEnable": `Enable 2FA`,
  "auth.mfaEnabledMsg": `Two-factor authentication is now ON for your account.`,
  "auth.mfaPendingWarn": `2FA code still needed to finish signing in.`,
  "auth.mfaPrompt": `This account uses 2FA — enter the code from your authenticator app.`,
  "auth.mfaScanHint": `Scan this QR code with your authenticator app (Google Authenticator, Authy, 1Password…), then enter the 6-digit code it shows.`,
  "auth.mfaSetupTitle": `Set up two-factor authentication`,
  "auth.mfaSubtitle": `Enter the 6-digit code from your authenticator app.`,
  "auth.mfaTitle": `Two-factor authentication`,
  "auth.noAccount": `Don't have an account?`,
  "auth.password": `Password`,
  "auth.passwordHint": `At least 6 characters`,
  "auth.privacy": `Privacy`,
  "auth.privacyNote": `Your email and progress are private — only you can see them.`,
  "auth.resendCode": `Resend code`,
  "auth.security": `Security`,
  "auth.signIn": `Sign in`,
  "auth.signOut": `Sign out`,
  "auth.signUp": `Sign up`,
  "auth.subtitle": `Save your progress across devices. Your data stays private.`,
  "auth.title": `Account`,
  "auth.verify": `Verify`,
  "auth.verifyCodeSubtitle": `We sent a 6-digit code to your email. Enter it below to finish signing up.`,
  "auth.verifyCodeTitle": `Enter your code`,
  "auth.working": `Please wait…`,
  "bookmarks.continueStudying": `Продолжить обучение`,
  "bookmarks.empty": `Закладок пока нет. Нажмите звездочку на любом вопросе, чтобы сохранить его для рассмотрения.`,
  "bookmarks.emptyQuestions": `Еще ничего не сохранилось. Нажмите ☆ на практическом вопросе.`,
  "bookmarks.emptySections": `Еще ничего не сохранилось. Нажмите ☆ во время чтения раздела.`,
  "bookmarks.remove": `Удалить`,
  "bookmarks.savedForReview": `сохранено для просмотра`,
  "bookmarks.savedQuestions": `Сохраненные вопросы ({n})`,
  "bookmarks.savedSections": `Сохраненные разделы ({n})`,
  "bookmarks.search": `Искать в закладках…`,
  "bookmarks.title": `Закладки`,
  "cards.answered": `Ответил`,
  "cards.bookmarks": `сохранено для просмотра`,
  "cards.bookmarksLabel": `Закладки`,
  "cards.continueLearning": `Продолжить обучение`,
  "cards.correct": `Правильно`,
  "cards.dailyGoal": `{done}/{total} вопросов сегодня`,
  "cards.dailyGoalLabel": `Ежедневная цель`,
  "cards.dailyGoalTitle": `Daily goal`,
  "cards.mockExam.subtitle": `На время · 20 вопросов`,
  "cards.mockExam.title": `Пробный экзамен`,
  "cards.officialInfo.button": `Открыть сайт Canada.ca`,
  "cards.officialInfo.subtitle": `Посетите canada.ca для получения официальной информации.`,
  "cards.officialInfo.title": `Официальная информация`,
  "cards.progress": `Прогресс`,
  "cards.progressDetails": `Подробности`,
  "cards.recentlyStudied": `Недавно изучал`,
  "cards.sections": `Разделы`,
  "cards.studyAssistant.subtitle": `Спросите что-нибудь об учебном материале`,
  "cards.studyAssistant.title": `Ассистент по учебе`,
  "cards.todaysRecommendation": `Сегодняшняя рекомендация`,
  "cards.verifiedSource.subtext": `Содержимое проверено на соответствие официальным источникам. Независимая помощь в обучении, не связанная и не одобренная правительством Канады или IRCC.`,
  "cards.verifiedSource.title": `Проверенный источник`,
  "common.back": `Назад`,
  "common.cancel": `Отмена`,
  "common.close": `Закрыть`,
  "common.continue": `Продолжить`,
  "common.done": `Готово`,
  "common.emptyBookmarks": `Еще ничего не сохранено`,
  "common.emptyRecentlyStudied": `Пока ничего не изучено — выберите тему, чтобы начать.`,
  "common.loading": `Загрузка…`,
  "common.next": `Далее`,
  "common.of": `из`,
  "common.previous": `Предыдущий`,
  "common.retry": `Повторить попытку`,
  "common.save": `Сохранить`,
  "exam.allTopics": `Все темы`,
  "exam.answeredCount": `{n} ответил`,
  "exam.autosaveNote": `Ваши ответы сохраняются по мере прохождения, поэтому закрытие приложения не приведет к потере вашего прогресса.`,
  "exam.cancel": `Отмена`,
  "exam.confirm": `Подтвердить`,
  "exam.confirmEnd": `{n} вопросов остались без ответа и будут помечены как неправильные.`,
  "exam.confirmEndTitle": `Закончить экзамен?`,
  "exam.endExamEarly": `Завершить экзамен раньше времени`,
  "exam.examDisclaimer": `Эта оценка отражает только примеры вопросов этого приложения.`,
  "exam.finishExam": `Завершить экзамен`,
  "exam.newExam": `Новый экзамен`,
  "exam.noMistakes": `Никаких ошибок — высший балл!`,
  "exam.pastAttempts": `Прошлые попытки`,
  "exam.questionAriaLabel": `Вопрос {n}`,
  "exam.questionCount": `Количество вопросов`,
  "exam.questionOf": `Вопрос {n} из {total}`,
  "exam.questionPalette": `Вопросы`,
  "exam.questionsOption": `{n} вопросов`,
  "exam.resultsTitle": `Ваш результат`,
  "exam.reviewMistakes": `Просмотрите свои ошибки ({n})`,
  "exam.scoreLine": `{correct} of {total} correct`,
  "exam.seeProgress": `Посмотреть прогресс`,
  "exam.setupDescription": `Это практическое моделирование, построенное на основе учебных вопросов этого приложения. Это не официальный тест, и он не позволяет предсказать ваш результат.`,
  "exam.setupTitle": `Настройте пробный экзамен`,
  "exam.simulationNote": `Практика моделирования · не официально`,
  "exam.startExam": `Начать экзамен`,
  "exam.timeLeft": `Осталось времени`,
  "exam.timedLabel": `рассчитанный по времени`,
  "exam.timedToggle": `На время (90 секунд на вопрос)`,
  "exam.title": `Пробный экзамен`,
  "exam.topicFilter": `Тема`,
  "exam.untimedLabel": `безвременный`,
  "footer.disclaimer": `Citizen Prep — это независимое учебное пособие. Не связан и не одобрен правительством Канады или IRCC. Это не может гарантировать проходной результат.`,
  "header.appName": `Гражданская подготовка`,
  "header.tagline": `Независимый инструмент обучения · Неофициально`,
  "hero.sectionsProgress": `{done} of {total} sections · {percent}% complete`,
  "hero.subtitle": `Независимый инструмент обучения · английский и французский · учетная запись не требуется`,
  "hero.title": `Подготовьтесь к тесту на гражданство`,
  "nav.exam": `Экзамен`,
  "nav.home": `Главная`,
  "nav.practice": `Практика`,
  "nav.progress": `Прогресс`,
  "nav.topics": `Темы`,
  "practice.allLevels": `Все уровни`,
  "practice.allTopics": `Все темы`,
  "practice.askAiAbout": `Задайте этот вопрос ИИ`,
  "practice.bookmarkQuestion": `Добавить в закладки вопрос`,
  "practice.bookmarked": `В закладках`,
  "practice.checkAnswer": `Проверить ответ`,
  "practice.correct": `Правильно`,
  "practice.demoContent": `Демо-контент`,
  "practice.difficulty": `Сложность`,
  "practice.easy": `Легко`,
  "practice.explanation": `Объяснение`,
  "practice.filters": `Фильтры`,
  "practice.hard": `Жесткий`,
  "practice.incorrect": `Не совсем`,
  "practice.medium": `Средний`,
  "practice.nextQuestion": `Следующий вопрос`,
  "practice.questionCounter": `Практический вопрос {n} из {total}`,
  "practice.reportIssue": `Сообщить о проблеме`,
  "practice.title": `Практика`,
  "practice.topicFilter": `Тема`,
  "practice.tryAgain": `Попробуйте еще раз`,
  "progress.accuracy": `Точность`,
  "progress.clearProgressDesc": `При этом ваши ответы, задания, закладки и история экзаменов будут удалены с этого устройства. Это невозможно отменить.`,
  "progress.clearProgressLabel": `Очистить весь прогресс обучения`,
  "progress.confirmClear": `Да, очистить все`,
  "progress.dailyGoal": `Ежедневная цель`,
  "progress.details": `Подробности`,
  "progress.examHistory": `История экзаменов`,
  "progress.noExams": `Экзамены еще не сданы.`,
  "progress.noWrongAnswers": `Нет неправильных ответов для проверки прямо сейчас.`,
  "progress.overview": `Обзор`,
  "progress.perTopic": `По теме`,
  "progress.questionsAnswered": `Ответы на вопросы`,
  "progress.reset": `Сброс`,
  "progress.retryTopic": `Повторить эту тему`,
  "progress.sectionsDone": `Разделы завершены`,
  "progress.suggestedNext": `Предлагается следующим: {topic}`,
  "progress.title": `Прогресс`,
  "progress.topicCompletion": `Завершение темы`,
  "report.detailsPlaceholder": `Расскажите нам больше (необязательно)`,
  "report.incorrectAnswer": `Неправильный ответ`,
  "report.outdatedInfo": `Устаревшая информация`,
  "report.submit": `Отправить отчет`,
  "report.technicalIssue": `Техническая проблема`,
  "report.thanks": `Спасибо — отчеты хранятся локально на этом устройстве.`,
  "report.translationProblem": `Проблема перевода`,
  "report.unclearExplanation": `Объяснение: Peu Claire`,
  "settings.about": `Об этом приложении`,
  "settings.appInterfaceLanguage": `Язык интерфейса приложения`,
  "settings.clearProgress": `Очевидный прогресс`,
  "settings.clearProgressConfirm": `Вы уверены? Это удалит весь ваш прогресс.`,
  "settings.interfaceDescription": `Меню, кнопки и навигация.`,
  "settings.language": `Язык`,
  "settings.machineNote": `Машинно переведенный контент не проверялся человеком-рецензентом. Ничто здесь не помечается как проверенное, если оно действительно не было рассмотрено.`,
  "settings.machineTranslatedBadge": `Машинный перевод`,
  "settings.manageProgress": `Управляйте данными о своем прогрессе`,
  "settings.notAvailable": `Пока не доступен`,
  "settings.officialGuideLink": `Официальное учебное пособие`,
  "settings.officialTestLink": `Официальная информация о тесте на гражданство`,
  "settings.privacy": `Конфиденциальность`,
  "settings.privacyText": `Ваши ответы, закладки и настройки хранятся только на этом устройстве. Никакой учетной записи не требуется. Вопросы, которые вы задаете ассистенту, отправляются в службу искусственного интеллекта для генерации ответов.`,
  "settings.reviewedBadge": `Рассмотрено`,
  "settings.studyContentLanguage": `Изучите язык контента`,
  "settings.studyDescription": `Учебный текст и пояснения. Вы можете читать на одном языке, одновременно перемещаясь на другом.`,
  "settings.textSize": `Размер текста`,
  "settings.title": `Настройки`,
  "topics.askAssistant": `Спросите ассистента об этом разделе`,
  "topics.bookmarkSection": `Раздел закладок`,
  "topics.bookmarkedSection": `В закладках`,
  "topics.completed": `Завершено`,
  "topics.continueLearningCard": `Продолжить обучение`,
  "topics.demoSourceNote": `Исходный образец вопроса — не официальный экзаменационный вопрос`,
  "topics.lastVerified": `Последняя проверка: {date}`,
  "topics.markComplete": `Отметить как завершенное`,
  "topics.markIncomplete": `Отметить как незавершенное`,
  "topics.minRead": `{n} минут чтения`,
  "topics.next": `Далее`,
  "topics.openOfficialPage": `Открыть официальную страницу`,
  "topics.paraphrasedSourceNote": `Перефразировано из официального материала`,
  "topics.practiceTopic": `Практикуйте эту тему`,
  "topics.previous": `Предыдущий`,
  "topics.reportIssue": `Сообщить о проблеме`,
  "topics.reviewedOn": `reviewed {date}`,
  "topics.reviewedTranslation": `Отзыв о переводе`,
  "topics.section": `Раздел`,
  "topics.sections": `разделы`,
  "topics.source": `Источник`,
  "topics.sourcesDescription": `Текст исследования здесь перефразирован из учебного пособия по гражданству правительства Канады и проверен в указанные даты. Практические вопросы изучаются на основе официального учебного пособия.`,
  "topics.sourcesHeading": `Источники контента и даты проверки`,
  "topics.studyLanguageLabel": `Изучите язык контента`,
  "topics.title": `Темы исследования`,
  "topics.vocabulary": `Словарь`,
};
