// UI strings for 'sk' — chunk of strings.generated.ts. DO NOT EDIT BY HAND.
import type { StringKey } from "../strings.generated";

export const sk: Record<StringKey, string> = {
  "actions.askAi": `Opýtajte sa AI`,
  "actions.mockExam": `Falošná skúška`,
  "actions.practice": `Prax`,
  "actions.quickActions": `Quick actions`,
  "actions.study": `Štúdium`,
  "assistant.aiEyebrow": `Študijný asistent AI`,
  "assistant.answerLanguage": `Jazyk odpovede`,
  "assistant.charLimit": `Zostáva {n} znakov`,
  "assistant.checkingMaterial": `Kontroluje sa študijný materiál…`,
  "assistant.clearChat": `Vymazať chat`,
  "assistant.copied": `Skopírované`,
  "assistant.copy": `Kopírovať`,
  "assistant.description": `Odpovede píše AI iba s použitím študijného materiálu tejto aplikácie so zobrazenými zdrojmi. Umelá inteligencia môže stále robiť chyby – skontrolujte dôležité podrobnosti na oficiálnych stránkach kanadskej vlády. Nie právne alebo imigračné poradenstvo.`,
  "assistant.enFrancais": `En français`,
  "assistant.error": `Niečo sa pokazilo. Skúste to znova.`,
  "assistant.fromAppContent": `Zo schváleného obsahu aplikácie`,
  "assistant.groundedBadge": `Zdroj uzemnený`,
  "assistant.helpful": `Užitočné`,
  "assistant.inputPlaceholder": `Opýtajte sa na kanadské občianstvo...`,
  "assistant.myAppLanguage": `Jazyk mojej aplikácie`,
  "assistant.notCovered": `Nepokryté – pozri oficiálnu stránku`,
  "assistant.notHelpful": `Nie je užitočné`,
  "assistant.openAssistant": `Otvorená študijná referentka`,
  "assistant.openLink": `Otvorte asistenta`,
  "assistant.practiceThis": `Toto si nacvičte`,
  "assistant.questionAriaLabel": `Vaša otázka`,
  "assistant.reportIncorrect": `Nahláste nesprávnu odpoveď`,
  "assistant.send": `Odoslať`,
  "assistant.showSource": `Zobraziť zdroj`,
  "assistant.simpleEnglish": `Jednoduchá angličtina`,
  "assistant.source": `Zdroj`,
  "assistant.starter1": `Aké sú tri časti parlamentu?`,
  "assistant.starter2": `Vysvetlite chartu jednoducho`,
  "assistant.starter3": `Kto zastupuje kráľa v Kanade?`,
  "assistant.starter4": `Čo zahŕňa vedomostný test?`,
  "assistant.suggestedQuestions": `Navrhované otázky`,
  "assistant.thinking": `Premýšľanie…`,
  "assistant.title": `Študijný asistent`,
  "assistant.tryAgain": `Skúste to znova`,
  "assistant.tryAsking": `Skúste sa opýtať:`,
  "assistant.vocabularyLabel": `Slovná zásoba:`,
  "assistant.whyItMatters": `Prečo je to dôležité pre test`,
  "auth.account": `Account`,
  "auth.checkEmail": `Check your email to confirm your account, then sign in.`,
  "auth.close": `Close`,
  "auth.codeLabel": `Verification code`,
  "auth.codeResent": `New code sent. Check your email.`,
  "auth.codeSent": `Code sent! Check your email and enter the 6-digit code.`,
  "auth.createAccount": `Create account`,
  "auth.dataDeletedMsg": `Your progress and profile data were deleted.`,
  "auth.deleteConfirm": `Tap again to permanently delete`,
  "auth.deleteData": `Delete my data`,
  "auth.email": `Email`,
  "auth.haveAccount": `Already have an account?`,
  "auth.mfaCodeLabel": `Authenticator code`,
  "auth.mfaDisable": `Disable 2FA`,
  "auth.mfaDisabledMsg": `Two-factor authentication is now OFF.`,
  "auth.mfaEnable": `Enable 2FA`,
  "auth.mfaEnabledMsg": `Two-factor authentication is now ON for your account.`,
  "auth.mfaPendingWarn": `2FA code still needed to finish signing in.`,
  "auth.mfaPrompt": `This account uses 2FA — enter the code from your authenticator app.`,
  "auth.mfaScanHint": `Scan this QR code with your authenticator app (Google Authenticator, Authy, 1Password…), then enter the 6-digit code it shows.`,
  "auth.mfaSetupTitle": `Set up two-factor authentication`,
  "auth.mfaSubtitle": `Enter the 6-digit code from your authenticator app.`,
  "auth.mfaTitle": `Two-factor authentication`,
  "auth.noAccount": `Don't have an account?`,
  "auth.password": `Password`,
  "auth.passwordHint": `At least 6 characters`,
  "auth.privacy": `Privacy`,
  "auth.privacyNote": `Your email and progress are private — only you can see them.`,
  "auth.resendCode": `Resend code`,
  "auth.security": `Security`,
  "auth.signIn": `Sign in`,
  "auth.signOut": `Sign out`,
  "auth.signUp": `Sign up`,
  "auth.subtitle": `Save your progress across devices. Your data stays private.`,
  "auth.title": `Account`,
  "auth.verify": `Verify`,
  "auth.verifyCodeSubtitle": `We sent a 6-digit code to your email. Enter it below to finish signing up.`,
  "auth.verifyCodeTitle": `Enter your code`,
  "auth.working": `Please wait…`,
  "bookmarks.continueStudying": `Pokračujte v štúdiu`,
  "bookmarks.empty": `Zatiaľ žiadne záložky. Klepnutím na hviezdičku na ľubovoľnú otázku ju uložíte na kontrolu.`,
  "bookmarks.emptyQuestions": `Zatiaľ nie je nič uložené. Klepnite na ☆ na cvičnej otázke.`,
  "bookmarks.emptySections": `Zatiaľ nie je nič uložené. Počas čítania časti klepnite na ☆.`,
  "bookmarks.remove": `Odstrániť`,
  "bookmarks.savedForReview": `uložené na kontrolu`,
  "bookmarks.savedQuestions": `Uložené otázky ({n})`,
  "bookmarks.savedSections": `Uložené sekcie ({n})`,
  "bookmarks.search": `Hľadať v záložkách…`,
  "bookmarks.title": `Záložky`,
  "cards.answered": `Odpovedané`,
  "cards.bookmarks": `uložené na kontrolu`,
  "cards.bookmarksLabel": `Záložky`,
  "cards.continueLearning": `Pokračujte v učení`,
  "cards.correct": `Správne`,
  "cards.dailyGoal": `{done}/{total} otázok dnes`,
  "cards.dailyGoalLabel": `Denný cieľ`,
  "cards.dailyGoalTitle": `Daily goal`,
  "cards.mockExam.subtitle": `Načasované · 20 otázok`,
  "cards.mockExam.title": `Falošná skúška`,
  "cards.officialInfo.button": `Otvorte canada.ca`,
  "cards.officialInfo.subtitle": `Oficiálne podrobnosti nájdete na stránke canada.ca`,
  "cards.officialInfo.title": `Oficiálne informácie`,
  "cards.progress": `Pokrok`,
  "cards.progressDetails": `Podrobnosti`,
  "cards.recentlyStudied": `Nedávno študovaný`,
  "cards.sections": `Sekcie`,
  "cards.studyAssistant.subtitle": `Opýtajte sa na čokoľvek ohľadom študijného materiálu`,
  "cards.studyAssistant.title": `Študijný asistent`,
  "cards.todaysRecommendation": `Dnešné odporúčanie`,
  "cards.verifiedSource.subtext": `Obsah skontrolovaný podľa oficiálnych zdrojov. Nezávislá študijná pomôcka – nie je pridružená ani neschválená vládou Kanady ani IRCC.`,
  "cards.verifiedSource.title": `Overený zdroj`,
  "common.back": `Späť`,
  "common.cancel": `Zrušiť`,
  "common.close": `Zavrieť`,
  "common.continue": `Pokračovať`,
  "common.done": `Hotovo`,
  "common.emptyBookmarks": `Zatiaľ nie je nič uložené`,
  "common.emptyRecentlyStudied": `Zatiaľ sa nič neštudovalo – začnite výberom témy.`,
  "common.loading": `Načítava sa…`,
  "common.next": `Ďalej`,
  "common.of": `z`,
  "common.previous": `Predchádzajúce`,
  "common.retry": `Skúste to znova`,
  "common.save": `Uložiť`,
  "exam.allTopics": `Všetky témy`,
  "exam.answeredCount": `{n} odpovedal`,
  "exam.autosaveNote": `Vaše odpovede sa priebežne ukladajú, takže zatvorením aplikácie nestratíte svoj postup.`,
  "exam.cancel": `Zrušiť`,
  "exam.confirm": `Potvrďte`,
  "exam.confirmEnd": `Otázky ({n}) sú nezodpovedané a budú označené ako nesprávne.`,
  "exam.confirmEndTitle": `Ukončiť skúšku?`,
  "exam.endExamEarly": `Ukončite skúšku skôr`,
  "exam.examDisclaimer": `Toto skóre odráža iba vzorové otázky tejto aplikácie.`,
  "exam.finishExam": `Dokončiť skúšku`,
  "exam.newExam": `Nová skúška`,
  "exam.noMistakes": `Žiadne chyby – perfektné skóre!`,
  "exam.pastAttempts": `Minulé pokusy`,
  "exam.questionAriaLabel": `otázka {n}`,
  "exam.questionCount": `Počet otázok`,
  "exam.questionOf": `Otázka {n} z {total}`,
  "exam.questionPalette": `Otázky`,
  "exam.questionsOption": `{n} otázok`,
  "exam.resultsTitle": `Vaše skóre`,
  "exam.reviewMistakes": `Skontrolujte svoje chyby ({n})`,
  "exam.scoreLine": `{correct} z {total} správne`,
  "exam.seeProgress": `Pozrite si pokrok`,
  "exam.setupDescription": `Toto je cvičná simulácia postavená na študijných otázkach tejto aplikácie. Nie je to oficiálny test a nepredpovedá váš výsledok.`,
  "exam.setupTitle": `Nastavte si falošnú skúšku`,
  "exam.simulationNote": `Cvičná simulácia · neoficiálna`,
  "exam.startExam": `Začať skúšku`,
  "exam.timeLeft": `Zostal čas`,
  "exam.timedLabel": `načasované`,
  "exam.timedToggle": `Načasované (90 sekúnd na otázku)`,
  "exam.title": `Falošná skúška`,
  "exam.topicFilter": `Téma`,
  "exam.untimedLabel": `nenačasované`,
  "footer.disclaimer": `Citizen Prep je nezávislá študijná pomôcka. Nie je pridružené ani schválené vládou Kanady alebo IRCC. Nemôže zaručiť úspešný výsledok.`,
  "header.appName": `Občianska prípravka`,
  "header.tagline": `Nezávislý študijný nástroj · Nie je oficiálny`,
  "hero.sectionsProgress": `{done} of {total} sections · {percent}% complete`,
  "hero.subtitle": `Nezávislý študijný nástroj · Angličtina a francúzština · Nie je potrebný účet`,
  "hero.title": `Pripravte sa na skúšku občianstva`,
  "nav.exam": `Skúška`,
  "nav.home": `Domov`,
  "nav.practice": `Prax`,
  "nav.progress": `Pokrok`,
  "nav.topics": `Témy`,
  "practice.allLevels": `Všetky úrovne`,
  "practice.allTopics": `Všetky témy`,
  "practice.askAiAbout": `Opýtajte sa AI na túto otázku`,
  "practice.bookmarkQuestion": `Otázka na záložku`,
  "practice.bookmarked": `Záložka`,
  "practice.checkAnswer": `Skontrolujte odpoveď`,
  "practice.correct": `Správne`,
  "practice.demoContent": `Demo obsah`,
  "practice.difficulty": `Náročnosť`,
  "practice.easy": `Jednoduché`,
  "practice.explanation": `Vysvetlenie`,
  "practice.filters": `Filtre`,
  "practice.hard": `Ťažko`,
  "practice.incorrect": `Nie tak celkom`,
  "practice.medium": `Stredná`,
  "practice.nextQuestion": `Ďalšia otázka`,
  "practice.questionCounter": `Cvičná otázka {n} z {total}`,
  "practice.reportIssue": `Nahláste problém`,
  "practice.title": `Prax`,
  "practice.topicFilter": `Téma`,
  "practice.tryAgain": `Skúste to znova`,
  "progress.accuracy": `Presnosť`,
  "progress.clearProgressDesc": `Týmto sa z tohto zariadenia odstránia vaše odpovede, dokončenia, záložky a história skúšok. Nedá sa to vrátiť späť.`,
  "progress.clearProgressLabel": `Vymazať celý priebeh štúdia`,
  "progress.confirmClear": `Áno, vymazať všetko`,
  "progress.dailyGoal": `Denný cieľ`,
  "progress.details": `Podrobnosti`,
  "progress.examHistory": `História skúšok`,
  "progress.noExams": `Zatiaľ neboli vykonané žiadne skúšky.`,
  "progress.noWrongAnswers": `Momentálne nie sú žiadne nesprávne odpovede na kontrolu.`,
  "progress.overview": `Prehľad`,
  "progress.perTopic": `Podľa témy`,
  "progress.questionsAnswered": `Otázky zodpovedané`,
  "progress.reset": `Resetovať`,
  "progress.retryTopic": `Skúste túto tému znova`,
  "progress.sectionsDone": `Sekcie dokončené`,
  "progress.suggestedNext": `Navrhované ďalšie: {topic}`,
  "progress.title": `Pokrok`,
  "progress.topicCompletion": `Dokončenie témy`,
  "report.detailsPlaceholder": `Povedzte nám viac (voliteľné)`,
  "report.incorrectAnswer": `Nesprávna odpoveď`,
  "report.outdatedInfo": `Zastarané informácie`,
  "report.submit": `Odoslať správu`,
  "report.technicalIssue": `Technický problém`,
  "report.thanks": `Ďakujeme – prehľady sa ukladajú lokálne na tomto zariadení.`,
  "report.translationProblem": `Problém s prekladom`,
  "report.unclearExplanation": `Vysvetlenie peu claire`,
  "settings.about": `O tejto aplikácii`,
  "settings.appInterfaceLanguage": `Jazyk rozhrania aplikácie`,
  "settings.clearProgress": `Jasný pokrok`,
  "settings.clearProgressConfirm": `si si istý? Týmto sa odstráni celý váš postup.`,
  "settings.interfaceDescription": `Menu, tlačidlá a navigácia.`,
  "settings.language": `Jazyk`,
  "settings.machineNote": `Strojovo preložený obsah nebol skontrolovaný ľudským kontrolórom. Nič tu nie je označené ako skontrolované, pokiaľ to nebolo skutočne skontrolované.`,
  "settings.machineTranslatedBadge": `Strojovo preložené`,
  "settings.manageProgress": `Spravujte svoje údaje o pokroku`,
  "settings.notAvailable": `Zatiaľ nedostupné`,
  "settings.officialGuideLink": `Oficiálna študijná príručka`,
  "settings.officialTestLink": `Oficiálne informácie o teste občianstva`,
  "settings.privacy": `Ochrana osobných údajov`,
  "settings.privacyText": `Vaše odpovede, záložky a nastavenia sú uložené iba v tomto zariadení. Nie je potrebný žiadny účet. Otázky, ktoré položíte študijnej referentke, sa posielajú do služby AI, aby vygenerovala odpovede.`,
  "settings.reviewedBadge": `Skontrolované`,
  "settings.studyContentLanguage": `Študujte jazyk obsahu`,
  "settings.studyDescription": `Učebný text a vysvetlenia. Môžete čítať v jednom jazyku a navigovať v inom.`,
  "settings.textSize": `Veľkosť textu`,
  "settings.title": `Nastavenia`,
  "topics.askAssistant": `Opýtajte sa asistenta na túto časť`,
  "topics.bookmarkSection": `Sekcia záložiek`,
  "topics.bookmarkedSection": `Záložka`,
  "topics.completed": `Dokončené`,
  "topics.continueLearningCard": `Pokračujte v učení`,
  "topics.demoSourceNote": `Pôvodná vzorová otázka – nie oficiálna skúšobná otázka`,
  "topics.lastVerified": `Naposledy overené {date}`,
  "topics.markComplete": `Označiť ako dokončené`,
  "topics.markIncomplete": `Označiť ako nedokončené`,
  "topics.minRead": `čítanie {n} min`,
  "topics.next": `Ďalej`,
  "topics.openOfficialPage": `Otvorte oficiálnu stránku`,
  "topics.paraphrasedSourceNote": `Parafrázované z oficiálnych materiálov`,
  "topics.practiceTopic": `Precvičte si túto tému`,
  "topics.previous": `Predchádzajúce`,
  "topics.reportIssue": `Nahláste problém`,
  "topics.reviewedOn": `recenzovaný {date}`,
  "topics.reviewedTranslation": `Recenzovaný preklad`,
  "topics.section": `oddiel`,
  "topics.sections": `oddielov`,
  "topics.source": `Zdroj`,
  "topics.sourcesDescription": `Text štúdie je parafrázovaný zo študijnej príručky kanadskej vlády o občianstve a je skontrolovaný v uvedených dátumoch. Praktické otázky sú skúmané z oficiálneho študijného sprievodcu.`,
  "topics.sourcesHeading": `Zdroje obsahu a dátumy kontroly`,
  "topics.studyLanguageLabel": `Študujte jazyk obsahu`,
  "topics.title": `Študijné témy`,
  "topics.vocabulary": `Slovná zásoba`,
};
