// UI strings for 'sl' — chunk of strings.generated.ts. DO NOT EDIT BY HAND.
import type { StringKey } from "../strings.generated";

export const sl: Record<StringKey, string> = {
  "actions.askAi": `Vprašajte AI`,
  "actions.mockExam": `Probni izpit`,
  "actions.practice": `Vadite`,
  "actions.quickActions": `Quick actions`,
  "actions.study": `Študij`,
  "assistant.aiEyebrow": `Študijski asistent AI`,
  "assistant.answerLanguage": `Jezik odgovora`,
  "assistant.charLimit": `Še {n} znakov`,
  "assistant.checkingMaterial": `Preverjanje učne snovi …`,
  "assistant.clearChat": `Počisti klepet`,
  "assistant.copied": `Kopirano`,
  "assistant.copy": `Kopiraj`,
  "assistant.description": `Odgovore napiše umetna inteligenca samo z uporabo študijskega gradiva te aplikacije s prikazanimi viri. AI lahko še vedno dela napake - preverite pomembne podrobnosti na uradnih straneh kanadske vlade. Ne pravno ali imigracijsko svetovanje.`,
  "assistant.enFrancais": `En français`,
  "assistant.error": `Nekaj je šlo narobe. prosim poskusite ponovno`,
  "assistant.fromAppContent": `Iz odobrene vsebine aplikacije`,
  "assistant.groundedBadge": `Temelji na viru`,
  "assistant.helpful": `koristno`,
  "assistant.inputPlaceholder": `Postavite vprašanje o kanadskem državljanstvu ...`,
  "assistant.myAppLanguage": `Jezik moje aplikacije`,
  "assistant.notCovered": `Ni zajeto - glejte uradno stran`,
  "assistant.notHelpful": `Ni v pomoč`,
  "assistant.openAssistant": `Odprt študijski asistent`,
  "assistant.openLink": `Odpri pomočnika`,
  "assistant.practiceThis": `Vadite to`,
  "assistant.questionAriaLabel": `Vaše vprašanje`,
  "assistant.reportIncorrect": `Prijavite napačen odgovor`,
  "assistant.send": `Pošlji`,
  "assistant.showSource": `Prikaži vir`,
  "assistant.simpleEnglish": `Preprosta angleščina`,
  "assistant.source": `Vir`,
  "assistant.starter1": `Kateri so trije deli parlamenta?`,
  "assistant.starter2": `Listino preprosto razložite`,
  "assistant.starter3": `Kdo zastopa kralja v Kanadi?`,
  "assistant.starter4": `Kaj obsega preizkus znanja?`,
  "assistant.suggestedQuestions": `Predlagana vprašanja`,
  "assistant.thinking": `Razmišljam ...`,
  "assistant.title": `Študijski asistent`,
  "assistant.tryAgain": `poskusi ponovno`,
  "assistant.tryAsking": `Poskusite vprašati:`,
  "assistant.vocabularyLabel": `Besednjak:`,
  "assistant.whyItMatters": `Zakaj je to pomembno za test`,
  "auth.account": `Account`,
  "auth.checkEmail": `Check your email to confirm your account, then sign in.`,
  "auth.close": `Close`,
  "auth.codeLabel": `Verification code`,
  "auth.codeResent": `New code sent. Check your email.`,
  "auth.codeSent": `Code sent! Check your email and enter the 6-digit code.`,
  "auth.createAccount": `Create account`,
  "auth.dataDeletedMsg": `Your progress and profile data were deleted.`,
  "auth.deleteConfirm": `Tap again to permanently delete`,
  "auth.deleteData": `Delete my data`,
  "auth.email": `Email`,
  "auth.haveAccount": `Already have an account?`,
  "auth.mfaCodeLabel": `Authenticator code`,
  "auth.mfaDisable": `Disable 2FA`,
  "auth.mfaDisabledMsg": `Two-factor authentication is now OFF.`,
  "auth.mfaEnable": `Enable 2FA`,
  "auth.mfaEnabledMsg": `Two-factor authentication is now ON for your account.`,
  "auth.mfaPendingWarn": `2FA code still needed to finish signing in.`,
  "auth.mfaPrompt": `This account uses 2FA — enter the code from your authenticator app.`,
  "auth.mfaScanHint": `Scan this QR code with your authenticator app (Google Authenticator, Authy, 1Password…), then enter the 6-digit code it shows.`,
  "auth.mfaSetupTitle": `Set up two-factor authentication`,
  "auth.mfaSubtitle": `Enter the 6-digit code from your authenticator app.`,
  "auth.mfaTitle": `Two-factor authentication`,
  "auth.noAccount": `Don't have an account?`,
  "auth.password": `Password`,
  "auth.passwordHint": `At least 6 characters`,
  "auth.privacy": `Privacy`,
  "auth.privacyNote": `Your email and progress are private — only you can see them.`,
  "auth.resendCode": `Resend code`,
  "auth.security": `Security`,
  "auth.signIn": `Sign in`,
  "auth.signOut": `Sign out`,
  "auth.signUp": `Sign up`,
  "auth.subtitle": `Save your progress across devices. Your data stays private.`,
  "auth.title": `Account`,
  "auth.verify": `Verify`,
  "auth.verifyCodeSubtitle": `We sent a 6-digit code to your email. Enter it below to finish signing up.`,
  "auth.verifyCodeTitle": `Enter your code`,
  "auth.working": `Please wait…`,
  "bookmarks.continueStudying": `Nadaljujte s študijem`,
  "bookmarks.empty": `Zaznamkov še ni. Dotaknite se zvezdice na poljubnem vprašanju, da ga shranite za pregled.`,
  "bookmarks.emptyQuestions": `Nič še ni shranjenega. Dotaknite se ☆ na vprašanju za vadbo.`,
  "bookmarks.emptySections": `Nič še ni shranjenega. Med branjem razdelka tapnite ☆.`,
  "bookmarks.remove": `Odstrani`,
  "bookmarks.savedForReview": `shranjeno za pregled`,
  "bookmarks.savedQuestions": `Shranjena vprašanja ({n})`,
  "bookmarks.savedSections": `Shranjeni razdelki ({n})`,
  "bookmarks.search": `Išči med zaznamki ...`,
  "bookmarks.title": `Zaznamki`,
  "cards.answered": `Odgovoril`,
  "cards.bookmarks": `shranjeno za pregled`,
  "cards.bookmarksLabel": `Zaznamki`,
  "cards.continueLearning": `Nadaljujte z učenjem`,
  "cards.correct": `Pravilno`,
  "cards.dailyGoal": `{done}/{total} vprašanj danes`,
  "cards.dailyGoalLabel": `Dnevni cilj`,
  "cards.dailyGoalTitle": `Daily goal`,
  "cards.mockExam.subtitle": `Časovno · 20 vprašanj`,
  "cards.mockExam.title": `Probni izpit`,
  "cards.officialInfo.button": `Odprite canada.ca`,
  "cards.officialInfo.subtitle": `Za uradne podrobnosti obiščite canada.ca`,
  "cards.officialInfo.title": `Uradne informacije`,
  "cards.progress": `Napredek`,
  "cards.progressDetails": `Podrobnosti`,
  "cards.recentlyStudied": `Nedavno preučeno`,
  "cards.sections": `Oddelki`,
  "cards.studyAssistant.subtitle": `Vprašajte kar koli o študijskem gradivu`,
  "cards.studyAssistant.title": `Študijski asistent`,
  "cards.todaysRecommendation": `Današnje priporočilo`,
  "cards.verifiedSource.subtext": `Vsebina je bila preverjena z uradnimi viri. Neodvisna študijska pomoč — ni povezana ali potrjena s strani vlade Kanade ali IRCC.`,
  "cards.verifiedSource.title": `Preverjen vir`,
  "common.back": `Nazaj`,
  "common.cancel": `Prekliči`,
  "common.close": `Zapri`,
  "common.continue": `Nadaljuj`,
  "common.done": `Končano`,
  "common.emptyBookmarks": `Nič še ni shranjenega`,
  "common.emptyRecentlyStudied": `Nič še ni preučenega — za začetek izberite temo.`,
  "common.loading": `Nalaganje ...`,
  "common.next": `Naprej`,
  "common.of": `od`,
  "common.previous": `Prejšnja`,
  "common.retry": `Poskusite znova`,
  "common.save": `Shrani`,
  "exam.allTopics": `Vse teme`,
  "exam.answeredCount": `{n} je odgovoril`,
  "exam.autosaveNote": `Vaši odgovori se shranjujejo sproti, tako da z zapiranjem aplikacije ne izgubite napredka.`,
  "exam.cancel": `Prekliči`,
  "exam.confirm": `Potrdi`,
  "exam.confirmEnd": `{n} vprašanj je neodgovorjenih in bodo označena kot nepravilna.`,
  "exam.confirmEndTitle": `Konec izpita?`,
  "exam.endExamEarly": `Končaj izpit predčasno`,
  "exam.examDisclaimer": `Ta rezultat odraža samo vzorčna vprašanja te aplikacije.`,
  "exam.finishExam": `Končaj izpit`,
  "exam.newExam": `Nov izpit`,
  "exam.noMistakes": `Brez napak — popoln rezultat!`,
  "exam.pastAttempts": `Pretekli poskusi`,
  "exam.questionAriaLabel": `vprašanje {n}`,
  "exam.questionCount": `Število vprašanj`,
  "exam.questionOf": `Vprašanje {n} od {total}`,
  "exam.questionPalette": `Vprašanja`,
  "exam.questionsOption": `{n} vprašanj`,
  "exam.resultsTitle": `Vaš rezultat`,
  "exam.reviewMistakes": `Preglejte svoje napake ({n})`,
  "exam.scoreLine": `{correct} od {total} pravilnih`,
  "exam.seeProgress": `Glej napredek`,
  "exam.setupDescription": `To je simulacija prakse, zgrajena iz študijskih vprašanj te aplikacije. To ni uradni test in ne predvideva vašega rezultata.`,
  "exam.setupTitle": `Pripravite poskusni izpit`,
  "exam.simulationNote": `Simulacija vaje · ni uradno`,
  "exam.startExam": `Začni izpit`,
  "exam.timeLeft": `Preostal čas`,
  "exam.timedLabel": `tempirano`,
  "exam.timedToggle": `Odmerjeno (90 sekund na vprašanje)`,
  "exam.title": `Probni izpit`,
  "exam.topicFilter": `Tema`,
  "exam.untimedLabel": `netempirano`,
  "footer.disclaimer": `Citizen Prep je neodvisen študijski pripomoček. Ni povezan z vlado Kanade ali IRCC in jih ne podpira. Ne more zagotoviti prehodnega rezultata.`,
  "header.appName": `državljan Prep`,
  "header.tagline": `Orodje za neodvisno študijo · Ni uradno`,
  "hero.sectionsProgress": `{done} of {total} sections · {percent}% complete`,
  "hero.subtitle": `Orodje za neodvisno učenje · Angleščina in francoščina · Račun ni potreben`,
  "hero.title": `Pripravite se na izpit za državljanstvo`,
  "nav.exam": `Izpit`,
  "nav.home": `domov`,
  "nav.practice": `Vadite`,
  "nav.progress": `Napredek`,
  "nav.topics": `Teme`,
  "practice.allLevels": `Vse stopnje`,
  "practice.allTopics": `Vse teme`,
  "practice.askAiAbout": `O tem vprašanju vprašajte AI`,
  "practice.bookmarkQuestion": `Vprašanje za zaznamke`,
  "practice.bookmarked": `Dodano med zaznamke`,
  "practice.checkAnswer": `Preverite odgovor`,
  "practice.correct": `Pravilno`,
  "practice.demoContent": `Demo vsebina`,
  "practice.difficulty": `Težavnost`,
  "practice.easy": `enostavno`,
  "practice.explanation": `Razlaga`,
  "practice.filters": `Filtri`,
  "practice.hard": `težko`,
  "practice.incorrect": `Ne povsem`,
  "practice.medium": `Srednje`,
  "practice.nextQuestion": `Naslednje vprašanje`,
  "practice.questionCounter": `Vprašanje za vadbo {n} od {total}`,
  "practice.reportIssue": `Prijavite težavo`,
  "practice.title": `Vadite`,
  "practice.topicFilter": `Tema`,
  "practice.tryAgain": `poskusi ponovno`,
  "progress.accuracy": `Natančnost`,
  "progress.clearProgressDesc": `S tem iz te naprave izbrišete svoje odgovore, zaključke, zaznamke in zgodovino izpitov. Ni ga mogoče razveljaviti.`,
  "progress.clearProgressLabel": `Počisti ves napredek študija`,
  "progress.confirmClear": `Da, jasno vse`,
  "progress.dailyGoal": `Dnevni cilj`,
  "progress.details": `Podrobnosti`,
  "progress.examHistory": `Zgodovina izpitov`,
  "progress.noExams": `Izpit še ni opravljen.`,
  "progress.noWrongAnswers": `Trenutno ni napačnih odgovorov za pregled.`,
  "progress.overview": `Pregled`,
  "progress.perTopic": `Na temo`,
  "progress.questionsAnswered": `Odgovori na vprašanja`,
  "progress.reset": `Ponastavi`,
  "progress.retryTopic": `Poskusi ponovno s to temo`,
  "progress.sectionsDone": `Sekcije dokončane`,
  "progress.suggestedNext": `Predlagano naslednje: {topic}`,
  "progress.title": `Napredek`,
  "progress.topicCompletion": `Zaključek teme`,
  "report.detailsPlaceholder": `Povejte nam več (neobvezno)`,
  "report.incorrectAnswer": `Napačen odgovor`,
  "report.outdatedInfo": `Zastarele informacije`,
  "report.submit": `Oddaj poročilo`,
  "report.technicalIssue": `Tehnična težava`,
  "report.thanks": `Hvala — poročila so shranjena lokalno v tej napravi.`,
  "report.translationProblem": `Težava s prevodom`,
  "report.unclearExplanation": `Razlaga peu claire`,
  "settings.about": `O tej aplikaciji`,
  "settings.appInterfaceLanguage": `Jezik vmesnika aplikacije`,
  "settings.clearProgress": `Jasen napredek`,
  "settings.clearProgressConfirm": `Ste prepričani? To bo izbrisalo ves vaš napredek.`,
  "settings.interfaceDescription": `Meniji, gumbi in navigacija.`,
  "settings.language": `Jezik`,
  "settings.machineNote": `Strojno prevedene vsebine ni preveril človeški pregledovalec. Nič tukaj ni označeno kot pregledano, razen če je bilo dejansko pregledano.`,
  "settings.machineTranslatedBadge": `Strojno prevedeno`,
  "settings.manageProgress": `Upravljajte svoje podatke o napredku`,
  "settings.notAvailable": `Še ni na voljo`,
  "settings.officialGuideLink": `Uradni študijski vodnik`,
  "settings.officialTestLink": `Informacije o uradnem preizkusu državljanstva`,
  "settings.privacy": `Zasebnost`,
  "settings.privacyText": `Vaši odgovori, zaznamki in nastavitve so shranjeni samo v tej napravi. Račun ni potreben. Vprašanja, ki jih postavite pomočniku pri študiju, se pošljejo storitvi AI, da ustvari odgovore.`,
  "settings.reviewedBadge": `Pregledano`,
  "settings.studyContentLanguage": `Jezik študijske vsebine`,
  "settings.studyDescription": `Učenje besedila in razlage. Med navigacijo v drugem lahko berete v enem jeziku.`,
  "settings.textSize": `Velikost besedila`,
  "settings.title": `nastavitve`,
  "topics.askAssistant": `Vprašajte pomočnika o tem razdelku`,
  "topics.bookmarkSection": `Oddelek za zaznamke`,
  "topics.bookmarkedSection": `Dodano med zaznamke`,
  "topics.completed": `Dokončano`,
  "topics.continueLearningCard": `Nadaljujte z učenjem`,
  "topics.demoSourceNote": `Prvotno vzorčno vprašanje — ni uradno izpitno vprašanje`,
  "topics.lastVerified": `Nazadnje preverjeno {date}`,
  "topics.markComplete": `Označi kot dokončano`,
  "topics.markIncomplete": `Označi kot nedokončano`,
  "topics.minRead": `{n} min branja`,
  "topics.next": `Naprej`,
  "topics.openOfficialPage": `Odpri uradno stran`,
  "topics.paraphrasedSourceNote": `Parafrazirano iz uradnega gradiva`,
  "topics.practiceTopic": `Vadite to temo`,
  "topics.previous": `Prejšnja`,
  "topics.reportIssue": `Prijavite težavo`,
  "topics.reviewedOn": `pregledano {date}`,
  "topics.reviewedTranslation": `Pregledan prevod`,
  "topics.section": `Razdelek`,
  "topics.sections": `razdelki`,
  "topics.source": `Vir`,
  "topics.sourcesDescription": `Tukajšnje študijsko besedilo je parafrazirano iz vodnika Kanadske vlade o državljanstvu in pregledano na prikazane datume. Vprašanja za vadbo so raziskana v uradnem vodniku za študij.`,
  "topics.sourcesHeading": `Viri vsebine in datumi pregledov`,
  "topics.studyLanguageLabel": `Jezik študijske vsebine`,
  "topics.title": `Študijske teme`,
  "topics.vocabulary": `Besednjak`,
};
