// UI strings for 'sq' — chunk of strings.generated.ts. DO NOT EDIT BY HAND.
import type { StringKey } from "../strings.generated";

export const sq: Record<StringKey, string> = {
  "actions.askAi": `Pyet AI`,
  "actions.mockExam": `Provim model`,
  "actions.practice": `Praktikoni`,
  "actions.quickActions": `Quick actions`,
  "actions.study": `Studimi`,
  "assistant.aiEyebrow": `Asistent studimi i AI`,
  "assistant.answerLanguage": `Gjuha e përgjigjes`,
  "assistant.charLimit": `{n} karaktere të mbetura`,
  "assistant.checkingMaterial": `Duke kontrolluar materialin e studimit…`,
  "assistant.clearChat": `Pastro bisedën`,
  "assistant.copied": `E kopjuar`,
  "assistant.copy": `Kopjo`,
  "assistant.description": `Përgjigjet janë shkruar nga AI duke përdorur vetëm materialin studimor të këtij aplikacioni, me burimet e treguara. Inteligjenca artificiale ende mund të bëjë gabime - kontrolloni detaje të rëndësishme në faqet zyrtare të Qeverisë së Kanadasë. Jo këshilla ligjore apo imigracioni.`,
  "assistant.enFrancais": `në frëngjisht`,
  "assistant.error": `Diçka shkoi keq. Ju lutemi provoni përsëri.`,
  "assistant.fromAppContent": `Nga përmbajtja e miratuar e aplikacionit`,
  "assistant.groundedBadge": `Me bazë burimi`,
  "assistant.helpful": `E dobishme`,
  "assistant.inputPlaceholder": `Bëni një pyetje në lidhje me shtetësinë kanadeze…`,
  "assistant.myAppLanguage": `Gjuha ime e aplikacionit`,
  "assistant.notCovered": `Nuk mbulohet - shikoni faqen zyrtare`,
  "assistant.notHelpful": `Jo të dobishme`,
  "assistant.openAssistant": `Asistent i hapur studimi`,
  "assistant.openLink": `Hap asistentin`,
  "assistant.practiceThis": `Praktikoni këtë`,
  "assistant.questionAriaLabel": `Pyetja juaj`,
  "assistant.reportIncorrect": `Raportoni një përgjigje të pasaktë`,
  "assistant.send": `Dërgo`,
  "assistant.showSource": `Trego burimin`,
  "assistant.simpleEnglish": `Anglisht e thjeshtë`,
  "assistant.source": `Burimi`,
  "assistant.starter1": `Cilat janë tre pjesët e Parlamentit?`,
  "assistant.starter2": `Shpjegoni Kartën thjesht`,
  "assistant.starter3": `Kush e përfaqëson Mbretin në Kanada?`,
  "assistant.starter4": `Çfarë përfshin testi i njohurive?`,
  "assistant.suggestedQuestions": `Pyetje të sugjeruara`,
  "assistant.thinking": `Duke menduar…`,
  "assistant.title": `Asistent studimi`,
  "assistant.tryAgain": `Provo sërish`,
  "assistant.tryAsking": `Provoni të pyesni:`,
  "assistant.vocabularyLabel": `Fjalori:`,
  "assistant.whyItMatters": `Pse ka rëndësi për testin`,
  "auth.account": `Account`,
  "auth.checkEmail": `Check your email to confirm your account, then sign in.`,
  "auth.close": `Close`,
  "auth.codeLabel": `Verification code`,
  "auth.codeResent": `New code sent. Check your email.`,
  "auth.codeSent": `Code sent! Check your email and enter the 6-digit code.`,
  "auth.createAccount": `Create account`,
  "auth.dataDeletedMsg": `Your progress and profile data were deleted.`,
  "auth.deleteConfirm": `Tap again to permanently delete`,
  "auth.deleteData": `Delete my data`,
  "auth.email": `Email`,
  "auth.haveAccount": `Already have an account?`,
  "auth.mfaCodeLabel": `Authenticator code`,
  "auth.mfaDisable": `Disable 2FA`,
  "auth.mfaDisabledMsg": `Two-factor authentication is now OFF.`,
  "auth.mfaEnable": `Enable 2FA`,
  "auth.mfaEnabledMsg": `Two-factor authentication is now ON for your account.`,
  "auth.mfaPendingWarn": `2FA code still needed to finish signing in.`,
  "auth.mfaPrompt": `This account uses 2FA — enter the code from your authenticator app.`,
  "auth.mfaScanHint": `Scan this QR code with your authenticator app (Google Authenticator, Authy, 1Password…), then enter the 6-digit code it shows.`,
  "auth.mfaSetupTitle": `Set up two-factor authentication`,
  "auth.mfaSubtitle": `Enter the 6-digit code from your authenticator app.`,
  "auth.mfaTitle": `Two-factor authentication`,
  "auth.noAccount": `Don't have an account?`,
  "auth.password": `Password`,
  "auth.passwordHint": `At least 6 characters`,
  "auth.privacy": `Privacy`,
  "auth.privacyNote": `Your email and progress are private — only you can see them.`,
  "auth.resendCode": `Resend code`,
  "auth.security": `Security`,
  "auth.signIn": `Sign in`,
  "auth.signOut": `Sign out`,
  "auth.signUp": `Sign up`,
  "auth.subtitle": `Save your progress across devices. Your data stays private.`,
  "auth.title": `Account`,
  "auth.verify": `Verify`,
  "auth.verifyCodeSubtitle": `We sent a 6-digit code to your email. Enter it below to finish signing up.`,
  "auth.verifyCodeTitle": `Enter your code`,
  "auth.working": `Please wait…`,
  "bookmarks.continueStudying": `Vazhdoni të studioni`,
  "bookmarks.empty": `Nuk ka ende faqeshënues. Prekni yllin në çdo pyetje për ta ruajtur për shqyrtim.`,
  "bookmarks.emptyQuestions": `Asgjë nuk është ruajtur ende. Prekni ☆ në një pyetje praktike.`,
  "bookmarks.emptySections": `Asgjë nuk është ruajtur ende. Prekni ☆ ndërsa lexoni një seksion.`,
  "bookmarks.remove": `Hiq`,
  "bookmarks.savedForReview": `ruajtur për shqyrtim`,
  "bookmarks.savedQuestions": `Pyetjet e ruajtura ({n})`,
  "bookmarks.savedSections": `Seksionet e ruajtura ({n})`,
  "bookmarks.search": `Kërko faqeshënuesit…`,
  "bookmarks.title": `Faqerojtësit`,
  "cards.answered": `U përgjigj`,
  "cards.bookmarks": `ruajtur për shqyrtim`,
  "cards.bookmarksLabel": `Faqerojtësit`,
  "cards.continueLearning": `Vazhdoni të mësoni`,
  "cards.correct": `E sakte`,
  "cards.dailyGoal": `{done}/{total} questions today`,
  "cards.dailyGoalLabel": `Qëllimi ditor`,
  "cards.dailyGoalTitle": `Daily goal`,
  "cards.mockExam.subtitle": `Me kohë · 20 pyetje`,
  "cards.mockExam.title": `Provim model`,
  "cards.officialInfo.button": `Hapur Kanada.ca`,
  "cards.officialInfo.subtitle": `Vizitoni canada.ca për detaje zyrtare`,
  "cards.officialInfo.title": `Informacion zyrtar`,
  "cards.progress": `Përparim`,
  "cards.progressDetails": `Detajet`,
  "cards.recentlyStudied": `Studuar së fundmi`,
  "cards.sections": `Seksionet`,
  "cards.studyAssistant.subtitle": `Pyetni ndonjë gjë në lidhje me materialin e studimit`,
  "cards.studyAssistant.title": `Asistent studimi`,
  "cards.todaysRecommendation": `Rekomandimi i sotëm`,
  "cards.verifiedSource.subtext": `Përmbajtja e kontrolluar nga burimet zyrtare. Ndihmë studimore e pavarur - nuk është e lidhur ose e miratuar nga Qeveria e Kanadasë ose IRCC.`,
  "cards.verifiedSource.title": `Burimi i verifikuar`,
  "common.back": `Mbrapa`,
  "common.cancel": `Anulo`,
  "common.close": `Mbylle`,
  "common.continue": `Vazhdoni`,
  "common.done": `U krye`,
  "common.emptyBookmarks": `Asgjë nuk është ruajtur ende`,
  "common.emptyRecentlyStudied": `Asgjë ende e studiuar - zgjidhni një temë për të filluar.`,
  "common.loading": `Po ngarkohet…`,
  "common.next": `Tjetra`,
  "common.of": `e`,
  "common.previous": `E mëparshme`,
  "common.retry": `Provo sërish`,
  "common.save": `Ruaj`,
  "exam.allTopics": `Të gjitha temat`,
  "exam.answeredCount": `{n} u përgjigj`,
  "exam.autosaveNote": `Përgjigjet tuaja ruhen ndërsa shkoni, kështu që mbyllja e aplikacionit nuk do të humbasë përparimin tuaj.`,
  "exam.cancel": `Anulo`,
  "exam.confirm": `Konfirmo`,
  "exam.confirmEnd": `{n} pyetje janë pa përgjigje dhe do të shënohen si të pasakta.`,
  "exam.confirmEndTitle": `Përfundimi i provimit?`,
  "exam.endExamEarly": `Përfundo provimin herët`,
  "exam.examDisclaimer": `Ky rezultat pasqyron vetëm pyetjet mostër të këtij aplikacioni.`,
  "exam.finishExam": `Përfundoni provimin`,
  "exam.newExam": `Provim i ri`,
  "exam.noMistakes": `Pa gabime - rezultat i përsosur!`,
  "exam.pastAttempts": `Përpjekjet e kaluara`,
  "exam.questionAriaLabel": `Pyetja {n}`,
  "exam.questionCount": `Numri i pyetjeve`,
  "exam.questionOf": `Pyetja {n} nga {total}`,
  "exam.questionPalette": `Pyetje`,
  "exam.questionsOption": `{n} pyetje`,
  "exam.resultsTitle": `Rezultati juaj`,
  "exam.reviewMistakes": `Rishikoni gabimet tuaja ({n})`,
  "exam.scoreLine": `{correct} of {total} correct`,
  "exam.seeProgress": `Shihni përparimin`,
  "exam.setupDescription": `Ky është një simulim praktik i ndërtuar nga pyetjet studimore të këtij aplikacioni. Nuk është testi zyrtar dhe nuk parashikon rezultatin tuaj.`,
  "exam.setupTitle": `Vendosni provimin tuaj simulues`,
  "exam.simulationNote": `Simulimi praktik · jo zyrtar`,
  "exam.startExam": `Filloni provimin`,
  "exam.timeLeft": `Koha e mbetur`,
  "exam.timedLabel": `me kohë`,
  "exam.timedToggle": `Me kohë (90 sekonda për pyetje)`,
  "exam.title": `Provim model`,
  "exam.topicFilter": `Tema`,
  "exam.untimedLabel": `pa kohë`,
  "footer.disclaimer": `Citizen Prep është një ndihmë studimi i pavarur. Nuk është e lidhur ose e miratuar nga Qeveria e Kanadasë ose IRCC. Nuk mund të garantojë një rezultat kalues.`,
  "header.appName": `Përgatitja qytetare`,
  "header.tagline": `Mjet i pavarur i studimit · Jo zyrtar`,
  "hero.sectionsProgress": `{done} of {total} sections · {percent}% complete`,
  "hero.subtitle": `Mjet i pavarur i studimit · Anglisht dhe Frengjisht · nuk nevojitet llogari`,
  "hero.title": `Përgatituni për testin tuaj të shtetësisë`,
  "nav.exam": `Provimi`,
  "nav.home": `Shtëpi`,
  "nav.practice": `Praktikoni`,
  "nav.progress": `Përparim`,
  "nav.topics": `Temat`,
  "practice.allLevels": `Të gjitha nivelet`,
  "practice.allTopics": `Të gjitha temat`,
  "practice.askAiAbout": `Pyetni AI për këtë pyetje`,
  "practice.bookmarkQuestion": `Pyetja e faqerojtësit`,
  "practice.bookmarked": `Shënuar në faqe`,
  "practice.checkAnswer": `Kontrolloni përgjigjen`,
  "practice.correct": `E sakte`,
  "practice.demoContent": `Përmbajtja demonstruese`,
  "practice.difficulty": `Vështirësi`,
  "practice.easy": `Lehtë`,
  "practice.explanation": `Shpjegimi`,
  "practice.filters": `Filtrat`,
  "practice.hard": `E vështirë`,
  "practice.incorrect": `Jo mjaft`,
  "practice.medium": `E mesme`,
  "practice.nextQuestion": `Pyetja e radhës`,
  "practice.questionCounter": `Praktikoni pyetjen {n} nga {total}`,
  "practice.reportIssue": `Raportoni një problem`,
  "practice.title": `Praktikoni`,
  "practice.topicFilter": `Tema`,
  "practice.tryAgain": `Provo sërish`,
  "progress.accuracy": `Saktësia`,
  "progress.clearProgressDesc": `Kjo fshin përgjigjet, plotësimet, faqeshënuesit dhe historikun e provimeve nga kjo pajisje. Nuk mund të zhbëhet.`,
  "progress.clearProgressLabel": `Pastro të gjithë përparimin e studimit`,
  "progress.confirmClear": `Po, pastroni gjithçka`,
  "progress.dailyGoal": `Qëllimi ditor`,
  "progress.details": `Detajet`,
  "progress.examHistory": `Historia e provimeve`,
  "progress.noExams": `Nuk janë marrë ende provime.`,
  "progress.noWrongAnswers": `Nuk ka përgjigje të pasakta për t'u rishikuar tani.`,
  "progress.overview": `Vështrim i përgjithshëm`,
  "progress.perTopic": `Sipas temës`,
  "progress.questionsAnswered": `Pyetjet u përgjigjën`,
  "progress.reset": `Rivendos`,
  "progress.retryTopic": `Provo sërish këtë temë`,
  "progress.sectionsDone": `Seksionet e përfunduara`,
  "progress.suggestedNext": `Sugjeruar në vijim: {topic}`,
  "progress.title": `Përparim`,
  "progress.topicCompletion": `Plotësimi i temës`,
  "report.detailsPlaceholder": `Na trego më shumë (opsionale)`,
  "report.incorrectAnswer": `Përgjigje e pasaktë`,
  "report.outdatedInfo": `Informacion i vjetëruar`,
  "report.submit": `Paraqisni raportin`,
  "report.technicalIssue": `Çështje teknike`,
  "report.thanks": `Faleminderit - raportet ruhen në nivel lokal në këtë pajisje.`,
  "report.translationProblem": `Problemi i përkthimit`,
  "report.unclearExplanation": `Shpjegim peu claire`,
  "settings.about": `Rreth këtij aplikacioni`,
  "settings.appInterfaceLanguage": `Gjuha e ndërfaqes së aplikacionit`,
  "settings.clearProgress": `Përparim i qartë`,
  "settings.clearProgressConfirm": `je i sigurt? Kjo do të fshijë të gjithë përparimin tuaj.`,
  "settings.interfaceDescription": `Menutë, butonat dhe navigimi.`,
  "settings.language": `Gjuha`,
  "settings.machineNote": `Përmbajtja e përkthyer në makinë nuk është kontrolluar nga një recensues njerëzor. Asgjë këtu nuk është etiketuar si e shqyrtuar nëse nuk është shqyrtuar në të vërtetë.`,
  "settings.machineTranslatedBadge": `E përkthyer në makinë`,
  "settings.manageProgress": `Menaxhoni të dhënat tuaja të përparimit`,
  "settings.notAvailable": `Nuk disponohet ende`,
  "settings.officialGuideLink": `Udhëzues zyrtar i studimit`,
  "settings.officialTestLink": `Informacioni i testit zyrtar të shtetësisë`,
  "settings.privacy": `Privatësia`,
  "settings.privacyText": `Përgjigjet, faqeshënuesit dhe cilësimet tuaja ruhen vetëm në këtë pajisje. Nuk nevojitet asnjë llogari. Pyetjet që i bëni asistentit të studimit i dërgohen një shërbimi të AI për të gjeneruar përgjigje.`,
  "settings.reviewedBadge": `Shqyrtuar`,
  "settings.studyContentLanguage": `Studioni gjuhën e përmbajtjes`,
  "settings.studyDescription": `Teksti mësimor dhe shpjegimet. Mund të lexoni në një gjuhë ndërsa lundroni në një tjetër.`,
  "settings.textSize": `Madhësia e tekstit`,
  "settings.title": `Cilësimet`,
  "topics.askAssistant": `Pyetni asistentin për këtë pjesë`,
  "topics.bookmarkSection": `Seksioni i faqeshënuesve`,
  "topics.bookmarkedSection": `Shënuar në faqe`,
  "topics.completed": `E përfunduar`,
  "topics.continueLearningCard": `Vazhdoni të mësoni`,
  "topics.demoSourceNote": `Mostra origjinale e pyetjes - jo një pyetje zyrtare e provimit`,
  "topics.lastVerified": `Verifikimi i fundit {date}`,
  "topics.markComplete": `Shëno si të plotë`,
  "topics.markIncomplete": `Shëno si të paplotë`,
  "topics.minRead": `{n} minuta lexim`,
  "topics.next": `Tjetra`,
  "topics.openOfficialPage": `Hapni faqen zyrtare`,
  "topics.paraphrasedSourceNote": `Parafrazuar nga materiali zyrtar`,
  "topics.practiceTopic": `Praktikoni këtë temë`,
  "topics.previous": `E mëparshme`,
  "topics.reportIssue": `Raportoni një problem`,
  "topics.reviewedOn": `rishikuar {date}`,
  "topics.reviewedTranslation": `Përkthimi i rishikuar`,
  "topics.section": `Seksioni`,
  "topics.sections": `seksionet`,
  "topics.source": `Burimi`,
  "topics.sourcesDescription": `Teksti i studimit këtu është perifrazuar nga udhëzuesi i studimit të shtetësisë së Qeverisë së Kanadasë dhe rishikohet në datat e treguara. Pyetjet e praktikës hulumtohen nga udhëzuesi zyrtar i studimit.`,
  "topics.sourcesHeading": `Burimet e përmbajtjes dhe datat e rishikimit`,
  "topics.studyLanguageLabel": `Studioni gjuhën e përmbajtjes`,
  "topics.title": `Temat e studimit`,
  "topics.vocabulary": `Fjalori`,
};
