// UI strings for 'sr' — chunk of strings.generated.ts. DO NOT EDIT BY HAND.
import type { StringKey } from "../strings.generated";

export const sr: Record<StringKey, string> = {
  "actions.askAi": `Питајте АИ`,
  "actions.mockExam": `Моцк испит`,
  "actions.practice": `Вежбајте`,
  "actions.quickActions": `Quick actions`,
  "actions.study": `Студија`,
  "assistant.aiEyebrow": `АИ асистент за учење`,
  "assistant.answerLanguage": `Језик одговора`,
  "assistant.charLimit": `{n} characters left`,
  "assistant.checkingMaterial": `Проверавам материјал за учење…`,
  "assistant.clearChat": `Обриши ћаскање`,
  "assistant.copied": `Копирано`,
  "assistant.copy": `Копирај`,
  "assistant.description": `Одговоре пише вештачка интелигенција користећи само материјал за учење ове апликације, са приказаним изворима. АИ и даље може да прави грешке — проверите важне детаље на званичним страницама Владе Канаде. Није правни савет или савет за имиграцију.`,
  "assistant.enFrancais": `Ен францаис`,
  "assistant.error": `Нешто је пошло по злу. Покушајте поново.`,
  "assistant.fromAppContent": `Из одобреног садржаја апликације`,
  "assistant.groundedBadge": `Изворно утемељено`,
  "assistant.helpful": `Корисно`,
  "assistant.inputPlaceholder": `Поставите питање о канадском држављанству...`,
  "assistant.myAppLanguage": `Мој језик апликације`,
  "assistant.notCovered": `Није покривено — погледајте званичну страницу`,
  "assistant.notHelpful": `Није од помоћи`,
  "assistant.openAssistant": `Отворени студијски асистент`,
  "assistant.openLink": `Отворени асистент`,
  "assistant.practiceThis": `Вежбај ово`,
  "assistant.questionAriaLabel": `Ваше питање`,
  "assistant.reportIncorrect": `Пријавите нетачан одговор`,
  "assistant.send": `Пошаљи`,
  "assistant.showSource": `Прикажи извор`,
  "assistant.simpleEnglish": `Симпле Енглисх`,
  "assistant.source": `Извор`,
  "assistant.starter1": `Која су три дела парламента?`,
  "assistant.starter2": `Објасните Повељу једноставно`,
  "assistant.starter3": `Ко представља краља у Канади?`,
  "assistant.starter4": `Шта обухвата провера знања?`,
  "assistant.suggestedQuestions": `Предложена питања`,
  "assistant.thinking": `Размишљајући…`,
  "assistant.title": `Студијски асистент`,
  "assistant.tryAgain": `Покушајте поново`,
  "assistant.tryAsking": `Покушајте да питате:`,
  "assistant.vocabularyLabel": `Речник:`,
  "assistant.whyItMatters": `Зашто је то важно за тест`,
  "bookmarks.continueStudying": `Наставите са учењем`,
  "bookmarks.empty": `Још нема обележивача. Додирните звездицу на било ком питању да бисте га сачували за преглед.`,
  "bookmarks.emptyQuestions": `Још ништа није сачувано. Додирните ☆ на питање за вежбање.`,
  "bookmarks.emptySections": `Још ништа није сачувано. Додирните ☆ док читате одељак.`,
  "bookmarks.remove": `Уклони`,
  "bookmarks.savedForReview": `сачувано за преглед`,
  "bookmarks.savedQuestions": `Saved questions ({n})`,
  "bookmarks.savedSections": `Saved sections ({n})`,
  "bookmarks.search": `Претражи обележиваче…`,
  "bookmarks.title": `Боокмаркс`,
  "cards.answered": `Одговорио`,
  "cards.bookmarks": `сачувано за преглед`,
  "cards.bookmarksLabel": `Боокмаркс`,
  "cards.continueLearning": `Наставите са учењем`,
  "cards.correct": `Тачно`,
  "cards.dailyGoal": `{done}/{total} questions today`,
  "cards.dailyGoalLabel": `Дневни циљ`,
  "cards.dailyGoalTitle": `Daily goal`,
  "cards.mockExam.subtitle": `Временски · 20 питања`,
  "cards.mockExam.title": `Моцк испит`,
  "cards.officialInfo.button": `Отворите цанада.ца`,
  "cards.officialInfo.subtitle": `Посетите цанада.ца за званичне детаље`,
  "cards.officialInfo.title": `Званичне информације`,
  "cards.progress": `Напредак`,
  "cards.progressDetails": `Детаљи`,
  "cards.recentlyStudied": `Недавно студирао`,
  "cards.sections": `Секције`,
  "cards.studyAssistant.subtitle": `Питајте било шта о материјалу за учење`,
  "cards.studyAssistant.title": `Студијски асистент`,
  "cards.todaysRecommendation": `Данашња препорука`,
  "cards.verifiedSource.subtext": `Садржај проверен у односу на званичне изворе. Независна помоћ за студирање — није повезана са нити одобрена од стране Владе Канаде или ИРЦЦ-а.`,
  "cards.verifiedSource.title": `Верифиед соурце`,
  "common.back": `Назад`,
  "common.cancel": `Откажи`,
  "common.close": `Затвори`,
  "common.continue": `Настави`,
  "common.done": `Готово`,
  "common.emptyBookmarks": `Још ништа није сачувано`,
  "common.emptyRecentlyStudied": `Још ништа није проучено — изаберите тему за почетак.`,
  "common.loading": `Учитавање…`,
  "common.next": `Следеће`,
  "common.of": `оф`,
  "common.previous": `Претходно`,
  "common.retry": `Покушајте поново`,
  "common.save": `Сачувај`,
  "exam.allTopics": `Све теме`,
  "exam.answeredCount": `{n} answered`,
  "exam.autosaveNote": `Ваши одговори се чувају док идете, тако да затварањем апликације нећете изгубити напредак.`,
  "exam.cancel": `Откажи`,
  "exam.confirm": `Потврди`,
  "exam.confirmEnd": `{n} questions are unanswered and will be marked incorrect.`,
  "exam.confirmEndTitle": `Завршити испит?`,
  "exam.endExamEarly": `Заврши испит раније`,
  "exam.examDisclaimer": `Овај резултат одражава само узорке питања ове апликације.`,
  "exam.finishExam": `Заврши испит`,
  "exam.newExam": `Нови испит`,
  "exam.noMistakes": `Без грешака — савршен резултат!`,
  "exam.pastAttempts": `Претходни покушаји`,
  "exam.questionAriaLabel": `Question {n}`,
  "exam.questionCount": `Број питања`,
  "exam.questionOf": `Question {n} of {total}`,
  "exam.questionPalette": `Питања`,
  "exam.questionsOption": `{n} questions`,
  "exam.resultsTitle": `Твој резултат`,
  "exam.reviewMistakes": `Review your mistakes ({n})`,
  "exam.scoreLine": `{correct} of {total} correct`,
  "exam.seeProgress": `Видите напредак`,
  "exam.setupDescription": `Ово је симулација праксе изграђена на основу студијских питања ове апликације. То није званични тест и не предвиђа ваш резултат.`,
  "exam.setupTitle": `Поставите свој пробни испит`,
  "exam.simulationNote": `Вежбајте симулацију · није званично`,
  "exam.startExam": `Почни испит`,
  "exam.timeLeft": `Остало је време`,
  "exam.timedLabel": `темпирано`,
  "exam.timedToggle": `Временски (90 секунди по питању)`,
  "exam.title": `Моцк испит`,
  "exam.topicFilter": `Тема`,
  "exam.untimedLabel": `невременски`,
  "footer.disclaimer": `Цитизен Преп је независно помагало за учење. Није повезан нити одобрен од стране Владе Канаде или ИРЦЦ-а. Не може гарантовати пролазан резултат.`,
  "header.appName": `Цитизен Преп`,
  "header.tagline": `Независно средство за учење · Није званично`,
  "hero.sectionsProgress": `{done} of {total} sections · {percent}% complete`,
  "hero.subtitle": `Алат за независно учење · енглески и француски · није потребан налог`,
  "hero.title": `Припремите се за тест за држављанство`,
  "nav.exam": `Испит`,
  "nav.home": `Хоме`,
  "nav.practice": `Вежбајте`,
  "nav.progress": `Напредак`,
  "nav.topics": `Теме`,
  "practice.allLevels": `Сви нивои`,
  "practice.allTopics": `Све теме`,
  "practice.askAiAbout": `Питајте АИ о овом питању`,
  "practice.bookmarkQuestion": `Означите питање`,
  "practice.bookmarked": `Боокмаркед`,
  "practice.checkAnswer": `Проверите одговор`,
  "practice.correct": `Тачно`,
  "practice.demoContent": `Демо садржај`,
  "practice.difficulty": `Потешкоће`,
  "practice.easy": `Лако`,
  "practice.explanation": `Објашњење`,
  "practice.filters": `Филтери`,
  "practice.hard": `Тешко`,
  "practice.incorrect": `Не баш`,
  "practice.medium": `Средње`,
  "practice.nextQuestion": `Следеће питање`,
  "practice.questionCounter": `Practice question {n} of {total}`,
  "practice.reportIssue": `Пријавите проблем`,
  "practice.title": `Вежбајте`,
  "practice.topicFilter": `Тема`,
  "practice.tryAgain": `Покушајте поново`,
  "progress.accuracy": `Прецизност`,
  "progress.clearProgressDesc": `Овим бришете ваше одговоре, довршавања, обележиваче и историју испита са овог уређаја. Не може се поништити.`,
  "progress.clearProgressLabel": `Обришите сав напредак у учењу`,
  "progress.confirmClear": `Да, очисти све`,
  "progress.dailyGoal": `Дневни циљ`,
  "progress.details": `Детаљи`,
  "progress.examHistory": `Историја испита`,
  "progress.noExams": `Још нема положених испита.`,
  "progress.noWrongAnswers": `Тренутно нема нетачних одговора за преглед.`,
  "progress.overview": `Преглед`,
  "progress.perTopic": `По теми`,
  "progress.questionsAnswered": `Одговори на питања`,
  "progress.reset": `Ресетуј`,
  "progress.retryTopic": `Покушајте поново са овом темом`,
  "progress.sectionsDone": `Секције су завршене`,
  "progress.suggestedNext": `Suggested next: {topic}`,
  "progress.title": `Напредак`,
  "progress.topicCompletion": `Завршетак теме`,
  "report.detailsPlaceholder": `Реците нам више (опционо)`,
  "report.incorrectAnswer": `Нетачан одговор`,
  "report.outdatedInfo": `Застареле информације`,
  "report.submit": `Пошаљи извештај`,
  "report.technicalIssue": `Техничко питање`,
  "report.thanks": `Хвала — извештаји се чувају локално на овом уређају.`,
  "report.translationProblem": `Проблем са преводом`,
  "report.unclearExplanation": `Експликација пеу цлаире`,
  "settings.about": `О овој апликацији`,
  "settings.appInterfaceLanguage": `Језик интерфејса апликације`,
  "settings.clearProgress": `Јасан напредак`,
  "settings.clearProgressConfirm": `Јесте ли сигурни? Ово ће избрисати сав ваш напредак.`,
  "settings.interfaceDescription": `Менији, дугмад и навигација.`,
  "settings.language": `Језик`,
  "settings.machineNote": `Machine-translated content has not been checked by a human reviewer. Nothing here is labelled as reviewed unless it has actually been reviewed.`,
  "settings.machineTranslatedBadge": `Машински преведено`,
  "settings.manageProgress": `Управљајте подацима о напретку`,
  "settings.notAvailable": `Још није доступно`,
  "settings.officialGuideLink": `Званични водич за учење`,
  "settings.officialTestLink": `Информације о званичном тесту држављанства`,
  "settings.privacy": `Приватност`,
  "settings.privacyText": `Ваши одговори, обележивачи и подешавања се чувају само на овом уређају. Није потребан налог. Питања која поставите асистенту за учење шаљу се служби вештачке интелигенције да генерише одговоре.`,
  "settings.reviewedBadge": `Прегледано`,
  "settings.studyContentLanguage": `Учите језик садржаја`,
  "settings.studyDescription": `Учење текста и објашњења. You can read in one language while navigating in another.`,
  "settings.textSize": `Величина текста`,
  "settings.title": `Подешавања`,
  "topics.askAssistant": `Питајте асистента о овом одељку`,
  "topics.bookmarkSection": `Одељак обележивача`,
  "topics.bookmarkedSection": `Боокмаркед`,
  "topics.completed": `Завршено`,
  "topics.continueLearningCard": `Наставите са учењем`,
  "topics.demoSourceNote": `Оригинални узорак питања — није званично испитно питање`,
  "topics.lastVerified": `Последња верификована {date}`,
  "topics.markComplete": `Означите као завршено`,
  "topics.markIncomplete": `Означите као непотпуно`,
  "topics.minRead": `{n} min read`,
  "topics.next": `Следеће`,
  "topics.openOfficialPage": `Отворите званичну страницу`,
  "topics.paraphrasedSourceNote": `Парафразирано из званичног материјала`,
  "topics.practiceTopic": `Вежбајте ову тему`,
  "topics.previous": `Претходно`,
  "topics.reportIssue": `Пријавите проблем`,
  "topics.reviewedOn": `reviewed {date}`,
  "topics.reviewedTranslation": `Прегледан превод`,
  "topics.section": `Секција`,
  "topics.sections": `секције`,
  "topics.source": `Извор`,
  "topics.sourcesDescription": `Текст студије овде је парафразиран из водича за проучавање држављанства Владе Канаде и прегледан у приказаним датумима. Питања за вежбу се истражују из званичног водича за учење.`,
  "topics.sourcesHeading": `Извори садржаја и датуми прегледа`,
  "topics.studyLanguageLabel": `Учите језик садржаја`,
  "topics.title": `Теме за учење`,
  "topics.vocabulary": `Речник`,
};
