// UI strings for 'sv' — chunk of strings.generated.ts. DO NOT EDIT BY HAND.
import type { StringKey } from "../strings.generated";

export const sv: Record<StringKey, string> = {
  "actions.askAi": `Fråga AI`,
  "actions.mockExam": `Spotprov`,
  "actions.practice": `Öva`,
  "actions.quickActions": `Quick actions`,
  "actions.study": `Studera`,
  "assistant.aiEyebrow": `AI studieassistent`,
  "assistant.answerLanguage": `Svarsspråk`,
  "assistant.charLimit": `{n} tecken kvar`,
  "assistant.checkingMaterial": `Kontrollerar studiematerialet...`,
  "assistant.clearChat": `Rensa chatten`,
  "assistant.copied": `Kopierade`,
  "assistant.copy": `Kopiera`,
  "assistant.description": `Svaren är skrivna av AI med endast den här appens studiematerial, med källor visade. AI kan fortfarande göra misstag – kontrollera viktiga detaljer på Kanadas officiella sidor. Inte juridisk rådgivning eller immigrationsrådgivning.`,
  "assistant.enFrancais": `En français`,
  "assistant.error": `Något gick fel. Försök igen.`,
  "assistant.fromAppContent": `Från godkänt appinnehåll`,
  "assistant.groundedBadge": `Källgrundad`,
  "assistant.helpful": `Hjälpsam`,
  "assistant.inputPlaceholder": `Ställ en fråga om kanadensiskt medborgarskap...`,
  "assistant.myAppLanguage": `Mitt app-språk`,
  "assistant.notCovered": `Ej täckt — se officiella sida`,
  "assistant.notHelpful": `Inte till hjälp`,
  "assistant.openAssistant": `Öppen studieassistent`,
  "assistant.openLink": `Öppna assistent`,
  "assistant.practiceThis": `Öva på detta`,
  "assistant.questionAriaLabel": `Din fråga`,
  "assistant.reportIncorrect": `Rapportera ett felaktigt svar`,
  "assistant.send": `Skicka`,
  "assistant.showSource": `Visa källa`,
  "assistant.simpleEnglish": `Enkel engelska`,
  "assistant.source": `Källa`,
  "assistant.starter1": `Vilka är de tre delarna av parlamentet?`,
  "assistant.starter2": `Förklara stadgan helt enkelt`,
  "assistant.starter3": `Vem representerar kungen i Kanada?`,
  "assistant.starter4": `Vad omfattar kunskapstestet?`,
  "assistant.suggestedQuestions": `Föreslagna frågor`,
  "assistant.thinking": `Funderar...`,
  "assistant.title": `Studieassistent`,
  "assistant.tryAgain": `Försök igen`,
  "assistant.tryAsking": `Försök att fråga:`,
  "assistant.vocabularyLabel": `Ordförråd:`,
  "assistant.whyItMatters": `Varför det är viktigt för testet`,
  "bookmarks.continueStudying": `Fortsätt studera`,
  "bookmarks.empty": `Inga bokmärken än. Tryck på stjärnan på en fråga för att spara den för granskning.`,
  "bookmarks.emptyQuestions": `Inget sparat ännu. Tryck ☆ på en övningsfråga.`,
  "bookmarks.emptySections": `Inget sparat ännu. Tryck på ☆ medan du läser ett avsnitt.`,
  "bookmarks.remove": `Ta bort`,
  "bookmarks.savedForReview": `sparas för granskning`,
  "bookmarks.savedQuestions": `Sparade frågor ({n})`,
  "bookmarks.savedSections": `Sparade avsnitt ({n})`,
  "bookmarks.search": `Sök efter bokmärken...`,
  "bookmarks.title": `Bokmärken`,
  "cards.answered": `Svarade`,
  "cards.bookmarks": `sparas för granskning`,
  "cards.bookmarksLabel": `Bokmärken`,
  "cards.continueLearning": `Fortsätt lära dig`,
  "cards.correct": `Rätt`,
  "cards.dailyGoal": `{done}/{total} frågor idag`,
  "cards.dailyGoalLabel": `Dagligt mål`,
  "cards.dailyGoalTitle": `Daily goal`,
  "cards.mockExam.subtitle": `Tidsinställd · 20 frågor`,
  "cards.mockExam.title": `Spotprov`,
  "cards.officialInfo.button": `Öppna canada.ca`,
  "cards.officialInfo.subtitle": `Besök canada.ca för officiella detaljer`,
  "cards.officialInfo.title": `Officiell information`,
  "cards.progress": `Framsteg`,
  "cards.progressDetails": `Detaljer`,
  "cards.recentlyStudied": `Nyligen studerat`,
  "cards.sections": `Avsnitt`,
  "cards.studyAssistant.subtitle": `Fråga vad som helst om studiematerialet`,
  "cards.studyAssistant.title": `Studieassistent`,
  "cards.todaysRecommendation": `Dagens rekommendation`,
  "cards.verifiedSource.subtext": `Innehåll kontrolleras mot officiella källor. Oberoende studiestöd — inte anslutet till eller godkänt av Kanadas regering eller IRCC.`,
  "cards.verifiedSource.title": `Verifierad källa`,
  "common.back": `Tillbaka`,
  "common.cancel": `Avbryt`,
  "common.close": `Stäng`,
  "common.continue": `Fortsätt`,
  "common.done": `Klart`,
  "common.emptyBookmarks": `Inget sparat ännu`,
  "common.emptyRecentlyStudied": `Inget studerat ännu - välj ett ämne att börja.`,
  "common.loading": `Laddar...`,
  "common.next": `Nästa`,
  "common.of": `av`,
  "common.previous": `Föregående`,
  "common.retry": `Försök igen`,
  "common.save": `Spara`,
  "exam.allTopics": `Alla ämnen`,
  "exam.answeredCount": `{n} svarade`,
  "exam.autosaveNote": `Dina svar sparas allt eftersom, så att du stänger appen förlorar du inte dina framsteg.`,
  "exam.cancel": `Avbryt`,
  "exam.confirm": `Bekräfta`,
  "exam.confirmEnd": `{n} frågor är obesvarade och kommer att markeras som felaktiga.`,
  "exam.confirmEndTitle": `Avsluta provet?`,
  "exam.endExamEarly": `Avsluta provet tidigt`,
  "exam.examDisclaimer": `Denna poäng återspeglar endast denna apps exempelfrågor.`,
  "exam.finishExam": `Avsluta examen`,
  "exam.newExam": `Ny examen`,
  "exam.noMistakes": `Inga misstag – perfekt poäng!`,
  "exam.pastAttempts": `Tidigare försök`,
  "exam.questionAriaLabel": `Fråga {n}`,
  "exam.questionCount": `Antal frågor`,
  "exam.questionOf": `Fråga {n} av {total}`,
  "exam.questionPalette": `Frågor`,
  "exam.questionsOption": `{n} frågor`,
  "exam.resultsTitle": `Din poäng`,
  "exam.reviewMistakes": `Granska dina misstag ({n})`,
  "exam.scoreLine": `{correct} av {total} korrekt`,
  "exam.seeProgress": `Se framstegen`,
  "exam.setupDescription": `Detta är en övningssimulering byggd från den här appens studiefrågor. Det är inte det officiella testet och förutsäger inte ditt resultat.`,
  "exam.setupTitle": `Ställ in ditt skenprov`,
  "exam.simulationNote": `Öva simulering · inte officiellt`,
  "exam.startExam": `Starta tentamen`,
  "exam.timeLeft": `Tid kvar`,
  "exam.timedLabel": `tidsinställd`,
  "exam.timedToggle": `Tidsbestämd (90 sekunder per fråga)`,
  "exam.title": `Spotprov`,
  "exam.topicFilter": `Ämne`,
  "exam.untimedLabel": `otidsbestämd`,
  "footer.disclaimer": `Citizen Prep är ett oberoende studiehjälpmedel. Ej ansluten till eller godkänd av Kanadas regering eller IRCC. Det kan inte garantera ett godkänt resultat.`,
  "header.appName": `Citizen Prep`,
  "header.tagline": `Oberoende studieverktyg · Ej officiellt`,
  "hero.sectionsProgress": `{done} of {total} sections · {percent}% complete`,
  "hero.subtitle": `Oberoende studieverktyg · Engelska och franska · inget konto behövs`,
  "hero.title": `Förbered dig för ditt medborgarskapstest`,
  "nav.exam": `Examen`,
  "nav.home": `Hem`,
  "nav.practice": `Öva`,
  "nav.progress": `Framsteg`,
  "nav.topics": `Ämnen`,
  "practice.allLevels": `Alla nivåer`,
  "practice.allTopics": `Alla ämnen`,
  "practice.askAiAbout": `Fråga AI om denna fråga`,
  "practice.bookmarkQuestion": `Bokmärk fråga`,
  "practice.bookmarked": `Bokmärkt`,
  "practice.checkAnswer": `Kontrollera svaret`,
  "practice.correct": `Rätt`,
  "practice.demoContent": `Demoinnehåll`,
  "practice.difficulty": `Svårighet`,
  "practice.easy": `Lätt`,
  "practice.explanation": `Förklaring`,
  "practice.filters": `Filter`,
  "practice.hard": `Hårt`,
  "practice.incorrect": `Inte riktigt`,
  "practice.medium": `Medium`,
  "practice.nextQuestion": `Nästa fråga`,
  "practice.questionCounter": `Öva fråga {n} av {total}`,
  "practice.reportIssue": `Rapportera ett problem`,
  "practice.title": `Öva`,
  "practice.topicFilter": `Ämne`,
  "practice.tryAgain": `Försök igen`,
  "progress.accuracy": `Noggrannhet`,
  "progress.clearProgressDesc": `Detta raderar dina svar, slutföranden, bokmärken och examenshistorik från den här enheten. Det går inte att ångra.`,
  "progress.clearProgressLabel": `Rensa alla studieframsteg`,
  "progress.confirmClear": `Ja, rensa allt`,
  "progress.dailyGoal": `Dagligt mål`,
  "progress.details": `Detaljer`,
  "progress.examHistory": `Tentamens historia`,
  "progress.noExams": `Inga prov avlagda ännu.`,
  "progress.noWrongAnswers": `Inga felaktiga svar att granska just nu.`,
  "progress.overview": `Översikt`,
  "progress.perTopic": `Per ämne`,
  "progress.questionsAnswered": `Frågor besvarade`,
  "progress.reset": `Återställ`,
  "progress.retryTopic": `Försök med det här ämnet igen`,
  "progress.sectionsDone": `Avsnitt färdiga`,
  "progress.suggestedNext": `Nästa förslag: {topic}`,
  "progress.title": `Framsteg`,
  "progress.topicCompletion": `Ämnesavslut`,
  "report.detailsPlaceholder": `Berätta mer (valfritt)`,
  "report.incorrectAnswer": `Felaktigt svar`,
  "report.outdatedInfo": `Föråldrad information`,
  "report.submit": `Lämna rapport`,
  "report.technicalIssue": `Tekniskt problem`,
  "report.thanks": `Tack – rapporter lagras lokalt på den här enheten.`,
  "report.translationProblem": `Översättningsproblem`,
  "report.unclearExplanation": `Förklaring peu claire`,
  "settings.about": `Om den här appen`,
  "settings.appInterfaceLanguage": `Appens gränssnittsspråk`,
  "settings.clearProgress": `Tydliga framsteg`,
  "settings.clearProgressConfirm": `Är du säker? Detta kommer att radera alla dina framsteg.`,
  "settings.interfaceDescription": `Menyer, knappar och navigering.`,
  "settings.language": `Språk`,
  "settings.machineNote": `Maskinöversatt innehåll har inte kontrollerats av en mänsklig granskare. Inget här är märkt som granskat om det inte faktiskt har granskats.`,
  "settings.machineTranslatedBadge": `Maskinöversatt`,
  "settings.manageProgress": `Hantera dina framstegsdata`,
  "settings.notAvailable": `Inte tillgänglig ännu`,
  "settings.officialGuideLink": `Officiell studieguide`,
  "settings.officialTestLink": `Officiell information om medborgarskapstest`,
  "settings.privacy": `Sekretess`,
  "settings.privacyText": `Dina svar, bokmärken och inställningar lagras endast på den här enheten. Inget konto behövs. Frågor du ställer till studieassistenten skickas till en AI-tjänst för att generera svar.`,
  "settings.reviewedBadge": `Recenserad`,
  "settings.studyContentLanguage": `Studera innehållsspråk`,
  "settings.studyDescription": `Lärande text och förklaringar. Du kan läsa på ett språk medan du navigerar på ett annat.`,
  "settings.textSize": `Textstorlek`,
  "settings.title": `Inställningar`,
  "topics.askAssistant": `Fråga assistenten om detta avsnitt`,
  "topics.bookmarkSection": `Bokmärkesektion`,
  "topics.bookmarkedSection": `Bokmärkt`,
  "topics.completed": `Avslutad`,
  "topics.continueLearningCard": `Fortsätt lära dig`,
  "topics.demoSourceNote": `Ursprunglig exempelfråga – inte en officiell provfråga`,
  "topics.lastVerified": `Senast verifierad {date}`,
  "topics.markComplete": `Markera som komplett`,
  "topics.markIncomplete": `Markera som ofullständig`,
  "topics.minRead": `{n} min läst`,
  "topics.next": `Nästa`,
  "topics.openOfficialPage": `Öppna den officiella sidan`,
  "topics.paraphrasedSourceNote": `Omskrivning från officiellt material`,
  "topics.practiceTopic": `Öva på detta ämne`,
  "topics.previous": `Föregående`,
  "topics.reportIssue": `Rapportera ett problem`,
  "topics.reviewedOn": `recenserade {date}`,
  "topics.reviewedTranslation": `Granskad översättning`,
  "topics.section": `avsnitt`,
  "topics.sections": `sektioner`,
  "topics.source": `Källa`,
  "topics.sourcesDescription": `Studietexten här är omskriven från studieguiden för Kanadas regering medborgarskap och granskas på de datum som visas. Övningsfrågor undersöks från den officiella studieguiden.`,
  "topics.sourcesHeading": `Innehållskällor och recensionsdatum`,
  "topics.studyLanguageLabel": `Studera innehållsspråk`,
  "topics.title": `Studieämnen`,
  "topics.vocabulary": `Ordförråd`,
};
