// UI strings for 'tr' — chunk of strings.generated.ts. DO NOT EDIT BY HAND.
import type { StringKey } from "../strings.generated";

export const tr: Record<StringKey, string> = {
  "actions.askAi": `Yapay zekaya sor`,
  "actions.mockExam": `Deneme sınavı`,
  "actions.practice": `Alıştırma`,
  "actions.quickActions": `Quick actions`,
  "actions.study": `çalışma`,
  "assistant.aiEyebrow": `Yapay zeka çalışma asistanı`,
  "assistant.answerLanguage": `Cevap dili`,
  "assistant.charLimit": `{n} karakter kaldı`,
  "assistant.checkingMaterial": `Çalışma materyali kontrol ediliyor…`,
  "assistant.clearChat": `Sohbeti temizle`,
  "assistant.copied": `Kopyalandı`,
  "assistant.copy": `Kopyala`,
  "assistant.description": `Yanıtlar yapay zeka tarafından yalnızca bu uygulamanın çalışma materyali kullanılarak ve kaynaklar gösterilerek yazılır. Yapay zeka hâlâ hata yapabilir; önemli ayrıntıları Kanada Hükümeti'nin resmi sayfalarından kontrol edin. Yasal veya göçmenlik tavsiyesi değildir.`,
  "assistant.enFrancais": `Fransızca`,
  "assistant.error": `Bir şeyler ters gitti. Lütfen tekrar deneyin.`,
  "assistant.fromAppContent": `Onaylanmış uygulama içeriğinden`,
  "assistant.groundedBadge": `Kaynak temelli`,
  "assistant.helpful": `yararlı`,
  "assistant.inputPlaceholder": `Kanada vatandaşlığı hakkında bir soru sorun…`,
  "assistant.myAppLanguage": `Uygulamamın dili`,
  "assistant.notCovered": `Kapsam dışı - resmi sayfaya bakın`,
  "assistant.notHelpful": `Yararlı değil`,
  "assistant.openAssistant": `Açık çalışma asistanı`,
  "assistant.openLink": `Asistanı aç`,
  "assistant.practiceThis": `Bunu uygula`,
  "assistant.questionAriaLabel": `Sorunuz`,
  "assistant.reportIncorrect": `Yanlış yanıtı bildirin`,
  "assistant.send": `Gönder`,
  "assistant.showSource": `Kaynağı göster`,
  "assistant.simpleEnglish": `Basit İngilizce`,
  "assistant.source": `Kaynak`,
  "assistant.starter1": `Parlamentonun üç kısmı nelerdir?`,
  "assistant.starter2": `Şartı basitçe açıklayın`,
  "assistant.starter3": `Kanada'da Kralı kim temsil ediyor?`,
  "assistant.starter4": `Bilgi testi neleri kapsar?`,
  "assistant.suggestedQuestions": `Önerilen sorular`,
  "assistant.thinking": `Düşünüyorum…`,
  "assistant.title": `Çalışma asistanı`,
  "assistant.tryAgain": `Tekrar dene`,
  "assistant.tryAsking": `Şunu sormayı deneyin:`,
  "assistant.vocabularyLabel": `Kelime Bilgisi:`,
  "assistant.whyItMatters": `Test için neden önemlidir?`,
  "bookmarks.continueStudying": `Çalışmaya devam et`,
  "bookmarks.empty": `Henüz yer işareti yok. İncelenmek üzere kaydetmek için herhangi bir sorudaki yıldıza dokunun.`,
  "bookmarks.emptyQuestions": `Henüz hiçbir şey kaydedilmedi. Bir alıştırma sorusunda ☆ simgesine dokunun.`,
  "bookmarks.emptySections": `Henüz hiçbir şey kaydedilmedi. Bir bölümü okurken ☆ simgesine dokunun.`,
  "bookmarks.remove": `Kaldır`,
  "bookmarks.savedForReview": `incelenmek üzere kaydedildi`,
  "bookmarks.savedQuestions": `Kayıtlı sorular ({n})`,
  "bookmarks.savedSections": `Kaydedilen bölümler ({n})`,
  "bookmarks.search": `Yer imlerinde ara…`,
  "bookmarks.title": `Yer imleri`,
  "cards.answered": `Yanıtlandı`,
  "cards.bookmarks": `incelenmek üzere kaydedildi`,
  "cards.bookmarksLabel": `Yer imleri`,
  "cards.continueLearning": `Öğrenmeye devam et`,
  "cards.correct": `Doğru`,
  "cards.dailyGoal": `Bugün {done}/{total} soru`,
  "cards.dailyGoalLabel": `Günlük hedef`,
  "cards.dailyGoalTitle": `Daily goal`,
  "cards.mockExam.subtitle": `Süreli · 20 soru`,
  "cards.mockExam.title": `Deneme sınavı`,
  "cards.officialInfo.button": `Canada.ca'yı açın`,
  "cards.officialInfo.subtitle": `Resmi ayrıntılar için canada.ca adresini ziyaret edin`,
  "cards.officialInfo.title": `Resmi bilgi`,
  "cards.progress": `İlerleme`,
  "cards.progressDetails": `Ayrıntılar`,
  "cards.recentlyStudied": `Son zamanlarda çalışılan`,
  "cards.sections": `Bölümler`,
  "cards.studyAssistant.subtitle": `Çalışma materyali hakkında herhangi bir şey sorun`,
  "cards.studyAssistant.title": `Çalışma asistanı`,
  "cards.todaysRecommendation": `Bugünün tavsiyesi`,
  "cards.verifiedSource.subtext": `İçerik resmi kaynaklara göre kontrol edildi. Bağımsız çalışma yardımı - Kanada Hükümeti veya IRCC ile bağlantısı yoktur veya bunlar tarafından desteklenmez.`,
  "cards.verifiedSource.title": `Doğrulanmış kaynak`,
  "common.back": `Geri`,
  "common.cancel": `İptal`,
  "common.close": `Kapat`,
  "common.continue": `Devam et`,
  "common.done": `Bitti`,
  "common.emptyBookmarks": `Henüz kaydedilen bir şey yok`,
  "common.emptyRecentlyStudied": `Henüz üzerinde çalışılan bir şey yok; başlamak için bir konu seçin.`,
  "common.loading": `Yükleniyor…`,
  "common.next": `Sonraki`,
  "common.of": `arasında`,
  "common.previous": `Önceki`,
  "common.retry": `Yeniden dene`,
  "common.save": `Kaydet`,
  "exam.allTopics": `Tüm konular`,
  "exam.answeredCount": `{n} yanıtladı`,
  "exam.autosaveNote": `Yanıtlarınız siz ilerledikçe kaydedilir, bu nedenle uygulamayı kapatmak ilerlemenizi kaybetmez.`,
  "exam.cancel": `İptal`,
  "exam.confirm": `Onayla`,
  "exam.confirmEnd": `{n} soru yanıtsız ve hatalı olarak işaretlenecek.`,
  "exam.confirmEndTitle": `Sınavın sonu mu?`,
  "exam.endExamEarly": `Sınavı erken bitirin`,
  "exam.examDisclaimer": `Bu puan yalnızca bu uygulamanın örnek sorularını yansıtır.`,
  "exam.finishExam": `Sınavı bitir`,
  "exam.newExam": `Yeni sınav`,
  "exam.noMistakes": `Hata yok - mükemmel puan!`,
  "exam.pastAttempts": `Geçmiş denemeler`,
  "exam.questionAriaLabel": `Soru {n}`,
  "exam.questionCount": `Soru sayısı`,
  "exam.questionOf": `{total} sorudan {n}. soru`,
  "exam.questionPalette": `Sorular`,
  "exam.questionsOption": `{n} soru`,
  "exam.resultsTitle": `Puanınız`,
  "exam.reviewMistakes": `Hatalarınızı gözden geçirin ({n})`,
  "exam.scoreLine": `{correct} of {total} correct`,
  "exam.seeProgress": `İlerlemeyi görün`,
  "exam.setupDescription": `Bu, uygulamanın çalışma sorularından oluşturulmuş bir pratik simülasyonudur. Bu resmi bir test değildir ve sonucunuzu tahmin etmez.`,
  "exam.setupTitle": `Deneme sınavınızı ayarlayın`,
  "exam.simulationNote": `Simülasyon alıştırması · resmi değil`,
  "exam.startExam": `Sınavı başlat`,
  "exam.timeLeft": `Kalan süre`,
  "exam.timedLabel": `zamanlı`,
  "exam.timedToggle": `Süreli (soru başına 90 saniye)`,
  "exam.title": `Deneme sınavı`,
  "exam.topicFilter": `Konu`,
  "exam.untimedLabel": `zamansız`,
  "footer.disclaimer": `Citizen Prep bağımsız bir çalışma yardımcısıdır. Kanada Hükümeti veya IRCC'ye bağlı değildir veya bunlar tarafından desteklenmemektedir. Geçer bir sonucu garanti edemez.`,
  "header.appName": `Vatandaş Hazırlığı`,
  "header.tagline": `Bağımsız çalışma aracı · Resmi değil`,
  "hero.sectionsProgress": `{done} of {total} sections · {percent}% complete`,
  "hero.subtitle": `Bağımsız çalışma aracı · İngilizce ve Fransızca · hesaba gerek yok`,
  "hero.title": `Vatandaşlık sınavına hazırlanın`,
  "nav.exam": `Sınav`,
  "nav.home": `Ana sayfa`,
  "nav.practice": `Alıştırma`,
  "nav.progress": `İlerleme`,
  "nav.topics": `Konular`,
  "practice.allLevels": `Tüm seviyeler`,
  "practice.allTopics": `Tüm konular`,
  "practice.askAiAbout": `Yapay zekaya bu soruyu sorun`,
  "practice.bookmarkQuestion": `Yer işareti sorusu`,
  "practice.bookmarked": `Favorilere eklendi`,
  "practice.checkAnswer": `Cevabı kontrol et`,
  "practice.correct": `Doğru`,
  "practice.demoContent": `Demo içeriği`,
  "practice.difficulty": `Zorluk`,
  "practice.easy": `Kolay`,
  "practice.explanation": `Açıklama`,
  "practice.filters": `Filtreler`,
  "practice.hard": `Sert`,
  "practice.incorrect": `Pek değil`,
  "practice.medium": `Orta`,
  "practice.nextQuestion": `Sonraki soru`,
  "practice.questionCounter": `{total} sorudan {n} numaralı alıştırma sorusu`,
  "practice.reportIssue": `Bir sorunu bildirin`,
  "practice.title": `Alıştırma`,
  "practice.topicFilter": `Konu`,
  "practice.tryAgain": `Tekrar dene`,
  "progress.accuracy": `doğruluk`,
  "progress.clearProgressDesc": `Bu işlem, yanıtlarınızı, tamamlamalarınızı, yer işaretlerinizi ve sınav geçmişinizi bu cihazdan siler. Bu işlem geri alınamaz.`,
  "progress.clearProgressLabel": `Tüm çalışma ilerlemesini temizle`,
  "progress.confirmClear": `Evet, her şeyi temizle`,
  "progress.dailyGoal": `Günlük hedef`,
  "progress.details": `Ayrıntılar`,
  "progress.examHistory": `Sınav geçmişi`,
  "progress.noExams": `Henüz sınav yapılmadı.`,
  "progress.noWrongAnswers": `Şu anda incelenecek yanlış yanıt yok.`,
  "progress.overview": `Genel Bakış`,
  "progress.perTopic": `Konu başına`,
  "progress.questionsAnswered": `Cevaplanan sorular`,
  "progress.reset": `Sıfırla`,
  "progress.retryTopic": `Bu konuyu yeniden dene`,
  "progress.sectionsDone": `Tamamlanan bölümler`,
  "progress.suggestedNext": `Sonraki önerilen: {topic}`,
  "progress.title": `İlerleme`,
  "progress.topicCompletion": `Konu tamamlama`,
  "report.detailsPlaceholder": `Bize daha fazlasını anlatın (isteğe bağlı)`,
  "report.incorrectAnswer": `Yanlış cevap`,
  "report.outdatedInfo": `Güncel olmayan bilgiler`,
  "report.submit": `Raporu gönder`,
  "report.technicalIssue": `Teknik sorun`,
  "report.thanks": `Teşekkürler — raporlar bu cihazda yerel olarak depolanıyor.`,
  "report.translationProblem": `Çeviri sorunu`,
  "report.unclearExplanation": `Açıklama peu claire`,
  "settings.about": `Bu uygulama hakkında`,
  "settings.appInterfaceLanguage": `Uygulama arayüzü dili`,
  "settings.clearProgress": `İlerlemeyi temizle`,
  "settings.clearProgressConfirm": `Emin misin? Bu, tüm ilerlemenizi silecektir.`,
  "settings.interfaceDescription": `Menüler, düğmeler ve gezinme.`,
  "settings.language": `Dil`,
  "settings.machineNote": `Makineyle çevrilmiş içerik, gerçek bir incelemeci tarafından kontrol edilmemiştir. Buradaki hiçbir şey, gerçekten incelenmediği sürece, incelenmiş olarak etiketlenmez.`,
  "settings.machineTranslatedBadge": `Makine çevirisi`,
  "settings.manageProgress": `İlerleme verilerinizi yönetin`,
  "settings.notAvailable": `Henüz mevcut değil`,
  "settings.officialGuideLink": `Resmi çalışma kılavuzu`,
  "settings.officialTestLink": `Resmi vatandaşlık testi bilgileri`,
  "settings.privacy": `Gizlilik`,
  "settings.privacyText": `Yanıtlarınız, yer işaretleriniz ve ayarlarınız yalnızca bu cihazda saklanır. Hiçbir hesaba gerek yoktur. Çalışma asistanına sorduğunuz sorular, yanıtların üretilmesi için bir yapay zeka hizmetine gönderilir.`,
  "settings.reviewedBadge": `İncelendi`,
  "settings.studyContentLanguage": `İçerik dilini inceleyin`,
  "settings.studyDescription": `Metin ve açıklamaları öğrenme. Bir dilde gezinirken başka bir dilde okuyabilirsiniz.`,
  "settings.textSize": `Metin boyutu`,
  "settings.title": `Ayarlar`,
  "topics.askAssistant": `Asistana bu bölümü sorun`,
  "topics.bookmarkSection": `Yer imi bölümü`,
  "topics.bookmarkedSection": `Favorilere eklendi`,
  "topics.completed": `Tamamlandı`,
  "topics.continueLearningCard": `Öğrenmeye devam et`,
  "topics.demoSourceNote": `Orijinal örnek soru — resmi bir sınav sorusu değil`,
  "topics.lastVerified": `Son doğrulanan {date}`,
  "topics.markComplete": `Tamamlandı olarak işaretle`,
  "topics.markIncomplete": `Eksik olarak işaretle`,
  "topics.minRead": `{n} dk. okuma`,
  "topics.next": `Sonraki`,
  "topics.openOfficialPage": `Resmi sayfayı aç`,
  "topics.paraphrasedSourceNote": `Resmi materyalden alıntılanmıştır`,
  "topics.practiceTopic": `Bu konuyu uygulayın`,
  "topics.previous": `Önceki`,
  "topics.reportIssue": `Bir sorunu bildirin`,
  "topics.reviewedOn": `{date} incelendi`,
  "topics.reviewedTranslation": `İncelenen çeviri`,
  "topics.section": `Bölüm`,
  "topics.sections": `bölümler`,
  "topics.source": `Kaynak`,
  "topics.sourcesDescription": `Buradaki çalışma metni Kanada Hükümeti vatandaşlık çalışma kılavuzundan alıntılanmıştır ve gösterilen tarihlerde gözden geçirilmiştir. Pratik sorular resmi çalışma kılavuzundan araştırılır.`,
  "topics.sourcesHeading": `İçerik kaynakları ve inceleme tarihleri`,
  "topics.studyLanguageLabel": `İçerik dilini inceleyin`,
  "topics.title": `Çalışma konuları`,
  "topics.vocabulary": `Kelime Bilgisi`,
};
