// UI strings for 'uk' — chunk of strings.generated.ts. DO NOT EDIT BY HAND.
import type { StringKey } from "../strings.generated";

export const uk: Record<StringKey, string> = {
  "actions.askAi": `Запитайте AI`,
  "actions.mockExam": `Пробний іспит`,
  "actions.practice": `Практика`,
  "actions.quickActions": `Quick actions`,
  "actions.study": `дослідження`,
  "assistant.aiEyebrow": `Асистент з вивчення ШІ`,
  "assistant.answerLanguage": `Мова відповіді`,
  "assistant.charLimit": `Залишилося {n} символів`,
  "assistant.checkingMaterial": `Перевірка навчального матеріалу…`,
  "assistant.clearChat": `Очистити чат`,
  "assistant.copied": `Скопійовано`,
  "assistant.copy": `Копія`,
  "assistant.description": `Відповіді написані штучним інтелектом, використовуючи лише навчальний матеріал цієї програми з указанням джерел. ШІ все ще може помилятися — перевірте важливі деталі на офіційних сторінках уряду Канади. Не юридичні чи імміграційні поради.`,
  "assistant.enFrancais": `En français`,
  "assistant.error": `Щось пішло не так. Спробуйте ще раз.`,
  "assistant.fromAppContent": `Із схваленого вмісту програми`,
  "assistant.groundedBadge": `Обґрунтований джерелом`,
  "assistant.helpful": `корисно`,
  "assistant.inputPlaceholder": `Задайте питання про громадянство Канади...`,
  "assistant.myAppLanguage": `Мова моєї програми`,
  "assistant.notCovered": `Не охоплено — див. офіційну сторінку`,
  "assistant.notHelpful": `Не допомагає`,
  "assistant.openAssistant": `Відкритий навчальний помічник`,
  "assistant.openLink": `Відкрити помічника`,
  "assistant.practiceThis": `Практикуйте це`,
  "assistant.questionAriaLabel": `Ваше запитання`,
  "assistant.reportIncorrect": `Повідомити про неправильну відповідь`,
  "assistant.send": `Надіслати`,
  "assistant.showSource": `Показати джерело`,
  "assistant.simpleEnglish": `Проста англійська`,
  "assistant.source": `Джерело`,
  "assistant.starter1": `З яких трьох частин складається парламент?`,
  "assistant.starter2": `Поясніть Статут просто`,
  "assistant.starter3": `Хто представляє короля в Канаді?`,
  "assistant.starter4": `Що включає перевірка знань?`,
  "assistant.suggestedQuestions": `Запропоновані питання`,
  "assistant.thinking": `Думаючи…`,
  "assistant.title": `Навчальний помічник`,
  "assistant.tryAgain": `Спробуйте знову`,
  "assistant.tryAsking": `Спробуйте запитати:`,
  "assistant.vocabularyLabel": `Словниковий запас:`,
  "assistant.whyItMatters": `Чому це важливо для тесту`,
  "auth.account": `Account`,
  "auth.checkEmail": `Check your email to confirm your account, then sign in.`,
  "auth.close": `Close`,
  "auth.codeLabel": `Verification code`,
  "auth.codeResent": `New code sent. Check your email.`,
  "auth.codeSent": `Code sent! Check your email and enter the 6-digit code.`,
  "auth.createAccount": `Create account`,
  "auth.dataDeletedMsg": `Your progress and profile data were deleted.`,
  "auth.deleteConfirm": `Tap again to permanently delete`,
  "auth.deleteData": `Delete my data`,
  "auth.email": `Email`,
  "auth.haveAccount": `Already have an account?`,
  "auth.mfaCodeLabel": `Authenticator code`,
  "auth.mfaDisable": `Disable 2FA`,
  "auth.mfaDisabledMsg": `Two-factor authentication is now OFF.`,
  "auth.mfaEnable": `Enable 2FA`,
  "auth.mfaEnabledMsg": `Two-factor authentication is now ON for your account.`,
  "auth.mfaPendingWarn": `2FA code still needed to finish signing in.`,
  "auth.mfaPrompt": `This account uses 2FA — enter the code from your authenticator app.`,
  "auth.mfaScanHint": `Scan this QR code with your authenticator app (Google Authenticator, Authy, 1Password…), then enter the 6-digit code it shows.`,
  "auth.mfaSetupTitle": `Set up two-factor authentication`,
  "auth.mfaSubtitle": `Enter the 6-digit code from your authenticator app.`,
  "auth.mfaTitle": `Two-factor authentication`,
  "auth.noAccount": `Don't have an account?`,
  "auth.password": `Password`,
  "auth.passwordHint": `At least 6 characters`,
  "auth.privacy": `Privacy`,
  "auth.privacyNote": `Your email and progress are private — only you can see them.`,
  "auth.resendCode": `Resend code`,
  "auth.security": `Security`,
  "auth.signIn": `Sign in`,
  "auth.signOut": `Sign out`,
  "auth.signUp": `Sign up`,
  "auth.subtitle": `Save your progress across devices. Your data stays private.`,
  "auth.title": `Account`,
  "auth.verify": `Verify`,
  "auth.verifyCodeSubtitle": `We sent a 6-digit code to your email. Enter it below to finish signing up.`,
  "auth.verifyCodeTitle": `Enter your code`,
  "auth.working": `Please wait…`,
  "bookmarks.continueStudying": `Продовжуйте навчання`,
  "bookmarks.empty": `Закладок ще немає. Торкніться зірочки будь-якого запитання, щоб зберегти його для перегляду.`,
  "bookmarks.emptyQuestions": `Ще нічого не збережено. Натисніть ☆ на практичне запитання.`,
  "bookmarks.emptySections": `Ще нічого не збережено. Торкніться ☆ під час читання розділу.`,
  "bookmarks.remove": `видалити`,
  "bookmarks.savedForReview": `збережено для перегляду`,
  "bookmarks.savedQuestions": `Збережені запитання ({n})`,
  "bookmarks.savedSections": `Збережені розділи ({n})`,
  "bookmarks.search": `Пошук закладок…`,
  "bookmarks.title": `Закладки`,
  "cards.answered": `відповів`,
  "cards.bookmarks": `збережено для перегляду`,
  "cards.bookmarksLabel": `Закладки`,
  "cards.continueLearning": `Продовжуйте навчання`,
  "cards.correct": `Правильно`,
  "cards.dailyGoal": `{done}/{total} запитань сьогодні`,
  "cards.dailyGoalLabel": `Щоденна мета`,
  "cards.dailyGoalTitle": `Daily goal`,
  "cards.mockExam.subtitle": `На час · 20 питань`,
  "cards.mockExam.title": `Пробний іспит`,
  "cards.officialInfo.button": `Відкрийте canada.ca`,
  "cards.officialInfo.subtitle": `Відвідайте canada.ca, щоб отримати офіційну інформацію`,
  "cards.officialInfo.title": `Офіційна інформація`,
  "cards.progress": `Прогрес`,
  "cards.progressDetails": `Подробиці`,
  "cards.recentlyStudied": `Нещодавно вивчав`,
  "cards.sections": `Розділи`,
  "cards.studyAssistant.subtitle": `Запитайте будь-що про навчальний матеріал`,
  "cards.studyAssistant.title": `Навчальний помічник`,
  "cards.todaysRecommendation": `Сьогоднішня рекомендація`,
  "cards.verifiedSource.subtext": `Вміст перевірено з офіційних джерел. Незалежний навчальний посібник — не пов’язаний і не схвалений урядом Канади чи IRCC.`,
  "cards.verifiedSource.title": `Перевірене джерело`,
  "common.back": `Назад`,
  "common.cancel": `Скасувати`,
  "common.close": `Закрити`,
  "common.continue": `Продовжити`,
  "common.done": `Готово`,
  "common.emptyBookmarks": `Ще нічого не збережено`,
  "common.emptyRecentlyStudied": `Ще нічого не вивчено — виберіть тему для початку.`,
  "common.loading": `Завантаження…`,
  "common.next": `Далі`,
  "common.of": `з`,
  "common.previous": `Попередній`,
  "common.retry": `Повторіть спробу`,
  "common.save": `зберегти`,
  "exam.allTopics": `Всі теми`,
  "exam.answeredCount": `{n} відповів`,
  "exam.autosaveNote": `Ваші відповіді зберігаються під час роботи, тож закриття програми не призведе до втрати прогресу.`,
  "exam.cancel": `Скасувати`,
  "exam.confirm": `Підтвердити`,
  "exam.confirmEnd": `{n} запитань не мають відповіді та будуть позначені як неправильні.`,
  "exam.confirmEndTitle": `Завершити іспит?`,
  "exam.endExamEarly": `Закінчити іспит раніше`,
  "exam.examDisclaimer": `Ця оцінка відображає лише приклади запитань цієї програми.`,
  "exam.finishExam": `Завершити іспит`,
  "exam.newExam": `Новий іспит`,
  "exam.noMistakes": `Жодної помилки — відмінний результат!`,
  "exam.pastAttempts": `Минулі спроби`,
  "exam.questionAriaLabel": `Питання {n}`,
  "exam.questionCount": `Кількість питань`,
  "exam.questionOf": `Питання {n} із {total}`,
  "exam.questionPalette": `Питання`,
  "exam.questionsOption": `{n} запитань`,
  "exam.resultsTitle": `Ваш рахунок`,
  "exam.reviewMistakes": `Перегляньте свої помилки ({n})`,
  "exam.scoreLine": `{correct} із {total} правильних`,
  "exam.seeProgress": `Перегляньте прогрес`,
  "exam.setupDescription": `Це практичне моделювання, створене на основі навчальних питань цієї програми. Це не офіційний тест і не передбачає ваш результат.`,
  "exam.setupTitle": `Налаштуйте свій пробний іспит`,
  "exam.simulationNote": `Симуляція практики · не офіційно`,
  "exam.startExam": `Розпочати іспит`,
  "exam.timeLeft": `Час залишився`,
  "exam.timedLabel": `за часом`,
  "exam.timedToggle": `Час (90 секунд на запитання)`,
  "exam.title": `Пробний іспит`,
  "exam.topicFilter": `Тема`,
  "exam.untimedLabel": `нетермінований`,
  "footer.disclaimer": `Citizen Prep — це незалежний навчальний посібник. Не афілійовано та не схвалено урядом Канади чи IRCC. Це не може гарантувати прохідний результат.`,
  "header.appName": `Citizen Prep`,
  "header.tagline": `Інструмент незалежного навчання · Неофіційний`,
  "hero.sectionsProgress": `{done} of {total} sections · {percent}% complete`,
  "hero.subtitle": `Інструмент незалежного навчання · англійська та французька · обліковий запис не потрібен`,
  "hero.title": `Підготуйтеся до іспиту на громадянство`,
  "nav.exam": `екзамен`,
  "nav.home": `додому`,
  "nav.practice": `Практика`,
  "nav.progress": `Прогрес`,
  "nav.topics": `Теми`,
  "practice.allLevels": `Всі рівні`,
  "practice.allTopics": `Всі теми`,
  "practice.askAiAbout": `Запитайте AI про це питання`,
  "practice.bookmarkQuestion": `Закладка питання`,
  "practice.bookmarked": `Додано в закладки`,
  "practice.checkAnswer": `Перевірте відповідь`,
  "practice.correct": `Правильно`,
  "practice.demoContent": `Демо-контент`,
  "practice.difficulty": `Складність`,
  "practice.easy": `легко`,
  "practice.explanation": `Пояснення`,
  "practice.filters": `Фільтри`,
  "practice.hard": `важко`,
  "practice.incorrect": `Не зовсім`,
  "practice.medium": `Середній`,
  "practice.nextQuestion": `Наступне питання`,
  "practice.questionCounter": `Тренувальне запитання {n} із {total}`,
  "practice.reportIssue": `Повідомити про проблему`,
  "practice.title": `Практика`,
  "practice.topicFilter": `Тема`,
  "practice.tryAgain": `Спробуйте знову`,
  "progress.accuracy": `Точність`,
  "progress.clearProgressDesc": `Ваші відповіді, завершення, закладки та історію іспитів буде видалено з цього пристрою. Це не можна скасувати.`,
  "progress.clearProgressLabel": `Очистити весь прогрес навчання`,
  "progress.confirmClear": `Так, ясно все`,
  "progress.dailyGoal": `Щоденна мета`,
  "progress.details": `Подробиці`,
  "progress.examHistory": `Історія іспитів`,
  "progress.noExams": `Іспитів ще не складено.`,
  "progress.noWrongAnswers": `Зараз немає неправильних відповідей для перегляду.`,
  "progress.overview": `Огляд`,
  "progress.perTopic": `За темою`,
  "progress.questionsAnswered": `Відповіді на запитання`,
  "progress.reset": `Скинути`,
  "progress.retryTopic": `Повторіть цю тему`,
  "progress.sectionsDone": `Розділи завершено`,
  "progress.suggestedNext": `Пропонований наступний: {topic}`,
  "progress.title": `Прогрес`,
  "progress.topicCompletion": `Завершення теми`,
  "report.detailsPlaceholder": `Розкажіть нам більше (необов'язково)`,
  "report.incorrectAnswer": `Неправильна відповідь`,
  "report.outdatedInfo": `Застаріла інформація`,
  "report.submit": `Здати звіт`,
  "report.technicalIssue": `Технічне питання`,
  "report.thanks": `Дякуємо — звіти зберігаються локально на цьому пристрої.`,
  "report.translationProblem": `Проблема перекладу`,
  "report.unclearExplanation": `Пояснення peu claire`,
  "settings.about": `Про цю програму`,
  "settings.appInterfaceLanguage": `Мова інтерфейсу програми`,
  "settings.clearProgress": `Явний прогрес`,
  "settings.clearProgressConfirm": `Ви впевнені? Це видалить усі ваші досягнення.`,
  "settings.interfaceDescription": `Меню, кнопки та навігація.`,
  "settings.language": `Мова`,
  "settings.machineNote": `Перекладений машиною вміст не перевірявся рецензентом. Ніщо тут не позначено як перевірене, якщо воно насправді не перевірено.`,
  "settings.machineTranslatedBadge": `Машинний переклад`,
  "settings.manageProgress": `Керуйте своїми даними про прогрес`,
  "settings.notAvailable": `Ще не доступний`,
  "settings.officialGuideLink": `Офіційний навчальний посібник`,
  "settings.officialTestLink": `Інформація про офіційний тест на громадянство`,
  "settings.privacy": `Конфіденційність`,
  "settings.privacyText": `Ваші відповіді, закладки та налаштування зберігаються лише на цьому пристрої. Обліковий запис не потрібен. Запитання, які ви ставите асистенту, надсилаються до служби ШІ для отримання відповідей.`,
  "settings.reviewedBadge": `Переглянуто`,
  "settings.studyContentLanguage": `Вивчайте мову змісту`,
  "settings.studyDescription": `Розучування тексту та пояснення. Ви можете читати однією мовою, а навігацію – іншою.`,
  "settings.textSize": `Розмір тексту`,
  "settings.title": `Налаштування`,
  "topics.askAssistant": `Запитайте помічника про цей розділ`,
  "topics.bookmarkSection": `Розділ закладок`,
  "topics.bookmarkedSection": `Додано в закладки`,
  "topics.completed": `Виконано`,
  "topics.continueLearningCard": `Продовжуйте навчання`,
  "topics.demoSourceNote": `Оригінальний зразок запитання — не є офіційним іспитовим запитанням`,
  "topics.lastVerified": `Востаннє перевірено {date}`,
  "topics.markComplete": `Позначити як завершене`,
  "topics.markIncomplete": `Позначити як незавершене`,
  "topics.minRead": `{n} хв читання`,
  "topics.next": `Далі`,
  "topics.openOfficialPage": `Відкрити офіційну сторінку`,
  "topics.paraphrasedSourceNote": `Перефраз з офіційних матеріалів`,
  "topics.practiceTopic": `Практикуйте цю тему`,
  "topics.previous": `Попередній`,
  "topics.reportIssue": `Повідомити про проблему`,
  "topics.reviewedOn": `reviewed {date}`,
  "topics.reviewedTranslation": `Рецензований переклад`,
  "topics.section": `Розділ`,
  "topics.sections": `розділи`,
  "topics.source": `Джерело`,
  "topics.sourcesDescription": `Навчальний текст тут перефразовано з навчального посібника з питань громадянства Уряду Канади та переглянуто у вказані дати. Практичні питання досліджуються з офіційного навчального посібника.`,
  "topics.sourcesHeading": `Джерела вмісту та дати перегляду`,
  "topics.studyLanguageLabel": `Вивчайте мову змісту`,
  "topics.title": `Теми вивчення`,
  "topics.vocabulary": `Словниковий запас`,
};
